### ISSUE TITLE
502 bad gateway when I create or remove a server account. cPanel server.

### ISSUE THREAD

**Issue by marceloalmeida33** [engintron/engintron#1000]
Hello 

I work with shared site hosting.

My servers use cPanel / WHM and Engintron

When I create or remove a server account, for a few seconds I get the message 502 bad gateway

Is there any timeout setting so this does not happen?

I know this message is displayed because NGINX does not get connection to Apache.

Thank you
Marcelo Almeida

**Comment by thoiruddin** [comment]
Yeah.

It's happened to me too.

**Comment by fevangelou** [comment]
Nginx will instantly serve HTTP traffic. For HTTPS traffic, Nginx has to sync against Apache's vhosts, which is done every 20-30 secs. You can lower the check time but it's not really worth it if you and only you add these accounts.

There may be a chance that this time is longer IF Apache is slow merging the changes in its httpd.conf file (which I've seen some times on low spec of overcrowded servers).
