### ISSUE TITLE
restart apache_php_fpm only where fpm is active

### ISSUE THREAD

**Issue by lpasquali** [engintron/engintron#1001]
Hello Fotis,

I have a slightly awful issue about installation, it would be super useful that fpm is tried to get restarted only on systems which use it, we use CloudLinux and lsapi for instance.
Checking if fpm is running and active before doing this would be very helpful and reduce by some minutes the installation  process.

```
=== Restarting Apache & Nginx... ===
Service Status

apache_php_fpm restarted successfully.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.

```

**Comment by fevangelou** [comment]
I'll test if `/scripts/restartsrv_apache_php_fpm --check` works as expected (the actual file is binary so I can't see the code there) and merge into engintron.sh.

**Comment by fevangelou** [comment]
Actually, the command above seems to check if the config files in PHP-FPM are all good. So it'll probably boil down to actually checking the service name in "ps".
