### ISSUE TITLE
How to enable WordPress cache busting plugins to work?

### ISSUE THREAD

**Issue by StephenIbiza** [engintron/engintron#1002]
Hi,

I have Engintron running on a cPanel server that is offering shared hosting. 

If I adjust the time of the dynamic cache from 1 second to say 1 hour, then when users make changes to WordPress sites then those changes are not seen my users who are not logged in for an hour.

There are a number of WP plugins (e.g. Busted, Proxy Cache Purge) that are supposed to be able to purge the cache in NGiNX for a post when the content is updated. However, they don’t seem to work with the standard Engintron install.  Some plugging say that NGiNX must allow purging of files via Curl.

Does anyone know how I can change to NGiNX configuration to allow such plugins to work?

Thanks,

Stephen

**Comment by fevangelou** [comment]
Users should simply login and any caching is disabled automatically by Nginx. I would also recommend a saner value for dynamic caching like 5-10-15 mins tops. 1 hour is overkill.

It's not currently possible to purge cache in this reverse caching proxy scenario.

**Comment by tons** [comment]
Hi @fevangelou, could you especify where to change that parameter at Engintron config? File? Or some configuration example.

Thanks in advance!

**Comment by fevangelou** [comment]
@tons It's all in the docs >> engintron.com/docs
