### ISSUE TITLE
installed engintron but don't know it is working for not

### ISSUE THREAD

**Issue by viper877** [engintron/engintron#1004]
Hello install engintron in my server and i am using cloudflare and i gave my dedicated server ip there and in cpanel i enable php fpm for websites and sites are working and engintron is enabled but when i go to my wordpress site and when i see in wordpress server info plugin it show that server is running still on apache http://prntscr.com/mgra0w   can you please tell me how to confirm that website is on Nginx or not

please help me out

**Comment by tarekfellah** [comment]
> Use curl from the terminal, e.g. `curl -I "https://www.domain.tld"`

And how to check if Engintron is working?

**Comment by fevangelou** [comment]
You'll see "Nginx" mentioned in the headers shown.
