### ISSUE TITLE
Webmail subdomain not working? (2)

### ISSUE THREAD

**Issue by ddrhost** [engintron/engintron#1005]
I tested it, but unfortunately it does not work with the indicated rule. Only forcing access to the hostname of the server with SSL.

Does not work:

> if ($host ~* "^(webmail|cpanel|whm|webdisk|cpcalendars|cpcontacts)\.") {
>     set $PROXY_FORWARDED_HOST '';
> }

![email 2](https://user-images.githubusercontent.com/9554453/52270122-1ee07280-2927-11e9-9552-91cd91eb9d60.jpg)

This works:

> if ($host ~* "^webmail\.") {
>     return 301 https://$hostname/webmail;
> }
> if ($host ~* "^whm\.") {
>     return 301 https://$hostname/whm;
> }
> if ($host ~* "^cpanel\.") {
>     return 301 https://$hostname/cpanel;
> }

#965

**Comment by fevangelou** [comment]
I lost you here. Which case does the screenshot apply to?

**Comment by ddrhost** [comment]
Some clients complain and would like to access the webmail with subdomain by the domain itself. If the client accesses the webmail by subdomain with HTTPS the problem does not occur.

It is something related only to access with HTTP.

**Comment by fevangelou** [comment]
Keep in mind that I can't replicate your issue. I have servers I manage that have the subdomain enabled and Roundcube/Horde working just fine.

**Comment by fevangelou** [comment]
> It is something related only to access with HTTP.
HTTP should redirect to HTTPS automatically. It does in my case with a stock cPanel installation.
