### ISSUE TITLE
EnginTron fails can't start nginx

### ISSUE THREAD

**Issue by evil4u** [engintron/engintron#1006]
I did try to force reinstall cpanel and I did clean tmp cache and reinstall engintron.

Feb 06 16:58:35 hq.domain.com systemd[1]: Starting nginx - high performance web server...
Feb 06 16:58:35 hq.domain.com nginx[32593]: nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (...ectory)
Feb 06 16:58:35 hq.domain.com nginx[32593]: 2019/02/06 16:58:35 [emerg] 32593#32593: open() "/var/log/nginx/access.log" failed (2: N...ectory)
Feb 06 16:58:35 hq.domain.com systemd[1]: nginx.service: control process exited, code=exited status=1
Feb 06 16:58:35 hq.domain.com systemd[1]: Failed to start nginx - high performance web server.
Feb 06 16:58:35 hq.domain.com systemd[1]: Unit nginx.service entered failed state.
Feb 06 16:58:35 hq.domain.com systemd[1]: nginx.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by evil4u** [comment]
Fixed.

**Comment by fevangelou** [comment]
What was the issue?

**Comment by spaceofmiah** [comment]
Hi @evil4u, how did you fix this issue ?
