### ISSUE TITLE
Virtualmin Support

### ISSUE THREAD

**Issue by katz-kt** [engintron/engintron#1007]
Good day, I know you are creating for Cpanel support, is there any way you can provide support for Virtualmin too? Thanks for the lovely script.

**Comment by fevangelou** [comment]
I would honestly have no issue doing that if both Virtualmin and Webmin were not such a mess. No offence here, if you've used it for a long time you may not bother with its peculiarities. But it's not a reliable control panel. Same goes for almost every other free/open source control panel out there. Although I live and breathe open source (Engintron is not my only project), when it comes to hosting control panels there are only 2 options around if you want your sanity and these are cPanel and Plesk. Everything else is either in constant alpha/beta mode or just not meant/built for the majority of users who would use a control panel in the first place.

For reference, I have evaluated (but not as extensively as I did for Webmin/Virtulamin) the following: Ajenti, VestaCP, CWP (CentOS Web Panel) and ISPConfig

They are either alpha/beta releases or far too opinionated or difficult to extend. It's like they've taken the bad things from cPanel (which has a 20 year old codebase by the way) and made them worse.

**Comment by katz-kt** [comment]
ok, I understand your point. however, I find Webmin/Virtualmin very nice and easy to use. I also like the fact that it challenges me to learn new things when it comes to configuring and setting up my own preferred modules. I guess its all about preferences sometimes and the willing to learn behind the scene. 

I have been using it for about 1 and a half year now. I have learned so much more than when I was using Cpanel. although Cpanel it's great you never learn a lot within the codes. everything is done for you automatically. I am a junior computer technician and I would like to explore more in programming.

Nevertheless, I have managed to install your script in my centos 7 system running with Virtualmin. it works, however, I am facing a root problem. when I set up my own Nginx server blocks, the browser just downloads the PHP files to local computer. 

Could you help me out here, please. how can I set up my own server blocks to work with your code? any little bit of info would be appreciated, thank you in advance.

**Comment by fevangelou** [comment]
What you describe seems to point to MIME detection issues. So just compare the /etc/nginx files you have with the ones that ship in Engintron. All files matter obviously.

**Comment by katz-kt** [comment]
Hi, firstly I would like to thank you for the support. After doing a little bit of reading in your script, I have finally realized that I don't need to create my own server blocks. Engitron has already been configured to detect apache server blocks using the default configuration for Nginx. 

So HTTP workes great except for https, so I edit the PHP script in utilities to generate default SSL Nginx configuration for Virtualmin. however, I see the SSL certificate has the wrong handshake on SSL Shopper. have I missed something on my configuration?

here is my PHP configuration generator script:

#!/usr/local/bin/php
<?php

/**
 * @version    1.9.3
 * @package    Engintron for cPanel/WHM
 * @author     Fotis Evangelou (https://kodeka.io)
 * @url        https://engintron.com
 * @copyright  Copyright (c) 2018 - 2019 Kodeka OÜ. All rights reserved.
 * @license    GNU/GPL license: https://www.gnu.org/copyleft/gpl.html
 */

if (file_exists('/etc/apache2/conf/httpd.conf') && is_readable('/etc/apache2/conf/httpd.conf')) {
    define('HTTPD_CONF', '/etc/apache2/conf/httpd.conf');
} elseif (file_exists('/etc/httpd/conf/httpd.conf') && is_readable('/etc/httpd/conf/httpd.conf')) {
    define('HTTPD_CONF', '/etc/httpd/conf/httpd.conf');
} else {
    define('HTTPD_CONF', '/usr/local/apache/conf/httpd.conf');
}
define('HTTPD_CONF_LAST_CHANGED', 15); /* In seconds */
define('HTTPD_HTTPS_PORT', '8443');
define('NGINX_HTTPS_PORT', '443');
define('NGINX_DEFAULT_HTTPS_VHOST', '/etc/nginx/conf.d/default_https.conf');

//date_default_timezone_set('UTC');
//ini_set('display_errors', 0);
//error_reporting(0);

function generate_https_vhosts()
{
    $hostnamePemFile = '';
    if (file_exists('/etc/webmin/miniserv.pem') && is_readable('/etc/webmin/miniserv.pem')) {
        $hostnamePemFile = '/etc/webmin/miniserv.pem';
    }
    if (file_exists('/etc/webmin/miniserv.pem') && is_readable('/etc/webmin/miniserv.pem')) {
        $hostnamePemFile = '/etc/webmin/miniserv.pem';
    }

    // Initialize the output for default_https.conf
    $output = '
# /**
#  * @version    1.9.3
#  * @package    Engintron for cPanel/WHM
#  * @author     Fotis Evangelou (https://kodeka.io)
#  * @url        https://engintron.com
#  * @copyright  Copyright (c) 2018 - 2019 Kodeka OÜ. All rights reserved.
#  * @license    GNU/GPL license: https://www.gnu.org/copyleft/gpl.html
#  */

# Default definition block for HTTPS (Generated on '.@date('Y.m.d H:i:s').') #
server {

    listen '.NGINX_HTTPS_PORT.' ssl http2 default_server;
    #listen [::]:'.NGINX_HTTPS_PORT.' ssl http2 default_server;
    server_name localhost;

    # deny all; # DO NOT REMOVE OR CHANGE THIS LINE - Used when Engintron is disabled to block Nginx from becoming an open proxy

    ssl_certificate '.$hostnamePemFile.';
    ssl_certificate_key '.$hostnamePemFile.';

    # OCSP Stapling
    #ssl_trusted_certificate '.$hostnamePemFile.';
    #ssl_stapling on;
    #ssl_stapling_verify on;

    include common_https.conf;

    location = /nginx_status {
        stub_status;
        access_log off;
        log_not_found off;
        # Uncomment the following 2 lines to make the Nginx status page private.
        # If you do this and you have Munin installed, graphs for Nginx will stop working.
        #allow 127.0.0.1;
        #deny all;
    }

    location = /whm-server-status {
        proxy_pass http://127.0.0.1:8080;
        # Comment the following 2 lines to make the Apache status page public
        allow 127.0.0.1;
        deny all;
    }

}
    ';

    // Process Apache vhosts
    if (file_exists(HTTPD_CONF) && is_readable(HTTPD_CONF)) {
        $file = file_get_contents(HTTPD_CONF);
        $regex = "#\<VirtualHost [0-9a-f\.\:\[\]\s]+\:".HTTPD_HTTPS_PORT."\>(.+?)\<\/VirtualHost\>#s";
        preg_match_all($regex, $file, $matches, PREG_PATTERN_ORDER);
        if (count($matches[1])) {
            foreach ($matches[1] as $vhost) {
                if ($hostnamePemFile && strpos($vhost, $hostnamePemFile)!== false) {
                    continue;
                } // Skip the main hostname entry
                preg_match("#ServerName (.+?)\n#s", $vhost, $name);
                preg_match_all("#ServerAlias (.+?)\n#s", $vhost, $aliases);
                preg_match("#SSLCertificateFile (.+?)(\n|\r)#s", $vhost, $certfile);
                preg_match("#SSLCertificateKeyFile (.+?)(\n|\r)#s", $vhost, $certkeyfile);
                preg_match("#SSLCACertificateFile (.+?)(\n|\r)#s", $vhost, $certcafile);
                if ($aliases[1]) {
                    $vhostAliases = implode(' ', $aliases[1]);
                } else {
                    $vhostAliases = '';
                }
                $vhostDomains = trim($name[1].' '.$vhostAliases);
                $vhostDomainsForNginx = explode(' ', $vhostDomains);
                $vhostDomainsForNginx = implode(PHP_EOL.'        ', $vhostDomainsForNginx);
                $vhostDomainsAsComment = str_split($vhostDomains, 250);
                $vhostDomainsAsComment = implode(PHP_EOL.'# ', $vhostDomainsAsComment);
                $vhostCertFile = $certfile[1];
                $vhostCertKeyFile = $certkeyfile[1];
                if (strpos($vhostCertFile, '/combined') !== false) {
                    $fullChainCertName = $vhostCertFile;
                    $vhostCertKeyFile = $vhostCertFile;
                } else {
                    $fullChainCertName = str_replace('/etc/webmin/webmin/', '/etc/ssl/engintron/', $vhostCertFile);
                    if ($certcafile[1]) {
                        $vhostCertCAFile = $certcafile[1];
                        $vhostFullChainCert = file_get_contents($vhostCertFile)."\n".file_get_contents($vhostCertCAFile);
                        $ocspStapling = '
    # OCSP Stapling
    #ssl_trusted_certificate '.$fullChainCertName.';
    #ssl_stapling on;
    #ssl_stapling_verify on;
                    ';
                    } else {
                        $vhostFullChainCert = file_get_contents($vhostCertFile);
                        $ocspStapling = '';
                    }
                    file_put_contents($fullChainCertName, $vhostFullChainCert);
                }

                $output .= '
# Definition block for domain(s): '.$vhostDomainsAsComment.' #
server {
    listen '.NGINX_HTTPS_PORT.' ssl http2;
    #listen [::]:'.NGINX_HTTPS_PORT.' ssl http2;
    server_name '.$vhostDomainsForNginx.';
    # deny all; # DO NOT REMOVE OR CHANGE THIS LINE - Used when Engintron is disabled to block Nginx from becoming an open proxy
    ssl_certificate '.$fullChainCertName.';
    ssl_certificate_key '.$vhostCertKeyFile.';
    '.$ocspStapling.'
    include common_https.conf;
}
                ';
            }
        }
    }
    file_put_contents(NGINX_DEFAULT_HTTPS_VHOST, $output);
}

// Run the check
if (!file_exists(NGINX_DEFAULT_HTTPS_VHOST) || (file_exists(HTTPD_CONF) && is_readable(HTTPD_CONF) && (filemtime(HTTPD_CONF) + HTTPD_CONF_LAST_CHANGED) > time())) {
    generate_https_vhosts();
    exit(1);
} else {
    exit(0);
}

**Comment by fevangelou** [comment]
Engintron is built for cPanel and works with the certificates cPanel's Apache generates. So you'll have to figure this out on your own I'm afraid...

P.S. The topic is also beyond the scope of the support I offer here.
