### ISSUE TITLE
Prestashop ang google/facebook integration

### ISSUE THREAD

**Issue by sla004** [engintron/engintron#1008]
Social login module in prestashop does not work if engintron is enabled. Currentöy I would like to use facebook and google logins for my users. Is there way to get this combination working?

Here you can find out more about how module is working...
https://faq.businesstech.fr/product/61-social-login

**Comment by fevangelou** [comment]
Use "custom rules" to exclude that domain from the 1 sec micro-caching in Nginx. Something like:
```
if ($SITE_URI ~* "myprestashopsite.tld") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
}
```

Read the comments in the Custom Rules file to see what's possible.

All the above is in the Engintron Docs of course...

**Comment by sla004** [comment]
WOW...that was easy. I just bypasses facebook.com and googleapis.com domain and now it works :)
Thanks @fevangelou

**Comment by fevangelou** [comment]
The rules are meant for domains on your server, not third party domains like facebook.com etc. I hope you've understood what I meant...
