### ISSUE TITLE
behaviour of  /etc/nginx/utilities/https_vhosts.sh

### ISSUE THREAD

**Issue by lpasquali** [engintron/engintron#1009]
Hello!

I see that every time the virtual host database in cPanel changes, it is issued a cache purge, which implies an nginx restart I have two questions about that:
1) this question is related to " /etc/nginx/utilities/https_vhosts.sh" in medium to large cPanel shared hostings users might add subdomains and aliases and secondary primary domains on a very random basis, is it sane to purge the cache on such basis?
2) this question then is related to the "/usr/local/src/engintron/engintron.sh purgecache" that is called by the script in subject I see you do:
```
purgecache)
    NOW=$(date +'%Y.%m.%d at %H:%M:%S')
    echo "==================================================================="
    echo "=== Clean Nginx cache & temp folders and restart Apache & Nginx ==="
    echo "==================================================================="
    echo ""
    echo "--- Process started at $NOW ---"
    echo ""
    find /var/cache/nginx/engintron_dynamic/ -type f | xargs rm -rvf
    find /var/cache/nginx/engintron_static/ -type f | xargs rm -rvf
    find /var/cache/nginx/engintron_temp/ -type f | xargs rm -rvf
    if [ "$(pstree | grep 'httpd')" ]; then
        echo "Restarting Apache..."
        /scripts/restartsrv apache_php_fpm
        /scripts/restartsrv_httpd
        echo ""
    fi
    if [ "$(pstree | grep 'nginx')" ]; then
        #echo "Restarting Nginx..."
        #service nginx restart
        echo "Reloading Nginx..."
        service nginx reload
        echo ""
    fi
    echo ""
    ;;
```

I tried with no particular issue to replace such restart with a reload, I would suggest, if anyone really uses it to replace the restart also in the "purgelogs"

also as /scripts/restartsrv_httpd never attempts to kill apache but does a graceful restart, as well nginx should be reloaded as much as possible. I think this will improve notably server uptimes checked by Pingdom or other vendors of http checks.

**Comment by fevangelou** [comment]
Reloading is of course the logical thing to do. However, tests showed that when simply reloading, changes in HTTPS certificates etc. may not properly reload. Of course that was a few versions (and more than a year) ago.

Have you double-checked?

**Comment by lpasquali** [comment]
Yup, I did check, we give both Let's Encrypt and cPanel autossl as a choice to our users, I see no issues at all,  I think it woule be safe for anyone to keep restart only in case the nginx binary changed because of an upgrade, imho the only other non un-attended cases should be two:
1) upon "sysadmin" will 
2) change to different init state, like reboot, shutdown, single user mode.

**Comment by fevangelou** [comment]
Noted. Closing for now.
