### ISSUE TITLE
NooB Question about cron jobs and Engintron

### ISSUE THREAD

**Issue by BCwhoLikesPHP** [engintron/engintron#101]
Quick Question that I am hoping to get some help with.... When I create a cron job on a server with Engintron running, and the cron job calls php directly to load a script as below: 

/usr/bin/php   /home/my_account_name/public_html/folder_with_script/myscript.php -r someparam

Will this request run through Engintron? or even Apache now that I think about it?

I know it is kind of a rookie question but I am getting timeouts with the script and I did not think I should. Was wondering if Engintron had anything to do with it. Anyway, let me know. Thanks.

**Comment by fevangelou** [comment]
When you do this, you're invoking php internally in your system. You're not
using either Nginx or Apache.

You would be using either Nginx or Apache if you used a wget or curl
command calling an http://... URL.
