### ISSUE TITLE
Other Servers on Same Network

### ISSUE THREAD

**Issue by reaper44au** [engintron/engintron#1011]
Have a problem running muttiple servers on network. Currently Cpanel and Openfire, Now when Engintron is active i have the cpanel sites working fine, But the Openfire Server, Inverse on port 7443 Causes a NXdomain timeout. The reverse proxy is causing this as ive already tested that. I am behind a net gear router with port forwarding. Firewall settings and ports have been set up correctly. Only fix ive found is to disable Engintron.

**Comment by fevangelou** [comment]
Engintron will only kick in if the Openfire server you mention uses either port 80 or 443. If so, you can use "custom rules" to proxy traffic on either of these ports for a specific domain to the Openfire server port.

See the example proxy for v1.9.0 here: https://engintron.com/docs/#/pages/Changelog

**Comment by reaper44au** [comment]
yes that would be fine, but  we are talking about a server that is seperate running on another machine on tthe same network. Using port forwarding pointing to  seperate boxs with different ips. How does Engrinton interefere with the openfire server. Is it causing problems with the port forwarding router?.

**Comment by fevangelou** [comment]
> Engintron will only kick in if the Openfire server you mention uses either port 80 or 443

I was very specific here.

If the Openfire server has nothing to do with the cPanel server that uses Engintron (=does not utilize a domain or subdomain that is hosted on cPanel), then there is no conflict here. Engintron would cause no issues to the Openfire server.

**Comment by reaper44au** [comment]
yes i  have heard this before. Hence why i bought this up. Evan though inverse and ofmeet run on port 7433. i cant access them with Engintron running on my network. First the mobile samsung browser throws nxdomain error, but not straight away, This makes me believe its a dns cache related problem,As you mentioned it shouldnt interfere with rest of network, but i assure you it does.. router is a v7610

**Comment by fevangelou** [comment]
It doesn't. They are 2 separate things. Unless your network topology mixes ports otherwise, there is no relation here.

**Comment by reaper44au** [comment]
I may hvae figured the problem out.as i am running on a main static I.P, i was using that, it didn`t like localhost or 127.0.0.1, so i used the servers domain name. So far so good, i can reach the other server on my network, Let you know if the problem turns back up.
