### ISSUE TITLE
php-fpm vs mod_lsapi + Engintron

### ISSUE THREAD

**Issue by josephsimony** [engintron/engintron#1012]
Now that [EasyApache 4 includes a light version of mod_lsapi](https://blog.cpanel.com/easyapache-4-and-mod_lsapi/) I wonder if Engintron plays along nicely and if it's worth it to replace php-fpm.

Any experience & thoughts on this are much appreciated!

Ps.: this is obviously not an "issue," (sorry, I couldn't find a better place to post it). 
It would be great to discuss things that are not Engintron issues but might be related to Engintron.

**Comment by fevangelou** [comment]
Engintron's Nginx talks to Apache, not PHP :) So it doesn't matter which medium is used to spit out PHP code (be it a CGI module for Apache or a service like PHP-FPM).

In any case, I would personally use PHP-FPM as (again to me) is far better at controlling processes if you know what you're doing. mod_lsapi may be better at preserving resources for servers with hundreds to thousands of user accounts/domains.

An Engintron blog is coming soon so I'll dive deeper into PHP-FPM configuration as nearly all examples on the web are dead wrong and mistakenly connect child processes to a server's available RAM.
