### ISSUE TITLE
Bad gateway 502 cache

### ISSUE THREAD

**Issue by mitya3003** [engintron/engintron#1013]
Hello.

I use it at cpanel server and discover that last version of engintron with default settings  can cache 503 error (gateway timeout) error for several virtual hosts (when apache restarts for example).

503 error will be hour or more, at same time it will serve other websites with no problem.

Purge cache can help.

But it looks like such error code needs more accurate caching or less caching time for it.

**Comment by fevangelou** [comment]
There is no change in how Engintron does caching for around 2 years or so. Errors are not cached.

If some sites are served just fine while others display an error, it means the latter are broken, thus the error.

BTW, 503 is for internal server error, 502 is gateway timeout (aka Apache did not respond = unhealthy backend).

**Comment by mitya3003** [comment]
Hello.

 

As I understand this lines is cachу errors

 

proxy_cache_use_stale          error timeout invalid_header updating http_429 http_500 http_502 http_503 http_504; # Additional options: http_403 http_404

proxy_cache_valid              200 1s; # Adjust for longer server-side cache times (unfortunately, we cannot use a variable here)

 

Regards

Sergey Dedyukhin

**Comment by fevangelou** [comment]
That line is merely defining to serve a cached page if an error occurs. If valid errors occur and there is no cached object to be served, errors show up just fine.

**Comment by mitya3003** [comment]
For example, backend restarts and nginx gives 502 error. When backend up, nginx will still returns 502 error for 1 minute.

 

May be I am wrong in my conclusion?..

**Comment by fevangelou** [comment]
Read this: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_use_stale

If the backend is unhealthy AND Nginx has a cached copy in store (unlikely if you use the 1 sec micro-cache), then and only then it will display the cached copy. Errors are never cached. So if you see a 502 or 503 error, this is not a cached copy.

**Comment by mitya3003** [comment]
Thank you for clarification. 

Regards!
