### ISSUE TITLE
Install ngx_http_sub_module

### ISSUE THREAD

**Issue by pmjcreations** [engintron/engintron#1014]
Can you tell me the way to install [ngx_http_sub_module](https://nginx.org/en/docs/http/ngx_http_sub_module.html) when using Engintron

**Comment by fevangelou** [comment]
I think it's now bundled by default. Check the Nginx modules loaded via
Engintron's WHM plugin.

**Comment by pmjcreations** [comment]
Yes it is @fevangelou.

I am trying to achieve similar to https://stackoverflow.com/questions/51660762/injecting-google-analytics-tracking-snippet-into-websites-behind-nginx-reverse-p

But somehow it is not working.

I tried to add code in common_http.conf file, but the script is not adding to any website.

Will this method work if I enable GZip? Have I needed to use Apache modules than Nginx modules?

**Comment by pmjcreations** [comment]
Hello @fevangelou,

All good now :+1: :smile:
