### ISSUE TITLE
502 For Cloudflare Pages

### ISSUE THREAD

**Issue by mikegemagine** [engintron/engintron#1015]
Just installed with no configuration modifications at all and sites using Cloudflare are giving me bad gateway errors. 

If I disable engintron the sites work fine, so I don't believe the issue is on the apache side. For the time being I've left it disabled.

From the error log:

2019/02/16 14:23:45 [error] 4744#4744: *36 connect() failed (111: Connection refused) while connecting to upstream, client: 74.78.24.94, server: localhost, request: "GET /license.txt HTTP/1.1", upstream: "http://104.24.106.189:8080/license.txt", host: "www.bethelregencyhomes.com"
2019/02/16 14:23:46 [error] 4744#4744: *36 connect() failed (111: Connection refused) while connecting to upstream, client: 74.78.24.94, server: localhost, request: "GET /license.txt HTTP/1.1", upstream: "http://104.24.107.189:8080/license.txt", host: "www.bethelregencyhomes.com"
2019/02/16 14:23:46 [error] 4744#4744: *36 connect() to [2606:4700:30::6818:6bbd]:8080 failed (101: Network is unreachable) while connecting to upstream, client: 74.78.24.94, server: localhost, request: "GET /license.txt HTTP/1.1", upstream: "http://[2606:4700:30::6818:6bbd]:8080/license.txt", host: "www.bethelregencyhomes.com"

**Comment by fevangelou** [comment]
CloudFlare requires special configuration. See the Engintron Docs for more.
