### ISSUE TITLE
Ulimit for max open files

### ISSUE THREAD

**Issue by josephmiller2000** [engintron/engintron#1016]
Is there any configuration for nginx to enable ulimit / max open files in our server to serve more concurrent file sharing or file opening for a heavy traffic websites?

**Comment by fevangelou** [comment]
The defaults are already high enough. If you're limited, check your Apache settings. Consult the Engintron Docs for Apache optimizations.

**Comment by fevangelou** [comment]
Closing as there is no response from the OP.
