### ISSUE TITLE
Magento 2.2, 2.3 domain based conf files

### ISSUE THREAD

**Issue by secaliskan** [engintron/engintron#1018]
Hi, We are using Magento 2.2.7 on Centos 6.1 with php 7.0. We rae using engintron and getting the huge benefits from it. this is a dedicated server with 10 accounts all running magento websites.

Magento 2 has a DOMAIN SPECIFIC sample nginx conf file below:
[nginx.conf.sample.txt](https://github.com/engintron/engintron/files/2904429/nginx.conf.sample.txt)

But its not working. I think this is for ubuntu servers. fastcgi_params value givng error. Can you please update this file and we include this conf additional to the general conf files for magento sites?
Please give hand on this...
regards

**Comment by fevangelou** [comment]
Any Nginx config provided by Magento will not apply to Engintron as in this case Nginx is used as a reverse caching proxy, not a "direct to app" web server...
