### ISSUE TITLE
CloudLinux BIG NO NO

### ISSUE THREAD

**Issue by evil4u** [engintron/engintron#1019]
Just wanted to let people know that EnginTron and CloudLinux does not play well together.
My server started to be extremely slow after I have install CloudLinux sometimes the pages started to take too long to load.

After that I have decided not to use CloudLInux with EngonTron.

**Comment by kmorton1988** [comment]
It would be helpful if you could post logs, confit files, use case, etc. the FAQs clearly state cloudlinux functionality. This general warning seems more like a scare tactic and doesn’t really belong here without proper documentation and repeatable steps.

**Comment by fevangelou** [comment]
CloudLinux is a beast of its own already. If it's misconfigured, it doesn't take much to "think" there are issues with other server components.

Of course, unless we have more info about "EngonTron", I can't tell much...

**Comment by mctaguma** [comment]
We're using Engintron and CloudLinux 6 together with no issues, if that helps.

**Comment by fevangelou** [comment]
Looks like a weird comment either way. Closing as the OP never provided substantial data to hold their claim.
