### ISSUE TITLE
Duplicate orders on ecom site after installing engintron

### ISSUE THREAD

**Issue by tonyr101** [engintron/engintron#1020]
I installed Engintron at the weekend and server load went down dramatically (yeah!)

BUT... one of the sites on the server is a Zen Cart powered ecom site and since installing Engintron it has been recording duplicate orders in the admin.
I can confirm only 1 payment is taken (via Barclays ePDQ) but 2 orders are recorded roughly 30 seconds apart for the same customer.

Looking at the Nginx access log I can see 1 hit to the "success-thank-you" page from the customers IP address and then another hit roughly 30 seconds later from the payment gateway's IP address?

Any idea what is going on and how to resolve this?

Thanks

**Comment by fevangelou** [comment]
Use "custom rules" to exclude that domain from the 1 sec micro-caching in Nginx. Something like:
```
if ($SITE_URI ~* "yourzencartdomain.tld") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
}
```

Read the comments in the Custom Rules file to see what's possible.

All the above is in the Engintron Docs of course...
