### ISSUE TITLE
Please can explain how setup for use with WebP Express

### ISSUE THREAD

**Issue by SaveTheHuman5** [engintron/engintron#1021]
Please can explain how setup for use with WebP Express

https://wordpress.org/plugins/webp-express/#description

Will be great add a easy setup for support this great plugin!

**Comment by fevangelou** [comment]
From what I'm reading, you don't really need to do anything. If the plugin alters the HTML output and replaces .jpg with .webp, Nginx will have no issue delivering these images with caching.
