### ISSUE TITLE
peer closed connection in SSL handshake while SSL handshaking to upstream

### ISSUE THREAD

**Issue by azizparacha** [engintron/engintron#1023]
v1.9.3
Build 20190122
(Nginx version: 1.14.2)

Log is full of these errors and sites go unresponsive

2019/03/13 10:20:36 [error] 17086#17086: *4444 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: 46.101.51.219, server: koolmaxgroup.com, request: "GET /interlevin-ess1365-gastronorm-preparation-counter-380-litre/ HTTP/1.1", upstream: "https://195.201.11.86:8443/interlevin-ess1365-gastronorm-preparation-counter-380-litre/", host: "www.koolmaxgroup.com"

AND

2019/03/13 10:20:37 [error] 17085#17085: *3887 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 54.36.150.85, server: koolmaxgroup.com, request: "GET /buffet-displays/shopby/600-700mm-_1000-1200mm-/ HTTP/1.1", upstream: "https://195.201.11.86:8443/buffet-displays/shopby/600-700mm-_1000-1200mm-/", host: "www.koolmaxgroup.com"

**Comment by fevangelou** [comment]
The site loads just fine (https://www.koolmaxgroup.com).

These entries in the log could have been temporary, e.g. while the HTTPS vhost definitions were re-generated by Apache & Nginx.
