### ISSUE TITLE
Apache Broken!

### ISSUE THREAD

**Issue by DavidBrockway** [engintron/engintron#1024]
Apache broken

**Comment by DavidBrockway** [comment]
[Thu Mar 14 03:19:37.789997 2019] [:error] [pid 660308:tid 47390153283328] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:424"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/js/cookieconsent.min.js"] [unique_id "XIoAiY5EzeeyeQEWNWG@iQAAAFE"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:37.766862 2019] [:error] [pid 660307:tid 47390153283328] [client 180.163.220.4:0] [client 180.163.220.4] ModSecurity: Warning. Matched phrase "180.163.220.4" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.4||PC:1137"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/js/venobox.min.js"] [unique_id "XIoAiex-STVrYwQxE1@ULgAAABE"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:37.360525 2019] [:error] [pid 660419:tid 47390151182080] [client 180.163.220.4:0] [client 180.163.220.4] ModSecurity: Warning. Matched phrase "180.163.220.4" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.4||PC:360"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/js/counter.js"] [unique_id "XIoAic8PKhoCs-kGj4O4VgAAARA"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:37.345599 2019] [:error] [pid 660391:tid 47390151182080] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:947"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/js/jquery-migrate.min.js"] [unique_id "XIoAiRcd6aBEc18L5pWzzAAAANA"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:37.336437 2019] [:error] [pid 660363:tid 47390151182080] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:1100"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/js/jquery.js"] [unique_id "XIoAiXZ55XwOaiCGoqqA3QAAAJA"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:37.048120 2019] [:error] [pid 660307:tid 47390151182080] [client 180.163.220.4:0] [client 180.163.220.4] ModSecurity: Warning. Matched phrase "180.163.220.4" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.4||PC:1035"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/css/custom.css"] [unique_id "XIoAiex-STVrYwQxE1@ULQAAABA"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:36.919901 2019] [:error] [pid 660447:tid 47390149080832] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:998"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/css/bootstrap-grid.min.css"] [unique_id "XIoAiIzZd4w-x@6YMVjkAgAAAU8"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:36.096212 2019] [:error] [pid 660391:tid 47390149080832] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:786"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/css/theme.css"] [unique_id "XIoAiBcd6aBEc18L5pWzywAAAM8"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:35.664717 2019] [:error] [pid 660363:tid 47390149080832] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:1072"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/css/cookieconsent.min.css"] [unique_id "XIoAh3Z55XwOaiCGoqqA3AAAAI8"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:35.329214 2019] [:error] [pid 660308:tid 47390149080832] [client 180.163.220.4:0] [client 180.163.220.4] ModSecurity: Warning. Matched phrase "180.163.220.4" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.4||PC:305"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/css/1-style.css"] [unique_id "XIoAh45EzeeyeQEWNWG@hwAAAE8"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:32.016903 2019] [:error] [pid 660391:tid 47390146979584] [client 180.163.220.4:0] [client 180.163.220.4] ModSecurity: Warning. Matched phrase "180.163.220.4" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.4||PC:1075"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/"] [unique_id "XIoAgxcd6aBEc18L5pWzygAAAM4"]
        [Thu Mar 14 02:04:43.849312 2019] [:error] [pid 660419:tid 47390146979584] [client 157.230.229.73:0] [client 157.230.229.73] ModSecurity: Access denied with code 403 (phase 1). Matched phrase "/.env" at REQUEST_URI. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/102_Global_Generic.conf"] [line "57"] [id "77210492"] [rev "3"] [severity "CRITICAL"] [tag "CWAF"] [hostname "shadowhuntersleics.co.uk"] [uri "/.env"] [unique_id "XInu@88PKhoCs-kGj4O3pwAAAQ4"]
        Mar 15 12:25:15 pluto systemd: Failed to start Apache web server managed by cPanel EasyApache.
        Mar 15 12:25:15 pluto restartsrv_httpd: AH00534: httpd: Configuration error: No MPM loaded.

httpd has failed. Contact your system administrator if the service does not automagically recover.
Redirecting to /bin/systemctl restart httpd.service
Job for httpd.service failed because the control process exited with error code. See "systemctl status httpd.service" and "journalctl -xe" for details.
Redirecting to /bin/systemctl restart nginx.service

**************************************
*       Installation Complete        *
**************************************


[root@pluto /]# yum update cagefs lvemanager

**Comment by DavidBrockway** [comment]
[Thu Mar 14 03:19:37.789997 2019] [:error] [pid 660308:tid 47390153283328] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:424"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/js/cookieconsent.min.js"] [unique_id "XIoAiY5EzeeyeQEWNWG@iQAAAFE"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:37.766862 2019] [:error] [pid 660307:tid 47390153283328] [client 180.163.220.4:0] [client 180.163.220.4] ModSecurity: Warning. Matched phrase "180.163.220.4" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.4||PC:1137"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/js/venobox.min.js"] [unique_id "XIoAiex-STVrYwQxE1@ULgAAABE"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:37.360525 2019] [:error] [pid 660419:tid 47390151182080] [client 180.163.220.4:0] [client 180.163.220.4] ModSecurity: Warning. Matched phrase "180.163.220.4" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.4||PC:360"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/js/counter.js"] [unique_id "XIoAic8PKhoCs-kGj4O4VgAAARA"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:37.345599 2019] [:error] [pid 660391:tid 47390151182080] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:947"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/js/jquery-migrate.min.js"] [unique_id "XIoAiRcd6aBEc18L5pWzzAAAANA"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:37.336437 2019] [:error] [pid 660363:tid 47390151182080] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:1100"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/js/jquery.js"] [unique_id "XIoAiXZ55XwOaiCGoqqA3QAAAJA"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:37.048120 2019] [:error] [pid 660307:tid 47390151182080] [client 180.163.220.4:0] [client 180.163.220.4] ModSecurity: Warning. Matched phrase "180.163.220.4" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.4||PC:1035"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/css/custom.css"] [unique_id "XIoAiex-STVrYwQxE1@ULQAAABA"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:36.919901 2019] [:error] [pid 660447:tid 47390149080832] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:998"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/css/bootstrap-grid.min.css"] [unique_id "XIoAiIzZd4w-x@6YMVjkAgAAAU8"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:36.096212 2019] [:error] [pid 660391:tid 47390149080832] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:786"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/css/theme.css"] [unique_id "XIoAiBcd6aBEc18L5pWzywAAAM8"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:35.664717 2019] [:error] [pid 660363:tid 47390149080832] [client 180.163.220.68:0] [client 180.163.220.68] ModSecurity: Warning. Matched phrase "180.163.220.68" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.68||PC:1072"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/css/cookieconsent.min.css"] [unique_id "XIoAh3Z55XwOaiCGoqqA3AAAAI8"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:35.329214 2019] [:error] [pid 660308:tid 47390149080832] [client 180.163.220.4:0] [client 180.163.220.4] ModSecurity: Warning. Matched phrase "180.163.220.4" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.4||PC:305"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/css/1-style.css"] [unique_id "XIoAh45EzeeyeQEWNWG@hwAAAE8"], referer: http://www.shadowhuntersleics.co.uk/
        [Thu Mar 14 03:19:32.016903 2019] [:error] [pid 660391:tid 47390146979584] [client 180.163.220.4:0] [client 180.163.220.4] ModSecurity: Warning. Matched phrase "180.163.220.4" at TX:i360_remote_addr. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/000_i360_0.conf"] [line "31"] [id "33329"] [msg "Source IP is recorded||MVN:TX:i360_remote_addr||T:APACHE||MV:180.163.220.4||PC:1075"] [severity "DEBUG"] [tag "i360"] [tag "noshow"] [hostname "www.shadowhuntersleics.co.uk"] [uri "/"] [unique_id "XIoAgxcd6aBEc18L5pWzygAAAM4"]
        [Thu Mar 14 02:04:43.849312 2019] [:error] [pid 660419:tid 47390146979584] [client 157.230.229.73:0] [client 157.230.229.73] ModSecurity: Access denied with code 403 (phase 1). Matched phrase "/.env" at REQUEST_URI. [file "/etc/apache2/conf.d/modsec_vendor_configs/imunify360_full_apache/102_Global_Generic.conf"] [line "57"] [id "77210492"] [rev "3"] [severity "CRITICAL"] [tag "CWAF"] [hostname "shadowhuntersleics.co.uk"] [uri "/.env"] [unique_id "XInu@88PKhoCs-kGj4O3pwAAAQ4"]
        Mar 15 12:25:15 pluto systemd: Failed to start Apache web server managed by cPanel EasyApache.
        Mar 15 12:25:15 pluto restartsrv_httpd: AH00534: httpd: Configuration error: No MPM loaded.

httpd has failed. Contact your system administrator if the service does not automagically recover.
Redirecting to /bin/systemctl restart httpd.service
Job for httpd.service failed because the control process exited with error code. See "systemctl status httpd.service" and "journalctl -xe" for details.
Redirecting to /bin/systemctl restart nginx.service

**************************************
*       Installation Complete        *
**************************************

**Comment by ardipa** [comment]
I updated my vps cPanel to v68.0.17 and Engintron doesn not working anymore!

**Comment by fevangelou** [comment]
@ardipa cPanel v68 is not the latest cPanel release (and it's actually around 2 years old). You need to push past v70. Engintron will always work properly with recent cPanel versions only.

@DavidBrockway Your logs indicate an error with mod_security rules. Check if something is broken there. If you can't make anything out of it, simply disable any mod_security rules.

Nginx does not control Apache in any way, so it's not an issue coming from Engintron.

**Comment by fevangelou** [comment]
@DavidBrockway Your first message truly reminded of this https://www.joomlaworks.net/blog/item/275-does-not-work by the way...
