### ISSUE TITLE
nginx: [emerg] cannot load certificate 

### ISSUE THREAD

**Issue by mitya3003** [engintron/engintron#1026]
Hello.

Afte remove of one user account (may be it was not removed properly?) nginx stucks on this error (were DOMAIN.RU belongs to removed account).

I try restore account from backup and remove it again
I try remove engintron and install it again

This steps didnt help.

I am end up with this)

Redirecting to /bin/systemctl status nginx.service
● nginx.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: exit-code) since Tue 2019-03-19 09:44:58 MSK; 15min ago
 Main PID: 6878 (code=exited, status=0/SUCCESS)

Mar 19 09:44:57 s10.steadyhost.ru systemd[1]: Starting nginx - high performance web server...
Mar 19 09:44:58 s10.steadyhost.ru nginx[61452]: nginx: [emerg] cannot load certificate "/var/cpanel/ssl/apache_tls/DOMAIN.RU/combined": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/apache_tls/DOMAIN.RU/combined','r') error:2006D080:BIO routines:BIO_new_file:no such file)
Mar 19 09:44:58 s10.steadyhost.ru systemd[1]: nginx.service: control process exited, code=exited status=1
Mar 19 09:44:58 s10.steadyhost.ru systemd[1]: Failed to start nginx - high performance web server.
Mar 19 09:44:58 s10.steadyhost.ru systemd[1]: Unit nginx.service entered failed state.
Mar 19 09:44:58 s10.steadyhost.ru systemd[1]: nginx.service failed.

**Comment by fevangelou** [comment]
Files got corrupt for some reason. Re-save Apache's config to regenerate certificates and Nginx will pick up the changes.

**Comment by mitya3003** [comment]
do you mean run rebuildhttpdconf?




-------- Исходное сообщение --------
От: Fotis Evangelou <notifications@github.com> 
Дата: 2019.03.31  9:27 PM  (GMT+03:00) 
Кому: engintron/engintron <engintron@noreply.github.com> 
Копия: mitya3003 <swisss@inbox.ru>, Author <author@noreply.github.com> 
Тема: Re: [engintron/engintron] nginx: [emerg] cannot load certificate 
  (#1026) 

Files got corrupt for some reason. Re-save Apache's config to regenerate certificates and Nginx will pick up the changes.

**Comment by fevangelou** [comment]
Correct, or simply open and saved Apache's settings from WHM. Nginx will see that Apache's config file was updated and update it own accordingly within 10-15 seconds.
