### ISSUE TITLE
Nginx not listening on 443 only on 80

### ISSUE THREAD

**Issue by Sherlokman** [engintron/engintron#1027]
Hello,

I just installed Engintron on a cPanel 76, centoOS 6  server. , it works fine with http, but not with https.
Nginx listens only on 80.
Apache on 8080 and 8443

I read on some  other related issures that SSL problem have been fixed since version 1.8, so normally it should work out of the box.
Am I missing something ? nginx default.conf shows only listen 80; , no proxy_pass https: directive.

Thanks in advance for your help!
Lok

**Comment by hennaboy** [comment]
Has never worked with SSL has been the case for over 2 years ago when I contacted them about the same problem.

Then you also have the problem that out of the box it has weak ciphers which if you have to pass PCI compliance then you will fail.

**Comment by fevangelou** [comment]
@hennaboy yeah, HTTPS is not working. Some 220,000+ domains using Engintron are faking it... https://publicwww.com/websites/engintron/

@Sherlokman This can happen if the switch to port 8443 for Apache was not successful. You can manually check the port in Tweak settings for Apache and then do:
```
fuser -k 443/tcp
fuser -k 8443/tcp
/engintron.sh res
```

Or try disabling and then re-enabling Engintron.

**Comment by hennaboy** [comment]
Yeah it's not working don't care much for your apparent stats

**Comment by fevangelou** [comment]
When you're claim is like this https://www.joomlaworks.net/blog/item/275-does-not-work sorry but I couldn't answer differently...

**Comment by hennaboy** [comment]
Don't use joomla but from experience doesn't work and ciphers are weak

**Comment by Sherlokman** [comment]
@hennaboy @fevangelou , I found a way of making it work by adding virtual host (server) in nginx conf, which listens on 443 and forwards to 8443 while using same certificate from cpanel.

Just need to find a way automate this as to update each time a new domain is added or deleted.

**Comment by fevangelou** [comment]
@Sherlokman This is either way done automatically by Engintron.
