### ISSUE TITLE
502 Bad Gateway .. in some site

### ISSUE THREAD

**Issue by juanremi** [engintron/engintron#1028]
Hi,

this is the first problem that i get using engintron for more than tree months. yerterday i check some of my sites and work ok, normally. but this morning i enter to one of my sites and i got a "502 Bad Gateway", first i check the server status and was ok, actually the cpu usawe was around 1-5%.

then i proceed to check all of my sites (ex, 30) and the majority (ex 25) works fine, but some of them (ex 5) retrive the "502 Bad Gateway" error

- in some sites when i enter via domain.com:8080 i get the page without the 502's error

i ask to whm/cpanel support, but they says "nginx is outside of the official support"

i reinstall the latest stable engintron via the GUI on WHM and the problem continue.. why after this time i got this error if i dont move any config in the last days?

so.. if some sites are working fine, how can i get the error and fix that?

**Comment by WebSavvyDude** [comment]
What do your nginx error logs say?

We had this problem before and it turned out we just had too much traffic and  a lack of local TCP ports.   We had to increase the ports range

**Comment by fevangelou** [comment]
As @WebSavvyDude said, check your Nginx logs, the answer should there. A 502 usually indicates an Apache issue (it fails to pass data back to Nginx), which could be related to the app, CloudLinux limits, you name it...

**Comment by angelexevior** [comment]
Had a similar issue and it was the csf security plugin.
Make sure port 8080 is allowed in TCP_IN and TCP_OUT
