### ISSUE TITLE
Craft CMS and Blitz Cache plugin - where to put this code?

### ISSUE THREAD

**Issue by Djive** [engintron/engintron#1029]
Where to put the following code:

```
# Blitz cache rewrite
set $cache_path false;
if ($request_method = GET) {
    set $cache_path /cache/blitz/$host/$uri/$args/index.html;
}
location / {
    try_files $cache_path;
}

# Send would-be 404 requests to Craft
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
```

This is the original info from the docs:
https://putyourlightson.com/craft-plugins/blitz/docs#/?id=server-rewrites

Thanks

**Comment by fevangelou** [comment]
This is not for Nginx when it's used in proxy mode. Find the equivalent code for Apache's .htaccess.
