### ISSUE TITLE
How to change the location of Nginx logs when using the "Show last xxx log entries" link?

### ISSUE THREAD

**Issue by WebSavvyDude** [engintron/engintron#1032]
We have moved our nginx access and error logs to another location on our server due to space issues.

When we use the following:

<img width="316" alt="showlogs" src="https://user-images.githubusercontent.com/24284360/54980369-7e323900-4fe0-11e9-916e-d9aa8c27adfc.png">

It still shows the default locations of /var/log/nginx/access.log and /var/log/nginx/error.log

How can we adjust this to allow those links to point to where our nginx logs are now located?

Thanks

**Comment by fevangelou** [comment]
You need to edit the plugin file for WHM at: /usr/local/cpanel/whostmgr/docroot/cgi/engintron.php
