### ISSUE TITLE
NGINX Automatically Shutting Down

### ISSUE THREAD

**Issue by Rockyuk** [engintron/engintron#1033]
I run a full server backup everyday at 1am and I have noticed NGINX always shuts down during this process. If work is being down on my server by an engineer NGINX also shuts down and restarts? Apache server stays up just NGINX shutdown all the time. I have been using Engintron for about a year now and has always done this but i have left it as the process always restarts. Recently the process has been getting stuck and not restarting not sure if this is due to Cpanel updates.

**Comment by fevangelou** [comment]
I have no idea. It could be low available RAM abruptly forcing Nginx to restart without properly killing any existing processes. Restarting in such a way would cause Nginx to fail as it would not be able to bind to port 80 & 443.

However, even so, it's not hard to create a script that pings the server's hostname (using curl). If downtime is detected, you can use Engintron's force restart option which would kill any previous Nginx processes to properly restart Nginx. If you need guidance, I could help.
