### ISSUE TITLE
engintron broke some pages in whm

### ISSUE THREAD

**Issue by Mesharsky** [engintron/engintron#1035]
Hello i have problem with WHM after installing engintron

When i want to access for example to EasyApache 4 or mod security, or any other options in security tab thats what shows me.
https://i.gyazo.com/d4970925a17badab482be7163beb6ef2.png

Most of the setting are working with interface but this one, is gone ;/

**Comment by dylanhansch** [comment]
I'm not seeing this issue. What version of WHM are you running? I'm on v78.0.18.

Maybe try clearing your browser cache. If it's still happening, check the developer console (or equivalent) for errors loading resources.

**Comment by Mesharsky** [comment]
Its happening for all users. Im using the latest version


śr., 3 kwi 2019, 18:25 użytkownik Dylan Hansch <notifications@github.com>
napisał:

**Comment by fevangelou** [comment]
How are you accessing WHM? Through a port or via whm.domain.tld?
