### ISSUE TITLE
Where to change log format?

### ISSUE THREAD

**Issue by idevwebs** [engintron/engintron#1036]
I need to change the log format to include $scheme://$host$request_uri

Where do I do this to where it won't be wiped out or not break.

Thanks.

**Comment by idevwebs** [comment]
I've added the below using the edit nginx.conf link in the engintron Operatings links:

Note the "main" being added at the end of: access_log /var/log/nginx/access.log main;
```

    log_format main '$remote_addr [$time_local] '
'"$request_method $scheme://$host$request_uri $server_protocol" '
'$status $body_bytes_sent "$http_referer" '
'"$http_user_agent" $request_time';

    ## Logging Settings ##
    access_log /var/log/nginx/access.log main;
```

**Comment by fevangelou** [comment]
I believe these variables are default either way. In any case, yes, adapting nginx.conf is the only way to do this.
