### ISSUE TITLE
problem for accessing cpanel from https standard port and using the cpanel terminal web application

### ISSUE THREAD

**Issue by lpasquali** [engintron/engintron#1039]
Hello Fotis,

If I use to the 2083 cpanel port of one account which has the terminal application enabled, 
like: 

https://cpanel.mydomain.tld:2083 or  https://actualcpanelserver:2083

everything works as expected

but when I use the https port, which is proxied by engintron I get the error displayed in the screenshot.

from cpanel logs (/usr/local/cpanel/logs/access_logs) I get:

XXX.XXX.XXX.XXX proxy fiorikorea74 [04/11/2019:13:59:48 -0000] "GET /cpsess4515155007/websocket/Shell?rows=24&cols=267 HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" "s" "-" 8443

I'm still debugging this problem, but I somehow think it may be related to the safari problem of #993 for cpanel.* and webmail.* subdomains.

![Screenshot 2019-04-11 at 15 54 48](https://user-images.githubusercontent.com/1780406/55962978-3b27c500-5c72-11e9-897a-ef805776bcf5.png)

**Comment by fevangelou** [comment]
If a port other than 80/443 is defined, Nginx is not running there.
