### ISSUE TITLE
nginx not automatically restarting after autossl 

### ISSUE THREAD

**Issue by traderbighouse** [engintron/engintron#1040]
This is similar to closed issue https://github.com/engintron/engintron/issues/662

Environment: On a new cPanel server with 4 small clients, with a new engintron installation this week.
When autossl fetches and installs the Comodo/free SSL cert, I am having to nginx reload manually in order for nginx to detect the new SSL. 

I experienced it each time after each new client I added to the server.

Is this a new bug that was introduced recently perhaps?

**Comment by fevangelou** [comment]
Comodo certificates always had issues.

Prefer LetsEncrypt in AutoSSL. No issues there.
