### ISSUE TITLE
IPv6 Button

### ISSUE THREAD

**Issue by zstergios** [engintron/engintron#1041]
I suggest to have a button to enable/disable IPv6 support.
Probably any custom changes from users to conf files will be lost. You can display an alert.

Also on fressh install, should automatically be enabled if
1) tweak settings listen to IPv6 is On
2)  ip IPv6 is declared on WHM setup

Many ISP has preconfigured the routers to IPv6 enabled.Windows 10 some times uses IPv6 instead the IPv4. (True story from last weekend, customer could not reach my server untill I enabled the IPv6 support)

**Comment by fevangelou** [comment]
I'll add the check for IPv6.

As for IPv6 usage, it's not up to Windows 10 to use for the record. This is purely provided by the ISP and as far as I know, Cosmote in Greece is steadily switching its infrastructure to IPv6 (but not everywhere yet).

**Comment by zstergios** [comment]
Thanks Fotis. Let me know when you will release the next version

**Comment by zstergios** [comment]
I just updated and I need to do all the changes again :P

**Comment by fevangelou** [comment]
Not for this release. Hopefully the next one.

**Comment by fevangelou** [comment]
Just pushed v1.11.0 making Engintron IPv6 capable by default. Please upgrade and let me know if you see any issues.

**Comment by zstergios** [comment]
Before I upgrade I had manually enabled the IPv6.
After upgrade seems config loads IPV4 resolvers
http://prntscr.com/od915c

**Comment by fevangelou** [comment]
Both exist, but there may be a preference to IPv4 - that's not a bad thing...

**Comment by fevangelou** [comment]
I should clarify - Engintron now supports BOTH IPv4 & IPv6 at the same time. So it's required to have resolvers for both IPv4 & IPv6. Nginx will pick whichever is system-preferable.
