### ISSUE TITLE
How can cpanel users config nginx rules?

### ISSUE THREAD

**Issue by aaadipop** [engintron/engintron#1042]
I successfully installed engintron on cPanel but I don't know how to configure for one subdomain. 

I modify the /etc/nginx/conf.d/default_https.conf but I can't let everyone modify this file ... so how can I have a nginx config file / cPanel account ... for example adding a new location rule for a domain 

I try to include a custom file from that account but when I add a new cPanel account the file will regenerate without my custom include

**Comment by aaadipop** [comment]
@fevangelou please tell us if there is any option because if you can't config nginx for a cpanel account this solution is not good at all :) 

thanks

**Comment by Matthew18Dev** [comment]
Hi,

I'm waiting for something like this as well, why can't we just set up custom rules etc. for every domain, and by that I don't mean just a variable in the custom_rules file, I mean proper rules like for example the "location" directive, I needed to set up a specific location for a specific domain and I just wasn't able to do it, I either had to setup it on all of the domains at once or just don't setup it at all...

Regards

**Comment by fevangelou** [comment]
If you use location blocks under a proxy scenario, you're doing it wrong...

F.

**Comment by fevangelou** [comment]
@Matthew18Dev This will be part of Engintron Pro.
