### ISSUE TITLE
Fresh Install, non-root: You do not have sufficient permissions to access this page

### ISSUE THREAD

**Issue by mooseable** [engintron/engintron#1043]
First up I was getting "You do not have sufficient permissions to access this page" when accessing the egintron WHM plugin.

I found that on line 22 and 25 of /usr/local/cpanel/whostmgr/docroot/cgi/engintron.php that you are using str_split instead of explode. I changed str_split to explode on my instance and it resolved the permissions issue. str_split will not split a string by the newline delimiter. It will split a string by a fixed length only.

I then received error 500, because it could not access "/var/cpanel/caches/_generated_header_files/cache_keys.json" when calling "WHM::header('Engintron for cPanel/WHM', 1, 1);"

If I remove WHM::header and WHM::footer calls, it loads, although without any header/menu/footer/etc.

I have CPANEL/WHM v78.0.21 with Cloudlinux 7.6, CageFS, CXS, CFD, and the latest Engintron (php file says "@version    1.9.3")

**Comment by fevangelou** [comment]
I assume you run the installation as root and you're now trying to access the WHM UI as non-root. Unless that non-root user has elevated reseller rights, you won't be able to access the Engintron WHM UI.

**Comment by mooseable** [comment]
The reseller account in use has the "all" permission that engintron looks for. As I said, all I need to do is change str_split to explode and it passes the permissions check. WHM::header and WHM::footer is now the issue.

**Comment by fevangelou** [comment]
Since the PHP API in cPanel is somewhat incomplete, I would assume there is no proper permissions checking there. But you need these 2 API calls for Engintron to work properly...

BTW, what's the (redacted) output of /var/cpanel/resellers in your setup?
