### ISSUE TITLE
Memcached stopped working, Had to use "additional installer" instead

### ISSUE THREAD

**Issue by informdev** [engintron/engintron#1044]
Any idea why memcached would stop working after several successful months with no issues (you installed my stack for me via fiverr) - it happened on all three of my servers. I had to use the "UPDATED ON JUNE 29TH 2018" installation method mentioned in your docs to bring it back online.

It was running still, I checked, but for some reason, W3TC listed it as failed until I did the above.

It's resolved now but I thought I would still ask.

**Comment by fevangelou** [comment]
Perhaps the service just stopped for a reason. Of course, if you re-install Engintron now, you'll see the installer for Memcached (the one that does not use EA4 repos) is now updated to support latest libraries and PHP 7.3.
