### ISSUE TITLE
Support for TLS v1.0 and TLS 1.1

### ISSUE THREAD

**Issue by mommaroodles** [engintron/engintron#1045]
This really should be sorted out. Why is Engintron still supporting outdated SSL protocols?

**Comment by CarlosLopezES** [comment]
https://github.com/engintron/engintron/pull/813

Mozilla still suggests this old config, but as the author says, it's easy to solve

King regards,

**Comment by mommaroodles** [comment]
It is easy to solve - its just good to see best practices being followed

**Comment by CarlosLopezES** [comment]
I also would prefer the other way, but meanwhile...

**Comment by fevangelou** [comment]
Two words: backwards compatibility

Unless you're hosting an e-banking app on cPanel (kudos if you do), I'm pretty sure "hackers" will not notice...

**Comment by hennaboy** [comment]
Surely a PCI Compliance fail

**Comment by fevangelou** [comment]
@hennaboy It's easy to change if you depend on being PCI compliant - which BTW is a US gimmick but that's another story...

**Comment by hennaboy** [comment]
Tell that to the card providers that require you pass it every quarter! It is also an EU gimmick but still a necessity if you are using a proper card processing provider and not something like Paypal. Perhaps, the inclusion on how to change it in documentation?

**Comment by fevangelou** [comment]
In Engintron's WHM app, hit "Edit common_https.conf" and then change line 21 from:
```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
```

To:
```
ssl_protocols TLSv1.2;
```

...and restart Apache/Nginx via Engintron.

**Comment by CarlosLopezES** [comment]
Hi,

Sorry to update this, but i think that two years later, it's time to move forward on this, because, for one side, the Mozilla SSL configurator, on intermediate, now suggests only 1.2 and 1.3.

In the other hand, the SSL Tests like ssllabs.com, says that it's outdated and will be capped to grade B.

King regards,

**Comment by fevangelou** [comment]
As I mentioned already, the new TLS versions will be applied in the next update.
