### ISSUE TITLE
.NET Core not support by Ngix

### ISSUE THREAD

**Issue by bekgroupservice** [engintron/engintron#1046]
Hi mate, 

could you add the .netcore also on ngix ? 

https://nexuscore.io/dot-net-core-cpanel-setup/#1505825466164-cf3d7329-f2ba

**Comment by fevangelou** [comment]
I don't see why Engintron would have issues with the NexusCore plugin...

NexusCore does Apache to Kestrel proxying. Unless it checks for Apache and its port before that, again, I don't see any issues.

Install Engintron and have a look at its error logs.

You can also bring the NexusCore devs here if you they are interested in having our plugins work nicely together.
