### ISSUE TITLE
Question [ best config/options to ea4 ]

### ISSUE THREAD

**Issue by brinsleyparagao** [engintron/engintron#1048]
Hello...

Whats the best options to select on or off, and anothers settings to make a EA4 most compatible/performance and reliable to all general users/domains

So what the best profile to make ina new dedicated server ?

**Comment by fevangelou** [comment]
https://github.com/engintron/engintron/blob/master/cpanel/EasyApache_Profiles/EA4/Engintron_EA4_2018_v3.json
