### ISSUE TITLE
Engintron disabled starts Nginx before Apache and blocks port 443

### ISSUE THREAD

**Issue by rcgit** [engintron/engintron#1049]
Issue environment:
CENTOS v7.6
WHM v78.0.21
Engintron v1.9.3 (disabled)

When Engintron is **disabled**, we expect standard Apache to work normally, according to Engintron's 'set it and forget it' design.

But when booting up the server with Engintron DISABLED, for us Apache isn't starting properly.

After boot, if we browse to _WHM > Server Status > Apache Status_ we observe the error:

**Failed to receive status information from Apache.
Unable to connect to local httpd server.**

Then if we attempt to restart the Apache service via command line, it fails with the following error:

[root@dev ~]# apachectl restart
httpd not running, trying to start
**(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:443**
no listening sockets available, shutting down
AH00015: Unable to open logs

It appears Nginx is starting _**before**_ Apache and pre-occupying port 443, preventing Apache from starting normally as expected.

**Comment by rcgit** [comment]
For anyone expecting Nginx to be disabled after disabling Engintron, but it does **_not_** disable, here is a workaround:
```
systemctl stop nginx
systemctl disable nginx
systemctl start httpd
```
When you enable Engintron again, Nginx will **also** automatically be enabled again, too.

**Comment by rcgit** [comment]
@fevangelou I tried disabling Engintron **again** and rebooting, and this time Nginx was disabled.

I _have_ since run the **above** commands, which may have resolved the issue (for all I know).

I didn't installing Nginx manually or enable it separately. I only ever used the Engintron interface.

Happy for you to close this, or I can investigate further, but Engintron.sh looks super fine to me.

**Comment by fevangelou** [comment]
When Engintron is disabled, Nginx is switched to ports 8080 & 8443. But it's still running. And there's no issue with that. So even if you reboot the server, Nginx will come up and run on these ports only. Not on 80/443.

If things were different with you, you might want to share some additional info, e.g. was Nginx previously installed by another plugin? Did you update anything in the Engintron scripts?
