### ISSUE TITLE
cPanel Calendar and Contacts Server on 8443

### ISSUE THREAD

**Issue by tiagomreis** [engintron/engintron#1050]
By last information on cPanel documentation, the user will be able to install directly on WHM the Calendar and Contacts Server that will use the port 8443. This port is forced on engintron.sh for Apache.

https://documentation.cpanel.net/display/CKB/Calendar+and+Contacts+Server
Documentation last modified on Apr 30, 2019

> As a system administrator, you can only access CCS data through the calendar port (8443). You can manage CCS data through Horde, Roundcube, or other applications.

Workaround:
On engintron.sh, verify the usage of this port before send the change of the ports to tweak settings.

**Comment by fevangelou** [comment]
I'm pretty sure Engintron got 8443 before that feature. It would be simpler if cPanel allowed you to configure that port. Switching Engintron off 8443 is a no-go at the moment.
