### ISSUE TITLE
issue with account

### ISSUE THREAD

**Issue by deepakkr3110** [engintron/engintron#1051]
Hello

i have some accounts running on dedicated IP engintron with but its give me defaults page of cpanel,  and also if i disable engintron, domain is working fine, can you tell me what is the issue in this?

**Comment by fevangelou** [comment]
Unless these accounts are on CloudFlare, you should have no issue at all. It could also be a networking issue (resolver related) so in that case, you can add custom rules to enforce each dedicated IP to the corresponding domains. See the comments inside the "custom rules" file on Engintron (you can do that via Engintron's WHM app).
