### ISSUE TITLE
What is the correct nomenclature for SITE_URI

### ISSUE THREAD

**Issue by hubertus2017** [engintron/engintron#1053]
What is the correct nomenclature for SITE_URI
`If ($SITE_URI ~* "checkout")`
or
`If ($SITE_URI ~* "*/checkout/*")`

for real url e.g. 
https://www.xyz.de/checkout/cart/

**Comment by fevangelou** [comment]
This should be enough:
```
if ($SITE_URI ~* "/checkout/") {
    # rules go here
}
```

**Comment by hubertus2017** [comment]
Hello,
the issue seems not to be solved somehow.
History:
We ran a magento webshop without any issues.
After installation of eningtron, we faced some issues with customers seeing other customers orders, and mixed up order contents.

It was aid this is a problem of minicaching.

Then we added the following custom rules:

`if ($SITE_URI ~* "domain-xy.de/admin_francop|domain-xy.de/customer|admin|domain-xy.de/checkout|domain-xy.de/catalogsearch|cpsess|domain-xy.de/contact") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
}`

Then we seem to had no more issues (obiously?!)  the last 4 weeks. But today, again, i was doing a test order, and i saw in cart checkout the content of another customer, who wrote me he could not complete his order.

Is there anything wrong with the syntax above, or did i forget anything to be prevented from caching?

Hubertus

**Comment by fevangelou** [comment]
You mix full paths with generic keywords: "domain-xy.de/customer|admin"

Be more specific - use domain paths only.

**Comment by fevangelou** [comment]
If your rules are correct, doing a `curl -I https://URL/to/page` (from a terminal) would show PASS for Nginx.

**Comment by hubertus2017** [comment]
Hello,
thanks for your support.

Do you mean with 
"show PASS for Nginx" 
equals to:
 "X-Nginx-Cache-Status: BYPASS"   ? 

If so, my rules are working for checkout area. But we had the issue. and i don't know why.

Hubertus

**Comment by fevangelou** [comment]
Yes, that's correct, it should show BYPASS.

So if you see that, the issue may lie elsewhere in the app - unless some other sort of caching is implemented on your server.

If you provide an actual URL, I can have a look.

**Comment by hubertus2017** [comment]
Hello,
yes, i will send you the URL.

Today again: A user get an confirmation email with a different users email.

I try to see how i can send you a private message with the url....?

Hubertus

**Comment by fevangelou** [comment]
Send it over email and make sure you reference all important URLs to check.

**Comment by hubertus2017** [comment]
sorry, how to send over email, i don't see an email or a "direct-mail" Link....?

**Comment by fevangelou** [comment]
Look at the main repo page (readme.md) at the bottom.

**Comment by fevangelou** [comment]
Perhaps the issue is not Engintron here but some cache setting in Magento. Either way, you can always test the rules you add with curl. Just "curl -I" the URLs and you'll see that Engintron reports back with BYPASS.
