### ISSUE TITLE
nginx memory consumption

### ISSUE THREAD

**Issue by mitya3003** [engintron/engintron#1054]
If we use nignx as reverse proxy (not engintron) with simple configuration it uses about 0.2% of server RAM at one thread.

but nginx at engintron on same server will use 3.8% of server RAM at one thread (buy default at 8 threads it uses  30% of 16GB RAM!).

Server hosts about 2000 domains and 700 users.

Why this memory consumption so large?

**Comment by fevangelou** [comment]
One word: caching

Although I doubt it's 30% of RAM - make sure you're reading RAM consumption correctly for its processes.

Simply proxying requests has no benefit to the system.

And of course you can largely improve your server's performance (and RAM consumption) by tuning MySQL/MariaDB, PHP-FPM, Apache and the system itself.

**Comment by mitya3003** [comment]
Hello.

 

I suppose that I can mistaken.. Here is my memory consumptions

 

root     53622  0.0  3.0 637232 502372 ?       Ss   12:56   0:00 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf

nginx    53623  0.1  3.3 677700 546124 ?       D    12:56   0:02 nginx: worker process

nginx    53625  0.1  3.3 675396 544960 ?       S    12:56   0:03 nginx: worker process

nginx    53626  0.1  3.3 679540 549028 ?       D    12:56   0:03 nginx: worker process

nginx    53627  0.2  3.3 678716 548416 ?       S    12:56   0:04 nginx: worker process

nginx    53629  0.2  3.3 681540 551116 ?       D    12:56   0:05 nginx: worker process

nginx    53630  0.2  3.3 682296 550980 ?       D    12:56   0:05 nginx: worker process

nginx    53631  0.2  3.3 682124 551752 ?       D    12:56   0:06 nginx: worker process

nginx    53632  0.3  3.3 684364 554036 ?       D    12:56   0:07 nginx: worker process

nginx    53633  0.0  3.0 637488 503476 ?       D    12:56   0:00 nginx: cache manager process

 

free -m

              total        used        free      shared  buff/cache   available

Mem:          15994        7466        5337         310        3190        7739

Swap:          4095        1072        3023

 

One nginx process in TOP looks like this

 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND

53630 nginx     20   0  683952 552508   6576 S   0.0  3.4   0:05.83 nginx

 

3.4% of CPU to one thread is about 30% per 8 threads.

**Comment by fevangelou** [comment]
RAM consumption per process is the RES column (~500 kb on average). On the last example that's 3.4% of total RAM (but it also accounts for cached RAM objects and so on).

CPU consumption is ~0 is you look closely.

**Comment by ddrhost** [comment]
What settings reduce Nginx memory usage? I have servers with 20~30% memory usage with nginx.

**Comment by fevangelou** [comment]
@ddrhost Are you sure it's 20-30%? It's what the OP said too, but metrics tell otherwise. If it's indeed this high, it could be caused e.g. by longer dynamic cache times. But I can't know just by giving me a RAM percentage. You need to be more precise on usage.
