### ISSUE TITLE
nginx goes down frequenty

### ISSUE THREAD

**Issue by damchey** [engintron/engintron#1055]
Have started getting this problem from the past 2 months.

Nginx goes down frequently (sometimes multiple times in a day) and it takes about 20-30 minutes for it to automatically restart.

When it goes down, all that's in the error log is the below:

```
2019/05/14 15:13:11 [emerg] 17801#17801: bind() to 0.0.0.0:80 failed (98: Address already in use)
2019/05/14 15:13:11 [emerg] 17801#17801: bind() to 0.0.0.0:443 failed (98: Address already in use)
2019/05/14 15:13:11 [emerg] 17801#17801: bind() to 0.0.0.0:80 failed (98: Address already in use)
2019/05/14 15:13:11 [emerg] 17801#17801: bind() to 0.0.0.0:443 failed (98: Address already in use)
2019/05/14 15:13:11 [emerg] 17801#17801: bind() to 0.0.0.0:80 failed (98: Address already in use)
2019/05/14 15:13:11 [emerg] 17801#17801: bind() to 0.0.0.0:443 failed (98: Address already in use)
2019/05/14 15:13:11 [emerg] 17801#17801: bind() to 0.0.0.0:80 failed (98: Address already in use)
2019/05/14 15:13:11 [emerg] 17801#17801: bind() to 0.0.0.0:443 failed (98: Address already in use)
2019/05/14 15:13:11 [emerg] 17801#17801: bind() to 0.0.0.0:80 failed (98: Address already in use)
2019/05/14 15:13:11 [emerg] 17801#17801: bind() to 0.0.0.0:443 failed (98: Address already in use)
2019/05/14 15:13:11 [emerg] 17801#17801: still could not bind()
```

If I do a ```service nginx start``` it starts up instantly and everything works until it goes down next time.

Server has enough free RAM and disk space and the load seem normal.

Can't figure out what makes it go down.

CentOS 6.10
Cpanel v78.0.23
Engintron v1.9.3
Nginx 1.16.0
EA4 with Apache 2.4

**Comment by fevangelou** [comment]
This could mean that something attempted to restart Nginx without properly shutting down first the previous process, and thus you get the port 80/443 binding issue.

Is you server low on RAM perhaps?
