### ISSUE TITLE
Sessions & login users conflict solution

### ISSUE THREAD

**Issue by vowave** [engintron/engintron#1056]
Hello,
I had an experiment with the issue where users were getting logged in to each others accounts. I tried all the ways that @fevangelou suggested including disabling micro caching but the problem didn't get solved.
After many tries I found the right way to do this and that was to add the session names where cookies were saving to proxy_params_dynamic like this :

`if ($http_cookie ~* "(joomla_[a-zA-Z0-9_]+|userID|wordpress_[a-zA-Z0-9_]+|wp-postpass|comment_author_[a-zA-Z0-9_]+|woocommerce_cart_hash|woocommerce_items_in_cart|wp_woocommerce_session_[a-zA-Z0-9]+|sid_customer_|sid_admin_|mainusername|loginToAdmin|vow_session|PrestaShop-[a-zA-Z0-9]+)") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $EXPIRES_FOR_DYNAMIC 0;
}`
I hope this saves your time.
Regards

**Comment by fevangelou** [comment]
Actually, if you disable micro-caching with a custom rule for the given domain, you don't need to modify that file. Which means you don't need to re-edit it after you upgrade Engintron in the future.
