### ISSUE TITLE
SSL with NGINX

### ISSUE THREAD

**Issue by bhargav27** [engintron/engintron#1057]
On CENTOS 7.6 I have forwarded JAVA sites as below in config for nginx.

# domainname.com
if ($host ~ "domainname.com") {
    set $PROXY_TO_PORT 9090;
}

Which works well as http://www.domainname.com. 

Now I have installed SSL certificate for  domainname.com and when I try https://www.domainname.com in a browser, it shows me as below 
**502 Bad Gateway
nginx**

and in nginx error log on server end, i get following error.

2019/05/24 11:23:01 [error] 9344#9344: *1387996 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 111.111.111.111, server: domainname.com, request: "GET / HTTP/2.0", upstream: "https://222.222.222.222:9090/", host: "www.domainname.com"
2019/05/24 11:23:02 [error] 9344#9344: *1387996 SSL_do_handshake() failed (SSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol) while SSL handshaking to upstream, client: 111.111.111.111, server: domainname.com, request: "GET /favicon.ico HTTP/2.0", upstream: "https://222.222.222.222:9090/favicon.ico", host: "www.domainname.com", referrer: "https://www.domainname.com/"

It works well like 
1) https://www.domainname.com:8443/ which is HTML site 
But I want to secure my JAVA site which is pointed to 9090 at present.
Please help me resolve this problem.

Thanking in advance

**Comment by fevangelou** [comment]
Incoming HTTPS requests are also passed as HTTPS requests to the backend. Perhaps the Java app can't respond to that protocol. In that case, set the proxying protocol to be HTTP only.

More on this here: https://engintron.com/docs/#/pages/hosting-node-apps-on-cpanel (the example is for Node apps but it applies to others too)
