### ISSUE TITLE
How can i change default server name for nginx with engintron in cPanel ?

### ISSUE THREAD

**Issue by 007basaran** [engintron/engintron#1058]
Hello,

Firstly very thanks for Engintron service. This is very good. But i need support for nginx server name change with Engintron. This is not issue but i need help.

If you need example for this subjectly this is example : 

curl -X HEAD -i serveripaddress

Listing : 

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 28 May 2019 22:32:34 GMT
Content-Type: text/html
Content-Length: 163
Connection: keep-alive
Last-Modified: Wed, 30 Jan 2019 02:03:25 GMT
Vary: Accept-Encoding
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: xxxxxxxxxx
Accept-Ranges: bytes

Listing 2. line Server:Nginx name change.

Is it possible to make server name change for nginx without rebuild ?

Thank for help already.

**Comment by fevangelou** [comment]
No, it's not possible.
