### ISSUE TITLE
Error after updating to latest Engintron [Nginx stable]

### ISSUE THREAD

**Issue by staygre** [engintron/engintron#1059]
Hi, 
after updating to latest version Engintron for cPanel/WHM - v1.10.0 Nginx cannot load. Yesterday server updated to CLOUDLINUX 6.10 v80.0.10.  
Basically it comes up with this errror:

nginx: [emerg] invalid value "Pragma" in /etc/nginx/proxy_params_static:40
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by Redbehrend** [comment]
Same Issue Update Tanks Engintron
removed Prama from proxy_ignore_headers in file proxy_params_static
restarted and everything works.

**Comment by fevangelou** [comment]
Sorry for that guys, this was pushed a couple hours ago. Reverted back. If you update on any other servers it should work just fine now.

**Comment by staygre** [comment]
Thanks a lot for your help.
New problem came up after that. In one only account i get this error and website cannot load.

2019/05/30 12:03:37 [error] 841238#841238: *157 connect() failed (110: Connection timed out) while connecting to upstream, client: xx.xxx.xx.xx., server: websites-domain.com, request: "GET /el/home-el/ HTTP/1.1", upstream: "https://209.99.40.223:8443/el/home-el/", host: "websites-domain.com"

I read that this is Nginx upstream timed out and that i need to increase proxy_read_timeout. I increased "proxy_params_common" (from WHM Nginx menu) from 300s to 3600s but the problem remained.

When i disable Engintron website loads normally. 
Since i am not experienced with that could anyone suggest something;
Thanks in advance.

**Comment by fevangelou** [comment]
Check the site via port 8080 or 8443 (direct to Apache in other words).

As for the timeout, it's set to 300 (which is 5 mins) and is inline with Apache's timeout which is 300 seconds as well (by default). Unless you've changed the latter value to something lower.

**Comment by staygre** [comment]
Thanks a lot.

**Comment by fevangelou** [comment]
What was the issue if I may ask?

**Comment by staygre** [comment]
Of course you can.  It was not engintron issue at all. 
My client forgot to renew domain name and dns resolved to new ip address. It took some time for me to realize that since i was not informed.
Thanks again for your help and your immediate response.
