### ISSUE TITLE
CloudFlare

### ISSUE THREAD

**Issue by HOSKIAINDIA** [engintron/engintron#1060]
We Are Running Web Hosting Company And We Installed Engintron On The Server After That Our Clients Not Able To Use CloudFlare Showing Error Like This On Their Website After They Added CloudFlare To Their Site https://prnt.sc/nvqd0f, Please Help Us To Fix The Problem.

**Comment by fevangelou** [comment]
https://engintron.com/docs/#/pages/Engintron-&-CloudFlare
