### ISSUE TITLE
Updating Engintron within WHM taking a long time

### ISSUE THREAD

**Issue by WebSavvyDude** [engintron/engintron#1061]
We just tried updating Engintron through the WHM app on one of our servers and it was taking very long. (Total was near 10 minutes)

It just keeps loading or something.  At one point our websites were all down as well.  That has finally gotten back up but the update is still not finished.

Is there another way to update Engintron without bringing down the entire webserver for an extended period.  I still have another server that needs the Engintron update.

Please advise.

**Comment by fevangelou** [comment]
Do it from the terminal. Just enter:
```
/engintron.sh install
```

**Comment by brinsleyparagao** [comment]
Im have this same issue...

The install/update/unnistall take a long long time to execute and finish... more 10 minutes.

**Comment by brinsleyparagao** [comment]
> Do it from the terminal. Just enter:
> 
> ```
> $ /engintron.sh install
> ```

no work for me !

**Comment by fevangelou** [comment]
Do the process from the terminal and copy the output. Then paste it back here so I can see what's wrong.
