### ISSUE TITLE
Nginx 1.16 not working

### ISSUE THREAD

**Issue by secaliskan** [engintron/engintron#1062]
Hi, I have Centos 7 Cpanel WHM VPS.
 
I just upgrade Engintron to V1.10.0 build 20190327 and nginx stop working.
all settings same, when try starting nginx its giving:
`Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.`
**And when I checked the systemctl status it shows:**

`● nginx.service - The NGINX HTTP and reverse proxy server
   Loaded: loaded (/etc/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-05-31 17:25:45 +03; 15s ago
  Process: 23282 ExecStop=/bin/kill -s QUIT $MAINPID (code=exited, status=0/SUCCESS)
  Process: 23232 ExecStartPost=/usr/bin/chmod 0600 /var/run/nginx_status.sock (code=exited, status=1/FAILURE)
  Process: 23225 ExecStart=/usr/sbin/nginx (code=exited, status=0/SUCCESS)
  Process: 23221 ExecStartPre=/usr/bin/rm -f /var/run/nginx_status.sock (code=exited, status=0/SUCCESS)
  Process: 23217 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=0/SUCCESS)
 Main PID: 23228 (code=exited, status=0/SUCCESS)

May 31 17:25:44 vps46222.inmotionhosting.com nginx[23217]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
May 31 17:25:44 vps46222.inmotionhosting.com nginx[23217]: nginx: configuration file /etc/nginx/nginx.conf test is successful
May 31 17:25:44 vps46222.inmotionhosting.com chmod[23232]: /usr/bin/chmod: cannot access ‘/var/run/nginx_status.sock’: No such file or directory`

I can not find anything going wrong, but any attempt nginx not starting...

Please give hand on this...
regards
<img width="1280" alt="Ekran Resmi 2019-05-31 17 28 19" src="https://user-images.githubusercontent.com/16090710/58712608-913efc00-83c9-11e9-8757-4673f5ef0a61.png">

**Comment by fevangelou** [comment]
The problem seems to be here: 
```
May 31 17:25:44 vps46222.inmotionhosting.com chmod[23232]: /usr/bin/chmod: cannot access ‘/var/run/nginx_status.sock’: No such file or directory`
```

In any case, re-install and if the issue persists, do a force-restart for Nginx from Engintron's WHM app.

Let me know how it goes.

**Comment by secaliskan** [comment]
Hi Fotis thank you for the prompt reply. Yes problem is there GM it there is no such file in that location...
I reinstalled engintron but no luck.This is vps from inmotion hosting and they force to use their IMH-nginx package. This IMH nginx repos there all time.
This is strange, im using your module almost for 4-5 years on my servers without problem. This is our client and have centos7 cPanel.
I will try again. And let you know the outcome...Regards

Savaş Çalışkan 

On Cuma, Mayıs 31, 2019, 10:26 ÖS, Fotis Evangelou <notifications@github.com> wrote:


The problem seems to be here:
May 31 17:25:44 vps46222.inmotionhosting.com chmod[23232]: /usr/bin/chmod: cannot access ‘/var/run/nginx_status.sock’: No such file or directory`

In any case, re-install and if the issue persists, do a force-restart for Nginx from Engintron's WHM app.

Let me know how it goes.

**Comment by fevangelou** [comment]
This looks like a recent change at InMotion then that may have broken the installer. In any case, I doubt they rename critical files in Nginx. So do send them a ticket. Engintron uses the default Nginx repos. I don't see why you can't use them on your VPS.
