### ISSUE TITLE
Engintron Stable Line -> Disabling will not restore apache config on SSL

### ISSUE THREAD

**Issue by maxcuttins** [engintron/engintron#1063]
Disabling Engintron on 10.10 I can see all SSL hosting will suddenly stop working.
Taking a look to /etc/apache2/conf/httpd.conf I can see that apache https is still on port 8443.
So there should be an issue restoring the port from 8443 to 443.

Please check.

**Comment by fevangelou** [comment]
Nginx does not change Apache's port directly. It changes the value that is stored under Tweak Settings in WHM and then applies the changes. Perhaps cPanel failed for some reason to update or restart Apache and thus why you saw port 8443 present in Apache's httpd.conf.
