### ISSUE TITLE
Wordpress/Woocommerce API 404

### ISSUE THREAD

**Issue by thoiruddin** [engintron/engintron#1064]
Hi,

Where should I put this code on Engintron for me to enable Wordpress/Woocomerce API ?

`
try_files $uri $uri/ /index.php$is_args$args;
`

I already make one configuration file for specified domain inside /etc/nginx/ folder, but the return I have is error called "woocommerce_api_no_route" and showing "404 not found". 

Am I have to edit in "edit default.conf" or "edit your custom rules"? And where can I see "sites-available" folder?

**Comment by fevangelou** [comment]
Nginx as setup by Engintron operates as a reverse caching proxy. So these rules won't apply in your case. Any changes you want done in regards to any app on cPanel should be done on Apache .htaccess files.

**Comment by thoiruddin** [comment]
Hi,

Thanks for your replied. I understand that and going to try with wordpress .htaccess and let know the result here.

**Comment by thoiruddin** [comment]
> Nginx as setup by Engintron operates as a reverse caching proxy. So these rules won't apply in your case. Any changes you want done in regards to any app on cPanel should be done on Apache .htaccess files.

I try to change my htaccess with this one 

`SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0`

and with this

`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>`

But still it's showing this on Postman.

`
{
  "code": "rest_no_route",
  "message": "No route was found matching the URL and request method",
  "data": {
    "status": 404
  }
}
`

Can someone help me with custom htaccess for this?

**Comment by fevangelou** [comment]
You should probably ask that question at a WordPress/WooCommerce related forum.

**Comment by thoiruddin** [comment]
Hi,

Thanks. I enabled it by using JSON API Controller plugin from Wordpress site. Everything work fine now.

**Comment by fevangelou** [comment]
Great! Thanks for letting us know.
