### ISSUE TITLE
Opencart 3 home 404 error page

### ISSUE THREAD

**Issue by alegolash** [engintron/engintron#1066]
Hi,
I am using OpenCart 3.0.3.1 and I am facing a strange issue with Engintron enabled.

**No SEO enabled**
My home page gives 503 internal server error and all other pages work properly.

**SEO enabled**
My homepage gives 404 error page and all other pages work properly.

In general https://www.mydomain.com goes to 404 error page or 503 internal server error.
It needs https://www.mydomain.com/index.php in order to work properly with Engintron enabled.

Disabling Engintron everything works properly.

It seems like when Engintron is enabled, DirectoryIndex is ignored.
But I have no problem with other accounts in the same server (Joomla and Wordpress installations)

I have read a lot of posts referring some directives for Opencart in NGINX servers.
e.g. https://isenselabs.com/posts/seo-urls-in-opencart-2x

Last thing I would like to mention is that Opencart's admin folder has been renamed to "customname" with the proper changes in config.php file in admin folder.

Thanks

**Comment by fevangelou** [comment]
Nginx works as a proxy, it does not make decisions on which file to load. In other words, if there's a problem, it's in your site's .htaccess file or in OpenCart's SEF URL settings. In either case, try explicitly setting DirectoryIndex to "index.php index.html" in your site's .htaccess file as it may be overwritten by cPanel's general rule for DirectoryIndex (if it's different to "index.php index.html" of course).

**Comment by alegolash** [comment]
You are absolutely right, but disabling Engintron everything worked properly. That's why I suspected NGINX.
After further investigation, it seems that the problem comes form PHP-FPM.
When enabling Engintron and disabling PHP-FPM works properly.
Seems that now the issue persists between PHP-FPM and NGINX
Thanks!

**Comment by fevangelou** [comment]
Nginx may surface the issue but it's not THE issue. And I doubt it's PHP-FPM to blame. Dig deeper into your .htaccess rules, plugins that may be involved in URL generation/manipulation and of course Apache's default settings.

**Comment by alegolash** [comment]
Hi, I will recheck everything and let you know.
Thanks for you time!

**Comment by alegolash** [comment]
Hi,
finally you were absolutely right.
The issue caused by a ModSecurity rule "Output filter: Response body too large".
Nothing to do with ENGINTRON or PHP-FPM.
A proper configuration in mod_sec user config solved the issue.
Thanks for your time!

**Comment by fevangelou** [comment]
Good to know.
