### ISSUE TITLE
Awstats, SSL wont update, only not HTTPS

### ISSUE THREAD

**Issue by SaveTheHuman5** [engintron/engintron#1067]
Hello.
After enable engintron, and follow all  instructions to setup log in apache config area of whm, + make click on *Restore Nginx IP forwarding in Apache*  ........nothing fix the issue.
Awstats only show all traffic on non SSL section and SSL, wont update any data.
The site run with autossl.
Some idea?
This happen duet apache pickup traffic over 8443 instaed 443?
Not is a major issue,  just wont know what cause this issue, if is a real problem, if can be fixed, etc.

**Comment by fevangelou** [comment]
Try this as well: https://engintron.com/docs/#/pages/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel

This may solve logging for you. In either case, you need to dig around which files AWstats reads, so you can troubleshoot any issues.

**Comment by SaveTheHuman5** [comment]
No, that wont help.
The stats are updating, my site run 100% on SSL.
All activity before engintron install, appear on awstats under ssl section of awtats reports.
After engintron install, all the data is updated on non ssl awstats section.

**Comment by fevangelou** [comment]
I have no idea why this happens for you. And to be honest, it's out of the scope of the support I provide for Engintron. If you need accurate log processing for you (not your users) you should look at GoAccess (which is dead simple to hook up to Nginx's logs and get raw live traffic data).

**Comment by SaveTheHuman5** [comment]
Dont worry, just asking, is not a real issue, the stats are saved and work just appear like non ssl, what not is really big issue.
I think this is related to port.
Anyway not a vital issue to solve, just have a customer asking.
From my point of view use awstatas on a really  high traffic site is really a bad idea, this customer just insist.
Thk for your time!

**Comment by fevangelou** [comment]
Sorry I couldn't be of more help to you.
