### ISSUE TITLE
Front page cache not clearing on WordPress

### ISSUE THREAD

**Issue by informdev** [engintron/engintron#1068]
Hi!

Many months ago you setup my server for me and everything has been running fine since then. However, the last few months I have trouble getting the homepage of my sites to clear. I've tried clearing W3TC and even purging through the Engintron interface.

Any idea what's up?

**Comment by fevangelou** [comment]
Since nothing's changed on Engintron's side, I can only assume a change/update in W3TC causes this. What are your settings there and is dynamic caching enabled on Engintron?

**Comment by informdev** [comment]
I really haven't changed much since your original installation. I even held off on updates till 1.10 and I was experiencing the problem before that happened. I say that because, how can I check and see if dynamic caching is enabled? lol

For W3TC, it seems the issue may be fixed if I switch from memcached to Disk: Enhanced.

**Comment by fevangelou** [comment]
> how can I check and see if dynamic caching is enabled?
The file /etc/nginx/proxy_params_dynamic has a property called proxy_cache_valid, set to "200 1s" by default. What's yours?

> For W3TC, it seems the issue may be fixed if I switch from memcached to Disk: Enhanced.
This may point to a W3TC issue then.
