### ISSUE TITLE
Command Cron

### ISSUE THREAD

**Issue by Clearis** [engintron/engintron#1069]
Hi everyone, I'm trying to use cron to do the 3 tasks that appear in the image but I do not know what I should do for it. Can you help me? Thank you.
![engintron](https://user-images.githubusercontent.com/51784796/59427051-07842b00-8dda-11e9-964f-95c6a74e2a14.png)

I would like them to be executed every day since the command: 
15 02 * * * root /engintron.sh purgecache >> /dev/null 2>&1
it is not enough

**Comment by fevangelou** [comment]
Explore Engintron's CLI commands with `$ /engintron.sh --help` - then you'll know which command to use in your cron jobs.

By the way, the cron job you mention is not setup by Engintron.

**Comment by Clearis** [comment]
thanks, I did a little research yesterday and I found the exec functions. Thank you

**Comment by fevangelou** [comment]
You're welcome.
