### ISSUE TITLE
offload SSL to nginx causing redirect loop

### ISSUE THREAD

**Issue by ethaniel86** [engintron/engintron#1071]
https://engintron.com/docs/#/pages/Offload-HTTPS-traffic-to-Nginx-only

I have set SSL offload to Nginx now wordpress site getting redirect loop which is expected. Wordpress has below .htaccess 

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

How do we fix this loop with wordpress site? Thanks!

**Comment by fevangelou** [comment]
Disable that customization (it's user contributed either way) and use Really Simple SSL in WordPress to handle the redirect to HTTPS.
