### ISSUE TITLE
Custom Rules setting 

### ISSUE THREAD

**Issue by marcelodelta** [engintron/engintron#1073]
I am very happy to donate to this project. Very important and effective for cPanel server performance.

Congratulations.

We are looking for a Custom Rules setting to provide a remote link from one of our applications to the cPanel server.

I'm trying this, but it does not work.

Could anyone help?

```
if ($host ~ "libertyblue.vip") {
    set $PROXY_SCHEME "https";
    Location / {
        proxy_set_header Host $host;
        proxy_pass https://site.mwti .com.br;
        proxy_set_header X-Real-IP $remote_addr;
        deny all;
    }
}
```

**Comment by fevangelou** [comment]
This won't work because you can't have location blocks inside if statements. If we could, Engintron would be 10 times awesomer...

But fear not:
```
if ($host ~* "libertyblue.vip") {
    set $PROXY_DOMAIN_OR_IP "site.mwti.com.br";
    set $PROXY_SCHEME "https";
}
```
Done.
