### ISSUE TITLE
AutoSSL for hostname seems to not work

### ISSUE THREAD

**Issue by denisgomesfranco** [engintron/engintron#1079]
Hi.
I noticed something today on a fresh Cpanel server of mine.

Engintron was installed successfully, sites ran Wordpress faster than ever and Cpanel's AutoSSL feature worked flawlessly with Sectigo certificates that validated correctly even behind Cloudflare's proxying (had some problem with these certificates before but managed to figure out what was going on). I'm in heaven.

But then I noticed that Cpanel wasn't issuing the certificates for the server's hostname, eg., myserver.mydomain.com. As we all know, without that certificate, every time someone logs to WHM and/or tries to use services such as IMAP and SMTP may receive warnings due to Cpanel using a self-signed certificate.

I set out to investigate the problem. The error message was:
"The system failed to acquire a signed certificate from the cPanel Store because of the following error: Neither HTTP nor DNS DCV preflight checks succeeded! "

By checking the logs I found out that DNS check didn't work (because I'm using Cloudflare) but the HTTP check should work just fine. It said that it created a file named "/.well-known/pki-validation/[random hash].txt" but then it could not connect to the server to read that file.

I manually created this file and tried opening "http://myserver.mydomain.com:80/.well-known/pki-validation/[random hash].txt" on a browser (that was the exact URL shown on the log) and it displayed the file just fine.

So I tried disabling Cloudflare temporarily (so myserver.mydomain.com would resolve directly to the server's IP) but that didn't help at all.

What helped was disabling Engintron temporarily. Now the certificate was issued via HTTP validation just fine.

And now I'm curious to know how on earth would that text file be acessible via my browser but not by the validation service.

Ideas?

**Comment by fevangelou** [comment]
It was actually Cloudflare but it may have taken a while for the change in
DNS to take effect. Actually, avoid using CF for the server hostname
because if one of your clients attempts to use it e.g. with SSH,
connectivity won't be possible as CF supports specific ports (Google it).

**Comment by denisgomesfranco** [comment]
Hey @fevangelou,
That makes sense but here's the thing: Cloudflare was always disabled (grey cloud) for that specific hostname. I'm aware that CF does not pass through all ports, that's why it was disabled. I never had SSH connectivity issues.

**Comment by fevangelou** [comment]
> So I tried disabling Cloudflare temporarily (so myserver.mydomain.com would resolve directly to the server's IP) but that didn't help at all.

Looks like it was on...

P.S. https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-
