### ISSUE TITLE
huge log files

### ISSUE THREAD

**Issue by stargazerwna** [engintron/engintron#108]
Please check this:
With the module *disabled* server gets full in less than 24hours : 
root@ [/var/log]# du -sch * | grep G
6.6G    nginx
7.2G    total

**Comment by fevangelou** [comment]
Can you provide a sample of what's logged?

**Comment by stargazerwna** [comment]
I think is somekind of security issue:
 tail error.log-20160321
2016/03/21 03:12:06 [error] 30080#0: *52664801 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 216.244.83.242, server: localhost, request: "GET http://www.onesms.cn/index.asp HTTP/1.1", upstream: "http://42.56.65.147:80/index.asp", host: "www.onesms.cn", referrer: "http://www.onesms.cn"
2016/03/21 03:12:06 [error] 16712#0: *52694856 upstream prematurely closed connection while reading response header from upstream, client: 139.129.18.2, server: localhost, request: "GET http://www.zzgjj.com.cn/shoulu.asp?weburl=www.pfsw.1115271.cn", upstream: "http://67.229.168.43:80/shoulu.asp?weburl=www.pfsw.1115271.cn"
2016/03/21 03:12:06 [error] 30080#0: *52668426 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 216.244.83.242, server: localhost, request: "GET http://www.onesms.cn/index.asp HTTP/1.1", upstream: "http://163.177.158.76:80/index.asp", host: "www.onesms.cn", referrer: "http://www.onesms.cn"
2016/03/21 03:12:06 [error] 16708#0: *52670510 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 216.244.83.242, server: localhost, request: "GET http://www.onesms.cn/index.asp HTTP/1.1", upstream: "http://163.177.158.76:80/index.asp", host: "www.onesms.cn", referrer: "http://www.onesms.cn"
2016/03/21 03:12:06 [error] 28439#0: *52662796 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 216.244.83.242, server: localhost, request: "GET http://www.onesms.cn/index.asp HTTP/1.1", upstream: "http://42.56.64.27:80/index.asp", host: "www.onesms.cn", referrer: "http://www.onesms.cn"

**Comment by fevangelou** [comment]
First off, this is not a security issue. It's just traffic. And the log
reports connections on port 8080 because something just pings your
(probably) main server IP.

The logs simply indicate some sort of bot or perhaps valid site pinging a
certain domain. Since the URL requested is .asp then the IP pinged was
probably linked to some other site in the past. That site could have
vulnerable or (judging from the 2nd line) was used as an open redirector
for any URL appended to a certain base URL.

It's nothing to worry about though.

The best you should is block IP 216.244.83.242. Such rogue traffic is
normal nowadays, especially with all the IP recycling occurring.

**Comment by stargazerwna** [comment]
Perhaps you should shut down nginx service when we choose to disable the module.
The weird thing is that apache log is not full of these requests, maybe there should be an option on which port we want nginx to run (an choose a different port than 8080 - default for most proxies).

**Comment by fevangelou** [comment]
Either way you should use a firewall like CSF. In there you can cut off
outside access for port 8080 and your issues will resolved.

In the future, Engintron will have a nice configuration page for stuff like
that and yes, the "backend" port will also be configurable.

**Comment by fevangelou** [comment]
As @jfchevrette pointed out, log rotation may be wacky and indeed it's set (by default) to 52 days (at least on CentOS 6 I just checked). To fix this for now (until it's merged to the codebase) edit this file:

    /etc/logrotate.d/nginx

and change the line where it reads "rotate 52" to "rotate 7" if you want to keep logs at 7 days tops.

**Comment by fevangelou** [comment]
Fixed in https://github.com/engintron/engintron/commit/a42994bfe1d252aa25395921850de94e3044f8a5
