### ISSUE TITLE
How will Cpanel's implementation of Nginx affect Engintron?

### ISSUE THREAD

**Issue by WebSavvyDude** [engintron/engintron#1081]
As some of you may know Cpanel is releasing Nginx but only in experimental mode.  I also understand it will still be missing some key features.  Furthermore, I think it cannot act as a proxy to Apache.   

However, I wanted to know if all of that is true and how this will affect Engintron and the key differences moving forward.   What the value of using Engintron's Nginx implementation over Cpanel's Nginx is.

**Comment by fevangelou** [comment]
It's exactly as you said it is. cPanel's Nginx implementation will be a direct web serving solution. So if you choose Nginx, it will hook up to PHP-FPM directly. The upside is no Apache of course, the downside is that unless they add an option to manage FastCGI caching in Nginx, the results will be slightly better as the processing burden will be on PHP-FPM and the stack won't have much performance difference to Apache & PHP-FPM.

My guess is that they know there is Engintron as the alternative. Which is a good thing for everyone, as Engintron is more customizable and allows for true page-level caching if configured properly. Engintron also allows users to keep their .htaccess files, while cPanel's solution needs to tackle that. If they allow for including Nginx config files on "site" level, then that can be a security problem, not to mention the potential to break Nginx's configuration - so it requires some additional thinking for the proper implementation on cPanel's side.

So at the moment, it looks like Engintron is a more balanced solution as it can improve performance while maintaining 100% compatibility with Apache .htaccess files (and therefore legacy sites, accounts etc.).

If cPanel decides to allow for both proxying and direct web serving with Nginx, then Engintron will probably transform to an Nginx configuration tool. Like MySQL/MariaDB and other server components, Nginx will probably ship "bare bones". So there's always room for improvement.
