### ISSUE TITLE
Odd SSL Error on mobile data

### ISSUE THREAD

**Issue by rallisf1** [engintron/engintron#1084]
**Issue:** SSL Sites not loading on Cosmote Greece mobile carrier
**Server Setup:** cPanel 80.0.20, Engintron 1.10.0 (nginx 1.16.0), Apache 2.4.39, OpenSSL 1.0.2s, cPanel AutoSSL enabled on all domains (tested and confirmed working), 1 Shared IP (requires SNI)
**Engintron Config:** Apart from enabling IPv6 and fixing double xss headers, it's the default engintron configuration
**Tested Platforms:** Latest Chrome/Firefox on Android 7/8

### Description
So, I potentially have this issue in like forever since I setup engintron on my server (about 2 years) but it was really hard to pinpoint as my own mobile device (and quite a few others) never had this issue and people with the issue could browse just fine after having cached the certificate from wifi or other carriers, until the certificate is renewed which doesn't seem to reflect for mobile data (I can confirm nginx restarts after autoSSL runs and there are no issues from landlines/wifi).

So, to clarify, this only happens on mobile data (4G) in one local carrier (Cosmote Greece) and the only reason I can find for not being able to reproduce it on my device is that I have a new SIM card as, according to this random [post](https://forums.androidcentral.com/samsung-galaxy-s6/593955-ssl-error-3g-4g-not-wireless.html), old SIM cards can cause trouble with SSL.

I would totally buy that if the issue wasn't resolved when disabling engintron.

### Things I have tried
Apparently I don't want to disable engintron, It is a brilliant piece of software and serves a good purpose. So i tried:
- Clearing engintron cache & restarting of course
- Messing with the SSL ciphers in both apache and nginx (tried all combinations of TLS1, TLS1.1, TLS1.2)
- Switched to Let's Encrypt (in a test domain)

No changes whatsoever. Only when disabling engintron would the affected devices connect to the server's websites.

I'm really buffled with this one as I get numerous complaints every few months (not tied to the autoSSL renewal dates though) and I'm not happy with the performance without nginx. I'm really thinking of switching to Plesk because it has nginx bult-in, unless someone has some brilliant idea.

P.S. Could this be some SSL offloading (caching) issue in Cosmote's infrastructure? If so why does disabling engintron fix this? Isn't it the same SSL regardless? What weird voodoo is this anyway? :D

**Comment by fevangelou** [comment]
Perhaps Cosmote does some sort of proxying on their own in certain regions (reminds me of JS injection by Vodafone through their proxy https://www.yetanotherblog.com/2007/08/20/vodafone-transparent-proxy-bmi-javascript-at-1234/). This may indeed cause issues related to SSL.

Keep in mind that you can adjust SSL ciphers for Apache through WHM and allow e.g. for SSL v3, but Nginx only supports TLS 1.1+ in Engintron's configuration. So if their proxy is somewhat outdated, that could be an issue. This would explain why Apache works and not Nginx.

To double-verify, adjust the ciphers in Apache to use the default option (TLS only) and disable Nginx. Restart Apache just in case and check though a mobile Cosmote connection BUT using a private tab (so there is no cached SSL session). If the site works, it may be an SSL issue. In that case, try switching to LetsEncrypt (you need to delete any existing certificate first), restart Apache and re-check the site with Engintron enabled & single private tab on your mobile.

If neither of the above solutions work, you need to first test your SSL certificate for any issues (use https://www.ssllabs.com/ssltest/ for that). Then verify if proxying occurs by prepending the site's URL with "view-source:" in Chrome and examining the source HTML on your mobile.

Also check for any custom headers sent by the domains which have issues (you never know).

If it was a widespread issue and given that Cosmote is essentially Deutsche Telecom, my guess is you'd not be the first to report given Engintron's user base. So it's probably some edge case.

**Comment by rallisf1** [comment]
@fevangelou thanks for the super fast response. I'll post an update when I'm through with the tests.

**Comment by fevangelou** [comment]
BTW, this may not work nowadays but you can try it: https://stackoverflow.com/questions/4113268/stop-mobile-network-proxy-from-injecting-javascript

Adding a certain property to the Cache-Control header may apparently prevent such proxies from modifying the output.

**Comment by rallisf1** [comment]
Ok this was really stupid... I had not checked https_vhosts.php since I first set it up and with the upgrades it was reverted back to default (meaning ipv6 didn't work through nginx) and didn't notice until I checked with https://www.ssllabs.com/ssltest/ which timed out on IPv6 checks. After fixing IPv6, the issue was resolved. It seems Cosmote strictly uses IPv6 on mobile when the DNS says it's available while this isn't the case with other carriers and ISPs as far as I know.

P.S. Maybe this file shouldn't get overwritten during upgrades

**Comment by fevangelou** [comment]
The problem is that if I have IPv6 enabled by default on Nginx, any server without IPv6 support will break (aka most servers today).

What changes did you perform exactly? I might add a switch for it to make things easier...

**Comment by rallisf1** [comment]
Just performed the third step of your IPv6 guide: https://engintron.com/docs/#/pages/Enable-IPv6-support-in-Nginx

I didn't imply to have IPv6 enabled by default, just to exclude https_vhosts.php from the upgrade script so that the IPv6 functionality doesn't break for those who already use it.

**Comment by fevangelou** [comment]
I just pushed v1.11.0 - Engintron is now IPv6 capable by default. Can you test please?

**Comment by rallisf1** [comment]
Sorry for the delay, I was out of town. I can confirm the new update doesn't break IPv6 functionality as it did before. Good job mate!
