### ISSUE TITLE
$server_addr

### ISSUE THREAD

**Issue by ddrhost** [engintron/engintron#1085]
After updating Nginx the $server_addr code returns error. See below:

`2019/07/10 21:47:15 [error] 18985#18985: *126 invalid port in upstream "::ffff:192.99.227.232:8443", client: 191.240.217.128, server: xxxxx.com.br, request: "GET / HTTP/1.1", host: "www.xxxxxx.com.br"`

**Comment by ddrhost** [comment]
Resolved: https://engintron.com/docs/#/pages/Enable-IPv6-support-in-Nginx

**Comment by fevangelou** [comment]
Sorry, what was the issue exactly?

**Comment by ddrhost** [comment]
I solved by reversing the settings of steps B and C, which were enabled by default after the upgrade.

**Comment by fevangelou** [comment]
Is your server IPv6 compatible?

**Comment by ddrhost** [comment]
Yes, but the conflict nevertheless. I use $server_addr to automatically configure the sites in CloudFlare.

And he returned like this:
::ffff:192.99.227.232:8443

And not:
192.99.227.232:8443

**Comment by fevangelou** [comment]
So, it's not an out-of-the-box issue with Engintron. Valid IPv6 addresses should be wrapped in square brackets: [...]

Where did you do the modifications? I might be able to help you out get the right syntax for Nginx's auto-generated vhosts.

**Comment by ddrhost** [comment]
In custom_rules. I added:

set $PROXY_DOMAIN_OR_IP $server_addr;

**Comment by fevangelou** [comment]
If you're 100% that all traffic can be routed to IPv6 addresses, use this instead:
```
set $PROXY_DOMAIN_OR_IP "[$server_addr]";
```

or just:
```
set $PROXY_DOMAIN_OR_IP [$server_addr];
```

**Comment by ddrhost** [comment]
Thank you.

**Comment by fevangelou** [comment]
Which one worked? (there's no rush in closing an issue by the way...)

**Comment by ddrhost** [comment]
The first option worked, thank you.

`set $PROXY_DOMAIN_OR_IP "[$server_addr]";`

Now only a DNS error occurs, but the sites work.

```
2019/07/12 05:56:14 [crit] 1357#1357: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/07/12 05:56:14 [crit] 1357#1357: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
```

**Comment by fevangelou** [comment]
I recommend you don't edit the DNS resolvers. Leave the default option on which has both IPv4 & IPv6 resolvers enabled.
