### ISSUE TITLE
Engintron Update Today Caused Problems

### ISSUE THREAD

**Issue by onestop54** [engintron/engintron#1086]
After the Engintron update it stopped Nginx from restarting. I tried reinstalling,and restarting Apache and nginx and it still is down. I even did a restart and still down. Please advise?

CENTOS 7.6 [server1]  v82.0.0

**Comment by WebSavvyDude** [comment]
Will hold off on updating Engintron until there is an answer to this.   Just upgraded to Cpanel 82 as well.

**Comment by fevangelou** [comment]
Did you try force-restart via Engintron's WHM app? That should resolve any stuck processes occupying ports 80/443.

**Comment by onestop54** [comment]
Yes, I did, It prevent Nginx from coming up properly also there is no module of php-fpmset error showing. Also from the Engintron control panel we tried to reinstall and still nothing. Nginx is shown to be down and   we are just forced to work off of Apache after diabling it.

**Comment by onestop54** [comment]
Before we did the update everything was fine. Once I clicked on update and it finished the problems started.

**Comment by fevangelou** [comment]
What's the output of the Nginx Status option?

**Comment by onestop54** [comment]
If I turn on Engintron it says down.

**Comment by fevangelou** [comment]
I understand that, but I'd like to see the exact multi-line message...

**Comment by onestop54** [comment]
Where would I get this? Please note I am waiting on our tech(who may know how to fix it quicker) who initially installed it to come  in this afternoon so I will try to assist the best I can.

**Comment by fevangelou** [comment]
Engintron's WHM app, under Nginx on the left. Or via terminal, with:
`service nginx status`

**Comment by onestop54** [comment]
It now shows Redirecting to /bin/systemctl status nginx.service
Unit nginx.service could not be found.

**Comment by fevangelou** [comment]
As the message implies, Nginx is not found. Ask your guy to have a look and
get back to me.

**Comment by onestop54** [comment]
Ok, I will. I had Nginx until I did the update and everything went South.

**Comment by IT-Dave** [comment]
I updated to Engintron v1.11.0 this morning from the Engintron Interface and noticed that it was sitting on the same screen for over 10-15mins then it poped up with a error 503 but when logging into WHM noticed it was running the latest version v1.11.0

No symptoms like what the Op is seeing though. Everything now though seems to be working fine.

**Comment by fevangelou** [comment]
Thanks for reporting back @IT-Dave.

**Comment by WebSavvyDude** [comment]
So what was the problem the OP had?  I am a bit hesitant to update now for fear it might break Nginx

**Comment by fevangelou** [comment]
@WebSavvyDude Nothing will break. I'm pretty sure it's unrelated to Engintron (the OP's Nginx service is entirely missing).

**Comment by WebSavvyDude** [comment]
Ok just updated on one server and nothing broke.

**Comment by onestop54** [comment]
Here is what my tech just sent over.


[7/12/2019 8:52:45 AM] Krishna Kumar: I have investigated the issue and found that, nginx package is getting removed and not installing again when we try to reinstall the engintron .. So I installed nginx manually using yum command ..

[7/12/2019 8:53:55 AM] Krishna Kumar: Then engintron started working .. If we try to update or reinstall engintron, it will again mess up the nginx .. Their support team have to investigate why their update/reinstall script is not installing nginx

**Comment by fevangelou** [comment]
@onestop54 If it didn't work in the first place, I'm pretty sure I'd know...

**Comment by onestop54** [comment]
Hey, you asked me to have our tech take a look and get back to you. This is what I did.

**Comment by onestop54** [comment]
Not only did he identify what the problem was he also told you what he had to do to fix it.

**Comment by fevangelou** [comment]
Right... He identified what I told you already. What would be great though is if he identified what's messed up your server, preventing the script to run. Cause the script simply executes "yum install..." as well. There is no other magic way of installing things on CentOS (besides compiling from source that is...).

**Comment by imediaone** [comment]
Hi, i updated today to v1.11.0 (Build 20190710) around 24 hours back on 3 servers with WHM. In all the three cases there is increase of CPU usage by more than 50% despite no other change. 
This happened in all three servers, having different geographical locations. 

Other than Updating Engintron, there was no change done. nginx.service is running in all of them properly. Any ideas ?

**Comment by fevangelou** [comment]
@imediaone Upgrading to the latest version would not have this effect, unless you had perhaps setup a longer dynamic cache time in the past, which would be reset upon updating.

If you mainly use WordPress, you can easily bump the dynamic cache TTL from 1s to minutes (e.g. 3m as value for 3 minutes).

**Comment by imediaone** [comment]
Hi, The issue was not with engintron but with a wordpress plugin, pretty links which was used in many sites. It was updated around same time automativcally. It was creating error logfile of GB's which was causing very high load. Sorry to bother. Thanks

--- Case Solved ---
 
> 
> 
> @imediaone Upgrading to the latest version would not have this effect, unless you had perhaps setup a longer dynamic cache time in the past, which would be reset upon updating.
> 
> If you mainly use WordPress, you can easily bump the dynamic cache TTL from 1s to minutes (e.g. 3m as value for 3 minutes).

**Comment by fevangelou** [comment]
@imediaone That's good to know :)

**Comment by fevangelou** [comment]
Closing the ticket as any issues here were not related to the latest release of Engintron.

**Comment by robwent** [comment]
I had the same problem after the latest update.

It was because of the yum repo sources as noted in this thread: https://github.com/engintron/engintron/issues/788#issuecomment-459828659

I had previously renamed them to prevent errors when installing and then renamed back to the originals.

After running the engintron update through whm, nginx was then missing and the site went down.

I uninstalled, renamed the repos again (There were more than noted in the other issue since whm had updated), reinstalled, set the ip for cloudflare and it worked again.
Then renamed the repos back to the original names.

**Comment by fevangelou** [comment]
Thanks for the update @robwent (and good to see a familiar Joomla face here ;) )
