### ISSUE TITLE
Sites in the same whm are mixed together because of engintron

### ISSUE THREAD

**Issue by hukuk-net** [engintron/engintron#1088]
I have Whm and my Whm have multiple sites on the server. I installed a plugin 'called x' on the main site. I have a license about x plugin for main site. However, this x plug-in is only installed on the main site, causing unlicensed use to close other sites. But I never installed the x plug-in to other sites. My second problem was that my main site suddenly shut down just before Engintron was updated. Is that happens with every update on Engintron?

**Comment by fevangelou** [comment]
I don't understand why you don't name that other plugin...

Furthermore, the fact that it stops other sites from working is clearly the issue here (and surely not Engintron).
