### ISSUE TITLE
Network unreachable

### ISSUE THREAD

**Issue by dp41646** [engintron/engintron#1090]
Hi,

I just updated engintron to v1.11 and having this errors in log:
2019/07/17 18:40:51 [crit] 26580#26580: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53

This kind of errors are showing every few seconds, and there are a lot of this kind of errors:
2019/07/17 18:44:06 [error] 26580#26580: *3407 www.****.com could not be resolved (2: Server failure), client: ::ffff:**.***.**.**, server: localhost, request: "GET / HTTP/1.1", host: "www.****.com"

Engitron configuration is default, and I am running 80.0.22 WHM

Can anybody help with this?

**Comment by fevangelou** [comment]
Have you changed the resolvers in /etc/nginx/nginx.conf by any chance?

**Comment by vinaykumar9999** [comment]
Hi

I am facing the same issue. Nothing has been changed in /etc/nginx/ngin.conf

**Comment by dp41646** [comment]
> Have you changed the resolvers in /etc/nginx/nginx.conf by any chance?

No, nothing has been changed

**Comment by fevangelou** [comment]
Unless your server is preferring the IPv6 resolver and your provider does not support IPv6, check if your firewall in case IPv6 traffic is somehow limited.

**Comment by fevangelou** [comment]
Worse case scenario: Edit /etc/nginx/nginx.conf and comment out the current enabled line in resolvers and uncomment the one with IPv4 resolvers only.

**Comment by dp41646** [comment]
Hi,

yes, you were right. Our provider doesn't support IPv6 so that was problem. After commenting IPv6 resolver errors are gone.
But, still there are every few minutes something like this in error logs:

2019/07/19 15:16:17 [error] 7784#7784: *766 www.***.hr could not be resolved (2: Server failure), client: ::ffff:46.229.168.136, server: ***.hr, request: "GET /login HTTP/1.1", host: "www.***.hr"
2019/07/19 15:26:03 [error] 7786#7786: *2033 ***.hr could not be resolved (2: Server failure), client: ::ffff:46.187.50.117, server: localhost, request: "GET / HTTP/1.0", host: "***.hr", referrer: "http://guaranteedberth.online/"
2019/07/19 15:30:20 [error] 7785#7785: *2264 www.***.hr could not be resolved (2: Server failure), client: ::ffff:77.222.25.21, server: ***.hr, request: "GET /norveski-fjordovi-1-42 HTTP/2.0", host: "www.***.hr"
2019/07/19 15:38:31 [error] 7781#7781: *2976 www.***.hr could not be resolved (2: Server failure), client: ::ffff:77.75.79.109, server: ***.hr, request: "GET /robots.txt HTTP/1.1", host: "www.***.hr"
2019/07/19 15:39:58 [error] 7785#7785: *3008 www.***.hr could not be resolved (2: Server failure), client: ::ffff:77.75.79.109, server: ***.hr, request: "GET"

Is this connected to Google resolver, or something else?
Thank you!

**Comment by fevangelou** [comment]
Nginx has a built-in 30 min resolver cache. That's what you're probably seeing. So just restart it and it should be OK.

**Comment by vinaykumar9999** [comment]
Hi,

i am getting following errors in log  after commenting IPv6 resolver 

2019/07/19 19:11:43 [error] 5288#5288: *4961 connect() failed (110: Connection timed out) while connecting to upstream, client: ::ffff:223.105.4.250, server: localhost, request: "GET http://112.35.53.83:8088/index.php HTTP/1.1", upstream: "http://112.35.53.83:8080/index.php", host: "112.35.53.83:8088"

Is this also related to this issue ?

**Comment by fevangelou** [comment]
@vinaykumar9999 "8088" is not a port used by Engintron so it's clearly modified...

**Comment by dp41646** [comment]
Hi,
after latest WHM update there is really a lot of 502 errors. This is again from error log:

2019/08/13 11:20:19 [error] 5241#5241: *133875 www.**.hr could not be resolved (2: Server failure), client: ::ffff:213.147.111.154, server: **.hr, request: "GET / HTTP/1.1", host: "www.**hr"
2019/08/13 11:22:20 [error] 5243#5243: *134018 www.**.hr could not be resolved (2: Server failure), client: ::ffff:46.229.168.135, server: **.hr, request: "GET /norveski-fjordovi-1-42 HTTP/1.1", host: "www.**.hr"
2019/08/13 11:23:19 [error] 5246#5246: *134205 **.hr could not be resolved (2: Server failure), client: ::ffff:213.147.111.154, server: **.hr, request: "GET / HTTP/1.1", host: "**.hr"

Only modification to default setting are in resolver - I commented out ipv4 and ipv6, and left only ipv4 google dns.

Can anyone please help me?

Thx

**Comment by fevangelou** [comment]
Try re-enabling both the IPv4 & IPv6 resolvers in Engintron's /etc/nginx.conf file.
