### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by mabehiry** [engintron/engintron#1092]
I installed Engintron on a server with a shared and a dedicated IP, connected through CloudFlare, and has the plugin: ConfigServer as a proxy.
I edited custom rules files as the following:
set $PROXY_DOMAIN_OR_IP "1.1.1.1" # I typed here the shared ip

if ($host ~ "mysite.com") {
    set $PROXY_DOMAIN_OR_IP "1.1.1.2"; # I typed here the dedicated ip
}

But I'm still getting the error even after restarting all necessary services.
This repeated on 2 servers with similar configuration.
Any help with this?

**Comment by fevangelou** [comment]
This probably means that Nginx cannot communicate with Apache. Check if ports 8080 & 8443 are blocked in your firewall.

**Comment by lvdlrs** [comment]
I have the same issue 502 bad gateway, I have dns config via stackpath? How can I fix this
