### ISSUE TITLE
Same ip from Cloudflare

### ISSUE THREAD

**Issue by AmanaDEV** [engintron/engintron#1093]
Hi,
We use cloudflare and the ips coming from cloudflare are being treated as same ip is there a fix for this ?

regards,

**Comment by fevangelou** [comment]
Visitor IPs are sent via a special HTTP header when you use CloudFlare: CF-Connecting-IP.

More info here: https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

**Comment by AmanaDEV** [comment]
No I mean different users are being treated like same user and log in to same session I am testing adding this set $CACHE_BYPASS_FOR_DYNAMIC 1; and see if this fixes it

**Comment by fevangelou** [comment]
Correct, this will shut down dynamic micro-caching which may have caused brief shared-session issues.

For the record, your original post has nothing to do with your 2nd...
