### ISSUE TITLE
After update to 1.11.0 websites are slower

### ISSUE THREAD

**Issue by ribo72** [engintron/engintron#1094]
After update engintron from 1.10.0 to 1.11.0 joomla websites are loading slower

**Comment by fevangelou** [comment]
No effect in performance whatsoever as there are no changes in Nginx's proxying setup.

Look for other factors like extension updates in Joomla, changes in your hosting (if you're on a VM, the host server may have been overloaded by the addition of other VMs) etc. Use the Engintron guides (docs) to improve performance for the other components in your server (not related to Joomla components) like the database, Apache etc.

**Comment by ribo72** [comment]
Its strange. When i disabled engintron, joomla websites are faster

**Comment by fevangelou** [comment]
Highly doubt so :)

But hey, whatever makes you happy.

**Comment by ribo72** [comment]
Can you tell me please what changes you made from 1.10 to 1.11?

**Comment by ribo72** [comment]
I found it. 
i comment 
resolver                       8.8.8.8 8.8.4.4 [2001:4860:4860::8888] [2001:4860:4860::8844];
and i uncomment
resolver                      8.8.8.8 8.8.4.4;
and now they are fast again with engintron
