### ISSUE TITLE
LetsEncrypt & Engintron Strange Redirects

### ISSUE THREAD

**Issue by si0077** [engintron/engintron#1095]
I am having problems with LetsEncrypt alongside Engintron. I have around 20 websites on my cPanel server. When Ngintron is enabled, some domains I can renew their SSL certs but others throw 403 errors. DNS is correct. Some domains have been on the server for a while and have LetsEncrypt SSL already installed. Trying a dry run is successful on some but not on others. As I said, DNS is fine, same for all my domains. Strange thing is some renew some don't. Also adding a new domain fails with the 403.

Now I switch off Engintron and LetsEncrypt works fine on all domains. So I issue a certificate for the new domain successfully (Engintron Off), check the domain running in https and all is fine. Turn on Engintron again and the http loads for the domain but the https redirects to another site on my server. Turn off Engintron and the https loads correctly.

Anyone else having this problem? Everything was fine up until today.

Thank you.

**Comment by fevangelou** [comment]
Purge Nginx's cache just in case - do that from Engintron's WHM app.

**Comment by si0077** [comment]
Sorry already tried that. I have also removed and reinstalled Engintron with the same problem. Only new domains are redirecting to the default domain on the server through https with Engintron enabled.

**Comment by fevangelou** [comment]
You need to tell me the exact errors you get from L/E. Engintron is battle-tested. If issuing L/E certificates was a general problem, I'd know by now.

So you need to provide more info: have you done any modifications, any other plugins that may affect certificate issuing, did you have another plugin for Nginx before Engintron, example URL to check etc. etc.
