### ISSUE TITLE
Intermittent 404 errors

### ISSUE THREAD

**Issue by maverick85** [engintron/engintron#1099]
Hi,

I have engintron installed and I am having intermittent 404 errors and I can't seem to find any culprit.
I have gone through all the apache logs, I get absolutely nothing in this regard.

On the nginx logs I get this:

`::ffff:my.ip.addr.ess - - [14/Aug/2019:13:17:39 +0100] "POST /wp-admin/admin-ajax.php HTTP/2.0" 404 4723 "https://www.domain.com/wp-admin/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"`
and two seconds later when I hit refresh:
`::ffff:my.ip.addr.ess - - [14/Aug/2019:13:17:41 +0100] "POST /wp-admin/admin-ajax.php HTTP/2.0" 200 67 "https://www.domain.com/wp-admin/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"`

I also get this error on the browser:
404 Not Found
Please forward this error screen to www.domain.com's WebMaster.
The server can not find the requested page:
www.domain.com/wp-admin/index.php (port 443)

And I've been getting this 404's back and forth.
It's Engintron listening on port 443 as Apache is on port 8443 so this looks directly connected to Engintron/Nginx
May I get some assistance?

Cheers

**Comment by fevangelou** [comment]
No way that's Engintron/Nginx. First of all, POST requests are passed AS IS to the backend. Look for any rogue .htaccess rules or for plugins that may affect the output of your site (e.g. caching plugins in WP).
