### ISSUE TITLE
Where can one find the site-available?

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#110]
With referral-spam.conf in /etc/nginx, include it globally from within /etc/nginx/nginx.conf:

```
http {
    include referral-spam.conf;
}
Add the following to each /etc/nginx/site-available/your-site.conf that needs protection:

server {
    if ($bad_referer) {
        return 444;
    }
}
```

**Comment by fevangelou** [comment]
What is this file?

**Comment by highacid** [comment]
@fevangelou this file is to block spam in sites referrals. More details here: https://github.com/Stevie-Ray/apache-nginx-referral-spam-blacklist

**Comment by fevangelou** [comment]
According to their instructions...

a) With referral-spam.conf in /etc/nginx, include it globally from
within/etc/nginx/nginx.conf:

http {
    include referral-spam.conf;
}

My comment: add the include line right above the include lines at the end
of nginx.conf shipping with Engintron.

b) Add the following to each /etc/nginx/site-available/your-site.conf that
needs protection:

server {
    if ($bad_referer) {
        return 444;
    }
}

My comment: add only the if ($bad_referer) {...} clause in the
"custom_rules" file and it will be properly injected in the master domain
config for Nginx, as used by Engintron.

**Comment by highacid** [comment]
> add only the if ($bad_referer) {...} clause in the
"custom_rules" file and it will be properly injected in the master domain
config for Nginx, as used by Engintron.

I did not get this part.

**Comment by fevangelou** [comment]
1. In WHM, Engintron, click "Edit your custom rules for Nginx"
2. Add:

    if ($bad_referer) {
        return 444;
    }

inside that file.
3. Save and restart Nginx.
