### ISSUE TITLE
Separate error/access log per website

### ISSUE THREAD

**Issue by peterarmo** [engintron/engintron#1101]
We use the Engintron for cPanel plugin and at present all website traffic is logged to /var/log/nginx/access.log

Is it possible to split logging into a separate file for each cPanel account/domain?

**Comment by fevangelou** [comment]
Not without significant changes in many files of the plugin. Either way the 2 Nginx log files are meant for the server admin to poke around, not end users. The latter still have their Apache access/error logs to look at directly.
