### ISSUE TITLE
Problem with HTTP sites

### ISSUE THREAD

**Issue by flavioxx** [engintron/engintron#1102]
Hello
In previous versions I never had this problem.

Today I installed engintron on two new servers and all sites that use HTTP do not work.

Enjoy the connection refused message, I believe it is something with apache.
For connections with HTTPS works perfectly.
Can someone help me?

See a print: https://prnt.sc/ot61za

**Comment by fevangelou** [comment]
Have a look at the Nginx logs. Visit an HTTP page and see what is logged.

**Comment by Konkorfu** [comment]
That's why I transferred all my sites to https!
