### ISSUE TITLE
Long TTFB times for all sites after installing Engintron

### ISSUE THREAD

**Issue by risorial1** [engintron/engintron#1104]
As title suggests, I'm having issues with website load times after installing Engintron on my CPanel servers. It affects both WordPress and non PHP sites that are just static HTML. The first page load can take 5 seconds plus for TTFB according to Chrome developer tools. Subsequent loads are fast (hard reload, not locally cached) but if I wait a few minutes and try again, I get again a very long TTFB for various resources. Does not seem to be MySQL or PHP optimization given the problem exists with static HTML sites too.

I've tried reinstalling Engintron, rebooting the server, tweaking Apache settings to no avail. Where do I go from here? Any suggestions? Thanks for your help.

**Comment by risorial1** [comment]
One additional comment: Apache is configured for event MPM. Not sure if this could be an issue but it was recommended to me for performance reasons prior to installing Engintron.

**Comment by fevangelou** [comment]
Your Apache setup is not an issue. However, the behaviour of how your sites load (first slow, then fast even with a cold browser cache) indicate the issue may be somewhere in between the client and your server. Are you using a CDN perhaps? That would explain the behaviour you mentioned...

**Comment by risorial1** [comment]
Thank you for the reply! There is no CDN in between. It basically seems like the server needs to "wake up" the first time the site loads. There's a TTFB tool online I was using to measure the results and you can see consistently from all their endpoints globally, the TTFB is 5 or more seconds for the first load and if you try it again shortly after it drops to 80-400ms depending on location. If you wait several minutes and hit it again, it will be back up to 5s or more again. I am working with the server provider on troubleshooting as well but so far we haven't had any luck.

The server has ConfigServer enabled, not sure if that could be affecting it?

**Comment by fevangelou** [comment]
CSF is also not an issue. If there is nothing in-between, does the TTFB drop when you remove Engintron? Is there any chance you had another plugin for Nginx before installing Engintron? Please share as much info as possible on your stack.

**Comment by risorial1** [comment]
No other plugins for Nginx previously. I had my host (managed support) look into the issue. They played with configuration settings, PHP handlers, etc but only disabling Engintron resolved the issue.

I re-enabled it just to see, and sure enough it came back.

Specs/stack:
VPS with 4 cores
4GB RAM
CPanel 82.0.9
EasyApache 4 with Apache 2.4 (MPM_EVENT), PHP 5.6, 7.2, 7.3 + OPCache
PHP-FPM enabled
Engintron v1.11.0 build 20190710
Nginx 1.16.1
Everything else is basically OOB except for some worker config changes for Apache/PHP-FPM

Any other info that is helpful, let me know.

**Comment by fevangelou** [comment]
Check for any potential bad rules in .htaccess files that may cause delays when Apache serves content to Nginx. E.g. a broken redirect loop. I've seen this occur a couple times in the past (the users eventually cleaned up or reset their .htaccess rules and performance improved dramatically). If in doubt, create a new account with some basic PHP code in it and see how it performs.

**Comment by risorial1** [comment]
The issue occurs on basic HTML websites as well, no PHP code. 

The .htaccess is default, i.e. the only code is a 301 redirect from the base URL to www. as well as the cPanel generated code which selects the PHP handler.

I can create a new account and throw some basic content and test that as well though if you think it might behave differently.

**Comment by fevangelou** [comment]
If that's the case, something else may be badly tuned on your server and that is exposed when Nginx sits in front of Apache. The right people can always troubleshoot for you (checking the logs & resource usage, adding monitoring to verify any claims etc. etc.). If your managed hosting can't find a solution to your problems, perhaps you should consider switching hosts.

**Comment by risorial1** [comment]
Fair enough! I agree that if I am alone in this issue, it's a configuration issue elsewhere vs a bug with Engintron. I'll continue to investigate through other means and close this issue. I appreciate your prompt support and advice!

**Comment by fevangelou** [comment]
P.S.
> The .htaccess is default, i.e. the only code is a 301 redirect from the base URL to www.
This is where your problem may occur if the redirect is poorly written (there are dozens of ways to do this in Apache, not all are optimal)...

**Comment by risorial1** [comment]
True, but the issue occurs for all sites, not just that one with the redirect. Others have default WordPress .htaccess files.
