### ISSUE TITLE
Web interface permissions code does not work.

### ISSUE THREAD

**Issue by frogstarr78** [engintron/engintron#1106]
I'm attempting to bring up, once again an issue that keeps getting ignored. This is a duplicate of Issue #1024 (where no explanation was given why the issue was closed.) and of Issue #916 (where sample code was used to demonstrate the problem but was dismissed as irrelevant). Both were closed without resolution. I have now made [a patch](https://gist.github.com/frogstarr78/943a2dcd24fa95bfb207630a5f11f9d4) that  at least gets the page to load, albeit without a header and footer because, as was mentioned in both other issues, these files are not being loaded. I have tested this to still be an issue in version 1.11 of engintron.

I don't expect this is an issue with Engintron, necessarily, however, the permissions mechanism that is being used is clearly not working.

Here's the output of the /var/cpanel/resellers file:

cat /var/cpanel/resellers 
unprivileged_user:all

**Comment by fevangelou** [comment]
Engintron merely uses the PHP API of WHM. Your patch is obviously for that so you should probably target it to the cPanel team through their forums. Besides, if it affects Engintron, it also affects any other plugin that uses PHP for its WHM UI interface...

As for why I closed the topic https://github.com/engintron/engintron/issues/1024, well, see my last post there (insufficient info on the issue). I also don't see how relevant it is with your issue... And as for https://github.com/engintron/engintron/issues/916 again my explanation is clear. The error referenced is not even on Engintron to begin with...

**Comment by frogstarr78** [comment]
I'll create a bug request with cPanel.

**Comment by fevangelou** [comment]
I guess it's just their policy (that they don't support 3rd party plugins), but:
a) there is no "known issues" with Engintron (the support person seems kinda ignorant or just throwing sh*t for no reason).
b) It's a PHP WHM API issue, which Engintron is ***forced*** to use if it wants to remain on the main WHM window (unlike e.g. Munin). So, frankly, this is a bug with WHM's PHP API.

You could kindly ask that the developers/maintainers of the WHM PHP API code have a look. E.g. the menu open/collapsed state as you may have noticed is also buggy when you're in the Engintron dashboard.

**Comment by frogstarr78** [comment]
Thanks for the feedback. I updated their ticket as well, referencing the same patch.
