### ISSUE TITLE
Problem with cloudflare - engintron

### ISSUE THREAD

**Issue by petrolins** [engintron/engintron#1108]
I have a big problem with engintron and cloudflare

I have a very robust vps with engintron installed, this is a marvel, we can support 35x the amount of requests per minute than before and we can also reduce our hardware usage.

Our problem is with cloudflare, when we connect cloudflare to the site, it loads the index normally, BUT, when loading other pages it 502

ex: domain.com - loads normal
domain.com/panel - 502

**Comment by fevangelou** [comment]
Did you configure Engintron for CloudFlare? For your reference: https://engintron.com/docs/#/pages/Engintron-&-CloudFlare
