### ISSUE TITLE
Getting 403 forbidden on all php pages

### ISSUE THREAD

**Issue by moazam1** [engintron/engintron#1109]
Just installed on my fresh whm setup. Everything looks great. I am having trouble access php pages. HTML pages are working fine but PHP pages are throwing 403 forbidden error. I have disabled csf but no luck.

**Comment by fevangelou** [comment]
Look for bad .htaccess rewrites. Nginx merely responds with whataver Apache sends it to.

It also has no rule to prefer index.php files. If you see such a thing somewhere, rest assured it's not Engintron.

**Comment by moazam1** [comment]
Thanks.
