### ISSUE TITLE
Slow Page Load Times

### ISSUE THREAD

**Issue by Samjlevy1985** [engintron/engintron#1110]
I recently installed Engintron, I'm running 8 cPanel accounts with a total of 13 Wordpress websites.

The reason I installed Engintron was due to a lot of timeout errors on Loader.io tests, which it seems to have fixed.

However I am getting very long initial load times on my sites. I have tried disabling all wordpress plugins, uninstalling Redis, but I still get the same results. They very vastly from 0.24ms to 15s.

I'm running Centos 7.

Below is a test with Engintron enabled:

[root@greyhost ~]# time curl -IL socialfile.co.uk
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 17 Sep 2019 19:19:25 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 233
Connection: keep-alive
Location: https://socialfile.co.uk/
Cache-Control: max-age=0
Expires: Tue, 17 Sep 2019 19:19:25 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: Engintron

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 17 Sep 2019 19:19:35 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Tue, 17 Sep 2019 16:01:11 GMT
Cache-Control: max-age=0
Expires: Tue, 17 Sep 2019 19:19:35 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: EXPIRED
X-Server-Powered-By: Engintron

real    0m10.252s
user    0m0.043s
sys     0m0.035s

Below is a test with Engintron disabled:

[root@greyhost ~]# time curl -IL socialfile.co.uk
HTTP/1.1 301 Moved Permanently
Date: Tue, 17 Sep 2019 19:24:49 GMT
Server: Apache
Location: https://socialfile.co.uk/
Cache-Control: max-age=0
Expires: Tue, 17 Sep 2019 19:24:49 GMT
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Tue, 17 Sep 2019 19:24:49 GMT
Server: Apache
Last-Modified: Tue, 17 Sep 2019 16:01:11 GMT
Cache-Control: max-age=0
Expires: Tue, 17 Sep 2019 19:24:49 GMT
Vary: User-Agent,Accept-Encoding
Content-Type: text/html; charset=UTF-8

real    0m0.111s
user    0m0.042s
sys     0m0.035s

The tests with Engintron disabled are consistent.

**Comment by fevangelou** [comment]
Although I've never seen that before, something is obviously blocking the proxying from Nginx to Apache. But it's impossible for me to test without access to the server.
