### ISSUE TITLE
Cache and tmp file location

### ISSUE THREAD

**Issue by windsofchange** [engintron/engintron#1111]
Ref: https://engintron.com/docs/#/pages/Change-the-location-of-Nginx-cache-&-temp-files

I think the doc is outdated at the above URL

It should be chnaging values are 
    # Proxy Cache Settings
    proxy_cache_path  /var/cache/nginx/engintron_dynamic levels=1:2 keys_zone=engintron_dynamic:20m inactive=10m max_size=512m;
    proxy_cache_path  /var/cache/nginx/engintron_static levels=1:2 keys_zone=engintron_static:20m inactive=10m max_size=512m;
    proxy_temp_path   /var/cache/nginx/engintron_temp;

**Comment by fevangelou** [comment]
Thanks for that. I actually removed that document as it's no longer relevant and no user has reported issues ever since the cache paths were changed.
