### ISSUE TITLE
Javascript executed from log visualization

### ISSUE THREAD

**Issue by dcordovez** [engintron/engintron#1112]
Hello,
On more than one occasion it occurred to me that when viewing the nginx error log from engintron, javascript code that is embedded in the log is executed. (popups, redirects, alerts, etc.). It would be good to add some filter to avoid security problems.

In this case the log did not finish loading and I redirect to a page with spam.
![2019-09-25 01_31_26-2019-09-25 01_27_58-Mozilla Firefox - Visualizador de fotos de Windows](https://user-images.githubusercontent.com/19319530/65569761-129c3a80-df35-11e9-886a-c79bdecdf3cf.png)

![2019-09-25 01_43_32-2019-09-25 01_42_57](https://user-images.githubusercontent.com/19319530/65569984-f947be00-df35-11e9-94bb-082d89b06c54.png)

The contents of the log file when editing it.
![2019-09-25 01_45_20-_var_log_nginx_error log](https://user-images.githubusercontent.com/19319530/65570171-986cb580-df36-11e9-9eb6-d5133e74475d.png)

For now what I did was modify the engintron.php file by adding the strip_tags function when reading the log, and the problem has been corrected.
![2019-09-25 01_59_02-_usr_local_cpanel_whostmgr_docroot_cgi_engintron php](https://user-images.githubusercontent.com/19319530/65570661-4462d080-df38-11e9-867b-20285a1cd8de.png)

**Comment by fevangelou** [comment]
Good catch. But I think it's best to make all HTML in the logs display with HTML entities so you can actually SEE what the log reports and spot potential security issues. I'll make sure to update the log rendering code in the next update.

**Comment by geeknik** [comment]
> Good catch. But I think it's best to make all HTML in the logs display with HTML entities so you can actually SEE what the log reports and spot potential security issues. I'll make sure to update the log rendering code in the next update.

This is actually a pretty serious security risk and with the right crafted JavaScript, I can takeover CPanel accounts belonging to anyone using this software. This flaw should be patched ASAP, a CVE requested from MITRE, and all of your users informed of the risk and the need to update immediately. Just my two cents as I spend my days looking for bugs just like this.

**Comment by fevangelou** [comment]
Thanks for the reminder.

I just released v1.12.0 which addresses this issue by filtering the output in the log files before they are displayed to the WHM user.

https://engintron.com/docs/#/pages/Changelog

**Comment by geeknik** [comment]
@fevangelou This doesn't appear to be resolved, as I just got a blind xss callback from a server running v1.12.0 / Build 20200109.   The user started out at https://host:2087/, ended up at https://host:2087/user/cgi/engintron.php?op=httpd_restoreipfwd and https://host:2087/user/cgi/engintron.php?op=engintron_resall when we received the callback.  If you have an email address, I can private share with you the DOM from these requests so you can figure out where the issue is coming from. Thank you.

**Comment by fevangelou** [comment]
You can email me at: engintron [at] gmail [dot] com
