### ISSUE TITLE
error while loading shared libraries: libbrotlienc.so.1: 

### ISSUE THREAD

**Issue by rkshinde** [engintron/engintron#1114]
We are having issue with the libbrotlienc with below error

nginx -t
nginx: error while loading shared libraries: libbrotlienc.so.1: cannot open shared object file: No such file or directory

We have tried update and reinstall, completely removed engintron and again installed but getting same error when try to enable or start nginx on the server. 

We have cPanel server and apache does have mod_brotli installed with libraries at /opt/cpanel/ea-brotli/lib/

Please let me know what need to be done with this. 

PS : tried ldconfig and it did not fixed the issue.

**Comment by fevangelou** [comment]
This is obviously not part of Engintron's Nginx setup. And the problem lies on where you're attempting to load that Nginx module (if it is a module of course).

**Comment by rkshinde** [comment]
It appears to be a problem with from which repo the nginx was getting installed, it was corrected my disabling that repo problem is corrected. 

but we want to install the brotli installed for nginx, do you know the way to install it safely?

**Comment by fevangelou** [comment]
This guide is all you need: https://computingforgeeks.com/how-to-enable-gzip-brotli-compression-for-nginx-on-linux/ (obviously follow the steps for CentOS)

**Comment by gpant** [comment]
nginx from the codeit repo requires now that you install brotli from the epel repo on centos 7.

To solve your issue after installing engintron just issue the following (assuming epel is enabled):
`yum install brotli.x86_64`

**Comment by rkshinde** [comment]
Hello, 

I have used below guide to install the brotli 
https://www.majlovesreg.one/adding-brotli-to-a-built-nginx-instance

There is many other guides also to install the modules on already built nginx like 

https://www.majlovesreg.one/adding-pagespeed-to-a-running-nginx-instance

Thank you for the response and instructions, Really appreciated.

**Comment by HNematiMovil** [comment]
> nginx from the codeit repo requires now that you install brotli from the epel repo on centos 7.
> 
> To solve your issue after installing engintron just issue the following (assuming epel is enabled): `yum install brotli.x86_64`

Solved for me! Thanks alot
