### ISSUE TITLE
Unit nginx.service could not be found.

### ISSUE THREAD

**Issue by OffshoreCloud** [engintron/engintron#1115]
After a fresh install, i've this error :
Nginx Status:

Redirecting to /bin/systemctl status nginx.service
Unit nginx.service could not be found.

I've try to uninstall/reinstall but it's the same.

**Comment by fevangelou** [comment]
Did you previously use some other Nginx plugin for cPanel?

**Comment by OffshoreCloud** [comment]
Nop, its a fresh cpanel install

**Comment by fevangelou** [comment]
A "fresh install" with added 3rd party repos (which you don't even mention) CAN be the problem apparently.

**Comment by OffshoreCloud** [comment]
No 3rd repo. I've just rename repos and add nginx.repo + yum install nginx + reinstall engintron with latest stable/mainline version.
