### ISSUE TITLE
cPanel User - Check Webmail Issue

### ISSUE THREAD

**Issue by donsony** [engintron/engintron#1116]
Hi,

When Engintron is enabled, and logged in as a cPanel user, the "Check Webmail" function redirects to webmail.hostname and thereby erroring out. The issue does not happen when logged in as a WHM user.

I checked multiple times, and this issue does not happen when Engintron is disabled

**Comment by fevangelou** [comment]
Are you referring to the "jump" page where the cPanel user selects which webmail client to use or the resulting URL of the webmail client? You also need to be a little more specific on the URLs. Redact the actual domain.
