### ISSUE TITLE
Error after added internal_tmp_disk_storage_engine=MyISAM

### ISSUE THREAD

**Issue by sioulisn** [engintron/engintron#1117]
Hi Fotis,

I added in my.cnf that rule internal_tmp_disk_storage_engine=MyISAM and engintron shows Error connection refused.

I removed that line and restarted again Mysql and still got this error.
I tried to clear cache manually and reinstall but I still get the same error (without the rule).
When I disable the Engintron, apache works fine.

Do you have any workaround how to solve this?

SOLVED: Just the nginx server was down for some time. Now is up and running again succesfully

**Comment by fevangelou** [comment]
Thanks for updating your post as it might help others with a similar issue.
