### ISSUE TITLE
cPanel URL Error

### ISSUE THREAD

**Issue by ddrhost** [engintron/engintron#1118]
Hello, how are you?

When my client accesses the WHM control panel by subdomain (http://whm.dominio.com.br), they go to the "Account Information» List Accounts "page and click the cPanel icon to login directly, URL is redirected to http://cpanel.hostname.com.br:8080.

This is very strange. Redirects to server hostname and does not hide port 8080. How to resolve?

**Comment by fevangelou** [comment]
cPanel may be reading the Apache port for "http" traffic and appending it to the URL if it's different from port 80. If you check the Engintron configuration, it purely proxies all traffic to cPanel's web server when either "whm" or "cpanel" is used as subdomain. So it's more likely a cPanel bug.

**Comment by fevangelou** [comment]
You could potentially address this with some customized rules for Apache. E.g. when the subdomain matches "whm" or "cpanel" and the port is 8080, redirect to a port-less URL.
