### ISSUE TITLE
Warning message after I added this "Offload HTTPS traffic to Nginx only"

### ISSUE THREAD

**Issue by sioulisn** [engintron/engintron#1119]
Hi Fotis,

I have followed your guide for "Offload HTTPS traffic to Nginx only" and when I make a "Check configuration for errors" I receive the following warning:

> nginx:` [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
> 

Another think that I want to ask you is that when I make Traffic test with Loader.io for about 300 visitors in 30 seconds, the CPU with Engintron enabled is 50% lower than if disabled but the response time is 2 times higher than when I disable Engintron.
example: 
engintron enabled: 500ms response time
engintron disabled: 1000ms response time

I have turned on the dynamic_cache and increased caching to "48h", I only keep "dashed" the cookies. 
Caching it seems works pretty fast and website when I test by myself is super fast too.
Just the loader.io results in stress test seems not as expected.

Do you have any suggestions?

**Comment by sioulisn** [comment]
I have SOLVED the first issue by adding

> proxy_headers_hash_max_size`    1024;
 proxy_headers_hash_bucket_size 512;
> 
at  nginx.conf

I would be happy if you can give me some advises for the second issue with Loader.io

thank you in advance!

**Comment by fevangelou** [comment]
Using 48h inside the config for dynamic caching is probably overkill and perhaps it may cause issues if a site does not match the exclusion criteria.

As for why you get higher response times when Engintron is enabled, the answer is "it depends". It may be normal for the initial calls to delay a bit until cache objects are fetched. Or perhaps you have some .htaccess rules that cause issues and slow things down. I can test things if you can provide actual URLs and make sure ports 8080 and 8443 are open so I can "curl" them remotely and see how things work with and without Nginx.

**Comment by sioulisn** [comment]
for dynamic caching it seems that after the exclusions i made in custom engintron's file and I also excluded the cookies that I need, it works great and it dropped the TTFB to 80-100ms from 600ms that is a huge difference in the eye.  I am aware about the caching issues can cause and I am monitoring it since I 've done that.

I will send an email to you with my links!! Thank you in advance!

**Comment by fevangelou** [comment]
I think the performance improvement is phenomenal now :)

Kudos!

**Comment by sioulisn** [comment]
it is like AI !!! It knows before you click that you will click the URL!!!!
Dude you are the Greek Cloudflare!

thank you for all your support

**Comment by fevangelou** [comment]
It's not really magic, but it's probably the best generic reverse caching proxy implementation at the moment... 😃
