### ISSUE TITLE
question about cache folder and nginx.conf settings

### ISSUE THREAD

**Issue by dzamanakos** [engintron/engintron#1120]
Hi, i'm new to engintron (thank you for the free work) and have 2 questions.

If i want to change some nginx.conf settings and read that the best way is to include it to custom_rules files.
Can i "overwrite" parameters like resolver to that file in order to disable ipv6 and add some other dns servers? Something like :
resolver  x.x.x.x y.y.y.y
Will custom_rules file change the nginx.conf value or will give errors?

Another question is, by your experience, will be faster if i mount /var/cache/nginx/ to a ramfs system instead of disks? 
Will that result in any problems?

best regards,

**Comment by fevangelou** [comment]
You can technically add your own resolvers in custom rules and they would take precedence over the ones used in /etc/nginx/nginx.conf. Run "nginx -t" to make sure the syntax is correct and that no errors come up. If all is well, reload Nginx to have your changes take effect.

As for your 2nd question, yes, it will be faster. This is actually a recommend trick for Nginx's cache object. If however you're on fast SSDs or NVMe SSDs, it's probably not worth the hassle.

**Comment by dzamanakos** [comment]
Thank you for your help.

best regards,

**Comment by fevangelou** [comment]
Let me know if it worked.

**Comment by dzamanakos** [comment]
Hi, i've added in custom_rules the resolvers and is working.
As i'm using ssd, i'll not add in ramfs the folder at this time.
thank you for your help.

**Comment by fevangelou** [comment]
You're welcome.
