### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by visator** [engintron/engintron#1121]
hello, cpanel, cloudlinux, engintron
all last versions
after uldate yesterday i gett on oll my sites error 500. every second -3rd refreshing i get error 500 and every refresh after 500 site showing normally.

how to fix that?

**Comment by fevangelou** [comment]
It's impossible for me to know what's wrong without any reference to load, logs etc.

**Comment by visator** [comment]
not found in logs
can you please give me instructions with paths what logs you need?
load normal

**Comment by fevangelou** [comment]
Look at the error log in Engintron's WHM app. Scan the latest 100 entries for any [error] messages.

**Comment by visator** [comment]
Showing last 100 entries from /var/log/nginx/error.log

2019/10/24 07:13:24 [crit] 1767170#1767170: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:28 [crit] 1767172#1767172: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:31 [crit] 1767168#1767168: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:31 [crit] 1767172#1767172: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:32 [crit] 1767170#1767170: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:33 [crit] 1767172#1767172: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:34 [crit] 1767172#1767172: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:35 [crit] 1767171#1767171: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:35 [crit] 1767166#1767166: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:35 [crit] 1767169#1767169: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:35 [crit] 1767171#1767171: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:35 [crit] 1767170#1767170: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:35 [crit] 1767169#1767169: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:35 [crit] 1767166#1767166: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:36 [crit] 1767168#1767168: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:36 [crit] 1767168#1767168: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:39 [crit] 1767170#1767170: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:40 [crit] 1767171#1767171: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:40 [crit] 1767172#1767172: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:41 [crit] 1767170#1767170: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:41 [crit] 1767172#1767172: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:43 [crit] 1767172#1767172: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:44 [crit] 1767171#1767171: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:47 [crit] 1767166#1767166: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8888]:53
2019/10/24 07:13:47 [crit] 1767170#1767170: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:48 [crit] 1767166#1767166: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2019/10/24 07:13:48 [crit] 1767172#1767172: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53

**Comment by fevangelou** [comment]
IPv6 is enabled on your server but your hosting provider probably does not support it. As such, Engintron fails to resolve domains.

Edit the file /etc/nginx/nginx.conf and change this line https://github.com/engintron/engintron/blob/master/nginx/nginx.conf#L58 from `resolver                       8.8.8.8 8.8.4.4 [2001:4860:4860::8888] [2001:4860:4860::8844];` to `resolver                       8.8.8.8 8.8.4.4;`.

You can edit that file directly in Engintron's WHM app.

**Comment by visator** [comment]
thank you!

**Comment by visator** [comment]
closed
