### ISSUE TITLE
connect() failed from CDN server

### ISSUE THREAD

**Issue by mhdifirouzi** [engintron/engintron#1122]
hello
When we active CDN on our website CDN provider servers can't connect to our server and have this errors:
connect() failed (111: Connection refused) while connecting to upstream
upstream timed out (110: Connection timed out) while connecting to upstream
and we switched to Apache and errors was fixed.
What is problem?

**Comment by fevangelou** [comment]
If by CDN you mean CloudFlare or some other similar service, have a look at this: https://engintron.com/docs/#/pages/Engintron-&-CloudFlare

**Comment by mhdifirouzi** [comment]
Thanks @fevangelou issue fixed
