### ISSUE TITLE
97: Address family not supported by protocol

### ISSUE THREAD

**Issue by ryancom2190** [engintron/engintron#1125]
I am getting the following error when I check the configuration for errors.

`Checking Nginx configuration...
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] socket() [::]:443 failed (97: Address family not supported by protocol)
nginx: configuration file /etc/nginx/nginx.conf test failed`

It may be similar to the issue #1098 

We have a dedicated server from Godaddy that runs CentOS 6.10 with WHM 84.0.8. I installed engintron yesterday and after the installation, all the sites stopped working so I disabled it and now trying to troubleshoot this error, which I am assuming is why the sites went down.

I use the AutoSSL - Let's Encrypt, component to issue SSLs to all the sites on the server. I don't currently have a firewall installed but we do use CES. Let me know if I need to run any commands to give you more information about the server. Thanks in advance.

**Comment by fevangelou** [comment]
The latest release of Engintron supports both IPv4 & IPv6.

However, IPv6 is disabled in your system and this causes issues (when it shouldn't). Enable it using the 2nd method as described here: https://www.thegeekdiary.com/how-to-enable-ipv6-on-centos-rhel-6/

You don't have to actually use IPv6 addresses.

**Comment by ryancom2190** [comment]
This is what I get when I try to apply the changes:

> net.ipv4.ip_forward = 0
> net.ipv4.tcp_syncookies = 1
> error: "net.ipv6.conf.all.disable_ipv6" is an unknown key
> error: "net.ipv6.conf.default.disable_ipv6" is an unknown key

**Comment by ryancom2190** [comment]
Found the issue, had to edit `/etc/nginx/conf.d/default_https.conf`
Changed:
```
#listen 443 ssl http2 default_server;
listen [::]:443 ssl http2 default_server ipv6only=off;
```
To:
```
listen 443 ssl http2 default_server;
#listen [::]:443 ssl http2 default_server ipv6only=off;
```
And no get this on testing the configuration:
```
Checking Nginx configuration...
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by ryancom2190** [comment]
Would it be possible to add a link to that file under the `Edit default.conf` link in the Engintron Plugin page in WHM?

**Comment by ryancom2190** [comment]
So was testing what would happen if I just edit the link in my browser for `Edit default.conf` to to be default_https and was greeted with this...

<img src="https://cdn.joomlaworks.org/gifs/galifianakis_santa.gif" alt="Seriously?">

Well played. Looks like I'll refrain from doing things like that going forward.

On a side note: This is example of great coding, preventing people from messing with functions. This project definitely has some top-notch devs. Major props!

**Comment by fevangelou** [comment]
Haha :) Thanks for your kind words...

As a sidenote, your changes will likely be overwritten once the cron kicks in. You would need to edit the "listen" directives in all available places in Engintron's code and config files.

That's why I mentioned editing the /etc/sysctl.conf file. In your case, you also need to enable the relevant module in CentOS, so do this `$ cat /etc/modprobe.d/ipv6.conf` and if the output is or contains `options ipv6 disable=1` change it to `options ipv6 disable=0`. Then reboot the server.

**Comment by ryancom2190** [comment]
I don't actually have that file on the server it seems.

**Comment by ryancom2190** [comment]
I have been doing a little digging into Godaddy's site and our server may not have the ability to enable IPv6, so if that is indeed the case, is there some kind of work around?

**Comment by ryancom2190** [comment]
What would be the harm in just setting the permissions for `default_https.conf` to 444 so it wouldn't be overwritten?

**Comment by ryancom2190** [comment]
Closing out this issue since it seems as though my server just isn't going to let this work properly. Luckily, since CentOS 6 is reaching end of life and Godaddy is upgrading their systems, we are actually in the middle migrating over to one of their newest systems which are Engintron capable.
