### ISSUE TITLE
false down notification for cpanel services

### ISSUE THREAD

**Issue by j-nohra** [engintron/engintron#1126]
After installing engintron for cPanel, we received many false down notifications for some services like: exim, lfd, imap.
any help please?

**Comment by fevangelou** [comment]
Completely unrelated. The installation does not even restart these services.

**Comment by j-nohra** [comment]
I think it’s something related to not enough memory on server.

Thank you.

Regards,
Sent from my iPhone.
Jad NOHRA / IT Online Consultant 
jad.nohra23@gmail.com

+96171466007 
Beirut, Lebanon 

           

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks.

**Comment by fevangelou** [comment]
Nginx does not require much memory either way.
