### ISSUE TITLE
Very slow and disable

### ISSUE THREAD

**Issue by byzky** [engintron/engintron#1127]
Engintron is getting corrupted as Cpanel updates arrive.
Currently it takes about 3 minutes to enter the engintron admin panel.
When I activate Engintron, the sites start to respond very slow after a while.
It's much faster when I'm disable.
By the way, I've been using it for about 8 months. These problems have just begun.
I think there is a compatibility issue.

Edit: I reinstalled the Stable version twice.

**Comment by fevangelou** [comment]
There is no known issue. Engintron works just fine with the latest releases of cPanel.

My guess is something's changed in your server's usage. If you have a VPS server, it may relate to host server overload.

In any case, it's difficult to troubleshoot if you don't provide more context.
