### ISSUE TITLE
low traffic?

### ISSUE THREAD

**Issue by Shahzadqayyum** [engintron/engintron#1128]
HI!
one of my client is claiming that he is getting lesser traffic after moving his site to my hosting.
i just checked these logs and found this. 

::ffff:66.220.149.21 - - [25/Nov/2019:13:55:31 +0500] "GET /?p=26 HTTP/1.1" 200 8118 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
45.116.232.62 - - [25/Nov/2019:13:55:31 +0500] "GET /2019/11/24/usa-hotels-guaranteed-relaxation/ HTTP/1.1" 200 7918 "http://xxxx.site/2019/11/24/usa-hotels-guaranteed-relaxation/" "Mozilla/5.0 (Linux; Android 8.0.0; SM-G570F Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.96 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/245.0.0.39.118;]"
::ffff:45.116.121.45 - - [25/Nov/2019:13:55:32 +0500] "GET /2019/08/usa-hotels-guaranteed-relaxation/ HTTP/1.1" 200 7028 "http://xxxx.me/2019/11/24/dipka-padkon-video-leak/" "Mozilla/5.0 (Linux; Android 9; SM-A920F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/242.0.0.15.119;]"
::ffff:188.240.208.26 - - [25/Nov/2019:13:55:32 +0500] "POST /xmlrpc.php HTTP/1.1" 200 403 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.90 Safari/537.36 2345Explorer/9.3.2.17331"
::ffff:66.220.149.8 - - [25/Nov/2019:13:55:32 +0500] "GET /?p=26 HTTP/1.1" 200 8118 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
::ffff:208.113.171.195 - - [25/Nov/2019:13:55:32 +0500] "GET /wp-login.php HTTP/1.1" 200 1303 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
::ffff:157.49.249.63 - - [25/Nov/2019:13:55:32 +0500] "GET /?p=11 HTTP/1.1" 200 8042 "http://xxxx.com/?p=13" "Mozilla/5.0 (Linux; Android 8.1.0; vivo 1723 Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.116 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/231.0.0.39.113;]"
::ffff:208.113.171.195 - - [25/Nov/2019:13:55:32 +0500] "POST /wp-login.php HTTP/1.1" 200 1688 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
::ffff:208.113.171.195 - - [25/Nov/2019:13:55:32 +0500] "POST /xmlrpc.php HTTP/1.1" 200 236 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
::ffff:106.193.242.109 - - [25/Nov/2019:13:55:32 +0500] "GET /2019/08/sirtaj-beverly-hills-cheap-usa-hotel/ HTTP/1.1" 200 7192 "http://hotel.primeoffer.xyz/2019/08/usa-hotels-guaranteed-relaxation/" "Mozilla/5.0 (Linux; Android 9; vivo 1909 Build/PKQ1.190302.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.136 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/241.0.0.17.116;]"
::ffff:106.215.220.150 - - [25/Nov/2019:13:55:33 +0500] "GET /2019/08/usa-hotels-guaranteed-relaxation/ HTTP/1.1" 200 7028 "http://xxxxx.me/2019/11/24/dipka-padkon-video-leak/" "Mozilla/5.0 (Linux; Android 7.0; vivo 1713 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/242.0.0.15.119;]"
::ffff:54.36.150.163 - - [25/Nov/2019:13:55:33 +0500] "GET /hurricanes-upset-stars-big-semi-final/ HTTP/2.0" 404 238 "-" "Mozilla/5.0 (compatible; AhrefsBot/6.1; +http://ahrefs.com/robot/)"

all of these logs are from his site. can you please tell me what going wrong there?

my server only has IPv4 addresses and i dont even have IPv6.
any help will be appreciated!
thanks

**Comment by fevangelou** [comment]
I don't see anything wrong.

You may not have an IPv6 compatible IP, but that does not mean that another server using IPv6 can't reach your server (and sites).

**Comment by Shahzadqayyum** [comment]
thanks fevangelou!
then why these errors are generating under logs if everything is right?
they are so many. Even i have set crons to remove cache and error logs every 2 hour

**Comment by fevangelou** [comment]
These are access logs, not errors.
