### ISSUE TITLE
CORS headers from Apache not being passed through NGINX

### ISSUE THREAD

**Issue by mctaguma** [engintron/engintron#1129]
Hi all,

I'm adding an Access-Control-Allow-Origin header in a .htaccess file in a cPanel account, on a cPanel server running cPanel v84.0.15 and Engintron 1.11.0.
I see the header in a curl request to httpd, but not nginx.
Why would this be occurring?

I see this eluded to in https://github.com/engintron/engintron/issues/700#issuecomment-383042832, but was unable to find a mention of this in the changelog.

```[root@server ~]# curl -I http://example.com:8080
HTTP/1.1 302 Found
Date: Fri, 29 Nov 2019 01:22:54 GMT
Server: Apache
Access-Control-Allow-Origin: https://example.com
Location: https://example.com/
Content-Type: text/html; charset=iso-8859-1

[root@server ~]# curl -I https://example.com
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 29 Nov 2019 01:23:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/7.2.25
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: PHPSESSID=55adab5338e162492c3506c70af27d1e; expires=Fri, 06-Dec-2019 01:22:59 GMT; Max-Age=604800; path=/; HttpOnly
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: Engintron```

**Comment by fevangelou** [comment]
Engintron's Nginx setup does not re-write that header. If it's not passing though Nginx, then it's not set properly. The Nginx config is open to browse.

**Comment by fevangelou** [comment]
Closing as not active.
