### ISSUE TITLE
some issue about nginx config

### ISSUE THREAD

**Issue by PrimeNetworks** [engintron/engintron#1130]
Hello,
I have some issue with the engintron configuration file.
i have some code must be included into configuration file as requirement : 
- Add the following block to domain nginx config for preventing direct access to your video files:
# protect videos from direct access
location /contents/videos/ {
root /home/username/public_html;
limit_rate_after 2m;
internal;
}

when im doing that for nginx config file and restart the nginx the all sites not working and the nginx not started per some wrong configuration , where i can use this code im own vps with 3 ips first one for the hostname and second ip is dedicated to the only hosted site , i need any help to make this code working correctly .

Thank You

**Comment by fevangelou** [comment]
Nginx, as setup by Engintron, works as a proxy. So any configuration additions that add location blocks to certain paths/URLs will not work.

What you should do is add the equivalent of that code in your .htaccess file and Nginx will honor any restrictions.

**Comment by fevangelou** [comment]
Closing as not active.
