### ISSUE TITLE
Sometimes 404 pages or not loading pages properly

### ISSUE THREAD

**Issue by ibokahveci** [engintron/engintron#1131]
Hi Guys,
I checked too many good reviews about Engintron and I installed.

I liked the speed. Faster than Apache PHP-FPM.
But I got some issues sometimes not every time.

I'm using WordPress on some websites. I have VPS and also I have a radio station and the player is a custom script. When I was working on the WordPress part like updating products, disabling and enabling plugins, editing theme parts. Sometimes I'm getting my theme 404 page, When I try to update something like on product pages. If I wait a little bit like 1 minute everything is coming back normal. But I'm getting this problem frequently like 10 times in an hour. I was thinking this problem is maybe about the cache problem. and I purged the cache and temp files on the engintron panel.

and also at the same time, I cleared my browser cache But It didn't work. And I called my friend to check the website all my WordPress websites are coming 404 pages or some different Error like not loading radio player pages at the same time.

So this problem is not showing only to me.
also, our customers and also our listeners can see the same errors.

Also, Another problem is I'm updating some pages like front page. If I didn't like it I am removing those parts. When I got a 404 page, At the same time Some removed parts are coming back to my websites How is it possible I couldn't Understand.
I think this plugin has a cache problem. This plugin is holding cache always that's why it's making really fast the website but the problem is cache is getting headache for the development part. 

And Also I tried to uninstall Engintron. My all websites are coming really really slow. I wait 24 hours I was thinking it will come back everything That I had before. But I got more slow websites before installation. So I reinstall Engintron. But Still, I'm getting the same issues. I want to use Engintron But without issue. How can we configure these issues? Please help me to fix this.

I will also Attach My last 100 error logs here. So you can figurate it Whats going on. Thank you in advance. My websites are www.lwstone.com , www.usaradyo.com/player please check and let me know. thanks.

2019/12/04 06:15:19 [error] 24968#24968: *99891 www.lwstone.com could not be resolved (2: Server failure), client: ::ffff:73.57.164.134, server: lwstone.com, request: "POST /wp-admin/admin-ajax.php HTTP/2.0", host: "www.lwstone.com", referrer: "https://www.lwstone.com/wp-admin/admin.php?page=porto"
2019/12/04 06:17:59 [error] 24973#24973: *106255 upstream prematurely closed connection while reading upstream, client: ::ffff:192.0.86.189, server: localhost, request: "GET /cgi-sys/suspendedpage.cgi?for=jetpack&token=gpocIeVWt4wAu2zIqXgzExRGr6KH%2AhwU%3A1%3A1×tamp=1575436674&nonce=Xem1riWo4e&body-hash=pdst%2B%2B8gjpsEsdzTGdS19%2BYN3g4%3D&signature=vtmxf69gxDsBNege%2Bgjxktv4Gb8%3D HTTP/1.1", upstream: "http://178.238.229.230:8080/cgi-sys/suspendedpage.cgi?for=jetpack&token=gpocIeVWt4wAu2zIqXgzExRGr6KH%2AhwU%3A1%3A1×tamp=1575436674&nonce=Xem1riWo4e&body-hash=pdst%2B%2B8gjpsEsdzTGdS19%2BYN3g4%3D&signature=vtmxf69gxDsBNege%2Bgjxktv4Gb8%3D", host: "www.neyookki.net", referrer: "http://www.neyookki.net/cgi-sys/suspendedpage.cgi?for=jetpack&token=gpocIeVWt4wAu2zIqXgzExRGr6KH%2AhwU%3A1%3A1×tamp=1575436674&nonce=Xem1riWo4e&body-hash=pdst%2B%2B8gjpsEsdzTGdS19%2BYN3g4%3D&signature=vtmxf69gxDsBNege%2Bgjxktv4Gb8%3D"
2019/12/04 08:14:31 [error] 24972#24972: *113175 www.neyookki.com could not be resolved (2: Server failure), client: ::ffff:46.229.168.153, server: neyookki.com, request: "GET /kategori-12349-3-8.html?daralt=1&il=34&sayfa=1&sayfa=1 HTTP/1.1", host: "www.neyookki.com"
2019/12/04 09:36:20 [error] 24973#24973: *116825 digitalcolorcenter.com could not be resolved (2: Server failure), client: ::ffff:118.25.79.17, server: localhost, request: "GET /wp-login.php HTTP/1.1", host: "digitalcolorcenter.com"
2019/12/04 12:52:40 [error] 24968#24968: *125564 connect() failed (110: Connection timed out) while connecting to upstream, client: ::ffff:182.61.163.32, server: localhost, request: "GET http://weibo.com/ HTTP/1.1", upstream: "http://36.51.254.234:8080/", host: "weibo.com"
2019/12/04 12:54:47 [error] 24968#24968: *125564 connect() failed (110: Connection timed out) while connecting to upstream, client: ::ffff:182.61.163.32, server: localhost, request: "GET http://weibo.com/ HTTP/1.1", upstream: "http://180.149.138.56:8080/", host: "weibo.com"
2019/12/04 12:54:48 [error] 24968#24968: *125564 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:182.61.163.32, server: localhost, request: "GET http://weibo.com/ HTTP/1.1", upstream: "http://180.149.134.141:8080/", host: "weibo.com"
2019/12/04 12:56:55 [error] 24968#24968: *125564 connect() failed (110: Connection timed out) while connecting to upstream, client: ::ffff:182.61.163.32, server: localhost, request: "GET http://weibo.com/ HTTP/1.1", upstream: "http://180.149.134.142:8080/", host: "weibo.com"
2019/12/04 12:59:02 [error] 24968#24968: *125564 connect() failed (110: Connection timed out) while connecting to upstream, client: ::ffff:182.61.163.32, server: localhost, request: "GET http://weibo.com/ HTTP/1.1", upstream: "http://180.149.134.142:8080/", host: "weibo.com"
2019/12/04 13:01:10 [error] 24968#24968: *125564 connect() failed (110: Connection timed out) while connecting to upstream, client: ::ffff:182.61.163.32, server: localhost, request: "GET http://weibo.com/ HTTP/1.1", upstream: "http://180.149.138.56:8080/", host: "weibo.com"
2019/12/04 13:01:10 [error] 24968#24968: *125564 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:182.61.163.32, server: localhost, request: "GET http://weibo.com/ HTTP/1.1", upstream: "http://180.149.134.141:8080/", host: "weibo.com"
2019/12/04 16:29:57 [error] 24972#24972: *136173 neyookki.com could not be resolved (2: Server failure), client: ::ffff:46.229.168.141, server: neyookki.com, request: "GET /kategori-35794-elektronik-devre.html?daralt=1&il=46&sayfa=1&sayfa=1&sayfa=1&sayfa=1 HTTP/1.1", host: "neyookki.com"
2019/12/04 16:56:19 [error] 24972#24972: *137312 www.neyookki.net could not be resolved (2: Server failure), client: ::ffff:54.36.148.233, server: localhost, request: "GET /dinlesene/artist/Lana+Del+Rey HTTP/1.1", host: "www.neyookki.net"

**Comment by fevangelou** [comment]
Engintron does micro-caching by default (1 sec only), so it won't cache HTML content. It does have a 1 min cache for static assets like CSS, JS, images etc. but you can easily turn that off using custom rules (either for the whole server or for specific domains).

There are currently more than 200,000 websites powered by Engintron out of the top 1 million sites worldwide: https://publicwww.com/websites/engintron/

So, yes, Engintron works as expected.

The fact that you had slowdowns, then removed Engintron and it got worse, clearly indicates that the (physical) host server that your VPS is on has performance issues. It could be high CPU or RAM or disk I/O usage caused by other VPSs on that server.

As I can see, your VPS is at Contabo. And since Contabo offers the best spec to money ration, they are very popular and as such, some folks may overuse their good specs. If you're on a busy host, send them an email and kindly ask them to move you to another host server that is less busy (I've done this twice in the past as I use them too).

**Comment by ibokahveci** [comment]
But I was using my website under the same traffic and every day I was updating products and other stuff and I never get any issue in Contabo and I never get the issue before engintron installation. After installation server is the same server WordPress is the same WordPress and my plugins and other stuff are the same. Ok, my website is responding really fast that's true. But If I crash 10 times in an hour. Who cares about the speed. Right now I couldn't go back because When I uninstall Engintron My VPS server is getting idiot. I do not know what I can do. I can Contact the Contabo but I think I will get the same issues. Because these issues come with Engintron and Strange Issue because It's not doing these issues every time So It's really hard to figurate it. I'm Really Disappointed. I do not know what can I do for the solution? Do you have any paid customer support services?

**Comment by fevangelou** [comment]
Again, THAT is why you need to contact Contabo and kindly ask them to move to a different physical server which is less busy.

A VPS server cannot magically preserve its performance at the same level, all the time. This is by design, as it shares a physical server with other VPSs. If one of the VPSs causes e.g. strain to the disks or consumes more CPU (polling) than it can, this will eventually create issues to the other VPSs on the same physical server.

All these have nothing to do with Engintron, which, when you uninstall, is completely removed from your server and reverts everything back as they were.

**Comment by ibokahveci** [comment]
I understand. But I need to understand one more thing. if the server causes physically, WHM/Cpanel can cause or crash too right? But When Our website can get 404 pages at the same time I'm trying to login and check WHM and WHM part is loading and working properly. How is it possible? I'm checking Process Manager and Load Averages everything looks perfect. I will contact them but I need more explanation. Sorry About that. Really Thank you for your help. You are really helpful.

**Comment by fevangelou** [comment]
I have already explained the issue in detail.
