### ISSUE TITLE
[Duplicate] Sometimes 404 pages or not loading pages properly #1131

### ISSUE THREAD

**Issue by ibokahveci** [engintron/engintron#1132]
I understand. But I need to understand one more thing. if the server causes physically, WHM/Cpanel can cause or crash too right? But When Our website can get 404 pages at the same time I'm trying to login and check WHM and WHM part is loading and working properly. How is it possible? I'm checking Process Manager and Load Averages everything looks perfect. I will contact them but I need more explanation. Sorry About that. Really Thank you for your help. You are really helpful.

_Originally posted by @ibokahveci in https://github.com/engintron/engintron/issues/1131#issuecomment-561886622_

**Comment by fevangelou** [comment]
Do not cross post please. You can respond to a closed issue, no need to open a new one.
