### ISSUE TITLE
hosts file

### ISSUE THREAD

**Issue by visator** [engintron/engintron#1133]
hi, please advice why it dont work with engintron.
we wish to test site on our server. now this site hosted on another server.
we adding same domain to our server, the we adding our ip to my windows hosts file.
ping going on our server but we get 502.

/var/log/nginx/error_log:
2019/12/05 19:24:27 [error] 767686#767686: *69 connect() failed (110: Connection timed out) while connecting to upstream, client: 176.213.x.x, server: localhost, request: "GET /index.php HTTP/1.1", upstream: "http://217.146.x.x:8080/index.php", host: "mydomain.eu"

how to fix? can i change site ip in engintron?

**Comment by fevangelou** [comment]
It's all in the documentation: https://engintron.com/docs/#/pages/Engintron-and-under-development-domains-that-dont-yet-resolve-point-to-your-cPanel-server
