### ISSUE TITLE
I figurate it the Issue Please check for your next update. Thanks

### ISSUE THREAD

**Issue by ibokahveci** [engintron/engintron#1134]
Hi, Sorry for bothering you again.
I contacted my server and the server told me their part is working properly.
And I tried something and I found the cause.
Your Plugin has a conflict with Mod_Evasive and also Mod_Security2.
I uninstalled those apache Modules from my system and right now everything is working Perfectly.
Right Now I'm installing and Uninstalling your plugin. I didn't get any issues. I tested too many times with my different webpage. So I just wanted to tell you this. Maybe You can check those modules to fix that. Also thanks for your help. Have a great day.

**Comment by fevangelou** [comment]
Engintron does not conflict with any Apache modules. However, improper configuration for these modules (which control how traffic flows to your server) will obviously increase the load in your server. A stock cPanel installation with Engintron plus CSF is all you need for a fast, secure server. And if you need good EA4 profiles, they come bundled with Engintron: https://github.com/engintron/engintron/tree/master/cpanel/EasyApache_Profiles/EA4
