### ISSUE TITLE
Updated to 1.11 from 1.9.2

### ISSUE THREAD

**Issue by Aeox-cdt** [engintron/engintron#1136]
Hello,

I updated from v1.11 from 1.9.2 and now i'm receiving the following errors:

nginx[19584]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx[19584]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] still could not bind()

Tweak settings already show Apache non-SSL port on 0.0.0.0:8080 and SSL port on 0.0.0.0:8443.

netstat shows nothing on port 80 or 443

I've uninstalled and reinstalled and cleared old files.

I've noticed that if i clear what i had in default.conf then i receive no errors and nginx doesn't fail.

below is what i had in default.conf:

server {
    listen 80;
    listen [::]:80;
    server_name;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name;
    
    ssl_certificate;
    ssl_certificate_key;

    ssl_prefer_server_ciphers on;
    ssl_ciphers "AES256+EECDH:AES256+EDH"; 
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass https://<REDACTED>;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_redirect off;
        server_tokens off;
    }
}

This worked fine in v1.9.2. I have a node js app running which i'm using engintron/nginx as the proxy for.

**Comment by fevangelou** [comment]
Run "nginx -t" and it will show you where Nginx's configuration compilation fails.

But to be honest, your changes are insignificant and some are outright placed in the wrong location. You should let Engintron do its thing. There's a reason "it just works".

**Comment by Aeox-cdt** [comment]
"nginx -t" is showing:

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by Aeox-cdt** [comment]
Nevermind! looks like removing "listen 443 ssl http2;" but keeping "listen [::]:443 ssl http2;" has solved it.

Many thanks for your reply

**Comment by fevangelou** [comment]
👍
