### ISSUE TITLE
Problem on adding dedcated ip

### ISSUE THREAD

**Issue by EvangelosBalafoutis** [engintron/engintron#1137]
Hello.

I have setup engintron on a server with a share ip and 2 dedicated ips.
I add the rules

set $PROXY_DOMAIN_OR_IP "136.243.177.70"; --> Shared Ip
if ($host ~ "domain1") {
    set $PROXY_DOMAIN_OR_IP "136.243.177.115"; ---> Dedicated Ip for domain1
    }

All sites in 136.243.177.70 they are in CloudFlare working ok.
The domain1 that is NOT in cloudflare but it has its own ip working ok.

Then I add a second domain with its own DEDICATED Ip and the code seems like this

set $PROXY_DOMAIN_OR_IP "136.243.177.70";
if ($host ~ "domain1") {
    set $PROXY_DOMAIN_OR_IP "136.243.177.115";
if ($host ~ "domain2") {
    set $PROXY_DOMAIN_OR_IP "136.243.177.79";
}

After that NOTHING is working.

What am I doing wrong?

**Comment by fevangelou** [comment]
Look closer and you'll notice that the syntax is incorrect. "If" statements must be properly closed. You could also make it more readable:
```
# Shared IP
set $PROXY_DOMAIN_OR_IP "136.243.177.70";

# Domain 1
if ($host ~ "domain1") {
    set $PROXY_DOMAIN_OR_IP "136.243.177.115";
}

# Domain 2
if ($host ~ "domain2") {
    set $PROXY_DOMAIN_OR_IP "136.243.177.79";
}
```

**Comment by EvangelosBalafoutis** [comment]
Thank you Fotis.
 I add just the domain that is on cloudflare and everything is working perfect. But Ill try your suggestions and let you know.

if ($host ~ "domain.proxy") {
    set $PROXY_DOMAIN_OR_IP "136.243.177.70";
    }

**Comment by fevangelou** [comment]
👍

**Comment by EvangelosBalafoutis** [comment]
I paste your code and its working perfect. Thank you so very much for the help.
