### ISSUE TITLE
Configuration test

### ISSUE THREAD

**Issue by EvangelosBalafoutis** [engintron/engintron#1138]
Hello Fotis.
I tested the configuration test and I got a warn
How can I fix that?

Checking Nginx configuration...
nginx: [warn] conflicting server name "mail.netwist.com" on [::]:443, ignored
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by fevangelou** [comment]
Re-built your Apache configuration. Just open the configuration page and hit save.

For some reason you have a double entry for that subdomain and this causes issues. Alternatively, locate the subdomain's duplicate entry from the cPanel user's account and delete it.

**Comment by EvangelosBalafoutis** [comment]
I figure out there was an alias on another domain. Thank you so very much.
