### ISSUE TITLE
Cloudflare port 443 issue?

### ISSUE THREAD

**Issue by Shahzadqayyum** [engintron/engintron#1139]
Hello!
One of my clients has a website!
when he use cloudflare DNS only? it works fine. but he use flexible/ full ssl with proxy? he gets 502 errors! though cloudflare on other sites are working fine but not on this specific website!
I've searching on internet since last night!

tried Adding domain IP in custom rules. settings for cloudflare also, disabled micro caching.
Nothing worked!
but found something like this;
If you have just moved to Cloudflare and you are seeing a 521 over HTTPS, it is possible that your origin server has not been configured to allow port 443 be accessed by Cloudflare IPs. In this case you should configure your server/firewall to being listening on port 443 and allow us to be able to conect. If this is not possible, you can move to using ‘Flexible’ SSL under the SSL/TLS app on the dashboard.

Not sure what to do? Please help?

So my question

**Comment by Shahzadqayyum** [comment]
If I disable cloudflare protection from cloudflare dns? site loads without any issue! But as soon as i enable cloudflare protection button it only loads 521 errors. not even a single page opens!
please help!
http://prntscr.com/qggmzy

(I dont want to add my site url here thats why added screenshot link)

**Comment by josephmiller2000** [comment]
@Shahzadqayyum Now a days you can get free SSL certificates. If you are using cpanel, then you can install free AUTO SSL certificate and change the cloudflare SSL settings to "STRICT FULL MODE" . WHich allows browsers to fetch the right certificate from the domain server instead of cloudflare.

This will fix you issue.

**Comment by Shahzadqayyum** [comment]
> @Shahzadqayyum Now a days you can get free SSL certificates. If you are using cpanel, then you can install free AUTO SSL certificate and change the cloudflare SSL settings to "STRICT FULL MODE" . WHich allows browsers to fetch the right certificate from the domain server instead of cloudflare.
> 
> This will fix you issue.

Tried everything. even disabled firewall from my server, disabled ssl fully from my host and cloudflare still 521 error! not sure whats wrong?

**Comment by fevangelou** [comment]
Does the domain resolve properly to the server? If all other domains do, then something is misconfigured in CF for that domain (obviously).

**Comment by Shahzadqayyum** [comment]
H/i Fotis!
Right now you can see if you check dns!
Site is working fine.
https://bit.ly/2F7vwHw
But proxy from cloudflare is disabled at the moment!
http://prntscr.com/qhgamy
So clearly its not an issue with dns. But as soon as i enable proxy protection from cloudflare? 
It start showing 521 error? 
http://prntscr.com/qhgayo
Its basically a URL shortner script but problem is the author of the script is also running this script on cloudflare as demo.

**Comment by fevangelou** [comment]
Perhaps it's not an issue by CloudFlare then but the app itself and only when it's behind CloudFlare. Consult with its developer if there are any special considerations when used as such.

It's also clearly not an Engintron issue.

**Comment by fevangelou** [comment]
Closing as not active.
