### ISSUE TITLE
Rarely getting 502 Bad Gateway Error

### ISSUE THREAD

**Issue by trdunya** [engintron/engintron#1140]
**Firstly, thank you for that stable great plugin!**

All websites are working perfectly compatible but sometimes i getting `502 Bad Gateway` error  unexpectedly. After reload the page then the error is gone.

I set the custom rule configuration as my shared IP -- _this only the customization that i set so everything works as default_:

`set $PROXY_DOMAIN_OR_IP "xx.xx.xx.xx";`

I couldn't catch the error from `error_log` because, it's getting too rare and unexpectedly. I'm not experienced much on web servers. Have you any idea to debug, catch and fix it?

Note: `csf` is disabled.

```
# Engintron:  v1.11.0 Build 20190710 (Nginx version: 1.16.1)
# cPanel:     v84.0.9
# CentOS:     v7.4
# Litespeed:  v5.3.8
```

**Comment by fevangelou** [comment]
The error means Apache did not respond in time or did not respond at all. Follow the optimization guides on engintron.com/docs so Apache, MySQL etc. can perform better.

**Comment by trdunya** [comment]
I've checked all documentation of engintron specially related **Apache** but still i couldn't find any solution.

Finally, I caught the error.

`2020/01/04 07:04:04 [error] 3470#3470: *510523 connect() failed (111: Connection refused) while connecting to upstream, client: xx:xx:xx:xx, server: localhost, request: "POST /page HTTP/1.1", upstream: "http://xx.xx.xx.xx:8080/page", host: "domain.tld", referrer: "http://domain.tld/page"`

Is the error might related to conflict of `PHP-FPM` or `Litespeed`?

**More Information:**
 - `Litespeed` active instead of Apache with Engintron.
 - Still that the weird part is, I getting the error, after about 10 to 30 page views unexpectedly.
 - The error is gone after refresh and everything is okay till to next coincidence.
 - When i disabled Engintron then error also has gone.
 - I use multiPHP actively with `PHP-FPM`.
 - CPU/RAM are low. No high load on the server.
 - I guess, Litespeed uses **keep alive** process. `connection refused` error might be related to litespeed keep alive process timed out.

**Comment by fevangelou** [comment]
Engintron is built for Nginx and Apache, not Nginx and Litespeed. It may work, but it's out of scope for what I'm doing with Engintron. I would recommend either using Engintron with Apache or just Litespeed (Apache off).

**Comment by trdunya** [comment]
The error was about **Litespeed Enterprise** conflict. I've disabled Litespeed Enterprise and error has been gone. **Engintron** works perfectly compatible with Apache.

Thanks for the addon!

**Comment by fevangelou** [comment]
Thanks for the feedback.
