### ISSUE TITLE
 str_split() expects parameter 2 to be int, string given in 

### ISSUE THREAD

**Issue by binipinki** [engintron/engintron#1141]
my engintron is not starting after update.
i was using 1.8.8 version and cpanel recommendd to upgrade it. i followed the instruction and took backup of 5 files recommended by engintron and updated. after 5 minutes it got updated and was not getting website to work. we restarted serer also. then we contacted cpanel and they advised that you contact engintron as we can see some error in there latest version

2020-01-05 02:57:28 -0800] info [whostmgrd] The system failed to connect to: “php-fpm/cptktjuab/sock”: No such file or directory at /usr/local/cpanel/Cpanel/Server/FastCGI.pm line 181.: falling back to php-cgi: check /usr/local/cpanel/logs/php-fpm/error.log
PHP Warning:  str_split() expects parameter 2 to be int, string given in cpanel/whostmgr/docroot/cgi/engintron.php on line 22
PHP Warning:  Invalid argument supplied for foreach() in cpanel/whostmgr/docroot/cgi/engintron.php on line 22

**Comment by fevangelou** [comment]
Do you have resellers set in WHM?

**Comment by binipinki** [comment]
no

**Comment by fevangelou** [comment]
Does the file "/var/cpanel/resellers" exist on your server and if so, does it have any contents?

**Comment by binipinki** [comment]
It is whm server. So definitely that folder I guess exist. Exact content I
can tell tomorrow. By the way this plugin is for cpanel so definitely I
guess these things are normal

**Comment by fevangelou** [comment]
It's not a folder, it's a file.

**Comment by binipinki** [comment]
Will check and update at the earliest. What I have to do if it exist.??

Should I delete it? To get niginx work

**Comment by fevangelou** [comment]
Just let me know if it exists and if so, what are its contents. I'll guide you afterwards.

P.S. You may be an edge case here so bare with me until we resolve this.

**Comment by binipinki** [comment]
Dear Sirs,

it exist and the content in it is

cat /var/cpanel/resellers

cphhjjhtty6yy8:all

**Comment by fevangelou** [comment]
So there was a reseller set at some point (albeit with a strange username - I hope you weren't hacked)...

Delete the contents of that file and save it.

**Comment by binipinki** [comment]
i mean i have to make that file empty ??

**Comment by fevangelou** [comment]
Yes.

**Comment by windsofchange** [comment]
> cphhjjhtty6yy8:all

that's probably Cpanel tech support's temp user for investigations

**Comment by fevangelou** [comment]
Good catch @windsofchange ;)

**Comment by binipinki** [comment]
there was only one space i guess. i deleted that space and again enabled engintron and the server gone down

**Comment by binipinki** [comment]
it works. thanks
