### ISSUE TITLE
Experienced Issue updating Engintron and 521 Error with Cloudflare

### ISSUE THREAD

**Issue by WebSavvyDude** [engintron/engintron#1142]
I just attempted to update Engintron to the latest release.

I clicked "Update (or re-install) Engintron [Nginx stable]"

Took nearly 6 minutes to update.   When it finally finished all my websites were showing a 521 cloudflare error.

What i did was install nginx again in SSH using "yum install nginx"

After that finished i was still getting the 521 cloudflare error.

I clicked "disable Engintron" and everything came back up.  When i clicked "enable Engintron" everything remained up.

Can anyone tell me what happened in this case?  The long downtime to update was scary and so was the fact it seems to have deleted my Nginx.   I have another more active server to update but before I do so, I would like a more safer way to update Engintron without bringing all my websites offline for that long and also without deleting Nginx. 

Please let me know exactly what happened in our scenario.

Thanks

**Comment by fevangelou** [comment]
Prefer to run `/engintron.sh install` via the terminal so you can get more info on the installation process.

I also noticed some stalling and it was due to Apache hanging up on restart (nearly the end of the installation) and not letting the script proceed.

**Comment by fevangelou** [comment]
Keep in mind that this stalling did not occur on all servers I updated, just a couple.

**Comment by WebSavvyDude** [comment]
How about the part of nginx completely disappearing? @fevangelou

**Comment by fevangelou** [comment]
No idea...

**Comment by babynew** [comment]
Same thing happened to me after updating .Nginx completely disappeared .What can i do? Urgent help needed..

**Comment by babynew** [comment]
Solved..
Re installed via command line..

**Comment by fevangelou** [comment]
Bingo.
