### ISSUE TITLE
Engintron for Directadmin

### ISSUE THREAD

**Issue by kang28ivan** [engintron/engintron#1144]
Hi

Are there any plans to expand to DirectAdmin? all this time I am an engintron user on cpanel
I hope that Engintron is in DirectAdmin too, because as long as they use nginx_apache built-in from DirectAdmin, they consume very large RAM.

cheers

**Comment by fevangelou** [comment]
No plans to port Engintron at the moment. If I did port it to other control panels, both Plesk and DirectAdmin would be high on my list.

**Comment by RagnarokOD** [comment]
I support this motion, with the increase of cpanel license prices, a lot of people would be very interested on directadmin support.

**Comment by fevangelou** [comment]
Noted.

**Comment by AlessioPellegrini** [comment]
I support this request too, I no longer use cPanel because of the absurd prices and DiractAdmin is really perfect for my needs.

**Comment by TORCommunity** [comment]
Also would really appreciate a port to DirectAdmin, cPanel pricing has gotten out of hand for baremetal servers

**Comment by nucombo** [comment]
I second that, DA option would be great
