### ISSUE TITLE
Nginx failing after latest update

### ISSUE THREAD

**Issue by PaddyBee70** [engintron/engintron#1145]
Engintron was working fine before, but after upgrading to the latest version 1.12.0, Nginx is not working. It doesn't even seem to be there.
> systemctl status nginx - simply says that nginx.service could not be found.

This is on the latest stable cPanel v84.0.20, Centos 7.7.
In the cPanel service status it also shows that Nginx is down, and the sites do not work.
I tried reinstalling, but the problem remains.
For now I had no choice but to disable it.

Is anyone else experiencing this problem? And is there a solution?

**Comment by fevangelou** [comment]
Attempt to uninstall it first and then re-install. All from the terminal.

**Comment by PaddyBee70** [comment]
That did the trick, thank you very much :)

**Comment by fevangelou** [comment]
Something got stuck in the way obviously :)
