### ISSUE TITLE
Video protection rules

### ISSUE THREAD

**Issue by bosper-cpu** [engintron/engintron#1146]
Using Kernel Video Sharing script and it requires to use Nnginx on cPanel Apache server in proxy mode. Everything fine until this.
I get warnings from the script when I try to add these rules for  these rules to my Nginx config to enable video skipping and protect video files from direct access.

    # protect videos from direct access
    location /contents/videos/ {
        root /home/account_name/public_html;
        limit_rate_after 2m;
        internal;
    }

Before Engintron, I used cpanel admin and in their vhost config required that  video protection rule to work properly had to be added above this rule:

location ~*.*\.(3gp|gif|jpg|jpeg|png|ico|wmv|avi|asf|asx|mpg|mpeg|mp4|pls|mp3|mid|wav|swf|flv|html|htm|txt|js|css|exe|zip|tar|rar|gz|tgz|bz2|uha|7z|doc|docx|xls|xlsx|pdf|iso)$ {
expires 1M;
try_files $uri @backend;
}

Tried different files on Engintron, I worked with 2 cPanel server management companies, but no success in solving the problem.
Did you encountered any other issues related to this?

**Comment by fevangelou** [comment]
Implement .htaccess rules for video blocking. No location rule will work with Engintron in proxy mode.

**Comment by bosper-cpu** [comment]
My server management proposed the same solution, but script developers told me that is not a solution and will not work with their script.
And they gave me as example Vesta panel where they use this rules in vhost config for each domain they add. Same was doing for cPanel cpanel admin plugin, but since it wasn't updated for long time cPanel removed from plugin list.

**Comment by fevangelou** [comment]
The script developers are ignorant then. What they told you basically is that their app won't work in Apache...
