### ISSUE TITLE
Server / Ip Not accessible after enabling Engintron

### ISSUE THREAD

**Issue by josephmiller2000** [engintron/engintron#1147]
For years im using engintron without any issue in my server.

For some reason, all the sudden all my websites hosted in a server went offline. During investigating i found that for some reason engintron is blocking the 80 and 443 ports.

Right now i have to keep engintron disabled in my production server.

WHM cpanel version : v84.0.21

Engintron Version : v1.12.0
                               Build 20200109

Help me out.. Thanks

**Comment by josephmiller2000** [comment]
Alright :) i fixed it by removing engintron complete using SSH terminal command mode. and then re installed it.

To remove engintron >>  bash /engintron.sh remove

and to install >> follow this directors in this page >> https://github.com/engintron/engintron

let me close this issue :) 

Issue related to #1145

**Comment by fevangelou** [comment]
Some cPanel installations seem to have suffered from similar issues but nothing common overall. In any case, upgrading from the terminal will always provide more info for the entire process (until an async update is made possible in the coming versions of Engintron).
