### ISSUE TITLE
Microcache within Laravel applications

### ISSUE THREAD

**Issue by brada1703** [engintron/engintron#1150]
Hi,

I noticed that within the [proxy_params_dynamic](https://github.com/engintron/engintron/blob/master/nginx/proxy_params_dynamic) settings, only certain sessions will not be micro-cached. 

I would like to add Laravel's session cookies to this list. This is due to the login system. In the current setting, the microcache will allow a second user to login as the first given that the second user logs in within one second of the first.

Here is how the code currently looks:

```
# CMS (& CMS extension) specific cookies (e.g. Joomla, K2 for Joomla, WordPress, WooCommerce, PrestaShop etc.)
if ($http_cookie ~* "(joomla_[a-zA-Z0-9_]+|userID|wordpress_(?!test_)[a-zA-Z0-9_]+|wp-postpass|comment_author_[a-zA-Z0-9_]+|woocommerce_cart_hash|woocommerce_items_in_cart|wp_woocommerce_session_[a-zA-Z0-9]+|sid_customer_|sid_admin_|PrestaShop-[a-zA-Z0-9]+)") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $EXPIRES_FOR_DYNAMIC 0;
}
```

Could you please add: `laravel_session|[a-zA-Z0-9_]_session` to this? 

Example:

```
# CMS (& CMS extension) specific cookies (e.g. Laravel, Joomla, K2 for Joomla, WordPress, WooCommerce, PrestaShop etc.)
if ($http_cookie ~* "(laravel_session|[a-zA-Z0-9_]_session|joomla_[a-zA-Z0-9_]+|userID|wordpress_(?!test_)[a-zA-Z0-9_]+|wp-postpass|comment_author_[a-zA-Z0-9_]+|woocommerce_cart_hash|woocommerce_items_in_cart|wp_woocommerce_session_[a-zA-Z0-9]+|sid_customer_|sid_admin_|PrestaShop-[a-zA-Z0-9]+)") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $EXPIRES_FOR_DYNAMIC 0;
}
```

Thanks!

**Comment by brada1703** [comment]
Let me know if you would like me to make a pull request.

**Comment by imorandinwnp** [comment]
This would be a good improvement. I also add these in custom_rules for Moodle, Laravel, Codeigniter, symphony, cake, etc:

.*PHPSESSID.*|.*MoodleSession.*|.*MOODLEID.*|.*laravel_session.*|.*ci_session.*|SSESS.*|symfony|CAKEPHP

**Comment by fevangelou** [comment]
@brada1703 I'll add them, don't worry. And thanks for letting me know.

@imorandinwnp Thanks for these as well. Just keep in mind that PHPSESSID is used for sessions in PHP and lots of CMSs use them even for guests. So including that to the exclusions list would effectively kill any type of caching for pages that should be cached. ;)

**Comment by fevangelou** [comment]
It seems that the laravel_session cookie is used for guest sessions as well. As such, excluding it will effectively disable micro-caching. So I won't be adding that to the exclusions list.

You can do that in your custom rules file:
```
if ($http_cookie ~* "(laravel_session|[a-zA-Z0-9_]_session|any_other_cookie)") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $EXPIRES_FOR_DYNAMIC 0;
}
```

**Comment by fevangelou** [comment]
Same goes for the cookies that @imorandinwnp mentioned. These all seem guest session cookies so excluding them will mean you're disabling micro-caching entirely. If that's the case, it's just easier to disable micro-caching entirely on your server or for specific domains only, with the exceptions defined in the custom rules file.

If there is any cookie from the aforementioned that is used to identify ONLY a logged in session, please let me know.
