### ISSUE TITLE
Apache error log showing server IP causing Modsecurity issues

### ISSUE THREAD

**Issue by kssuhesh** [engintron/engintron#1152]
I know this is discussed more and you guys referring it is beyond your free support. But this is a common issue faced by a system administrator. So it is good to refer a good documentation to rewrite the apache logs to show the real IP of the end-user or a way to integrate modsecurity with engintron. 

A reply should be expected.

**Comment by fevangelou** [comment]
It's best to tweak log reporting to include the proxy IP. So either use the related option in Nginx or follow this guide: https://engintron.com/docs/#/pages/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel

**Comment by fevangelou** [comment]
Closing as not active.
