### ISSUE TITLE
Engintron 1.12.0 update crashed the Nginx

### ISSUE THREAD

**Issue by azizparacha** [engintron/engintron#1153]
After the Engintron update, it stopped Nginx from restarting. I tried reinstalling and restarting Apache and Nginx and it still is down. I even did a restart and still down. Please advise?

**v1.12.0
Build 20200109
Kernel: Linux henry.mywebsitebox.com 3.10.0-962.3.2.lve1.5.26.7.el7.x86_64 #1 SMP Wed Oct 2 07:53:12 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux**

```
Nginx Status:

Redirecting to /bin/systemctl status nginx.service
Unit nginx.service could not be found.
```

CENTOS 7.7 [henry] v82.0.16

**Comment by imorandinwnp** [comment]
Hi,I had the same problem some tima ago, fixed it by installing nginx with yum:

`yum install nginx
`
Then reinstall engintron

**Comment by fevangelou** [comment]
Do the installation/upgrade from the terminal. Some users have reported issues when upgrading from within WHM...

**Comment by fevangelou** [comment]
Closing as not active.
