### ISSUE TITLE
Header "Cf-Railgun" missing after Engintron

### ISSUE THREAD

**Issue by imorandinwnp** [engintron/engintron#1155]
Hi,

Seems that the header "Cf-Railgun" gets stripped out when it passes through Nginx:
![image](https://user-images.githubusercontent.com/35805127/74946354-e7c8ec00-53d7-11ea-8c04-0a7da44a3637.png)

It doesn't seem to be happening with another Header, only this one.

**Comment by fevangelou** [comment]
Nginx does not strip any headers.

**Comment by imorandinwnp** [comment]
Do you have any ideas why this is happening? if I curl directly to Apache I get the headers just fine but if do through nginx I don't get the header:

```
ignacio@ignacio:~$ curl -v https://www.cotillonunpocoloco.com:8443 2>&1 | grep -i Railgun
< Cf-Railgun: direct (starting new WAN connection)
ignacio@ignacio:~$ curl -v https://www.cotillonunpocoloco.com 2>&1 | grep -i Railgun
ignacio@ignacio:~$ 

```

**Comment by fevangelou** [comment]
It's not -v it's -I:

```
$ curl -I "https://www.cotillonunpocoloco.com"
HTTP/2 200 
date: Wed, 04 Mar 2020 13:06:30 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d6b8e6974a7a5d15d9bc62c959827f9be1583327188; expires=Fri, 03-Apr-20 13:06:28 GMT; path=/; domain=.cotillonunpocoloco.com; HttpOnly; SameSite=Lax
vary: Accept-Encoding
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
set-cookie: PHPSESSID=a08c30f7fa6e2fde23a037ba23df00f4; path=/
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-nginx-cache-status: EXPIRED
x-server-powered-by: Engintron
cf-cache-status: BYPASS
set-cookie: PrestaShop-5bd6dee8dbf33ea253b8350dd0018d7b=def5020002dab87be37d904b68d4b1d9cba3f83ee578900c10fc6027bd8b6eb76a7b269b9520e3095409bb4c4769b972edeb93f8db288c179901b22fe73f41df2e39b99085c6eedba21946979c77a9bdd7d6a77f99136dba169a89f2711171d6b7bfcc7b8bbc10a1951d6b92ef41db2ebcf2b545b3e1ad9a8263b60b3bc08a4788f65c7a94d38d90dbc2fadbb6711a2f48fa3ee3ec6f58b18286010b3274; expires=Tue, 24-Mar-2020 13:06:29 GMT; Max-Age=1727999; path=/; domain=www.cotillonunpocoloco.com; secure; HttpOnly
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
alt-svc: h3-27=":443"; ma=86400, h3-25=":443"; ma=86400, h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
server: cloudflare
cf-ray: 56ebd090fb3bd17b-SKG
```

**Comment by imorandinwnp** [comment]
OK... -I, -v it's the same in this case.
The thing is that the header does not pass Nginx, do you have any ideas?

**Comment by fevangelou** [comment]
If you need just the headers, it's -I. In any case, Nginx does not strip any tags. Practically speaking, is it important to show the world you're using Railgun?

**Comment by imorandinwnp** [comment]
OK, I'll investigate further then. Yes, it is important to show the header because the Railgun checker inside Cloudflare uses this header and now it's failing, saying that Railgun is not working properly (and our clients believe that)

**Comment by imorandinwnp** [comment]
Couldn't find the reason for this to happen. I have another site with Railgun activated in the same server and the header is present.
Thanks anyway!
