### ISSUE TITLE
enabling TLS 1.3

### ISSUE THREAD

**Issue by ethaniel86** [engintron/engintron#1157]
engintron common_https.conf 
ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;

apache
-all +TLSv1.2 +TLSv1.3

Updated to cPanel 86, edited both nginx and apache and restarted both services to enable TLS 1.3 but tests from geekflare and ssllabs still showing tls 1.3 not enabled. Which part did i miss?

Thanks

**Comment by bonny3** [comment]
Hi,
I also ask the same question
how to enable TLS 1.3 in Engintron?

**Comment by joomkit** [comment]
Does this suggest another Cpanel setting required?
https://docs.cpanel.net/release-notes/86-release-notes/#added-tls-to-global-configuration-interface

**Comment by bonny3** [comment]
> 
> 
> Does this suggest another Cpanel setting required?
> https://docs.cpanel.net/release-notes/86-release-notes/#added-tls-to-global-configuration-interface
> TS 1.3 is dependant upon OPenSSL1.1.1 which requires recompiling modules (eg php7.2) is in order to use.
> "You must recompile any module that uses OpenSSL 1.0. For example, you must recompile any PHP 7.2 PECL modules to ensure that they continue to function"
> 
> Have you looked at this and still got no TLS1.3?

Hi
so do i need to reinstall engintron?

**Comment by windsofchange** [comment]
Setting it to 
`ssl_protocols TLSv1.3 TLSv1.2 ;`
and restarting nginx works for me

**Comment by bonny3** [comment]
> 
> 
> Setting it to
> `ssl_protocols TLSv1.3 TLSv1.2 ;`
> and restarting nginx works for me

no it doesn't work because nginx has the version
OpenSSL 1.0.2k-fips
that's what I can't update
how can I do?
do I have to install NGINX?

**Comment by fevangelou** [comment]
TLS 1.3 will be added in the next update. If you change your server to 1.3 now you should also manually change it in Engintron's files as well. Re-running EasyApache4 is not needed. If you use the installers I provide for APCu and Memcached then YES you need to re-run them so they can be re-compiled.

**Comment by bonny3** [comment]
> TLS 1.3 will be added in the next update. If you change your server to 1.3 now you should also manually change it in Engintron's files as well. Re-running EasyApache4 is not needed. If you use the installers I provide for APCu and Memcached then YES you need to re-run them so they can be re-compiled.

I can't update NGINX openssl
I installed the latest version of NGINX 1.17.9
but nothing has changed
GCC also has an old version ...
how can I update these two?

![2020-03-04_121624](https://user-images.githubusercontent.com/19350758/75874804-ca057900-5e12-11ea-9474-0a39ce014df2.png)

**Comment by fevangelou** [comment]
> I installed the latest version of NGINX 1.17.9
How?

And which CentOS version are you on?

**Comment by bonny3** [comment]
> 
> 
> > I installed the latest version of NGINX 1.17.9
> > How?
> 
> And which CentOS version are you on?

CENTOS 7.7 [server] v86.0.8 Load Averages: 1.24 1.23 1.20

**Comment by fevangelou** [comment]
I meant, where did you install Nginx from? You may have a different version if it's not the installer from Engintron (which uses the official repos).

Additionally, Nginx will use whatever your system has in terms of dependencies.

As for your version of Nginx and OpenSSL, they are both up to date from what I can see, in current cPanel builds.

I would also recommend that you wait for Engintron to ship with the option for TLS v1.3 (within the month).

**Comment by bonny3** [comment]
> I meant, where did you install Nginx from? You may have a different version if it's not the installer from Engintron (which uses the official repos).
> 
> Additionally, Nginx will use whatever your system has in terms of dependencies.
> 
> As for your version of Nginx and OpenSSL, they are both up to date from what I can see, in current cPanel builds.
> 
> I would also recommend that you wait for Engintron to ship with the option for TLS v1.3 (within the month).

NGINX has been installed by Repo

"nginx.repo"

[nginx]
name=nginx repo
baseurl=http://nginx.org/packages/mainline/centos/$releasever/$basearch/
gpgcheck=0
enabled=1

the version is the mainline
was installed by SSH

it's correct?

Openssl 1.1.1 must be installed for TLS 1.3 to work in NGINX
I can't find a way to update it ...
How can only NGINX Openssl be updated?
I have tried Apache 4 and TLS 1.3 works correctly

**Comment by fevangelou** [comment]
Works with Nginx too. But MUST you update to 1.3 for Nginx now? If you do, just edit the appropriate files in Nginx and restart services.

**Comment by bonny3** [comment]
> 
> 
> Works with Nginx too. But MUST you update to 1.3 for Nginx now? If you do, just edit the appropriate files in Nginx and restart services.

already added TLS 1.3 in NGINX but it doesn't work
the problem is that the Openssl version of my NGINX is old
1.0.2k
this version does not run TLS 1.3
For this reason I am asking for help to update NGINX Openssl 1.1.1

![2020-03-04_143532](https://user-images.githubusercontent.com/19350758/75884610-73556a80-5e25-11ea-826e-99c1aab4db4c.png)

**Comment by fevangelou** [comment]
In cPanel, Apache comes from cPanel's repo and it's obviously precompiled with a different OpenSSL version to support TLS 1.3. Since OpenSSL is a crucial part of the OS, it's not recommended to attempt to upgrade it.

What you can do is either wait for CentOS to upgrade the OpenSSL package, use a third party repo (e.g. https://codeit.guru/en_US/) or compile Nginx against a newer OpenSSL package.

**Comment by windsofchange** [comment]
> In cPanel, Apache comes from cPanel's repo and it's obviously precompiled with a different OpenSSL version to support TLS 1.3. Since OpenSSL is a crucial part of the OS, it's not recommended to attempt to upgrade it.
> 
This would mean that EasyApache compiles Apache with custom OpenSSL as apache under cPanel 86 support TLSv1.3

**Comment by fevangelou** [comment]
EasyApache4 does not compile anything, anymore. It just fetches prebuilt binaries. That's why it's faster than EA3.

**Comment by windsofchange** [comment]
Ouch! Does that mean we probably need to install OpenSSL 1.1.1 for Nginx? Something like https://www.osradar.com/how-to-install-the-latest-version-of-openssl-on-centos-7/

**Comment by bonny3** [comment]
> > Since OpenSSL is a crucial part of the OS, it's not recommended to attempt to upgrade it.

I updated Centos Openssl whit 1.1.1c Version,
but that doesn't solve the problem,
because the problem is NGINX Opnessl...
I can't find any method to update this Openssl in NGINX

**Comment by fevangelou** [comment]
The Nginx binaries are built to be compatible with each supported OS. As such, if CentOS 7 is using OpenSSL 1.0.2, they will be prebuilt for that version. That is why I mentioned different repos.
