### ISSUE TITLE
X-Nginx-Cache-Status headers missing for static content

### ISSUE THREAD

**Issue by WhiteDogBe** [engintron/engintron#1159]
Hello,

Not a real issue, more a question. I have this experience on multiple servers.
When accessing static content such as images, there are no headers for X-Nginx-Cache-Status, X-Server-Powered-By, ..

Example of a dynamic and static request:
```
root@server [~]# curl -I https://www.redacted.gone/
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 04 Mar 2020 10:17:27 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Pragma: no-cache
Cache-Control: max-age=0, must-revalidate, no-cache, no-store
Expires: Mon, 04 Mar 2019 09:58:28 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Set-Cookie: PHPSESSID=redacted; expires=Wed, 04-Mar-2020 20:17:27 GMT; Max-Age=36000; path=/; domain=www.redacted.gone; secure; HttpOnly
X-UA-Compatible: IE=edge
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: EXPIRED
X-Server-Powered-By: Engintron

root@server [~]# curl -I http://www.redacted.gone/pub/media/wysiwyg/redacted.gone/redacted.gone.jpg
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 04 Mar 2020 10:17:30 GMT
Content-Type: image/jpeg
Content-Length: 215396
Connection: keep-alive
Last-Modified: Thu, 13 Feb 2020 10:19:54 GMT
X-Frame-Options: SAMEORIGIN
Expires: Sun, 03 May 2020 10:17:30 GMT
Cache-Control: max-age=5184000
Pragma: public
Accept-Ranges: bytes
```

If I set the header in proxy_params_static, for example:
```
# Reset headers
add_header              Pragma "public";
add_header              X-Nginx-Cache-Status $upstream_cache_status;  
```
Then the header is added and the cache indicates it is working.

Is this by design and if so, where exactly is it configured to not include the "common" headers?

**Comment by fevangelou** [comment]
The cache always works, that's why it's not there ;)

The indicator matters for dynamic content primarily, where you need to know when the cache is on and off, especially when troubleshooting login issues.

**Comment by WhiteDogBe** [comment]
It's just because if you look at some older topics here, for [example](https://github.com/engintron/engintron/issues/382), the headers were also present for static content at some point.

**Comment by fevangelou** [comment]
It doesn't matter. Even if you disable static (=server-side) caching, Nginx will update the HTTP headers for longer client-side caching. So the caching benefit is still there.
