### ISSUE TITLE
A fix for some people having slow TTFB or slow first page load.

### ISSUE THREAD

**Issue by uj** [engintron/engintron#1160]
First of all, thank you for this project!  It is very kind of you to do this.

I recently installed, and I was having an issue where the first time I went to a page, it took several seconds before it started to load.  Then, if I reload, it was very fast.  If I wait a few minutes, the first page load is slow again.  I searched the issues here, and found a few other people with similar issues, but never anything that worked for me.

Finally, somewhere I ran across a suggestion to change the resolver to only use IPv4 in the .conf file., instead of IPv4 + IPv6.  Once I changed that, it completely fixed my problem.

Perhaps this is already in your instructions and I have overlooked it, or if not, perhaps you could add this information for people who are not yet using IPv6 on their servers.

**Comment by fevangelou** [comment]
Thanks for your input. My guess however is that this is dependant on the hosting provider. Perhaps in your case there is no full IPv6 routing support.

**Comment by valiant1x** [comment]
This was an obscure issue on one of my servers as well. I am not sure why IPv4 + IPv6 was selected as the default resolver option. To clear up what OP mentioned above, specifically it is nginx.conf that should be modified. Look for the section titled `## DNS Resolver ##` and select one of the options labeled as IPv4 only.

**Comment by fevangelou** [comment]
It's important for folks with IPv6 capable servers which grow day by day.

If it took 5+ seconds for you it means something's not properly configured in your networking setup.
