### ISSUE TITLE
sub domain account shows main hostname website data in nginx

### ISSUE THREAD

**Issue by mhdifirouzi** [engintron/engintron#1161]
Hi dear,
I have an cPanel account for my subdomain ex: "sub.example.com" with dedicated ip.
When my server is running on engintron, sub.example.com shows main hostname website.
When I switch to apache server, that problem will be fixed.
How can I solve this terrible problem?

**Comment by fevangelou** [comment]
This will only occur if the subdomain does not yet resolve to that IP.

More info here: https://engintron.com/docs/#/pages/Engintron-and-under-development-domains-that-dont-yet-resolve-point-to-your-cPanel-server

**Comment by mhdifirouzi** [comment]
Thanks, problem solved.
