### ISSUE TITLE
Proxy requests to PHP FPM via the FCGI protocol

### ISSUE THREAD

**Issue by getedge** [engintron/engintron#1163]
I want to proxy php requests to the fcgi cache but when i follow the instructions here and put the following code in the default.conf but still the x-cache-status is always expired/miss. Also the php files on port 80 always shows 404 not found. Website works fine on port ssl/443.

https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/#connecting-nginx-to-php-fpm

> location ~ [^/]\.php(/|$) {
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    if (!-f $document_root$fastcgi_script_name) {
        return 404;
    }

    # Mitigate https://httpoxy.org/ vulnerabilities
    fastcgi_param HTTP_PROXY "";

    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;

    # include the fastcgi_param setting
    include fastcgi_params;

    # SCRIPT_FILENAME parameter is used for PHP FPM determining
    #  the script name. If it is not set in fastcgi_params file,
    # i.e. /etc/nginx/fastcgi_params or in the parent contexts,
    # please comment off following line:
    # fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
}

I have php 7.3 on easy apache 4

**Comment by fevangelou** [comment]
Engintron is for proxying requests from Nginx to Apache. It's not for direct serving with Nginx.
