### ISSUE TITLE
502 Bad Gateway Error on One Specific Website

### ISSUE THREAD

**Issue by mustafaerdinc** [engintron/engintron#1166]
Hello,

I have around 100 website on server however this one specific website got 502 Bad Gateway with following error: 

`2020/03/29 15:55:16 [crit] 29298#29298: connect() failed (101: Network is unreachable) while resolving, resolver: [2001:4860:4860::8844]:53
2020/03/29 15:55:16 [error] 29298#29298: *644 www.site.com could not be resolved (2: Server failure), client: ::ffff:88.230.168.184, server: site.com, request: "GET /tr/uzaktanegitim1 HTTP/2.0", host: "www.site.com"`

What may cause this?

**Comment by fevangelou** [comment]
Are the domain's DNS records properly pointing to your server?

**Comment by fevangelou** [comment]
Also checkout the troubleshooting section in the docs: https://engintron.com/docs/

**Comment by mustafaerdinc** [comment]
yes. dns records are correct, however when I enable Engintron this one website get 502 error. I have been using Engintron since 2016 this is the first time I got this kind of problem. This site was working fine.

**Comment by fevangelou** [comment]
Edit /etc/nginx.conf and set only IPv4 resolvers, in case there's some IPv6 configuration issue with your server or provider.
