### ISSUE TITLE
504 Gateway Time-out Nginx

### ISSUE THREAD

**Issue by dkalantzis** [engintron/engintron#1167]
Hi, i am developing a C# application, for woocommerce product and operations management. I am using Woocommerce API v3. Everything works perfectly, except when i am sending batch updates of 100 products to the shop. (Cpanel/Engitron). At the first 100 products JSON i get a gateway time-out, first 100 do get created, at the next batch i get timeout. When i do the same procedure to vanilla cpanel, works fine. I guess i need to change the folllowing ? 

The thing is that the shop already has 80000 products, any optimizations more i can do ? 8 core 32gb vps btw
 
Timeouts
proxy_connect_timeout       300s; - 1200s for example
proxy_read_timeout          300s;
proxy_send_timeout         300s;

**Comment by fevangelou** [comment]
You can surely bump these timeouts, but it would probably be better if you did some performance optimization (tuning) to MySQL or MariaDB.

Check out the optimization guides on the Engintron Docs if you want to do it on your own: https://engintron.com/docs/#/pages/Beyond-Engintron-Optimizing-MySQL

**Comment by dkalantzis** [comment]
I already did, i may need your help. The entire process takes hours, in order to see if changes worked. I saw you provide such services. I will send a request, from your site.

**Comment by fevangelou** [comment]
Closing for now.
