### ISSUE TITLE
Remove Unnecessary SSL Certificate

### ISSUE THREAD

**Issue by kent-chin** [engintron/engintron#1169]
Use Case: I would like to integrate an FPX payment gateway. The service provider claims that they are not able to support SNI enabled website. Therefore I am trying to remove unnecessary SSL certificates.

Checking: Based on this tool > https://www.ssllabs.com/ssltest/analyze.html?d=www.gloo.com.my, I see that there are two certificates on my website which are gloo.com.my and aws-whm.gloo.com.my. I would like to remove aws-whm.gloo.com.my.

What I have done: I removed those unnecessary certificates from cPanel, and re-run the tool and found that the result was still the same. After some researches, I found that it was the Engintron problem. When I disable Engintron and run the tool, the result was good where I only see one certificate which is gloo.com.my. When I enable back Engintron, again the second certificates pop up and my website has again become an SNI enabled website.

I tried to disable Engintron, manually run AutoSSL once and then enable back Engintron, but the result is still the same. I also tried reinstall and update Engintron to the latest stable version (v1.13.0), but the result is still the same.

I need Engintron because it helps with my website performance but at the same time, I need to load only one SSL certificate. I am not sure whether I am in the right direction, am really appreciate it if you could help with this.

Thank you.

**Comment by fevangelou** [comment]
Engintron will always map domains to certificates as they are present in Apache. When you delete a certificate in Apache, it may take a few minutes (tops) for Nginx to also delete the relevant entry in its vhosts. The report from SSL Labs may have been cached. So it's best to use a terminal command to verify a certificate, e.g.:
```
nmap -p 443 --script ssl-cert domain.tld
```

You need nmap installed for the above command.

Some other examples are here: https://serverfault.com/questions/661978/displaying-a-remote-ssl-certificate-details-using-cli-tools

**Comment by kent-chin** [comment]
Hi,


I am pretty sure it is not cached. Because when I disable Engintron, the additional certificate was not loaded; but when I enable back Engintron, the certificate comes up again.


I do not want that additional certificate, do you able to assist by providing guidance on how to remove this additional certificate from Engintron? Like is there any configuration file related?


Thank you.


Best regards,

Kent
Programmer

[cid:image003.jpg@01D23383.A25AAEB0]

SNS Network (M) Sdn. Bhd. (512056-K)
61, Jalan Sultan Nazrin Shah, 30250 Ipoh, Perak.
Tel: +605-2424 616  ext. 1107
Email: kent.chin@sns.com.my | Website: www.sns.com.my<http://www.sns.com.my/>

Disclaimer: This message is intended only for the use of the person(s) to whom it is addressed and may contain information that is privileged and confidential. If you are not the intended recipient you are hereby notified that any use, review, disclosure or copying of this message and the information it contains is prohibited. If you receive the message in error, please notify the sender by reply email and delete all its contents. No liability or responsibility is accepted if the information or data in this email is corrupted. All opinions, conclusions and other information in this message that do not relate to the official business of the Company and its associates shall be understood as neither given nor endorsed by the organization.

________________________________

**Comment by fevangelou** [comment]
This could mean that Nginx does not sync with Apache's certificates. If so, perhaps your cron jobs are broken. See engintron.com/docs for additional help.
