### ISSUE TITLE
Cannot retrieve repository metadata

### ISSUE THREAD

**Issue by AtivosDave** [engintron/engintron#1173]
We are seeing this issue in Yum:

http://nginx.org/packages/centos/6/x86_64/repodata/repomd.xml/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2001:1af8:4060:a004:21::e3: Network is unreachable"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: nginx. Please verify its path and try again

Have checked the location of the repo and added manually but still fails.

Any advice very appreciated.

Thank you.

**Comment by fevangelou** [comment]
Probably because of this: https://www.githubstatus.com/incidents/80d0cs6kpsps

**Comment by AtivosDave** [comment]
This problem persists 6 days later any resolution?

**Comment by fevangelou** [comment]
Disable IPv6 temporarily and retry.

**Comment by AtivosDave** [comment]
Will try, thank you.  I see it is a Nginx issue so apologise for adding it as an issue here.

**Comment by AtivosDave** [comment]
Have informed the Nginx team so will close this issue as its not truly an Engintron issue.
