### ISSUE TITLE
HTTP ERROR 500 

### ISSUE THREAD

**Issue by ashkankhalili** [engintron/engintron#1176]
Hi, 
When I try to open engintron setting on WHM=>plugins=>Engintron for cPanel/WHM,
It just show an error as HHTP ERROR 500.
 I have tried to reinstall and update it from the terminal and everything went ok but still getting the same error.
Would you please tell e how to solve this problem ? 
thanks in advance

**Comment by fevangelou** [comment]
Are you logging into WHM as a reseller perhaps?

**Comment by ashkankhalili** [comment]
> Are you logging into WHM as a reseller perhaps?

Nope, I have logged in as root ... 
Even i thought the same so i tried the root and still have the same error!

**Comment by fevangelou** [comment]
Perhaps the installation was not successful for some reason. You should try again.

**Comment by ashkankhalili** [comment]
> Perhaps the installation was not successful for some reason. You should try again.

As i have mentioned, i have reinstall it again ... but no changes ...
It was working earlier with no issues and didn't have this problem.
last time it was working fine which was around a week ago that i have checked, but now it shows me this error, besides i didn't make any changes to the server configuration, except i have just installed a php extension on easyapache which was php73-php-sourceguardian.
is there any chance this happened cause by that ?!

**Comment by ashkankhalili** [comment]
well... its simply solved !!!! i dont know how and why it happened and i dont know how and why it is solved !!!! kinda weird...!!!!!
The only thing i did this time was changing some stuff in tweak setting and saved it ... 
what is going on i really love to find out !

**Comment by fevangelou** [comment]
I can't possibly know because Tweak Settings are a part of cPanel and not Engintron.

**Comment by ashkankhalili** [comment]
hi again, 
Yes that's what i thought ... so i guess it was an unknown error which been solved automatically ! 
thanks anyway :)

**Comment by fevangelou** [comment]
One of the mysteries in cPanel I guess...
