### ISSUE TITLE
https redirect not working with Node.js application

### ISSUE THREAD

**Issue by iantrudell** [engintron/engintron#1177]
I have a Node.js app running using Express on port 2000 and I'd like to redirect all traffic from http to https, and www to non-www.

I've added this to my custom_rules but http and www aren't redirecting:

```
if ($host ~ "example.net") {
    set $PROXY_SCHEME "https";
    set $PROXY_TO_PORT 2000;
}
```

TL;DR I want all of these:
http://www.example.net
http://example.net
http://example.net:2000
http://www.example.net:2000

to redirect to this:
https://example.net

Any ideas what I'm doing wrong?

**Comment by fevangelou** [comment]
Do this first:
```
# Redirect first
if ($SITE_URI ~ "www.example.net|http://example.net") {
    return 301 https://example.net;
}

# Then proxy
if ($SITE_URI ~ "https://example.net") {
    set $PROXY_SCHEME "https";
    set $PROXY_TO_PORT 2000;
}
```

Nginx does not run on port 2000, so it can't redirect traffic from there. You can just close that port in the firewall (e.g. CSF). Nginx will be able to access it internally of course.

**Comment by fevangelou** [comment]
Make sure you run `nginx -t` after you add the above to ensure Nginx's config compiles correctly. If it doesn't, you probably need to escape "://" in the example above.

**Comment by iantrudell** [comment]
Tried adding those lines to custom_rules and recompiled ok, but now I'm getting 403 Forbidden errors on all versions of example.net

**Comment by fevangelou** [comment]
If you Node app responds ONLY to http and not https, change `set $PROXY_SCHEME "https";` to `set $PROXY_SCHEME "http";`.

**Comment by iantrudell** [comment]
When I use just this:

```
if ($host ~ "example.net") {
    set $PROXY_SCHEME "https";
    set $PROXY_TO_PORT 2000;
}
```

then the node app works at https://example.net with port 2000 only there's no redirecting www or http

Trying to mix those two or using what you posted results in the 403 Forbidden error.

Here's the beginning of the node app:

```
var fs = require('fs');
var https = require('https');

// Express
var express = require('express');

// Create app
var app = express();

// Files for client
app.use(express.static('public'));

// Force SSL
app.use(function (req, res, next) {
    if ((req.get('X-Forwarded-Proto') !== 'https')) {
        res.redirect('https://' + req.get('Host') + req.url);
    } else {
        console.log('failed');
        next();
    }
});

// Set up server
// let server = app.listen(process.env.PORT || 2000, listen);

var server = https.createServer({
    key: fs.readFileSync('/home/example/ssl/keys/example.key'),
    cert: fs.readFileSync('/home/example/ssl/certs/example.crt'),
    ca: fs.readFileSync('/etc/pki/tls/certs/ca-bundle.crt'),
    requestCert: false,
    rejectUnauthorized: false
}, app);

var serverPort = 2000;

server.listen(serverPort, function () {
    console.log('server up and running at %s port', serverPort);
});
```

**Comment by fevangelou** [comment]
> then the node app works at https://example.net with port 2000 only there's no redirecting www or http
Do you mean the actual URL on the browser is https://example.net:2000? You're not being clear here.

In any case, handle the primary domain redirect with Nginx and NOT Node. Exactly as I mentioned in my first response.

**Comment by iantrudell** [comment]
> > then the node app works at https://example.net with port 2000 only there's no redirecting www or http
> 
> Do you mean the actual URL on the browser is https://example.net:2000? You're not being clear here.
> 
> In any case, handle the primary domain redirect with Nginx and NOT Node. Exactly as I mentioned in my first response.

Sorry, let me try explaining again.

**With this code in custom_rules:**

```
# Redirect first
if ($SITE_URI ~ "www.example.net|http://example.net") {
    return 301 https://example.net;
}
# Then proxy
if ($SITE_URI ~ "https://example.net") {
    set $PROXY_SCHEME "https";
    set $PROXY_TO_PORT 2000;
}
```

I get 403 Forbidden errors on everything.


**With nothing added to custom_rules:**

I can access the app from these URLs:
http://example.net:2000
http://www.example.net:2000

But https results in an SSL protocol error in the browser.


**With just this code in custom_rules:**

```
if ($host ~ "example.net") {
    set $PROXY_SCHEME "https";
    set $PROXY_TO_PORT 2000;
}
```

The app works from these URLs:

https://example.net
http://example.net

But the non-https is still accessible (doesn't redirect to https)

**Comment by fevangelou** [comment]
This means the regex I sent you doesn't work. Did `nginx -t` return OK? If so, then try changing the regex from:
```
# Redirect first
if ($SITE_URI ~ "www.example.net|http://example.net") {
    return 301 https://example.net;
}
# Then proxy
if ($SITE_URI ~ "https://example.net") {
    set $PROXY_SCHEME "https";
    set $PROXY_TO_PORT 2000;
}
```

to:
```
# Redirect first
if ($SITE_URI ~* "www\.example\.net|http:\/\/example\.net") {
    return 301 https://example.net;
}
# Then proxy
if ($SITE_URI ~* "https:\/\/example\.net") {
    set $PROXY_SCHEME "https";
    set $PROXY_TO_PORT 2000;
}
```

If that doesn't work either, then parse `req.get('Host')` in your main Node app file and detect if www. is part of it and then redirect accordingly (you already parse the protocol).
