### ISSUE TITLE
CentOS 8

### ISSUE THREAD

**Issue by racetech22** [engintron/engintron#1181]
Hi, 

Engintron work on CentOS 8?

Thanks,

Fernando, Brasil

**Comment by fevangelou** [comment]
I don't see why it shouldn't work.

But I know cPanel doesn't... >> https://features.cpanel.net/topic/support-for-rhel-8

**Comment by jkalergis82** [comment]
It seems that it does not work out of the box as did on centos < 8 . It gives the default nginx page even after disabling EPEL
