### ISSUE TITLE
W3TC and NGINX caching

### ISSUE THREAD

**Issue by informdev** [engintron/engintron#1183]
Hey man,

Hope you're doing well. I feel like I may have asked this to you before but I'm going to ask again.

Is WordPress caching (in this case W3TC) different than NGINX? I'm sure I'm not wording that right, but what I mean is when I clear W3TC cache it appears to not clear server-side.

Any idea why? Is that why you recommend NGINX valid be kept at 1s ?

**Comment by fevangelou** [comment]
It depends on how many caching layers you have. There's server-side cache from Nginx (if you don't do micro-caching but longer caching), Memcached, APCu, file caches from WordPress etc. There's also client-side cache enforced by HTTP headers to the browser or a CDN.

The micro-cache is ideal to assist a server when sudden traffic occurs, but without causing any issues for sites with user generated content and logins that do not make proper use of HTTP headers (to disable caching) or are not part of the ready-made exclusions list in Engintron.
