### ISSUE TITLE
Site No longer Opening after I installed Engintron

### ISSUE THREAD

**Issue by xata11** [engintron/engintron#1184]
I faced this issue after I just installed this plugin, my site stopped working completely.

but for the sake of other who want to install this plugin, if you face the same issue, Kindly go to your **Edit your custom_rules for Nginx** uncomment the line
```
if ($host ~ "example.com") {
     set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX";
 }
```
replace the XXX.XXX.XXX.XXX with your original server IP, then change the example.com to your sitename.com

save it and your sites will start working perfectly

**Comment by TezHostAdmin** [comment]
Was your site on Cloudflare? Sites on cloudflare seems to be throwing 502 Bad gateway error on a shared IP. We have installed Engintron on one of our server and it created many issues with sites on cloudflare, Woocommerce sites, sites on that server casually going down for some time. As users have third party ping services installed on their sites they report down times. Engintron is not that mature yet to be installed on large servers having hundreds of clients.

**Comment by TezHostAdmin** [comment]
Was your site on Cloudflare? Sites on cloudflare seems to be throwing 502 Bad gateway error on a shared IP(fixed now by adding custom rules). We have installed Engintron on one of our server and it created many issues with sites on cloudflare, Auto-SSL(Forced-https domains) & Woocommerce sites etc. sites on that server casually going down for some time. As users have third party ping services installed on their sites they report down times. Engintron is not that mature yet to be installed on large servers having hundreds of clients.

**Comment by fevangelou** [comment]
@xata11 This is referenced in Engintron docs either way, plus inside that file as well. Hard to miss...

@TezHostAdmin When you install a piece of software, it's a good thing to have a look at the docs. Clearly you didn't. Oh, I'd say it's pretty mature already...
https://trends.builtwith.com/framework/Engintron
https://publicwww.com/websites/engintron/
