### ISSUE TITLE
Possible to cache full page in Redis and bypass caching

### ISSUE THREAD

**Issue by moazam1** [engintron/engintron#1186]
Hi,

We would like to cache full page in memory ideally in Redis, is it possible? Also, we would like to disable micro-caching in our custom coded backend. Is it possible to send header so engintron doesn't cache at all?

P.s. we have sent couple paid support help but we didn't hear back from you.

**Comment by fevangelou** [comment]
a) Regarding Nginx & Redis there's a module for that: https://www.nginx.com/resources/wiki/modules/redis/ (the module can be dynamically loaded)
b) See the "custom rules" file in Engintron. You can control micro-caching based on URL patterns. So you can just exclude the path to the admin backend.
c) I've seen your request but I can't perform work over Zoom. Contact a sysadmin in your city/region for that.

**Comment by moazam1** [comment]
Thank you
