### ISSUE TITLE
Different ports reverse proxy forward with one $host, including WebSocket

### ISSUE THREAD

**Issue by mttbork** [engintron/engintron#1187]
I have a WHM/cPanel server with your plugin installed. Internal IP is 192.168.1.100. Server is behind the NAT. NAT router forward all needed ports to this local IP.

I have other server (centos) with Bitrix portal soft installed. Local IP address is 192.168.1.111.

In custom rules I have this working configuration for reverse proxy:

if ($host ~ "portal.company.net") {
     set $PROXY_DOMAIN_OR_IP "192.168.1.111";
     set $PROXY_TO_PORT 443;
  }

It works well.

But i need to reverse proxy other ports for this domain name too:
http - 8895
https - 9993, 8894

Also, i need reverse proxy for WebSocket.

I give up. I tried a tons of code, inserting new codes {server listen .
I didn’t get any result.

**Comment by fevangelou** [comment]
Can you provide me an actual mapping of what you wish to forward?

E.g. "https://portal.company.net" to internal IP 1.2.3.4.

**Comment by mttbork** [comment]
> Can you provide me an actual mapping of what you wish to forward?
> 
> E.g. "https://portal.company.net" to internal IP 1.2.3.4.

this mapping is actual.

E.g.     

internet --> |nat| --> all domains and ports forwarded to cPanel/WHM with engintron with local 192.168.1.140 --> if domain name "portal.company.net", forward websockets and http - 8895
https - 9993, 8894 ports to  local address --> 192.168.1.111

**Comment by fevangelou** [comment]
Having the ports would also help. And your use of dashes doesn't really help so I'll take a stab at it either way...

You can only proxy external ports 80 and 443 (HTTP and HTTPS respectively) cause these are the ones utilized by Nginx.

So do this:
```
# Combine the protocol and host name into a single variable
set $URI "$scheme://$host";

if ($URI ~ "http://portal.company.net") {
    set $PROXY_DOMAIN_OR_IP "192.168.1.111";
    set $PROXY_TO_PORT 8895;
}
if ($URI ~ "https://portal.company.net") {
    set $PROXY_DOMAIN_OR_IP "192.168.1.111";
    set $PROXY_TO_PORT 9993;
}
```
