### ISSUE TITLE
How can the site that comes up when going to the IP address be changed or disabled?

### ISSUE THREAD

**Issue by sblaydes** [engintron/engintron#1188]
Have a new install on WHM v86.0.21 and Engintron 1.12.0 (will be upgrading this week), but when you go to the IP address in a web browser, the first site that was added to the server comes up. 

How can I disable that or change it so that the WHM 404 comes up?

If there is a better place to ask a question like this, please point me in the right direction.

**Comment by fevangelou** [comment]
What's the IP? Is that IP dedicated only to that domain or is it a shared one?

**Comment by sblaydes** [comment]
Shared IP.

Worth mentioning that I had to set $PROXY_DOMAIN_OR_IP "xxx.xxx.xxx.xxx" in the custom_rules on this server to get it work.

**Comment by fevangelou** [comment]
Pre-setting the shared IP saves you from a lot of potential headaches (e.g. sites on CloudFlare).

**Comment by sblaydes** [comment]
The problem still isn't resolved, just mentioning that I had to set $PROXY_DOMAIN_OR_IP in case that is related to the problem I asked about. When you go to the IP address in a web browser, the first site that was added to the server comes up.

How can I disable that or change it so that the WHM 404 comes up? Even being able to control what site comes up or redirecting the web browser would be solution for this issue.

Anyone have any ideas?

**Comment by fevangelou** [comment]
If you haven't messed with Engintron's files, this can't happen by default. If it does happen, it means your Apache setup redirects IP calls to the first domain for some reason. But even so, this is not the default behaviour in Apache as setup by cPanel.

Which leads to either some sort of configuration hacking or some other networking voodoo (e.g. another proxy listening to incoming requests and performing possible redirects).

Even so, you can create a custom rule in Engintron to match the IP as a $host variable and then do a 301 redirect wherever you like.

**Comment by sblaydes** [comment]
Could you give me an example of the rule for the 301 redirect? I tried, but wasn't successful. 

Thank you for the help on this.

**Comment by fevangelou** [comment]
```
if ($host = "1.2.3.4") {
    return 301 https://example.com/whatever;
}
```
Place at the bottom of the file custom rules (via the Engintron WHM app).

**Comment by sblaydes** [comment]
Worked perfect, thank you.

**Comment by fevangelou** [comment]
Great.
