### ISSUE TITLE
On installing Engintron Load going from 1-2 to 15-17.   

### ISSUE THREAD

**Issue by tibbie123** [engintron/engintron#1189]
Disabled micro cache, load back to 2.

As my sites not heavy usage do not really need micro cache but please advise what the problem is and is Engintron working properly as a reverse proxy without the micro cache. I have reviewed the documentation and I have VPS 12 Processors, 12GB RAM, OS: CentOS Linux release 7.8.2003 (Core)

Kernel: Linux server.xxxxx.com 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux 
PHP-FPM

thanks

**Comment by tibbie123** [comment]
Solved by increasing set $EXPIRES_FOR_DYNAMIC in Edit proxy_params_dynamic. The higher I put it the lower the server load went. As my visitors increase, I can push back down.

**Comment by fevangelou** [comment]
"$EXPIRES_FOR_DYNAMIC" actually refers to the cache-control header. I would strongly advise that you configure your app or site with such a header, if that's possible.
