### ISSUE TITLE
Referer Module

### ISSUE THREAD

**Issue by millermultimedia** [engintron/engintron#119]
Hello,
I am trying to block referrer attacks on my server through NGINX. According to the NGINX website: https://www.nginx.com/resources/wiki/start/topics/examples/refererspam/
The configuration change from the above link should resolve the issue. When I add this rule to the "location / { ..." section of the defualt.conf file I am getting the 403 error for all sites on my server.
Is the valid_referers module complied into NGINX? I do not see it listed in the "Show compiled modules" area. If it is not installed, is there a way to include it?
Thanks!

**Comment by fevangelou** [comment]
Only if you compile from source. But then you won't be able to update easily. That was the point of using the official Nginx repos in the first place.

Know that the ngx_http_referer_module doesn't really protect you from spammers. Read the docs here: http://nginx.org/en/docs/http/ngx_http_referer_module.html

**Comment by highacid** [comment]
@millermultimedia Try https://github.com/Stevie-Ray/apache-nginx-referral-spam-blacklist

**Comment by millermultimedia** [comment]
Thanks for the links. I will read through them this morning. The issue I am having is that someone is hitting one of the sites I host from up to a thousand different IPs all in less than a minute. All of the connections have the same referer. I have tried blocking at the Apache level but by that time it is too late as the connections have already started a PHP instance for each connection. I am also trying to use CloudFlare although it does not like to cache an index.php file. The ideal situation would be to use NGINX to stop the connection from reaching Apache. From what I have read the referer module can do this.

**Comment by millermultimedia** [comment]
The links you provided simply reenforce my conclusion that I need the referer module as they both describe how to use it to solve the issue I am having (both use $bad_referer in their solution). You mention I can recompile NGINX on my own to include the module. Are their directions available on how to do this properly? I understand this would prevent me from upgrading, although the primary reason I loaded your add-on was to try and resolve this issue.

Thanks for the help.

**Comment by fevangelou** [comment]
CloudFlare is probably your best bet as they will block the offender.

If you wish to protect a single site, then I could help you with specific caching rules for that site, in order to totally bypass Apache, even when you get hit by hundreds of IPs.

**Comment by millermultimedia** [comment]
Thanks for the offer. So far so good with CloudFlare and some aggressive caching rules on their side. I would like to leave this thread open for another 24 hours. If all is good at that time I will close it.

**Comment by fevangelou** [comment]
Sure :)

**Comment by millermultimedia** [comment]
Agressive caching on CloudFlare did help alleviate the issue.

**Comment by fevangelou** [comment]
Good to know :)

**Comment by millermultimedia** [comment]
Hello, I had opened this request a couple months ago in regards to using one of the official NGINX modules which is not loaded in the Engintron install. Since that time I have found that I really need three official NGINX modules:
ngx_http_access_module
ngx_http_referer_module
ngx_http_limit_request_module
NGINX has done a nice job of moderating my CPU usage although it has not helped at all in regards to spam bots, Poorly written SEO site scanners etc. These can put massive loads on my server due to 95% of my sites being PHP driven. According to the NGINX documentation:
https://www.nginx.com/resources/admin-guide/installing-nginx-open-source/
all three of the modules are included in their official package. Based on fevangelou's first response to my initial request, it sounds like you are using the official NGINX package. So my question is, why are these modules not included in your version of NGINX? Followed up with, how do I replace the copy of NGINX you are using with the complete official version with all of the modules built by default?
Thanks for your time and expertise.

**Comment by fevangelou** [comment]
@millermultimedia The official Nginx repos for CentOS and other Red Hat variant OSes does not include these modules. The article you read mentions these modules when you custom built Nginx from source, not when you install Nginx from the CentOS repo. Since I'd like to follow the "update Nginx when CentOS/cPanel get updated" mantra, I don't plan on changing the installation of Nginx from repos to compiling from source.
