### ISSUE TITLE
Proxy Routing Docker to Subdomain

### ISSUE THREAD

**Issue by ekwo-hauka** [engintron/engintron#1190]
I have to run dockers on the Centos with Cpanel and the plugin additionally.
The installation of a container is successful so that it can be accessed on a local IP.
Now I wanted to put it on a sub.domain.info.
I have to:
```
if ($host = "https://x.domain.info") {
    set $PROXY_CHEME "https"
    set $PROXY_DOMAIN_OR_IP "xxx.xx.x.x"
    set $PROXY_TO_PORT 8445;
}
```
under Edit your custom_rules for Nginx (view default).
Unfortunately, when you call the subdomain it still remains in the directory as specified in the panel.
At the end the subdomain must be accessible via proxy under http and https each with a different port.
I hope someone can help me with this. 

PS the docker is a Jipsi but there are more to come.

**Comment by fevangelou** [comment]
The syntax you're using is wrong. It should be:
```
if ($host ~ "x.domain.info") {
    set $PROXY_CHEME "https"; # Is the internal protocol HTTPS? If not, change to "http"
    set $PROXY_DOMAIN_OR_IP "x.x.x.x";
    set $PROXY_TO_PORT 8445;
}
```

**Comment by ekwo-hauka** [comment]
thanks now it worked out
