### ISSUE TITLE
Engintron ON : CentOS 7 - Server in production - need to add module.

### ISSUE THREAD

**Issue by hfrance** [engintron/engintron#1194]
Hi,

At this moment the situation is, I have a dedicated server with engintron with centos 7.

Everything is fine but I need to add the module 

https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source

I dont want to make a compile error and shutdown my nginx. 

Someone have a simple but complete solution for compile the ngx_pagespeed module 

thank you

**Comment by fevangelou** [comment]
As far as I know, there is no easy solution. What you could do though is load the relevant Apache module. The result will be the same as Nginx will simply pass on the optimized assets to each visitor.
