### ISSUE TITLE
Engintron and WHM/Cpanel 88.5

### ISSUE THREAD

**Issue by WebSavvyDude** [engintron/engintron#1195]
WHM just released version 88.0.5

Anybody upgrade yet with the current version of Engintron?   Just don't want any unexpected events so would rather ask here first before upgrading.

@fevangelou are we good to go?

Thanks

**Comment by ardipa** [comment]
> WHM just released version 88.5
> 
> Anybody upgrade yet with the current version of Engintron? Just don't want any unexpected events so would rather ask here first before upgrading.
> 
> @fevangelou are we good to go?
> 
> Thanks

hi,
it's 88.0.5 and engintron working very well there ;)

**Comment by fevangelou** [comment]
"Shit happens" indeed 😄  but I also use Engintron on a daily basis so I'd know if anything breaks and quickly patch Engintron.

You're in good hands @WebSavvyDude.
