### ISSUE TITLE
Last 100 Errors Access Log Entries  Number 2

### ISSUE THREAD

**Issue by tibbie123** [engintron/engintron#1199]
My last error - looks like a few a second. Any idea what the heck they are? Or how I can get rid of?thanks, Simon  

2020/06/01 08:53:59 [error] 32197#32197: *6552 connect() failed (111: Connection refused) while connecting to upstream, client: 96.75.63.10, server: localhost, request: "GET /wp/wp-content/uploads/2015/03/itunes_image.jpg HTTP/1.1", upstream: "http://104.28.3.26:8080/wp/wp-content/uploads/2015/03/itunes_image.jpg", host: "www.yuppiejunk.com"
2020/06/01 08:53:59 [error] 32197#32197: *6552 connect() to [2606:4700:3030::681c:31a]:8080 failed (101: Network is unreachable) while connecting to upstream, client: 96.75.63.10, server: localhost, request: "GET /wp/wp-content/uploads/2015/03/itunes_image.jpg HTTP/1.1", upstream: "http://[2606:4700:3030::681c:31a]:8080/wp/wp-content/uploads/2015/03/itunes_image.jpg", host: "www.yuppiejunk.com"
2020/06/01 08:53:59 [error] 32197#32197: *6552 connect() to [2606:4700:3035::681c:21a]:8080 failed (101: Network is unreachable) while connecting to upstream, client: 96.75.63.10, server: localhost, request: "GET /wp/wp-content/uploads/2015/03/itunes_image.jpg HTTP/1.1", upstream: "http://[2606:4700:3035::681c:21a]:8080/wp/wp-content/uploads/2015/03/itunes_image.jpg", host: "www.yuppiejunk.com"
2020/06/01 08:53:59 [error] 32197#32197: *6552 connect() to [2606:4700:3033::ac43:8195]:8080 failed (101: Network is unreachable) while connecting to upstream, client: 96.75.63.10, server: localhost, request: "GET /wp/wp-content/uploads/2015/03/itunes_image.jpg HTTP/1.1", upstream: "http://[2606:4700:3033::ac43:8195]:8080/wp/wp-content/uploads/2015/03/itunes_image.jpg", host: "www.yuppiejunk.com"

**Comment by fevangelou** [comment]
Responded in https://github.com/engintron/engintron/issues/1198 - don't open multiple issues for the same thing.
