### ISSUE TITLE
How to change the Server version

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#120]
Hello,

I do not want the nginx server to be display on headers, any way to avoid this?

**Comment by fevangelou** [comment]
Aren't you proud of it? :)

Nginx version is already suppressed from nginx.conf. But I'm afraid you can't hide "nginx" entirely (the server header). Besides, Nginx is the last thing you should be worried about.

**Comment by highacid** [comment]
This can be hidden, but it requires precompile edit in httpheadermodule.c

**Comment by fevangelou** [comment]
Which is not worth the effort...

**Comment by amirvenus** [comment]
@uhlhosting 

Could you please provide a brief guide? It's really a super necessary feature! 

We are all proud of nginx but we don't necessarily want hackers to learn about the Web Server info..
