### ISSUE TITLE
Entries for domains not being created

### ISSUE THREAD

**Issue by FrogStoneMedia** [engintron/engintron#1200]
I initially submitted this to my web host, and they recommended sharing with Engintron support "It seems Engintron is not creating entry for the domains so the domains are loading default website. Please contact Engintron support to fix the isssue."

CENTOS 7.8 kvm [fro] v88.0.6 
Engintron v1.13.0 Build 20200328 (Nginx version: 1.18.0)

Steps:
Set registrar nameserver to server dns:

Nameserver
NS1.xyz.COM
NS2.xyz.COM

Create new account on WHM. 

Verify Auto SSL runs and works with DV cert, which normally tells me the domain is propagated and ready to load/work on.

Upon going to the site, it redirects to the main server fro.com domain.

I tried Restart Apache & force restart Nginx. Then I tried restarting the DNS server and saw these in the log:

Jun 02 15:05:23 xyz.x.com pdns_server[20432]: PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Jun 02 15:05:23 xyz.x.com pdns_server[20432]: Listening for HTTP requests on 127.0.0.1:953
Jun 02 15:05:23 xyz.x.com pdns_server[20432]: Creating backend connection for TCP
Jun 02 15:05:23 xyz.x.com pdns_server[20432]: [bindbackend] Parsing 271 domain(s), will report when done
Jun 02 15:05:23 xyz.x.com pdns_server[20432]: [bindbackend] Warning! Skipping zone '.' because type 'hint' is invalid
Jun 02 15:05:23 xyz.x.com pdns_server[20432]: [bindbackend] Warning! Skipping zone '.' because type 'hint' is invalid
Jun 02 15:05:23 xyz.x.com pdns_server[20432]: [bindbackend] Warning! Skipping zone '.' because type 'hint' is invalid
Jun 02 15:05:23 xyz.x.com pdns_server[20432]: [bindbackend] Done parsing domains, 3 rejected, 137 new, 0 removed
Jun 02 15:05:23 xyz.x.com systemd[1]: Started PowerDNS Authoritative Server.
Jun 02 15:05:23 xyz.x.com pdns_server[20432]: Only asked for 1 backend thread - operating unthreaded

**Comment by fevangelou** [comment]
Check this: https://engintron.com/docs/#/pages/SSL-certificate-changes-not-visible-in-Nginx%3F-Here-s-a-possible-explanation-&-solution

**Comment by FrogStoneMedia** [comment]
Just clicked the Update button on crontab without making any changes - didn't make any initially. Waited 10 minutes, then purged cache/temp files. Restarted DNS server, same log as above.

Here's my cron:

`SHELL=/bin/bash
`PATH=/sbin:/bin:/usr/sbin:/usr/bin
`MAILTO=root
`
`# For details see man 4 crontabs
`
`# Example of job definition:
`# .---------------- minute (0 - 59)
`# |  .------------- hour (0 - 23)
`# |  |  .---------- day of month (1 - 31)
`# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
`# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
`# |  |  |  |  |
`# *  *  *  *  * user-name  command to be executed
`
`
`* * * * 
`
`# Cron job to purge Nginx cache & temp files
`0 2 * * * root "/engintron.sh purgecache" >> /dev/null 2>&1
`* * * * 
`
`
`* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1
`
`

**Comment by fevangelou** [comment]
I've cleaned up your crontab so it's easier for others to see...

It's indeed broken. It should be:

```
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

# For details see man 4 crontabs

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name  command to be executed

# Cron job to purge Nginx cache & temp files
0 2 * * * root "/engintron.sh purgecache" >> /dev/null 2>&1

* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1
```

**Comment by FrogStoneMedia** [comment]
Looks like the domain is loading correctly now. Thanks for the help with that!
