### ISSUE TITLE
Engintron with Cloudflare and IPv6

### ISSUE THREAD

**Issue by WebSavvyDude** [engintron/engintron#1201]
Ok so we have this application on our server that logs users IPs and we can ban them.   We use Cloudflare and of course CF is a proxy so everyone has the same IP coming into our site. However, we have the module that converts that IP into their real IP.  (not sure if we installed that module or it comes automatically with Engintron).

Everything was working fine with regular IPv4 IPs coming through our application.  Troublesome users are banned and everything is fine.

However, recently we noticed some of the users that were being banned had Cloudflare IPv6's IPs associated with them.   Obviously we do not want to ban any Cloudflare IPs as it is usually shared by other users.

We found that odd as all other users with IPv4 were being converted from Cloudflare IPs to their real IPs no problem.   In our application logs we are also getting users with IPv6 IPs (non cloudflare IPs) from their ISP...so we know that at least some IPv6's are being converted to their real IPs.

All of the IPv6s came from this range "2405:8100::/32"  Whether thats a coincidence or significant, i don't know.

Within WHM for the Engintron dashboard i checked the nginx.conf file and it had

  ```
 # CloudFlare IPs
    # List from: https://www.cloudflare.com/ips-v4
    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 104.16.0.0/12;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 131.0.72.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    # List from: https://www.cloudflare.com/ips-v6
    set_real_ip_from 2400:cb00::/32;
    set_real_ip_from 2405:8100::/32;
    set_real_ip_from 2405:b500::/32;
    set_real_ip_from 2606:4700::/32;
    set_real_ip_from 2803:f800::/32;
    set_real_ip_from 2c0f:f248::/32;
    set_real_ip_from 2a06:98c0::/29;

    # Replace with correct visitor IP
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;
```

That looks ok..looks like all CF IPs are covered.

I wanted to check here to see if this might be an Engintron issue and any other configuration we need to add to get IPv6 to properly convert from Cloudflare to a real IP.

I have a ticket also open with Cloudflare now and they are telling me that the remoteIP module should also work for IPv6's.....so I am not sure whats going on.  

Hopefully someone can assist here.

**Comment by jonas8686** [comment]
I have the same problem on my Centos 7 server - Cpanel v88.0.6 
`2020/06/07 20:46:38 [error] 17843#17843: *67 connect() to [2606:4700:3033::ac43:9df5]:8080 failed (101: Network is unreachable) while connecting to upstream, client: 151.37.182.232, server: localhost, request: "GET /panel/ HTTP/1.1", upstream: "http://[2606:4700:3033::ac43:9df5]:8080/xxxxx/", host: "www.xxxxxxxxxxxxxxxx.com"`

**Comment by fevangelou** [comment]
@WebSavvyDude I would recommend a different approach. Since CF passes an additional HTTP header that contains the user's real IP address (https://github.com/engintron/engintron/blob/master/nginx/proxy_params_common#L25) use that in your app to grab the IP and decide whether to ban it or not.

CloudFlare IPs are always listed here: https://www.cloudflare.com/ips/ (though they very rarely change)

**Comment by fevangelou** [comment]
@jonas8686 That's different - your server may not be properly configured for IPv6 or your datacenter isn't. Simply switch to IPv4 resolvers in /etc/nginx.conf. This should fix your issue.

**Comment by WebSavvyDude** [comment]
Thanks for the reply @fevangelou .  I spoke to the developer and he told me there isn't any place in his app to add that:

`proxy_set_header              CF-Connecting-IP $http_cf_connecting_ip;`

I am guessing all the header information sent to the APP is directly from the origin server.  

Do you have any other solutions and an explanation as to why this problem is happening?   It doesn't happen with ipV4 addresses.    Looks like just some isolated ipV6's from Cloudflare.    The APP picks up other  non-cloudflare ipV6's well but it just seems some from Cloudflare "slip through" the cracks and show up in the logs as Cloudflare IPs.



> @WebSavvyDude I would recommend a different approach. Since CF passes an additional HTTP header that contains the user's real IP address (https://github.com/engintron/engintron/blob/master/nginx/proxy_params_common#L25) use that in your app to grab the IP and decide whether to ban it or not.
> 
> CloudFlare IPs are always listed here: https://www.cloudflare.com/ips/ (though they very rarely change)

**Comment by fevangelou** [comment]
Utilizing this header is the most reliable way to get a visitor's IP. You can double check with CloudFlare support if you want.

> I spoke to the developer and he told me there isn't any place in his app to add that:

If it's a custom app, there's always an option to add a new HTTP header to lookup IP info. It's done from the X-Real-IP http header already. If your developer says this can't be done, they're bullsh*tting you.

**Comment by fevangelou** [comment]
The HTTP header sent by CloudFlare is "CF-Connecting-IP" for clarification and it's passed on by Engintron to the backend.
