### ISSUE TITLE
High worker CPU usage

### ISSUE THREAD

**Issue by jdarow** [engintron/engintron#1202]
We have a client using cPanel with:

CloudLinux Server release 6.10
Apache/2.4.43 (cPanel)
engintron 1.9

They have custom php scripts that deliver flash player content converted with ffmpeg-php.  The load can get extremely high with workers consuming all the CPU.  Disk i/o and memory usage are both low during these periods.

worker_processes auto;

We have tried worker_connections 1024, 49152 ( server has 48 cores) and 65535.  No real change in load and CPU usage.  

keepalive-timeout 10;

Perhaps when the server gets slow, the timeout isn't long enough.  We didn't modify this value at all.

Any suggestions on what else can be done?  The server will be fine, then top will fill with worker processes using all the CPU and load will spike to 1000+

**Comment by fevangelou** [comment]
You didn't mention which process eats up your CPU cause I'm pretty sure it's not Nginx...

**Comment by jdarow** [comment]
` 7440 nginx     20   0  155m  73m  52m R 21.6  0.0 149:12.72 nginx: worker process`

Just a bunch of worker processes using 80% of CPU via atop (sys using the other 19-20%).  There are simple php scripts that get data / modify DBs and open the flash player.  Those processes complete quickly.  Mysql CPU usage is low.

**Comment by jdarow** [comment]
Right now the load is fine (~10). Only a few workers showing up, but almost as many php processes. Currently 200 requests/sec, but was only around 250 when load was 1000+

**Comment by fevangelou** [comment]
Revert the changes you did in /etc/nginx/nginx.conf (the defaults are already pretty generous).

Consult the optimization guides beyond Engintron/Nginx here: https://engintron.com/docs/#/pages/Beyond-Engintron-cPanel-WHM-initial-optimal-setup
