### ISSUE TITLE
Memcached Error

### ISSUE THREAD

**Issue by tibbie123** [engintron/engintron#1203]
Hi, I have tried to install memcached from
https://engintron.com/docs/#/pages/Install-Memcached-in-cPanel-(EasyApache-4-only)

 bash /usr/local/src/engintron/utilities/install_memcached_in_cpanel_ea4_no_exp_repo.sh 512M

the updated version June 29th 2018

I get the below error at the bottom of the installation which I note does not mention the current ea-php7.4 which I am using.

********** Memcached PHP configuration **********
/usr/local/src/engintron/utilities/install_memcached_in_cpanel_ea4_no_exp_repo.sh: line 195: /opt/cpanel/ea-php56/root/usr/bin/php: No such file or directory
/usr/local/src/engintron/utilities/install_memcached_in_cpanel_ea4_no_exp_repo.sh: line 196: /opt/cpanel/ea-php70/root/usr/bin/php: No such file or directory
/usr/local/src/engintron/utilities/install_memcached_in_cpanel_ea4_no_exp_repo.sh: line 197: /opt/cpanel/ea-php71/root/usr/bin/php: No such file or directory
/usr/local/src/engintron/utilities/install_memcached_in_cpanel_ea4_no_exp_repo.sh: line 198: /opt/cpanel/ea-php72/root/usr/bin/php: No such file or directory
/usr/local/src/engintron/utilities/install_memcached_in_cpanel_ea4_no_exp_repo.sh: line 199: /opt/cpanel/ea-php73/root/usr/bin/php: No such file or directory

 ****************************************************
 *         Memcached installation complete          *
 ****************************************************

**Comment by fevangelou** [comment]
Support for PHP 7.4 will be added in a coming update of Engintron.

PHP 7.4 support in cPanel was only very recently added and I'm pretty sure they still won't have the memcached module ready.

**Comment by fevangelou** [comment]
Of course you can always try: `yum -y install ea-php74-php-memcached` (if the package exists, but like I said, I doubt it does).

**Comment by tibbie123** [comment]
Hi, I rolled back to PHP 7.3, ran   /usr/local/src/engintron/utilities/install_memcached_in_cpanel_ea4.sh 3072M and it all ran perfectly! Thank you (again)
