### ISSUE TITLE
Yoast (and other) Sitemaps

### ISSUE THREAD

**Issue by tibbie123** [engintron/engintron#1204]
Hi, google has not been able to reach my yoast sitemaps for a while now. Errors such as Couldn´t Fetch. 
I see this suggestion here  https://www.arnebrachhold.de/projects/wordpress-plugins/google-xml-sitemaps-generator/help/ and https://yoast.com/help/xml-sitemaps-nginx/

"If you are using nginx as a webserver, please add the Rewrite Rules manually. They should be displayed at the Plugins settings page."

Could you please advise a Rewrite Rule? I Tried the Yoast one in functions.php in theme editor. It has errors

# Rewrites for Yoast SEO XML Sitemap
rewrite ^/sitemap_index.xml$ /index.php?sitemap=1 last;
rewrite ^/([^/]+?)-sitemap([0-9]+)?.xml$ /index.php?sitemap=$1&sitemap_n=$2 last

Your PHP code changes were rolled back due to an error on file wp-content/themes/porto-child/functions.php. Please fix and try saving again.

syntax error, unexpected '/'

**Comment by fevangelou** [comment]
Use .htaccess rewrites only, DO NOT use Nginx rewrites. The rules suggested by Yoast apply only when Nginx is the primary webserver and not a proxy (as in the case of Engintron).

**Comment by tibbie123** [comment]
Understood, thanks
