### ISSUE TITLE
I'm not able to create a rule to send all trafic to https

### ISSUE THREAD

**Issue by gotplitz** [engintron/engintron#1205]
I have this rules:

```
if ($host = "dorothyophals.com") {
     set $PROXY_SCHEME "http";
     set $PROXY_TO_PORT 5070;
}

if ($host = "dashboard.dorothyophals.com") {
     set $PROXY_SCHEME "http";
     set $PROXY_TO_PORT 5071;
}

if ($host = "plitz7.com") {
     set $PROXY_SCHEME "http";
     set $PROXY_TO_PORT 5001;
}

if ($host = "gotplitz.com") {
     set $PROXY_SCHEME "http";
     set $PROXY_TO_PORT 5002;
}
```
I don't know how to make all this website load in https mode, I'm not really expert in servers. The samples you have are for CloudFlare, I don't use that service. I tried using the .htaccess but I get too many redirects error.

Thanks for your help.

**Comment by fevangelou** [comment]
Why are you using these ports? Are these sites based on Node or something?

**Comment by gotplitz** [comment]
Yes, these are MERN applications.

**Comment by fevangelou** [comment]
Node apps are not affected by Apache/.htaccess.

If your apps listen on "http" and the ports are correct, proxying should work just fine.

Just know that `if ($host = "gotplitz.com") {` however (as with others) will never match "www.gotplitz.com".

**Comment by fevangelou** [comment]
Forgot to mention that if you wish to redirect HTTP to HTTPS traffic by default, you'd also need to do this (per domain):
```
# Combine the protocol and host name into a single variable
set $URI "$scheme://$host"; # Don't include this again

if ($URI ~ "http://gotplitz.com") {
    redirect 301 https://gotplitz.com;
}
```

**Comment by gotplitz** [comment]
> Forgot to mention that if you wish to redirect HTTP to HTTPS traffic by default, you'd also need to do this (per domain):
> 
> ```
> # Combine the protocol and host name into a single variable
> set $URI "$scheme://$host"; # Don't include this again
> 
> if ($URI ~ "http://gotplitz.com") {
>     redirect 301 https://gotplitz.com;
> }
> ```
> 
> You can make the redirect more generic of course, but this may affect other domains that don't run on Node.

Hi fevangelou, I tried this and still don't work. About the response before, should I create a rule for the www. or what is the best option? When I mentioned about .htaccess it was just to mention that I tried everything, and nothing looks to work to ensure all traffic is redirect to https, that's actually my main issue, if you go to gotplitz.com it works in that port, it's just that is loading http and not https.

**Comment by fevangelou** [comment]
Sorry, made a typo. The correct redirect code is:
```
# Combine the protocol and host name into a single variable
set $URI "$scheme://$host"; # Don't include this again

if ($URI ~ "http://gotplitz.com") {
    return 301 https://gotplitz.com;
}
```

**Comment by gotplitz** [comment]
Hi, still not working, it just loads http://gotplitz.com

**Comment by fevangelou** [comment]
Since I can see your node files but Engintron IS present, this means that your rules are probably messed up.

You need to add the redirect rules first and THEN add then proxying rules to the node apps.

**Comment by gotplitz** [comment]
Thanks for your help, but I gave up, I removed Engitron, if I have only one website your rule works, but I have 7 websites here. I will go directly with Nginx, thanks though.
