### ISSUE TITLE
APCu vs Memcached

### ISSUE THREAD

**Issue by ardipa** [engintron/engintron#1206]
Hi,

I am very confused with these caching tech, In Engintron docs there is APCu and Memcached installer but in some topic like:
https://github.com/engintron/engintron/issues/1025
You mentioned that: "I highly recommend you use Memcached over APCu in any case."

Well what should I do?
Install both Memcached and APCu? Ignore APCu? Which one should I keep or not install?!
I'm just sitting here and wait for your help :)

Thanks.

p.s.
My VPS has 4GB Ram + 2vCPU with fresh Centos 7

**Comment by fevangelou** [comment]
You can install both. But if you have the option to select one of the 2 (e.g. Joomla has cache drivers for both APCu and Memcached), then prefer Memcached.

**Comment by ardipa** [comment]
Thank you in advance!!
