### ISSUE TITLE
Better Way to offload SSL to Nginx

### ISSUE THREAD

**Issue by vaska94** [engintron/engintron#1207]
Hello, https://engintron.com/docs/#/pages/Offload-HTTPS-traffic-to-Nginx-only
This article is little bit outdated and breaks `Force SSL` functionality in Cpanel. 
I have found better way.

Step 1. Edit /etc/apache2/conf.d/includes/pre_virtualhost_global.conf and append:
`SetEnvIf X-Forwarded-Proto "https" HTTPS=on`

Step 2. Edit /var/cpanel/templates/apache2_4/vhost.default
Find
`RewriteCond %{HTTPS} !=on`
Replace with
`RewriteCond %{HTTP:X-Forwarded-Proto} !https`

Step 3. Edit /etc/nginx/proxy_params_common to update proxy_pass:
`proxy_pass http://$PROXY_DOMAIN_OR_IP:8080;`

--

```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```
will cause redirect loop, instead use Force SSL Option From Cpanel or
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>
```
P.s: you can use grep to find sites using htaccess redirect to avoid redirect loops:
`grep -rnHIi '{HTTPS}' --include=.htaccess /home`
Feel free to update current guide!

**Comment by fevangelou** [comment]
I recommend you make a new one if possible (and in detail) so I can publish it as well :)

**Comment by vaska94** [comment]
Here is Revised Guide : 
https://sysadmin.lol/engintron-ssl-offload/

Here is Source Code in Markdown:
https://paste2.org/FvHOFaGf

**Comment by fevangelou** [comment]
Thank you. I'll make sure a reference is added to the Engintron docs.
