### ISSUE TITLE
SSL Issues Using Engintron

### ISSUE THREAD

**Issue by scott8787979** [engintron/engintron#1209]
I am using the latest Engintron plugin in cPanel CENTOS 7.8 v88.0.11 (EasyApache 4.x)

I do not use cPanel to purchase and install my SSL certificates--mine are bought directly from Trustwave and self-installed.

After updating my SSL Certificate Engintron could not find this newly installed certificate, even though it was installed correctly via cPanel. SSL browser errors were thrown, and the only way I could fix this issue was by going into cPanel's Tweak Settings and doing the following:

1) Changing the Apache non-SSL IP/port to: 0.0.0.0:8080.
2) Changing the Apache SSL port to: 0.0.0.0:8043
3) Click Save.
4) Changing the Apache non-SSL IP/port back to: 0.0.0.0:80.
5) Changing the Apache SSL port back to: 0.0.0.0:443
6) Click Save.

Then everything was operating normally, until I rebooted my server, then this same issue came back! Now, each time I reboot my server I must go through the above steps to fix the certificate issue. Why? 

How can I resolve this issue so that when I reboot my server it does not break my SSL?

**Comment by fevangelou** [comment]
That's not a solution. This is simply switching Apache in place of Nginx.

If you don't wish to use Nginx, simply uninstall Engintron.

If you do want to keep Nginx, you need to revert any changes in Tweak Settings you did or uninstall and reinstall Engintron (to resolve these issues). After Engintron is fully working, send me the URL to one of your sites so I can check any SSL errors.

**Comment by scott8787979** [comment]
I cannot run Engintron since updating my SSL. I am unable to get it running. Whenever I change the ports I get SSL errors.

**Comment by scott8787979** [comment]
PS - After installing the new SSL I'm unable to get Engintron working properly. How can I fix this issue?

**Comment by scott8787979** [comment]
Is uninstalling and re-installing the best answer? This seems kind of strange. Have several sites on the server with self-installed SSL certs. Will I have to do this each time I update a cert?

**Comment by scott8787979** [comment]
So I successfully uninstalled the plugin, then re-installed it, and I still get this error:

Your connection is not secure

The website tried to negotiate an inadequate level of security.

www.celiac.com uses security technology that is outdated and vulnerable to attack. An attacker could easily reveal information which you thought to be safe. The website administrator will need to fix the server first before you can visit the site.

Error code: NS_ERROR_NET_INADEQUATE_SECURITY

**Comment by scott8787979** [comment]
I got it working! So far I am not seeing any performance boost compared to Apache PHP-FPM. Are there any other speed changes I can make besides this:
nginx.conf:
client_body_timeout            5s; # Use 5s for high-traffic sites
client_header_timeout          5s; # Use 5s for high-traffic sites

Also, I am tying to upgrade cipher code used and protocols to make my server more secure. I tried to change this in common_https.conf:
ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA;

To this:
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:!DSS:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256;

But it does not work.  Any idea how to make this change?

**Comment by scott8787979** [comment]
So please forget the SSL Cipher change, I did not need it. I am able to get an A+ with just this change, which I recommend that you make as a default in your plugin:
ssl_protocols TLSv1.2 TLSv1.3;
https://www.ssllabs.com/ssltest/analyze.html?d=www.celiac.com 

If you have any guidance on how I can speed up my server please let me know.

**Comment by scott8787979** [comment]
And I just noticed in that test that TLSv1.3 is NOT working. Any idea why not?

**Comment by fevangelou** [comment]
When you comment out one block (e.g. the one with TLS 1.2 & 1.3) you MUST comment the one you previously used.

Can you verify that?

**Comment by scott8787979** [comment]
I believe I figured out the SSL issues, but was wondering if you could please answer the following:

1) Although I've uninstalled and reinstalled it and the SSL works, I tried de-activating the plugin again today, then re-activating it, and the problem came back--it could not find my SSL cert. I had to again uninstall and re-install the plugin. This tells me if my server should be rebooted it will not find the cert, and I will have to re-install it. Is this really how you guys want this plugin to work? Can you fix this?

2) Is it faster than Apache PHP-FPM? So far I'm not seeing it. I asked about other settings to speed it up... I have 65G of memory, are there any other setting changes I can make? So far it seems the same speed as Apache PHP-FPM.

**Comment by scott8787979** [comment]
3. My cipher suite won't work...it's actually the default cipher for cpanel. I am commenting out the old cipher, but it breaks ssl. Also, I can't get TLS 1.3 working no matter what I do. Not sure why.

ssl_ciphers ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:!DSS:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256;

**Comment by fevangelou** [comment]
Replying...

1. When you activate/de-activate the plugin, it may take a couple of mins for changes to take effect. You should not think of this as a simple switch you toggle and everything instantly works. Additionally, there may be issues with Nginx's installation, ESPECIALLY if you previously had another plugin for Nginx installed in cPanel. In any case, it's difficult to troubleshoot without actually seeing any logs.

2. Yes, obviously. Engintron will shine when you have lots of traffic. For a couple requests per minute, it won't seem like a big difference. However there are other benefits that require some slight tweaking. E.g. if you use WordPress only on your sites, you can bump the cache time to 2-3 minutes and then you'll see how much faster sites are served. Engintron v2 (which will be out this year) will offer a separate configuration for WordPress sites only to accelerate them automatically.

3. Use the default one in both cPanel and Engintron and don't really sweat about it.

**Comment by scott8787979** [comment]
Thank you...

My site is fairly busy and gets ~500-700 unique visitors every 15 minutes. It isn't WP, but is Invision Power Board, so the heart is a large, busy forum with nearly 1M posts.

and for #3, I still can't get TLS 1.3 working and I am not sure why. It could be some other issue, but my thinking was to change the cipher code in Engintron, but I can't seem to do that without causing the SSL to break.

**Comment by fevangelou** [comment]
Engintron provides some caching exceptions for IPB. See the file proxy_params_dynamic inside /etc/nginx/. Perhaps you can bump the dynamic cache time then to more seconds or even mins.

As for the TLS 1.3 issue, don't change the cipher lines. These come directly from Mozilla's SSL configurator. If there are issues, perhaps there's an issue with your SSL certificate. Why not try using LetsEncrypt (via AutoSSL) for the time being?

**Comment by scott8787979** [comment]
I can report good news that I rebooted my server yesterday, and everything came up fine. I had no issues with the SSL. 

I changed the line below to 60s, and will experiment with that setting:
proxy_cache_valid              200 1s; # Adjust for longer server-side cache times (unfortunately, we cannot use a variable here)

I will check into my SSL cert to see if there is an issue with it.

**Comment by scott8787979** [comment]
With regard to my cert TLS 1.3 issue, cPanel had me run this command:
# rpm -qa |grep ea-openssl1
which showed this installed:
ea-openssl11-1.1.1g-1.1.2.cpanel.x86_64

They said I needed to install this package and restart Apache:
ea-openssl11-devel-1.1.1g-1.1.2.cpanel.x86_64

I installed it successfully:
yum -y install ea-openssl11-devel-1.1.1g-1.1.2.cpanel.x86_64

and used the Enginetron plugin to restart Apache and Engintron, however, this did not fix the TLS 1.3 issues. Is it possible I need to reinstall Enginetron after doing that?

**Comment by scott8787979** [comment]
So when I turn off Engintron my TLS 1.3 works fine:
This server supports TLS 1.3.

When I enable it it does not work. I even tried uninstalling Engintron and re-installing it.  Can you help solve this issue?

**Comment by fevangelou** [comment]
Perhaps the official Nginx packages are not built/compiled to work with TLS v1.3 in CentOS.

**Comment by scott8787979** [comment]
This is ironic because TLS 1.3 is faster, and the whole reason I installed Engintron was because I've heard that NGINX is faster than Apache. 

I've disabled the Engintron plugin to run some speed tests. Will it stay disabled, even on reboot, and not interfere with anything?

**Comment by fevangelou** [comment]
Yes.

**Comment by scott8787979** [comment]
So is there any way for you to verify whether my TLS 1.3 issue is due to NGINX not being compiled to work with CentOS? It seems like I'm running a popular configuration, so I still wonder if the issue is not something on my configuration.

**Comment by fevangelou** [comment]
I can't possibly know...

**Comment by scott8787979** [comment]
Ok, well, thank you for your help. It looks like others are having this issue as well:
[https://github.com/engintron/engintron/issues/1157](https://github.com/engintron/engintron/issues/1157)

Unfortunately with TLS v1.2 I'm not seeing any speed increase. It might be faster with TLS v1.3 but I guess I won't know until it will work with it.

**Comment by scott8787979** [comment]
Does this look like a possible solution? 
[https://dev.to/bidhanahdib/how-to-enable-tls-1-3-in-nginx-with-openssl-centos-7-4f4b](https://dev.to/bidhanahdib/how-to-enable-tls-1-3-in-nginx-with-openssl-centos-7-4f4b)

When I run this command:
openssl ciphers -v | awk '{print $2}' | sort | uniq
I don't see v 1.3 installed:
SSLv3
TLSv1.2

But somehow it is working with Apache.
