### ISSUE TITLE
Add Varnish to engintron!

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#121]
This will be a great deal and feature to Engintron, I am sure this will even gain more users @ engintron.

**Comment by fevangelou** [comment]
Engintron caching already does 99% of the things Varnish would do. But it also does micro-caching, which Varnish is not suitable for. Nginx with micro-caching is the proper solution to have page caching for any website without the need to URL exclusions. This allows websites to have user generated content (e.g. forums or e-commerce sites) without specifying any URL exclusions to Nginx, so Nginx doesn't cache user entry points. This is VERY important and it's something Varnish simply can't do at this scale.

**Comment by frilogg** [comment]
I know this is a closed topic, but just wanted to say I totally agree with Fegangelou, its not use of Varnish in combo with Engintron.
