### ISSUE TITLE
502 bad gateway after migration

### ISSUE THREAD

**Issue by slumer** [engintron/engintron#1211]
We have installed engitron to a new cpanel server.
When we transfered new accounts to the server , we got 502 error . 
We tried to create a new account , and the new account worked fine . 

In the logs i saw , that the migrated hosting was trying to connect to the previous ip
the transfer made , with migration tool of cpanel . 

I tried to  rm -rf /etc/nginx/conf.d/default_https.conf and /etc/nginx/utilities/https_vhosts.sh but it didnt work

**Comment by fevangelou** [comment]
Set a fixed IP in Engintron's "custom rules" file. And do read the docs, there's a reason they exist...
