### ISSUE TITLE
how to define custom rules

### ISSUE THREAD

**Issue by juanremi** [engintron/engintron#1214]
i defined custom rules in /etc/nginx/conf.d/default_https.conf

but after some time, the default_https.conf was re-loaded again with only the ngitron routes/rules

how can i define custom rules for an existing subdomain to avoid this dissapear?

**Comment by fevangelou** [comment]
Use the "custom rules" file which exists for that reason.

**Comment by juanremi** [comment]
I try to use the custom_rules files, but i got the error: 
nginx: [emerg] "location" directive is not allowed here in /etc/nginx/custom_rules:121
nginx: configuration file /etc/nginx/nginx.conf test failed

```
    location ^~ /static {
        proxy_pass http://localhost:9090/static;
    }
    location ~* ^/(?!(static)) {
        try_files $uri @proxy_django;
    }
    location @proxy_django {
        uwsgi_pass  127.0.0.1:3031; #django;
        include     /pathto/uwsgi_params;
    }
```

any idea? thanks

**Comment by fevangelou** [comment]
```
    location ^~ /static {
        proxy_pass http://localhost:9090/static;
    }
```
You probably don't need that if they are indeed static files.

To proxy to a Python app, you need to configure the app to either run standalone or via Apache as the web server. Then and only then you can use something like:
```
if ($host = "app.mypythonapp.com") {
    set $PROXY_SCHEME "http";
    set $PROXY_DOMAIN_OR_IP "127.0.0.1";
    set $PROXY_TO_PORT 3031;
}
```

Engintron configures Nginx as a generic proxy, not as the direct web/app server for which you're attempting to load the uWSGI Python integration.

**Comment by fevangelou** [comment]
Here's a guide to use the mod_wsgi module for Apache to launch your Python app: https://forums.cpanel.net/threads/configure-easyapache-experimental-for-python-with-mod_wsgi.647561/

After that, simply create the proxy block I mentioned and you're done.

And if you place your files inside an account's public_html folder so the /static path in your Python app is symmetrical to public_html/static/, then you don't need a special rule for the static files.

**Comment by juanremi** [comment]
> ```
> if ($host = "app.mypythonapp.com") {
>     set $PROXY_SCHEME "http";
>     set $PROXY_DOMAIN_OR_IP "127.0.0.1";
>     set $PROXY_TO_PORT 3031;
> }
> ```

Following your example @fevangelou : 

If the host matches the rule, but i need to use a subfolder, how can i specify the rule?.

For example, 

> url: app.mypythonapp.com/mydir/ > to proxy1
> host: app.mypythonapp.com
> location: mydir

and
```
url: app.mypythonapp.com/mydir2/ > to proxy2
host: app.mypythonapp.com
location: mydir2
```

```
if ($host = "app.mypythonapp.com") {
    location ~ ^/mydir1/ {
    }
    location ~ ^/mydir2/ {
    }
}
```

is that ok?

**Comment by fevangelou** [comment]
Nope. Only symmetrical redirects.

Don't use subfolders internally. If you app responds to a certain port only, don't put it in a subfolder. Make a subdomain for it in cPanel, place it there and then proxy requests on 80/443 (via Nginx) to the internal port.

Can't get any simpler.
