### ISSUE TITLE
recompiling Nginx with image filter

### ISSUE THREAD

**Issue by Sulieman9** [engintron/engintron#1215]
Hello 
I successfully run Engintron with Nginx, all fine.
but I  need to re-compile it with image filter ti use the image resize feature , Is it possible to add modules to Nginx while using Engintron? 
If yes, Could you please help how to do that since i didn't find the Nginx source folder.?
Thank

**Comment by fevangelou** [comment]
> Is it possible to add modules to Nginx while using Engintron

Nope.

**Comment by Sulieman9** [comment]
Can you please advice? how to found it ?

**Comment by fevangelou** [comment]
Not possible with Engintron's Nginx build. Sorry.
