### ISSUE TITLE
Apache logs to domain.tld but not domain.tld-ssl_log

### ISSUE THREAD

**Issue by cPJasonB** [engintron/engintron#1216]
I'm uncertain if non-cPanel installations are affected, but when using the default configuration of Engintron with cPanel which proxies through Apache, Apache logs all requests to /var/log/apache2/domlogs/domain.tld regardless of whether https is in use.

```-bash-4.2# rpm -q ea-apache24{,-config,-config-runtime} nginx
ea-apache24-2.4.43-5.5.3.cpanel.x86_64
ea-apache24-config-1.0-164.164.1.cpanel.noarch
ea-apache24-config-runtime-1.0-164.164.1.cpanel.noarch
nginx-1.18.0-1.el7.ngx.x86_64```

**Comment by fevangelou** [comment]
Since cPanel folks usually append "cP" in front of their names, are you working for cPanel? If so, is the affected client server using CloudFlare perhaps in which you might get an HTTPS to HTTP proxying scenario (if using the "Flexible SSL" option)?

If no CloudFlare is used and since Engintron modifies the mod_remoteip module's config (see https://github.com/engintron/engintron/blob/master/engintron.sh#L62-L63) to include the user's actual IP, perhaps the issue is related to some configuration bug between mod_remoteip and how cPanel's Apache config is setup for logging.

**Comment by cPJasonB** [comment]
Hi @fevangelou 

Yes, I work for cPanel.

I do not believe the client server was using CloudFlare, no.

I reproduced the issue on a testing server without CloudFlare involved. I made use of a non-existant domain in my testing.

I added this to the configuration (where 1.2.3.4 represents the server's IP address) to prevent a 503 error since the domain did not exist but I was using a hosts file to access:


```
if ($host ~ "om.tld") {
--
set $PROXY_DOMAIN_OR_IP "1.2.3.4";
}
```

I would think that the issue must be with how nginx is proxying to Apache as I wouldn't think that Apache would log SSL requests to the non-SSL log unless they came in over port 80. It seems unlikely to be caused by mod-remoteip as I would expect this also to impact Apache only servers.

Are you able to test this on your end to replicate?

**Comment by fevangelou** [comment]
Is this "om.tld" domain configured in cPanel though? Does it have an SSL vhost in Apache's config?

**Comment by cPJasonB** [comment]
Yes, "om.tld" was a primary domain of a cPanel account and had a secure vhost in the Apache configuration.

**Comment by fevangelou** [comment]
I can confirm that *-ssl_log files are indeed empty in production and test servers.

However proxying works as expected.

Unless something else is wrong in your setup, proxying should always be symmetrical. In other words, Nginx's ports 80 and 443 would proxy traffic to Apache's port 8080 and 8443.

In a typical httpd.conf created by cPanel, I see this:
```
# This allows us to not log requests proxied to Apache from nginx;
#    That way hits are not double recorded.
SetEnvIf cPanel-localhost 1 isproxyrequest
```

And then on each vhost there's a check for "isproxyrequest" when logging requests from SSL.

```
CustomLog "|/usr/local/cpanel/bin/splitlogs --dir=/etc/apache2/logs/domlogs --main=server.hostname.tld --mainout=/etc/apache2/logs/access_log --sslport=8443" combinedvhost env=!isproxyrequest
```

So it does seem like a mis-configuration on cPanel's side if I'm reading that correctly (if the request is proxied by Nginx, do not log SSL traffic).

**Comment by cPJasonB** [comment]
There was a time where I'd agree with you, as there was an issue where **all** (not just SSL) proxied traffic (including all CDNS, varnish, and nginx) was not logged. That was a result of this [change](https://docs.cpanel.net/changelogs/easyapache-4-change-log-2020/):

    ZC-6899: do not log proxied requests to avoid double counting of them in stats.

We later fixed this so that this should only impact ea-nginx:

EA-9123: Check for cPanel-localhost to see if we are proxying from nginx.

If you downgrade ea-apache24-config and ea-apache24-config-runtime to the earliest version possible which would be before anything related to "isproxyrequest" was added, this issue is still present.

**Comment by fevangelou** [comment]
Well, in any case, the issue is part of Apache's config. Nginx as I said symmetrically proxies requests. 80 to 8080 and 443 to 8443 - and this is easy to double-check on your side if you want.  So what Apache does afterwards cannot be related to Nginx (or Engintron).

**Comment by cPJasonB** [comment]
I've updated our internal case with this information (case ID EA-9180). Since the issue appears to be present in all published versions of Apache, it doesn't appear to be a new issue as far as I can tell. I'm not sure how long this has been occurring, nor am I sure if this is related to changes cPanel has made to Apache.

I appreciate your time and consideration. I'll update if there's anything new to add.

**Comment by fevangelou** [comment]
Thank you.
