### ISSUE TITLE
Service (formerly proxy) subdomains do not work with 'WHM >> Terminal' or 'cPanel >> Terminal'

### ISSUE THREAD

**Issue by cPholloway** [engintron/engintron#1217]
* The reason for this is that nginx is currently using a http 1.0 connection which does not support 'Upgrades' such as the WebServer Socket (ws or wss) that is used in these interfaces
* In order to correct this, the following needs to be added to the Service Subdomain configuration

`proxy_http_version 1.1;`

**Comment by fevangelou** [comment]
It's been 1.1 for some time already...

https://github.com/engintron/engintron/blob/master/nginx/proxy_params_common#L13
