### ISSUE TITLE
XSS related issue with nginx engintron running on Apache/cPanel

### ISSUE THREAD

**Issue by Undefined-Variables** [engintron/engintron#1218]
One of our servers uses nginx engintron running as a reverse proxy cache (system details below).

````

OS: CentOS Linux release 7.8.2003 (Core)

Kernel: Linux dxxxxxxxxx.eu 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

````

I have found a problem that I'm unsure of how to solve, setting an alert inside script tags nginx will cache the javascript and is executed when the cache is purged using the root account. For example

If you use this

        https://example.com/signup/?ref=main&a=index&u=chaya-ward&f_n=Avis"><script>alert('XSS')</script>

Using this on a properly written website does nothing as it gets escaped like it should be. But what we have noticed is that on purging the cache that nginx holds it is executed...

![xss2](https://user-images.githubusercontent.com/52648055/88385892-31629c00-cda7-11ea-9d8b-e5c661954438.PNG)

I can see this catching someone out as its executed when you are logged as root. How can we stop this from happening?

**Comment by fevangelou** [comment]
Indeed this may come up when you and only you test the site (aka there is no real traffic) and Nginx throws the last log messages in the restart routine (containing your actions). But on a production server that is probably highly unlikely to happen.

The logs are already filtered for that as it was more likely to have something like that occur there, but just in case, I'll add a filter for that part as well.

Thanks for reporting that.

**Comment by Undefined-Variables** [comment]
This is on our production server with high traffic volumes!

**Comment by Undefined-Variables** [comment]
Sorry I have time to answer your reply properly now. This is happening in a full production environment and not any form of safe/test installation. This server is almost 2yrs old having been running a number of live sites that see their share in traffic. We had been running Apache 2.4 until we recently had a sudden rise in traffic and needed to speed a few things up. Nginx was our best option so had this plugin installed 3 months ago by the hosting company to be sure it was done correctly. 

This is possible in more than one way, straight forward script tags added to the end of any URI query string but once we assumed that was solved using custom regex to remove the tags from the URI query before it had chance to execute we then found if you HTML Encode the tags and alert then URL Encode the output of the HTML Encoding and added that to the same URI query it was totally missed and found its way in to nginx cached files, then executed at the worst possible time. 

This could be any valid javascript and it would execute on the root account when the cache is purged... This could be a disaster in so many different ways.    

There are also some really irritating problems too like in WHM you are constantly interrupted by a side bar asking if you can collect info and why is there not a simple way to disable cache for times like maintenance or updating? Its all or nothing and disabling nginx really upsets the server and all the sites hosted on it are down while Apache sorts its life out!

**Comment by fevangelou** [comment]
Wow, so many questions...

> There are also some really irritating problems too like in WHM you are constantly interrupted by a side bar asking if you can collect info[...]

That's coming from WHM, not Engintron.

> [...]why is there not a simple way to disable cache for times like maintenance or updating[...]

Are you referring to the sites or the server? If it's the sites, the cache won't cause any issues either way as there's most likely an exclusion for the CMSs you use. If it's about the server, why would Nginx's 1 sec cache cause issues exactly?

And to return to your original question, it will be dealt with in a future update. In the meantime you can always use Engintron's CLI. Just execute /engintron.sh in the terminal to see all available options.

**Comment by Undefined-Variables** [comment]
I was referring to the ten minute micro cache that is part of Engintron. We are can not disable it without disabling Engintron all together and when we do disable it for maintenance all the sites hosted on that server go down for a good five minutes with bad gateway errors. Once apache has restarted all is fine again but then we have the same on reenabling Engintron. 

There is a shortcut link to purge the cache and temporary files so could there not be one that turns the cache off? And that irritating side popup only happens on the Engintron page, why is that? I'm not sure but it never happens anywhere else but on this one page.

**Comment by fevangelou** [comment]
You can bypass caching for certain domains or even domain paths/subfolders. See the notes in "Custom Rules" and read the docs at engintron.com/docs for additional help. There is no reason to disable Engintron...

The popup you mention (and like the menu on the left that will always expand when a PHP-based cPanel plugin is loaded is most likely a bug in cPanel's PHP API.

**Comment by Undefined-Variables** [comment]
Okay I will do this thank you for your help and I will close this now and look forward to the release that fixes this issue :)

**Comment by fevangelou** [comment]
You're welcome.
