### ISSUE TITLE
Right after i installed memecache I started getting too much notification!

### ISSUE THREAD

**Issue by Shahzadqayyum** [engintron/engintron#1219]
Hi!
Right after i installed memecached I started getting too much notification!
My Emails are being bounced back As i have set limit on server!
I tried every method to stop these notifications in CSF!
tried
exe:/sbin/memcached in  p.ignore!
but its still sending me these emails.
http://prntscr.com/tom9rl

though i have un installed memcached and re installed engintron, compiled EA4 again without memcache but still useless.

Please help!
regards
Shahzad

**Comment by fevangelou** [comment]
This boils down to your CSF/LFD configuration which is obviously too strict. The Memcached installer works just fine with a stock CSF installation.
