### ISSUE TITLE
PHP-FPM support in Cpanel with ENGINTRON?

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#122]
Does engintron works well with PHP-FPM?

I have deployed it by this guide. 

https://documentation.cpanel.net/display/CKB/Configure+PHP-FPM+with+User+Pools+for+EasyApache+4

**Comment by fevangelou** [comment]
I works like any other setup in PHP. As long as Apache does the fetching from PHP (even PHP5-FPM) you should have no issue.
