### ISSUE TITLE
Nginx error

### ISSUE THREAD

**Issue by lucasdelalibera** [engintron/engintron#1222]
Today, for no reason the sites started giving the following error
502 bad gateway nginx

Sometimes the websites of the server access others generates this error

I updated the engintron but the problem continued

I had to disable engintron to solve the problem

My server is CENTOS 6.10 [server] CPANEL v86.0.24

**Comment by fevangelou** [comment]
A 502 error means Apache is taking too long to respond. This can happen for many reasons. E.g. if your server is a VM/VPS, there's a chance the host server's resources have changed. Or some Apache config changed (e.g. bad .htaccess rules) causing redirect loops or other delays.

**Comment by inventivo** [comment]
@lucasdelalibera Did you find out what the problem was? Lately I have this on various servers and have to restart PHP FPM in order to make sites accessible again. Error is "Bad gateway nginx"

**Comment by inventivo** [comment]
@fevangelou 

Errors in the error log: 

wrong ident 55459 response for www.########.com, expect 35531
*294247 www.########.com could not be resolved
unexpected response for #########.com

**Comment by fevangelou** [comment]
Bump your PHP-FPM resources a bit. Rule of thumb is your max children at 50-75% of your actual CPUs, so for an 8-core CPU use 4-6 as max children, use 1s for process idle timeout and 2000 to 4000 for max requests. The cPanel defaults are pretty low.
