### ISSUE TITLE
How to uninstall apcu?

### ISSUE THREAD

**Issue by amirasap** [engintron/engintron#1223]
Hi,
I installed Engintron with apcu but whmcs is not working and i see following error:

Whoops\Exception\ErrorException: PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php72/root/usr/lib64/php/modules/apcu.so' (tried: /opt/cpanel/ea-php72/root/usr/lib64/php/modules/apcu.so (/opt/cpanel/ea-php72/root/usr/lib64/php/modules/apcu.so: cannot open shared object file: No such file or directory), /opt/cpanel/ea-php72/root/usr/lib64/php/modules//opt/cpanel/ea-php72/root/usr/lib64/php/modules/apcu.so.so (/opt/cpanel/ea-php72/root/usr/lib64/php/modules//opt/cpanel/ea-php72/root/usr/lib64/php/modules/apcu.so.so: cannot open shared object file: No such file or directory)) in Unknown:0

How can i solve issue or uninstall apcu?

**Comment by fevangelou** [comment]
Looks like the paths are wrong. Are you sure you didn't try to install APCu from cPanel module manager? Cause the one I build actually works :)

**Comment by amirasap** [comment]
The problem was from disable-fuvtions. i empty and it worked. but css caches are so annoying and i am getting many complains from developers. i know there is another topic about that but it is old and common_http.conf has different settings now. even i deleted css|js lines and still caching files.

**Comment by fevangelou** [comment]
There's a 1 min cache for static files. You can disable that globally or on a per site basis though the custom rules file. Read the docs and the comments in that file.
