### ISSUE TITLE
http/2

### ISSUE THREAD

**Issue by EvangelosBalafoutis** [engintron/engintron#1225]
With Engintron enable, http/2 is not operating.
With disable Engintron, http/2 seems is working.
From CL repliedthe issue is related to the openssl package, which engintron uses.
It's a base openssl package, and there is no new version of it for CentOS/RHEL/CloudLinux 6.

Apache uses ea-openssl package 1.1+ version which is newer and supports ALPN.

You may contact cPanel or Ngintron support to find a workaround to force nginx using another openssl libraries, for example, provided by ea-openssl package

How can I fix to have http/2 and Engintron enable?

**Comment by fevangelou** [comment]
CentOS 6 is old and as such does not have the necessary libs for http/2 to work in Nginx.

So either build Nginx on your own or (better) upgrade to CentOS 7.

**Comment by EvangelosBalafoutis** [comment]
Thank you so very much

 

Best Regards

Evangelos Balafoutis

--------------------------------
