### ISSUE TITLE
How to setup Engintron as a reverse proxy without server blocks?

### ISSUE THREAD

**Issue by iantrudell** [engintron/engintron#1226]
Hi,

I'm following [this guide](https://strapi.io/documentation/v3.x/deployment/nginx-proxy.html) to deploy Strapi using Nginx as a reverse proxy, but I'm having trouble getting it to work with Engintron's configuration and interaction with Apache.

It says to add this to /etc/nginx/conf.d/upstream.conf

```
# Strapi server
upstream strapi {
    server 127.0.0.1:1337;
}
```

And then to add this to /etc/nginx/sites-available/strapi.conf

```
server {
    # Listen HTTP
    listen 80;
    server_name example.com;

    # Redirect HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    # Listen HTTPS
    listen 443 ssl;
    server_name example.com;

    # SSL config
    ssl_certificate /path/to/your/certificate/file;
    ssl_certificate_key /path/to/your/certificate/key;

    # Static Root
    location / {
        root /var/www/html;
    }

    # Strapi API
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://strapi;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }

    # Strapi Dashboard
    location /dashboard {
        proxy_pass http://strapi/dashboard;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }
}
```

But I do not have that folder and I'm not sure what other configuration files to insert those blocks in instead.

I'm also not sure what path to give for the SSL certificates since I'm using cPanel and AutoSSL.

I'm already running other standard sites using PHP - this is the first API I'm running with Node.JS and Engintron.

Any assistance getting this to work with Engintron would be much appreciated!

**Comment by fevangelou** [comment]
That won't work. See Engintron's docs on how to proxy to a non-standard app in cPanel, e.g. a Node app: https://engintron.com/docs/#/pages/hosting-node-apps-on-cpanel

The solution is much simpler and Apache won't even be involved.

**Comment by iantrudell** [comment]
> That won't work. See Engintron's docs on how to proxy to a non-standard app in cPanel, e.g. a Node app: https://engintron.com/docs/#/pages/hosting-node-apps-on-cpanel
> 
> The solution is much simpler and Apache won't even be involved.

Thanks for the reply - so if I’m understanding, instead of upstream.conf I’d add something like this to custom_rules:

‘’’
if ($host = "strapi.mydomainname.com") {
    set $PROXY_SCHEME "http";
    set $PROXY_TO_PORT 1337;
}
‘’’

But then how would I go about the rewrite rules in Engintron? E.g. /api and /dashboard from the server blocks in the first post? The linked guide didn’t mention those. Thanks!

**Comment by fevangelou** [comment]
If you notice, the rewrites are symmetrical. E.g. /dashboard from the outside world maps to 127.0.0.1:1337/dashboard.

The config you mention is already done in Engintron. :)

**Comment by iantrudell** [comment]
Thanks again for the reply - I've tried adding this to custom_rules:

```
if ($host = "api.mydomain.com") {
    set $PROXY_SCHEME "https";
    set $PROXY_TO_PORT 1337;
}
```

However I am getting a 502 Bad Gateway with the following errors in the nginx log:

```
25264#25264: *9470743 SSL_do_handshake() failed (SSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol) while SSL handshaking to upstream, client: ::_, server: localhost, request: "POST / HTTP/1.1", upstream: "https://myip:1337/", host: "mydomain.com"
```

**Comment by fevangelou** [comment]
There's an SSL error connection to your app. Try using "http" instead and ensure the Node app is not enforcing any redirects to https.

**Comment by iantrudell** [comment]
Setting it to "http" seems to allow the app to load, but it does look like something is redirecting to "https."

Should I attempt to make sure nothing in the app redirects to https, and let the custom_rules set the PROXY_SCHEME to "https"? Or should I try and ensure everything is set to https both in the app and custom_rules?

I am using an out-of-the-box installation of [Strapi](https://strapi.io/documentation/v3.x/installation/cli.html)

**Comment by fevangelou** [comment]
I'm not really aware of how Strapi works, so I'll just consider this as any other Node app.

Check for any configs that may point to HTTPS redirection. Additionally, check if you must upload a separate certificate if you want the app to respond on port 1337 using HTTPS.

All this is really app specific. Just remember that the setup you do in custom_rules allows you to transform HTTPS requests on the outside to HTTP requests on the inside (app). That's good flexibility to have.

**Comment by fevangelou** [comment]
This might give some hints: https://github.com/strapi/strapi/issues/4884

The issue seems to be Strapi specific in regards to SSL.

**Comment by iantrudell** [comment]
Really appreciate your help with this fevangelou. After setting PROXY_SCHEME to "http" in the custom_rule snippet, reinstalling Strapi using the manual method instead of --quickstart, setting "enable SSL" to true during the installation, and rebuilding the Strapi app with the yarn build --clean option, it now seems to be working with cPanel's AutoSSL certificate.

Thanks again!

**Comment by fevangelou** [comment]
That's great 👍

**Comment by iantrudell** [comment]
Reopening this since I have another related question - I have the API application working using custom_rules on a subdomain api.mydomain.com with port 1337, and now I'm trying to get the frontend [Angular ](https://angular.io/) application up an running on the root domain mydomain.com.

The root folder of the cPanel is /home/account/public_html/mydomain but the app is building itself in /home/account/public_html/mydomain/approot/dist/app (index.html for Angular is there)

Normally I would create a server block with something like this to change the root:

```
http {
         ...
  server {
        listen       8080;
        server_name  localhost;
    location / {
            root  /home/account/public_html/mydomain/approot/dist/app;
            index  index.html index.htm;
        }
```

What would the equivalent be for that in Engintron using custom_rules? Thanks again!

**Comment by fevangelou** [comment]
Make /home/account/public_html/mydomain/approot/dist/app the root path for the domain in cPanel. This way the static files will always be served from there, from Apache and therefore Nginx.
