### ISSUE TITLE
Subpaths proxy pass

### ISSUE THREAD

**Issue by AryaRDI** [engintron/engintron#1227]
Hi

I was struggling with creating a custom rule for a reverse proxy on my WebSocket and so far it works but I'm wondering how can I solve this use case:

For example, I have different Websockets which are running like this: `127.0.0.1:3030` then I have `127.0.0.1:3030/connect` and another one `127.0.0.1:3030/api/foo/bar` etc
 
then How we can create a single rule for all the subpaths of `127.0.0.1:3030`?

I create something like this and it works for `127.0.0.1:3030`:

```
if ($SITE_URI ~* "example.com/nviu24vuig24fhg") {
    set $PROXY_DOMAIN_OR_IP "127.0.0.1";
    set $PROXY_TO_PORT 3030;
}
```

Now what to do for the `127.0.0.1:3030/connect` to be able to work like `example.com/nviu24vuig24fhg/connect`?

In nginx you can create something like this:

```
location ~ ^/nviu24vuig24fhg(.*)$ {
    proxy_pass http://127.0.0.1:3030$1;
    ...
}
```

**Comment by fevangelou** [comment]
Check this out: https://engintron.com/docs/#/pages/hosting-node-apps-on-cpanel

**Comment by AryaRDI** [comment]
> Check this out: https://engintron.com/docs/#/pages/hosting-node-apps-on-cpanel

Sorry, It didn't help much because it is a PHP application, and some of the services are running separately. The solution provides a solution for the whole domain name I want to achieve something like this:

```
location ~ ^/nviu24vuig24fhg(.*)$ {
    proxy_pass http://127.0.0.1:3030$1;
    ...
}
```

**Comment by fevangelou** [comment]
You can't use location blocks in Engintron's custom rules. Any proxying has to be symmetrical.

**Comment by AryaRDI** [comment]
> You can't use location blocks in Engintron's custom rules. Any proxying has to be symmetrical.

I could fix the issue by putting the config inside the http.conf, couldn't any way to achieve the same with the custom rules conf. If there is a way to convert that NginX format `location` conf to your custom rules, that would be nice to know

**Comment by fevangelou** [comment]
I'm afraid it's not possible to do that with custom rules.
