### ISSUE TITLE
removing host file after updating

### ISSUE THREAD

**Issue by j-nohra** [engintron/engintron#1228]
engintron is removing host file after upgrading.
host file was located in /etc/nginx/conf.d/ 

it's a proxy file and not a created site in cPanel.

how can we solve this?

**Comment by fevangelou** [comment]
Don't edit these files, they are auto-generated. Read the docs please.

**Comment by j-nohra** [comment]
Thank you @fevangelou the files are note being edited; we have added a new host file.

**Comment by fevangelou** [comment]
That won't work. Engintron works with specific files and as a proxy only, not a generic web server like Apache. You can't just add your own vhost.
