### ISSUE TITLE
Munin Nginx Requests

### ISSUE THREAD

**Issue by BomBom123** [engintron/engintron#123]
I'm having an issue where requests aren't showing on the nginx request graphs.
I left Engintron disabled for a while as i got the configs ready, unsure if disabling caused this issue.

![image](https://cloud.githubusercontent.com/assets/3690196/14327766/a3dca6a6-fc2b-11e5-9089-a51298608085.png)

**Comment by fevangelou** [comment]
Re-install via WHM and let me know.

**Comment by BomBom123** [comment]
Alrighty i have just done that.
I'll keep an eye on the graphs for a few days to see if they start working.

**Comment by fevangelou** [comment]
Great. When disabling Nginx, its integration with Munin does not change. What you see under requests seems normal. Since Engintron was disabled, Nginx switched to port 8080 so 0 requests there. Connections however could occur to the Nginx status page (I'm guessing) that's why you see the bottom graphs.

**Comment by BomBom123** [comment]
Still seems the top graphs are empty :/

**Comment by fevangelou** [comment]
BEFORE you switched Engintron off, did you notice if they worked just fine? Could be stupid Munin not regenerating its cache or something.

**Comment by BomBom123** [comment]
In a previous setup where i first installed Engintron and didn't turn it off, after leaving it running for a few days, the graphs did indeed work.

I can see other graphs generating and going along perfectly, just them.

**Comment by fevangelou** [comment]
Then it's probably Munin. I guess the best thing to do is ask cPanel support if they can force-regenerate the graphs. cPanel uses its own package for Munin so locations may be different compared to "stock" Munin you'd get from a yum repo.

**Comment by dcordovez** [comment]
Hello, same problem here in two servers.

I edit the file /usr/local/cpanel/3rdparty/share/munin/plugins/nginx_request 
and change the line:

my $URL = exists $ENV{'url'} ? $ENV{'url'} : "http://$fqdn/nginx_status";

For this:
my $URL = exists $ENV{'url'} ? $ENV{'url'} : "http://localhost/nginx_status";

And now the graphs for requests  is Ok.

**Comment by sercba** [comment]
Add this to **/etc/munin/plugin-conf.d/cpanel.conf**:

    [nginx*]
    env.url http://localhost/nginx_status

Then restart:
`# service munin-node restart`

**Comment by fevangelou** [comment]
@sercba You're right, I should have added this as well in the installer. I'll merge it for v1.7.0. Thanks.
