### ISSUE TITLE
Node/Python App Proxying Headers

### ISSUE THREAD

**Issue by bgabler** [engintron/engintron#1234]
Hi,

When setting up a proxy via engintron to an app https://engintron.com/docs/#/pages/hosting-node-apps-on-cpanel, is there an easy way to add headers? (ie: CORS headers)

I've tried in just about every possible spot I can think of, but no luck.

Thanks

**Comment by fevangelou** [comment]
Use the app itself to transmit any additional headers.

**Comment by bgabler** [comment]
> Use the app itself to transmit any additional headers.

That’s what I figured ;)

Thanks!
