### ISSUE TITLE
ngx http2_v2 module

### ISSUE THREAD

**Issue by mroth911** [engintron/engintron#1238]
I cant start Nginx once I install Engintron because I get a lot of errors. one major error I cant get past is this. 

nginx: [emerg] the "http2" parameter requires ngx_http_v2_module in /etc/nginx/conf.d/default_https.conf:14

 Can someone help me how to fix it?

**Comment by fevangelou** [comment]
a) What's your CentOS version
b) Did you have any other Nginx installation on your server before Engintron?

**Comment by mroth911** [comment]
No, I am running cloud Linux 7.8 .

**Comment by fevangelou** [comment]
What are the other errors?
