### ISSUE TITLE
1:1 cPanel NAT 

### ISSUE THREAD

**Issue by digitaltea** [engintron/engintron#1241]
Hey all,

Hoping you could help with this.  We're running a 1:1 NAT setup via cPanel and everything is fine when Engintron is disabled.  Once enabled, we get 404 errors.

We've modified the custom rules as follows:

set $PROXY_DOMAIN_OR_IP "<external_ip>";

What am I doing wrong? 👍 

TIA!

**Comment by fevangelou** [comment]
Use the internal IP.
