### ISSUE TITLE
Google Analytics issue?

### ISSUE THREAD

**Issue by Shahzadqayyum** [engintron/engintron#1243]
HI!
I am providing hosting to my clients. some clients claims that their google analytics stats are showing less traffic after migrating to my server?
Is this because of Nginx? or micro caching?
How can i Avoid such thing as there are more than 5 clients claiming same issue after migrating to my servers! Let me clear one thing here, there are 3 different servers and running same settings, engintron, php-fpm and EA profile you have provided?
Please advise what could be the main reason?

thanks

**Comment by fevangelou** [comment]
I can't possibly know what's going on in your server. You provide hosting services, you should be able to address that on your own.

Closing as off-topic.
