### ISSUE TITLE
HTTP to HTTPS - AutoSSL not working

### ISSUE THREAD

**Issue by faca5** [engintron/engintron#1244]
Hello.

When we try redirect all HTTP traffic (port 80) to HTTPS (port 443), AutoSSL cannot renew SSL certificates.
This is problem in AutoSSL. Do you have any suggestion how to exclude AutoSSL from redirect in nginx?

Example:
Exclude all request for url ".well-known" or something like that.

Thank you.

**Comment by fevangelou** [comment]
Nginx does not redirect from HTTP to HTTPS. Plus, AutoSSL will verify via HTTP first. Judging from your other post in https://github.com/engintron/engintron/issues/1232#issuecomment-712886736 you need to have a look at your redirects...
