### ISSUE TITLE
OpenCart v3.

### ISSUE THREAD

**Issue by faca5** [engintron/engintron#1245]
Hello.

We got problem with cache on OpenCart v3. OpenCart v3 use own session system.

We have turned off these to settings to make work correctly:
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $CACHE_BYPASS_FOR_STATIC 1;

It could be problem in custom session library and not in engintron.

Problem:
When 1st customer login and buy something next customer get personal data from 1st customer.

**Comment by fevangelou** [comment]
You can also disable the cache for that domain only.

**Comment by faca5** [comment]
Yes! This solution we have used.
