### ISSUE TITLE
Engintron proxy cache key doesn't account for scheme

### ISSUE THREAD

**Issue by godismyjudge95** [engintron/engintron#1246]
Encountered this when spinning up a new server.

### Steps to replicate:

1. Install engintron
2. Add a cpanel account
3. Create the index.html and .htaccess files
3. Add the following standard force https code to the .htaccess:
```
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteCond %{HTTPS} off
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>
```
4. Visit the http (non-ssl) version of the site - eg. http://domain.com - This will cache the redirect in the nginx cache
5. Visit the https (ssl) version of the site - eg. https://domain.com

### Result:
An infinite redirect loop from httpS://domain.com to httpS://domain.com

### Why this happens:
In /etc/nginx/proxy_params_dynamic there is a line:
```
proxy_cache_key                "$MOBILE$host$request_uri";
```
This causes nginx to properly cache the redirect from http://domain.com to httpS://domain.com
However, it does not account for the scheme of the original url.
Thus, when we visit httpS://domain.com it uses "domain.com" as the key to look up in the cache and it finds that it needs to redirect from httpS://domain.com to httpS://domain.com

### The Fix:
Change the line in /etc/nginx/proxy_params/dynamic to:
```
proxy_cache_key                "$MOBILE$scheme$request_method$host$request_uri";
```

This way the cache key accounts for both the scheme and the request method when checking the cache.

**Comment by fevangelou** [comment]
Apparently the removal of "$scheme" causes a lot of issues to such .htaccess redirects. I'll re-instate it.

$request_method is not really needed though. This is translated to either HEAD or GET and will cause double cache entries for essentially the same content response.

**Comment by fevangelou** [comment]
BTW, since I prefer to use cPanel's .htaccess redirects and seeing these redirects never had an issue with the removal of $scheme in proxy_cache_key, you might wish to consider these .htaccess redirect rules:
```
RewriteCond %{HTTPS} !=on [OR]
RewriteCond %{HTTP:X-Forwarded-Proto} =http
RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

**Comment by fevangelou** [comment]
Version 1.14.0 has been published already.

**Comment by godismyjudge95** [comment]
> BTW, since I prefer to use cPanel's .htaccess redirects and seeing these redirects never had an issue with the removal of $scheme in proxy_cache_key, you might wish to consider these .htaccess redirect rules:
> 
> ```
> RewriteCond %{HTTPS} !=on [OR]
> RewriteCond %{HTTP:X-Forwarded-Proto} =http
> RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
> ```

Ah did not know cpanel's redirects were set up that way.  We have been running into issues with clients using Wordpress plugins to force https and they use a set of rules that by default don't look for the x-forwarded-proto.

**Comment by godismyjudge95** [comment]
> Version 1.14.0 has been published already.

Great, thanks!

**Comment by JialuZhang** [comment]
@godismyjudge95 @fevangelou 

Having just
```
RewriteCond %{HTTPS} !=on [OR]
RewriteCond %{HTTP:X-Forwarded-Proto} =http
RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```
is a silent misconfiguration. Since "RewriteEngine" is by default set to off, it is a must to add "RewriteEngine on" in configuration file, if we want to enable the functionality of "RewriteCond" and "RewriteRule".

Here is the related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
