### ISSUE TITLE
Feature Request:  Option to Install Purge Module

### ISSUE THREAD

**Issue by godismyjudge95** [engintron/engintron#1247]
Would it be possible to offer an option of automatically installing the ngx_cache_purge module?
See:  https://github.com/FRiCKLE/ngx_cache_purge
Instructions for compiling into nginx:  https://linuxadmin.io/add-ngx_cache_purge-module-to-nginx/

This would allow a config block like the following:
```
location ~ /purge(/.*) {
    allow $PROXY_DOMAIN_OR_IP;
    deny all;
    proxy_cache_purge engintron_dynamic $MOBILE$scheme$host$1;
    proxy_cache_purge engintron_static $MOBILE$scheme$host$1;
}
```

Which would then allow one to clear the cache for a given url:  https://example.com/page/
by visiting:  https://example.com/purge/page/

This option would be very popular when having longer cache times (instead of the default micro-caches).

Thanks

**Comment by fevangelou** [comment]
It's best to use this method: https://bluegrid.io/edu/how-to-purge-the-nginx-cache/

The module you refer to cannot be built as a dynamic module for Nginx and as such, cannot be installed with the Nginx copy that comes from the official Nginx repos.

**Comment by godismyjudge95** [comment]
> It's best to use this method: https://bluegrid.io/edu/how-to-purge-the-nginx-cache/
> 
> The module you refer to cannot be built as a dynamic module for Nginx and as such, cannot be installed with the Nginx copy that comes from the official Nginx repos.

Yeah, the unfortunate part of that is that it appears to require a subscription to NGINX Plus.

**Comment by fevangelou** [comment]
Please do take a minute and read it.
