### ISSUE TITLE
Error After Update

### ISSUE THREAD

**Issue by hizkiace** [engintron/engintron#1248]
Hello Problem found after im doing engintron Update its show Error Code:
invalid value "http_429" 
When Starting nginx.
Anyone know how to fix it?

**Comment by fevangelou** [comment]
Weird...

Edit this line https://github.com/engintron/engintron/blob/master/nginx/proxy_params_dynamic#L81 and remove `http_429`. Then run `nginx -t` in the terminal and if it's all good, restart Engintron with `/engintron.sh purgecache` (will purge any caches and restart the related services).

**Comment by hizkiace** [comment]
working. Thanks

**Comment by fevangelou** [comment]
Great.
