### ISSUE TITLE
Is it possible to add nginx rate limiting and th limit connection module when using engintron?

### ISSUE THREAD

**Issue by WebSavvyDude** [engintron/engintron#1249]
Hi

I want to add rate limiting (https://www.nginx.com/blog/rate-limiting-nginx/) while i am using Engintron with Cpanel.

Anyone have any ideas how to achieve this?  Which files to use and where to put it.

I want to add something like this

```
limit_req_zone $binary_remote_addr zone=ip:10m rate=5r/s;

server {
    listen 80;
    location / {
        limit_req zone=ip burst=12 delay=8;
        proxy_pass http://website;
    }
}
```

I also want to add the limit connection module (http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html)

```
limit_conn_zone $binary_remote_addr zone=perip:10m;

server {
    ...
    limit_conn perip 10;
}
```

Please let me know the best place to put these.

Thanks

**Comment by fevangelou** [comment]
Both are core Nginx module so any rules you want added should work just fine if configured inside your "Custom Rules".
