### ISSUE TITLE
as I shot a website to use nginx

### ISSUE THREAD

**Issue by weltonwe** [engintron/engintron#125]
As I shot a website to use nginx I have a website that enables engintron the 502 Bad Gateway ha more sites working standard need only turn to the site that the error occurs

**Comment by fevangelou** [comment]
Ask a friend who speaks English to write your question for you and assist you with the responses I'll provide you.

**Comment by weltonwe** [comment]
I have this error in the DNS of a site
ns1.redelin.com.   [] (NO GLUE)   [TTL=86400] 
ns2.redelin.com.   [] (NO GLUE)   [TTL=86400] 
more without it enabled nginx it works
	Your www.autopostolajedaense.com.br A record is:
www.autopostolajedaense.com.br -> autopostolajedaense.com.br -> [ 95.130.9.249  ] 
I wanted to know how I turn nginx only for this site -> autopostolajedaense.com.br

**Comment by fevangelou** [comment]
You can't. Nginx must be enabled for your entire server as it binds to port 80.
