### ISSUE TITLE
Offload HTTPS traffic to Nginx only

### ISSUE THREAD

**Issue by Shahzadqayyum** [engintron/engintron#1251]
Also in /etc/nginx/common_https.conf added the ssl-offloaded header to the location backend block:

location @backend {
    include proxy_params_common;
    # === MICRO CACHING ===
    # Comment the following line to disable 1 second micro-caching for dynamic HTML content
    include proxy_params_dynamic;
    proxy_set_header Ssl-Offloaded "1"; # Added custom "ssl-offloaded" header for Apache
    proxy_set_header X-Forwarded-Port 443;
}

I cant see location@backend in /etc/nginx/common_https.conf?
though i can see this block in /etc/nginx/common_http.conf
?
is this just a typo?
i am facing huge wait times in ssl redirect reuests?
help needed!
thanks

**Comment by darnellkeithj** [comment]
It was moved to common_http.conf so add it there.
 However, this also gives me a redirect errors so I gave up on it.

**Comment by Shahzadqayyum** [comment]
have you tried 
this in htaccess?
RewriteCond %{HTTP:X-Forwarded-Port} !=443
RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]

instead of this?
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

**Comment by darnellkeithj** [comment]
I did but still got the "too many redirect errors". I'll play with it again this weekend and see if I can make some progress on it. It may have sometime to do with cloudflare even though I have it set up correctly.

**Comment by darnellkeithj** [comment]
Hello, Guide which is posted on engintron.com is outdated and breaks Force SSL Functionality in Cpanel. So Here is my Solution:

Step 1. Edit /etc/apache2/conf.d/includes/pre_virtualhost_global.conf and append:
SetEnvIf X-Forwarded-Proto "https" HTTPS=on

Step 2. Run
cp /var/cpanel/templates/apache2_4/vhost.default /var/cpanel/templates/apache2_4/vhost.local
sed -i 's/RewriteCond %{HTTPS} !=on/RewriteCond %{HTTP:X-Forwarded-Proto} !https/g' /var/cpanel/templates/apache2_4/vhost.local
/scripts/rebuildhttpdconf

Step 3. Edit /etc/nginx/proxy_params_common to update proxy_pass:
proxy_pass http://$PROXY_DOMAIN_OR_IP:8080;

Step 4. restart both apache & nginx
apachectl restart systemctl restart nginx

https://sysadmin.lol/engintron-ssl-offload/

This seems to work.

**Comment by fevangelou** [comment]
Also, do update to the latest Engintron version. It may solve your redirects issue (unless you have crappy .htaccess rules).

**Comment by Shahzadqayyum** [comment]
> Hello, Guide which is posted on engintron.com is outdated and breaks Force SSL Functionality in Cpanel. So Here is my Solution:
> 
> Step 1. Edit /etc/apache2/conf.d/includes/pre_virtualhost_global.conf and append:
> SetEnvIf X-Forwarded-Proto "https" HTTPS=on
> 
> Step 2. Run
> cp /var/cpanel/templates/apache2_4/vhost.default /var/cpanel/templates/apache2_4/vhost.local
> sed -i 's/RewriteCond %{HTTPS} !=on/RewriteCond %{HTTP:X-Forwarded-Proto} !https/g' /var/cpanel/templates/apache2_4/vhost.local
> /scripts/rebuildhttpdconf
> 
> Step 3. Edit /etc/nginx/proxy_params_common to update proxy_pass:
> proxy_pass http://$PROXY_DOMAIN_OR_IP:8080;
> 
> Step 4. restart both apache & nginx
> apachectl restart systemctl restart nginx
> 
> https://sysadmin.lol/engintron-ssl-offload/
> 
> This seems to work in combination with all the other steps.

well thanks darnellkeithj but i see instead of a better https speed? I am getting worst ttfb now :(

any way to restore default without crashing my live server?

i got this reply from my host!

### It seems moreso that the discrepancy lies with HTTP vs HTTPS and that the server is very capable of a low TTFB.

$ curl -o /dev/null -w "Connect: %{time_connect} TTFB: %{time_starttransfer} Total time: %{time_total} \n" xyz123.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   234  100   234    0     0   1560      0 --:--:-- --:--:-- --:--:--  1549
Connect: 0.074852 TTFB: 0.150323 Total time: 0.150850 
jeff@jeff-workstation:~$ curl -o /dev/null -w "Connect: %{time_connect} TTFB: %{time_starttransfer} Total time: %{time_total} \n" https://xyz123.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 56850    0 56850    0     0  52638      0 --:--:--  0:00:01 --:--:-- 52638
Connect: 0.073696 TTFB: 1.007522 Total time: 1.080184

**Comment by darnellkeithj** [comment]
I've had nothing but great results with engintron and the offloading. With good caching and switching out out php-fpm for mod_lsapi, my site loads in about 1 second. It wont crash your server, just undo the steps.

**Comment by JialuZhang** [comment]
@Shahzadqayyum 

In your post 
```
have you tried
this in htaccess?
RewriteCond %{HTTP:X-Forwarded-Port} !=443
RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]

instead of this?
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

The first one contains silent misconfiguration. Since "RewriteEngine" in that is by default set to off, it is a must to add "RewriteEngine on" in the configuration file, if we want to enable the functionality of "RewriteCond" and "RewriteRule".

Here is the related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
