### ISSUE TITLE
Adding user agents to dynamic | Googlebot | Google ads bot.

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1252]
Hello, i have a little issue here...
i try to add a user agent of Google bot, the problem is the Googlebot API is shared string to desktop and mobile...
sometimes the scan very bad and effective on the mobile... have a choice to activate the user agent properly? maybe inside
the http_common?

this is the user agents from google:
https://support.google.com/webmasters/answer/1061943

this what i try to do (i add user agents in the dynamic config but is not work so well... on desktop and mobile, and sometimes the scan take a lot of time, this because he searching the right user agent cache

what i did ( this not good ):

# Allow separate cache entries for mobile devices (smartphones & tables)
set $MOBILE "";
if ($http_user_agent ~* "(iPhone|iPod|iPad|Android|Mobile|Tablet|Googlebot|AdsBot-Google|AdsBot-Google-Mobile)") {
    set $MOBILE "m_";
}

Please help me :)

**Comment by fevangelou** [comment]
I honestly don't understand WHAT you are trying to achieve here...

**Comment by locksmithunit** [comment]
is very old, is from last year. I am sorry,
I was learning the software.

I will delete it. @fevangelou
