### ISSUE TITLE
Question about cache

### ISSUE THREAD

**Issue by PantelisK** [engintron/engintron#1253]
Hello,

a client of ours reported that his changes don't apply unless he restarts his router/browser or logs in on his website.
For example a change in his contact form doesn't show. Here is the headers we get in return:

curl -lI https://www.$$$$$$.gr/contact-us/
HTTP/2 200
server: nginx
date: Tue, 10 Nov 2020 12:27:01 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
link: <https://www.$$$$$$.gr/wp-json/>; rel="https://api.w.org/", <https://www.$$$$$$.gr/wp-json/wp/v2/pages/106>; rel="alternate"; type="application/json", <https://www.$$$$$$.gr/?p=106>; rel=shortlink
set-cookie: woocommerce_current_currency=EUR; expires=Sun, 15-Nov-2020 12:52:12 GMT; Max-Age=604800; path=/
cache-control: max-age=172800
expires: Tue, 10 Nov 2020 12:52:12 GMT
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-nginx-upstream-cache-status: HIT
x-server-powered-by: Engintron

This contact page contains simple HTML code and a lot of <script type="text/javascript" > in the end. Not sure if this makes a difference.

My question is why the expires is set to more than 1 minute and in some cases even 1 hour.
I see the set-cookie variable seems to be setting the expires to such a high number but my programming knowledge is limited so pardon my ignorance.

Our client reports that there is no caching plugin on the website. Also we haven't changed anything on our setup apart from the Cloudflare IP and the dedicated IP on the custom rules file.

Thank you for your time.

**Comment by fevangelou** [comment]
The problem is this: `cache-control: max-age=172800`

However this is not set by Engintron, most likely by some caching plugin or some .htaccess rule.

**Comment by PantelisK** [comment]
Thank you for your time and your explanation. Very much appreciated.
