### ISSUE TITLE
Current Connections on port 80 / 443 show wrong number

### ISSUE THREAD

**Issue by konstantinosbotonakis** [engintron/engintron#1254]
The script should be:

netstat -ant | grep :443 | awk '{print $6}' | sort | uniq -c | sort -n

so it shows all connections by their state.
The above will show for example:

      2 LISTEN
      6 CLOSE_WAIT
    284 TIME_WAIT
    380 ESTABLISHED

But currently it shows:

672 which is confusing and wrong as TIME_WAIT connections are closed connections that wait 60" for delayed packets.

**Comment by fevangelou** [comment]
Thank you Konstantinos 👍 .

I will merge this in the next version along with a new table that displays total traffic as well.
