### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by faca5** [engintron/engintron#1256]
Hello.

We have problem with engintron (nginx) and OpenCart v3, Magento 2.

For unknown reason customer A get order data from customer B.
Engintron set wrong session for customers.

In OpenCart v3 we have solved with this settings:
set $CACHE_BYPASS_FOR_DYNAMIC 1;
set $CACHE_BYPASS_FOR_STATIC 1;

OpenCart v3 has own session library.

Today we got similar problem with Magento 2. On OpenCart v1 and v2 we haven't detected this problem. This two version use PHP SESSION library.

**Comment by fevangelou** [comment]
Do the same for any site that does not play nice with micro-caching.

**Comment by faca5** [comment]
Hello.

I don't know. We haven't detected this problem on WordPress.

Problem has been detected on ecommerce with GDPR is not very nice to have that kind of problem.

**Comment by fevangelou** [comment]
I didn't say there's an issue with WordPress. I said switch off micro-caching for any site that has issues with it. This has always been the case. You can't enforce caching for something that should not be cached. GDPR is irrelevant.

**Comment by faca5** [comment]
Cache has been turned off only for list of domain name.

**Comment by faca5** [comment]
https://github.com/opencart/opencart/issues/7295

**Comment by faca5** [comment]
Today it appear on OpenCart v1 which use PHP sessions.

**Comment by faca5** [comment]
Any idea how to fix it for all users?

**Comment by fevangelou** [comment]
As mentioned multiple times already, disable micro-caching.
