### ISSUE TITLE
on whm the message "restart server after update" is stuck

### ISSUE THREAD

**Issue by sibony88** [engintron/engintron#1257]
hi, 
the "You must reboot the server to apply software updates." message is always on top only in the engintron menu item
i have two vps servers and it is in both of them

**Comment by fevangelou** [comment]
What cPanel and/or Engintron version are you using?

**Comment by sibony88** [comment]
latest version of them both of them
and two time gracefull restart

‫בתאריך יום ג׳, 24 בנוב׳ 2020 ב-17:30 מאת ‪Fotis Evangelou‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by fevangelou** [comment]
Probably cached (as a message) by cPanel.

**Comment by sibony88** [comment]
Ok, thanks.
now the message is gone

בתאריך יום ו׳, 27 בנוב׳ 2020, 15:04, מאת Fotis Evangelou ‏<
notifications@github.com>:

**Comment by fevangelou** [comment]
Cool :)
