### ISSUE TITLE
Download index.php (0 bytes)

### ISSUE THREAD

**Issue by zstergios** [engintron/engintron#1262]
Randomly browser download index.php on desktop only. On Mobile works OK.
So I guess it's engintron related.

A visitor noted that had issue when he requested my-domain.gr and not when requested https://my-domain.gr (domain has http to https redirect already)

Issue started after upgrade to latest version.

**Comment by fevangelou** [comment]
This actually indicates a bad response from Apache/PHP-FPM. Purge Nginx's caches to restart all related services and cleanup and cached responses in Nginx.
