### ISSUE TITLE
Bad Gateway 502

### ISSUE THREAD

**Issue by inventivo** [engintron/engintron#1263]
Sites go down frequently with a **Bad gateway 502 Error** on various WHM managed Servers.
This started within the last three weeks.

**Errors in the error log:**
wrong ident 55459 response for www.########.com, expect 35531
*294247 www.########.com could not be resolved
unexpected response for #########.com

**Software (latest versions):**
CENTOS 7.9 [server3] v92.0.3
Engintron v1.14.0, Build 20201028, (Nginx version: 1.18.0)

Now have disabled engintron and it seems not to occur.

**Comment by fevangelou** [comment]
Bump your PHP-FPM resources a bit. Rule of thumb is your max children at 50-75% of your actual CPUs, so for an 8-core CPU use 4-6 as max children, use 1s for process idle timeout and 2000 to 4000 for max requests. The cPanel defaults are pretty low.

And please don't cross-post.

**Comment by inventivo** [comment]
Jepp, sorry for cross-posting. I will try the values given on one server for the first, thank you!

**Comment by fevangelou** [comment]
Most likely yes. It may be related to other limits as well, e.g. Apache connections. It depends.
