### ISSUE TITLE
Help with some custom rules

### ISSUE THREAD

**Issue by WebSavvyDude** [engintron/engintron#1264]
I have some rules i need to set in the default_https file but they keep getting put back to default.  My understanding is any rules need to put in the "custom rules" file.

Specifically i need to add the following location block to one of my domains:

`location /wss/ {
    proxy_pass http://127.0.0.1:8081;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 86400;
}`

How would i go about this if location blocks are not allowed in "if" statements? or are they allowed?  Do I need to include the following part at the beginning:

`listen [::]:443 ssl http2;
    server_name mydomain.com`

Would appreciate if anyone can help with this.   Please provide me what i need to put at the bottom of my custom rules file.

**Comment by fevangelou** [comment]
This should work at least for correctly proxying to a different port:
```
if ($SITE_URI ~* "^/wss/") {
	set $PROXY_SCHEME "http";
	set $PROXY_TO_PORT 8081;
}
```

To raise "proxy_read_timeout" though you need to adjust your proxy_params_common file.

**Comment by WebSavvyDude** [comment]
Thanks for the reply @fevangelou

However, adding that to the custom rules doesn't work. 

Adding it to the default_https file still works though but it doesn't stick.

Is there something i could be missing?

Sorry i realize this is probably heading out of the scope of this plugin but hopefully you can help.

**Comment by WebSavvyDude** [comment]
Thanks for the reply @fevangelou

However, adding that to the custom rules doesn't work.

Adding my original location block to the default_https file still works though but it doesn't stick.

Is there something i could be missing?

Sorry i realize this is probably heading out of the scope of this plugin but hopefully you can help.

**Comment by fevangelou** [comment]
Why doesn't it work? Did you check with a private window or curl to verify?

**Comment by WebSavvyDude** [comment]
@fevangelou

I am not quite sure why it doesn't work, it just doesn't.   I launched the URL with the APP installed in my browser and it gave an error.  (The applications error message was  "websocket is closed")

As soon as i put the location block in the default_https file it worked fine.

Looks like i am still missing something or the code to be added into the custom files needs some tweaks.
