### ISSUE TITLE
Feature SameSite

### ISSUE THREAD

**Issue by zstergios** [engintron/engintron#1266]
https://www.chromium.org/updates/same-site

SameSite feature starts affecting our websites.

I suggest to include some code to engintron configuration.

For example
If is HTTPS + SECURE COOKIE AND SAMESITE is missing then add SameSite=None; 
If you don't want to add it as feature, you can write us here the solution to added it as custom rule.

Joomla uses custom framework (as you very well know @fevangelou )
https://issues.joomla.org/tracker/joomla-cms/25414

I managed to set SameSite globally for any cookies for PHP < 7.3 just using a custom plugin, but I can't find solution how to do that on PHP 7.3 >=

All platforms I guess, will not release a solution ASAP.

**Comment by fevangelou** [comment]
This is a better approach https://stackoverflow.com/questions/39750906/php-setcookie-samesite-strict/51128675#51128675 and entirely controlled by the app/CMS.
