### ISSUE TITLE
Suspicious process running under user nginx

### ISSUE THREAD

**Issue by VIPKaiser** [engintron/engintron#1267]
Running the latest version. Is this normal? I seem to be getting excessive resource usage as well running over 3600 seconds...

Files open by the process (if any):

/dev/null
/dev/null
/var/log/nginx/error.log
/var/log/nginx/access.log
/var/log/nginx/error.log
/var/cache/nginx/engintron_static/5/4e/770701bb1d6489b30bee7cadfb6864e5
/var/cache/nginx/engintron_static/e/2b/7f21495c13c1bb4b8d6718d527f192be
anon_inode:[eventpoll]
anon_inode:[eventfd]
anon_inode:[eventfd]
/var/cache/nginx/engintron_static/6/bb/f1df4288f3e23c64abf077013ebfcbb6
/var/cache/nginx/engintron_static/d/91/dc89e1528d663fd8ffc428a76ca2591d
/var/cache/nginx/engintron_static/e/2e/8befbbb48bf1bf25389fdc370df342ee
/var/cache/nginx/engintron_static/e/94/1eb7f2168a7217be8c2bd4974a5a594e
/var/cache/nginx/engintron_static/1/e9/93a1b8b7221dd5345ea54d013e3a9e91
/var/cache/nginx/engintron_static/5/51/b07986f5bf3f85e9dc90012da11d1515
/var/cache/nginx/engintron_static/2/c7/91e36d03118a930087fc38b9dd74cc72
/var/cache/nginx/engintron_static/4/05/86b202b5dfc910b982bbd15cbfa58054
/var/cache/nginx/engintron_static/2/b5/236429e7e1716f2cd274bf6345916b52
/var/cache/nginx/engintron_static/c/51/b5c17663e49720e504fb14ef645f851c
/var/cache/nginx/engintron_static/e/2f/e00bd96e74863de86ea39754d78b62fe
/var/cache/nginx/engintron_static/d/5e/73f2da9a91ad9c880ec001925daac5ed
/var/cache/nginx/engintron_static/c/86/bfbaea2782cfb9a9814a88da40ac086c
/var/cache/nginx/engintron_static/e/49/2202b24a8572c426d062d20648e5649e
/var/cache/nginx/engintron_static/7/d0/aa546466af722af3c4281541484c7d07
/var/cache/nginx/engintron_static/1/55/0d56dc267fc0e084e9dda90e8765c551
/var/cache/nginx/engintron_static/e/29/edfd086464f4d4dc85a471f8bfac629e
/var/cache/nginx/engintron_static/c/6e/8fdd28a59d1cbb087d4ccbc1efd4e6ec
/var/cache/nginx/engintron_static/2/9d/fc82e216c45689dad8b4e142d7b929d2
/var/cache/nginx/engintron_static/f/16/8543bf4e6d358b810751ccbc2ba0516f
/var/cache/nginx/engintron_static/7/57/db9f35e8c356f7eb83dd5ce136f3a577
/var/cache/nginx/engintron_static/7/ca/43ed18598f661f6500109061bc8fbca7
/var/cache/nginx/engintron_static/8/a9/4d4f8e211ef032f3b53957fb2773fa98

Memory maps by the process (if any):

562357de0000-562357f02000 r-xp 00000000 09:02 72618214                   /usr/sbin/nginx
562358101000-562358103000 r--p 00121000 09:02 72618214                   /usr/sbin/nginx
562358103000-562358124000 rw-p 00123000 09:02 72618214                   /usr/sbin/nginx
562358124000-562358143000 rw-p 00000000 00:00 0
562358201000-562358b2a000 rw-p 00000000 00:00 0                          [heap]
562358b2a000-5623590ab000 rw-p 00000000 00:00 0                          [heap]
7fcefa187000-7fcefbc07000 rw-p 00000000 00:00 0
7fcefbc07000-7fcefee07000 rw-s 00000000 00:04 18908040                   /dev/zero (deleted)
7fcefee07000-7fcf1ee07000 rw-s 00000000 00:04 18908039                   /dev/zero (deleted)
7fcf1ee07000-7fcf3ee07000 rw-s 00000000 00:04 18908038                   /dev/zero (deleted)
7fcf3ee07000-7fcf3ee2b000 r-xp 00000000 09:02 72616072                   /usr/lib64/libselinux.so.1
7fcf3ee2b000-7fcf3f02a000 ---p 00024000 09:02 72616072                   /usr/lib64/libselinux.so.1
7fcf3f02a000-7fcf3f02b000 r--p 00023000 09:02 72616072                   /usr/lib64/libselinux.so.1
7fcf3f02b000-7fcf3f02c000 rw-p 00024000 09:02 72616072                   /usr/lib64/libselinux.so.1
7fcf3f02c000-7fcf3f02e000 rw-p 00000000 00:00 0
7fcf3f02e000-7fcf3f044000 r-xp 00000000 09:02 72616172                   /usr/lib64/libresolv-2.17.so
7fcf3f044000-7fcf3f244000 ---p 00016000 09:02 72616172                   /usr/lib64/libresolv-2.17.so
7fcf3f244000-7fcf3f245000 r--p 00016000 09:02 72616172                   /usr/lib64/libresolv-2.17.so
7fcf3f245000-7fcf3f246000 rw-p 00017000 09:02 72616172                   /usr/lib64/libresolv-2.17.so
7fcf3f246000-7fcf3f248000 rw-p 00000000 00:00 0
7fcf3f248000-7fcf3f24b000 r-xp 00000000 09:02 72615811                   /usr/lib64/libkeyutils.so.1.5
7fcf3f24b000-7fcf3f44a000 ---p 00003000 09:02 72615811                   /usr/lib64/libkeyutils.so.1.5
7fcf3f44a000-7fcf3f44b000 r--p 00002000 09:02 72615811                   /usr/lib64/libkeyutils.so.1.5
7fcf3f44b000-7fcf3f44c000 rw-p 00003000 09:02 72615811                   /usr/lib64/libkeyutils.so.1.5
7fcf3f44c000-7fcf3f45a000 r-xp 00000000 09:02 72615987                   /usr/lib64/libkrb5support.so.0.1
7fcf3f45a000-7fcf3f65a000 ---p 0000e000 09:02 72615987                   /usr/lib64/libkrb5support.so.0.1
7fcf3f65a000-7fcf3f65b000 r--p 0000e000 09:02 72615987                   /usr/lib64/libkrb5support.so.0.1
7fcf3f65b000-7fcf3f65c000 rw-p 0000f000 09:02 72615987                   /usr/lib64/libkrb5support.so.0.1
7fcf3f65c000-7fcf3f68d000 r-xp 00000000 09:02 72615837                   /usr/lib64/libk5crypto.so.3.1
7fcf3f68d000-7fcf3f88c000 ---p 00031000 09:02 72615837                   /usr/lib64/libk5crypto.so.3.1
7fcf3f88c000-7fcf3f88e000 r--p 00030000 09:02 72615837                   /usr/lib64/libk5crypto.so.3.1
7fcf3f88e000-7fcf3f88f000 rw-p 00032000 09:02 72615837                   /usr/lib64/libk5crypto.so.3.1
7fcf3f88f000-7fcf3f892000 r-xp 00000000 09:02 72615816                   /usr/lib64/libcom_err.so.2.1
7fcf3f892000-7fcf3fa91000 ---p 00003000 09:02 72615816                   /usr/lib64/libcom_err.so.2.1
7fcf3fa91000-7fcf3fa92000 r--p 00002000 09:02 72615816                   /usr/lib64/libcom_err.so.2.1
7fcf3fa92000-7fcf3fa93000 rw-p 00003000 09:02 72615816                   /usr/lib64/libcom_err.so.2.1
7fcf3fa93000-7fcf3fb6c000 r-xp 00000000 09:02 72615895                   /usr/lib64/libkrb5.so.3.3
7fcf3fb6c000-7fcf3fd6b000 ---p 000d9000 09:02 72615895                   /usr/lib64/libkrb5.so.3.3
7fcf3fd6b000-7fcf3fd79000 r--p 000d8000 09:02 72615895                   /usr/lib64/libkrb5.so.3.3
7fcf3fd79000-7fcf3fd7c000 rw-p 000e6000 09:02 72615895                   /usr/lib64/libkrb5.so.3.3
7fcf3fd7c000-7fcf3fdc6000 r-xp 00000000 09:02 72616103                   /usr/lib64/libgssapi_krb5.so.2.2
7fcf3fdc6000-7fcf3ffc6000 ---p 0004a000 09:02 72616103                   /usr/lib64/libgssapi_krb5.so.2.2
7fcf3ffc6000-7fcf3ffc7000 r--p 0004a000 09:02 72616103                   /usr/lib64/libgssapi_krb5.so.2.2
7fcf3ffc7000-7fcf3ffc9000 rw-p 0004b000 09:02 72616103                   /usr/lib64/libgssapi_krb5.so.2.2
7fcf3ffc9000-7fcf3ffcb000 r-xp 00000000 09:02 72614614                   /usr/lib64/libfreebl3.so
7fcf3ffcb000-7fcf401ca000 ---p 00002000 09:02 72614614                   /usr/lib64/libfreebl3.so
7fcf401ca000-7fcf401cb000 r--p 00001000 09:02 72614614                   /usr/lib64/libfreebl3.so
7fcf401cb000-7fcf401cc000 rw-p 00002000 09:02 72614614                   /usr/lib64/libfreebl3.so
7fcf401cc000-7fcf40390000 r-xp 00000000 09:02 72615965                   /usr/lib64/libc-2.17.so
7fcf40390000-7fcf4058f000 ---p 001c4000 09:02 72615965                   /usr/lib64/libc-2.17.so
7fcf4058f000-7fcf40593000 r--p 001c3000 09:02 72615965                   /usr/lib64/libc-2.17.so
7fcf40593000-7fcf40595000 rw-p 001c7000 09:02 72615965                   /usr/lib64/libc-2.17.so
7fcf40595000-7fcf4059a000 rw-p 00000000 00:00 0
7fcf4059a000-7fcf405af000 r-xp 00000000 09:02 72615949                   /usr/lib64/libz.so.1.2.7
7fcf405af000-7fcf407ae000 ---p 00015000 09:02 72615949                   /usr/lib64/libz.so.1.2.7
7fcf407ae000-7fcf407af000 r--p 00014000 09:02 72615949                   /usr/lib64/libz.so.1.2.7
7fcf407af000-7fcf407b0000 rw-p 00015000 09:02 72615949                   /usr/lib64/libz.so.1.2.7
7fcf407b0000-7fcf409e6000 r-xp 00000000 09:02 72615815                   /usr/lib64/libcrypto.so.1.0.2k
7fcf409e6000-7fcf40be6000 ---p 00236000 09:02 72615815                   /usr/lib64/libcrypto.so.1.0.2k
7fcf40be6000-7fcf40c02000 r--p 00236000 09:02 72615815                   /usr/lib64/libcrypto.so.1.0.2k
7fcf40c02000-7fcf40c0f000 rw-p 00252000 09:02 72615815                   /usr/lib64/libcrypto.so.1.0.2k
7fcf40c0f000-7fcf40c13000 rw-p 00000000 00:00 0
7fcf40c13000-7fcf40c7a000 r-xp 00000000 09:02 72616075                   /usr/lib64/libssl.so.1.0.2k
7fcf40c7a000-7fcf40e7a000 ---p 00067000 09:02 72616075                   /usr/lib64/libssl.so.1.0.2k
7fcf40e7a000-7fcf40e7e000 r--p 00067000 09:02 72616075                   /usr/lib64/libssl.so.1.0.2k
7fcf40e7e000-7fcf40e85000 rw-p 0006b000 09:02 72616075                   /usr/lib64/libssl.so.1.0.2k
7fcf40e85000-7fcf40ee5000 r-xp 00000000 09:02 72616092                   /usr/lib64/libpcre.so.1.2.0
7fcf40ee5000-7fcf410e5000 ---p 00060000 09:02 72616092                   /usr/lib64/libpcre.so.1.2.0
7fcf410e5000-7fcf410e6000 r--p 00060000 09:02 72616092                   /usr/lib64/libpcre.so.1.2.0
7fcf410e6000-7fcf410e7000 rw-p 00061000 09:02 72616092                   /usr/lib64/libpcre.so.1.2.0
7fcf410e7000-7fcf410ef000 r-xp 00000000 09:02 72615892                   /usr/lib64/libcrypt-2.17.so
7fcf410ef000-7fcf412ee000 ---p 00008000 09:02 72615892                   /usr/lib64/libcrypt-2.17.so
7fcf412ee000-7fcf412ef000 r--p 00007000 09:02 72615892                   /usr/lib64/libcrypt-2.17.so
7fcf412ef000-7fcf412f0000 rw-p 00008000 09:02 72615892                   /usr/lib64/libcrypt-2.17.so
7fcf412f0000-7fcf4131e000 rw-p 00000000 00:00 0
7fcf4131e000-7fcf41335000 r-xp 00000000 09:02 72616052                   /usr/lib64/libpthread-2.17.so
7fcf41335000-7fcf41534000 ---p 00017000 09:02 72616052                   /usr/lib64/libpthread-2.17.so
7fcf41534000-7fcf41535000 r--p 00016000 09:02 72616052                   /usr/lib64/libpthread-2.17.so
7fcf41535000-7fcf41536000 rw-p 00017000 09:02 72616052                   /usr/lib64/libpthread-2.17.so
7fcf41536000-7fcf4153a000 rw-p 00000000 00:00 0
7fcf4153a000-7fcf4153c000 r-xp 00000000 09:02 72615917                   /usr/lib64/libdl-2.17.so
7fcf4153c000-7fcf4173c000 ---p 00002000 09:02 72615917                   /usr/lib64/libdl-2.17.so
7fcf4173c000-7fcf4173d000 r--p 00002000 09:02 72615917                   /usr/lib64/libdl-2.17.so
7fcf4173d000-7fcf4173e000 rw-p 00003000 09:02 72615917                   /usr/lib64/libdl-2.17.so
7fcf4173e000-7fcf41760000 r-xp 00000000 09:02 72615469                   /usr/lib64/ld-2.17.so
7fcf418de000-7fcf41913000 r--s 00000000 09:02 41158488                   /var/db/nscd/group
7fcf41913000-7fcf41948000 r--s 00000000 09:02 41158485                   /var/db/nscd/passwd
7fcf41948000-7fcf41951000 rw-p 00000000 00:00 0
7fcf4195c000-7fcf4195d000 rw-s 00000000 00:0b 18902701                   /[aio] (deleted)
7fcf4195d000-7fcf4195e000 rw-s 00000000 00:04 18908043                   /dev/zero (deleted)
7fcf4195e000-7fcf4195f000 rw-p 00000000 00:00 0
7fcf4195f000-7fcf41960000 r--p 00021000 09:02 72615469                   /usr/lib64/ld-2.17.so
7fcf41960000-7fcf41961000 rw-p 00022000 09:02 72615469                   /usr/lib64/ld-2.17.so
7fcf41961000-7fcf41962000 rw-p 00000000 00:00 0
7fff456b2000-7fff456d3000 rw-p 00000000 00:00 0                          [stack]
7fff456db000-7fff456dd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by fevangelou** [comment]
The processes are correct. Whatever limits you impose or resources you check is another story...
