### ISSUE TITLE
Change cache location of /var/cache/nginx/engintron_dynamic

### ISSUE THREAD

**Issue by mjpromotions** [engintron/engintron#1269]
Hi,
I want to change default cache location /var/cache/nginx/engintron_dynamic. 
I edit the file > /etc/nginx/nginx.conf to change path.
I see the new path filling with cache files, so that works.
However, when I check system status & info on Engintron panel I still see old cache location, with low MB's, as it is not used.
Purging cache through Engintron panel doesn't seem to empty the new custom location.

Can you advise on the correct steps to change location of nginx cache files generated by Engintron ?

Thanks

**Comment by fevangelou** [comment]
You obviously didn't search everywhere: https://github.com/engintron/engintron/search?q=%2Fvar%2Fcache%2Fnginx%2F

**Comment by xuhaibkhan1122** [comment]
Do I have to edit the /engintron.sh and app/engintron.php to the correct paths?

**Comment by fevangelou** [comment]
It don't recommend this. It's much easier to make a symlink to another partition if that's your issue.

**Comment by fevangelou** [comment]
```
rm -rf /var/cache/nginx/*
ln -s /var/cache/nginx /some/other/location
```

Done.

**Comment by xuhaibkhan1122** [comment]
@fevangelou Do you offer Paid Support! I am struck with couple of things and would like your help!

**Comment by fevangelou** [comment]
Sure thing. See where to contact me here: https://github.com/engintron/engintron#commercial-support--server-optimization-services
