### ISSUE TITLE
CloudFlare with Subdomains

### ISSUE THREAD

**Issue by ytlevine** [engintron/engintron#127]
I'm trying to set things up with Cloudflare, and I followed the instructions here: https://github.com/engintron/engintron/wiki/Engintron-&-CloudFlare

I'm setting up the "if" rules on the bottom for each dedicated IP, and I realized that I have a few dedicated IPs that have subdomains set up to come in to that IP address as well.
I didn't see any information on how that's supposed to be set up.

Am I supposed to create a separate "if" rule for each subdomain as well?
Or is there a way to include those in the same rule as the main domain, so that example.com and sub.example.com will both go to the same IP address?

Thanks a lot!

**Comment by fevangelou** [comment]
No, just use the "naked" domains (aka domain.tld - with no subdomains), unless a subdomain is on a different IP than the main domain.

**Comment by ytlevine** [comment]
So all I need is one entry, like this:

if ($host ~ "domain.com") {
	set $PROXY_DOMAIN_OR_IP "x.x.x.x";
}

And that will include all subdomains as well?

Thanks a lot!

**Comment by fevangelou** [comment]
Correct.

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by ytlevine** [comment]
Awesome, thanks a lot!
