### ISSUE TITLE
Video plays but with black screen

### ISSUE THREAD

**Issue by urosg3** [engintron/engintron#1270]
Hello,

I`m using Nginx/engintron on RHEL 8.2 server, for reverse proxy and simple health check for two application servers bellow them.
When I`m on RHEL/engintron nginx IP in the browser I can see that video is playing but with a black screen.
On the contrary when I`m directly on my application server IP in a browser, then video plays normally.
So the only difference is that I can`t see the video which is playing if goes trough Nginx/engintron reverse proxy

**Comment by fevangelou** [comment]
Since you're proxying to 2 other servers and given that Engintron was never tested on RHEL 8 (neither cPanel), I don't see how I could ever reply to your question unless you provide meaningful info on your Nginx customizations.
