### ISSUE TITLE
after install https stops responding

### ISSUE THREAD

**Issue by mitya3003** [engintron/engintron#1274]
Hello.

I have engintron on two servers. One works fine.

While I install it on second I get server unavailable for https requests to all websites.

I have latest cPanel and centos 7.9 x64

I try to disable CSF with no result.

I try full reinstall of engintron - also with no result.

it seems that there is some configuration error in firewall or rules that engintron creates works bad?

**Comment by fevangelou** [comment]
That's up to you to find out by spotting the differences in the setup of both servers. If it were an Engintron issue, none of your servers would work.

**Comment by mitya3003** [comment]
engintron doesnt create default_https.conf config file, so it is not listen 443 port.

Why this occurs? I several times totally reinstall it

**Comment by mitya3003** [comment]
I create it by manual way but nginx now uses server hostname ssl certificate for all domains.

So I need your helo to sort it out.

How to tell engintron recteate https configs?

**Comment by fevangelou** [comment]
See the docs at engintron.com/docs - it's most likely your crontab file's syntax is broken.

**Comment by mitya3003** [comment]
I fint error in crontab command that Ive made (cron tab job was not removed by uninstall operation).

I fix it, nginx become available on 443 port but it uses server hostname ssl certificate for all vhosts.

I re run this cron job and restart all services with same result.

**Comment by mitya3003** [comment]
Today my second server where engintron works fine has got same issue: for all virtual hosts nginx use server hostname ssl certificate.

**Comment by mitya3003** [comment]
In logs I got this

2021/01/15 22:23:23 [alert] 23124#23124: shared memory zone "SSL" was locked by 12493
2021/01/15 22:23:33 [alert] 23124#23124: worker process 13773 exited on signal 11
2021/01/15 22:23:33 [alert] 23124#23124: shared memory zone "SSL" was locked by 13773
2021/01/15 22:24:05 [alert] 23124#23124: worker process 13830 exited on signal 11
2021/01/15 22:24:05 [alert] 23124#23124: shared memory zone "SSL" was locked by 13830
2021/01/15 22:24:40 [alert] 23124#23124: worker process 13530 exited on signal 11
2021/01/15 22:24:40 [alert] 23124#23124: shared memory zone "SSL" was locked by 13530
2021/01/15 22:24:41 [alert] 23124#23124: worker process 14303 exited on signal 11
2021/01/15 22:24:41 [alert] 23124#23124: shared memory zone "SSL" was locked by 14303
2021/01/15 22:24:54 [alert] 23124#23124: worker process 14305 exited on signal 11
2021/01/15 22:24:54 [alert] 23124#23124: shared memory zone "SSL" was locked by 14305
2021/01/15 22:25:06 [alert] 23124#23124: worker process 13171 exited on signal 11
2021/01/15 22:25:06 [alert] 23124#23124: shared memory zone "SSL" was locked by 13171
2021/01/15 22:25:27 [alert] 23124#23124: worker process 14405 exited on signal 11
2021/01/15 22:25:27 [alert] 23124#23124: shared memory zone "SSL" was locked by 14405
2021/01/15 22:25:35 [alert] 23124#23124: worker process 14517 exited on signal 11
2021/01/15 22:25:35 [alert] 23124#23124: shared memory zone "SSL" was locked by 14517

**Comment by fevangelou** [comment]
Uninstall and re-install.
