### ISSUE TITLE
Recommendation: Change in the static the key with $schema

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1278]
recommended you bring the $schema keys back to what they were.
is will solve a lot of SEO issues and this the most important.

this the aherf robots.txt check, this how i figure out the problem:
https://ahrefs.com/robot

you can try run any site with your configuration you will see he get the bot, but because the transfer from HTTP static to
dynamic HTTPS...

chack me.

**Comment by fevangelou** [comment]
What the hell are you talking about, seriously...

**Comment by locksmithunit** [comment]
All the messages are in a mistake, it was all over the year and GitHub suddenly unblocks the account.
this message is over 1 year... and now everything got unblock i didn't know, i am sorry.

about the schema key.
In this case, I actually correct but it depends on your WordPress.
sorry again for all of that.

have a great day.
@fevangelou
