### ISSUE TITLE
Issues re-istalling Engintron

### ISSUE THREAD

**Issue by webhostsg** [engintron/engintron#1279]
Had issues with the log not reporting visitor's IP, so I reinstalled Engintron. After it completed i get this:

```
Checking Nginx configuration...
sh: nginx: command not found
```

Tried uninstalling Engintron and installing again still the same issue. I'm using CloudLinux 7.9

**Comment by webhostsg** [comment]
Everything is ok now, i don't know what happened by i re-install from GUI one more time and it works

**Comment by fevangelou** [comment]
Great :)
