### ISSUE TITLE
Sites with SSL activate not work without SSL

### ISSUE THREAD

**Issue by abkrim** [engintron/engintron#128]
Hi.

After install on WHM CENTOS 7.2 x86_64 kvm – hq  WHM 54.0 (build 21) with Apache 2.4 /easyapache 3 get a error.

All sites that has a SSL (not shared) not work on mode without https

Example:

Site **domain.tld**

https://domain.tld WORK
http://domain.tld NOT WORK

I need uninstall engintron for work all.

**Comment by fevangelou** [comment]
This doesn't tell me much. Do you use CloudFlare for SSL?

**Comment by abkrim** [comment]
No uses Cloudfare. Only Engintron.
On other server same problem. Same scenario.
apache 2.4 /Cpanel 
Shared server. Any domain with IP owned work. And this domains not use cloudfare.

Well.

Try now, update sysme. 
Restart machine
Execute script for install 
Fail all sites.
Restart apache manually... and now work...

Close issue.

**Comment by fevangelou** [comment]
So by simply restarting Apache once more after installation, you managed to solve your issue?

**Comment by CharlieJoseph** [comment]
Sorry to bump, I'm having the same issue.

If I type 'url.com' in the search bar without https, it automatically fails.

Anyway to fix?
