### ISSUE TITLE
Feed cache doesn't get cleared even after static cache expiry time

### ISSUE THREAD

**Issue by knm80** [engintron/engintron#1281]
Feed cache doesn't get cleared even after static cache expiry time. It doesn't reflect new posts until I purge all cache and temp files by going to WHM. How to avoid doing that and make feed cache expiry work seamlessly.

**Comment by fevangelou** [comment]
Example URLs?

**Comment by knm80** [comment]
domain.com/feed and domain.com/feed/atom

**Comment by fevangelou** [comment]
I meant actual URLs to I can test them with curl.

**Comment by knm80** [comment]
https://nokiapoweruser.com/news/feed
https://nokiapoweruser.com/news/feed/atom/

**Comment by fevangelou** [comment]
Your feed URLs have a "cache-control: max-age=172800" header. This is not set by Nginx, it's set by some WordPress plugin.

**Comment by knm80** [comment]
That's surprising because I don't use a page cache plugin and in Cloudflare I have this feed setup as cache bypass.

**Comment by knm80** [comment]
Anyways I have set a 30 min feed refresh time in my theme's functions file. Now, let's see if that works.

Can you please enable support for a plugin like Nginx helper if possible. This may help site owners using Engintron a lot.

**Comment by knm80** [comment]
Still the feed won't refresh until I purge all cache and temp files by going to Engintron in WHM

**Comment by fevangelou** [comment]
> Anyways I have set a 30 min feed refresh time in my theme's functions file. Now, let's see if that works.

Your feed cache is set to 48 hrs.

```
$ curl -I "https://nokiapoweruser.com/news/feed"
HTTP/2 301 
date: Mon, 08 Feb 2021 17:25:24 GMT
content-type: application/rss+xml; charset=UTF-8
content-length: 0
set-cookie: __cfduid=d478b2d1c06b792f73c791c4d4a114b6c1612805123; expires=Wed, 10-Mar-21 17:25:23 GMT; path=/; domain=.nokiapoweruser.com; HttpOnly; SameSite=Lax; Secure
cf-edge-cache: cache,platform=wordpress
x-redirect-by: WordPress
last-modified: Mon, 08 Feb 2021 12:20:18 GMT
etag: "a6aafbc034cab15dbde43a8367bcd55d"
location: https://nokiapoweruser.com/news/feed/
**cache-control: max-age=172800**
expires: Wed, 10 Feb 2021 17:25:23 GMT
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-nginx-upstream-cache-status: MISS
x-server-powered-by: Engintron
cf-cache-status: DYNAMIC
cf-request-id: 08244643f700009e6142010000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=B%2B%2FJq0FT0g0I6N%2BhaL%2FZOQT%2BAAoeRwHqEj3RAPuHgZk7KLWuPpWooGikzzfXj0OrAXSj3gaCSbpFaMO7ndbnos1DiNKUMFXCP7Evdqvlsxqqcjg%3D"}],"max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 61e70cb318369e61-ATH
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by knm80** [comment]
You are right. Even I checked in dev tools and see the same. But I have no plugin installed currently for doing this. In my htacess I have no such rules. In cloudflare I have the feed set as cache bypass. And every time I need to refresh the feed I need to purge Engintron cache. That's why I am not sure why this is happening.

**Comment by fevangelou** [comment]
WordPress' feeds are treated as dynamic content by Nginx. As such, they would fall into Nginx's microcache or if a specific cache-control header is sent, respect that header and cache the content accordingly (which is how a reverse caching proxy works).

So if you have a cache control header that says cache this page for 5 mins, Nginx will server-side cache it for 5 mins. Period.

If you want to control that effectively, you need to control how WP or Apache emit these cache-control headers. If it's not a WP plugin or some .htaccess rule it may be a global .htaccess rule (some Apache include). It may be another layer which I'm not aware of.

In any case, I've given you the knowledge for what to search for. I can't help you any further.
