### ISSUE TITLE
can you update nginx manually while using engintron?

### ISSUE THREAD

**Issue by iamsyh** [engintron/engintron#1283]
Hi guys,

First of all, thank you so much for providing this amazing plugin/app to us for free! Really appreciate it and will donate surely!

Now I've got a question guys; can I update nginx manually while using it with Engintron? That's how I originally installed it on my cPanel based server. Does anyone have any experience with doing this?

Thank you for reading and answering! :)

**Comment by fevangelou** [comment]
Update Nginx itself or its configuration?

**Comment by fevangelou** [comment]
Closing as there is no response from the OP.
