### ISSUE TITLE
Visitor IP incorrect when using Engintron+CloudFlare

### ISSUE THREAD

**Issue by windsofchange** [engintron/engintron#1285]
Hello,

When a visitor views a page, the visitor IP is shown as the CloudFlare Railgun IP instead of visitor's IP. If Enginetron is disabled, the visitor IP shows up correctly.

Any ideas?

**Comment by fevangelou** [comment]
CloudFlare will only provide a user's IP in a special HTTP header. If you see user IPs with Engintron off, you probably have the CloudFlare plugin for cPanel, so Apache is configured to access/log that special HTTP header.

**Comment by konstantinosbotonakis** [comment]
From https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs-logging-visitor-IP-addresses

`Use the following Nginx module and the following configuration parameters:set_real_ip_from 103.21.244.0/22; set_real_ip_from 103.22.200.0/22; set_real_ip_from 103.31.4.0/22; set_real_ip_from 104.16.0.0/12; set_real_ip_from 108.162.192.0/18; set_real_ip_from 131.0.72.0/22; set_real_ip_from 141.101.64.0/18; set_real_ip_from 162.158.0.0/15; set_real_ip_from 172.64.0.0/13; set_real_ip_from 173.245.48.0/20; set_real_ip_from 188.114.96.0/20; set_real_ip_from 190.93.240.0/20; set_real_ip_from 197.234.240.0/22; set_real_ip_from 198.41.128.0/17; set_real_ip_from 2400:cb00::/32; set_real_ip_from 2606:4700::/32; set_real_ip_from 2803:f800::/32; set_real_ip_from 2405:b500::/32; set_real_ip_from 2405:8100::/32; set_real_ip_from 2c0f:f248::/32; set_real_ip_from 2a06:98c0::/29;use any of the following tworeal_ip_header CF-Connecting-IP; #real_ip_header X-Forwarded-For;That list of prefixes needs to be updated regularly, and we publish the full list in Cloudflare IP addresses.
To Include the original visitor IP in your logs, add the variables $http_cf_connecting_ip and $http_x_forwarded_for in the log_format directive.`

**Comment by fevangelou** [comment]
This is baked into Engintron since forever :)

https://github.com/engintron/engintron/blob/master/nginx/nginx.conf#L64

**Comment by fevangelou** [comment]
And here... https://github.com/engintron/engintron/blob/master/nginx/proxy_params_common#L25
