### ISSUE TITLE
nginx fails to start

### ISSUE THREAD

**Issue by duuhmenezes** [engintron/engintron#1286]
please help-me
Feb 11 08:25:50 zeus.novadedicados.com.br nginx[3940]: nginx: [emerg] invalid number of the map parameters in /etc/nginx/conf.d/ea-nginx.conf:2

------------- file ea-nginx.conf---------------

map $host $CPANEL_APACHE_PROXY_IP {
default ;
}

map $host $CPANEL_APACHE_PROXY_PORT {
default ;
}

map $host $CPANEL_APACHE_PROXY_SSL_IP {
default ;
}

map $host $CPANEL_APACHE_PROXY_SSL_PORT {
default ;
}

server_names_hash_max_size 1024;
server_names_hash_bucket_size 128;

**Comment by fevangelou** [comment]
Well, don't customize what you don't know. It's simple.
