### ISSUE TITLE
How to exclude feed from Engintron caching

### ISSUE THREAD

**Issue by knm80** [engintron/engintron#1289]
Hi,

Can you please tell me how to exclude feed from caching in Engintron?

**Comment by fevangelou** [comment]
You need to be more specific. You can exclude from a single URL to entire domains & paths in custom rules...

**Comment by knm80** [comment]
Appreciating you taking time to respond to that. I figured that out already with help of my hosting support.

**Comment by fevangelou** [comment]
Great :)
