### ISSUE TITLE
Engintron and .htaccess redirects and SetEnvIf

### ISSUE THREAD

**Issue by dandrikop** [engintron/engintron#1290]
I'm running Magento on Apache and I'm investigating the solution of Engintron. If I understood correctly, my website will continue to be served by Apache for Engintron/NginX, and NginX working as reverse proxy will serve visitors. My ISP claims that any redirects specified in .htaccess file will not work with Engintron. I have various redirects in .htaccess file such as the following:

RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

Also, my .htaccess file has the below lines specific to Magento:

SetEnvIf Host www\.mydomain\.com MAGE_RUN_CODE=base
SetEnvIf Host www\.mydomain\.com MAGE_RUN_TYPE=website
SetEnvIf Host de\.mydomain\.com MAGE_RUN_CODE=mydomain_de
SetEnvIf Host de\.mydomain\.com MAGE_RUN_TYPE=website
SetEnvIf Host fr\.mydomain\.com MAGE_RUN_CODE=mydomain_fr
SetEnvIf Host fr\.mydomain\.com MAGE_RUN_TYPE=website

Will all the above work with Engintron?

**Comment by fevangelou** [comment]
Why wouldn't they work? :)

99,99% of issues with .htaccess rules stem from double (or bad) redirects or redirects that work on top of existing PHP redirects in CMSs (e.g. Joomla or WordPress are capable of auto-redirecting via PHP to a secure connection).

**Comment by dandrikop** [comment]
I cannot also think a reason that an Apache redirect may not work on Engintron/NginX. I have two types of redirects:

- .htaccess level like the below:
`   RewriteCond %{HTTP_HOST} !^www\. [NC]
    RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]`

- 301 Redirects at Magento level like the below:
   https://de.dlastore.com/externe-einheit/kraftstoffpumpen-1.html

Is there any chance that a redirect works without Engintron, and may not work with Engintron?

**Comment by fevangelou** [comment]
It'll work just fine.

**Comment by dandrikop** [comment]
Is the following setup feasible so that I test Engintron without any impact on the current implementation?

- Install Engintron and activate NginX on different ports than Apache (for instance 8080 for HTTP and 4443 for HTTPS).
- Apache continues serving Internet clients as currently.
- Test Engintron / NginX by passing to the website via the new ports, for example visiting https://www.dlastore.com:4443 instead of the standard https://www.dlastore.com:443 which will be served by Apache.

**Comment by fevangelou** [comment]
Install and disable to test on 8080 & 8443.
