### ISSUE TITLE
Mobile Caching Issue

### ISSUE THREAD

**Issue by jessebrightman** [engintron/engintron#1292]
Hi guys,

First of all, I absolute love engintron and use it on multiple servers!  Just recently, I updated a box to v14 and I have had a strange issue on just the one server where the engintron cache gets stuck but only on mobile.  As a workaround, I have manually purged the caches and also commented out the separate mobile cache setting in the proxy_params_dynamic file.  I'm just wondering if anyone else has had this issue pop up and if there is a solution out there that doesn't require changing the core.  Monitoring it daily is time consuming.  Thanks.

**Comment by fevangelou** [comment]
If you comment out the prefix that gets created for mobile devices, then you won't have a mobile specific cache. That's why you probably have these issues...

**Comment by jessebrightman** [comment]
Appreciate the thoughts.  I will try again with the mobile specific cache.  Keep up the great work.

**Comment by jessebrightman** [comment]
Default configuration still produces the issue, however, I have now added the page url to the === DOMAIN AND URL PATH EXCLUSIONS FROM CACHING === section in custom_rules.  Problem solved.  The original issue was probably related to additional software/network caching.  Thanks for everything.
