### ISSUE TITLE
location match allow ip doesnt work

### ISSUE THREAD

**Issue by AnaxagorasKosta** [engintron/engintron#1293]
Added a rule into common_http.conf but allow ip; deny all doesnt work . i get 404 from server and remotely. 

reproduce:

```
location ~ ^/(wp-cron\.php) {
        allow 127.0.0.1;
        deny all;
}
```
nginx error.log file

`021/03/04 15:42:50 [error] 14754#14754: *6 open() "/etc/nginx/html/wp-cron.php" failed (2: No such file or directory), client: ::ffff:10.50.1.28, server: domain.com, request: "POST /wp-cron.php?doing_wp_cron=1614865370.5635790824890136718750 HTTP/1.1", host: "domain.com", referrer: "https://domain.com/wp-cron.php?doing_wp_cron=1614865370.5651790824890213671870"
`

**Comment by fevangelou** [comment]
Yeah, don't do that. Nginx acts as a proxy, not a webserver. Location definitions will fail in the absence of a "root" path directive.

Deny all access to your wp-cron.php file in .htaccess and trigger the file via php (=calling the filesystem path to the file, not an HTTP URL), using a cron job.

**Comment by AnaxagorasKosta** [comment]
I did add to .htaccess but it still doesnt work. No able to view the wp-cron.php url 
`<Files ~ "(wp-cron.php)$">  
Require all denied
Require ip ipAddress
</Files>
`

**Comment by AnaxagorasKosta** [comment]
found the reason didnt work (it was getting the servers ip address), but still after following these tutorials https://www.damchey.com/2018/01/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel/
https://engintron.com/docs/#/pages/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel

the problem is not solved. i am still getting the servers ip insteaf of the real ip address.

**Comment by AnaxagorasKosta** [comment]
Okay fixed it.

For anyone has this issue just add the local ip to this file.
/etc/apache2/conf.modules.d/370_mod_remoteip.conf

**Comment by fevangelou** [comment]
There's an option to do that in Engintron, under the "Apache" section (Restore Nginx IP forwarding in Apache).
