### ISSUE TITLE
Real IP address not logged in nginx log files. only apache 

### ISSUE THREAD

**Issue by AnaxagorasKosta** [engintron/engintron#1294]
**CPanel** v94.0.2
**Engintron** v1.14.0 Build 20201028 (Nginx version: 1.19.8)

Firstly, I would like to mention that  I use Barracuda Firewall. (Barracuda logs ip addresses correctly)

Furthermore, yesterday i changed remoteip.php file and included all ip addresses (barracudas, local, public) see below.
```
LoadModule remoteip_module modules/mod_remoteip.so
RemoteIPHeader        X-Forwarded-For
RemoteIPInternalProxy 127.0.0.1 localIP baracudaLocalip  ServerPublicIP

```

LogFormat (combined) [?]
`%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"`

LogFormat (common) [?] 
`%a %l %u %t \"%r\" %>s %b`

/usr/local/apache/conf/httpd.conf
```
<IfModule mod_log_config.c>
    LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combinedvhost
    <IfModule logio_module>
        LogFormat "%v %{%s}t %I .\n%v %{%s}t %O ." bytesvhost
    </IfModule>
    LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b" common
    LogFormat "%{Referer}i -> %U" referer
    LogFormat "%{User-agent}i" agent


            <IfModule logio_module>
        CustomLog "|/usr/local/cpanel/bin/splitlogs --dir=/etc/apache2/logs/domlogs --main=hostname.mydomain.com --suffix=-bytes_log --sslport=8443" b$
    </IfModule>
    CustomLog "|/usr/local/cpanel/bin/splitlogs --dir=/etc/apache2/logs/domlogs --main=hostname.mydomain.com --mainout=/etc/apache2/logs/access_log --$
</IfModule>
```

In nginx /var/log/nginx/access.log and error.log i get baracudaLocalip
```
::ffff:baracudaLocalip - - [10/Mar/2021:13:10:02 +0200] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 171 "" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1"
```

in apache /var/log/apache2/error_log i get the correct IP address
```
Wed Mar 10 13:03:35.343853 2021] [:error] [pid 5629:tid ] [client correctIP:0] [client correctIP] ModSecurity: Access denied with code 403 (phase 2). Matched ....
```

I am confused. shouldnt be working? I have read every single issue here related to IP addresses, and nothing fixed it. 

Any help would be much appreciated

**Comment by fevangelou** [comment]
The real IP is passed to Apache via Nginx, using a different HTTP header, which Nginx does not use for logging. That's because Nginx is configured to always be placed first in the chain of traffic. In your case, the scenario is like placing Nginx behind a NAT. Nginx can't possibly know the IP of the firewall, so yes, there's an additional step you need to take.
