### ISSUE TITLE
Fresh Install on Brand New cPanel Dedicated Server - Welcome to Nginx?

### ISSUE THREAD

**Issue by evolvingant** [engintron/engintron#1295]
[nginx.tar.gz](https://github.com/engintron/engintron/files/6126431/nginx.tar.gz)
I just setup WHM/cPanel on a new dedicated server. I installed the Engintron and all my sites are showing Welcome to nginx on Red Hat Enterprise Linux!

I'm using Centos 8.

Haven't changed anything. I tried the link for the Fedora fix mentioned in the documentation, tried both mainline, and regular, nothing fixes it.
![Screenshot 2021-03-11 175959](https://user-images.githubusercontent.com/80491955/110866742-9ebe3100-8293-11eb-83f0-c08aa24b9159.jpg)

Website is https://talksos.com

What do I need to look at to fix this?
ATTACHED is nginx.tar.gz which is the entire /etc/nginx/ directory and all contents.

**Comment by evolvingant** [comment]
*** Engintron is ENABLED ***
########################################
*** System Info ***

Uptime: 00:14:53 up  1:27,  1 user,  load average: 0.02, 0.07, 0.02

OS: CentOS Linux release 8.3.2011

Kernel: Linux server1.bloopsee.com 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Mon Mar 1 17:16:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Processors: 24 CPU(s)

RAM: 125.56 GB

Memory Usage:
              total        used        free      shared  buff/cache   available
Mem:         128570        1781      123741           7        3046      125622
Swap:          4090           0        4090

Disk Usage:
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs   63G     0   63G   0% /dev
tmpfs          tmpfs      63G     0   63G   0% /dev/shm
tmpfs          tmpfs      63G  1.1M   63G   1% /run
tmpfs          tmpfs      63G     0   63G   0% /sys/fs/cgroup
/dev/md2       ext4      1.8T   37G  1.6T   3% /
/dev/md1       ext3      487M  215M  247M  47% /boot
tmpfs          tmpfs      13G     0   13G   0% /run/user/0

Nginx Cache/Temp Disk Usage:
4.0K	/var/cache/nginx/engintron_dynamic
4.0K	/var/cache/nginx/engintron_static
4.0K	/var/cache/nginx/engintron_temp

System Time: Fri Mar 12 00:14:53 CET 2021

System Users Connected:
00:14:53 up  1:27,  1 user,  load average: 0.02, 0.07, 0.02
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
root     pts/0    71.47.227.23     00:10    2:30   0.00s  0.00s -bash

**Comment by evolvingant** [comment]
I have disabled Engintron for the time being so the sites will continue to work.

**Comment by evolvingant** [comment]
fixed the existing issue by renaming the default Nginx page (/usr/share/nginx/html/)

**Comment by fevangelou** [comment]
This will only occur if you installed Nginx from some other repo. Or if some other repo that has the Nginx package in and takes precedence over the default Nginx repo.
