### ISSUE TITLE
http://vzdownload.swsoft.com - HTTP Error 504 - Gateway Timeout

### ISSUE THREAD

**Issue by Pol67** [engintron/engintron#1297]
Hello,
last two parts didn't install as the mirror was inaccessible. Hopefully that is only temporary error?

failure: repodata/primary.xml.gz from vz-base: [Errno 256] No more mirrors to try.
http://vzdownload.swsoft.com/ez/packages/centos/7/x86_64/os/repodata/primary.xml.gz: [Errno 14] HTTP Error 504 - Gateway Timeout

**Comment by fevangelou** [comment]
How this is relevant to Engintron is really beyond my comprehension...
