### ISSUE TITLE
Problem with location / and try_files

### ISSUE THREAD

**Issue by hebergementwebs** [engintron/engintron#1298]
hello everybody,

I have uploaded all of my file in the root folder on nginx.

I have activated the try_files fonction in location /

location / {
try_files $uri $uri.html  @backend;
}

all of page look working in the cache but not the / index.html

my folder /usr/share/nginx/html look like

/usr/share/nginx/html/index.html not detected not working
/usr/share/nginx/html/article.html cache working 
/usr/share/nginx/html/article2.html cache working 
/usr/share/nginx/html/article3.html cache working 
/usr/share/nginx/html/article4.html cache working 

any idea what is my problem thank you

**Comment by fevangelou** [comment]
Nginx works in proxy mode - you can't use location blocks. Perform any rewrites in Apache. Nginx will honor them.
