### ISSUE TITLE
TLS 1.3 Problem

### ISSUE THREAD

**Issue by d4mourtzis** [engintron/engintron#1299]
Hi, i have tried everything to enable TLS1.3 in engintron-nginx but i had no luck. 
I reinstalled my server with openssl 1.1.1 but when i install engintron it compiles nginx with older openssl which does not support tls1.3. I also managed to recompile nginx manually in openssl1.1.1. but then i installed engintron and again nginx went to previous version. Is there any way to have TLS 1.3 with engintron?

B.T.W excellent work Fotis
Dimitris from Greece!!

**Comment by fevangelou** [comment]
Is this CentOS 6 or 7?

**Comment by d4mourtzis** [comment]
Centos 7!

**Comment by fevangelou** [comment]
a) If you want to use Engintron, you should not manually compile Nginx
b) I would recommend removing any custom installation for Nginx from your system, removing Engintron as well and then re-installing Engintron.

Use TLS 1.2 which is active and fully supported by both cPanel and the Nginx repo for CentOS 7. Using TLS 1.3 only will limit who gets to access any of your sites (anything newer than Firefox 63, Android 10.0, Chrome 70, Edge 75, Java 11, OpenSSL 1.1.1, Opera 57 & Safari 12.1): https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=modern&openssl=1.1.1d&guideline=5.6

Perhaps you may want to consider switching to intermediate cipher support (enab;e this block and disable the default one here https://github.com/engintron/engintron/blob/master/nginx/common_https.conf#L28-L32) if you want to exclude older ciphers.

**Comment by d4mourtzis** [comment]
That is perfect i had not noticed that at all. I will try the Intermediate client support!
Thanks
