### ISSUE TITLE
Deny all not working

### ISSUE THREAD

**Issue by laurfx** [engintron/engintron#130]
When i put in htaccess the rules for deny all it's working without url:8080 but when i put in nginx it doesn't work.

   location = /myurl/{
    allow 127.02.32.1;
    deny all;
    }

In that folder are many PDF's files, which i want to be blocked by all and allowed just for few ip addresses, how i can do it?

Thanks.

**Comment by fevangelou** [comment]
Do whatever you want to do on .htaccess files in Apache. Do not modify
Nginx's config files unless you know what you're doing.

**Comment by laurfx** [comment]
If i do only in .htaccess files in Apache it will work only when i put the port after the website url, ex: www.mywebsite.com:8080/myurl

**Comment by fevangelou** [comment]
Of course not. Unless your rules are port specific. What are you using in
.htaccess now?

**Comment by laurfx** [comment]
# ALLOW USER BY IP
<Limit GET POST>
 ErrorDocument 403 /specific_page.html
 Require all denied
 Require ip IP1
 Require ip IP2
 Require ip IP3
 Require ip IP4
</Limit>

What do you mean by port specific? I should put rules to work only with port 80 ?

**Comment by fevangelou** [comment]
What version of Apache is installed on your cPanel server?

I need to make sure the rules are correct for the version of Apache you run.

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by laurfx** [comment]
I use Apache 2.4.18.

I know what Engintron is and is awesome, thank you for that, but i asked if it's there any way to put rules in .htaccess (Apache what is runing on port 8080) to work on port 80 over (Nginx)Engintron, that i understand from what do you said.

How i said, that rules what i put in .htacces it won't work over NGINX.

**Comment by laurfx** [comment]
Can you help me with that?

Thanks.

**Comment by fevangelou** [comment]
Create a .htaccess file in the root of the site you wish to control access and then simply add the following lines in it:

    order deny,allow
    deny from all
    allow from <your ip>

Repeat the last line to add more IPs.

The issue you faced is Apache specific, it's not Nginx specific, nor is Engintron involved in any way overall. The rules you originally set in Apache did not work with Nginx, because they obviously did not work with Apache in the first place.

In any case, Google is your friend: http://stackoverflow.com/questions/4400154/deny-all-allow-only-one-ip-through-htaccess

**Comment by laurfx** [comment]
Hello,

You closed the topic but it's not solved, that rule is for Apache 2.2, the correct rule for 2.4 is:

Require all denied
Require host IP-TO-ALLOW

But this don't solve my problem, the real problem is that Engintron is don't get the real IP from clients so that's why i get 403 Forbidden.

I installed Mod_remoteip but i don't know how to make it to work proprely with Engintron, can you help me with that?

Thanks.

**Comment by fevangelou** [comment]
Just update/re-install Engintron. It should already install & configure mod_remoteip for you.

**Comment by laurfx** [comment]
Now is working, thanks !
