### ISSUE TITLE
Engintron is causing some issues with Pagespeed Insights (Core Web Vitals)

### ISSUE THREAD

**Issue by WebSavvyDude** [engintron/engintron#1300]
As you probably know, Google is going to add a new ranking factor based on Core Web Vitals.  Normally we would check our rating/score by using the Pagespeed Insights Tool found here:  https://developers.google.com/speed/pagespeed/insights/

However, with Engintron enabled it is not allowing it go to through.

<img width="956" alt="Screen Shot 2021-04-03 at 6 16 18 PM" src="https://user-images.githubusercontent.com/24284360/113475507-bc547400-94a8-11eb-99c9-def5ce853e3a.png">

"Lighthouse returned error: ERRORED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 520)Dismiss"

Once I disable Engintron I am able to check and get the scores without issue.   Therefore, I think Engintron is causing some issues which doesn't allow Lighthouse to read the site. (of course there could be some other factors as well)

Can you please look into this? @fevangelou

**Comment by fevangelou** [comment]
This is specific to that site or server setup. There's no issue with Engintron here. Proxies have existed on the web for decades now.

**Comment by WebSavvyDude** [comment]
@fevangelou 

Thanks for the reply.  Just reporting my findings.

Tested on 2 different servers but same host.  Multiple websites (about 10 different domains).  Some with Cloudflare, some without.  Some new domains, some old.   Tested with Cloudflare both ON and OFF.
Both servers have standard set up with latest version of WHM/CPanel.  No special add ons or configurations other than those offered in WHM/CPanel.  Some PHP sites, some HTML static sites.

Both servers exhibit the same behaviour.

TURN ENGINTRON ON = Google PageSpeed unable to report on all domains with error noted above.
TURN ENGINTRON OFF = Google PageSpeed responds to all domains.

Having said that, I do have one domain on a third different server that DOES NOT have Engintron installed yet its also getting this issue.   Its a completely different server with just Nginx. (No Cpanel)   It only allows Pagespeed reports on HTML pages but not on PHP pages.   That could be domain specific, however, the above 2 CPanel servers are definitely exhibiting weird behaviour when it comes to Google PageSpeed and Engintron Enabled.

Anything you can see it being?

**Comment by fevangelou** [comment]
Could be something else that's blocking PageSpeed. Perhaps something that checks user agents before allowing a connection to go through.

Here's a list you can test as well: https://publicwww.com/websites/engintron/

The few that I check all run the PageSpeed test just fine.
