### ISSUE TITLE
Can i use Engintron with DNS Only server?

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1301]
It is possible?
I have "DNS only" Cpanel server on google cloud:
https://docs.cpanel.net/installation-guide/cpanel-dnsonly-installation/

Can i install Engintron on this?
or is not compatible?

**Comment by fevangelou** [comment]
No, it's not possible.

**Comment by locksmithunit** [comment]
Ok, thank you. appreciate your response.
