### ISSUE TITLE
Engintron still needed after cPanel comes with their own implementation?

### ISSUE THREAD

**Issue by IkenHuub** [engintron/engintron#1302]
Hi,

cPanel just released their own implementation of NGINX.
https://docs.cpanel.net/knowledge-base/web-services/nginx-with-reverse-proxy/#the-nginx-installation

Where does that leave Engintron?

**Comment by fevangelou** [comment]
2 reasons mainly:
a) Better performance (because of built-in caching).
b) Your site users get to keep their .htaccess configs and rules.

Read cPanel's blog post here as well: https://blog.cpanel.com/how-to-install-and-manage-nginx-on-cpanel/
