### ISSUE TITLE
Is this needed with Cpanel 96?

### ISSUE THREAD

**Issue by scottct1** [engintron/engintron#1303]
Cpanel today released version 69 which has Nginx caching built into it.

Do we still need to run Engintron or should we remove it and use the one built into Cpanel?

Is there a reason to use one over another?

Thanks!

**Comment by virtualos** [comment]
> Cpanel today released version 69 which has Nginx caching built into it.
> 
> Do we still need to run Engintron or should we remove it and use the one built into Cpanel?
> 
> Is there a reason to use one over another?
> 
> Thanks!

You mean v96
Me too! wondering about Engintron next move ;) But I still think Engintron is more mature and better cooked than cPanel Nginx.

Well I'm sure Fotis is cooking something hot for cPanel :)

**Comment by CarlosLopezES** [comment]
I'm also wondering next move for Engintron! I'm so happy with this solution and I will continue with it as long Fotis wants to support it :)

Last year cPanel Nginx didn't have caching, but now it's the full package. However, I suspect that Engintron it's a lot more flexible and customizable, and this is a great advantage.

I'm waiting to deploy in a trial server and test if there are performance differences between them

**Comment by fevangelou** [comment]
Engintron is not going anywhere, that's for sure... And it's not going anywhere for multiple reasons, one of which is that I personally use it :)

Do take some time to read cPanel's own blog post on using Nginx on cPanel: https://blog.cpanel.com/how-to-install-and-manage-nginx-on-cpanel/

Even if cPanel adds reverse caching proxy features in their own implementation for Nginx, there's always room to do things differently.

Think about this for a sec... cPanel could be performant out of the box, e.g. auto-tune Apache & MySQL/MariaDB based on available hardware specs, number of cPanel accounts/sites, outgoing bandwidth etc. etc. But it's not. If it was, what leverage would cPanel client A have over cPanel client B?

**Comment by chopinesque** [comment]
I tested Cpanel's implementation. Feeling underwhelmed really, a short review I wrote here: https://www.translatum.gr/forum/index.php?topic=992620.0

**Comment by CarlosLopezES** [comment]
> I tested Cpanel's implementation. Feeling underwhelmed really, a short review I wrote here: https://www.translatum.gr/forum/index.php?topic=992620.0

Thank you! But in the other hand, I think that the examples are very bad for Nginx in general.

Nginx as proxy reverse takes advantage in CMS scenery or websites with multiple images. As you can see in your benchmark, a forum index doesn't have any advantages with Nginx over Apache because there not almost static content.

**Comment by chopinesque** [comment]
I am not sure whether cpanel's implementation uses microcaching. To start with, there are no config options. On the other hand, I noticed a change in engintron's code removing longer-term caching: https://github.com/engintron/engintron/commit/defde7b1b5c18d5b0c72eebfb99f551466b40d6c

**Comment by fevangelou** [comment]
@chopinesque You failed to mention that this commit is about specific file types that are usually related to pure data distribution (JSON, CSV etc.). Not for everything...

**Comment by fevangelou** [comment]
I believe the topic is answered. Since it's not really constructive, I'm closing it now.
