### ISSUE TITLE
Can i use pretty permalinks with the @backend instance?

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1305]
Hey... :)
I try to follow this:"
https://wordpress.org/support/article/using-permalinks/

if you go down a little bit you will see recommendation use permalinks:
location / {
            try_files $uri $uri/ /index.php?$args;
}

now I see you have inside http_common:

location / {
    try_files $uri $uri/ @backend;
}

_________________________________

what about:
location / {
    try_files $uri $uri/ /index.php?$args @backend;
}

______________________________

it is possible?

**Comment by fevangelou** [comment]
No. You use .htaccess rules in Apache for that. Nginx will pick up the "pretty" permalinks.

**Comment by locksmithunit** [comment]
Ok, you the boss.
Thank you.
