### ISSUE TITLE
Rate Limiting Help

### ISSUE THREAD

**Issue by evolvingant** [engintron/engintron#1308]
I am trying to introduce rate limiting as follows. I've tried in nginx.conf and custom rules, but it breaks. Please tell me how to put this in there properly.

limit_req_zone $binary_remote_addr zone=global:10m rate=1r/s;
limit_req zone=global burst=5;
location / {
limit_conn addr 3;
limit_rate 1500k
}

**Comment by fevangelou** [comment]
I would recommend you use this guide: https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-proxied-http/

Just make sure NOT to use `location...` blocks, instead anything that should go in a location block, try adding it in your custom rules file directly. This includes anything that should go inside `server {...}` blocks.

Finally, what should go directly into the `http { ... }` block you need to add it in your nginx.conf file and keep record of that change so you don't lose it in the future.

However, if you're looking to protect your site(s) or server from DoS attacks, it's much better to control IP connection count in the firewall, e.g. via CSF. Just set CT_LIMIT there to say 300 or 400 and you're done. Any IP that does more than 300 or 400 concurrent connections gets blocked on the firewall which is much more efficient. The reason you provide a few hundred connections per sec is to cover external proxies (e.g. CSF) and mobile gateways that may route traffic from multiple clients to a single IP that then connects to your server.

**Comment by evolvingant** [comment]
I use CSF. My main goal is to just limit the download speed per IP address to 1500kb/sec or whatever I choose that limit to be. Is there an easy code you could provide please for me to add that to the custom rules?

**Comment by fevangelou** [comment]
It's really beyond the scope of the support I provide here.
