### ISSUE TITLE
Strange page on websites

### ISSUE THREAD

**Issue by windsofchange** [engintron/engintron#1309]
Hello,

Did a clean install of latest version, Now the website main page shows a stange place holder https://www.awesomescreenshot.com/image/7951250?key=69e5088f2f48dc2aa2b715a9116b4545

What did I do wrong?

**Comment by fevangelou** [comment]
You changed OS for starters? My guess is that Almalinux's repos already contain Nginx and that build takes precedence over the official Nginx repo that Engintron configures.

See this https://wiki.centos.org/PackageManagement/Yum/Priorities on how to change the priority for the Nginx repo.

Plus, Engintron has not yet been tested with Almalinux, but it \*should\* work just fine.
