### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by zstergios** [engintron/engintron#1310]
I had issue with ssl on one site, I disabled-enabled the engintron, and from then never worked again, i am getting connection refused ( ΑΔΥΝΑΜΙΑ ΣΥΝΔΕΣΗΣ) to browser, like apache was down. (was not, all services was running OK)

1) disabled-enabled multiple times
2) Re-installed it
3) Uninstalled it and installed it again

No luck...any help?

**Comment by fevangelou** [comment]
Do a "force restart" from the Engintron WHM app as there may be a port binding issue.
Worse case scenario (after you re-install Engintron): double check Apache's ports in Tweak Settings, if they are OK but you still get issues (Nginx does not respond), then do this:
```
$ fuser -k 80/tcp
$ fuser -k 8080/tcp
$ fuser -k 443/tcp
$ fuser -k 8443/tcp
```
Restart Engintron and test again.
