### ISSUE TITLE
Recommended WordPress Cache Plugin(s)

### ISSUE THREAD

**Issue by VR51** [engintron/engintron#1312]
I've installed Engintron into a VPS server. I'm happy with the installation process, which was smooth.

I'm using the LiteSpeed WordPress cache plugin in one site. It seems to work ok but I'm thinking there must be a working cache plugin more appropriate for nginx. Is there a preferred WordPress cache plugin to use with nginx or specifically with Engintron?

**Comment by fevangelou** [comment]
The trick is to use a plugin that sets the correct cache-control headers for your site. Beyond that, Engintron will do its magic.

If you can install Memcached additionally using Engintron's utilities folder, you can have a killer combo.

You can use this Memcached driver for WordPress: https://github.com/kodeka/kdk_memcached_object_cache

For generic caching you can use either W3 Total Cache (Memcached support is built-in here) or go for a commercial one like WP Rocket (which can utilize the above driver). The first one is probably a bit harder to setup but does the job just fine.

It's in my plans to release official Engintron plugins in the future for WordPress, Joomla and perhaps other CMSs for a more flexible caching experience.

**Comment by VR51** [comment]
Thank you for this information. It is good to know. I will test with W3 Total Cache and see how performance differs from LiteSpeed Cache.

I must say I like LiteSpeed Cache. It has a lot of useful features and integrates with Memcached and Redis but on my provider's VPS servers Memcached is easier to get working when installed via your installer for it.
