### ISSUE TITLE
502 bad gateway while trying to access my website and it's subdomains

### ISSUE THREAD

**Issue by armaneth95** [engintron/engintron#1314]
Hi
Am running a cpanel server with a main website and subdomains.
I installed Engintron and since that moment I get "502 Bad Gateway" when trying to access my website or subdomains.
When I try reaching then through port 8080 (ex: mydomain.tld:8080) everything work fine.

After checking NGINX error log, I got this 

**2021/05/12 09:27:45 [error] 41177#41177: *457 connect() failed (110: Connection timed out) while connecting to upstream, client: ::ffff:137.255.6.21, server: localhost, request: "GET / HTTP/1.1", upstream: "http://XXX.XXX.XXX.XXX:8080/", host: "mydomain.tld"**

I have tried setting **$PROXY_DOMAIN_OR_IP** to my server IP and even to the domain name but nothing changed

Thanks for your kind help

**Comment by fevangelou** [comment]
On which OS version please?

**Comment by armaneth95** [comment]
Hi
We installed it on Cpanel 94 running on CentOS 7.
As we got no solution we finally removed it. Will be helpful to know how to
make it work.

Regards
--
Kenneth Hounsou

**Comment by fevangelou** [comment]
Nginx to Apache connections may time out for a ton of reasons. Search past issues and you'll find your answer...
