### ISSUE TITLE
Redirect Loop for Inbound Traffic Routed Through a CDN

### ISSUE THREAD

**Issue by VR51** [engintron/engintron#1315]
This may be related to #1306.

I've installed Engintron onto two different VPS servers. Both servers are configured the same way and are provided by the same webhost (Namecheap). One of these servers hosts several sites that receive traffic through the eZoic ad network's CDN. eZoic's CDN uses a network of Amazon web servers. eZoic also allows integration with Cloudflare. One of the sites on the server cannot serve SSL pages without entering a redirect loop. Other sites on the same server using the same network conditions work fine.

- I have configured Engintron to work with Cloudflare.
- I have whitelisted the AWS IP addresses used by eZoic's CDN. I did this using the CFS GUI's 'Firewall Allow IPs' screen (edits /etc/csf/csf.allow)
- I've reviewed the affected site's .htaccess rules
- I have tested the site with Cloudflare enabled and disabled. Same result.
- I've tried different CND SSL settings (Flexible, Full and Strict)
- I've tried enabling and disabling HTTP to HTTPS redirects in .htaccess and at the CDN
- I can access the site without issue when I map the domain name to the server's IP address in my local hosts file to bypass the eZoic CDN.
- Subdomains of the same site work fine
- I'm about to switch the site's nameservers to send traffic direct to the server. I'm waiting for the registrar's authorisation key to come through so I can make the change and test.

The issue seems to be with how the server responds to traffic routed through eZoic's CDN but it affects one site only and not subdomains of that same domain.

Any suggestions for what might be causing the redirect loop?

**Comment by VR51** [comment]
I think I've discovered the issue. It might not be Engintron related though I needed to uninstall Engintron for the solution to take. The faulty site (a WordPress site) was presenting as both www and non-www. The issue was being masked by the CDN. I will reinstall Engintron in the early hours when site traffic is lower.

**Comment by fevangelou** [comment]
As long as Engintron is configured for CloudFlare (which is essentially for any CDN), you should have no issues with Ezoic, even if Ezoic proxies traffic to CloudFlare which in turn lands on your server...

**Comment by VR51** [comment]
I am sorry for my very late reply. The issue was due to an internal configuration within eZoic, a switch only eZoic's tech team could toggle.

Thank you for your reply. I will send you a donation this week to show appreciation for your time and work.

Lee

**Comment by fevangelou** [comment]
Good to know @VR51 :)

**Comment by VR51** [comment]
@fevangelou 29 days later... I've just sent that donation.

For anyone else struggling with eZoic origin errors, eZoic has a new CDN that uses fewer IP addresses than eZoic's conventional CDN (12 IP addresses instead of several thousand) which means it is easier to whitelist them and manage them. This new CDN is in beta so those who wish to use it need to request eZoic's tech team switch them over to it. The new CDN is (touch wood) flawless.

**Comment by fevangelou** [comment]
@VR51 Appreciate it :)
