### ISSUE TITLE
cpanel nginx - engintron's future

### ISSUE THREAD

**Issue by zstergios** [engintron/engintron#1316]
Hi,
finaly cpanel launched nginx!

Do you plan to integrate your addon with default cpanel's-nginx?

https://docs.cpanel.net/knowledge-base/web-services/nginx-with-reverse-proxy/#the-nginx-installation

Would be great to have the logic of engitron with core solution.

**Comment by fevangelou** [comment]
cPanel's solution claims caching per user. This is not optimal and it's probably inline with what Plesk does (=pointless).

Engintron is the closest you get to the true Nginx build plus caching that actually works as it should.

There is no point in "integrating" anything.
