### ISSUE TITLE
OCSP with default_https.conf and https_vhosts.php

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1317]
Hey :)
I try to come back to your default and remove
the custom stuff I did over the years with Engintron.

I am trying to use only what your software has already. (defaults configuration)
one of the things is OCSP stapling.

I notice in default_https.conf and https_vhosts.php
have the option to uncomment 3 parts with OCSP (1 in the default file and 2 sections in the PHP file)

I uncomment all of them but is not working :/
https://www.ssllabs.com/ssltest/analyze.html?d=locksmithunit.com
____________

The test passing with OCSP only when I put this code inside the common_https file:
```
# OCSP Stapling
ssl_trusted_certificate /var/cpanel/ssl/cpanel/mycpanel.pem;
ssl_stapling on;
ssl_stapling_verify on;

# Google Public DNS (IPv4 only)
resolver                      8.8.8.8 8.8.4.4;
resolver_timeout                        10s;
```

**Originally, to be honest, I did this configuration:**

```

" .... your code is here.... inside common_https "
# HSTS Header / Preload ON | HSTS Before SSL / OCSP
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
#add_header Strict-Transport-Security "max-age=300; includeSubDomains; preload";

# Security Headers
add_header                     X-Frame-Options SAMEORIGIN;
add_header        X-XSS-Protection "1; mode=block" always;
add_header        X-Content-Type-Options "nosniff" always;

# Info
add_header        X-Nginx-Upstream-Cache-Status $upstream_cache_status;
add_header        X-Server-Powered-By "Locksmith Unit";

# OCSP Stapling
ssl_trusted_certificate /var/cpanel/ssl/cpanel/mycpanel.pem;
ssl_stapling on;
ssl_stapling_verify on;

# Google Public DNS (IPv4 only)
resolver                      8.8.8.8 8.8.4.4;
resolver_timeout                           10s;

# Set the port for HTTPS proxying
set $PROXY_TO_PORT 8443;

# Include common definitions and rules with HTTP
include common_http.conf;
```

________________________________

Now, I know you do not encourage/recommend to other people to put headers and change the files as I did...
So, I move all the headers to apache and now I try to use Engintron as his default (your default, without all the headers).

Currently now, common_https.conf is in his default configuration with intermedia support. (defaults of Engintron)
but as I told you, I uncomment the option for stapling (default_https.conf and https_vhosts.php)

**But OCSP stapling not working.**
Again, Engintron now on his defaults, all of him.
I only uncomment what Engintron offers to uncomment, code is already prepared, for example:
intermedia support SSL you wrote inside common_https ).

Have maybe a solution?
or any idea why OCSP working only inside common_https and not as Engintron offered?
(when I said "offered" i meant to default_https.conf and https_vhosts.php.)

Please Help :(

**Comment by fevangelou** [comment]
Yeah, it's not that simple. OCSP support requires additional configuration, it's not just a matter of uncommenting out these lines. The reason they're there is to assist folks who know how to enable OCSP stapling. That being said, you don't really need it.

**Comment by locksmithunit** [comment]
@fevangelou 

Can I use the OCSP stapling code i showed you with the extra google resolver inside https_common?

Sorry about the pressure, is important and google kind of force us to provide the response.

This the only way to get the OSCP response:
https://www.ssllabs.com/ssltest/analyze.html?d=locksmithunit.com
inside https_common (what i showed you message before this one, without all the headers).

Tell me only if is possible,
and if is possible with or without the extra google resolver?

BTW
I can put only the ocsp stapling code as you did in: 
default_https.conf 

I need your recommendation,
Is very important to google to get the ocsp response.

**Comment by fevangelou** [comment]
> Is very important to google to get the ocsp response.

No it isn't :)

As much as HSTS isn't. And a ton of other stuff.

Focus your efforts on other things. Perhaps PageSpeed scores if you're looking to improve your SEO rankings.

**Comment by locksmithunit** [comment]
Hey, thank you for your response.

@fevangelou 
I focus, believe me, you can scan all my sites in there, Yoast and Semrush, you will get 98 - 100 SEO score.

Algorithm is a big factor now in google,
all this response especially things connected to SSL can improve your ranking.

https://hstspreload.org/?domain=locksmithunit.es
https://hstspreload.org/?domain=locksmithunit.cat
https://hstspreload.org/?domain=locksmithunit.com

this site is recommended by google chrome (Google inc).

SSL lab is the number one tool for SSL (specified in Google Developers Docs):
https://www.ssllabs.com/ssltest/analyze.html?d=locksmithunit.com
https://www.ssllabs.com/ssltest/analyze.html?d=locksmithunit.es
https://www.ssllabs.com/ssltest/analyze.html?d=locksmithunit.cat

Google Mobile:
https://www.thinkwithgoogle.com/feature/testmysite/

PageSpeed get inside Google Search Console:
https://developers.google.com/speed/pagespeed/insights/?hl=en&utm_source=wmx&utm_campaign=wmx_otherlinks&url=https%3A%2F%2Flocksmithunit.com%2F

another one from google developers and Google docs recommended  for security headers,
This tool already recommended a couple of years:
https://www.webpagetest.org/result/210531_AiDcSG_8a9bcadfb8e659900b35388872e6f5c8/

Believe me, I work a lot of time on this issue,
Search Result response in Ranking with an improvement of the server.
( Speed, Policy, Resolvers of google/cloud flare - Data Centers close to the client with the IP of the country ).

google change the game, especially with all the GDPR and country blocking policies...
have countries google even demand the IP Range of the same state you targeting.

I already put the code as you see...
all the tools read the response.

this what I put in https_common in the end:

```
"Engintron HTTPS common.... (default code until here.)"

# OCSP Stapling
ssl_trusted_certificate /var/cpanel/ssl/cpanel/mycpanel.pem;
ssl_stapling on;
ssl_stapling_verify on;

# Google Public DNS (IPv4 only)
resolver                      8.8.8.8 8.8.4.4;

# Set the port for HTTPS proxying
set $PROXY_TO_PORT 8443;

# Include common definitions and rules with HTTP
include common_http.conf;

```

the only thing that is actually different from your "https_default" in "/etc/nginx/conf.d"
is the resolver, and OSCP certificate code in any vHost inside Engintron.

If I remove the resolver is very similar to your default (if you uncomment your OSCP stapling code inside HTTPS default).
