### ISSUE TITLE
[Coming Soon] Support for RHEL 8 variants (Rocky Linux, AlmaLinux and CloudLinux)

### ISSUE THREAD

**Issue by virtualos** [engintron/engintron#1318]
Hello,

I upgraded my vps from cloudlinux 7 to cloudlinux 8 then installed Engintron but I have no luck to update nginx from 1.14 to more recent versions as you offer in other topic, I have to say I tried some ways to manually install nginx but I encounter with Welcome to nginx page for all my customers account:
![11111](https://user-images.githubusercontent.com/62283634/118356139-1c026c80-b589-11eb-939b-dedbe57d466f.png)

I believe it's time for Engintron to officially support Centos 8 and Cloudlinux 8 and test against all bugs and limitations as we put centos6/7 cloudlinux 6/7 behind.

Right now I'm using cloudlinux 8 with cpanel 96 nginx cache(Uninstalled Engintron) but I prefer Engintron, hope you start to support centos/cloudlinux 8.

Thanks.

**Comment by Chipmank** [comment]
I've experienced the same issue on Almalinux 8.3. I've renamed html folder to get Engitron working.
But I think we need a proper solution.

**Comment by fevangelou** [comment]
Engintron does not support RHEL 8 variants at the moment. The next update will though...

**Comment by brinsleyparagao** [comment]
Its compatible with CentOS8 ( no stream ) ?

**Comment by fevangelou** [comment]
Engintron does not support RHEL 8 variants at the moment. The next update will though...

**Comment by CarlosLopezES** [comment]
+1 to support RHEL 8 on Engintron :)

I'm sorry to say this, but official Nginx manager it's garbage, too slow, zero configuration possibilities and no microcaching... the server works better without Nginx cPanel manager than with it.

**Comment by fevangelou** [comment]
Support for RHEL 8 variants will come early September with Engintron v2.

**Comment by imorandinwnp** [comment]
Hi @fevangelou 

Moving /usr/share/nginx/html to /usr/share/nginx/html.bak or deleting the folder seems to solve the problem.
Apart from this, is Engintron 100% working with RHEL 8 variants or is there any other reported issue?

Thanks

**Comment by virtualos** [comment]
> 
> 
> Hi @fevangelou
> 
> Moving /usr/share/nginx/html to /usr/share/nginx/html.bak or deleting the folder seems to solve the problem.
> Apart from this, is Engintron 100% working with RHEL 8 variants or is there any other reported issue?
> 
> Thanks

one issue I know is not possible to update Nginx to more recent version like v1.21.x and it stick to v1.14

**Comment by imorandinwnp** [comment]
Thanks @virtualos

**Comment by imorandinwnp** [comment]
I realized that deleting/renaming /usr/share/nginx/html is not the best option as it gets recreated when cpanel or nginx updates, so instead I did this:

Replace this line on file /etc/nginx/common_http.conf:

```
location / {
    try_files $uri $uri/ @backend;
}
```

with this one:

```
location / {
        try_files /dev/null @backend;
}
```

and this seems to solve the problem permanently (unless you update engintron, in that case you have to do the change again).

Credits: https://serverfault.com/questions/908086/nginx-directly-send-from-location-to-another-named-location

Ignacio

**Comment by fevangelou** [comment]
@imorandinwnp I would not recommend this.

@all The installer needs reworking. Nginx's configs don't. This will be solved (as I stated already) pretty soon with v2 of Engintron.

**Comment by amanullahtanweer** [comment]
Moving the HTML folders works for me as well so far no other issues

**Comment by tanero** [comment]
+1 for AlmaLinux support, would be great.

**Comment by JohnTrabusca** [comment]
@fevangelou Any ETA on Engintron v2 with a fix for this issue ? Thank you for the excellent plugin

**Comment by fevangelou** [comment]
I'm currently finalizing the installer on Almalinux 8.5 and then will test it on Rocky Linux and CentOS 8 (for those who may stick around with it a bit longer). The new version will be launched in about 10 days from now, just before Christmas.

**Comment by JohnTrabusca** [comment]
@fevangelou Excellent Thank you for the fast reply

**Comment by fevangelou** [comment]
Almalinux testing is now completed. Working on Rocky Linux & CentOS 8 (for those already on that & who won't have time to update soon to Almalinux or Rocky Linux). Once v2 of Engintron is released, Ubuntu follows :)

**Comment by fevangelou** [comment]
Sneak preview for v2.0 :)

Coming out really, really soon!

<img width="1440" alt="engintron_v2 0_s1" src="https://user-images.githubusercontent.com/1301787/147854409-a6d7a796-888a-4b94-adc2-b64589790bc3.png">
<img width="1440" alt="engintron_v2 0_s2" src="https://user-images.githubusercontent.com/1301787/147854412-d6376075-2eaf-4ae2-b296-6d973bfe9311.png">

**Comment by CarlosLopezES** [comment]
Thank you!!! Looks promising!

**Comment by fevangelou** [comment]
Engintron v2.0 is now released https://engintron.com/docs/#/pages/Changelog so I'm closing this issue.

Enjoy!

**Comment by mblendinger** [comment]
v2.1 and Almalinux, show the default welcome to cloudlinux nginx page.

**Comment by zGansalloz** [comment]
Поддерживаю. Проблема не решена.
