### ISSUE TITLE
How can hide Interface Analytics popup

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#1320]
@fevangelou How can hide Interface Analytics popup? This only appear in engintron plugin page.

![ScreenShot00262](https://user-images.githubusercontent.com/6899856/118950669-b2a0a600-b95a-11eb-8a5e-40367015f583.png)

**Comment by bosen** [comment]
https://docs.cpanel.net/knowledge-base/cpanel-product/cpanel-analytics/ ?

**Comment by fevangelou** [comment]
The analytics slide-in as well as the broken sidemenu are bugs in cPanel's UI for PHP based plugins. Direct your question to cPanel please.

**Comment by atifone** [comment]
@fevangelou , @Nirjonadda

Fix Cannot set properties of null & Interface Analytics slide out container
file: engintron.php 
replace line : 

`el.querySelector('#PluginsContent li[searchtext*="Engintron"]').className = 'highlighted activePage';`

with: 

```
if (el.querySelector('#PluginsContent li[searchtext*="Engintron"]')) {
  el.querySelector('#PluginsContent li[searchtext*="Engintron"]').className = 'highlighted activePage';
}
```

**Comment by fevangelou** [comment]
Resolved in https://github.com/engintron/engintron/commit/07382adcc37f4ff84b0db995948596c94bd206d6
