### ISSUE TITLE
Nginx restart fails due to "start request repeated too quickly for nginx.service"

### ISSUE THREAD

**Issue by TommyChris** [engintron/engintron#1322]
Maybe I misconfigured something, but after updating to 1.15, I realized the following situation.

If I click on "Restart" or "Force restart" or "Purge ..." buttons, the browser goes to wsod. I had to ssh into the server and manually restart nginx service (service nginx restart).

I investigated the problem, and it is occures beacuse shell_exec("service nginx restart") kills the current connection to the browser. The browser (Chrome) tries to reload the same page (engintron.php?op=nginx_purgelogs), which do the same again - and again - and again (load the page, clear the cache, restart nginx, kills current connection). This happens until the OS rate limit hit, and finally, the OS prohibits the restart.

After it, I had to manually (re)start Nginx using ssh console.

The Nginx log:

```
systemd[1]: Stopping nginx - high performance web server...
systemd[1]: Stopped nginx - high performance web server.
systemd[1]: Starting nginx - high performance web server...
systemd[1]: Started nginx - high performance web server.
systemd[1]: Stopping nginx - high performance web server...
systemd[1]: Stopped nginx - high performance web server.
systemd[1]: Starting nginx - high performance web server...
systemd[1]: Started nginx - high performance web server.
systemd[1]: Stopping nginx - high performance web server...
systemd[1]: Stopped nginx - high performance web server.
systemd[1]: Starting nginx - high performance web server...
systemd[1]: Started nginx - high performance web server.
systemd[1]: Stopping nginx - high performance web server...
systemd[1]: Stopped nginx - high performance web server.
systemd[1]: Starting nginx - high performance web server...
systemd[1]: Started nginx - high performance web server.
systemd[1]: Stopping nginx - high performance web server...
systemd[1]: Stopped nginx - high performance web server.
systemd[1]: start request repeated too quickly for nginx.service
systemd[1]: Failed to start nginx - high performance web server.
systemd[1]: Unit nginx.service entered failed state.
```

I made a little modification in engintron.php. With this modifications, restarting nginx is happens in a seperate subshell. I think there are much more better solutions, that's all I can do:

```
case "nginx_restart":
         $ret = "<b>Restarting Nginx...</b><br />";
-        $ret .= shell_exec("service nginx restart");
+        shell_exec('/bin/bash -c "' . addslashes('service nginx restart &> /dev/null &') . '"');
        break;
```

```
case "nginx_purgelogs":
+        $ret = "<b>Purging logs...</b><br />";
+        shell_exec('/bin/bash -c "' . addslashes('/usr/local/src/engintron/engintron.sh purgelogs &> /dev/null &') . '"');
-        $ret = shell_exec("bash /usr/local/src/engintron/engintron.sh purgelogs");
-        $ret .= shell_exec("service nginx restart");
        break;
```

```
case "nginx_purgecache":
+        $ret = "<b>Purging cache...</b><br />";
+        shell_exec('/bin/bash -c "' . addslashes('/usr/local/src/engintron/engintron.sh purgecache &> /dev/null &') . '"');
-        $ret = shell_exec("bash /usr/local/src/engintron/engintron.sh purgecache");
-        $ret .= shell_exec('/bin/bash -c "' . addslashes('service nginx restart &> /dev/null &') . '"');
        break;
```

I can't do the force restart part. Sorry :(

**Comment by itsTheFae** [comment]
For what it's worth, I'm using the same version `1.15.0` and also using Chrome often to work with WHM.  I have not had this issue.  
If I recall correctly, cpanel/WHM connections are served by a separate server process, not attached to or depending on Apache or nginx.   So the issue you're having is more complicated than just a problem with Engintron, I think..

**Comment by fevangelou** [comment]
@TommyChris WHM runs on its own web server, not Nginx, nor Apache. It's most likely the browser page dies because the purge command generates a huge amount of HTML content to list. I know it's not the most optimal way to present data, but your case is an edge case really. If you need to perform any tasks that are heavy for the Engintron UI, simply use the terminal. Run `/engintron.sh --help` to explore all available options to you.
