### ISSUE TITLE
resolver from the hosting company and engintron resolver.

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1324]
Hey how are you @fevangelou 
so I notice in my cPanel when the hosting provider set up cPanel, they put the IP resolver of the hosting:
https://ibb.co/Y2qggnJ

as you see the third resolver is 1.1.1.1

I know is belongs to cloud flare IPv4.

recommended to use it in Engintron (nginx.conf)?

or is ok to stay with google resolver IPv4? (8.8.8.8)

AND THE MOST IMPORTANT.

if I need to specify in "costume rules" in Engintron interface my shared IP? 
I have 1 Sheard IP to all my 3 sites...

**Comment by fevangelou** [comment]
a) Doesn't matter. Leave Engintron's config as-is.

b) Custom rules already provide detailed explanations on how to use that file. Have a look at the Engintron docs as well for additional help.

**Comment by locksmithunit** [comment]
I know how to specify the IP I have the URL:
https://engintron.com/docs/#/pages/Engintron-&-the-%22Custom-Rules%22-file-(for-Nginx)

but if I need that? or keep everything like that?
I suspect the host use cloud flare... sometimes get an error in the log with the IP something like that:
23.235.206.148:8080 error connection or something like that.

I think is because the domain name not get resolved,
I suspect they use cloud flare.

have a way to check it?
Maybe a tool?
(I afraid to specify the IP in Custom Rules config and this not actually needed).

**Comment by itsTheFae** [comment]
It is never really a good idea to use a public resolver on an internal proxy.  Using public resolvers can be much slower and less secure than using host-provided or internally curated services such as dnsmasq or systemd's resolver.  Using a resolver on an internal proxy opens your nginx to abuse as a relay or open proxy.   Because the `Host` header cannot be implicitly trusted... 

You can find out if a domain is using CloudFlare by using `dig` for the SOA records. (If you don't know what `dig` is, google it, and consider using: https://www.digwebinterface.com/ ) 
 
Realistically you should deny all requests for hosts that your Apache server isn't configured to serve.  If your cpanel has a local resolver, you should use that first before using others.  Avoiding public resolvers if you don't need them.  Engintron uses a pretty wide default configuration, and needs to be manually customized and locked down according to your needs.  If that isn't your thing, you might fair better using cPanel's recent official nginx supporting packages, if your instance is up-to-date enough to use it.

**Comment by locksmithunit** [comment]
is not so true what you said, this because the Nginx resolver is respecting other resolvers (cPanel WHM resolver), and you have the hosting resolvers inside /etc/resolve.conf (the resolvers of the hosting).

It means Google Resolver gets the option to resolve after the resolver of the hosting and your internal resolver work with Apache...
so you little wrong.

I was thinking like you before a year ago, I put 127.0,0,0 but I figure out the default of @fevangelou  is the best configuration
with any cPanel...

this guy is genius bro... hahaha really I redesigned Engintron 1000 times...
and I did a lot of mistakes with the years... (like internal resolver).
I got burn... a lot.

This why I asking him from now and on in everything I do.
He knows the best... i tell you. (I can tell you, today I work on the Engintron Default, much better result).

**Comment by itsTheFae** [comment]
If you specify your local resolver first, in the list of resolvers.   Nginx will use those listed in the order they are listed until one returns a result.  Many local resolvers defer to others that have been configured in the system, correct.  
The point remains that the default configurations allow for abuse of service by spoofing the host header in requests.   Engintron's default config will place the domain given in the Host header directly into the proxy pass which will attempt to resolve the domain name and make a connection using your system.
Regardless of if the target system has ports 8080 or 8443 open, the socket will be attempted and a denial of service or generic proxy attack can be carried out on or via your service.

**Comment by locksmithunit** [comment]
regardless if you use cPanel you use DNS Resolving.
no matter what you will do, all cPanel design this way...

you can go to the WHM>TWAEK
you will see you have a resolver every 10 sec on the resolver of Engintron.
is means all of them working because in Engintron @fevangelou didn't put resolver_timeout.

so the resolver is open with all the resolvers together...
Nginx has a resolver from his own, when apache resolver works every 10 sec.

btw Engintron utilities cron based on this Apache resolver in WHM>TWAEK.

I tell you... this guy is a genius...
where you will try to improve Engintron you understand this guy... is a genius.

Recommended to you read his docs.
you understand this guy has years of experience...
especially with cPanel.

**Comment by itsTheFae** [comment]
You are missing the point.

**Comment by locksmithunit** [comment]
I am not, I know what you talking about. (I got you, bro)
But you wrong, is not true.

if you will investigate the Engintron software more, and you understand you not right.

**Comment by locksmithunit** [comment]
@fevangelou thank you for your response.
but I really don't know if they use Cloudflare.

when I do "dig" it shows the resolver of Nginx.
(google public resolver)

but under the scan, I don't know if they use Cloudflare.
this why I ask you.
if have how to check it?
