### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by samuelmartinez** [engintron/engintron#1325]
Hi,
I want to activate CORS per domain /vhost.
 It is possible with Engintron?

**Comment by fevangelou** [comment]
You don't provide much context, but what you want can be achieved either in code (send the right HTTP headers) or through .htaccess files.

**Comment by locksmithunit** [comment]
i put this inside any .htaccess of any of my sites:
```
###############################################################################
# Activate CORS                                                  
###############################################################################
<IfModule mod_headers.c>
    <FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|font.css|css|js|gif|png|jpe?g|svg|svgz|ico|webp|mp3|mp4)$">
        Header set Access-Control-Allow-Origin "*"
    </FilesMatch>
</IfModule>
```

hope this is helpful.
you can put it throw Engintron as well, but I prefer to keep the default of @fevangelou as it is.

**Comment by locksmithunit** [comment]
@samuelmartinez you can put this too:
```
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*" 
</IfModule>
```

but is can be a little risky, is depend if you redirect your subdomains
