### ISSUE TITLE
x-nginx-upstream-cache-status: BYPASS

### ISSUE THREAD

**Issue by pyxage** [engintron/engintron#1328]
Hi team,

No matter what I set and do... I don't get a HIT on my cache... I get Expired and Bypass most of the time.
Can anyone please help me? 

Centos 8, WHM, latest Engintron installed fresh

**Comment by pyxage** [comment]
I get MISS as well as per gtmetrix results...

**Comment by fevangelou** [comment]
First off, Nginx does micro-caching. That's a 1 sec cache. And it works magic when you have lots of concurrent connections. But it's difficult to spot manually. If you really need to do caching right (and longer), you should configure a cache-control header in your site for dynamic content (=the rendered HTML).

**Comment by locksmithunit** [comment]
@pyxage
is apache,
you use expire in apache right?

if you do it is very dangerous, don't use it together with Nginx.

the reason you get miss is that you expire HTML is on 0 inside apache.
I recommended not to use expires in apache and Nginx...
I actually open a topic but not on expires, on all apache headers, and deflet:
https://github.com/engintron/engintron/issues/1327
