### ISSUE TITLE
DNS cPanel with Engintron? 3600 Default (included SOA) or 86400?

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1329]
Hello @fevangelou 
I Know i open a lot of topics.
is because I try not to mix subjects and understanding the best way Engintron will be compiled with cPanel.

So...
I notice engintron HTTPS_COMMON has 24 hours cache + 50m of shared caching.

I believe is a kind of technique with the default DNS from cPanel.
but is wired... why? cPanel recommendation and even the Basic config, Design for 86400.
but when you in WHM you see cPanel create different default of 3600. (1hour)

I believe has a technique between the 50m to the 3600 of the cPanel DNS.

I want to ask you to be sure what is better with Engintron?
full static of 24 hours in cPanel DNS and Engintron.

or kind of Infiniti loop (50m and 1hour)?

Again, sorry for all the posts.
I try to understand the software much deeper and compile it properly.

**Comment by fevangelou** [comment]
Well, read a book about Nginx man. I really can't respond to your knowledge-seeking questions.

**Comment by locksmithunit** [comment]
are you kidding right?
you build something to optimize cPanel, your Nginx is not regular Nginx...
is ok I got you, never mind.
