### ISSUE TITLE
Dynamic Cache Sessions

### ISSUE THREAD

**Issue by BomBom123** [engintron/engintron#133]
Had to disable the dynamic cache recently as for some forum softwares there were issues where users were logged in as others and all sorts more.

Is there a way to fix this issue?

**Comment by fevangelou** [comment]
Did you use the default 1 sec micro-cache time or a longer time?

**Comment by BomBom123** [comment]
Used the 1 second micro-cache without any changes.

**Comment by fevangelou** [comment]
Even if the users "saw" the username of someone else, they were never logged in as someone else. Have you made sure there is no other type of caching layer in between? In other words, by disabling micro-caching, have you made sure the issues you originally described are indeed solved?

And I'll see if I can find a way to exclude micro-caching per domain only.

**Comment by BomBom123** [comment]
I have indeed checked and the issues don't exist once the micro caching is off but it is worrying since i had some people that were showing logged in as an admin when they weren't and as that admin was browsing some admin pages, other people were also able to see them pages which is even more worrying!

**Comment by SoGooDFR** [comment]
I've the same problem with Symfony 3.0. Please correct this.

**Comment by SoGooDFR** [comment]
In proxy_params_dynamic, why in ignore_headers you set cookie ? **Is very dangerous** !

`proxy_ignore_headers		Expires Cache-Control **Set-Cookie** Vary;`

**Comment by BomBom123** [comment]
I'd love to have this feature usable as theres a great performance boost but it does seem a lot of sites don't like it what so ever, constant complaints of being signed in as other users, pages not showing the correct permissions.

**Comment by SoGooDFR** [comment]
Look this configuration : https://www.howtoforge.com/why-you-should-always-use-nginx-with-microcaching

**Comment by fevangelou** [comment]
@SoGooDFR If you remove Set-Cookie, then there will be no caching is CMSs or apps where a session cookie is used, even for guests (see Joomla, SMF and more many more). If you don't use a session cookie for guests, then yes, you can safely remove this header from the "proxy_ignore_headers" option.

@BomBom123 You can try what I suggested to @SoGooDFR if your CMS or app does not use session cookies for guests. But if it does, you cache will fill up with a unique entry for each guest, which entirely beats the advantage of caching.

**Comment by kuteninja** [comment]
Hello, sorry for getting this thread back to life, but I happened to find the same issue with the Moodle software, and the only way to fix it was to remove the Set-Cookie from the ignore headers as @SoGooDFR said.

In cases when I was logged in with cookies ("remember me" checked), then somebody else logged in at almost the same time that I updated the homepage, I've been able to view that page as if I was that same user. 

Despite I not being logged in as him, I was able view stuff that I shouldn't have, breaking the privacy policies of the website and also getting around read privileges for some documents.

Perhaps it's more friendly if you disable Set-Cookie by default, and leave a comment explaining this issue, if somebody wants to change it, they must be certain that they're not using cookie authentication.

**Comment by fevangelou** [comment]
@kuteninja I've already replied above...

> If you remove Set-Cookie, then there will be no caching is CMSs or apps where a session cookie is used, even for guests (see Joomla, SMF and more many more). If you don't use a session cookie for guests, then yes, you can safely remove this header from the "proxy_ignore_headers" option.

**Comment by kuteninja** [comment]
@fevangelou I understand the guest cache issue, do you understand that I'm talking about something else?

If you cache the websites with cookies, then ignore them from the request, you don't pass the cookie to the user which is Ok... although you DO cache the common top-bar where it says "you're logged in as..." as well as dynamic websites like the the profile page (where you can see the email address and some more private information), any credit card info page (for the last user that logged in and viewed it after the caché got cleared) and thus you make that information viewable to anyone for one minute or more (it refreshes with any other request).

It's an issue bigger than just caching the guest users, I rather NOT cache the guest ones, if that forces me to cache the logged in ones as well. Most CMS apps do use cookies for both logged in and guest users (primarily the PHPSESSID, and maybe some ad-related stuff), so it's not safe to cache those websites by default, you should leave that setting commented with a warning to only apply it if you know what you're doing.

**Comment by fevangelou** [comment]
@kuteninja That's why the "middle ground" is a micro-cache of 1 sec. If you remove Set-Cookie as mentioned above and you have sites with guest sessions cookies (ad related stuff don't matter here), then you will get zero benefits from caching when traffic spikes hit you. The best approach is to identify when a user is logged in and in that case, entirely switch the cache off. Such recommendations e.g. for Joomla or WordPress will be part of v1.8.0 of Engintron (if not earlier).

**Comment by kuteninja** [comment]
Is there a blog or twitter feed for Enginetron (or yourself) that I can subscribe/follow in order to find out when the new version will be released?

**Comment by fevangelou** [comment]
If you have installed Engintron already, you'll see the links to all 3 
major social networks (Twitter, FB & G+) right below the left sidebar, 
in the WHM app. Pick the one(s) you like to get updates.

A blog will open at some point along with the new Engintron site.

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com
