### ISSUE TITLE
Nginx Issue (Solved)

### ISSUE THREAD

**Issue by Sherbi** [engintron/engintron#1333]
Today I got issue on my nxinx is go down & traffic to  
Welcome to CloudLinux
CloudLinux is the only commercially supported OS designed specifically for the service provider market. CloudLinux s drived from sources freely provided to the public by a prominent North American Enterprise Linux vendor.

CloudLinux has following advantages:

    Resource isolation via lightweight virtual environmentsâ„  (LVEs)
    LVEs prevent individual websites from using too many resources
    LVEs provide better security and protect the server from issues that drain resources for other tenants.
    Single website cannot overload the server
    Allows you to fit more sites on one server
    Lowers risk, increases efficiency and improves server performance

when I see the error log I found that :

2021/06/18 14:49:02 [emerg] 1379408#1379408: bind() to [::]:80 failed (98: Address already in use)
2021/06/18 14:49:02 [emerg] 1379408#1379408: bind() to [::]:443 failed (98: Address already in use)
2021/06/18 14:49:02 [emerg] 1379408#1379408: bind() to [::]:80 failed (98: Address already in use)
2021/06/18 14:49:02 [emerg] 1379408#1379408: bind() to [::]:443 failed (98: Address already in use)
2021/06/18 14:49:02 [emerg] 1379408#1379408: bind() to [::]:80 failed (98: Address already in use)
2021/06/18 14:49:02 [emerg] 1379408#1379408: bind() to [::]:443 failed (98: Address already in use)
2021/06/18 14:49:02 [emerg] 1379408#1379408: bind() to [::]:80 failed (98: Address already in use)
2021/06/18 14:49:02 [emerg] 1379408#1379408: bind() to [::]:443 failed (98: Address already in use)
2021/06/18 14:49:02 [emerg] 1379408#1379408: bind() to [::]:80 failed (98: Address already in use)
2021/06/18 14:49:02 [emerg] 1379408#1379408: bind() to [::]:443 failed (98: Address already in use)
2021/06/18 14:49:02 [emerg] 1379408#1379408: still could not bind()
2021/06/18 14:49:05 [emerg] 1379556#1379556: bind() to [::]:80 failed (98: Address already in use)
2021/06/18 14:49:05 [emerg] 1379556#1379556: bind() to [::]:443 failed (98: Address already in use)
2021/06/18 14:49:06 [error] 1379651#1379651: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:194.71.211.96, server: localhost, request: "GET /robots.txt HTTP/1.1", upstream: "http://85.10.200.69:8080/robots.txt", host: "al3asmaalyoum.com"
2021/06/18 14:49:16 [error] 1379649#1379649: *28 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: ::ffff:66.249.70.4, server: localhost, request: "GET /%D9%84%D9%85%D8%A7%D8%B0%D8%A7-%D8%AA%D8%B9%D8%A7%D9%86%D9%89-%D8%A3%D9%86%D8%AC%D9%84%D9%8A%D9%86%D8%A7-%D8%AC%D9%88%D9%84%D9%8A-%D9%85%D9%86-%D8%A7%D9%84%D9%86%D8%AD%D8%A7%D9%81%D8%A9-%D8%A7%D9%84/ HTTP/1.1", upstream: "https://85.10.200.69:8443/%D9%84%D9%85%D8%A7%D8%B0%D8%A7-%D8%AA%D8%B9%D8%A7%D9%86%D9%89-%D8%A3%D9%86%D8%AC%D9%84%D9%8A%D9%86%D8%A7-%D8%AC%D9%88%D9%84%D9%8A-%D9%85%D9%86-%D8%A7%D9%84%D9%86%D8%AD%D8%A7%D9%81%D8%A9-%D8%A7%D9%84/", host: "sehrayamag.com"
2021/06/18 14:49:16 [error] 1379651#1379651: *40 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: ::ffff:216.244.66.236, server: localhost, request: "GET /tag/%D8%A2%D8%AB%D8%A7%D8%B1-%D8%A7%D9%84%D8%AC%D8%B1%D9%88%D8%AD-%D8%A7%D9%84%D9%82%D8%AF%D9%8A%D9%85%D8%A9/ HTTP/1.1", upstream: "https://85.10.200.69:8443/tag/%D8%A2%D8%AB%D8%A7%D8%B1-%D8%A7%D9%84%D8%AC%D8%B1%D9%88%D8%AD-%D8%A7%D9%84%D9%82%D8%AF%D9%8A%D9%85%D8%A9/", host: "sehrayamag.com"
2021/06/18 14:49:16 [error] 1379645#1379645: *55 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: ::ffff:35.230.176.58, server: localhost, request: "POST /wp-login.php HTTP/1.1", upstream: "https://85.10.200.69:8443/wp-login.php", host: "gibq-eg.com"
2021/06/18 14:49:16 [error] 1379646#1379646: *41 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: ::ffff:188.165.135.204, server: localhost, request: "POST /wp-login.php HTTP/1.1", upstream: "https://85.10.200.69:8443/wp-login.php", host: "vacant-jobs.net"
2021/06/18 14:49:16 [error] 1379649#1379649: *42 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: ::ffff:157.55.39.96, server: localhost, request: "GET /%d8%a2%d9%8a%d8%b4%d9%88%d8%a7%d8%b1%d9%8a%d8%a7-%d8%b1%d8%a7%d9%89-%d8%aa%d8%b9%d8%a8%d8%b1-%d8%b9%d9%86-%d8%a5%d9%85%d8%aa%d9%86%d8%a7%d9%86%d9%87%d8%a7-%d9%84%d8%ac%d9%85%d9%87%d9%88%d8%b1%d9%87/ HTTP/2.0", upstream: "https://85.10.200.69:8443/%d8%a2%d9%8a%d8%b4%d9%88%d8%a7%d8%b1%d9%8a%d8%a7-%d8%b1%d8%a7%d9%89-%d8%aa%d8%b9%d8%a8%d8%b1-%d8%b9%d9%86-%d8%a5%d9%85%d8%aa%d9%86%d8%a7%d9%86%d9%87%d8%a7-%d9%84%d8%ac%d9%85%d9%87%d9%88%d8%b1%d9%87/", host: "liveegy.com"
2021/06/18 14:49:16 [error] 1379645#1379645: *68 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: ::ffff:40.77.167.10, server: localhost, request: "GET /%C3%98%C2%A3%C3%98%C2%B3%C3%98%C2%B9%C3%98%C2%A7%C3%98%C2%B1-%C3%98%C2%A7%C3%99%E2%80%9E%C3%98%C2%B0%C3%99%E2%80%A1%C3%98%C2%A8-%C3%99%E2%80%9E%C3%98%C2%A7%C3%99%C5%A0%C3%99%C2%81-%C3%98%C2%A7%C3%99%E2%80%9E%C3%99%C5%A0%C3%99%CB%86%C3%99%E2%80%A6-%C3%98%C2%A7%C3%99%E2%80%9E%C3%98%C2%AB%C3%99%E2%80%9E%C3%98%C2%A7%C3%98%C2%AB%C3%98%C2%A7%C3%98%C2%A1-25-%C3%99%E2%80%A6%C3%98%C2%A7%C3%99%C5%A0%C3%99%CB%86-2021 HTTP/2.0", upstream: "https://85.10.200.69:8443/%C3%98%C2%A3%C3%98%C2%B3%C3%98%C2%B9%C3%98%C2%A7%C3%98%C2%B1-%C3%98%C2%A7%C3%99%E2%80%9E%C3%98%C2%B0%C3%99%E2%80%A1%C3%98%C2%A8-%C3%99%E2%80%9E%C3%98%C2%A7%C3%99%C5%A0%C3%99%C2%81-%C3%98%C2%A7%C3%99%E2%80%9E%C3%99%C5%A0%C3%99%CB%86%C3%99%E2%80%A6-%C3%98%C2%A7%C3%99%E2%80%9E%C3%98%C2%AB%C3%99%E2%80%9E%C3%98%C2%A7%C3%98%C2%AB%C3%98%C2%A7%C3%98%C2%A1-25-%C3%99%E2%80%A6%C3%98%C2%A7%C3%99%C5%A0%C3%99%CB%86-2021", host: "liveegy.com"
2021/06/18 14:49:16 [error] 1379646#1379646: *78 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: ::ffff:114.119.142.183, server: localhost, request: "GET /wp-content/uploads/2020/07/202007211245494549-780x405-1.jpg?is-pending-load=1 HTTP/1.1", upstream: "https://85.10.200.69:8443/wp-content/uploads/2020/07/202007211245494549-780x405-1.jpg?is-pending-load=1", host: "sehrayamag.com"
2021/06/18 14:49:16 [error] 1379645#1379645: *73 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: ::ffff:62.210.78.76, server: localhost, request: "GET /sex-hookups-near-me/ HTTP/1.1", upstream: "https://85.10.200.69:8443/sex-hookups-near-me/", host: "agsksa.com"
2021/06/18 14:49:16 [error] 1379649#1379649: *9 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:41.43.9.21, server: localhost, request: "GET /robots.txt HTTP/1.1", upstream: "http://85.10.200.69:8080/robots.txt", host: "octobermageg.com"
2021/06/18 14:49:16 [error] 1379645#1379645: *76 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: ::ffff:114.119.152.59, server: localhost, request: "GET /wp-content/uploads/2018/10/0-3.jpg%20600w,%20https:/sehrayamag.com/wp-content/uploads/2018/10/0-3-300x200.jpg%20300w HTTP/1.1", upstream: "https://85.10.200.69:8443/wp-content/uploads/2018/10/0-3.jpg%20600w,%20https:/sehrayamag.com/wp-content/uploads/2018/10/0-3-300x200.jpg%20300w", host: "sehrayamag.com"
2021/06/18 14:49:16 [error] 1379650#1379650: *11 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:41.43.9.21, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://85.10.200.69:8080/favicon.ico", host: "octobermageg.com", referrer: "http://octobermageg.com/"
2021/06/18 14:49:16 [error] 1379649#1379649: *31 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:102.164.99.87, server: localhost, request: "GET /%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%AD%D8%B0%D9%81-%D8%AC%D9%85%D9%8A%D8%B9-%D8%B1%D8%B3%D8%A7%D8%A6%D9%84-%D8%A7%D9%84%D9%81%D9%8A%D8%B3-%D8%A8%D9%88%D9%83-%D8%AF%D9%81%D8%B9%D8%A9-%D9%88%D8%A7%D8%AD/ HTTP/1.1", upstream: "http://85.10.200.69:8080/%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%AD%D8%B0%D9%81-%D8%AC%D9%85%D9%8A%D8%B9-%D8%B1%D8%B3%D8%A7%D8%A6%D9%84-%D8%A7%D9%84%D9%81%D9%8A%D8%B3-%D8%A8%D9%88%D9%83-%D8%AF%D9%81%D8%B9%D8%A9-%D9%88%D8%A7%D8%AD/", host: "monw3at.com", referrer: "http://m.facebook.com/"
2021/06/18 14:49:16 [error] 1379649#1379649: *47 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:54.69.94.50, server: localhost, request: "GET /robots.txt HTTP/1.1", upstream: "http://85.10.200.69:8080/robots.txt", host: "akhbarelsyaha.com"
2021/06/18 14:49:16 [error] 1379650#1379650: *29 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:51.15.19.181, server: localhost, request: "GET /%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%B1%D8%A8%D8%AD-20-%D8%AF%D9%88%D9%84%D8%A7%D8%B1-%D9%8A%D9%88%D9%85%D9%8A%D8%A7%D9%8B-%D9%85%D9%86-%D8%AC%D9%88%D8%AC%D9%84-%D8%A8%D8%A7%D9%84%D8%AE%D8%B7%D9%88/ HTTP/1.1", upstream: "http://85.10.200.69:8080/%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%B1%D8%A8%D8%AD-20-%D8%AF%D9%88%D9%84%D8%A7%D8%B1-%D9%8A%D9%88%D9%85%D9%8A%D8%A7%D9%8B-%D9%85%D9%86-%D8%AC%D9%88%D8%AC%D9%84-%D8%A8%D8%A7%D9%84%D8%AE%D8%B7%D9%88/", host: "monw3at.com"
2021/06/18 14:49:16 [error] 1379645#1379645: *17 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:197.9.238.46, server: localhost, request: "GET /wp-includes/js/comment-reply.min.js?ver=5.2.11 HTTP/1.1", subrequest: "/wp-includes/js/comment-reply.min.js", upstream: "http://85.10.200.69:8080/wp-includes/js/comment-reply.min.js?ver=5.2.11", host: "monw3at.com", referrer: "http://monw3at.com/%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%AD%D8%B0%D9%81-%D8%AC%D9%85%D9%8A%D8%B9-%D8%B1%D8%B3%D8%A7%D8%A6%D9%84-%D8%A7%D9%84%D9%81%D9%8A%D8%B3-%D8%A8%D9%88%D9%83-%D8%AF%D9%81%D8%B9%D8%A9-%D9%88%D8%A7%D8%AD/"
2021/06/18 14:49:16 [error] 1379652#1379652: *21 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:197.9.238.46, server: localhost, request: "GET /wp-content/themes/monw3at/js/plugins.js?ver=1.0 HTTP/1.1", subrequest: "/wp-content/themes/monw3at/js/plugins.js", upstream: "http://85.10.200.69:8080/wp-content/themes/monw3at/js/plugins.js?ver=1.0", host: "monw3at.com", referrer: "http://monw3at.com/%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%AD%D8%B0%D9%81-%D8%AC%D9%85%D9%8A%D8%B9-%D8%B1%D8%B3%D8%A7%D8%A6%D9%84-%D8%A7%D9%84%D9%81%D9%8A%D8%B3-%D8%A8%D9%88%D9%83-%D8%AF%D9%81%D8%B9%D8%A9-%D9%88%D8%A7%D8%AD/"
2021/06/18 14:49:16 [error] 1379646#1379646: *20 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:197.9.238.46, server: localhost, request: "GET /wp-content/plugins/contact-form-7/includes/js/scripts.js?ver=5.1.4 HTTP/1.1", subrequest: "/wp-content/plugins/contact-form-7/includes/js/scripts.js", upstream: "http://85.10.200.69:8080/wp-content/plugins/contact-form-7/includes/js/scripts.js?ver=5.1.4", host: "monw3at.com", referrer: "http://monw3at.com/%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%AD%D8%B0%D9%81-%D8%AC%D9%85%D9%8A%D8%B9-%D8%B1%D8%B3%D8%A7%D8%A6%D9%84-%D8%A7%D9%84%D9%81%D9%8A%D8%B3-%D8%A8%D9%88%D9%83-%D8%AF%D9%81%D8%B9%D8%A9-%D9%88%D8%A7%D8%AD/"
2021/06/18 14:49:16 [error] 1379645#1379645: *36 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:51.89.155.27, server: localhost, request: "GET /%D8%A3%D9%81%D8%B6%D9%84-%D8%AA%D8%B7%D8%A8%D9%8A%D9%82-%D9%84%D9%85%D8%B9%D8%B1%D9%81%D8%A9-%D8%A8%D9%8A%D8%A7%D9%86%D8%A7%D8%AA-%D9%85%D9%86-%D9%8A%D8%AA%D8%B5%D9%84-%D8%A8%D9%83-%D8%AD%D8%AA HTTP/1.1", upstream: "http://85.10.200.69:8080/%D8%A3%D9%81%D8%B6%D9%84-%D8%AA%D8%B7%D8%A8%D9%8A%D9%82-%D9%84%D9%85%D8%B9%D8%B1%D9%81%D8%A9-%D8%A8%D9%8A%D8%A7%D9%86%D8%A7%D8%AA-%D9%85%D9%86-%D9%8A%D8%AA%D8%B5%D9%84-%D8%A8%D9%83-%D8%AD%D8%AA", host: "monw3at.com"
2021/06/18 14:49:16 [error] 1379650#1379650: *19 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:197.9.238.46, server: localhost, request: "GET /wp-content/themes/monw3at/images/bg.jpg HTTP/1.1", subrequest: "/wp-content/themes/monw3at/images/bg.jpg", upstream: "http://85.10.200.69:8080/wp-content/themes/monw3at/images/bg.jpg", host: "monw3at.com", referrer: "http://monw3at.com/wp-content/themes/monw3at/css/main.css?ver=5.2.11"
2021/06/18 14:49:16 [error] 1379646#1379646: *23 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:197.9.238.46, server: localhost, request: "GET /wp-content/themes/monw3at/js/main.js?ver=1.0 HTTP/1.1", subrequest: "/wp-content/themes/monw3at/js/main.js", upstream: "http://85.10.200.69:8080/wp-content/themes/monw3at/js/main.js?ver=1.0", host: "monw3at.com", referrer: "http://monw3at.com/%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%AD%D8%B0%D9%81-%D8%AC%D9%85%D9%8A%D8%B9-%D8%B1%D8%B3%D8%A7%D8%A6%D9%84-%D8%A7%D9%84%D9%81%D9%8A%D8%B3-%D8%A8%D9%88%D9%83-%D8%AF%D9%81%D8%B9%D8%A9-%D9%88%D8%A7%D8%AD/"
2021/06/18 14:49:16 [error] 1379645#1379645: *51 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:51.89.155.27, server: localhost, request: "GET /%D8%A3%D9%81%D8%B6%D9%84-%D8%AA%D8%B7%D8%A8%D9%8A%D9%82-%D9%84%D9%85%D8%B9%D8%B1%D9%81%D8%A9-%D8%A8%D9%8A%D8%A7%D9%86%D8%A7%D8%AA-%D9%85%D9%86-%D9%8A%D8%AA%D8%B5%D9%84-%D8%A8%D9%83-%D8%AD%D8%AA HTTP/1.1", upstream: "http://85.10.200.69:8080/%D8%A3%D9%81%D8%B6%D9%84-%D8%AA%D8%B7%D8%A8%D9%8A%D9%82-%D9%84%D9%85%D8%B9%D8%B1%D9%81%D8%A9-%D8%A8%D9%8A%D8%A7%D9%86%D8%A7%D8%AA-%D9%85%D9%86-%D9%8A%D8%AA%D8%B5%D9%84-%D8%A8%D9%83-%D8%AD%D8%AA", host: "monw3at.com"
2021/06/18 14:49:16 [error] 1379650#1379650: *18 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:41.43.9.21, server: localhost, request: "GET /robots.txt HTTP/1.1", upstream: "http://85.10.200.69:8080/robots.txt", host: "octobermageg.com"
2021/06/18 14:49:16 [error] 1379650#1379650: *22 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:197.9.238.46, server: localhost, request: "GET /wp-content/plugins/jetpack/modules/wpgroho.js?ver=5.2.11 HTTP/1.1", subrequest: "/wp-content/plugins/jetpack/modules/wpgroho.js", upstream: "http://85.10.200.69:8080/wp-content/plugins/jetpack/modules/wpgroho.js?ver=5.2.11", host: "monw3at.com", referrer: "http://monw3at.com/%D8%B7%D8%B1%D9%8A%D9%82%D8%A9-%D8%AD%D8%B0%D9%81-%D8%AC%D9%85%D9%8A%D8%B9-%D8%B1%D8%B3%D8%A7%D8%A6%D9%84-%D8%A7%D9%84%D9%81%D9%8A%D8%B3-%D8%A8%D9%88%D9%83-%D8%AF%D9%81%D8%B9%D8%A9-%D9%88%D8%A7%D8%AD/"
2021/06/18 14:49:16 [error] 1379650#1379650: *27 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ::ffff:41.43.9.21, server: localhost, request: "GET /robots.txt HTTP/1.1", upstream: "http://85.10.200.69:8080/robots.txt", host: "octobermageg.com"
2021/06/18 14:49:16 [notice] 1380134#1380134: signal process started

Note this server is working good for more 3 years with the nginx it go down just today when I didn't make any updates on it
can you help with this please

I made reinstall for engintorn and made this steps
https://engintron.com/docs/#/pages/%22Welcome-to-Nginx-on-Fedora%22-showing-on-all-sites-after-upgrading-Engintron-or-cPanel-(aka-Nginx-from-EPEL-repo-issue)

**Comment by nandogameiro** [comment]
I had the same issue in 3 server in the last 24 hours, they have been working normally for years. The solution so far is force resinstall engintron mainline. However one of the servers which I resintalled about 8 hours ago had the same issue again, I had to do the same procedure above.

I am running Centos 7.9 on all servers. Anyone know the root cause?

Thanks

**Comment by Sherbi** [comment]
> 
> 
> I had the same issue in 3 server in the last 24 hours, they have been working normally for years. The solution so far is force resinstall engintron mainline. However one of the servers which I resintalled about 8 hours ago had the same issue again, I had to do the same procedure above.
> 
> I am running Centos 7.9 on all servers. Anyone know the root cause?
> 
> Thanks

I made reinstall via dashbord but the same issue I'm running CLOUDLINUX 7.9

**Comment by Sherbi** [comment]
I found the issue in Nginx Version 
[root@alpha ~]# nginx -V
nginx version: nginx/1.20.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
built with OpenSSL 1.1.1g FIPS  21 Apr 2020

now working when I made update for it again by
[root@alpha ~]# yum update nginx

and made update to Engintron [Nginx mainline] via dashboard 

the worked version is : 
[root@alpha ~]# nginx -V
nginx version: nginx/1.21.0
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
built with OpenSSL 1.0.2k-fips  26 Jan 2017

but still don't know why this version changed  but now

**Comment by fevangelou** [comment]
@Sherbi The fact that OpenSSL is an older release yet Nginx is newer indicates that Nginx was previously installed from another repo. Therefore some update may have screwed things up in the first place, which would explain why Nginx (the service) got stuck.

For anyone else, if Nginx ever gets stuck, there's an option to force restart both Apache and Nginx. This option ensures the services are killed first and cleanly started afterwards.
