### ISSUE TITLE
Question: OCSP stapling from apache not override on NGINX?

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1335]
Hello, i still struggling to keep Engintron Default and create OCSP response, try from APACHE only.
now, my thing is when you uncomment /etc/nginx/conf.d/default_https.conf
OCSP stapling,
and even in the PHP utilities, Engintron has.

you get the response only on the server block himself, but the sites not get the response...

Now I don't know about the certificate of the main block, and if is a match for all the sites:

`#ssl_trusted_certificate /var/cpanel/ssl/cpanel/mycpanel.pem;`

now, have option not specified certified in NGINX as Nginx.com say:
https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling

now, I notice in one of the /etc/nginx/utilities
have PHP with OCSP stapling (2 places for uncommenting OCSP)
and after this you have the block himself and he contains
'ocspstapling'

this string is the problem and he not work, in the /etc/nginx/conf.d/default_https.conf

my question (in short version)
is:

If Apache/WHM ocsp stapling is turn on in the interface,
Nginx will not copy him?

maybe this is will work:
https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling

without the trust certificate in NGINX, this because is already excites in APACHE / WHM.
what do you say? is possible?

**Comment by locksmithunit** [comment]
I found another interesting thing @fevangelou .

in /etc/nginx/utilities/https_vhosts.php

have some function inside to edit the:
APACHE HTTPD 
AND ENGINTRON IS NOT EDIT HTTPD.

CPANEL ACTUALLY TAKE CARE OF IT IN THE:
WHN>APACHE CONFIGURATION>GLOBAL CONFIGURATION

**more than that, I talk with Cpanel support, when you turn off Engintron.
and work only with APACHE, the OCSP response I perfect.**

NOW IN THE SCRIPT HAVE ANOTHER COOL THING ACTUALLY
in the function of the httpd edit have this:

```
    # OCSP Stapling
    #ssl_trusted_certificate '.$fullChainCertName.';
    #ssl_stapling on;
    #ssl_stapling_verify on;

```

Now, this actually takes the regular certificate when they have already the OCSP response.
I ask Cpanel and they confirm to any certificate (even combined) has OCSP, so we turn off Engintron and they were right.

Now what I see, and recommended (but is up to you @fevangelou , if you tell me is not good I will not do it until you test it).
when you go to the bottom of the file, I see the function of the domain block (what actually create a block for the website:

```
# Definition block for domain(s): '.$vhostDomainsAsComment.' #
server {
    #listen '.NGINX_HTTPS_PORT.' ssl http2;
    listen [::]:'.NGINX_HTTPS_PORT.' ssl http2;
    server_name '.$vhostDomainsForNginx.';
    # deny all; # DO NOT REMOVE OR CHANGE THIS LINE - Used when Engintron is disabled to block Nginx from becoming an open proxy
    ssl_certificate '.$fullChainCertName.';
    ssl_certificate_key '.$vhostCertKeyFile.';
    '.$ocspStapling.'
    include common_https.conf;
}
```


@fevangelou 
what about replacing the string '.$ocspStapling.'  with:
```
    # OCSP Stapling
    ssl_trusted_certificate '.$fullChainCertName.';
    ssl_stapling on;
    ssl_stapling_verify on;

```

even we can put a resolver... **(again i only suggested, the final call is yours).**

The only thing, it is true and working and actually, cPanel takes care of that as promise me in the support chat.
you still not be able to put it by default, because they be must turn on SSL STAPLING 
true APACHE CONFIGURATION.

the other option, is to put it without the certificate and resolver do it auto for you (this because certificates already in apache):
https://www.digicert.com/kb/ssl-support/nginx-enable-ocsp-stapling-on-server.htm

in both of the ways I showed you I get the check marked green in SSL LAB:
https://www.ssllabs.com/ssltest/index.html

I remove it until you approve to be one of the ways is ok,
I figure out with the years your configuration is the best.
and any time I found myself fighting with configuration when your default is the best option.
so I will wait to your response @fevangelou

**Comment by locksmithunit** [comment]
I Bring it back with option 2 (digicert.com suggestion):
i run open ssl in ssh:
`openssl.exe s_client -connect locksmithunit.com:443 -status`

look good:
```
root@server [~]# openssl s_client -connect locksmithunit.com:443 -status
CONNECTED(00000003)
depth=3 C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
verify return:1
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Certification Authority
verify return:1
depth=1 C = US, ST = TX, L = Houston, O = "cPanel, Inc.", CN = "cPanel, Inc. ECC Certification Authority"
verify return:1
depth=0 CN = server.locksmithunit.com
verify return:1
OCSP response:
======================================
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: FE198899934848D2C2A56715955F3501318E738B
    Produced At: Jul  1 16:46:19 2021 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: C941CDD3ABA86C13185E9BEE4D31939FB76F7DA6
      Issuer Key Hash: FE198899934848D2C2A56715955F3501318E738B
      Serial Number: 3DD0AE82B45D5593DDD427D4D7C5AF1C
    Cert Status: good
    This Update: Jul  1 16:46:19 2021 GMT
    Next Update: Jul  8 16:46:19 2021 GMT

    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:c3:e2:a2:27:d3:1b:de:51:68:42:5a:a8:b2:
         49:c7:fa:71:45:94:80:da:a8:0d:29:5a:2d:06:9d:c8:31:a9:
         00:02:21:00:91:c8:8e:0f:39:b1:e9:db:b9:00:41:c7:ba:bc:
         a7:4a:1a:e9:b6:5e:4a:04:e0:51:d6:fa:0a:01:24:bd:93:15
======================================
---
Certificate chain
 0 s:/CN=server.locksmithunit.com
   i:/C=US/ST=TX/L=Houston/O=cPanel, Inc./CN=cPanel, Inc. ECC Certification Authority
 1 s:/C=US/ST=TX/L=Houston/O=cPanel, Inc./CN=cPanel, Inc. ECC Certification Authority
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO ECC Certification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO ECC Certification Authority
   i:/C=GB/ST=Greater Manchester/L=Salford/O=Comodo CA Limited/CN=AAA Certificate Services
---
Server certificate
-----BEGIN CERTIFICATE-----
```

what you say @fevangelou ?

**Comment by locksmithunit** [comment]
I see you not answering...
so, this is without Engintron:
![Screenshot 2021-07-05 235242](https://user-images.githubusercontent.com/37716063/124540127-c316be00-ddec-11eb-8541-78fd5e343b94.jpg)

this cPanel default bro...
btw they create Nginx fit the cPanel perfectly, I like Engintron more, but if you will not support the product
Engintron will lose his power against cPanel Nginx... with all the respect.

if you do not start to move your project and do updates, you will lose a lot of good users.

by the way, I pretty sure OCSP stapling can be activated without the trusted certificate because the certificate already present
in the vHost file of APACHE (HTTPD).

as i said, if performance our the same, maybe don't have a nice interface like Engintron, but is faster and supportable by cPanel,
your product will be history.

Is will be very very sad.

**Comment by fevangelou** [comment]
Indeed.
