### ISSUE TITLE
engintron_static cache not grow's

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1336]
Hey,
I notice the static cache does not grow at all...
even when I turn it off the dynamic caching is not grow more than 20M
A little bit wired no?

**Comment by locksmithunit** [comment]
suspicious on 301 response cache:
https://support.cpanel.net/hc/en-us/articles/4402765267095-ea-nginx-does-not-cache-301-redirects

is familiar with the NGINX of cPanel, I notice Engintron cache only 200 responses.
now I redirecting from apache all the subdomains.
is mean all the response from HTTP they actually 301.

this why I think the HTTP cache not growing.
maybe I need to cache 301 response in the paramas_static?

**Comment by locksmithunit** [comment]
@fevangelou  :
https://ibb.co/BcYGQ7d

is possible? or i have something i missing here?

**Comment by fevangelou** [comment]
Your cache (from the screenshot) seems fine.
