### ISSUE TITLE
AutoSSL (LetsEncrypt) with JS proxy

### ISSUE THREAD

**Issue by thomasando** [engintron/engintron#1338]
Hi there,

I've got the following custom_config, which is working - 
```
#Custom Domains/subdomains using JS servers - reverse proxy
if ($host = "xxxxxx.xxxxxx.co") {
     set $PROXY_SCHEME "http";
     set $PROXY_TO_PORT 5444;
}
```
Unfortunately though, AutoSSL using LetsEncrypt is failing. This path can't be reached, as it exists in the standard webserver but I'm pushing all traffic through to the JS server, which cannot see this path in the standard location, where AutoSSL is putting it. 

Is there a way to specify to bypass the proxy options for the /.well-known path and have it look directly at the file-system path? 
`The content of the DCV (Domain Control Validation) file, as accessed at “http://xxxxxx.xxxxxx.co/.well-known/acme-challenge/asdfasdfasdf”, did not match the expected value.`

Apologies, I feel like this is a basic question. I've inherited this setup from a developer who set it up and am now trying to migrate it to a new host and I believe this is the last hurdle for me to cross!

I tried creating a symlink to the folder within the JS server root, NGINX returns a '502 bad gateway' for this config.

**Comment by fevangelou** [comment]
Use $SITE_URL as shown here: https://github.com/engintron/engintron/blob/master/nginx/custom_rules#L90
