### ISSUE TITLE
Hotlinking issue and 403

### ISSUE THREAD

**Issue by internetwiki** [engintron/engintron#1339]
Hi,

I am submitting this again because did it got deleted yesterday?

When I restart or rebuild my server when Engintron is disabled (in the backup that is rebuilt or in the restarted server) I get a half an hour 403 error, after the half hour my site works again, automatically.

Engintron is causing issues with the hotlinking protection functionality of cPanel: no matter that hotlinking protection is active or not, I am randomly getting hotlinking warnings dummy images that replace my images. Once I disable Engintron, the issue is gone.

Are there any fixes for these issues?

Thanks.

**Comment by fevangelou** [comment]
Hotlinking is probably not configured correctly and as such blocks Nginx. You should ensure exceptions are in place.
