### ISSUE TITLE
WHM GUI broken

### ISSUE THREAD

**Issue by TXJMT** [engintron/engintron#1340]
When entering the Engintron GUI through the WHM Plugins applet the engintron app causes all left hand menus to expand regardless of their prior state.  Each item in the Engintron app that you click causes all left hand WHM menus to re-expand.  

Also, while using the WHM app the cPanel request to monitor activity slide-in dialog shows every time any option in the Engintron GUI is selected.

Watch it here:  https://www.screencast.com/t/KGykcJFa

**Comment by virtualos** [comment]
> When entering the Engintron GUI through the WHM Plugins applet the engintron app causes all left hand menus to expand regardless of their prior state. Each item in the Engintron app that you click causes all left hand WHM menus to re-expand.
> 
> Also, while using the WHM app the cPanel request to monitor activity slide-in dialog shows every time any option in the Engintron GUI is selected.
> 
> Watch it here: https://www.screencast.com/t/KGykcJFa

Nice video! Yes I saw that too, hope to be fix for new upcoming versions...

**Comment by locksmithunit** [comment]
you maybe didn't install the mainline, i recommended delete Engintron from the script /engintron.sh
then remove the Nginx folder (just in case you have another Nginx or "stable" Engintron files.
remove the Engintron script.

then do everything from the beginning (installation) but install it when at the end of the command line have "mainline":
`cd /; rm -f engintron.sh; wget --no-check-certificate https://raw.githubusercontent.com/engintron/engintron/master/engintron.sh; bash engintron.sh install mainline`

copy past it after you do all the process.
is will download the Engintron script from a new registry and install everything properly,
I install the stable version and my sites fall down, the stable version breaking the cPanel.

Maybe it will fix the issue.

**Comment by virtualos** [comment]
This UI bug is not related to nginx mainline or stable it's a bug from engintron itself.

**Comment by locksmithunit** [comment]
This is why i telling you to try to delete all, included the Engintron script, and download it again, it will download it from another register (depend on your cPanel version).

is can help.

btw:
I only note for you, the stable Engintron version not working on my cPanel as well.

**I was thinking maybe it works for you as well, if you will install the mainline version only, without any interfere.**


and i am not the developer, i am just a guy working on Engintron like you,

**Comment by fevangelou** [comment]
@virtualos Actually, it's a bug in WHM. Long standing bug. Like years...

**Comment by TXJMT** [comment]
Been using WHM for > 15 years. Never seen it before...

Thanks,
Joe
o: 214-227-8700
m: 214-802-8289
________________________________

**Comment by fevangelou** [comment]
The bug is in the WHM API for PHP based cPanel plugins. It's evident on the menu and the annoying analytics sidebar.

**Comment by fevangelou** [comment]
Apparently it ignores the cookies used by these 2 things to store their state (the collapsed state for the menus and the show/hide for the analytics sidebar).
