### ISSUE TITLE
WordPress 5.7 updates HTTPs in the PHP | params_static.conf

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1341]
WordPress removes the HTTP version and secures itself with updates and instructions to change the PHP from HTTP to HTTPS by default:
https://make.wordpress.org/core/2021/02/22/improved-https-detection-and-migration-in-wordpress-5-7/

**I little suspect maybe the proxy key needs an additional $schema in the key:**
`proxy_cache_key                "$scheme$host$request_uri";`

(btw - my static cache not growing so much and I little suspect only dynamic cache actually working):
https://github.com/engintron/engintron/issues/1336

@fevangelou 
what do you say?
any recommendation?

**Comment by fevangelou** [comment]
You don't have to do anything.
