### ISSUE TITLE
index directive in http block? possible?

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1342]
**Hope you will answer one day if you see it.**

Hello, I see this:
https://wordpress.org/support/article/nginx/

WordPress recommended adding this to your HTTP block:
` index index.php index.html index.htm;
`
the default is only:
`index index.html;
`
http://nginx.org/en/docs/http/ngx_http_index_module.html

have more couple of thing I was recommended but this is the most important one for now.
what you said @fevangelou

**Comment by fevangelou** [comment]
FFS.
