### ISSUE TITLE
Welcome to CloudLinux !

### ISSUE THREAD

**Issue by zstergios** [engintron/engintron#1343]
http://prntscr.com/1g718j8

> Welcome to CloudLinux
> CloudLinux is the only commercially supported OS designed specifically for the service provider market. CloudLinux s drived from sources freely provided to the public by a prominent North American Enterprise Linux vendor.
> 
> CloudLinux has following advantages:
> 
>     Resource isolation via lightweight virtual environmentsβ  (LVEs)
>     LVEs prevent individual websites from using too many resources
>     LVEs provide better security and protect the server from issues that drain resources for other tenants.
>     Single website cannot overload the server
>     Allows you to fit more sites on one server
>     Lowers risk, increases efficiency and improves server performance
> 

I got this message to ALL websites.
This is happened of 2 of my servers. I disabled the engintron and works.

I tried reinstall, uninstall install nothing happen.

**Comment by fevangelou** [comment]
Enable Engintron and check the logs in /var/log/nginx/. Ensure the Nginx service runs as expected (on ports 80 & 443) with Apache on ports 8080 & 8443. If you see the CloudLinux page, it seems that proxying from Nginx to Apache fails. This could be caused by a multitude of reasons.
