### ISSUE TITLE
Low requests per second because of missing/disabled Keep-Alive

### ISSUE THREAD

**Issue by VirtusB** [engintron/engintron#1345]
Testing done with Apache Bench

With an empty PHP file I get 900 requests per second and 100% of the requests are Keep-Alive.
If there's any content in the PHP file, even a comment, I get 40 requests per second and 0% of the requests are Keep-Alive.

I've tried to solve this problem for a couple of days now, and my only real guess is that Engintron is disabling Keep-Alive if there's content in the PHP file.

I've had Engintron installed for a couple of months now, but without any performance increase, it's still around 40 requests per second for all of the 120 sites that I host. It would make sense that Keep-Alive is the problem, since there's content on every single website.

The URL of the empty PHP file: https://www.rastec.dk/virtus/tester2.php
The URL of the PHP file 1 byte of content, just a single "1": https://www.rastec.dk/virtus/tester.php

The command that I've used to test with Apache Bench: `abs.exe -k -c 350 -n 5000 https://www.rastec.dk/virtus/tester.php`

The server is running CentOS with CloudLinux 7.9 and cPanel version 96.0.14, Engintron version is 1.15.0
alt-php version 8.0.8 with OPcache enabled as well as OPcache file_cache enabled as fallback

phpinfo: https://www.rastec.dk/phpinfo.php

I'm really at a dead end here, so any help is greatly appreciated :)

**Comment by fevangelou** [comment]
First of all, if you run AB from your desktop, you probably won't get a good measure of performance...

Secondly, Engintron is one piece of the puzzle. Configure it properly and your sites will "fly". But it's not just Engintron. A stock or mis-configured Apache, MySQL/MariaDB, PHP and of course the system itself, play a large role in a server's performance.

Using curl I can see this:
```
$ curl -I "https://www.rastec.dk/virtus/tester.php"
HTTP/2 200 
server: nginx
date: Mon, 02 Aug 2021 21:05:32 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
x-powered-by: PHP/8.0.8
cache-control: max-age=2592000
expires: Wed, 01 Sep 2021 13:54:10 GMT
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-nginx-upstream-cache-status: HIT
x-server-powered-by: Engintron
```

This means you have some .htaccess rule (or code in your PHP file) that instructs Nginx to cache the response. This means that after the first request (which Nginx will subsequently request from Apache), Nginx will cache the response for 30 days and serve EVERYONE else for that timeframe. So if you get 40 reqs/sec on that (!) when you should be getting at least a few thousands, then it's most likely a problem with your AB test run from your Windows desktop to your server.
