### ISSUE TITLE
Static files are being served by apache even when Engintron is active

### ISSUE THREAD

**Issue by avinashpudota** [engintron/engintron#1346]
Hi,
When i open Home »Server Status »Apache Status in WHM, i see many static files like css, html(static html files, not generated via PHP), fonts, images are being served by Apache. I think these files should be served by Nginx, Please correct me if i am wrong.

**Comment by fevangelou** [comment]
Use `curl -I https://someurl` to verify this. A URL would also help me debug the case for you.

**Comment by avinashpudota** [comment]
Headers look fine and it shows nginx and powered by Engintron, but i see static files being served by apache via port 8080 and 8443 in Apache Status
Here is a static HTML website for sample - http://bluemontsoft.net
Below is the output for curl -I http://bluemontsoft.net

`curl -I http://bluemontsoft.net/
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 11 Sep 2021 04:54:03 GMT
Content-Type: text/html
Content-Length: 11805
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Thu, 14 Nov 2019 06:31:20 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Upstream-Cache-Status: EXPIRED
X-Server-Powered-By: Engintron
Accept-Ranges: bytes`

I have attached the screenshot for Apache Status which shows JPG and HTML files being served.

![apache status](https://user-images.githubusercontent.com/18302154/132936832-722a05e6-77af-41f9-9919-0c5e3263a49b.JPG)

**Comment by fevangelou** [comment]
This is normal cause you're checking the Apache status page. Fetch some .jpg image with curl (and NOT on port 8080 or 8443) as I showed you above and you'll see it's Engintron (the HTTP headers will also be a bit different as Engintron adds client-side caching).

**Comment by avinashpudota** [comment]
thank you for the clarification.
