### ISSUE TITLE
Basic Auth Per Domain 

### ISSUE THREAD

**Issue by nvlonline** [engintron/engintron#1347]
Hi,
I need some help to set up custom rules.  I have been using Engintron for few years now successfully and am familiar with usage of custom_rules file.

However, I seem to be in a corner case where custom_rules is not sufficient but I am scared to hack away into the main files.  Here is my scenario.

SCENARIO:
I need to set basic authentication for all the domains on the server by default but allow certain IPs all the time.  However, at times, I should be able to add exception to some domains.  

Here is the way I am doing it inside custom_rules file:

```
satisfy any;
include /etc/nginx/dev_stage_configs/allowed_ips/*;
deny all;
auth_basic "Restricted Access";
auth_basic_user_file /etc/nginx/dev_stage_configs/.password_file;
```

However, if I try something like this, it won't work because it is using the satisfy any and is denying access because there is no more basic auth.

```
set $basic_auth_mode "Restricted Access";
set $basic_auth_ips "/etc/nginx/dev_stage_configs/restricted_ips.conf";

if ($host ~ 'example.com') {
    set $basic_auth_mode off;
}

satisfy any;
include /etc/nginx/dev_stage_configs/allowed_ips/*;
deny all;
auth_basic $basic_auth_mode;
auth_basic_user_file /etc/nginx/dev_stage_configs/.password_file;
```

The only option seems to be to hack the utilities/https_vhosts.php and add these include statements there conditionally. 

QUESTION:
When does this dynamic generation happen? Is it every time we add a new domain? Or is it at a set cron? If so where is that cron?
I noticed that when I use the utilities/https_vhosts.sh script, it only worked if I previously deleted the conf.d/default_https.conf

Thanks a lot for any guidance and help!

**Comment by nvlonline** [comment]
UPDATE:
Looks like I found the answer. The cron job is actually defined in /etc/crontab to run every min. So looks like I am all set by making a change to the PHP file.

Would appreciate if you know of any cleaner way to do this using custom_rules instead of hacking PHP file.

Thanks again!

**Comment by fevangelou** [comment]
It's much easier to do that in your .htaccess file. Nginx will respect any domain locking.
