### ISSUE TITLE
Some errors in the nginx log from the new wordpress update. (proxy judge)

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1348]
Hello, i get a lot of errors from the new update of WordPress to 5.8...

```
2021/08/19 17:45:25 [error] 15126#15126: *1215 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:20.150.209.191, server: localhost, request: "GET http://azenv.net/ HTTP/1.1", upstream: "http://45.33.51.119:8080/", host: "azenv.net"
2021/08/19 18:19:26 [error] 15122#15122: *1589 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:13.113.94.21, server: localhost, request: "GET http://azenv.net/ HTTP/1.1", upstream: "http://45.33.51.119:8080/", host: "azenv.net"
2021/08/19 18:24:26 [error] 15123#15123: *1727 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:13.113.94.21, server: localhost, request: "GET http://azenv.net/ HTTP/1.1", upstream: "http://45.33.51.119:8080/", host: "azenv.net"
2021/08/19 18:39:31 [error] 15122#15122: *1875 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:13.113.94.21, server: localhost, request: "GET http://azenv.net/ HTTP/1.1", upstream: "http://45.33.51.119:8080/", host: "azenv.net"
```
as you see, bots try get to port 8080 and 80 with azenv.net, a stoped proxy judge, these errors come from the cache of engintron, if i knew what is this and how Engintron cache actually save a URL like this? (as a JSON? RSS?)

then i will delete him from the Engitron cache and give Apache to deal with these people,
when the error is not present on Engintron.

I know is sounds wired, but i found out has a header HTTP 1.1 in Engintron causing problems with XML cache as well.

For example:
the sitemap XML i remove from the Nginx cache is causing errors of UTF-8
and ISO chart.

This together with a firewall from WordPress (Wordfence).
I believe apache needs hendel all of this

maybe i will get rid of the errors in the log with the same caching result.

this is what i try to do now, to delete the azenv.net from the cache, the problem I don't know where is coming from.
is a JSON? is an RSS? when i read it online people said is a script.

how can i make it go away from Nginx log?

**Comment by fevangelou** [comment]
Doesn't happen in stock setups so it's most likely some configuration you've done. I can't possibly know though...

**Comment by locksmithunit** [comment]
you right i am sorry, is from ModSecure and the new vendor rules from cPanel.
cPanel support already adjusts it for me.
