### ISSUE TITLE
servicedomain redirect error with engintron

### ISSUE THREAD

**Issue by hribernik** [engintron/engintron#1349]
Hi,
users logged in over cpanel.domain.name get the following error when they click the autologin button for webmail:

`Template::Exception:
 [TYPE]=[undef]
 [INFO]=[Over standard port expect “cpanel.” service subdomain, not “server.domain.com”! at /usr/local/cpanel/Cpanel/WebmailRedirect.pm line 260.
]
 [TEXT]=[]
 at cpanel.pl line 1128.
 cpanel::cpanel::cptt_exectag("/usr/local/cpanel/base/frontend/paper_lantern/mail/webmailfor"..., 1) called at cpanel.pl line 4634
 cpanel::cpanel::run_standard_mode() called at cpanel.pl line 932
 cpanel::cpanel::script("cpanel::cpanel", "./frontend/paper_lantern/mail/webmailform.html.tt") called at cpanel.pl line 328`

when they log in over domain.name:2086/cpanel the redirect works fine. 

is this an engintron related issue? and if, how can we troubleshoot it?

Best Regards.

**Comment by fevangelou** [comment]
I believe there's an option in Tweak Settings for that. I've given up remembering their names though...

**Comment by hribernik** [comment]
The option is activated. found this article though https://geizhals.at/hoover-hwpdq49ambcr-1-s-frontlader-31011096-a2425339.html since engintron/nginx is another layer in front of apache ithought you could help me out.

**Comment by fevangelou** [comment]
And?
