### ISSUE TITLE
Support use by resellers with the 'all' privilege

### ISSUE THREAD

**Issue by escherlat** [engintron/engintron#135]
In enginetron.php a hard coded check for the root user exists. This has the following problems:

1. On some systems 'root' can be renamed
2. In cPanel & WHM a reseller with the 'all' privilege is the equivalent of root

**Comment by fevangelou** [comment]
Are you referring to the ACL fix I apply? E.g. here: https://github.com/engintron/engintron/blob/master/engintron.sh#L324

**Comment by escherlat** [comment]
I'm referring to this:

https://github.com/engintron/engintron/blob/master/app/engintron.php#L13

The REMOTE_USER environment variable is set to the system name of the logged in user. If that user is a resellers with root privileges (has the 'all' acl) that user is effectively root, however REMOTE_USER will contain his user name, not root.

A recommended method of doing this to check the return of the **myprivs** API call for the _all_ privilege: https://documentation.cpanel.net/display/SDK/WHM+API+1+Functions+-+myprivs

**Comment by fevangelou** [comment]
Thank you. I'm noting it down to fix in the next update.

BTW, have you considered having a user object and/or perhaps system object that carries such (among others) info and have it available anywhere in WHM without the need for any external file (API) calls? Similar to how CMSs usually provide info about the currently logged in user and the system (site, server info etc.).

**Comment by fevangelou** [comment]
Additionally, is the "addon_engintron.cgi" file necessary? I use it to redirect to the engintron.php file and I can see there are root user checks in there as well (I probably got this from some older WHM plugin).

**Comment by fevangelou** [comment]
OK, looking at Munin's .cgi file I managed to simplify Engintron's .cgi file even further and ACLs seem to be properly used now without any "root" user checks. Marking as resolved. :)
