### ISSUE TITLE
csv file doesnt export

### ISSUE THREAD

**Issue by Brijendrasial** [engintron/engintron#1351]
Hello,

I have trying to export csv file but it doesnt work. For apache its working fine.

apache (port 8443)

https://www.digiversal.info:8443/portal/test_export.php?status=new_lead&website_id=13&fromDate=2021-08-31%2000:00:00&toDate=2021-08-31%2023:59:59&expert=undefined&withtvah=&lead_source=

for nginx (it prints data instead of download)

https://www.digiversal.info/portal/test_export.php?status=new_lead&website_id=13&fromDate=2021-08-31%2000:00:00&toDate=2021-08-31%2023:59:59&expert=undefined&withtvah=&lead_source=

**Comment by virtualos** [comment]
> Hello,
> 
> I have trying to export csv file but it doesnt work. For apache its working fine.
> 
> apache (port 8443)
> 
> https://www.digiversal.info:8443/portal/test_export.php?status=new_lead&website_id=13&fromDate=2021-08-31%2000:00:00&toDate=2021-08-31%2023:59:59&expert=undefined&withtvah=&lead_source=
> 
> for nginx (it prints data instead of download)
> 
> https://www.digiversal.info/portal/test_export.php?status=new_lead&website_id=13&fromDate=2021-08-31%2000:00:00&toDate=2021-08-31%2023:59:59&expert=undefined&withtvah=&lead_source=

Hi,
I just tried both your apache and nginx and I downloaded csv without any issue:
![a](https://user-images.githubusercontent.com/62283634/131629903-91f548e4-9c72-444f-a359-0e4904da393e.png)
![n](https://user-images.githubusercontent.com/62283634/131629915-9978b899-6299-4be7-a269-fd3c834080e2.png)

**Comment by Brijendrasial** [comment]
Hello,

I have to change many lines in code to make it work. I have changed the file to default. Please check now. In apache it works and in nginx as reverse proxy it doesnt.

**Comment by fevangelou** [comment]
Probably bad/missing HTTP headers sent from the script performing the download. Nginx does not know how to interpret them so it defaults to text on the screen.
