### ISSUE TITLE
Welcome to nginx on CloudLinux!

### ISSUE THREAD

**Issue by barchard** [engintron/engintron#1352]
this may be related to https://github.com/engintron/engintron/issues/1343 but on CentOS 8, a rpmup installed a newer version of nginx. Now all sites render the attached default page. Disabling Engintron fixes the site. I have several CentOS 7 installs which did not exhibit this. 

```
# which nginx
/sbin/nginx
```

```
# nginx -v
nginx version: nginx/1.14.1
```
<img width="1012" alt="CleanShot 2021-09-02 at 21 12 08@2x" src="https://user-images.githubusercontent.com/17622/131935950-cf0601d6-dc1f-4609-99c9-c4aa8405e713.png">

**Comment by virtualos** [comment]
Please see this topic:
https://github.com/engintron/engintron/issues/1318
