### ISSUE TITLE
Nginx couldn't start

### ISSUE THREAD

**Issue by tarekfellah** [engintron/engintron#1353]
I have a Cpanel/WHM server with Nginx installed as reverse proxy, so i tried to replace Nginx with Engintron 
so I installed Engintron and uninstalled Nginx via Cpanel Nginx manager.
As a result i got website not working and Nginx couldn't start (status from WHM  Engintron page), so i should reinstall Nginx? 
I don't know if Engintron contains already Nginx or not
I tried to reinstall Nginx and website work again, but i don't know if Engintron is serving the website or Nginx

**Comment by virtualos** [comment]
Please see this topic if you try Engintron on RHEL 8
https://github.com/engintron/engintron/issues/1318

Otherwise if you are on RHEL7 Reinstall Nginx from Engintron interface (Use mainline version which is latest version)

> I don't know if Engintron contains already Nginx or not
Yes, it does!

**Comment by tarekfellah** [comment]
I'm using CentOS 7.9, i uninstalled Nginx from Nginx manager and i reinstalled Engintron (mainline version), now the website is not working, 
I tried to check Nginx configuration i got this 
"Checking Nginx configuration...
sh: nginx: command not found"

**Comment by tarekfellah** [comment]
I reinstalled Nginx (ea-nginx) from shell, 
curl -I "https://domain.ltd"
HTTP/1.1 200 OK
Server: nginx/1.21.1
Date: Mon, 06 Sep 2021 08:23:29 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Magento-Cache-Control: max-age=86400, public, s-maxage=86400
X-Magento-Cache-Debug: MISS
X-Magento-Tags: store,cms_b,cms_p_72,amasty_mega_menu,cms_b_image,cms_b_freeicon,FPC
Pragma: no-cache
Cache-Control: max-age=0, must-revalidate, no-cache, no-store
Expires: Sun, 06 Sep 2020 08:23:29 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Vary: Accept-Encoding,User-Agent
X-UA-Compatible: IE=edge
Cache-Control: max-age=0, no-cache, must-revalidate

Does Engintron work?

**Comment by fevangelou** [comment]
ea-nginx is the Nginx package coming from cPanel, not the official one from Nginx. I have no idea how things got messed up for you. Try uninstalling and re-installing Engintron.

**Comment by fevangelou** [comment]
Closing as non-active.
