### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [engintron/engintron#1354]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by avinashpudota** [comment]
@JamieSlome I think this is the official Email ID listed here (engintron@gmail.com)
https://github.com/engintron/engintron/blob/e1d549a23b031064bb352d3aafc076359e65e7ee/app/engintron.php#L615

**Comment by fevangelou** [comment]
Thank you for your email @JamieSlome - Issue resolved
