### ISSUE TITLE
Installed and running, error log is showing loads of errors though

### ISSUE THREAD

**Issue by ep0ch** [engintron/engintron#1356]
These issues are appearing approximately every second in error log:

```
2021/09/22 03:05:01 [error] 4130#4130: *15676 open() "/etc/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /whm-server-status HTTP/1.0"
2021/09/22 03:05:01 [error] 4130#4130: *15676 open() "/etc/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /whm-server-status HTTP/1.0"
2021/09/22 03:05:18 [error] 4128#4128: *15722 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: , request: "GET / HTTP/1.0"
2021/09/22 03:05:18 [error] 4128#4128: *15722 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: , request: "GET / HTTP/1.0"
```

**Comment by fevangelou** [comment]
This would only come up if there was an actual location block for the server's hostname pointing to a local path, but there isn't any (at least not in Engintron). Everything in Engintron works in proxy mode, so errors like that are not possible.

If you previously installed other plugins for Nginx (or even cPanel's copy), you need to ensure they are properly removed/uninstalled before installing Engintron.

And unlike other plugins/solutions, when Engintron is uninstalled, it leaves your system in the state it were before you installed it in the first place.
