### ISSUE TITLE
Disable Caching of Static Files 

### ISSUE THREAD

**Issue by rafaelmagic** [engintron/engintron#1357]
Hi,
I tried to disable Nginx caching of Static files  (images, css, js). So far I havn't had any luck.

I tried the code like below, but then the css and images were not loading from Apache. I am not sure what I am doing wrong.

`location ~* \.(?:css|js)$ {
     set $CACHE_BYPASS_FOR_DYNAMIC 1; 
     set $CACHE_BYPASS_FOR_STATIC 1; 
}`

Thank you,
Rafael

**Comment by rafaelmagic** [comment]
So I did a bunch of thinking and if I comment out the browser cache lines at common_http.conf. Then replace them with the code below. Will that disable static file caching?

`# Disable cache for static content files
location ~* \.(?:json|xml|rss|atom)$ {
     set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
     set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}

# Disable cache for CSS / JS 
location ~* \.(?:css|js)$ {
     set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
     set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}

# Disable cache for images
location ~* \.(?:ico|jpg|jpeg|gif|png|webp)$ {
     set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
     set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}

# Disable cache for archives, documents & media files
location ~* \.(?:3gp|7z|avi|bmp|bz2|csv|divx|doc|docx|eot|exe|flac|flv|gz|less|mid|midi|mka|mkv|mov|mp3|mp4|mpeg|mpg|odp|ods|odt|ogg|ogm|ogv|opus|pdf|ppt|pptx|rar|rtf|swf|tar|tbz|tgz|tiff|txz|wav|webm|wma|wmv|xls|xlsx|xz|zip)$ {
     set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
     set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}

# Disable cache for fonts & fix @font-face cross-domain restriction 
location ~* \.(eot|ttf|otf|woff|woff2|svg|svgz)$ {
     set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
     set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}
`

Then since I just want to cache HTML files. I will add the following code
`location ~* \.(?:html|htm|html.gz|htm.gz|txt)$ {
        include proxy_params_common;
        include proxy_params_static;
        expires 30d;
    }`

**Comment by fevangelou** [comment]
Read the notes in "custom rules". Setting `set $CACHE_BYPASS_FOR_STATIC 1;` should be enough.
