### ISSUE TITLE
Nginx problem with cPanel Autossl

### ISSUE THREAD

**Issue by GFWebmaster** [engintron/engintron#1358]
Hello, suddenly, I think since last update, when adding a NEW domain, addon domain or a subdomain, cPanel assign the SSL certificate (AutoSSL) but when we open it in browser the certificate is invalid.

When we run "nginx -s reload" manually the SSL problem in browser is fixed.

We have been using Engintron for cPanel for years ant this is te first time we have a problem.

Any ideas?

Thanks very much

**Comment by fevangelou** [comment]
Certificates make take a few minutes to properly show on the browser. If you want to check a certificate immediately after issued, you need to open a site you opened before in a private window. Browsers cache certificates.

**Comment by GFWebmaster** [comment]
Hello, thanks for your answer.
The certificates were invalid even 24 hours after assigned.
We discussed this in cPanel forum also.
Running "nginx -s reload" solved the problem but is not normal.
As I said, we're using Engintron for years.
We uninstalled and installed it again and apparently the problem is fixed but for the moment we don't have any new domains to add.
The problem is with NEW domains, addon domains and subdomiains, SSL renewals are ok.
We will be in touch if the problem persists
Kind Regards

**Comment by fevangelou** [comment]
Any chance the file /etc/crontab was edited and got borked or something? I doubt the issue was just a matter of reloading the Nginx config. If an SSL certificate is issued or updated in Apache, the Apache config changes, Nginx picks up the change through the cron job in /etc/crontab and then updates its configs and of course reloads them.

There's a troubleshooting section in the Engintron docs. Have a look there as well.

**Comment by GFWebmaster** [comment]
Hello, thanks for your answer.
All right, we will check it out and let you know.
Regards!

**Comment by GFWebmaster** [comment]
Hello, ¿which line must have nginx in cpanel crontab?
Thanks for your help

**Comment by fevangelou** [comment]
This one: https://github.com/engintron/engintron/blob/master/engintron.sh#L577

**Comment by GFWebmaster** [comment]
Hello, thanks for your time and your answer.

We added the line to crontab, but there was no difference so we switched to Let's Encrypt AutoSSL provider and it seems to be fixed.

Kind Regards

**Comment by fevangelou** [comment]
Always prefer LetsEncrypt :)
