### ISSUE TITLE
Eazy Apache 4 (cPanel) Default vs MPM_WORKER?

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1359]
Hey, i install a new cPanel server on GCP.
I notice the default is "prefork"

I try stick to the default cPanel configuration how much i can.

EazyApache4 default (mod_prefork) from cPanel can work well with engintron?

or i must to change it to mod_worker?

**Comment by fevangelou** [comment]
Ask cPanel who you pay for your license.
