### ISSUE TITLE
Custom rules to setup SSL

### ISSUE THREAD

**Issue by hostfusion** [engintron/engintron#136]
Hi,

i need to install a SSL (COMODO) for a domain with dedicate ip, Do I need to make some adjustment in the custom rules?

Thanks for your help

Regards

P.S.

**Comment by hostfusion** [comment]
Hi,

thanks, i have include the domain and the dedicate ip in exclude domain custom rules.

Regards

P.S.

**Comment by fevangelou** [comment]
Since Nginx does not habdle traffic at port 443 (the HTTPS port) it does not need any special configuration unless you have internal redirections of some sort that use both HTTP and HTTPS protocols.

**Comment by hostfusion** [comment]
Hello @fevangelou 

Thanks for the reply, i note that if a hosting have ssl (COMODO) and dedicate ip, calls to http not work, go to tipical cPanel screen DNS propagation , only https work, to work http and https i need include the domain and the dedicate ip in exclude domains in Engintron custom rules.

that´s normal ?

Regards

P.S.

**Comment by fevangelou** [comment]
Not really. You must have some .htaccess redirects messing things up OR you have CloudFlare and then yes, it does require additional setup inside the "custom rules" file. If you don't have CloudFlare, check for any .htaccess redirects that could be causing issues.

**Comment by bashcode** [comment]
I have included SSL through additional configuration but we have not had problems with HTTP.

**Comment by hostfusion** [comment]
Thanks for the comments, i take a look.

Regards

P.S.

**Comment by fevangelou** [comment]
@bashcode Would you mind sharing your SSL configuration in a new issue here on GitHub? Maybe we could brainstorm on various configurations with other users on the right solution ;)
