### ISSUE TITLE
MariaDB 10.5 not restarting with all the services.

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1365]
Hey, whats up. @fevangelou 

MariaDB changes the command line.
what is wired to me, is:
when you restart my.cnf, is restarts properly.

but when you restart all the services together, MariaDB does not get it :(

is because MariaDB changes the cmd from "mysql".

they note that on the installation of MariaDB when you upgrade that on cPanel interface.

if you can build a button for MariaDB 10.5 users is be much better :)

**Comment by fevangelou** [comment]
Yes it does: https://github.com/engintron/engintron/blob/master/engintron.sh#L929

Please report actual issues that can be verified with logs or other proof.
