### ISSUE TITLE
Charset_map error in log - Recommended + solution.

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1366]
ok, for our the last topic, this isiue is with a lot of people use engintron, a problem not come from engintron but can be fixed by engintron.

I notice in the forum of NGINX RU, one of the people offer to put it open like this:
` charset_map      iso-8859-1 utf-8 { }`

**THIS IS MAKE THE ERROR DISAPPEAR FROM THE LOG BUT IS NOT THE RIGHT FIX.**

ok if we read well the NGINX DOCS:
http://nginx.org/en/docs/http/ngx_http_charset_module.html#charset_map

We will see the option we have.
Now,

ANY NGINX INSTALL 2 CHARSET MAPS BY DEFAULTS:
https://fossies.org/linux/www/nginx-1.20.1.tar.gz/nginx-1.20.1/conf/koi-win
https://fossies.org/linux/www/nginx-1.20.1.tar.gz/nginx-1.20.1/conf/koi-utf

in engintron, you don't have it and we have only mime-type.

if we look on the docs of engintron they publish this construction:

```
The ngx_http_charset_module module adds the specified charset to the “Content-Type” response header field. In addition, the module can convert data from one charset to another, with some limitations:

conversion is performed one way — from server to client,
only single-byte charsets can be converted
or single-byte charsets to/from UTF-8.
Example Configuration
include        conf/koi-win;

charset        windows-1251;
source_charset koi8-r;
```

and they say is ok to choose only one from the charset or the source_charset.
**but the conf/koi-win or other (depending on the conversion you want) must be included.**

I didn't find any charset map for the regular ISO of cPanel ( they convert it from the PHP with Fastcgi contact-type-header ).

but i found this:
https://fossies.org/linux/www/nginx-1.20.1.tar.gz/nginx-1.20.1/contrib/unicode2nginx/unicode-to-nginx.pl

Fossies create a special script to get the mapping from charset headers you already have but do not have a mapping map online.

You can include this bash script in Engintron and solve everybody the problem, i gonna test the bash script as well.
But from my experience, you know your software better than me.

after this mapping people be able to convert to UTF-8 inside Engintron without any problem.

waiting you your respond and recommendations :)

**Comment by fevangelou** [comment]
> and solve everybody the problem

You really are the only one to ever have reported this. And my guess is you've probably done lots of tweaks to squeeze more performance out of the wrong component on your server...

Closing as non-issue.
