### ISSUE TITLE
/var/log/nginx/error.log

### ISSUE THREAD

**Issue by xuhaibkhan1122** [engintron/engintron#1368]
Hello,

I have /var/log/nginx/error.log filled with these errors.
[alert] 1420#1420: ignore long locked inactive cache entry 6e7e56dc49fafb61be7f0631533c6f97, count:1

    # Proxy Cache Settings
    proxy_cache_path  /var/cache/nginx/engintron_dynamic  levels=1:2 keys_zone=engintron_dynamic:512m max_size=16g inactive=1h use_temp_path=off;
    proxy_cache_path  /var/cache/nginx/engintron_static   levels=1:2 keys_zone=engintron_static:512m  max_size=4g inactive=1h use_temp_path=off;
    proxy_temp_path   /var/cache/nginx/engintron_temp;

Can you please suggest what I am doing wrong!

**Comment by fevangelou** [comment]
Seems Nginx related. This might shed some light: https://forum.nginx.org/read.php?2,263625,263630#msg-263630

**Comment by xuhaibkhan1122** [comment]
Server have one website with images around 400GB of images would you suggest changing max_size=16g ? will it make any performance difference?
proxy_cache_path  /var/cache/nginx/engintron_dynamic  levels=1:2 keys_zone=engintron_dynamic:512m max_size=16g inactive=1h use_temp_path=off;

**Comment by fevangelou** [comment]
I believe the defaults are just fine - stick to that. Either way, a large cache pool is probably bound to create thousands if not millions of stale cache entries, which may fail to be refreshed on the filesystem.

**Comment by xuhaibkhan1122** [comment]
I was not able to find any good settings online, and also found in topic here that the php-fpm setting available online aren't right. 
I have 8core(Cpu) 32GB server and have the following settings.
SYSTEM PHP-FPM SETTINGS
Max Requests: 300 cPanel Default: 20
Max Children:30 cPanel Default: 5
Process Idle Timeout:10 cPanel Default: 10

Would you suggest to tweak them!

**Comment by xuhaibkhan1122** [comment]
All the images on site are always served in "Stale State" Site have around 60,000 images and Videos.
Do you think I should just stick to default values.

**Comment by fevangelou** [comment]
Have a look at this: https://www.nginx.com/blog/nginx-caching-guide/#:~:text=inactive%20specifies%20how,the%20inactive%20timer.
