### ISSUE TITLE
PDF download link issues in site with engintron enabled

### ISSUE THREAD

**Issue by theozsnowman** [engintron/engintron#1369]
I guess this is more an nginx issue than a problem but im not able to find anything in cpanel forums etc as a solution

In a clients website we CAN download pdf files if the link is IN the page :

`<a href="name.pdf">`

But NOT if the entire url and link is placed in the page or you link DIRECTLY to the pdf file///

`<a href="https://domain.com/name.pdf">`

anyone know of a workaround to allow a full path to be added to a liunk and still trigger a download of the file instead of it trying to render it as a webpage? (which results in jibberish)

**Comment by fevangelou** [comment]
It's not an Engintron issue for sure. I would also recommend using the "download" HTML attribute on links: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download

**Comment by theozsnowman** [comment]
ok thanks i will give the download link a try
