### ISSUE TITLE
End of script output before headers

### ISSUE THREAD

**Issue by tess0072** [engintron/engintron#137]
I've been running Engintron with great results for the past two months but I've recently started to experience the following errors within apaches error log:

[Mon Apr 18 23:02:21.070974 2016] [fcgid:warn] [pid 33824] (104)Connection reset by peer: [client XXX.XXX.XXX.XXX:XXXXX] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: http://xxxx.com/
[Mon Apr 18 22:53:58.203463 2016] [core:error] [pid 25464] [client XXX.XXX.XXX.XXX:XXXXX] End of script output before headers: index.php, referer: http://xxxx.com/
[Mon Apr 18 23:03:20.586245 2016] [core:error] [pid 34957] [client XXX.XXX.XXX.XXX:XXXXX] End of script output before headers: index.php, referer: http://xxxx.com/

These pages never used to cause any issues whatsoever but recently I've started to experience this issue very regularly. I also usually receive a cPanel Out of memory: A process was terminated because the system is low on memory. Although the system has over 32GB of free memory at that time so it is not actually tight on memory whatsoever. I can see that php invokes oom-killer eventually within the dmesg file.

Any idea what could be causing this? I followed your wiki exactly and was able to reproduce this error.

**Comment by fevangelou** [comment]
Have a look here:
- http://stackoverflow.com/questions/33811543/php-and-mod-fcgid-ap-pass-brigade-failed-in-handle-request-ipc-function
- https://techjourney.net/connection-reset-by-peer-mod_fcgid-ap_pass_brigade-failed-in-handle_request_ipc-function/

Tweaking your FastCGI setup will probably resolve your issues.
