### ISSUE TITLE
Clear cache button?

### ISSUE THREAD

**Issue by CarlosLopezES** [engintron/engintron#1371]
Hi!

This it's a think that I thought for a long time, and with the last cPanel update, they have implemented:

> Added the Clear Cache button to the cPanel Interface page
> In cPanel & WHM version 100, we added a Clear Cache button to the General Information section of the cPanel interface. If NGINX® caching is active for your account, click Clear Cache to clear the NGINX cache.
> 
> This button only appears if NGINX is installed on your server and caching is active.

So... it's possible to add it to Engintron? That would be and awesome feature, many users asks me everytime for clear cache...

Thanks!

**Comment by luxmicro** [comment]
Pretty sure Engintron already has this feature. Click on **Enginetron for cPanel/WHM** - **Nginx** - **Purge cache & temp files** (_At the bottom of the Nginx column_)

**Comment by CarlosLopezES** [comment]
Of course, but it's only for WHM admin, the key here it's allow to users to restart the cache.

For example, I have dedicated servers that I would approve that users can clear all server cache without problem, but I cannot allow them to WHM...

**Comment by fevangelou** [comment]
There is literally no reason to clear any caches when using Engintron. Dynamic content is cached for 1 sec and static content is cached for 1 min. The latter may cause issues if someone is changing e.g. some CSS file on a live site. But even so, the best strategy to use is cache-busting. Cache-busting is also a "must" if you wish to develop live on a site without causing problems to end-users/visitors.

This browser plugin eases this process too: https://chrispederick.com/work/web-developer/
