### ISSUE TITLE
possible to add html block for WordPress caching plugin?

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1376]
Hey @fevangelou 

I use the cache-enabler plugin:
https://wordpress.org/plugins/cache-enabler/

together with Engintron.
now:
1. i have difficulty bypassing the PHP Hendler the plugin creates.
and
2. the plugin does not create JS AND CSS he creates HTML INDEX (STATIC HTML - IS LIKE WP-SUPER-CACHE)

It means Engintron maybe need an HTML block to read that plugin cache.
or maybe i wrong? and Dynamic cache does it already? 

I think if i will add to the http_common an HTML BLOCK
maybe improve performance and give me the option to bypass the PHP-HENDLER.
But i a little confused because i use the micro cache in engintron. (static HTML)

So i got lost if i need to put this block or not, to enjoy the benefit of the Cache Enabler plugin
( the plugin creates HTML files in the cache folder and not JS-CSS! )

@fevangelou , Have a chance you help me here a little bit? only tell me if is good to add an HTML block in http_common.

for example, inside the common_http:
```
# Enable browser cache for HTML / TXT Static files | Cache-Enabler (TTL is 1 min)
location ~* \.(html|htm|txt)$ {
    include proxy_params_common;
    include proxy_params_static;
    expires 1m;
}
```

by the way, i am on default, the cPanel, the Engintron the WordPress plugins, everything is on his default.
i try to keep it this way for updates in the feature.

**Comment by fevangelou** [comment]
This is wrong as it implies additional Nginx config for direct serving, not for proxying (which is what Engintron does).

**Comment by locksmithunit** [comment]
why additional?
i want to implant that inside the http_common of engintron.
what will cause static HTML in engintron static. ( because the cache enabler plugin generate HTML pages )

my propose is to by pass the PHP handler with Engintron.
then Engintron will serve the cache better.

if you have another idea i be happy to hear.
if not i will keep it on default and be stuck with the PHP HENDLER of the plugin.

the plugin work like wp-super-cache ( WordPress WP-CACHE TRUE inside WP-CONFIG )

I KNOW IS OUT OF AREA, 
but you know better then me and i sure you work with WP-CACHE before. especially with WordPress.
