### ISSUE TITLE
Engintron support cPanel DNS Clustering?

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1379]
Hey @fevangelou ,
I cluster 2 servers (2 VMs on GCP)

both of the VMs are WHM/CPANEL with 2 licenses.

with Engintron of course :)

I cluster between them with DNS CLUSTER inside WHM of each server.
the cluster of cPanel duplicates DNS Records from server to server.

its can be a problem for Engintron?
or you tried before cluster 2 servers (WHM servers) and you already know Engintron is capable of that?
or need some adjustment? ( like the cloud flare in the costum_rules of Engintron?)

**Comment by fevangelou** [comment]
It's not a problem for Engintron.
