### ISSUE TITLE
Wordpress Upload

### ISSUE THREAD

**Issue by jynxy** [engintron/engintron#138]
Hi, i cannot upload images to wordpress when enable i get http error.

Any fix or setting i need to change thanks.

**Comment by fevangelou** [comment]
You need to specify the exact error message you get.

**Comment by jynxy** [comment]
Hi,

when engintron is activated, if you goto media -> add new and upload an image, it just displays http error.

if i disable engintron, the image uploads with no issue.

Thanks

**Comment by fevangelou** [comment]
Yes, but what's the freaking http error you mention? If you disable Engintron, it's like it's not installed on your system, so no Nginx, just Apache.

**Comment by jynxy** [comment]
Please see the image.

![error](https://cloud.githubusercontent.com/assets/697606/14835314/120f8690-0c01-11e6-849d-5148b5bf37b2.jpg)

**Comment by fevangelou** [comment]
You can see the error code though the browser's network tab in its web developer tools. If you can do that, it would be great. Otherwise, can you count how many seconds it takes from when you click upload and until this message shows up?

**Comment by jynxy** [comment]
WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403
http://www.domainhere.co.uk/wp-admin/async-upload.php Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2public-api.wordpress.com/:453 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by jynxy** [comment]
2016/04/26 22:53:29 [crit] 161006#0: *968 open() "/var/cache/nginx/client_temp/0000000750" failed (13: Permission denied), client: *.*.*.*, server: localhost, request: "POST /wp-admin/async-upload.php HTTP/1.1", host: "www.domainhere.co.uk", referrer: "http://www.domainhere.co.uk/wp-admin/upload.php"

**Comment by fevangelou** [comment]
Nginx, the way it's configured by Engintron, does not set /var/cache/nginx/ for Nginx's cache files. Are you 100% sure you're using Engintron?

**Comment by jynxy** [comment]
100% i can access it via whm

**Comment by fevangelou** [comment]
Did you use some other Nginx for cPanel plugin before? Cause I think that's the case and that plugin was not properly uninstalled.

**Comment by jynxy** [comment]
i dont remember doing so, but may well have done.

**Comment by fevangelou** [comment]
The old plugin is conflicting with Engintron. I'm pretty sure Nginx was never installed properly by Engintron exactly because it was present already by some other similar plugin.

It's best to cleanup your server from any old installation of Nginx (as in your case).

This falls into commercial support so please have a look here: https://github.com/engintron/engintron#i-need-commercial-support---do-you-offer-such-services

**Comment by jynxy** [comment]
Seems to be coming from the installer, has something changed maybe ?

Show precompiled Nginx modules...

nginx version: nginx/1.10.0
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_perl_module=dynamic --add-dynamic-module=njs-1c50334fbea6/nginx --with-threads --with-stream --with-stream_ssl_module --with-http_slice_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-http_v2_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'

**Comment by fevangelou** [comment]
You are just viewing a command from Nginx, retrieved via Engintron's WHM app. The Nginx build referenced there is clearly not coming from Engintron's setup.

**Comment by jynxy** [comment]
just running engintron setup on a server that has never seen nginx.

**Comment by jynxy** [comment]
issue appears to be /var was owned by named and not root, no idea why but thats fixed that issue.

now i have an issue where adblock plus is blocking the images, this appears on this server and a clean server, so i know its nothing thats been modified.

anything in the config that would effect this ?

GET x.x.x.x/300x250-300x250.jpg net::ERR_BLOCKED_BY_CLIENT

if i disable adblock the image loads ok.

Thanks

**Comment by fevangelou** [comment]
AdBlock is supposed to block web content based on some rules. So some rule kicks in and blocks your images. This is a browser plugin. Nginx can't cause the plugin to behave somehow. It's all in the plugin's settings or built-in behaviour.

**Comment by masteranalyze** [comment]
Solution : Uninstall AD BLOCK ,it cause alot of problems,not only on WP but on joomla components too.

You can live without ad block too,and with your website running good!
