### ISSUE TITLE
engintron mt

### ISSUE THREAD

**Issue by asciixster** [engintron/engintron#1382]
~engintron mt
=== MySQL Tuner ===

/root/.my.cnf: line 1: [client]: command not found
 >>  MySQLTuner 1.8.5 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.pl/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[!!] Attempted to use login credentials, but they were invalid

Operation completed.

**Comment by fevangelou** [comment]
Go into WHM at `Home » SQL Services » MySQL Root Password` and then reset your root password for your database. This will re-create the file /root/.my.cnf and MySQL Tuner will be able to login and run its diagnostics.

**Comment by asciixster** [comment]
Perfect!
Thank you
