### ISSUE TITLE
502 bad gateway (server behind NAT)

### ISSUE THREAD

**Issue by valentinlevrier** [engintron/engintron#1384]
Hello, 
We have a problem when using this plugin, at the end of the installation, our site displays an error 502 bad gateway.
After the plusgin activated (and timeout in Nginx logs), we only have access to cpanel & WHM via their dedicated ports.

The server is behind a NAT and we have defined our public IP in the custom rules. (set $PROXY_DOMAIN_OR_IP "xxx.xxx.xxx.xxx";)

Do you have a solution to this problem?

Sincerely

**Comment by fevangelou** [comment]
Is cPanel also configured properly for NAT?

**Comment by valentinlevrier** [comment]
> Is cPanel also configured properly for NAT?

Hello,
yes, cPanel works correctly without engintron. when it is activated, this problem occurs

Sincerely

**Comment by fevangelou** [comment]
My mistake, you should set the private (internal) IP in Nginx's custom_rules file.

**Comment by valentinlevrier** [comment]
Hello,

Should we set the private IP of our nginx server in the following option? 
set $PROXY_DOMAIN_OR_IP "xxx.xxx.xxx.xxx";

Thanks in advance

**Comment by valentinlevrier** [comment]
Hello,

After defining the private IP in the parameter everything works perfectly, and I could create reverse proxy rules without any problem.

Thanks for your help
