### ISSUE TITLE
Thank You Fotis + Question for HTTPOnly and Secure Cookie (Solved)

### ISSUE THREAD

**Issue by virtualos** [engintron/engintron#1388]
Hi,

Today I've come back to Engintron 2.0, Thank You for such a Professional, Nice, Clean crafted and Charming piece of art you've done!
Engintron definitely Rocks :)

Because of my website's payment gateway cookie I want to use **HTTPOnly;Secure;SameSite=none** for Apache or Nginx (I don't know which one I can use for this purpose) or maybe .htaccess file I should use but I have no idea!

When I was on litespeed I used below code in htaccess and it worked:
```
<IfModule LiteSpeed>
ForceSecureCookie secure same_site_none
</IfModule>
```
I used below code in Engintron's nginx.conf (http section) but not working:
`add_header                     Set-Cookie "Path=/; HttpOnly; Secure; SameSite=None";`

So any idea where and how I can get HTTPOnly and Secure Cookie enable in Engintron?

**Comment by virtualos** [comment]
Well Seekers Keepers :)
I found HTTPOnly and Secure Cookie solution:

Find Apache.conf (It depends on OS) almalinux is here:
/etc/apache2/conf.d/includes/pre_main_global.conf

then put this code in it and restart apache:
`Header always edit Set-Cookie (.*) "$1;HTTPOnly;Secure;SameSite=none"`

**Comment by fevangelou** [comment]
This will be enforced for all your sites. If you want to target a specific one, you can always append the relevant config on the site's .htaccess file.

**Comment by virtualos** [comment]
> This will be enforced for all your sites. If you want to target a specific one, you can always append the relevant config on the site's .htaccess file.

Thank you for your wisely advice; I removed it from Apache.conf and added to my website by .htaccess:

`<IfModule mod_headers.c>
  Header always edit Set-Cookie (.*) "$1;HTTPOnly;Secure;SameSite=none"
</IfModule>`
