### ISSUE TITLE
Renaming files and caching issue 

### ISSUE THREAD

**Issue by virtualos** [engintron/engintron#1389]
Hello Fotis,

After 2 days of Engintron 2, one customer contacted me about caching issue.

The senario is when I change a picture or css in website(1st time), I can see the changes so no problem, but if I CHANGE THOSE PICTURE OR CSS AGAIN (2nd time) I can't see the changes in browser!

What I have done to solve this problem so far are:
I changed browser from chrome to firefox to edge, fully clean browsers history and cache, wait for more than 1 minute(aka Engintron internal cache system to finish) and even I changed WHM/Engintron/Edit common_http.conf (All to 1m):

# Enable low duration browser cache for static data files (TTL is 1 min)
location ~* \.(?:csv|json|xml|rss|atom)$ {
    include proxy_params_common;
    include proxy_params_static;
    expires 1m;
}

# Enable browser cache for CSS / JS (TTL is 30 days)
location ~* \.(?:css|js)$ {
    include proxy_params_common;
    include proxy_params_static;
    expires 1m;
}

# Enable browser cache for images (TTL is 60 days)
location ~* \.(?:ico|jpg|jpeg|gif|png|webp)$ {
    include proxy_params_common;
    include proxy_params_static;
    expires 1m;
}

# Enable browser cache for fonts & fix @font-face cross-domain restriction (TTL is 60 days)
location ~* \.(eot|ttf|otf|woff|woff2|svg|svgz)$ {
    include proxy_params_common;
    include proxy_params_static;
    expires 1m;
}

Also I reset vps and I used this extension you offered in other topic: Web Developer
but none worked. Well finally I desparatly used WHM/Engintron/Purge cache & temp files which worked! but I feels like I missed something maybe my lack of knowledge or maybe I'm getting old and memory sucks...

p.s
I must add website I tested has no caching plugin it's base on WHMCS cms but other cms like wordpress behave the same :(

- OS: Almalinux 8.5
- cPanel: 100.0.5
- Nginx Mainline: 1.21.5
- In EA4 memchached + OPcache extensions for php7.4 are installed.
- I'm using MySQL8 wiki optimization: https://gist.github.com/fevangelou/0da9941e67a9c9bb2596

**Comment by virtualos** [comment]
> Hello Fotis,
> 
> After 2 days of Engintron 2, one customer contacted me about caching issue.
> 
> The senario is when I change a picture or css in website(1st time), I can see the changes so no problem, but if I CHANGE THOSE PICTURE OR CSS AGAIN (2nd time) I can't see the changes in browser!
> 
> What I have done to solve this problem so far are: I changed browser from chrome to firefox to edge, fully clean browsers history and cache, wait for more than 1 minute(aka Engintron internal cache system to finish) and even I changed WHM/Engintron/Edit common_http.conf (All to 1m):
> 
> # Enable low duration browser cache for static data files (TTL is 1 min)
> location ~* .(?:csv|json|xml|rss|atom)$ { include proxy_params_common; include proxy_params_static; expires 1m; }
> 
> # Enable browser cache for CSS / JS (TTL is 30 days)
> location ~* .(?:css|js)$ { include proxy_params_common; include proxy_params_static; expires 1m; }
> 
> # Enable browser cache for images (TTL is 60 days)
> location ~* .(?:ico|jpg|jpeg|gif|png|webp)$ { include proxy_params_common; include proxy_params_static; expires 1m; }
> 
> # Enable browser cache for fonts & fix @font-face cross-domain restriction (TTL is 60 days)
> location ~* .(eot|ttf|otf|woff|woff2|svg|svgz)$ { include proxy_params_common; include proxy_params_static; expires 1m; }
> 
> Also I reset vps and I used this extension you offered in other topic: Web Developer but none worked. Well finally I desparatly used WHM/Engintron/Purge cache & temp files which worked! but I feels like I missed something maybe my lack of knowledge or maybe I'm getting old and memory sucks...
> 
> p.s I must add website I tested has no caching plugin it's base on WHMCS cms but other cms like wordpress behave the same :(
> 
> * OS: Almalinux 8.5
> * cPanel: 100.0.5
> * Nginx Mainline: 1.21.5
> * In EA4 memchached + OPcache extensions for php7.4 are installed.
> * I'm using MySQL8 wiki optimization: https://gist.github.com/fevangelou/0da9941e67a9c9bb2596

OK!! Forget above post, I set Engintron settings reset to factory defaults (The old man thinks he found the issue) put some time to test deeper and here I found which I don't know is it bug or something else?!!

Senario:

I have a webpage with a link to a picture like:
<img src="{$WEB_ROOT}/templates/{$template}/assets/images/gallery/1.png">

And I have 5 picture files (all in {$WEB_ROOT}/templates/{$template}/assets/images/gallery/) which 1.png right now is assigned to link as you see:
1.png
2.png
3.png
4.png
5.png

Now without touching/changing link (leave it as it is) I just want to view and test pictures therefore I rename 1.png to blah1.png and afterwards rename 2.png to 1.png:
blah1.png
1.png
3.png
4.png
5.png

Engintron will 50% understand that file content of 1.png has been changed so when I hard reload webpage I can see new changed image! (sometimes Engintron won't get that and still shows old 1.png =aka blah1.png).

But If I do that again and rename 1.png to blah2.png then rename 3.png to 1.png, Engintron will not understand and with even hard reload webpage Engintron will show **content** of 2.png(=aka blah2.png) not 3.png:
blah1.png
blah2.png
1.png
4.png
5.png

I test this with 4.png and 5.png many many times and got this issue.

In nutshell:
Seems Engintron will not attention to renaming files if happens more than one time.

Note: THIS WILL NOT HAPPEN IF USER **REPLACE** FILES, ENGINTRON WILL UNDERSTAND REPLACE!!

**Comment by fevangelou** [comment]
There is a 10 sec cache for static files: https://github.com/engintron/engintron/blob/master/nginx/proxy_params_static#L47

You can switch this off entirely on your server by adding this in your custom_rules file:
```
set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
```

**Comment by virtualos** [comment]
Thanks Fotis!
