### ISSUE TITLE
Proxy Subdomain not working

### ISSUE THREAD

**Issue by fauzanariffin** [engintron/engintron#139]
### Overview
I noticed that [Proxy Subdomain](https://documentation.cpanel.net/display/CKB/Proxy+Subdomains+Use+the+cPanel+Service+SSL) is no longer working.

Proxy Subdomain is enabled by going to **cPanel > Tweak > Domain > [Proxy Subdomain](https://documentation.cpanel.net/display/ALD/Tweak+Settings+-+Domains#TweakSettings-Domains-Proxysubdomains)**

### Problem
If I typed http://cpanel.example.com, it will redirect me to https://cpanel.example.com%2C+cpanel.example.com:2083/

The expected result should be 
**http**://cpanel.emerain.com/ redirect to **https**://cpanel.emerain.com/

**Comment by fevangelou** [comment]
Type https://cpanel.emerain.com/ (notice the https) and cPanel will open up.

The redirect from http to https does not work perhaps because it's probably some fixed redirect rule in Apache from port 80 to port 2082 or 2083.

I will note this down however to possibly fix in Nginx directly.

I assume emerain.com is just one of the server's domains and it's not related to the server's hostname, right?

**Comment by esb** [comment]
I had this problem with http://webmail.xxxx domains.

The problem in my case was that the nginx proxy_params_common had the host name in both X-Forwarded-Host and X-Forwarded-Server. The webmail software like Horde and Squirrelmail try to extract a host name from the headers to use as a redirect location, but they get confused that there are two names and try to use both. This means we get malformed location headers with something like "http://www.mydomain.com, www.mydomain.com/rest_of_the_url".

I solved the problem by commenting out the X-Forwarded-Host header.

**Comment by fauzanariffin** [comment]
@fevangelou

> Type https://cpanel.emerain.com/ (notice the https) and cPanel will open up.

The direct link works.

> I assume emerain.com is just one of the server's domains and it's not related to the server's hostname, right?

Yes, emeraein.com is just one of the server's domains.

**Comment by fevangelou** [comment]
@esb thank you for the tip :)
