### ISSUE TITLE
How to install properly image_filter module on Engintron?

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1390]
Hey @fevangelou 
I see this for installation of the free source:
https://www.nginx.com/blog/responsive-images-without-headaches-nginx-plus/#mainline

Have 2 options one for Nginx 9R
and
**one for the open-source ( i believe its fit Engintron )**

I will be glad for a short way to install it for engintron, to download that ( I BELIVE YUM DOWNLOAD )
and put load_module inside nginx.conf.

**I already know what to do ( PLUS / MINUS ),
But
I will feel much better to hear if you have another setup for Engintron.**

**Comment by fevangelou** [comment]
For generic Nginx questions, it's best to discuss/ask in the main Nginx forum here: https://forum.nginx.org/

**Comment by locksmithunit** [comment]
@fevangelou common bro help me here.
this forum abounded for years...

as i said, i know install it and put the model cmd in the nginx.conf ( is not hard )

but i know Engintron build a little bit differently, i be glad for your help @fevangelou 
common is not even 1 min bro, help me here do it right. it's only a module, not the configuration.
