### ISSUE TITLE
EasyApache

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#1394]
Hi,

I have a CloudLinux server, should I use the latest EA4 profile from them or from Engintron?

**Comment by Friends4U** [comment]
Bump? Anyone...

**Comment by fevangelou** [comment]
CloudLinux promotes their own versions of PHP. The suggested profiles in Engintron use the PHP packages that ship from cPanel's repo. So use whatever you like. If you go with CL's packages, you'll probably use mod_lsapi and control resources via CL's options. I guess you paid for it for some reason in the first place, right?

**Comment by Friends4U** [comment]
Yes I do pay for it but I don't know if it is best to use those packages.
Thanks! I will try them.
