### ISSUE TITLE
User IP forwarding

### ISSUE THREAD

**Issue by nhadsall** [engintron/engintron#1396]
On Wordpress nginx isn't passing the IP somehow. The specific issue is the plugin wordfence that is a software firewall. It sees all traffic coming from the server's IP and then starts to block all traffic. Is this a but that isn't passing IPs to Apache -> FPM ? Thanks!

**Comment by ncabete** [comment]
Have a look at this issue here - https://github.com/engintron/engintron/issues/1387

The only way I could get around this is by using a Regex Processor to remove ::ffff: - not sure if you can do that with your WP plugin.

**Comment by nhadsall** [comment]
Thanks @ncabete, but sadly I gave up on engintron because of this. We offer hosting to multiple clients on each server, and we can't have all of them add specialized code because our hosting does strange things that PHP doesn't usually expect.
