### ISSUE TITLE
High memory usage for nginx

### ISSUE THREAD

**Issue by barchard** [engintron/engintron#1398]
With the latest version of Engintron, I am seeing excessively high memory usage. As a result, the oom is killing nginx processes and server is becoming unresponsive with high load. A snapshot of the memory usage is, on a 64GB system, is around 50GB. Any thoughts? Thanks

```
> [root@host ~]# top -b -o +%MEM | head -n 22
> top - 09:33:02 up 1 day, 3:25, 1 user, load average: 1.04, 1.40, 1.58
> Tasks: 1125 total, 1 running, 1121 sleeping, 0 stopped, 3 zombie
> %Cpu(s): 0.8 us, 0.8 sy, 0.0 ni, 98.3 id, 0.2 wa, 0.0 hi, 0.0 si, 0.0 st
> MiB Mem : 64146.1 total, 10513.6 free, 17720.5 used, 35912.1 buff/cache
> MiB Swap: 512.0 total, 411.0 free, 101.0 used. 44249.1 avail Mem 
> 
> PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
> 3149216 nginx 20 0 2822324 1.6g 32824 S 0.0 2.6 0:16.49 nginx
> 3149217 nginx 20 0 2822324 1.6g 29948 S 0.0 2.6 0:00.51 nginx
> 3149218 nginx 20 0 2822324 1.6g 9000 S 0.0 2.6 0:00.06 nginx
> 3149220 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx
> 3149222 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx
> 3149223 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx
> 3149224 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx
> 3149228 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx
> 3149230 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.07 nginx
> 3149232 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.06 nginx
> 3149234 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx
> 3149235 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.06 nginx
> 3149236 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx
> 3149237 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.06 nginx
> 3149238 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.06 nginx
> [root@host ~]# top -cd1
> 
> top - 09:33:35 up 1 day, 3:25, 1 user, load average: 1.30, 1.41, 1.57
> Tasks: 1137 total, 2 running, 1133 sleeping, 0 stopped, 2 zombie
> %Cpu(s): 4.1 us, 1.8 sy, 0.1 ni, 93.9 id, 0.0 wa, 0.0 hi, 0.1 si, 0.0 st
> MiB Mem : 64146.1 total, 10238.4 free, 17989.7 used, 35918.0 buff/cache
> MiB Swap: 512.0 total, 411.0 free, 101.0 used. 43979.7 avail Mem 
> 
> PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND 
> 3149216 nginx 20 0 2822324 1.6g 32960 S 10.6 2.6 0:17.35 nginx: worker process 
> 3149217 nginx 20 0 2822324 1.6g 29948 S 0.0 2.6 0:00.55 nginx: worker process 
> 3149218 nginx 20 0 2822324 1.6g 9000 S 0.0 2.6 0:00.06 nginx: worker process 
> 3149220 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx: worker process 
> 3149222 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx: worker process 
> 3149223 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx: worker process 
> 3149224 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx: worker process 
> 3149228 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx: worker process 
> 3149230 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.07 nginx: worker process 
> 3149232 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.06 nginx: worker process 
> 3149234 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx: worker process 
> 3149235 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.06 nginx: worker process 
> 3149236 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.05 nginx: worker process 
> 3149237 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.06 nginx: worker process 
> 3149238 nginx 20 0 2822324 1.6g 1228 S 0.0 2.6 0:00.06 nginx: worker process 
```

**Comment by fevangelou** [comment]
If I read the above lists correctly, 90+ of CPU is idle. High RAM usage with such low CPU is weird to me, unless you're config is not stock... You didn't mention number of sites, any tweaks you might have done, RAMdisk setup (?), sysctl.conf tweaks etc. etc.

**Comment by barchard** [comment]
A fair number of sites but not a lot of traffic. Typically everything was stable. No custom config. I had to upgrade the server and reduce the max memory used by nginx (max open files). Since then, this issue hasn't popped up again. Hope this helps:

> Please see the current Nginx settings:
> 
> [root@server ~]# egrep "worker_processes|worker_rlimit_nofile" /etc/nginx/nginx.conf
> worker_processes auto;
> worker_rlimit_nofile 65535;
> [root@server ~]# egrep "worker_connections" /etc/nginx/nginx.conf
> worker_connections 65535;
> Please note, the number of workers are limited by the amount of memory available on server. Also, as the number of workers increase, so will the memory consumption of NGINX.
> 
> Upon checking the system core limits, I can see as below:
> 
> [root@server ~]# ulimit -n
> 1024
> Current limit on Nginx master process:
> 
> [root@server ~]# cat /proc/$(cat /var/run/nginx.pid)/limits | grep open.files
> Max open files 1024 262144 files 
> soft limit = 1024
> Hard limit = 262144
> 
> Checked the Nginx worker processes limit:
> 
> [root@server ~]# ps --ppid $(cat /var/run/nginx.pid) -o %p|sed '1d'|xargs -I{} cat /proc/{}/limits|grep open.files
> Max open files 65535 65535 files 
> Max open files 65535 65535 files 
> Max open files 65535 65535 files 
> Max open files 65535 65535 files 
> Max open files 65535 65535 files 
> Max open files 65535 65535 files 
> Max open files 65535 65535 files 
> Max open files 65535 65535 files 
> Max open files 65535 65535 files 
> Max open files 65535 65535 files 
> Max open files 65535 65535 files 
> Soft limit: 65535 
> Hard limit: 65535
> 
> (Max open files) for nginx user is important when optimizing nginx configuration. Specially when setting worker_rlimit_nofile directive and worker_connections directive.
> 
> Since Nginx workers are consuming high memory usage, we can adjust/reduce the "worker_rlimit_nofile" and "worker_connections" values and test further.
>

**Comment by fevangelou** [comment]
What you changed is the hard limits Nginx uses to process requests. You effectively limited your server's throughput. The default value of "worker_rlimit_nofile" in Engintron will override the system's default limit of file descriptors (at least that's what it's supposed to do last time I checked).

**Comment by barchard** [comment]
Hi, it's been a while but this started happening again. Periodic random load spikes are taking down various services on the system. Do you have specific guidance on what to change or professional services to assist further? Thanks

**Comment by barchard** [comment]
Presently, this appears to be happening about every 2 weeks.

**Comment by dpunkturban** [comment]
Hi @barchard, what was the cause of your problem? Did you get it fixed? 😅

**Comment by barchard** [comment]
@dpunkturban no, I've moved to cPanel's native Nginx cache which allows the user to clear the cache on their own.
