### ISSUE TITLE
Feature request: GUI page or simplified page to Cloudflare

### ISSUE THREAD

**Issue by truls1502** [engintron/engintron#140]
Hello,

Is there possible to have such as GUI page or page with Flipswitch (On/Off) and textarea for Cloudflare. It is more easier for us who are not familiar with linux and coding. Of course they can click on advanced if they want to do terminal-style.

**Comment by fevangelou** [comment]
A proper configuration page inside the WHM plugin where you can set such things as you wish is already part of the Engintron roadmap :)

Especially the configuration page is what I plan to do within the next couple of months.

**Comment by truls1502** [comment]
could you please explain a little bit more, I'm not sure if I understand it correct.

"_is already part of the Engintron roadmap :)
Especially the configuration page is what I plan to do within the next couple of months._"

**Comment by fevangelou** [comment]
I meant that what you suggested already is part of the changes to come for Engintron :)
