### ISSUE TITLE
A warning pop up from the browser when purge the cache.

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1404]
Hey @fevangelou  how are you?

i experience the issue again:
https://ibb.co/kJMSGqM

i try to install several times, issue stop after day or 2 comebacks again.

The funny thing, its comeback only on one server of mine:
server.locksmithunit.com

i have server.locksmithunit.es not do it to me.
Don't know why…

What to do? please help :"(

**Comment by locksmithunit** [comment]
ok i delete it and delete the vendor, only one question.
its better install it (with curl) imidate how you get inside the SSH throw WHM/cPanel? (root folder /~)

Or install it in "cd /" and then install it with curl?

**Comment by fevangelou** [comment]
If you use Engintron v2, this should not be an issue anymore.

**Comment by locksmithunit** [comment]
It's because the Vendor rules, when you remove this Vendor from cPanel Engintron work much better.

I did what you recommended in your Git:
https://github.com/engintron/engintron/blob/master/cpanel/EasyApache_Profiles/EA4/Engintron_EA4_2022_v1_EL7.json

The best.
Amazing, Engintron 2 is very nice :)

**Comment by fevangelou** [comment]
Your commend makes no sense. There is no "vendor"-anything in the profiles...

**Comment by locksmithunit** [comment]
I don't know if you are real, really bro…
**Go to WHM > mod secure Vendors.**

You will start to understand what i am talking about.

I really not understand you, really i try figure you out, maybe it's English, maybe it's other communication problem
or maybe just you not like me.

But any answer of yours its against me, you are shaming yourself bro.
**You are really disappointment, i am not believe a guy like you create something so good like Engintron.**

EVERYTHING I EVER ASK YOU HERE, OVER ALL THIS YEAR'S, YOU NEVER ANSWERED, SOMETHING LIKE 2 YEARS.

I will not ask or response here anymore, you are useless any way and any comment of yours its against me,
**(sorry on my language, but you are a horrible person)**

Have a great day @fevangelou
