### ISSUE TITLE
ea-modsec2-rules-owasp-crs-3.3.2-3.6.1.cpanel.x86_64 (cPanel Vendor Rules)

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1405]
Hey @fevangelou , i notice in your EA4 profile you offer:
https://github.com/engintron/engintron/blob/master/cpanel/EasyApache_Profiles/EA4/Engintron_EA4_2022_v1_EL7.json

don't have this "cPanel Vendor Rules":
https://docs.cpanel.net/knowledge-base/security/owasp-modsecurity-crs/

Have reason why?
its not recommended with Engintron?

Be Glad for your recommendation.

**Comment by fevangelou** [comment]
Read the part where is says "What are the risks?". That's why :)
