### ISSUE TITLE
Force Query String cache

### ISSUE THREAD

**Issue by imorandinwnp** [engintron/engintron#1408]
Is there any way to ignore a Query String and force cache?

For example I have this URL: https://domain.com/wp-json/wp/v2/posts/70503?random=0.3176704700664371

the ?random=0.3176704700664371 part is invalidating the cache because it is different all the time.

Thanks,

Ignacio

**Comment by fevangelou** [comment]
It's not easy. If it's just one site for the entire server, you can change the pattern that Nginx uses to create a cache object, defined in `proxy_cache_key`. If the change is for a single site among many others, you'll have to replicate the setup for just this one site, which is a PITA really and out of the scope of the support provided here.
