### ISSUE TITLE
Install Redis via Engintron Wiki.

### ISSUE THREAD

**Issue by locksmithunit** [engintron/engintron#1410]
Hey whatsup @fevangelou 

I look on the wiki again and i want try Redis toghter with Engintron,
i see you offered in your wiki this:
https://engintron.com/docs/#/pages/optimization-guide-install-redis

Now, a couple of things before i install it via this wiki.

1. If your installation (this installation is a script from Engintron folder)
is actually cPanel repesotry?

From my experience, i know EasyApache4 / whm offered Memchace PHP package.
I don't know about Redis, i checked EasyApache4 but didn't see a Redis PHP package.
**won't be sure with you, i not going to install it 2 times.**

2. if i want to DELETE it in the feature?
It's possible?

3. Its better to open new ports?
As i did to Engintron?
Or it recommended work on Engintron PORT? or Other cPanel ports you know be better?
(I DON'T KNOW THIS WHY I ASK YOU)

I will be much more happy if you help me here :)
I really want to use Redis with Engintron, i even open topic on WordPress:
https://wordpress.org/support/topic/using-gcp-and-csf-need-to-open-port/#post-15545599

But he not pro like you, he knows more WordPress and not cPanel / Linux like you.
He has a lot of users, and i believe if you recommended on him inside your WIKI, its need to be very good.

Please help @fevangelou

**Comment by fevangelou** [comment]
The Redis installer just works. And your questions are irrelevant.

Constantly asking anything that pops up in your mind in here is not really productive...

If you don't know how to use any piece of software (like Redis), first learn more about it and then decide if you actually want to use it and how.

**Comment by locksmithunit** [comment]
Yeah, bro,                    
 i got you…
Any question i ask you is irrelevant, you notice to that?

Look here:
https://forums.cpanel.net/threads/redis-installation-on-cpanel.700025/

You must check with cPanel if this come from their repository!
They even say it in their docs and i clarify that in the forum, so my question is very relevant.

Really man, you have the best product in the market,
but you think you are space or above your clients, it's matter of time someone will invent NGINX like yours…

If you think you have a good support,
YOU ARE A NIGHTMARE, BRO. REALLY,
As we said from where i come from ( not far away from your country  ):
“To any donkey have replacement”

**It's mean:**
to any NGINX have a replacement,
the day will come and someone will create a better NGINX from yours.
And i promise you, i will not think twice.
If i have option and tell to all my clients and my friends not use your NGINX.

**You really need to work on yourself, bro, you destroy your own product with your ****** behavior / support .**

**Just for the record.**
I design my own cloud, and i know to work on many software, maybe Redis NEW for me,
but don't worry.

 ( yours answers all the time the same, or your shutdown my tickets ).

As i did it with Engintron, without your help
I will make it with Redis.
AS I DID IT WITH GOOGLE CLOUD AND BELIEVE ME, GCP IS MUCH MORE DIFFICULT TO UNDERSTAND FROM REDIS.

Really @fevangelou 
SHAME YOU, YOU ARE REALLY TROUBLE PERSON BRO.
I wish someone will do you the same, then you will understand how it feels.

BTW YES NEED TO OPEN A PORT FOR REDIS AND DO THE SAME THING AS YOU DO WITH ENGINTRON ( SPECIALLY ON GCP )
MORE Than THAT, I WILL TELL YOU A SECRET,
GCP HAVE SEPARATE FIREWALL, NEED TO OPEN THE PORT TWICE!

The answer was so simple.
