### ISSUE TITLE
Set different cache timeout for single user

### ISSUE THREAD

**Issue by avinashpudota** [engintron/engintron#1411]
Hi, I would like to have a different proxy_cache_valid time for a single user. Is it possible to have like this.
Can i edit custom_rules and add something like if ($SITE_URI ~* "domainname.com")

Thank you.

**Comment by fevangelou** [comment]
That wouldn't work. If you're looking to disable the cache for a single domain or path though, you can...

**Comment by avinashpudota** [comment]
Thanks for the update. Actually i am looking for opposite. I have one static site with heavy traffic. I want a longer cache timeout for this single user. I have setup Cloudflare for this domain which serves the purpose.
