### ISSUE TITLE
Hey, hello to everybody. (need little help)

### ISSUE THREAD

**Issue by Yossifsolman** [engintron/engintron#1412]
Hello, i start use Engintron 2.0v and i notice in the wiki have a Redis installation:
https://engintron.com/docs/#/pages/optimization-guide-install-redis

In the worst case, if i will need to delete it after. (if something go wrong, or i want to reinstall it)

To delete it throw YUM?
`yum remove redis`

Or should i do it with your script somehow? (maybe the script install add-ons or something, i believe you know better than me)
What is the best practice? (what you recommended if it was installed via your script?)

I already install it, is work perfect, just want for the feature be able to delete it properly if i want to.

Waiting for someone responses and thanks for the helpers.

**Comment by fevangelou** [comment]
The script is open source, so you can see the process followed for Redis to be installed. Could be "yum/dnf remove redis-server", I don't remember...

Most of the times, a standard package removal process is sufficient.

**Comment by Yossifsolman** [comment]
I am so sorry, @fevangelou ,
But you mean package removal **like this one from Redis Enterprise:**
https://docs.redis.com/latest/rs/installing-upgrading/uninstalling/

**This what you mean? ( if this is the right one, it is very nice uninstall script and easy to use )**

Or you mean to something also?
(like your script with -help in the end):
```
/opt/engintron/installers/install_redis_in_cpanel.sh -help

or

/opt/engintron/installers/install_redis_in_cpanel.sh -remove redis
```

Btw, i look on your script here in the git.
https://github.com/engintron/engintron/blob/master/installers/install_redis_in_cpanel.sh

This is a very nice script :)
This is not regular installation of Redis,
this script install repertories epel and much more.

Now i see on what you actually mean:
yum/dnf remove redis-server

dnf is inside the script, i see too( but this centos8 from what i see in your script )
and much more: (https://rpms.remirepo.net/enterprise/remi-release-7.rpm)

**You sure no needs to delete this "remirepos" repo as well?**



For the end, easy last thing:
If i want to refresh your Redis installation.
**Just re-run your script for Redis and this is it?**

@fevangelou 
Thank you again for your time.

**Comment by Yossifsolman** [comment]
@fevangelou  i fork both of the issues if you look.
This because i got this warning on TCP (Redis working 100% its a warning)

but i try to understand what is it:
```
[root@server ~]# lsof -i:6379
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
redis-ser 1105 redis    6u  IPv4  18854      0t0  TCP localhost:6379 (LISTEN)
[root@server ~]# redis-server
3019:C 13 May 2022 03:36:43.366 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
3019:C 13 May 2022 03:36:43.366 # Redis version=7.0.0, bits=64, commit=00000000, modified=0, pid=3019, just started
3019:C 13 May 2022 03:36:43.366 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
3019:M 13 May 2022 03:36:43.367 * Increased maximum number of open files to 10032 (it was originally set to 4096).
3019:M 13 May 2022 03:36:43.367 * monotonic clock: POSIX clock_gettime
3019:M 13 May 2022 03:36:43.367 # Warning: Could not create server TCP listening socket *:6379: bind: Address already in use
3019:M 13 May 2022 03:36:43.367 # Failed listening on port 6379 (TCP), aborting.
```
