### ISSUE TITLE
Lazy Loading - Reduce bandwidth

### ISSUE THREAD

**Issue by faca5** [engintron/engintron#1413]
Hello.

Is possible to change HTML content using Engintron? How?

Example:
We like to add new parameter loading="lazy" to all <img tags to reduce bandwith on both way (server - user) and speed up page load time. Let's image you have 1000 sites on server and 80% of them won't manually update their sites to new standards. It can takes years. Using NGINX for adding new tag if this doesn't exists maybe there can be drastic speed/load improvements. 

Lazy Loading
https://samanbaboli.medium.com/modify-html-pages-on-the-fly-using-nginx-2e7a2d069086
https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading
https://web.dev/browser-level-image-lazy-loading/

**Comment by fevangelou** [comment]
It is, but you shouldn't mess with the HTML output of pages. What if you append `loading="lazy"` inside an <img element that is rendered via JS code? You get a broken site because quotes may break string output. So, you should avoid this as possible.

**Comment by faca5** [comment]
This is new browser standard.
https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading
