### ISSUE TITLE
Permission issue on whm with root

### ISSUE THREAD

**Issue by nilnvoid** [engintron/engintron#143]
Hi,

The plugin page on whm gives this error, with root access, on new installation:
> You do not have sufficient permissions to access this page

**Comment by fevangelou** [comment]
Can you provide system info please and cPanelWHM version?

**Comment by fevangelou** [comment]
BTW, I re-tested on CentOS 6 & 7, latest WHM builds, systems up to date and had no issues accessing the Engintron plugin in WHM. Are you sure the user is root with full privileges in WHM?

**Comment by nilnvoid** [comment]
Installed again, the same error.

CLOUDLINUX 6.7 x86_64
cPanel/WHM 11.50.5

**Comment by fevangelou** [comment]
Can you please login as root user via a terminal and execute this command?

    whmapi1 myprivs

This will show what privileges the root user has. They are just indicators, no sensitive data is exposed. Can you please paste back the results of the above command as I currently don't have direct access to CloudLinux 6.x?

**Comment by nilnvoid** [comment]
Gives error, command not found. It seems that whmap1 is no implemented on 11.50

**Comment by hypegit** [comment]
Getting same problem on a new cpanel install.

root gets "You do not have sufficient permissions to access this page..."

WHM 11.42.1 (build 13)
CentOS 6 x64

whmapi1: command not found in ssh as root

**Comment by grantoos** [comment]
Same here. I just installed Engintron and went to WHM and got "You do not have sufficient permissions to access this page...". I also tried whmapi1 myrpvis in SSH as root and got "command not found".

**Comment by fevangelou** [comment]
The cPanel team advised on this change but I guess there are scenarios where the new check causes issues. I will revise the code in a while so you can use Engintron immediately. Hold on a sec...

**Comment by fevangelou** [comment]
@escherlat Any idea why some servers don't have the "whmapi1" shell command?

**Comment by hypegit** [comment]
I checked my install earlier today and was able to load it fine. I had not tried to access it or change anything since I made this post. Not sure what changed but it was working.

**Comment by fevangelou** [comment]
cPanel update in-between?

**Comment by grantoos** [comment]
@fevangelou Thanks for the quick response. I'm just waiting to use it! I've done all the optimizing except the Engintron stuff.

**Comment by hypegit** [comment]
Yes, looks like it. Build 14 now.

**Comment by fevangelou** [comment]
In the meantime I have updated the codebase to include the legacy check as well...

**Comment by grantoos** [comment]
What I did was upgrade Cpanel to build 14 and was able to get into Engintron no problem.

**Comment by jamesdoesdesign** [comment]
Was looking to install this as well. I have cpanel build 14 and still have all of the same problems as above. whmapi1 myprivs comes back -bash command not found. Any solutions?

**Comment by fevangelou** [comment]
Upgrade Engintron via the terminal. It will bring in some changes to the permissions check and allow you to have access again to Engintron's WHM plugin, without the need to upgrade cPanel.

**Comment by jamesdoesdesign** [comment]
Oh, I can't even get it to install let alone upgrade! haha! 

`Resolving raw.githubusercontent.com... XX.XXX.39.133
Connecting to raw.githubusercontent.com|XX.XXX.39.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20305 (20K) [application/octet-stream]
engintron.sh: Permission denied

Cannot write to “engintron.sh” (Success).
`

Perhaps my issue isn't the same. My apologies if it isn't.

**Comment by fevangelou** [comment]
Make sure you login as root user, don't just "su..." the installation.

Copy exactly as it is the quick command for installing Engintron from the welcome page here on GitHub.

**Comment by fevangelou** [comment]
Closed due to inactivity.

**Comment by feperrella** [comment]
Hi, i had this same issue, installed using root, however i usually use a different user to manage WHM,  root itself disabled.

Is there a way to manage without using root user?

**Comment by fevangelou** [comment]
Root can't be disabled. But you can choose not to do anything with it. In this case though, it's mandatory to be root for the installation to finish. You don't have to create keys et al, you can just perform the installation from cPanel's web terminal which will always open as root user.

**Comment by feperrella** [comment]
Yes, i know that, i did install using root, but after that point, i used my user to access WHM, and when accessing Engintron link in WHM it gives me that erro, i'm only able to access the user interface using root user.

**Comment by fevangelou** [comment]
Yeah, you must use root credentials in WHM so WHM acts as root user after that. I doubt cPanel would work properly otherwise. If the root user is not allowed to login remotely, there is no reason not to use it in WHM.
