### ISSUE TITLE
Password protected directories become open/public after installation

### ISSUE THREAD

**Issue by dazamc** [engintron/engintron#144]
After installing Engintron 1.6.1. all password protected directories became open/public.
https://www.cpanel.com/media/tutorials/passwdprotect.htm

**Comment by fevangelou** [comment]
Nginx proxies requests to Apache. Apache then decides whether to serve content or not. I don't see how Nginx could affect password protected directories in Apache...

You'll have to provide more info so I can help you out. Either copy the .htaccess file generated by cPanel at the root of some site or directory which is password protected or just post a url to some directory with a couple of dummy files and password protect it so we can see what's going on.

**Comment by dazamc** [comment]
Below is a copy of the .htaccess, but I can't demo at this stage as I reverted back because its a production server. Would you still like to see it on a non-production server?

`Options All Indexes
IndexOptions FancyIndexing
AuthName "Members-Only"
AuthUserFile "/home/rrfcorg/.htpasswds/public_html/files/private/passwd"
AuthType Basic
require valid-user`

**Comment by timmmmyboy** [comment]
I ran into this recently and we had to add the line `ErrorDocument 401 "Unauthorized Access"` in order for it to work.

**Comment by fevangelou** [comment]
@dazamc Did it work with @timmmmyboy solution?

**Comment by whosjose** [comment]
@fevangelou Didn't run into the issue using both CentOS 6 & 7 using the latest version of cPanel

**Comment by dazamc** [comment]
After I found this problem (28 Apr 2016), I removed engintron from my server.
I have just re-installed engintron now and the problem no longer exists.
We can possibly close this as the issue is no longer presenting itself.

**Comment by fevangelou** [comment]
Engintron does not mess with anything .htaccess related so I'm sure it was
something else.

**Comment by dazamc** [comment]
OK...Lets close this one. It is no longer a valid issue and there's no signs that Enginetron was causing the problem.

**Comment by fevangelou** [comment]
Great :)
