### ISSUE TITLE
What I have seen with Engintron on first load.

### ISSUE THREAD

**Issue by Kasayka1999** [engintron/engintron#1441]
On first load of website took around 4-5 seconds to load the website, then everything works amazing.
Also after an hour happen again the same thing.

**Comment by fevangelou** [comment]
The delays most likely boil down to slow Apache (and PHP-FPM if enabled) performance. Have a look at the optimization guides in the Engintron docs to improve your server's performance, as Nginx is one side of the performance coin ;)

**Comment by Kasayka1999** [comment]
Hi fevangelou, already did the optimizations as on 'BEYOND ENGINTRON - OPTIMIZATION GUIDES'
