### ISSUE TITLE
redirects to a node app and a wordpress blog on the same domain

### ISSUE THREAD

**Issue by Chris-Sibaja** [engintron/engintron#1447]
I try to add my "custom_rules" properties of "mydomain.com" and redirect to my node application and also when the $host is "mydomain.com/blog" send to my wordpress blog but it doesn't work, it always sends to me Node application, could someone tell me what I'm doing wrong? 

I would appreciate it very much I leave my conditions:

` if ($host = "mydomain.com/blog") {
    set $PROXY_SCHEME $scheme;
    set $PROXY_TO_PORT 8080;
 }
 
 if ($host = "www.mydomain.com/blog") {
    set $PROXY_SCHEME $scheme;
    set $PROXY_TO_PORT 8080;
 }

 if ($host = "mydomain.com") {
    set $PROXY_SCHEME "http";
    set $PROXY_TO_PORT 3001;
 }
 
 if ($host = "www.mydomain.com") {
    set $PROXY_SCHEME "http";
    set $PROXY_TO_PORT 3001;
 }`

**Comment by Chris-Sibaja** [comment]
Can somebody help me?

**Comment by fevangelou** [comment]
You need to use $SITE_URI: https://github.com/engintron/engintron/blob/master/nginx/custom_rules#L90

$host will only capture the domain and as such is effectively invalid in your case.

**Comment by Chris-Sibaja** [comment]
Thank you very much, I solved it in the following way in case someone else has the same problem:

`if ($host = "mydomain.com") {
set $PROXY_SCHEME "http";
set $PROXY_TO_PORT 3001;
}

if ($host = "www.mydomain.com") {
set $PROXY_SCHEME "http";
set $PROXY_TO_PORT 3001;
}

if ($SITE_URI ~* "mydomain.com/blog") {
set $PROXY_SCHEME $scheme;
set $PROXY_TO_PORT 8080;
}

if ($SITE_URI ~* "www.mydomain.com/blog") {
set $PROXY_SCHEME $scheme;
set $PROXY_TO_PORT 8080;
}`
