### ISSUE TITLE
http/2 support missing 

### ISSUE THREAD

**Issue by Jockel725** [engintron/engintron#1457]
Hi there,
after installation Engintron to WHM/Cpanel server, I found no http/2 support. Only http/1 in place.

So I went to EasyApache 4, and installed the nginx http/2 Modul and Brotli as well from there.
All is working fine now.
Http/2 support is given, brotli as well.

My question:
Is this the right way of instruction?
I mix of Engintron and EA4 Ngnix Moduls?
Even it's working obviously, I don't feel well somehow.

Please explain how to activate http/2 and Brotli in Engintron.

Thanks and nice regards
Jakob

**Comment by fevangelou** [comment]
The Nginx configs are ready for HTTP/2: https://github.com/engintron/engintron/blob/master/nginx/utilities/https_vhosts.php#L53

I can't say why it doesn't work on your server though. To be honest, you're the first to report such a thing since HTTP/2 support was added.
