### ISSUE TITLE
Development and roadmap

### ISSUE THREAD

**Issue by bwbos** [engintron/engintron#1458]
With satisfaction I use Engintron. I see activity, but little. The roadmap has been like this for a while now. The concrete question is: is Engintron still being actively developed, or will it still work as long as it works? It looks like new functionality will not actually become available.

**Comment by bwbos** [comment]
No reply in 2 months…. that probably says it all.

**Comment by fevangelou** [comment]
Engintron is feature complete for now. The roadmap is not bound to a certain date.

Updates will come as needed.
