### ISSUE TITLE
Is Enigtron 2.2 compatible with cPanel 110.0x? 

### ISSUE THREAD

**Issue by gitoutofhere97** [engintron/engintron#1468]
We have been running Enigtron for several years - largely without issues.  Has mostly worked amazingly well. We were most recently running v 2.1 without problems.

(Server is at cPanel 110.0.17 - needs to be upgraded but likely eol at Centos 7.9)

We had issues yesterday with expired Let's Encrypt SSL certificates that "should" have auto-renewed via Let's Encrypt/AutoSSL.  All sites on the server were coming up as 'unsafe' in browsers b/c of the expired certificates.  This happened last summer and we got it resolved manually and never figured out exactly why it happened.

After renewing the certificates via AutoSSL, things were  still not working right.  In reviewing the issue this time, I saw the notice from Enigtron that v2.2 update was available-  so I updated it.  

Now I only can get a 502 'Bad Gateway' error whenever Enigtron is enabled.  And renewed SSL certificates are still not working properly. 

I have tried restarting the server, restarting the services, disabling and re-enabling Enigtron, purging the cache, etc.  

Are you aware of issues/ possible incompatibility?  If there is a problem, is there a way to roll back to v2.1 which has been running well?

Thanks very much for any insights or suggestions.

**Comment by gitoutofhere97** [comment]
Forgot to mention - no configuration errors are showing up for either Nginx or Apache.

**Comment by fevangelou** [comment]
Engintron should have no issues with latest cPanel. Check if you had any customizations or if the upgrade somehow triggered another repo and installed Nginx e.g. from Almalinux and not Nginx.com.

I've also seen the SSL error as well but since it was random I assumed it was cPanel related. If you flush the cache in Nginx, it usually resolves the issue.

**Comment by gitoutofhere97** [comment]
> Engintron should have no issues with latest cPanel. Check if you had any customizations or if the upgrade somehow triggered another repo and installed Nginx e.g. from Almalinux and not Nginx.com.
> 
> I've also seen the SSL error as well but since it was random I assumed it was cPanel related. If you flush the cache in Nginx, it usually resolves the issue.

Thank you very much.  

I cannot presently run the latest cPanel which is why I am asking a version-specific question about cPanel 110.0.x . 

Enigtron 2.1 was running smoothly on cPanel 110.0.17 prior to the latest Enigtron update (to v. 2.2). 

Now it definitely will NOT work.  Also I have resolved the SSL issues (including flushing the cache) but still every time I enable Enigtron 2.2, the 502 "Bad Gateway" error returns for all sites.  That error disappears as soon as I disable Enigtron 2.2.    

All status and configurations are still showing as 'no errors.' 

I hope I might roll back Enigtron until the server is either upgraded to a version of Linux that can accommodate newer WHM and cPanel versions, or it is replaced.   If v 2.2 won't work and I cannot roll it back, I will just need to leave it off for now.

Thank you again.

**Comment by fevangelou** [comment]
There is no config change in Engintron in the last version that may have borked this part. I firmly believe the problem is in some custom config (check your custom rules, it's important) or the system entirely, e.g. like I said, an update forced Nginx to be installed from some other repo (and not Nginx.com's).

**Comment by fevangelou** [comment]
You can't have both Engintron and cPanel's Nginx.
