### ISSUE TITLE
Nginx crashes when placing custom rules

### ISSUE THREAD

**Issue by alerickert** [engintron/engintron#1469]
I have a plugin to automatically convert images to webp, which asks me for these settings:
https://mattplugins.com/docs/nginx-configuration

# BEGIN Converter for Media
set $ext_avif ".avif";
if ($http_accept !~* "image/avif") {
    set $ext_avif "";
}
 
set $ext_webp ".webp";
if ($http_accept !~* "image/webp") {
    set $ext_webp "";
}
 
location ~ /wp-content/(?<path>.+)\.(?<ext>jpe?g|png|gif|webp)$ {
    add_header Vary Accept;
    add_header Cache-Control "private";
    expires 365d;
    try_files
        /wp-content/uploads-webpc/$path.$ext$ext_avif
        /wp-content/uploads-webpc/$path.$ext$ext_webp
        $uri =404;
}
# END Converter for Media

however when I put them in custom rules, nginx crashes.

Any ideas?

**Comment by fevangelou** [comment]
These rules imply Nginx is used as your primary web server and not as a reverse caching proxy server.

Your webserver is actually Apache, so look for rules to place in .htaccess.
