### ISSUE TITLE
Mysqltuner

### ISSUE THREAD

**Issue by truls1502** [engintron/engintron#147]
Hi @fevangelou 

I was on your wiki-page [Beyond-Engintron:-Optimizing-MySQL](https://github.com/engintron/engintron/wiki/07.-Beyond-Engintron:-Optimizing-MySQL)

Would you not recommend to run mysqltuner and optimize the mysql instead of simply them following values provided?

Since they vary depending on the server specs and mysql usage etc.

**Comment by fevangelou** [comment]
MySQL Tuner as well as Tuning Primer (another similar tool), are great for getting insights to your database. The my.cnf file I provide is a starting point. Beyond that you MUST use either of these tools to further tweak MySQL's configuration and therefore improve your server's performance.

In an upcoming update of Engintron, I will have these 2 tools bundled, including a new tool to defrag/optimize all databases using MySQL's CLI commands :)
