### ISSUE TITLE
Further development plans

### ISSUE THREAD

**Issue by onurtural** [engintron/engintron#1474]
Hello team,

I'm reaching out to inquire about the future of the Engintron project. Can we anticipate further development and updates, or are there any plans to discontinue it? I've noticed a period of quietness recently, and I'm curious if this indicates a shift in direction or if it's simply a lull in activity. Perhaps I've been overly skeptical, but I'd appreciate any clarification you can provide.

Thank you.

**Comment by fevangelou** [comment]
Engintron is actively developed cause it's used daily by yours truly.

However being a mature project (it's 10 years already), it's natural that new features will be added more rarely and only when they make sense.

Engintron at its core does one thing exceptionally well. And that's to use Nginx in the best way possible as a reverse caching proxy. Don't confuse that with other software. And remember Nginx is updated separately and automatically when your system updates.

**Comment by onurtural** [comment]
Thanx for the quick reply. I am just setting up a new server with Almalinux v9.3.0 STANDART kvm and needed to be sure :)) Have a nice evening ✌️
