### ISSUE TITLE
URGENT - Remove Tracking Code / Spyware from the software

### ISSUE THREAD

**Issue by faca5** [engintron/engintron#1476]
Hello.

Please remove any tracking code (spyware) from your excellent software.

Reference:
https://github.com/engintron/engintron/blob/07382adcc37f4ff84b0db995948596c94bd206d6/app/engintron.php#L871

Code:
```
    <script src="https://engintron.com/app/js/services.js?t=<?php echo date('Ymd'); ?>"></script>
    <script>(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};m[i].l=1*new Date();for(var j=0;j<document.scripts.length;j++){if(document.scripts[j].src===r){return;}}k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})(window,document,"script","https://cdn.jsdelivr.net/npm/yandex-metrica-watch/tag.js","ym");ym(87045362,"init",{clickmap:true,trackLinks:true,accurateTrackBounce:true,trackHash:true });</script><noscript><div><img src="https://mc.yandex.ru/watch/87045362" style="position:absolute;left:-9999px;" alt="" /></div></noscript>
```
Connecting to "https://mc.yandex.ru/watch/87045362" these days is not great idea when privacy should be higher level. Yandex, Google, Facebook similar... We don't like to have any tracking code in that software.

Thank you!

**Comment by faca5** [comment]
You are breaking EU laws with these 2 lines:
- Cookies Law
- GDPR Law

Tracking code creates cookies without our previous permission.

Tracking code sending our IP address to 3rd party without our permissions.

There is no opt-in. When we can accept or denied or get more information about it. How data are collections and used etc.

Please just remove these 2 lines in official version. Thank you!

**Comment by fevangelou** [comment]
Tracking is GDPR compliant - no IPs are stored, bare minimum anonymous
tracking only.

If you don't want to use Engintron, remove it. No one is forcing you to use
it.

F.
