### ISSUE TITLE
Remove tracking code to external source

### ISSUE THREAD

**Issue by faca5** [engintron/engintron#1477]
https://github.com/engintron/engintron/blob/07382adcc37f4ff84b0db995948596c94bd206d6/app/engintron.php#L870

**Comment by fevangelou** [comment]
The next update in Engintron will include optional bot protection which covers Baidu as well.

In the meantime, I'd recommend closing port 9998 in your server or locking access to it for select IPs.

**Comment by fevangelou** [comment]
Tracking is GDPR compliant - no IPs are stored, bare minimum anonymous tracking only.

If you don't want to use Engintron, remove it. No one is forcing you to use it.
