### ISSUE TITLE
Mobile themes

### ISSUE THREAD

**Issue by brinsleyparagao** [engintron/engintron#148]
Hello, In wordpress, when use a separate theme for mobile themes, have this issues...
Sometimes in desktop show mobile themes and sometimes in smarthphones/tables show the desktop theme.

**Comment by fevangelou** [comment]
If the selection between mobile and desktop theme is done using PHP and not JavaScript (as you should), then what you see is the effect of micro-caching. But even then, a page will be cached only for a second. If you can't change your site's code to detect what browser a visitor is using (with JavaScript), then you can simply disable micro-caching in Engintron: https://github.com/engintron/engintron/wiki/02.-Installation-(and-updates)#a-word-about-micro-caching
