### ISSUE TITLE
nginx 1.25+ [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead

### ISSUE THREAD

**Issue by konstantinosbotonakis** [engintron/engintron#1481]
Since nginx version 1.25+
the "listen ... http2" directive is deprecated.

So basically we need to change this:
`listen 443 ssl http2;`

to:

`listen 443 ssl;
http2 on;`

References: 
https://hg.nginx.org/nginx/rev/08ef02ad5c54
https://community.centminmod.com/threads/nginx-1-25-1-release-http2-parameter-deprecation.23890/

**Comment by fevangelou** [comment]
Can you confirm you only see this warning on Almalinux 8+ or Ubuntu 20.04+?

**Comment by konstantinosbotonakis** [comment]
I can confirm the warning is shown with Almalinux 8.x versions. I can't test it with Ubuntu at the moment.

**Comment by fevangelou** [comment]
Thanks - I'll update Engintron soon to address the warning.

**Comment by fevangelou** [comment]
Fixed in v2.4.
