### ISSUE TITLE
Almalinux 9 compatible

### ISSUE THREAD

**Issue by ribo72** [engintron/engintron#1495]
I installed engintron and it worked. But suddenly last night stopped to work.
Please check my comment in my previous closed issue.
https://github.com/engintron/engintron/issues/1494

**Comment by maurocordioli** [comment]
check the status via the engintron ui frontend for an error "nginx[1179378]: nginx: [emerg] unknown directive "http2" in /etc/nginx/conf.d/default_https.conf:15" 
(anothe user here)
