### ISSUE TITLE
NGINX Tries to Proxy External Domains

### ISSUE THREAD

**Issue by tess0072** [engintron/engintron#150]
I noticed from taking a glance at my nginx error log that it tries to reverse proxy domains regardless of whether or not it should. For example:

2016/05/02 19:16:01 [error]: *59 upstream timed out (110: Connection timed out) while connecting to upstream, client: XXX.XXX.XXX.XXX, server: localhost, request: "GET http://www.mafengwo.cn/ HTTP/1.1", upstream: "http://XXX.XXX.XXX.XXX:8080/", host: "www.mafengwo.cn"

I do not own the domain "www.mafengwo.cn" nor does it's IP point to my server. So I understand that this is probably just some sort of attack but I am wondering why Nginx actually tries to proxy this domain at all since it does not resolve to my server.

Is there any way to stop this behaviour? My firewall is not happy with Nginx trying to get out on port 8080 as I do not allow outbound traffic on that port. Not that it would make a difference if i did open the port, nginx would still just timeout unless "www.mafengwo.cn" happens to be listening on port 8080.

Thanks,

tess0072

**Comment by fevangelou** [comment]
Someone could have just had that IP associated with the domain you mention in their hosts file. IPs are re-used all the time. It's not a security issue.

As for your firewall not being happy to have port 8080 open. Well, Apache responds in 8080. Not some insecure service. So it's not a security issue either.

**Comment by tess0072** [comment]
I understand that its not a big deal that the requests reach my server. I'm just curious if theres a way to stop nginx from trying to proxy these requests that do not resolve to the server itself.

**Comment by tess0072** [comment]
For example, could nginx be configured to return a 444 for these requests?

**Comment by fevangelou** [comment]
No. Because anyone can fake this easily as I explained. Just add your server's IP in your PC's hosts file and have google.com assigned to it. When you hit "google.com" in your browser, your server will come up. Nginx will retrieve an incoming request in your server's IP and try to pass on relevant domain info to Apache. Google.com obviously does not exist on your server so this will be logged by Nginx in the error log.

Your case may simply be some dev who had that IP associated with an old domain in their hosts file.

**Comment by fevangelou** [comment]
No, Nginx cannot do that (return 444) because it acts like a black box, passing requests to Apache. It does not have specific domain definitions. But that doesn't mean this is a security issue. Apache would log the same thing if someone had manipulated their hosts file to have your server's IP point to some fake domain.

**Comment by tess0072** [comment]
I understand that this is not a security issue. In your example using google.com however what I am seeing is that nginx is attempting to reverse proxy to google.com's IP:8080. So it is resolving google.com to an IP and then the request proceeds to that IP on port 8080. It does not pass the request on to Apache as you mentioned.

**Comment by tess0072** [comment]
See this example:

2016/05/02 19:29:13 [error] 26847#26847: *71 upstream timed out (110: Connection timed out) while connecting to upstream, client: 80.82.78.38, server: localhost, request: "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1", upstream: "http://103.235.46.39:8080/cache/global/img/gs.gif", host: "www.baidu.com"

Why even bother trying to connect to 103.235.46.39:8080 when that resolves to somewhere in Hong Kong... not my server.

**Comment by fevangelou** [comment]
My mistake. I should have explained better (kind of late where I am now)...

So, someone can fake the initial routing (your IP, fake domain, Nginx will respond, Apache won't). Nginx uses Google's resolvers to get the IP of a domain. If the fake/wrong domain points elsewhere, Nginx will get that other IP and redirect to that other IP:8080.

**Comment by tess0072** [comment]
Right, makes sense. What I've done in that case is updated nginx to use my DNS servers, which only have my dns zones defined and so it will not resolve the bad domain and as a result not try and proxy to it.

**Comment by bojin** [comment]
What if the fake/wrong domain actually listens on port 8080? Seems like nginx will process such request. I think that engintron should be configured to make requests to upstream IP if the IP address of the upstream is actually on the server.

**Comment by tess0072** [comment]
I agree that nginx should only process requests for upstream IPs... My solution of using the local DNS server solved the issue because the wouldnt be any domains defined for anything that isnt upstream but it is a risk for sure. Also, I've blocked outbound traffic on 8080 originating from nginx.

**Comment by bojin** [comment]
Yes, this is a solution but requires custom setup. Imagine multiple cpanel servers using engintron as nginx frontend. Each of these servers will have multiple domains listening on port 8080. It's possible to create a botnet connecting one server to another..... there are also a lot of other applications which by default listen on port 8080 ( like some java apps ). If engintron goal is to make easy nginx implementation for cpanel, fixing the upstream problem is a must..

**Comment by tess0072** [comment]
Yup! I'm with you, this has been a P.I.T.A to manage / secure.

**Comment by bojin** [comment]
Yes, it's actually an open proxy for servers listening on port 8080

**Comment by tess0072** [comment]
@bojin how would you propose solving the issue. The more I think about it the less I am sure how to implement it. Would you put an IF statement inside the location block of code that checks if $PROXY_DOMAIN_OR_IP is in the following list [IP's ALLOWED], that would default to all the IPs defined on the server?

**Comment by tess0072** [comment]
What about something like this in the HTTP block:

`geo $block_almost_everybody {
    default         0;
    XXX.XXX.XXX.XXX   1;
}

server {
    ....
    if ($block_almost_everybody) {
        return 444;
    }
    ....
}`

**Comment by bojin** [comment]
I would generate separate vhost for each cpanel domain and setup upstream for this vhost. And everything else goes to 4xx. For now I'm setting
 
set $PROXY_DOMAIN_OR_IP "127.0.0.1"

in /etc/nginx/custom_rules

because i have to go to sleep.
