### ISSUE TITLE
Why use mod_rpaf? Consider mod_remoteip

### ISSUE THREAD

**Issue by azirer** [engintron/engintron#152]
I think that mod_rpaf is not supported anymore. There is mod_remoteip which seems to do the same job if not a better one.

**Comment by fevangelou** [comment]
Mod_rpaf is used for Apache 2.2 (if you look closer at the installer) and
it's an up to date fork of the original codebase. Mod_remoteip is what's
used for Apache 2.4.

**Comment by azirer** [comment]
Thank you! Issue closed
