### ISSUE TITLE
 Suspicious process 

### ISSUE THREAD

**Issue by rmxs** [engintron/engintron#153]
Καλημέρα,

I finish with the engintron conf yesterday and till then LFD spam me with the suspicious process runing.
I saw 2 ips that my server connects 
tcp: 0.0.0.0:80 -> 0.0.0.0:0
tcp: 5.9.xx.xxx:80 -> 66.249.66.69:37045
tcp: 5.9.xx.xxx:80 -> 178.128.14.227:52570

Files open by the process (if any):

/dev/null
/dev/null
/var/log/nginx/error.log
/var/log/nginx/access.log
/var/log/nginx/error.log
[eventpoll]
[eventfd]
[eventfd]

In other email..

Network connections by the process (if any):

tcp: 0.0.0.0:80 -> 0.0.0.0:0
tcp: tcp: 5.9.xx.xxx:80 -> 62.138.0.25:35234
tcp:tcp: 5.9.xx.xxx:80 -> 62.138.0.25:35021
tcp: tcp: 5.9.xx.xxx:80 -> 108.162.229.50:14281
tcp: tcp: 5.9.xx.xxx:80 -> 108.162.218.59:29284
tcp: tcp: 5.9.xx.xxx:80 -> 101.119.20.21:15295
tcp: tcp: 5.9.xx.xxx:80 -> 101.119.20.8:45792

Files open by the process (if any):

/dev/null
/dev/null
/var/log/nginx/error.log
/var/log/nginx/access.log
/var/log/nginx/error.log
/tmp/engintron_dynamic/0/1d/2d9a11d5b218f3f610f4b8f2ab6ba1d0
[eventpoll]
[eventfd]
[eventfd]

What are this ips? 

Also you have to mention that users with LFD have to exlude /usr/sbin/nginx

**Comment by fevangelou** [comment]
Not really. On a CSF stock installation with what I consider the basic setup (DoS protection, basic notifications etc.) you do not need to exclude Nginx's binary. Why should you?

I think it boils down to your current LFD setup but it's out of the support I can provide you.

If possible, I'd recommend testing on a different machine with stock CSF installed and cPanel latest. You should not see these issues...
