### ISSUE TITLE
mod_remoteip not loading

### ISSUE THREAD

**Issue by allanw1** [engintron/engintron#156]
CentOS 7.2 and Cpanel 56 with EasyApache4

I spent a few hours trying to figure out why Apache + nginx + Cloudflare wasn't passing along the visitor's IP into PHP. The REMOTE_ADDR would show the server's IP.

So I wasted a bunch of time setting up mod_cloudflare, trying to figure out why it didn't do anything, and only realized much later on that mod_remoteip was installed with engintron and was supposed to be enabled.

1. Its configuration file was incorrectly placed into /etc/apache2/conf.d/includes/remoteip.conf and it never loaded the module (httpd -M didn't show it) and nowhere did it ever output an error message indicating something was wrong. I moved this conf file to /etc/apache2/conf.modules.d/ and everything works now.

2. Since it's a bit confusing for newbies, I also recommend mentioning in the docs that mod_cloudflare isn't necessary and that mod_remoteip provides that functionality here.

3. You may want to mention following these steps so that nginx's logs have the visitor's IP instead of cloudflare. https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx-

**Comment by fevangelou** [comment]
All this is in place already. However if you read carefully in the requirements section of Engintron, EasyApache 4 (still flagged as beta from cPanel themselves) is not yet supported. That's why mod_remoteip was not installed in the new structure imposed by EasyApache4 for Apache's config files.

EA4 support will come with v1.7.0 of Engintron.

**Comment by allanw1** [comment]
Okay. I was just under the impression from reading the other bug report about EA 4 that the only thing that had to be considered was to remove the version check from the script since everything was supported already.

**Comment by fevangelou** [comment]
If it were that simple, I'd have removed it already :)
