### ISSUE TITLE
site noat loading

### ISSUE THREAD

**Issue by hrvoje29** [engintron/engintron#158]
If site is not dns propagated, site is not loading, the static dns entry is in host file on local pc, when i disable engintron site work OK

**Comment by fevangelou** [comment]
Look at the custom rules file in Engintron's WHM app. Read the whole thing.

Following the commented examples there, simply add your domain to point to the server's IP, as if you were using your domain with CloudFlare. This will skip the DNS check and redirect the domain correctly.

In the end you'll have something like this in there:

if ($host ~ "mydomain.com") {
	set $PROXY_DOMAIN_OR_IP "1.2.3.4";
}

After you do this, restart both Apache and Nginx. Remember that when you switch the domain to point to the actual IP in its DNS records, you should probably remove the above "if" statement and again restart Apache & Nginx.

**Comment by hrvoje29** [comment]
ok now its works tnx
