### ISSUE TITLE
Two errors when installing Enginetron

### ISSUE THREAD

**Issue by mormondancer1** [engintron/engintron#160]
When I try to install enginetron I get two errors.  

One is:

![screen shot 2016-06-02 at 2 49 41 pm](https://cloud.githubusercontent.com/assets/10783118/15756917/58513d1e-28d1-11e6-8c58-58622a33bbad.png)

the other is:
![screen shot 2016-06-02 at 2 51 08 pm](https://cloud.githubusercontent.com/assets/10783118/15756955/7b1afba0-28d1-11e6-8eab-bf9f73081160.png)

Here's my entire log:

root@server.mytutorialpodcast.com [/]# cd /; rm -f engintron.sh; wget --no-check-certificate https://raw.githubusercontent.com/engintron/engintron/master/engintron.sh; sh engintron.sh install
--2016-06-02 18:43:42--  https://raw.githubusercontent.com/engintron/engintron/master/engintron.sh
Resolving raw.githubusercontent.com... 23.235.40.133
Connecting to raw.githubusercontent.com|23.235.40.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20305 (20K) [application/octet-stream]
Saving to: “engintron.sh”

100%[======================================================================================================================================================================================================================================>] 20,305      --.-K/s   in 0.03s   

2016-06-02 18:43:42 (618 KB/s) - “engintron.sh” saved [20305/20305]

/usr/local/cpanel/3rdparty/bin/perl: symbol lookup error: /home/mytutori/perl5/lib/perl5/auto/List/Util/Util.so: undefined symbol: Perl_Istack_sp_ptr

*****************************************************

 ENGINTRON ERROR:
 This server has EasyApache version 4 (beta)
 installed and Engintron is currently only compatible
 with EasyApache version 3 only!
 EasyApache version 4 will be supported
 in Engintron version 1.6.

 --- Installation aborted ---

*****************************************************
First question: what does perl have to do with the installer?

second question: why is the installer still saying I have EasyApache 4 installed when I'm using EasyApache 3?

**Comment by fevangelou** [comment]
It seems you haven't pasted the installation command correctly.

The last part should be:

bash engintron.sh install

and not:

sh engintron.sh install

In other words, just copy/paste the quick command from the GitHub repo.

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by mormondancer1** [comment]
I tried that still getting those same two errors.

**Comment by fevangelou** [comment]
Are you 100% you don't have EA4 enabled in cPanel?

**Comment by mormondancer1** [comment]
![screen shot 2016-06-02 at 8 10 16 pm](https://cloud.githubusercontent.com/assets/10783118/15765025/1da4606a-28fe-11e6-85c6-ce4dc43fd511.png)

**Comment by fevangelou** [comment]
Assuming you have the latest cPanel build installed, disable the EasyApache version check and see how far the installation goes.

Follow the installation steps but don't do the last step (bash engintron.sh). Instead edit this file on your server and change line 429 https://github.com/engintron/engintron/blob/master/engintron.sh#L429 from:
    GET_EA3_VERSION=$(/scripts/easyapache --version | grep "Easy Apache v3")
to
    GET_EA3_VERSION=1

Then simply execute the installer with:
    bash engintron.sh

Let me know how it goes.

**Comment by mormondancer1** [comment]
now it's giving me this error:

root@server.mytutorialpodcast.com [/]# bash engintron.sh install





engintron.sh: line 429: 1: command not found

**Comment by fevangelou** [comment]
Delete lines 429 to 449 entirely and try again.

**Comment by mormondancer1** [comment]
Never mind I have it installed finally.

**Comment by fevangelou** [comment]
Hey, don't just throw me a "never mind"! :)

What was it?

**Comment by mormondancer1** [comment]
Just had to move the 1 next to the =
