### ISSUE TITLE
Add module "nginx-push-stream-module"

### ISSUE THREAD

**Issue by Akylenok** [engintron/engintron#161]
Hello. 

Tell me, please, that you need to do to connect to nginx module "nginx-push-stream-module" (the module itself is located here https://github.com/wandenberg/nginx-push-stream-module). 

I'm new to using nginx, so any help would be appreciated, especially detailed ;)

**Comment by fevangelou** [comment]
You can't use this module with Engintron's Nginx installation because it requires a custom Nginx installation. Engintron on the other hand uses Nginx's CentOS repo to install Nginx on your cPanel server, which makes the process easier and it allows for automatic Nginx updating when cPanel updates the server software.

**Comment by Akylenok** [comment]
What if you add in installer custom configuration file and a directory with additional modules, in which the user of your wonderful designs will be able to register additional options or extensions that it needs? It will make your product even more versatile and you can add a 9th item to the list of features ? ;)

**Comment by fevangelou** [comment]
The main "selling" point of Engintron is easy upgrades for everything. Why
should you wait, for example, for Engintron itself to get updated when a
new version of Nginx is already available?

The solution however for additional Nginx modules will come soon as Nginx
is already changing to allow for the installation of such modules using the
repo for each Linux distro. So in your case it will soon be possible to
perform: $ yum install nginx-push-stream

So either wait a while or install Engintron now, remove Nginx manually and
then rebuild with your custom modules in. But this will break future
automated Nginx updates for you.
