### ISSUE TITLE
Tried Update - nginx: unrecognized service

### ISSUE THREAD

**Issue by virtuali1151** [engintron/engintron#162]
Ive had the plugin install for months with no issues, then I tried to update it, and I first got the error about not being compatible with EA4, so I updated the line of code (GET_EA3_VERSION=1) as suggested and tried to install again and It does install but not nginx properly.. the below error is shows as the status of nginx is not avail.

nginx: unrecognized service.

Running: CENTOS 6.8 / WHM 56.0 (build 24)

I had no other nginx plugins etc installed, just this and it was ok until the update was tried.

Tks.

**Comment by fevangelou** [comment]
Engintron is NOT compatible with EA4.

**Comment by virtuali1151** [comment]
I am not using EA4.. thats my point.. I am using 3 and I got that error.

**Comment by fevangelou** [comment]
Doesn't make sense. If you don't have EA4 then why did you kill the check?

Try re-installing via WHM and paste back the entire installation log as output there.

**Comment by virtuali1151** [comment]
I have used the plugin for a long time with this setup with no issues, I have EA3 and EA4 installed, but only 3 is active. I have installed the plugin many times like that with no problems.  When I went to update I got the error about EA4 being installed, so that is why I killed the check. Once I killed the check then it did install, but with the error nginx: unrecognized service.  

I am not using EA4 forsure, it is just installed but not activated.  Even if I use the recommended way from cpanel to remove it, my output is the following: 

root@svr [~]# /scripts/migrate_ea3_to_ea4 --revert --run
--revert only applies to systems running EasyApache4
root@svr [~]#

**Comment by fevangelou** [comment]
EA4 should not be installed at all. That's the problem. And that's why the check kicked in. If you didn't want to use EA4 (which is beta by the way), you shouldn't have installed it. This is like the core of cPanel. Of course it was bound to cause issues...

**Comment by virtuali1151** [comment]
This is the output from cpanel, I have installed the plugin many times like the below without any issue??

EasyApache 4 is not available when EasyApache 3 is active.

If you would like to use EasyApache 4, the following url contains instructions on how to convert to EasyApache 4.

**Comment by fevangelou** [comment]
I meant provide me with the installation output of Engintron.

But before you do that, enabled EA4 and then execute the revert function to completely remove it and switch back to EA3 as you previously mentioned and as stated here: https://documentation.cpanel.net/display/EA4/How+to+Install+or+Uninstall+EasyApache+4#HowtoInstallorUninstallEasyApache4-HowtouninstallEasyApache4

**Comment by virtuali1151** [comment]
k.. doing now.

**Comment by virtuali1151** [comment]
It looks like even with the check disabled it is still grabing the goods for the EA4... I will try to re-install it and remove it as suggested, but here is the output from just trying now.
-------------------

**************************************
*        Installing Engintron        *
**************************************
Archive:  engintron.zip
c727f75a9caa58a25e90ae41d03558e864850ce3
  inflating: engintron-master/LICENSE  
  inflating: engintron-master/README.md  
   creating: engintron-master/apache/
  inflating: engintron-master/apache/apxs.sh  
  inflating: engintron-master/apache/mod_rpaf-0.8.4.zip  
  inflating: engintron-master/apache/mod_rpaf-0.8.5-rc1.zip  
   creating: engintron-master/app/
  inflating: engintron-master/app/addon_engintron.cgi  
  inflating: engintron-master/app/engintron.php  
  inflating: engintron-master/engintron.sh  
   creating: engintron-master/nginx/
   creating: engintron-master/nginx/conf.d/
  inflating: engintron-master/nginx/conf.d/default.conf  
  inflating: engintron-master/nginx/custom_rules  
  inflating: engintron-master/nginx/mime.types  
  inflating: engintron-master/nginx/nginx.conf  
  inflating: engintron-master/nginx/proxy_params_common  
  inflating: engintron-master/nginx/proxy_params_dynamic  
  inflating: engintron-master/nginx/proxy_params_static  
removed `/usr/local/src/engintron/engintron-master/LICENSE'
removed `/usr/local/src/engintron/engintron-master/README.md'
removed `/usr/local/src/engintron/engintron-master/apache/mod_rpaf-0.8.4.zip'
removed `/usr/local/src/engintron/engintron-master/apache/mod_rpaf-0.8.5-rc1.zip'
removed `/usr/local/src/engintron/engintron-master/apache/apxs.sh'
removed directory: `/usr/local/src/engintron/engintron-master/apache'
removed `/usr/local/src/engintron/engintron-master/app/addon_engintron.cgi'
removed `/usr/local/src/engintron/engintron-master/app/engintron.php'
removed directory: `/usr/local/src/engintron/engintron-master/app'
removed `/usr/local/src/engintron/engintron-master/engintron.sh'
removed `/usr/local/src/engintron/engintron-master/nginx/nginx.conf'
removed `/usr/local/src/engintron/engintron-master/nginx/proxy_params_static'
removed `/usr/local/src/engintron/engintron-master/nginx/proxy_params_dynamic'
removed `/usr/local/src/engintron/engintron-master/nginx/custom_rules'
removed `/usr/local/src/engintron/engintron-master/nginx/conf.d/default.conf'
removed directory: `/usr/local/src/engintron/engintron-master/nginx/conf.d'
removed `/usr/local/src/engintron/engintron-master/nginx/proxy_params_common'
removed `/usr/local/src/engintron/engintron-master/nginx/mime.types'
removed directory: `/usr/local/src/engintron/engintron-master/nginx'


=== Let's upgrade our system first & install a few required packages ===
Loaded plugins: fastestmirror, tsflags, universal-hooks
Setting up Update Process
Loading mirror speeds from cached hostfile
 * EA4: 69.50.192.73
 * base: mirror.web-ster.com
 * extras: mirror.chpc.utah.edu
 * rpmforge: mirror.hmc.edu
 * updates: mirror.chpc.utah.edu
Loaded plugins: fastestmirror, tsflags, universal-hooks
Setting up Upgrade Process
Loading mirror speeds from cached hostfile
 * EA4: 69.50.192.73
 * base: mirror.web-ster.com
 * extras: mirror.chpc.utah.edu
 * rpmforge: mirror.hmc.edu
 * updates: mirror.chpc.utah.edu
Loaded plugins: fastestmirror, tsflags, universal-hooks
Setting up Install Process
Loading mirror speeds from cached hostfile
 * EA4: 69.50.192.73
 * base: mirror.web-ster.com
 * extras: mirror.chpc.utah.edu
 * rpmforge: mirror.hmc.edu
 * updates: mirror.chpc.utah.edu
Loaded plugins: fastestmirror, tsflags, universal-hooks
Cleaning repos: EA4 MariaDB101 base extras nginx rpmforge scl updates virtualmin
              : virtualmin-universal
Cleaning up Everything
Cleaning up list of fastest mirrors


=== Install Nginx (stable) from nginx.org ===
Loaded plugins: fastestmirror, tsflags, universal-hooks
Setting up Install Process
Determining fastest mirrors
 * EA4: 69.50.192.73
 * base: mirror.web-ster.com
 * extras: mirror.chpc.utah.edu
 * rpmforge: mirror.hmc.edu
 * updates: mirror.chpc.utah.edu


=== Installing mod_remoteip for Apache ===
/usr/local/apache/build/libtool --mode=install install mod_remoteip.la /usr/local/apache/modules/
libtool: install: install .libs/mod_remoteip.so /usr/local/apache/modules/mod_remoteip.so
libtool: install: install .libs/mod_remoteip.lai /usr/local/apache/modules/mod_remoteip.la
libtool: install: install .libs/mod_remoteip.a /usr/local/apache/modules/mod_remoteip.a
libtool: install: chmod 644 /usr/local/apache/modules/mod_remoteip.a
libtool: install: ranlib /usr/local/apache/modules/mod_remoteip.a
libtool: finish: PATH="/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/lib/courier-imap/sbin:/usr/lib/courier-imap/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin:/opt/bin:/sbin" ldconfig -n /usr/local/apache/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/apache/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------


=== Switch Apache to port 8080 ===


=== Distill changes in Apache's configuration and restart Apache ===
Distilled successfully
Built /usr/local/apache/conf/httpd.conf OK


=== Installing Engintron WHM plugin files... ===

=== Fix ACL requirements in newer cPanel releases ===
Invalid value for “autodiscover_mail_service”: ““0”” - Value must be either 0 or 1. This setting will not be updated.Your changes have been saved.

Restarting cPanel daemons...done.

Updating your system to reflect any changes...
Apache Jails cannot be enabled because mod_ruid2 must be at least version 0.9.4a. Please recompile Apache using Easy Apache w/mod_ruid2
While trying to rectify your configuration for “jailapache” an error was encountered: No such file or directory
Processing post action for Thunderbird and Outlook autodiscover and autoconfig support (enables proxy subdomain and SRV record creation):
The master proxysubdomains setting changed state so we do not need to update the autodiscover domains.
Processing post action for Conserve memory:
Processing post action for Standardized Hooks - Debug Mode:
Processing post action for Include mailman in disk usage calculations:
Processing post action for Include databases in disk usage calculations:
Processing post action for Mail authentication via domain owner password:
Processing post action for Number of failed or deferred messages a domain may send before protections can be triggered:
Processing post action for Enable Email Archiving support:
Processing post action for Email delivery retry time:
Processing post action for Allow cPanel & WHM to determine the best value for your MySQL innodb_buffer_pool_size configuration?:
Processing post action for Allow cPanel & WHM to determine the best value for your MySQL max_allowed_packet configuration?:
Processing post action for Allow cPanel & WHM to determine the best value for your MySQL open_files_limit configuration?:
Processing post action for cPanel PHP max execution time:
Processing post action for cPanel PHP max POST size:
Processing post action for cPanel PHP max upload size:
Processing post action for cPanel PHP loader:
Processing post action for Allow users to relay mail if they use an IP address through which someone has validated an IMAP or POP3 login within the last hour (Pop-before-SMTP):
Processing post action for Proxy subdomains:
Creating proxy domain DNS entries in background. This process can take several minutes to complete.
Processing post action for Require SSL:
Processing post action for Reset Password for cPanel accounts:
Processing post action for Reset Password for Subaccounts:
Processing post action for Enable Analog stats:
Processing post action for Enable Awstats stats:
Processing post action for Enable BoxTrapper spam trap:
Processing post action for Enable Horde Webmail:
Processing post action for Enable Mailman mailing lists:

whmappname='Restarting Service';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
if (window.update_ui_status) update_ui_status("mailman");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
mailman...[2016-06-09 20:40:49 -0600] info [restartsrv_base] The service 'mailman' is disabled and the system will not attempt to restart it.
(XID xwfner) The “mailman” service is disabled.
Waiting for “mailman” to stop ………finished.



...Done
if (window.clear_ui_status) clear_ui_status();
Restarting mailman
Configuration file passes test!  New configuration file was installed.


Skipping boxtrapper_autowhitelist entry in check_mail_permissions insert as it requires boxtrapper and it is disabled or unavailable.
Skipping virtual_boxtrapper_user entry in virtual_user insert as it requires boxtrapper and it is disabled or unavailable.
Skipping boxtrapper_localuser entry in localuser insert as it requires boxtrapper and it is disabled or unavailable.
Skipping boxtrapper_autowhitelist entry in virtual_userdelivery insert as it requires boxtrapper and it is disabled or unavailable.
Skipping local_boxtrapper_delivery entry in virtual_userdelivery insert as it requires boxtrapper and it is disabled or unavailable.
Skipping virtual_boxtrapper_userdelivery entry in virtual_userdelivery insert as it requires boxtrapper and it is disabled or unavailable.

/etc/exim.pl.local installed!
SPF is disabled in exim or unavailable, enabling SPF for SpamAssassin
Refreshing SMTP Mail protection.
SMTP Mail protection has been disabled.  All users may make outbound smtp connections.
Disabled scgi-bin since suexec is enabled or the webserver runs as the user
Distilled successfully
Processing post action for Enable Apache SpamAssassin™ spam filter:
Processing post action for Enable Apache SpamAssassin™ Spam Box delivery for messages marked as spam (user configurable):
Processing post action for Enable Webalizer stats:
Processing post action for Restrict outgoing SMTP to root, exim, and mailman (FKA SMTP Tweak):
Processing post action for Prefix “mail.” onto Mailman URLs:
Processing post action for Use pre-4.1-style MySQL® passwords:
Done.


Waiting for “cpsrvd” to restart gracefully ……waiting for “cpsrvd” to initialize ………finished.

Service Status
	cpanel (cpsrvd - dormant mode - accepting connec --llu=1465526197 --listen=10,3,4,5,6,7,8,9) is running as root with PID 11994 (pidfile check method).

Startup Log
	Starting PID 11994: /usr/local/cpanel/libexec/cpsrvd-dormant

cpsrvd restarted successfully.



=== Restarting Apache & Nginx... ===

**Comment by virtuali1151** [comment]
After I reinstalled it, and removed it again, then it worked.. looks like the CentOS-SCL repo was erroring out, I had to remove that.. then it worked.. tks..:)

**Comment by fevangelou** [comment]
All sorted. Cool :)
