### ISSUE TITLE
Cache Always Empty

### ISSUE THREAD

**Issue by tess0072** [engintron/engintron#163]
For some reason the nginx /tmp files are always empty for me... I can see that a directory structure exists but there are never any files present.

108K /tmp/engintron_dynamic
4.0K	/tmp/engintron_static
4.0K	/tmp/engintron_temp

Any idea what could be causing this?

**Comment by fevangelou** [comment]
You're probably on CentOS 7. This is just false reporting due to security changes in CentOS 7 compared to 6 and it's something to be fixed in v1.7.0.

**Comment by fevangelou** [comment]
See here for more info: https://github.com/engintron/engintron/issues/115
