### ISSUE TITLE
Configure nginx to load modsecurity

### ISSUE THREAD

**Issue by Akylenok** [engintron/engintron#164]
Hello. 

Tell me, at the moment nginx is not configured with modsecurity?

In this article (http://wiki.atomicorp.com/wiki/index.php/Atomic_ModSecurity_Rules#Step_1:_Download_ModSecurity) Step 6 - written that you want to add, but I don't know in what kind of place I need to add these settings.

location / {
           ModSecurityEnabled on;
           ModSecurityConfig modsecurity.conf;
           proxy_pass http://localhost:8080;
           proxy_read_timeout 180s;
}

And whether it's a code and all the file paths?

**Comment by fevangelou** [comment]
If you install it as mentioned in that article, then I don't see why it shouldn't work with Engintron's Nginx setup. You'll have to edit the "default.conf" file through Engintron's WHM app and simply add the 2 lines for ModSecurity right above the "try_files..." line in this code block:

	location / {
		try_files $uri $uri/ @backend;
	}

**Comment by whosjose** [comment]
@fevangelou Location would be `/usr/local/apache/conf/modsec2.user.conf` ?

**Comment by Akylenok** [comment]
I understand you correctly?:

	location / {
		ModSecurityEnabled on;
        ModSecurityConfig modsecurity.conf;
        proxy_pass @backend;
        proxy_read_timeout 180s;
		try_files $uri $uri/ @backend;
	}

and another question do I understand correctly that the variable @backend == http://localhost:8080 and can be written as I prescribed above (proxy_pass @backend; instead of proxy_pass http://localhost:8080;)?

**Comment by fevangelou** [comment]
@Akylenok Do exactly as I mention. Engintron's Nginx proxy setup is more complex than the examples provided over the web.

**Comment by Akylenok** [comment]
:(
nginx: [emerg] unknown directive "ModSecurityEnabled" in /etc/nginx/conf.d/default.conf:23

**Comment by fevangelou** [comment]
...that's because ModSecurity (as it seems) must be compiled as an Nginx module. So I'd recommend you forget about this solution and simply use ModSecurity as provided by cPanel for Apache. Should any requests that should be filtered by ModSecurity pass from Nginx to Apache, they will be caught by ModSecurity.
