### ISSUE TITLE
Will it play nice with Apache 2.2?

### ISSUE THREAD

**Issue by cre8gr** [engintron/engintron#166]
Hey guys! I'm thinking of installing Engintron in my cPanel server which right now has Apache 2.2.31 installed.

Also many of the sites hosted are using Cloudflare as well. I'm stating this to be sure that if Engintron works with Apache 2.2 do we have to do the changes documented at the Wiki for sites hosted on Cloudflare?

So bottom line will it work, or do I have to upgrade Apache to 2.4?

**Comment by fevangelou** [comment]
Yes, it will work. You could be running IIS on cPanel for all I know and Nginx would not care less :) Things would just work. For CloudFlare you have to define the sites in "if" blocks as explained in the Engintron Wiki.
