### ISSUE TITLE
Does modsecurity show the real ip of the visitor when triggering a rule?

### ISSUE THREAD

**Issue by azirer** [engintron/engintron#168]
This is a question rather an issue. Does modsecurity inside WHM show the real ip of the visitor in the hitlist when a modsecurity rule is triggered?

**Comment by fevangelou** [comment]
Nginx passes the real visitor's IP back to Apache so there should be no
issue with ModSecurity rules.

**Comment by azirer** [comment]
I have tried nginxcp and one custom installation of nginx and in both cases modsecurity doesn't show the real ip of the user. All other apps on the server show the correct one though that's why I asked. 

I think that modsecurity uses the `_SERVER["REMOTE_ADDR"]` and without compiling nginx `--with-http_realip_module` modsec and other apps that rely one `REMOTE_ADDR` won't function correctly.

**Comment by timeassistant** [comment]
I would like to report that this is an issue. Our server hosts also said this is an issue from engintron

when engintron is installed on our VPS modsecurity reports all source IP's as the VPS IP. 

Could this please be looked at as this is stopping modsec from banning IPs that trigger the rules

**Comment by fevangelou** [comment]
@timeassistant If the issue is fixed with a re-installation, this means that mod_remoteip installed by Engintron was not originally installed properly - for some reason only the cPanel gods know as I've seen this before.

@azirer Nginx reports the correct $_SERVER["REMOTE_ADDR"] - make sure mod_remoteip is installed for you as well. If not, simply re-run the Engintron installer.

**Comment by timeassistant** [comment]
@fevangelou Thanks for the reply, yeah I had read the problem could be that the remoteip mod was not installed so I checked the loaded mods and it was at which point I also read another person reinstalled and that fixed it.

It might be  a good idea to add some documentation regarding this for other users who have this issue as that was a relatively simple fix just not an obvious one :)

**Comment by fevangelou** [comment]
Will do. Closing for now.

**Comment by Mecanik** [comment]
How exactly did you enable mod_remoteip if you don`t mind ? I can`t seem to get around it...

**Comment by fevangelou** [comment]
@Mecanik Did you try re-installing? My only guess is that because the module is directly fetched from the Apache Foundation website, there may have been downtime issues. I'll make sure to pack the module with Engintron to avoid such possible issues in the future.

**Comment by timeassistant** [comment]
@fevangelou 

I just noticed the issue again, as you will note in a previous comment I had to reinstall to get the IP's working in ModSecurity, I just had to do this again, so it seems like after a while there is an issue with this. 

I have the IP's reporting correctly again but for how long?

**Comment by Mecanik** [comment]
Yes indeed, same issue here!

**Comment by fevangelou** [comment]
Just upgrade to v1.6.2 released yesterday :)

I'm now packing the source code into the GitHub repo, because the only issue I can think of that mod_remoteip was not installed in the first place, is that the Apache repo site did not respond during your initial installation.

**Comment by timeassistant** [comment]
upgraded, and seems to be reporting correct IP's at the moment, 

although I do have to say that mod_remoteip was definitely still installed when the IP's were not showing correctly. 

anyway lets hope this version will fix the issue :)

**Comment by arabgenius** [comment]
I did every thing
installin/reinstalling/updating so ever
still shows server ip in mod_sec

**Comment by arabgenius** [comment]
and Iam sure mod_remoteip is installed and working will
yet .. it shows server ip in mod_sec

**Comment by KristijanL** [comment]
Same here on 1.8.0, i try:
Fresh install 1.7.3,
Upgrade to 1.8.0,
Uninstall, new install 1.8.0

It shows server ip in logs.
EA4, Cloudlinux 7.3, fresh install.
Didn't have the time to start fixing it manualy, just want to notify that clean install does not work for me.
