### ISSUE TITLE
Using Loggly 

### ISSUE THREAD

**Issue by whosjose** [engintron/engintron#171]
I'm trying to use Loggly to monitor my system logs. I'm having a problem using it for Apache and/or Nginx. 

I set it up for nginx and followed instructions, from what I thought it went smooth. No errors. When I tried to visit a site, it doesn't connect. I was still able to access cPanel but not the site itself.

When I tried to install it for Apache I get

`ERROR: Apache is not configured as a service
Manual instructions to configure Apache2 is available at https://www.loggly.com/docs/sending-apache-logs/. Rsyslog troubleshooting instructions are available at https://www.loggly.com/docs/troubleshooting-rsyslog/
`

I figured that would happen for Apache.

Does anyone have a clue on how to set it Engintron with Loggly?

**Comment by fevangelou** [comment]
You should ask at Loggly's website. The example you provided seems to be
for Ubuntu Server by the way (cPanel works on CentOS only)...

**Comment by whosjose** [comment]
@fevangelou 
The script will auto-detect what linux version you are using.

**Comment by fevangelou** [comment]
"Apache2" is referenced only in Ubuntu. So something's wrong with the installation. You should contact Loggly first as their installer may not recognize cPanel's Apache installation (which uses totally different folder structure from the installation of Apache via CentOS' yum repos).
