### ISSUE TITLE
502 error as nginx is trying to connect wrong IP

### ISSUE THREAD

**Issue by iRickyJ** [engintron/engintron#176]
This may not be an issue or could be. I have gone through lots of nginx docs and 502 related discussion on internet. However, still not able to resolve. I will try to be descriptive as much as I can. 

Here is my setup: 

I have a domain points to IP x.x.x.x , however I have mirror at IP y.y.y.y , I have monitoring system which checks if x.x.x.x is not available, all traffic is then served from IP y.y.y.y 

We use command like :` curl -vk --header 'host:domain.com'' http://x.x.x.x` for testing

But problem comes when IP x.x.x.x is down, then domain resolves to IP y.y.y.y  , and then if we run following command then issue comes : 
 curl -vk --header 'host:domain.com'' http://x.x.x.x  ,  menace comes.

The menace is that internally nginx  is trying to route request  to y.y.y.y:8080  but it should be x.x.x.x:8080 

My best guess is that its because nginx is resolving hostname we gave in curl command through --header to "y.y.y.y" (since x.x.x.x was down)  . May be it is the desired behaviour as nginx is trying to 
	set $PROXY_DOMAIN_OR_IP $host 

I went through your tutorial 
https://github.com/engintron/engintron/wiki/Engintron-%26-the-%22Custom-Rules%22-file-(for-Nginx) 

I modified custom rules as per instruction and added : 

```
if ($host ~ "domain.com") {
	set $PROXY_DOMAIN_OR_IP "x.x.x.x";
```

However, still same issue is happening where request made via curl with "host" specified is causing it resolve to wrong IP which is not even there on this server.  Also we can't remove --header 'host:abc" directive from curl as we use to check same system for domain hosted on shared IPs also.

Any advice ?

**Comment by fevangelou** [comment]
DNS resolving by Nginx is cached for some time so if IP x.x.x.x is not "healthy", it will take some time for Nginx to pick up the change to y.y.y.y. The solution is simple. Just change the DNS servers in nginx.conf to point to your main server doing all the DNS work.

I think though that you should handle this issue differently. If you currently have 3 cPanel servers (or just one cPanel server with Engintron plus any 2 others) to achieve what you describe above, there's a more efficient way to do what you're trying to do now. I would recommend using Engintron directly on the servers with IPs x.x.x.x and y.y.y.y if they are cPanel based and then using some sort of load balancing (Nginx is great for that - but use only that, you don't need cPanel) on the server where you currently have Engintron installed. And you won't even have to run any curl commands for load balancing. If you're interested in such a an efficient load balancing setup, you can always hire me to do it for you :)

**Comment by iRickyJ** [comment]
This make sense because later on things were working as they should when I reinstalled it, but clearly there was no need for it.

For my setup, there is not much traffic so its more about failover than load-balancing. However, if I ever need something more complicated , I will definitely ask you for advice and possibly your services :)

**Comment by fevangelou** [comment]
Great :)
