### ISSUE TITLE
502 bad gateway error

### ISSUE THREAD

**Issue by rafaelppaulucci** [engintron/engintron#177]
Hi guys,

i have one issue here. 
Maybe could be my amateurism with Nginx.

After installed Engintron to my servers and created an account with real domain (example.com), this domain dns doenst appointed to my servers yet.

So, what i do? I modify my hosts machine file to appoints the dns to my server (to work on site) and other stuffs.

When i try to access this message is displayed:

2016/06/24 08:05:34 [error] 24837#24837: *1138285 connect() failed (110: Connection timed out) while connecting to upstream, client: 152.xxx.xxx.xxx (my browser ip), server: localhost, request: "GET / HTTP/1.1", upstream: "http://187.xxx.xxx.xxx:8080/" (current server ip where's dns appoints), host: "www.example.com"

Its there any way to fix that?
Thanks!

**Comment by rafaelppaulucci** [comment]
Solved changing DNS's of NGINX.

Thanks Guys!

**Comment by fevangelou** [comment]
There's another solution in the Engintron Wiki you might wanna check out :)

**Comment by melihornek** [comment]
same the problem
