### ISSUE TITLE
Default Web Site Page New Account/Addon Domain Created

### ISSUE THREAD

**Issue by MarcusChiang** [engintron/engintron#179]
When a New Account/Addon Domain is Created.

Usually you'll be able to access the Website immediately.

But it's showing Default Web Site Page and Browser Cache needs to be cleared on in order to work. Is this normal?

**Comment by fevangelou** [comment]
Were you using some other plugin for Nginx on cPanel previously?

Are you using any other type of caching?

The default cPanel page has a .cgi extension so it's only cached by Nginx for 1 sec.

**Comment by MarcusChiang** [comment]
No plugin for NGINX, yours is the first plugin :)

No caching, I followed all optimization on your wiki.

**Comment by fevangelou** [comment]
Did you by any chance call that domain on your browser without having it first setup in cPanel and perhaps DNS which was already pointing in your server produced this whole issue?

Have you tried adding another domain and re-checking?

**Comment by MarcusChiang** [comment]
No, I get about 10 new accounts daily and all of them are like that.

**Comment by fevangelou** [comment]
Are you located in China by any chance? DNS may not resolve properly as used in Nginx by default...

**Comment by MarcusChiang** [comment]
No, I'm located in Singapore.

**Comment by fevangelou** [comment]
OK, this is a first.

For starters just do a one time restart for Apache and Nginx via Engintron's WHM app. If that doesn't solve your issue, try re-installing Engintron either via terminal or via Engintron's WHM app. See if this fixes the issue.

If both fail, something else is wrong here and I'll need to see some log file...

**Comment by MarcusChiang** [comment]
Restarted before.

Does the NGINX, PHP, MySQL, Apache settings saved when Engintron is uninstalled?

**Comment by fevangelou** [comment]
If you uninstall it, anything related to Nginx ONLY is wiped off. 
Re-installing is better.

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by MarcusChiang** [comment]
I'll update you if the issue persist. Thanks.

**Comment by MarcusChiang** [comment]
Seems to be fine after reinstall.

**Comment by masteranalyze** [comment]
glad you solved your problem @MarcusChiang .

if you like it and works good,donate to @fevangelou for the project,in order things to be better and to make things go on more faster!

**Comment by wislem** [comment]
I am creating m.example.com subdomains (DNS only) through Cloudflare, so I can get
away with the theme messing up due to micro-caching. I am not doing anything for that subdomain
in cPanel, I just create a CNAME in Cloudflare.

On some domains, it worked flawlessly after DNS propagation.

On others, it shows the /cgi-sys/defaultwebpage.cgi page from cPanel.

Could this be the same with the above and reinstalling engintron will solve the issue?

**Comment by masteranalyze** [comment]
The default cPanel page has a .cgi extension so it's only cached by Nginx for 1 sec.

Did you delete all browser cache or use private sesion and re-check?Have you tried adding another domain and re-checking?

you can try re-install and after let us now if it did solved the problem.

**Comment by wislem** [comment]
Did all you proposed, except reinstalling of course :)

It is a production server, so I'll have to do it some time later.

I will report with the results.

**Comment by masteranalyze** [comment]
okay,let us now if it did solved the problem after.

**Comment by fevangelou** [comment]
@wislem the subdomain has to be setup in cPanel as well, otherwise although Nginx will know were to forward the subdomain, Apache won't. In other words, Apache has to know that m.something.tld points to this system folder.
