### ISSUE TITLE
Server Down After Every Few Hours

### ISSUE THREAD

**Issue by MarcusChiang** [engintron/engintron#180]
Hello, after every few hours. My Hosting Account Domain, http, https are unreachable and I have to killall -KILL mysql mysqld_safe mysqld (unreachable), service start mysql (error establishing database connection) and restart mysql server via whm (back to normal).

May I know what's causing the issue? I have 2 servers.
1 of them has more Hosting Account than the other one.

The one that has the most Hosting Account has the issue while the other one doesn't seems to have issue until now.

tuning-primer is used and both servers has the same configuration.

**Comment by masteranalyze** [comment]
Maybe you can replicate the steps 1 by 1 what did you done until the killall ?!

Provide more details,and if you have 2 servers,you installed on both Engintron or?!

**Comment by MarcusChiang** [comment]
I didn't do anything except configuring engintron.

**Comment by MarcusChiang** [comment]
And yes, both server had engintron.

**Comment by masteranalyze** [comment]
so you have 2 servers,in both you installed engintron is that corectly?

in 1 server how many accounts are and in the 2nd how many they are?

Those 2 servers are the same?same config?from same provider?

On the one with the problem,did you tryed removed Engintron and the problem it`s still there or not?

**Comment by MarcusChiang** [comment]
Yes.

First server 1000 account second server 400 account

Same config, same specs.

No issues before installing engintron.

**Comment by masteranalyze** [comment]
okay,witch server haves problem the one with 1000 or 400 account,after installing engintron?

**Comment by MarcusChiang** [comment]
1000

**Comment by MarcusChiang** [comment]
SqL sever always go offline after few hours and I had to kill in order to restart the service.

**Comment by masteranalyze** [comment]
in the one with 400 there is no such problem?

In the one with 1000,remove it,and tell us if problems persist.

**Comment by MarcusChiang** [comment]
The problem is with the sql and when the default my.cnf is used doesn't seems to have an issue.

**Comment by masteranalyze** [comment]
i understood,but can you remove engintron for 5 minutes from there,and check back if this is still happening or not?

As if in the one with 400 accounts is working,maybe the problem you have is not from it,and we need to identify the cause of this crashing.

Do an test remove it from there,check back in an few hours,and tell us if you still have to kill all.

Did you looked into resource manager what is using or wasting so much?!

I think you have something in there,that gets into conflict....

**Comment by fevangelou** [comment]
It would also greatly help if you actually provided some meaningful information like what's the content of your my.cnf files (if you have modified them) as this is something entirely separate to Engintron's installation. If you have modified the my.cnf files in both servers according to the suggestions I'm making in the Engintron Wiki, you also have to modify some values based on server specs, number of sites served and actual mysql resource usage.

**Comment by MarcusChiang** [comment]
Yes, I have modified based on your suggestions and used tuning-primer.

[client]
port                            = 3306
socket                          = /var/lib/mysql/mysql.sock

[mysqld-safe]
socket                          = /var/lib/mysql/mysql.sock
nice                            = 0

[mysqld]
#basedir                         = /usr
#bind-address                    = 127.0.0.1 # Comment out if you want remote servers to connect to this server's MySQL instance
datadir                         = /var/lib/mysql
lc-messages-dir                 = /usr/share/mysql
max-allowed-packet              = 16M
myisam-recover                  = BACKUP
#pid-file                        = /var/run/mysqld/mysqld.pid
port                            = 3306
skip-external-locking
socket                          = /var/lib/mysql/mysql.sock
thread-stack                    = 192K
tmpdir                          = /tmp
user                            = mysql
sql_mode                        = NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

# InnoDB Settings
default-storage-engine          = InnoDB
innodb-buffer-pool-size         = 2G    # Use up to 70-80% of RAM & optionally check if /proc/sys/vm/swappiness is set to 0
innodb-buffer-pool-instances    = 2     # Use 1 instance per 1GB of InnoDB pool size
innodb-file-per-table           = 1
innodb-flush-log-at-trx-commit  = 0
innodb-flush-method             = O_DIRECT
innodb-log-buffer-size          = 8M
innodb-log-file-size            = 128M

# MyISAM Query Cache Settings
query-cache-limit               = 3M    # UPD
query-cache-size                = 8M   # UPD
query-cache-type                = 1

key-buffer-size                 = 48M   # UPD

join-buffer-size                = 3M    # UPD
sort-buffer-size                = 2M    # UPD
read-buffer-size                = 2M    # UPD
read-rnd-buffer-size            = 2M    # UPD

max-heap-table-size             = 128M
tmp-table-size                  = 128M

table-definition-cache          = 75000  # UPD
table-open-cache                = 25000  # UPD
open-files-limit                = 15000 # UPD

max-connections                 = 80    # UPD
max-user-connections            = 60    # UPD

wait-timeout                    = 300
low-priority-updates            = 1
concurrent-insert               = 2
thread-cache-size               = 40    # UPD

ft-min-word-len                 = 3     # Minimum length of words to be indexed for search results

log-queries-not-using-indexes   = 1
slow-query-log                  = 1
long-query-time                 = 5
expire-logs-days                = 7
max-binlog-size                 = 100M

max_allowed_packet=268435456
open_files_limit=50000
[mysqldump]
quick
quote-names
max-allowed-packet              = 16M

[mysql]

[isamchk]
key-buffer                      = 16M

**Comment by fevangelou** [comment]
This is very old. Refer to the revised my.cnf with troubleshooting info. Read this section very carefully and get back to me.

https://gist.github.com/fevangelou/0da9941e67a9c9bb2596

**Comment by MarcusChiang** [comment]
I'll get back to you if issue persist.

[client]
port                            = 3306
socket                          = /var/lib/mysql/mysql.sock

[mysqld-safe]
socket                          = /var/lib/mysql/mysql.sock
nice                            = 0

[mysqld]
#basedir                         = /usr
bind-address                    = 127.0.0.1 # Comment out if you want remote servers to connect to this server's MySQL instance
datadir                         = /var/lib/mysql
lc-messages-dir                 = /usr/share/mysql
max-allowed-packet              = 16M
myisam-recover                  = BACKUP
#pid-file                        = /var/run/mysqld/mysqld.pid
port                            = 3306
skip-external-locking
socket                          = /var/lib/mysql/mysql.sock
thread-stack                    = 192K
tmpdir                          = /tmp
user                            = mysql
sql_mode                        = NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

# InnoDB Settings
default-storage-engine          = InnoDB
innodb-buffer-pool-size         = 2G    # Use up to 70-80% of RAM & optionally check if /proc/sys/vm/swappiness is set to 0
innodb-buffer-pool-instances    = 2     # Use 1 instance per 1GB of InnoDB pool size
innodb-file-per-table           = 1
innodb-flush-log-at-trx-commit  = 0
innodb-flush-method             = O_DIRECT
innodb-log-buffer-size          = 8M
innodb-log-file-size            = 128M

# MyISAM Query Cache Settings
query-cache-limit               = 3M    # UPD
query-cache-size                = 8M   # UPD
query-cache-type                = 1

key-buffer-size                 = 48M   # UPD

join-buffer-size                = 3M    # UPD
sort-buffer-size                = 2M    # UPD
read-buffer-size                = 2M    # UPD
read-rnd-buffer-size            = 2M    # UPD

max-heap-table-size             = 128M
tmp-table-size                  = 128M

table-definition-cache          = 75000  # UPD
table-open-cache                = 25000  # UPD
open-files-limit                = 15000 # UPD

max-connections                 = 80    # UPD
max-user-connections            = 60    # UPD

wait-timeout                    = 300
low-priority-updates            = 1
concurrent-insert               = 2
thread-cache-size               = 40    # UPD

ft-min-word-len                 = 3     # Minimum length of words to be indexed for search results

log-error                       = /var/lib/mysql/mysql_error.log
log-queries-not-using-indexes   = 1
slow-query-log                  = 1
slow-query-log-file             = /var/lib/mysql/mysql_slow.log
long-query-time                 = 5
expire-logs-days                = 7
max-binlog-size                 = 100M

[mysqldump]
quick
quote-names
max-allowed-packet              = 16M

[mysql]

[isamchk]
key-buffer                      = 16M

**Comment by MarcusChiang** [comment]
Still happening. Any ideas what's the cause?

**Comment by MarcusChiang** [comment]
I have contacted cPanel and the issue might be solved.

I'll update again if everything goes well.

**Comment by masteranalyze** [comment]
If you solve your issue,update here with what was the cause and the solution,in case other haves the same problem.

Practically there is no reason in 1 server as they are the same to work,and in 1 to not work,even if they are more account on the second one.

**Comment by MarcusChiang** [comment]
On my first server, the server that has issue.
I see bind-address

On second server, no issues and I see
#bind-address

My server status for mysql is marked as offline on first server while marked as online for second server and upon adding a comment on first server, it became online.

I have increased the soft and hard limits on first server, not sure if it affects.

Will update in 24 hours and see if server is down.

**Comment by masteranalyze** [comment]
you use cloud linux on it?with lve ?or what do you mean by you incresed the soft and hard limits?

on the server with 1000 and problems,the customers what are they using?wp,joomla?magento?open cart?or?

It might be getting into conflict with all kinds of plugins that is used on all those websites...

If the servers are exactly the same configuration as you said,and no difference,practically it should work on both without no server crash.

If one crashes as your saying,something is differently setup in 1 of them and you must see exactly what,as we don t have access on it,is hard to tell,it can be alot of stuff.

good waiting your update on the cause.

**Comment by MarcusChiang** [comment]
@masteranalyze The thing that is on /etc/sysctl.conf and /etc/security/limits.conf.

**Comment by masteranalyze** [comment]
So you manage in that server 1000 account without cloud linux ?and without an LVE manager?!

**Comment by MarcusChiang** [comment]
Both of my server has CloudLinux and LVE Manager.

I only have default software, don't have MySQL Governor.

**Comment by masteranalyze** [comment]
If you have cloud linux,you should have also the mysql governor,managing so many accounts in 1 server is not an easy task if you don`t have the right tools on it.

MySQL governor is software to monitor and restrict MySQL usage in shared hosting environment. The monitoring is done via resource usage statistics per each MySQL thread.

MySQL governor can also kill off slow SELECT queries.
 
MySQL Governor has multiple modes of operations, depending on the configuration. It can work in monitor only mode, or it can use different throttling scenarious.

MySQL Governor allows to restrict customers who use too much resources. It supports following limits:

CPU

%
	

CPU speed relative to one core. 150% would mean one and a half cores

READ
	

bytes
	

bytes read. Cached reads are not counted, only those that were actually read from disk will be counted

WRITE
	

bytes
	

bytes written. Cached writes are not counted, only once data is written to disk, it is counted

You can set different limits for different periods: current, short, med, long. By default those periods are defined as 1 second, 5 seconds, 1 minute and 5 minutes. They can be re-defined using configuration file. The idea is to use larger acceptable values for shorter periods. Like you could allow a customer to use two cores (200%) for one second, but only 1 core (on average) for 1 minute, and only 70% within 5 minutes. That would make sure that customer can burst for short periods of time.

When customer is restricted, the customer will be placed into special LVE with ID 3. All restricted customers will be placed into that LVE, and you can control amount of resources available to restricted customers. Restricted customers will also be limited to only 30 concurrent connections. This is done so they wouldn't use up all the MySQL connections to the server.

MySQL Governor configuration is located in /etc/container/mysql-governor.xml

It is best to modify it using dbctl tool.

**Comment by masteranalyze** [comment]
Once configuration file is updated, please, restart the governor using:

$ service db_governor restart

Example configuration:

<governor>
 






<lve use="on|single|off|abusers|all"/>
 



 

<connector host="..." login="..." password=".." prefix_separator="_"/>
 

<intervals short="5" mid="60" long="300"/>
 

<log file=”/var/log/dbgovernor-error.log” mode=”DEBUG|ERROR”/>
 




<!- level1, level2, level3, level4 - period of restriction user for different level of restriction. During this period all user's requests will be placed into LVE container -->




 

<restrict level1="60s" level2="15m" level3="1h" level4="1d" timeout="1h"
log="/var/log/dbgovernor-restrict.log" format="SHORT|MEDIUM|LONG|VERYLONG"
     script="/path/to/script"
     user_max_connectins="30"/>
 


<restrict_mode use="period|limit" unlimit="1m"/>
 


<slow_queries run="on|off" log="/var/log/dbgovernor-kill.log"/>
 
 

<statistic mode="on|off"></statistic>


<logqueries use="on|off"></logqueries>
<default>

<limit name="cpu" current="150" short="100" mid="90" long="65"/>
<limit name="read" current="100000000" short="90000000" mid="80000000" long="70000000"/>
<limit name="write" current="100000000" short="90000000" mid="80000000" long="70000000"/>


<limit name="slow" current="30"/>
</default>

 




<user name=”xxx” mysql_name=”xxx” mode=”restrict|norestrict|ignore”>
<limit...>
</user>
 

<debug_user name="xxx"/>
 
</governor>

**Comment by MarcusChiang** [comment]
So far seems to have no issues. Will close.

**Comment by masteranalyze** [comment]
@MarcusChiang if you solved your problem,don`t forget to mention here ,on how did you solved and what was the cause and how you fixed,is important for others,as this is an open source project,and the products needs to be better with the help of the community.

From what you did writed anyhow,this problem was more MYSQL related more then Engintron.

But it`s important for others to know how you solved in case others might have the same problem,we can direct them here to read what needs to be done,else everytime same problem occurs we have to reload it again and start again,witch is kind like INSANITY,doing the same thing again and again and expecting differently results,when you just can provide directly the solution.

What`s your skype?

**Comment by MarcusChiang** [comment]
I cannot confirm but I think is the sysctl.conf and /etc/security/limits.conf needs to be increased.

**Comment by masteranalyze** [comment]
you solved your problem or is still crashing the server?

post here,the config on them,if this solved the problem.

**Comment by MarcusChiang** [comment]
/etc/sysctl.conf
# Performance Tuning
net.core.netdev_max_backlog = 65535
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 65535
fs.file-max = 512000

/etc/security/limits.conf
# Performance Tuning    
*       soft    nofile  512000
*       hard    nofile  512000

**Comment by fevangelou** [comment]
If this server had 4000 domains as you said (honestly I've never seen so many in a cPanel server before - or any server frankly) the increasing fs.file-max in sysctl.conf as well as the corresponding values in limits.conf does make sense. Adjusting these files is mentioned in the Engintron wiki as well: https://github.com/engintron/engintron/wiki/11.-Beyond-Engintron:-optimizing-CentOS

Additionally, lots of websites (thousands in your case) means you have to adapt the my.cnf I provide. Most probably increase values that are by design related to usage like the query cache and key buffer values, the InnoDB pool size, the thread cache size and of course the number of max user connections. It's a process that requires testing, that's why it's best to use a tool like Tuning Primer or MySQLTuner to be able to to fine-tune MySQL's configuration to your needs. I do see some errors still (if you haven't updated it), e.g.:

table-definition-cache = 75000 # UPD
table-open-cache = 25000 # UPD
open-files-limit = 15000 # UPD

Should be...

table-definition-cache = 25000 # UPD
table-open-cache = 25000 # UPD
open-files-limit = 50000 # UPD

But you should test with some MySQL tuning tool to be sure. And of course, you need to allow MySQL to run for a few days so it can gather usage statistics to properly use a tuning tool to improve your configuration.

Upcoming Engintron releases, possibly in v1.7.0 or v1.8.0, will include these tools so everything can be performed within the Engintron WHM app.
