### ISSUE TITLE
limit_req per domain

### ISSUE THREAD

**Issue by expssh** [engintron/engintron#181]
Hello. It's possible to limit request for each domain by limit_req? If yes, please show some example.

**Comment by fevangelou** [comment]
I guess you know what you want it for. In that case, since you can use these directives in every context, try adding this in the "custom rules" file via Engintron's WHM app:

`
limit_req_zone $binary_remote_addr zone=exampledotcom:10m rate=1r/s;
if ($host ~ "example.com") {
    limit_req zone=exampledotcom burst=5;
}
`

This example is for a specific domain. For all domains just use:

`
limit_req_zone $binary_remote_addr zone=global:10m rate=1r/s;
limit_req zone=global burst=5;
`

**Comment by fevangelou** [comment]
Updated the examples...

**Comment by expssh** [comment]
Hi, Fotis. Thank you for reply. How about GeoIP usage, let me show you some example:
1) http context:
========================
geo $country {
    default no;
    include nginxGeoIP.txt;
}
    geoip_country /usr/share/GeoIP/GeoIP.dat;
    map $geoip_country_code $allowed_country {
        default yes;
        BR no;
        IN no;
        CN no;
}
===========================
2) server context:
===========================
    if ($allowed_country = no) {
        return 444;
    }
===========================
should I add "1)" to the nginx.conf and "2)" to the customs rules?

**Comment by fevangelou** [comment]
According to this http://nginx.org/en/docs/http/ngx_http_geoip_module.html you would have to split configuration as you suggested. However, the geoip module is not bundled with the Nginx setup that Engintron downloads from Nginx's CentOS/RedHat repos...

**Comment by fevangelou** [comment]
An alternative is by using CloudFlare and this: http://nginxlibrary.com/using-cloudflare-for-country-blocking/

You'll get the country as part of the headers sent from CloudFlare to your server.

**Comment by fevangelou** [comment]
...And this is probably the easiest, without using the GeoIP module at all: https://www.scalescale.com/tips/nginx/block-country-nginx/

**Comment by expssh** [comment]
/var/log/nginx/error.log 
"limit_req_zone" directive is not allowed here in /etc/nginx/custom_rules:66

**Comment by fevangelou** [comment]
http://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_zone

Move it at the end of the nginx.conf file as this directive works only inside http {...} blocks (missed that previously).

**Comment by expssh** [comment]
nginx.conf
===============
	## Virtual Host Configs ##
	include /etc/nginx/conf.d/*.conf;
	limit_req_zone $binary_remote_addr zone=firewall:20m rate=10r/s;
===============
"custom rules" at the end

if ($host ~ "example.com") {
	limit_req zone=firewall burst=11;
}
===============
/var/log/nginx/error.log
"limit_req" directive is not allowed here in /etc/nginx/custom_rules:71

**Comment by fevangelou** [comment]
"limit_req" is not allowed in "if" blocks. So it's best to do this (as a recap):

First:
```
http {

	...

	# Rate limiting
	limit_req_zone $binary_remote_addr zone=firewall:20m rate=10r/s;
}
```

And then inside the custom rules file:

```
error_page 410 = @slowdown;
location @slowdown {
	limit_req zone=firewall burst=11;
}

# Repeat the following block for additional domains
if ($host ~ "example.com") {
	return 410;
}
```

**Comment by expssh** [comment]
Hi, Fotis. The rules works fine and limits the requests. But the domain it self not work when I open in the browser http;//example.com -> (nginx 404 not found)

**Comment by fevangelou** [comment]
Did it show up just fine before the changes?

**Comment by expssh** [comment]
Sure, when remove 

> if ($host ~ "example.com") {
>     return 410;
> }
domain works fine

**Comment by fevangelou** [comment]
I hope you're substituting "example.com" with an actual domain, right?

Also notice the syntax. If you have "if(" and not "if (" this will fail.

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by expssh** [comment]
Absolutely.

custom rules (at the end of file)
> error_page 410 = @slowdown;
> location @slowdown {
>     limit_req zone=firewall burst=10;
> }

> if ($host ~ "mydomain.com") {
> 	return 410;
> }

**Comment by fevangelou** [comment]
Move the location block below the if block and restart Nginx.

**Comment by expssh** [comment]
> error_page 410 = @slowdown;
> if ($host ~ "mydomain") {
> 	return 410;
> }
> location @slowdown {
>     limit_req zone=firewall burst=10;
> }
like this?

**Comment by fevangelou** [comment]
Yes.

**Comment by expssh** [comment]
nginx 404 not found

**Comment by expssh** [comment]
Hi, Fotis. Any news how to make this work?

**Comment by fevangelou** [comment]
The 404 error is obviously not triggered by the rules above. You'll have to paste the contents of all the files in Nginx you modified. Also make sure port 8080 is open in your firewall (if you have any).

**Comment by expssh** [comment]
custom rules

`set $PROXY_DOMAIN_OR_IP "shared IP";`
```
if ($host ~ "dedicated-domain.com") {
	set $PROXY_DOMAIN_OR_IP "dedicated-IP";
}
```
```
error_page 410 = @slowdown;
if ($host ~ "example.com") {
return 410;
}
location @slowdown {
limit_req zone=firewall burst=10;
}
```
nginx.conf

`limit_req_zone $binary_remote_addr zone=firewall:20m rate=5r/s; #at the end of file`
there is no additional modified files or configs

**Comment by fevangelou** [comment]
I'm assuming you have "limit_req_zone..." within the http {...} block, right?

**Comment by expssh** [comment]
Yes, as i wrote in the last comment.

**Comment by fevangelou** [comment]
I'm really out of ideas. As this is not part of Engintron but it's more a generic Nginx issue, why not post about it in their friendly forum? https://forum.nginx.org/

**Comment by supersophie** [comment]
This did not work in the nginx.conf

limit_req_zone $binary_remote_addr zone=exampledotcom:10m rate=1r/s; 
if ($host ~ "my.domain.com") { 
    limit_req zone=exampledotcom burst=5; 
}

Does the exampledotcom reference a counter with the number of connections incremented or decremented?  It's unclear.

What is my.domain.com ?  The incoming IP address reverse looked up ( that will slow the server down) or is this the server name used in the vhost?  It's unclear.

if directive. Obviously not in the nginx.conf:
# nginx -t
nginx: [emerg] "if" directive is not allowed here in /etc/nginx/nginx.conf:43

Kind regards.
