### ISSUE TITLE
Multiple Proxy IP's

### ISSUE THREAD

**Issue by Leykis** [engintron/engintron#182]
Is it possible to set multiple shared IPs in the NGINX custom rules for CloudFlare?

`set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX"; # Use your cPanel's share IP address here`

We use a couple shared IPs and currently the only way around this is to add an an exclusion for every domain not on the main shared IP that is using CloudFlare.

Thank you.

**Comment by fevangelou** [comment]
I'm afraid that's not possible. Of course you can use regular expressions for the domains to have just 2 "if" blocks, but I think the best option would be to just move all domains to the same shared IP address.

**Comment by Leykis** [comment]
Okay, thank you.
