### ISSUE TITLE
PLEASE REGISTER THE APP in CPANEL/WHM

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#183]
If the tweak to allow only registered apps to be installed is on, engintron WHM interface is not working anymore. Add this in the next version.

**Comment by fevangelou** [comment]
Engintron is already patching this behaviour. Are you sure it doesn't work for you?

**Comment by highacid** [comment]
Yes I am very sure. Turning on protection for registered apps throws me a not visible engintron page.

**Comment by fevangelou** [comment]
Oh, you mean AFTER you installed Engintron. OK, I'll see how this can get addressed.

**Comment by highacid** [comment]
Yes after Engintron was in place. And I did some hardening and come accross this.

**Comment by fevangelou** [comment]
OK. Marked to fix in v1.7.0.
