### ISSUE TITLE
When is the new version coming out?

### ISSUE THREAD

**Issue by ky1607** [engintron/engintron#188]
Firstly, I'd like to thank you for making such an awesome software. It has helped me a lot.

When will the new version coming out? With the features that is on the Wiki > Roadmap.

**Comment by fevangelou** [comment]
Already working on v1.7.0. Minor changes are always merged to the current release, so for example v1.6.1 offered for download (marked with Feb 2016 as release date) has been updated in May.

**Comment by ky1607** [comment]
Hey there.

Will the next released version support HTTPS?

**Comment by ky1607** [comment]
@fevangelou

**Comment by fevangelou** [comment]
That's coming with v1.8.0.

**Comment by ky1607** [comment]
@fevangelou - I'm so excited for this and I bet others too are. Any ETA for it at this moment?

**Comment by fevangelou** [comment]
Sept/Oct tops.
