### ISSUE TITLE
Engintron supports the https?

### ISSUE THREAD

**Issue by marcelodelta** [engintron/engintron#190]
I have accounts with use of https in subfolders, but error is displayed.

url: https://app.site.com/login

Not Found
The requested URL /login was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the requesta.

It can be a .htaccess error?

**Comment by Leykis** [comment]
This would be something related to your rewrites/script, not engintron specifically. Engintron has full HTTPS support and does not really require any custom configuration for it to work.

**Comment by fevangelou** [comment]
Actually Nginx does not work at all for port 443 (the HTTPS port). What you're seeing @marcelodelta is Apache so as @Leykis said it's probably an .htaccess issue.

Nginx will support HTTPS with LetsEncrypt integration as well in v1.8.0.
