### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by rapidcloubr** [engintron/engintron#191]
Hello,

Engintron installed in all my cPanel servers.

However I have some clients who work with frequent updates on their websites and the cache simply does not allow the customer to see the updates in real time.

How do I get Engintron ignore certain domains?

**Comment by Leykis** [comment]
The way engintron is setup you shouldn't need this. The most they should see is about 1 minute of caching, and in my experience this can be cleared on the users end by just doing a hard refresh. Within NGINX you can add exclusions per domain. I'll let the developers explain more about their caching method.

**Comment by rapidcloubr** [comment]
My clients are complaining that the CSS files are slow to update.

I found that even after sending the updated CSS file to the server, even clearing the browser cache the arquvio is not updated in real time.

**Comment by markbignell** [comment]
I am experiencing the exactly the same problem. Developers are complaining that they need to "Cleanup cache & temp files" in Engintron each time they edit css or php files. For now, exclusions per domain will be useful however it would be preferable if caching was less intrusive.

**Comment by rapidcloubr** [comment]
90% of my clients are developers, unfortunately I will have to remove the Engintron if there is no solution. I like to use engintron, I hope there is a solution.

I tried to add the domain exclusions through custom rules, but that did not solve the problem.

**Comment by rapidcloubr** [comment]
Due to delay for support had to temporarily disable. :(

**Comment by tess0072** [comment]
You need to use a cache busting technique of some kind on sites you are actively developing. I do lots of wordpress development and found that the plugin Busted! does exactly what i need it to do.

**Comment by markbignell** [comment]
Thanks for the tip, will check it out.

**Comment by rapidcloubr** [comment]
My clients are developers and are against the use of Wordpress, thank you for your tip, but infelzimente will not help me. = /

**Comment by justinbeatz** [comment]
You can suggest to your clients (as a workaround) to add random numbers at the end of the file, for example: style.css?v=<rand-number>, they can easily do this with php. Hope it helps.

**Comment by Leykis** [comment]
I've been developing a site on Engintron and instantly see all the changes after a hard refresh using F5 / CMD + R , no problems at all...

**Comment by markbignell** [comment]
Its interesting to note that in our experience some systems (e.g. Joomla) are refreshing perfectly fine, while others (Wordpress, some custom PHP dev) are not loading correctly after refresh.

**Comment by fevangelou** [comment]
You can simply disable the static asset cache of 1m if you don't wish to use it. PHP files are not affected, only static ones. So whoever reported PHP files are cached is wrong.

If you still use Engintron @rapidcloubr, let me know so I can provide you with the fix.

**Comment by fevangelou** [comment]
@markbignell Might depend on what type of caching WP sites have. Joomla has built-in caching, so it's mostly the same behaviour everywhere. WP on the other hand does not have a built-in caching mechanism, so different plugins may be used, and in consequence causing different issues or just behaving differently.

@Leykis Actually you won't see refreshed even if you do force a hard refresh on your browser. At least not until 1 min has passed THE MOST. The best option from any performance standpoint is to always use cache-busting techniques.

**Comment by rapidcloubr** [comment]
The main problem reported by my clients is the CSS file cache. How do I disable caching for CSS files?

**Comment by rapidcloubr** [comment]
Yes! I wear! Just let him off in order to find the solution!

**Comment by fevangelou** [comment]
I'd recommend you drop the cache time to say 3 secs which is fair for your use case.

Edit the file "proxy_params_static" via the Engintron WHM app and simply change line 24 from:
`proxy_cache_valid			200 301 302 1m; # Covers 200, 301 & 302 responses, caching time set to 1 minute`

to:
`proxy_cache_valid			200 301 302 3s; # Covers 200, 301 & 302 responses, caching time set to 3 seconds`

**Comment by Leykis** [comment]
@fevangelou Any plans to add a feature to change this per domain?

**Comment by fevangelou** [comment]
@Leykis Although you piched the ONLY value in Nginx that cannot be replaced by a variable, you'd be surprised how easy this is to do now. Open up the proxy_params_static file and replace this:
```proxy_cache_valid           200 301 302 1m; # Covers 200, 301 & 302 responses, caching time set to 1 minute```

with this:
```
if ($host ~ "example.com") { 
    proxy_cache_valid           200 301 302 3m; # Covers 200, 301 & 302 responses, caching time set to 3 minutes for domain example.com ONLY 
} 
if ($host !~ "example.com") { 
    proxy_cache_valid           200 301 302 1m; # Covers 200, 301 & 302 responses, caching time set to 1 minute for ANY domain BUT example.com 
} 
```

**Comment by fevangelou** [comment]
Considering issue resolved.
