### ISSUE TITLE
cPanel Web Sites on Static IP Addresses

### ISSUE THREAD

**Issue by Host4u** [engintron/engintron#192]
Hello.

We have a problem with web sites using the Engintron for cPanel/WHM plugin. The issue is that all sites which are on static IP's don't work and just give the cPanel default page. For example: takethepebble.com which is on the IP: 188.64.184.186

This is effecting all our sites which are not on the default shared server IP.

Have I missed something in the config or is this an issue and how do we work around this?

Paul.

**Comment by Leykis** [comment]
You'll need to exclude the domains with the specific IP. You can follow this on how to do that : https://github.com/engintron/engintron/wiki/Engintron-&-(under-development)-domains-that-don't-yet-resolve-(point)-to-your-cPanel-server

**Comment by Host4u** [comment]
Hello.

I have already done this but is this a bug or something which will be fixed in the future?

**Comment by fevangelou** [comment]
Actually, you shouldn't have to do this either way. Nginx resolves each internal domain using Google's Public DNS servers (8.8.8.8 & 8.8.4.4) so if requesting one of your domains does not end up serving that domain, maybe there's a problem for Nginx resolving these domains.

BTW, doing a "curl -I http://www.takethepebble.com/" looks like the site is correctly served by Nginx (via Engintron).

**Comment by marklajer** [comment]
Is it possible to setup engintron to automatic create an 

```
if ($host ~ "domain.tld") {
	set $PROXY_DOMAIN_OR_IP "xxx.xxx.xxx.xxx";
}
```
Entry when account adding a new domain ?

**Comment by fevangelou** [comment]
@marklajer You don't need to do this. These if blocks are to be setup only when using such a domain with CloudFlare or when you want to point a domain to your server when it's not propagated yet (for dev purposes).
