### ISSUE TITLE
Setting up HTTP Headers security

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#195]
Hello,

Since NGINX runs in back of Apache, I am wondering where the following rules should be added for effective work?

```
Header always set Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'"
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
Header always set Public-Key-Pins "pin-sha256='X3pGTSOuJeEVw989IJ/cEtXUEmy52zs1TZQrU06KUKg=';
pin-sha256='MHJYVThihUrJcxW6wcqyOISTXIsInsdj3xK8QrZbHec=';
pin-sha256='isi41AizREkLvvft0IRW4u3XMFR2Yg7bvrF7padyCJg=';
includeSubdomains; max-age=2592000"

add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubdomains" always;
add_header Public-Key-Pins "pin-sha256='X3pGTSOuJeEVw989IJ/cEtXUEmy52zs1TZQrU06KUKg=';
pin-sha256='MHJYVThihUrJcxW6wcqyOISTXIsInsdj3xK8QrZbHec=';
pin-sha256='isi41AizREkLvvft0IRW4u3XMFR2Yg7bvrF7padyCJg=';
includeSubdomains; max-age=2592000" always;

NginX: add_header X-Frame-Options "SAMEORIGIN" always;
Apache: Header always set X-Frame-Options "SAMEORIGIN"

NginX: add_header X-Xss-Protection "1; mode=block" always;
Apache: Header always set X-Xss-Protection "1; mode=block"

NginX: add_header X-Content-Type-Options "nosniff" always;
Apache: Header always set X-Content-Type-Options "nosniff"

```

**Comment by fevangelou** [comment]
/etc/nginx/proxy_params_common at the very bottom.

**Comment by highacid** [comment]
It seems to be an issue with current config in nginx, while some headers must be split in vhosts and allow 80: and also 443 to add headers messages. Any idea how I do this with the current config? The headers are validated as per: https://securityheaders.io/?q=highacid.com&hide=on&followRedirects=on yet I spoke with the tool developer and this some headers are only for HTTPS to reply to.

**Comment by fevangelou** [comment]
It's best to set these headers from your application/website only when you require it too.

**Comment by highacid** [comment]
How do I setup explicitly for HTTPS instead of HTTP the headers?

**Comment by fevangelou** [comment]
Nginx handles only HTTP traffic. For HTTPS traffic you should add these headers in Apache, via some .htaccess file.

**Comment by fevangelou** [comment]
Execute this as root from a terminal:

`grep processor /proc/cpuinfo | wc -l`

What does it output?
