### ISSUE TITLE
IPv6 related errors

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#196]
2016/07/08 04:29:20 [error] 41154#41154: *17527 connect() failed (113: No route to host) while connecting to upstream, client: 207.46.13.38, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[2001:41d0:2:21d:1::7]:8080/", host: "www.highacid.com"

**Comment by Leykis** [comment]
IPv6 does seem to be experiencing issues when engintron is enabled, checkout : #185

**Comment by fevangelou** [comment]
The setup on Nginx's side seems correct. Consult your hosting company for more info.
