### ISSUE TITLE
Wrong CPU reads

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#198]
Engintron reads Processors: 16 CPU(s) instead of 8...

**Comment by fevangelou** [comment]
CPU are the result of actual cores by threads. You may have a server with 2 cores each sporting 8 threads. That's 16 cores to the system.

**Comment by highacid** [comment]
I am sure it is one core.

**Comment by fevangelou** [comment]
Execute this as root from a terminal:

`grep processor /proc/cpuinfo | wc -l`

What does it output?

**Comment by highacid** [comment]
hm 16, weird 💯 my bad.

**Comment by fevangelou** [comment]
Told ya.
