### ISSUE TITLE
Compliance recommendations from nginx

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#202]
Hello, 

Lately I am early adopter of https://amplify.nginx.com/ from nginx, here are a few suggestions to improve the config file overall.

Warning – Location defined as regex has a valid regex operator, but does not include a regex pattern. It is generally more efficient to configure exact or prefix matching for locations that do not really require regex matching. Please refer the documentation describing location directive.

Check the following file(s):
/etc/nginx/conf.d/default.conf, line 114
Warning – location defined as regex has a regex pattern that does not include ^ or $. It is recommended that the regex pattern always includes anchors ^ and $.

Check the following file(s):
/etc/nginx/conf.d/default.conf, line 114
Warning – location defined as regex is set up for case-insensitive matching. It is recommended to generally avoid case-insensitive matching for regex locations since it’s prone to many errors.

Check the following file(s):
/etc/nginx/conf.d/default.conf, line 56
/etc/nginx/conf.d/default.conf, line 34
/etc/nginx/conf.d/default.conf, line 45
/etc/nginx/conf.d/default.conf, line 66

**Comment by fevangelou** [comment]
The regex's are correct. ^ means the start of a filename or path. When you target a file extension, this is invalid. These are mechanical RECOMMENDATIONS. If the rules didn't work, then Nginx wouldn't work at all.
