### ISSUE TITLE
Cache isn't working

### ISSUE THREAD

**Issue by proxieus** [engintron/engintron#203]
Hello,

I've installed it without any errors but I've noticed itsnot actuality caching anything, I've left it for a few hours and went to.l clear the temp/cache files within whm and its saying that it's empty, any idea on where to start to troubleshoot?

**Comment by proxieus** [comment]
Also when o try to run the update/reinstall option I get this error:


No response from subprocess (php): The subprocess ended prematurely because it received the “TERM” (15)

**Comment by highacid** [comment]
Check @ https://github.com/engintron/engintron/issues/115

**Comment by highacid** [comment]
@proxieus make a backup of your config if changed, try removing it completely and reinstall then.

**Comment by proxieus** [comment]
Awesome that's fixed it, thank you.

**Comment by fevangelou** [comment]
Just upgrade to v1.6.2 released yesterday :)
