### ISSUE TITLE
 horde and squirrelmail url not working

### ISSUE THREAD

**Issue by shivsingh7150** [engintron/engintron#204]
After enabling Engintron  horde and squirrelmail url not working working only roundcube is working,  is there any issue related to Engintron  , if yes please tell. you can see error screenshot 
![screenshot_1](https://cloud.githubusercontent.com/assets/3428506/16977190/493fe50c-4e72-11e6-9aba-fc308843d970.png)

**Comment by highacid** [comment]
have you checked your nameservers in nginx?

**Comment by fevangelou** [comment]
The subdomains "webmail" and "cpanel" are being proxied by Apache if I recall properly to the internal cPanel ports used.

The solution another user mentioned was to comment out the line "proxy_set_header X-Forwarded-Host $host;" in proxy_params_common.

Do it and let me know if it works. If it does, I'll include custom rules to correct this behaviour.

**Comment by shivsingh7150** [comment]
Thanks for update but it's still not working, i am using cloud linux also. any other solution please

**Comment by jcmdln** [comment]
Related to #207, might want to check my response there

**Comment by fevangelou** [comment]
Please let's continue this in issue #207 as @jcmdln already mentioned.
