### ISSUE TITLE
Micro Cache not working

### ISSUE THREAD

**Issue by manojENTITY** [engintron/engintron#208]
my get request header giving x-cache-status miss.
here are the headers for get request -
Connection	keep-alive
Content-Encoding	gzip
Content-Type	application/json
Date	 Fri, 22 Jul 2016 08:47:06 GMT
Server	nginx
Transfer-Encoding	chunked
Vary	 -Accept  Encoding
X-Cache-Status	  MISS
X-Server-Powered-By	Engintron

you can clearly see x-cache status coming miss. and i have also setup micro cache to 2 sec. but it looks like some how it's not serving through cache.

I wants to use Micro  Cache for post request also. can you please guide me how i can setup that. 
Here the headers for post request - 
Cache-Control	no-cache, must-revalidate, max-age=0
Connection	keep-alive
Content-Encoding	gzip
Content-Type	application/json
Date	Fri, 22 Jul 2016 08:47:08 GMT
Expires	Wed, 11 Jan 1984 05:00:00 GMT
Pragma	no-cache
Server	nginx
Transfer-Encoding	chunked
Vary	Accept-Encoding
X-Content-Type-Options	nosniff
X-Robots-Tag	noindex
X-Server-Powered-By	Engintron

for url you can check -  live.sportzwiki.com and request coming from cricket.entitysport.com
Please provide a detailed instruction so i can understand how to solve these issue.

**Comment by fevangelou** [comment]
Micro caching works just fine. Because it's 1 sec, you have to do "curl -I domain.tld" a few times in your terminal and pretty fast to actually see HIT.

Micro caching is turned off for POST requests because POST means data exchange and you don't wanna cache that, so avoid it.

**Comment by manojENTITY** [comment]
i have changed the micro cache to 10 seconds but still seeing miss.

**Comment by fevangelou** [comment]
I see different headers...

```curl -I http://live.sportzwiki.com/
HTTP/1.1 200 OK
Date: Fri, 22 Jul 2016 12:08:39 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Link: <http://live.sportzwiki.com/wp-json/>; rel="https://api.w.org/"
Link: <http://live.sportzwiki.com/>; rel=shortlink
Server: sportzwiki nginx
X-Cache: MISS
X-Cache-2: BYPASS```

**Comment by manojENTITY** [comment]
no check for GET Request url on that domain. requests coming from curl 'http://cricket.entitysport.com/live/index.php?_=1469189552386&a=live&mid=8601&lastball=27.0' -H 'Host: cricket.entitysport.com' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:48.0) Gecko/20100101 Firefox/48.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'X-Requested-With: XMLHttpRequest' -H 'Referer: http://cricket.entitysport.com/widgets/?layout=layout1&widgets=mid%3D8601%26widget%3Dmatch_centre%26location%3D1'

**Comment by manojENTITY** [comment]
no check for GET Request url on that domain. requests coming from curl 'http://cricket.entitysport.com/live/index.php?_=1469189552386&a=live&mid=8601&lastball=27.0'

**Comment by fevangelou** [comment]
I've lost you. What does this have to do with Engintron properly working on your server. I see a modified Nginx signature which means one thing. Nginx was installed from source on your server. If you want generic Nginx help, better post on forum.nginx.org.

**Comment by manojENTITY** [comment]
sportzwiki my client url. and widgets that are on that page is getting served from a server using engintron.
cricket.entitysport.com

**Comment by fevangelou** [comment]
Do I have to dig around? If you want help, get me the exact URL to curl from my terminal.

**Comment by manojENTITY** [comment]
just open firebug console on this URL live.sportzwiki.com . You will see GET request coming from cricket.entitysport.com. Just check header of that request you will see X-cache-status miss. I am using engintron on cricket.entitysport.com server. i am delivering widgets on live.sportzwiki.com URL.  just simple as that.

![untitled1](https://cloud.githubusercontent.com/assets/20593925/17057247/7cdda316-5036-11e6-8512-da32a4e743aa.png)

**Comment by fevangelou** [comment]
It works. Load it up multiple times with the cache turned off and you'll see. It's difficult to troubleshoot this way, since you're blocking requests externally (not very smart when you're still debugging the thing).

If these widgets can benefit from better caching, raise it to 60s (1 min).

**Comment by manojENTITY** [comment]
ok. thanks.
