### ISSUE TITLE
engintron with apache traffic server

### ISSUE THREAD

**Issue by manojENTITY** [engintron/engintron#209]
1. is it possible to use enginetron with Apache traffic server and c panel will work with Apache traffic serve?
2. can i use a combination of apache traffic server with nginx ? apache traffic server for backend and nginx as proxy.

**Comment by fevangelou** [comment]
1. No.

2. No.

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com
