### ISSUE TITLE
varnish cache

### ISSUE THREAD

**Issue by manojENTITY** [engintron/engintron#210]
is it possible to use a combination of apache + engintron + varnish ? if yes please provide some brief how i can do that.

**Comment by fevangelou** [comment]
No.

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by manojENTITY** [comment]
Hello  fevangelou,
i am using apache + varnish + engintron. i have linked up varnish cache with apache on port 8080 and nginx is still serving on as reverse proxy. i have turned off microcache on engintron but i am not getting any cache hit or miss results on my get requests with varnish. i have also tested it using curl. can you please tell me what changes i need to do on nginx so it can work with varnish cache to serve http request. we serve real time data on our server which needs to be refreshed in just few seconds so for that i opted to use varnish for dynamic request cache.

here are the details of my varnish  configuration on default.vcl -

sub vcl_recv {
    set req.grace = 60sec;

    if (req.request == "PURGE") {
        if(!client.ip ~ purge) {
            error 405 "Not allowed.";
        }

        purge("req.url ~ ^" req.url "$ && req.http.host == "req.http.host);
    }

    if (req.url ~ "\.(jpg|png|gif|gz|tgz|bz2|lzma|tbz)(\?.*|)$") {
        remove req.http.Accept-Encoding;
    } elsif (req.http.Accept-Encoding ~ "gzip") {
        set req.http.Accept-Encoding = "gzip";
    } elsif (req.http.Accept-Encoding ~ "deflate") {
        set req.http.Accept-Encoding = "deflate";
    } else {
        remove req.http.Accept-Encoding;
    }

    if (req.url ~ "wp-(login|admin)") {
        return (pass);
    }

    if (req.request != "GET" && req.request != "HEAD") {
		return (pass);
    }
	
	if (req.http.X-Requested-With != "XMLHttpRequest"){
		return (pass);
	}

    unset req.http.cookie;

    if (req.url ~ "\.(jpeg|jpg|png|gif|ico|swf|js|css|txt|gz|zip|rar|bz2|tgz|tbz|html|htm|pdf|pls|torrent)(\?.*|)$") {
        unset req.http.Authenticate;
        unset req.http.POSTDATA;
        set req.request = "GET";
        set req.url = regsub(req.url, "\?.*$", "");
    }
}

sub vcl_pipe {
    set bereq.http.connection = "close";

    if (req.http.X-Forwarded-For) {
        set bereq.http.X-Forwarded-For = req.http.X-Forwarded-For;
    } else {
        set bereq.http.X-Forwarded-For = regsub(client.ip, ":.*", "");
    }
}

sub vcl_pass {
    set bereq.http.connection = "close";

    if (req.http.X-Forwarded-For) {
        set bereq.http.X-Forwarded-For = req.http.X-Forwarded-For;
    } else {
        set bereq.http.X-Forwarded-For = regsub(client.ip, ":.*", "");
    }
}

sub vcl_fetch {
    set beresp.ttl = 5sec;
    set req.grace = 60sec;

    if (req.url ~ "wp-(login|admin)") {
        return (pass);
    }

    unset beresp.http.set-cookie;

    if (req.url ~ "\.(jpeg|jpg|png|gif|ico|swf|js|css|txt|gz|zip|rar|bz2|tgz|tbz|html|htm|pdf|pls|torrent)$") {
        set beresp.ttl = 24h;
    }
}

sub vcl_deliver {
    if (obj.hits > 0) {
        set resp.http.X-Cache = "HIT";
        set resp.http.X-Cache-Hits = obj.hits;
    } else {
        set resp.http.X-Cache = "MISS";
    }
}


i am also trying to store xmlhttp request using varnish. so this configuration is correct for me? and please provide some help so i can linkup it with nginx perfectly.

**Comment by fevangelou** [comment]
You don't need Varnish if you already have Nginx as a reverse caching
proxy. What you need to address as I mentioned in another issue you opened
is that you need to verify there is no cache busting done in your XHR
requests to the server. If there is cache busting performed, neither Nginx
nor Varnish can help you.

**Comment by manojENTITY** [comment]
Yes. You are right. Need to some tweaking on development side.
