### ISSUE TITLE
Micro cache for XHR content

### ISSUE THREAD

**Issue by manojENTITY** [engintron/engintron#211]
Hello fevangelou,
Can you please tell me how i can enable micro cache for xhr content and how i can also set a if modified condition for this micro cache? and i am looking to setup 5 sec. micro cache for that.  the content i am serving is xhr and it's x-cache status is coming miss. so can you please help me with that ?

**Comment by fevangelou** [comment]
If you're doing XHR using jQuery, you should know that jQuery does cache 
busting. So, no, you can't fix this unless you change your code.

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com
