### ISSUE TITLE
Logged out

### ISSUE THREAD

**Issue by irwanwan** [engintron/engintron#213]
Hai thanks for making engintron. You are life saver, my web really faster and drastically decreased on CPU/RAM load.
But why I keep getting logged out when Iam using engintron. I use wordpress with mod_pagespeed installed

**Comment by irwanwan** [comment]
And i also running on centos 7.2 latest cpanel+apache+php with .htaccess leverage browser cache and opcache installed.
Is it conflicting with leverage browser or opcache? Or mod_pagespeed maybe?
Thank you so much

**Comment by jcmdln** [comment]
When you say you "keep getting logged out", is there a specific time frame that this occurs? Might be due to the cookie session timeout set but unless it's happening while you are actively working may be a non-issue.

Any chance you could provide replication steps and an estimated duration of time that this takes place?

**Comment by fevangelou** [comment]
Nginx is already configured to tweak static and dynamic content headers for
client-side caching. There is no issue whatsoever with any opcode cache you
might use. What are your .htaccess rules beyond the defaults in WP?

**Comment by irwanwan** [comment]
@jcmdln hai thanks for your respond, it was always happened when i switch to another pages or go back to home page. it might be due to the cookie session as you mentioned, i set up mod_expires in my <directory> directives in httpd.conf

@fevangelou hai thanks for your reply, i am not using .htaccess anymore since i can access httpd.conf and i add <Directory> directives through Pre Virtual Host Include, as below

<Directory "../../public_html">
Options All
AllowOverride None
Require all granted
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
<IfModule mod_expires.c>
ExpiresDefault A0
ExpiresByType image/gif A2592000
ExpiresByType image/png A2592000
ExpiresByType image/jpg A2592000
ExpiresByType image/jpeg A2592000
ExpiresByType image/ico A2592000
ExpiresByType image/svg+xml A2592000
ExpiresByType text/css A600000
ExpiresByType text/javascript A259200
ExpiresByType application/javascript A259200
ExpiresByType application/x-javascript A259200
</IfModule>
<IfModule mod_headers.c>
<filesMatch "\.(ico|jpe?g|png|gif|swf|svg|xml)$">
Header set Cache-Control "public"
</filesMatch>
<filesMatch "\.(css)$">
Header set Cache-Control "public"
</filesMatch>
<filesMatch "\.(js)$">
Header set Cache-Control "private"
</filesMatch>
Header unset ETag
Header set Connection keep-alive
FileETag None
</IfModule>
<IfModule mod_deflate.c>
AddOutputFilterByType DEFLATE text/text text/html text/plain text/xml text/css text/javascript application/javascript
</IfModule>
</Directory>

**Comment by irwanwan** [comment]
@fevangelou just want to updated aabout keep logged out problem on my wordpress
it was stopped when I disabled proxy_params_dynamic in default.conf
And I commented out line in proxy_params_static
#proxy_hide_header           Set-Cookie;
#proxy_ignore_headers        Set-Cookie;
#proxy_set_header            Cookie "";
I think this set-cookie caused my wordpress keep logged out everytime I accessed dashboard
Is it wont be a problem if I did this comment out line in proxy_params_static?
Please advice, thanks

**Comment by ailyroot** [comment]
we need to know this too as we have same problems on wordpress users
any firmed solution please?

**Comment by fevangelou** [comment]
@irwanwan Commenting out the proxy_params_dynamic line in default.conf will switch off micro-caching for dynamic content. I don't know why this caused issues to you but in the many WP sites I operate with Engintron, there is no issue whatsoever. You don't need to comment out anything in proxy_params_static as this affects static files only which play no role in user sessions.

**Comment by irwanwan** [comment]
@fevangelou @ailyroot @jcmdln
Hai thanks for your response. Like i mentioned before that I commented out those lines in proxy_params_static and it really works.
Im no longer getting logged out when accessing wp-admin, especially when accessing users/member area for editing/approving.
I assumed its all about header and set cookie things that affected wp cookie session on wp-admin pages. Hope that you will find the real problems here and fix it.
Anyway, its all work now and just like magic decresing my server load drastically.
Thanks a lot for your hardwork, really appreciate that.
