### ISSUE TITLE
Enable/Disable Engintron Per-domain

### ISSUE THREAD

**Issue by jcmdln** [engintron/engintron#217]
An interesting feature would be to allow the user to selectively enable/disable Engintron per-site from cPanel, without interaction from an administrator/root to do so. Something similar to how the ModSec Manager in cPanel allows whitelisting or enabling/disabling per domain would be ideal.

This issue is mainly for tracking interest and general discussion of such a feature, please let me know if I should elaborate further or if the use-case is defined well enough.

**Comment by fevangelou** [comment]
I think it's doable although I haven't checked the cPanel API for creating
user options yet.

I'll add it to the roadmap to test in upcoming releases.

**Comment by ailyroot** [comment]
second this function!

**Comment by fevangelou** [comment]
This requires adding option to each user's cPanel interface. Adding to the roadmap (see the Wiki) and closing for now.
