### ISSUE TITLE
mod geoip (.htaccess rules) are not working on engintron (- 403 error on websites) .

### ISSUE THREAD

**Issue by jerrybopara** [engintron/engintron#219]
Hello Guys,
I've installed engintron on my WHM/Cpanel Server. Everything is working perfectly, but recently  I've noticed my some of websites are not working they are showing this  (- ERROR -  403 Forbidden error was encountered .)
In investigation i found that this is happening due to one .htaccess rule. I am using mod_geoip to restrict websites access for certain countries.
here's the my .htaccess rule  - 
<IfModule mod_rewrite.c>
      RewriteEngine On
      RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^(DZ|AO|CF|TD|KM|CG|CD)$
      RewriteRule .* - [F]
</IfModule>

If i remove this rule from .htaccess then my sites are came back and start running fine. but i want to use these rules from .htaccess due to some reasons, i can't remove them I've to resolve . 

So is there anyone who can help me to fix this use , and make mod_geoip htaccess rules running on my websites..

any help will be appreciated... Thanks in advance.. :)

**Comment by jerrybopara** [comment]
Hi Guy's,
I've found an another issue on Server while troubleshooting above issue - 

Issue -  Apache have Issue with Visitors Ip address, I check Apache access logs for  one of my domain, and see that Apache showing  Server Ip in logs instead of Visitors IP address.

After making changes in below files according to https://github.com/engintron/engintron/issues/69
- /usr/local/apache/conf/includes/remoteip.conf
- /usr/local/apache/conf/httpd.conf
and its start showing Visitor Ip Address in Apache Logs.

but still mod_GeoIP is not getting exact Visitor IP, and mod_GeoIP unable to block or allow specific Countries on the behalf of .htaccess.

So is there any way that we can pass Visitor Actual IP Address to .php and .htaccess Scripts.
Please suggest me that what i can do in this situation..

any help will be appreciated... Thanks in advance.. :)

**Comment by fevangelou** [comment]
Try re-installing Engintron. What Apache version do you have installed?

**Comment by jerrybopara** [comment]
Thank you for replying me back.. Thanks.
I'm using 
- WHM 56.0 (build 28)
-  Apache/2.4.18
- CENTOS 7.2 x86_64
and my server is running on AWS. I've tried with reinstalling  Engintron.
Now my access logs are looking like this  - http://screencast.com/t/E19gD4N72

Mod_GeoIp .htaccess rules and error which i'm facing on domain - http://screencast.com/t/zSE4QghAf
Please have a look ,,

Thanks..

**Comment by jerrybopara** [comment]
Hi fevangelou,

Could you please help me to figure out this issue, In my Case Mod_GeoIP is not getting actual visitor ip because Nginx is running in front of Apache. Nginx forwarding all http request to apache  with server's own ip.  That's by Mod_GeoIP is unable to block Countries or right IPs.

I'll be very Thankful for your any help..
Thanks. !

**Comment by bogdanrotariu** [comment]
Dear Sir,

After seeing you crying on engitron list I’ve read the docs for mod_geoip and you need to enable into the mod_geoip config :

GeoIPScanProxyHeaders On

This issue that you are encountering is related to the proxying that your are doing with engitron but should not be threated as “engitron issue”.

-- 
Bogdan-Stefan Rotariu
Sent with Airmail

On 1 August 2016 at 21:52:57, Jerry Bopara (notifications@github.com) wrote:

Hi fevangelou,

Could you please help me to figure out this issue, In my Case Mod_GeoIP is not getting actual visitor ip because Nginx is running in front of Apache. Nginx forwarding all http request to apache with server's own ip. That's by Mod_GeoIP is unable to block Countries or right IPs.

I'll be very Thankful for your any help..
Thanks. !

**Comment by jerrybopara** [comment]
Thank you :)
I know this is not a Engitron Issue, but this is one of good scenario where i'm trying to apply Engitron with my WHM Servers, where Mod_GeoIP is mostly used by our clients.
I'll really appreciate your help.. 
Thank you so much for giving me direction...

Thanks
