### ISSUE TITLE
cron problem fixed 

### ISSUE THREAD

**Issue by tammyrocks** [engintron/engintron#220]
i am getting emails from my sever every hour 

error: cannot resolve /tmp/nginx_client: No such file or directory

i have looked in /tmp and theres no /nginx_client

**Comment by hostfusion** [comment]
Hi,

If previously you have installed Nginx CP, you may remain some rest, and this is the result of cron daily for cleaning tm, delete the cron.

Regards

PS

**Comment by tammyrocks** [comment]
ok thanks 
could you give me some idea on where i would find it to delete it

**Comment by Leykis** [comment]
Possibly in Crontab, open with; `crontab -e`

Should look something like; `0 */1 * * * /usr/sbin/tmpwatch -am 1 /tmp/nginx_client`

**Comment by tammyrocks** [comment]
awesome
that fixed it thanks
engintron rocks
thanks for the great work

**Comment by fevangelou** [comment]
In v1.7.0 I've added the option to directly edit your server's crontab file from the Engintron WHM app :)

**Comment by zstergios** [comment]
I have the 1.8.1 and I got this annoying message.
This started after the upgrade on 1.8.0 I think.

I can fix that?

**Comment by fevangelou** [comment]
If you're getting the error originally mentioned (error: cannot resolve /tmp/nginx_client: No such file or directory) then you haven't properly uninstalled a previous Nginx for cPanel plugin.

Try @Leykis solution if you don't see the related cron job in /etc/crontab.

**Comment by zstergios** [comment]
I have already looked there....
http://prntscr.com/ef4rux
