### ISSUE TITLE
Revert to "Old" version

### ISSUE THREAD

**Issue by brinsleyparagao** [engintron/engintron#222]
Hello to every...
Its possible revert, install or reinstall the old (before this latest upgrade) version to make full work on my actual server ?
If yes, how to make ?

**Comment by fevangelou** [comment]
What's the problem?

**Comment by brinsleyparagao** [comment]
Because, the actual version 162, no work propelly in cpanel, some issues on subdomain system like a webmail. cpanel. whm. ( https://github.com/engintron/engintron/issues/207 )

i try comment **proxy_set_header X-Forwarded-Host $host;** but no efect. So i think in revert to previous version.

The "NEW" cpanel instalations no  have anymore ea3 so, i cant reverto to new cpanel, because engitron no compatible yet, and cant use 162 because no work fine yet.

**Comment by brinsleyparagao** [comment]
@fevangelou have some tip or fix to this?

**Comment by fevangelou** [comment]
Engintron v1.7.0 has been released with EA4 support. Upgrade :)
