### ISSUE TITLE
empty cache 

### ISSUE THREAD

**Issue by tammyrocks** [engintron/engintron#223]
Nginx Cache/Temp Disk Usage:
380K	/tmp/engintron_dynamic
1.1M	/tmp/engintron_static
4.0K   	/tmp/engintron_temp

the 3 caches are empty folders
when l clear the temp/cache files within whm and its saying that it's empty, any idea on where to start to troubleshoot?

in /tmp/engintron_static its making folder 1,2,3,a,b,c  etc  and there all empty 

i read a few posts here on problems no cache on CENTOS 7 
my server is  CENTOS 6.8 x86_64 vmware

**Comment by tammyrocks** [comment]
in another post theres this fix 

In CentOS the file is located here: /usr/lib/systemd/system/nginx.service

In there, change PrivateTmp=true to PrivateTmp=false and you're ready.


i do not have this folder /usr/lib/systemd/ ;et alone the rest of it

**Comment by fevangelou** [comment]
What you read is for CentOS 7.

The Nginx cache readings are normal for what you provided. If they where really empty, you'd see a few KBs for each folder referenced.

**Comment by tammyrocks** [comment]
they are empty 
static is 1.1 m  only from the amount of folders its made
and all the folders are empty

**Comment by fevangelou** [comment]
A folder occupies 4k if I'm not mistaken. 1.1m is thousands of folders.

Send me an actual domain to test remotely using curl.

**Comment by tammyrocks** [comment]
try this url
theopenretreat.com

even i set cache to 10 minutes 
and open the site in few browsers with few pages open in each 

none of the cache sizes increase 
i tryed load inpact with 500 open connections and same no changes to cache sizes 

is there a way of telling it where the static files are ??

**Comment by fevangelou** [comment]
Right... the URL you provided redirects to https://www.theopenretreat.com/ - Nginx does not cache HTTPS pages, that's why you see nothing in the cache.

**Comment by tammyrocks** [comment]
i have just spent a few hours google 
Nginx does not cache HTTPS 

and i can not find one page that says it does not cache https
theres lots on it dose cache https

**Comment by fevangelou** [comment]
There's like a big fat FAQ in the homepage of the repo: https://github.com/engintron/engintron#faq

But I guess few people bother reading those...

**Comment by tammyrocks** [comment]
I did not see them im on mobile and they not show on the page 
I had to switch to desktop version to see them
Thats awesome that its in the roadmap
