### ISSUE TITLE
Engintron Error with EasyApache 4

### ISSUE THREAD

**Issue by ihfbib** [engintron/engintron#224]
ENGINTRON ERROR:
 This server has EasyApache version 4 (beta)
 installed and Engintron is currently only compatible
 with EasyApache version 3 only!
 EasyApache version 4 will be supported
 in Engintron version 1.6.

 --- Installation aborted ---

**Comment by TheMongooseBytes** [comment]
Hi 

I am having the same issues upon upgrading our Cpanel server from Easy Apache 3 to Easy Apache 4. We really rely on Nginx as well.

**Comment by ihfbib** [comment]
Hi
How to downgrade to Easy Apache 3.

**Comment by fevangelou** [comment]
Update to v1.7.0 just released.
