### ISSUE TITLE
Wildcard DNS and Wordpress Multisites

### ISSUE THREAD

**Issue by ihfbib** [engintron/engintron#225]
Hello,
how to configure Engintron to enable WordPress Multisites in our servers via sub-domain?
like: *.domain.com

please help me.

**Comment by fevangelou** [comment]
If this is not already setup with Apache, then Nginx can't help you here.

**Comment by ihfbib** [comment]
With Apache working fine. But with Engintron I can't use it.
Can you tell me about virtual hosts on Engintron?
