### ISSUE TITLE
Need to try enable SSL support immediately

### ISSUE THREAD

**Issue by timeassistant** [engintron/engintron#228]
Hi @fevangelou 

With v58 of cPanel now being live, I have enabled autoSSL in WHM all our sites now use SSL at all times. After reading some other issues here I now realise engintron / nginx is now doing nothing for me at all as every domain is served via https which is just forwarded to apache

I know you have stated that SSL is planned for an upcoming release however I was wondering if there is a way to make nginx / engintron serve my pages instead of apache right now before the next update releases this functionality? (our sites are now running terribly slow as apache is just not keeping up !) and as we cannot yet use EA4 either so I have not been able to improve apaches performance at all. 

Any help would be great, each domain has its own SSL from cPanel / comodo via the AutoSSL section in WHM v58. 

We DON'T use cloudflare or anything else like that
our VPS has about 8 domains on it at the moment, its a CENTOS 6.8 x86_64 on a virtuozzo environment, with 3 xeon cores, 4 GB RAM.

I have also done most of the configs from the documentation for optimising etc

**Comment by fevangelou** [comment]
I'm afraid it's not that easy to implement. You should have first
considered the benefits of switching to SSL over better performance using
Nginx. Google cares about the latter more, as far as I know.

Either disable the certificates if you don't really need them (or the
redirects to HTTPS) or uninstall Engintron as the benefits to you are
currently zero.

**Comment by timeassistant** [comment]
Ah thats not what I was hoping to hear sadly.

Unfortunately we require both benefits of nginx and SSL. I really love engintron too I would hate to have to get rid of it.

Do you happen to know when the SSL support for engintron is likely to be released? Atleast if I do have to uninstall I would know when to come back to it

**Comment by fevangelou** [comment]
Months away for sure but no exact date.

**Comment by timeassistant** [comment]
Ah thats a real shame ! 

before removing engintron I will see if I can find a way to configure nginx to handle SSL (any advice or help would be very much appreciated). Otherwise it looks like I may have to defect temporarily to one of the other nginx whm plugins if they can offer SSL capability.

**Comment by fevangelou** [comment]
I'm afraid no other plugin for Nginx on cPanel provides HTTPS support. It basically boils down to how HTTPS works in the first place and how Nginx needs to be clone-configured with Apache.

In any case, you can keep Engintron for anything that is non HTTPS as it will not burden your system in any way.

Sign up to one of Engintron's social accounts to be notified for when HTTPS support comes. A newsletter will be added at some point in the coming weeks as well.

**Comment by timeassistant** [comment]
I was just wondering, If I reinstalled engintron, is it possible to manually set up SSL support? I know there are guides out there that cover nginx as a proxy to apache with SSL support I'm just wondering if file paths and actions would be different from engintron to a generic nginx install? 

(either that or is there any way I can help you to progress your SSL support?)

I do miss having engintron so does our server CPUs, even the interface itself was great for general management...

**Comment by fevangelou** [comment]
Short answer: no.

If it were simple I would have told you about it. I don't see though why you can't have Engintron on. Both HTTP and HTTPS will work. Any HTTP traffic will simply pass from Engintron. There must be parts of your sites that probably load over HTTP only. There's no overhead having Engintron on.

**Comment by timeassistant** [comment]
Yeah ok fair point, it does seem like a complex task.

I could reinstall engintron, **and I might just for the use of the GUI alone** - but all of our sites (when I finish updating the last couple stragglers) will be using HTTPS for everything so that the browsers do not flag up issues with mixed content etc. 

I actually can't think of anything that will be unsecured now as the free AutoSSL provided by cpanel covers all domains and sub domains. Not only that because we use wordpress on most sites I have added rules to .htaccess to ensure everything is passed as https aswell.

However as I said above I think I am going to reinstall engintron purely for the GUI functionality atleast until you are able to support SSL.

**Comment by fevangelou** [comment]
v1.8.0 with HTTPS support will probably come first ;) It will also include goodies for better/longer caching for WordPress sites, without messing with logged in users. :)

**Comment by timeassistant** [comment]
This sounds pretty good, I dont imagine you have an intended release date for 1.8.0?

The wordpress caching is intriguing but your configs that you provide in the docs worked great for our wordpress sites.  Especially along side W3Total Cache and Redis (also use the wordpress redis object cache). I have even just switched our php session handling from files to Redis for the full server. Perhaps you could look into adding Redis into engintron for additional caching etc it could be a very nice solution to compliment nginx if you can make it work out. 

also in terms of your caching for wordpress, if you had the time you could even create an engintron wordpress plugin, it could listen out for certain actions in wordpress (log in / out. publishing posts etc) and could then send commands to nginx to flush cache etc, that could then possibly allow you to give some control to the user via gui... or perhaps you could make that work from the WHM plugin itself

**Comment by fevangelou** [comment]
A WP plugin is not really required as WP already has everything that's required to better control caching.

**Comment by timeassistant** [comment]
Ah I see, sounds like you may have already been looking into this ;)
