### ISSUE TITLE
Cache size up to 80GB

### ISSUE THREAD

**Issue by tuwid** [engintron/engintron#229]
I have just installed engintron with the default settings and within a day I got on all my servers a /tmp/engintron_temp directory between 60-80GBs . 

These directives look legit but i still have tons of files and the total its filling up my disk
```
	# Proxy Settings
	proxy_cache_path /tmp/engintron_dynamic levels=1:2 keys_zone=engintron_dynamic:20m inactive=10m max_size=500m;
	proxy_cache_path /tmp/engintron_static levels=1:2 keys_zone=engintron_static:20m inactive=10m max_size=500m;
	proxy_temp_path /tmp/engintron_temp;
```

Can these be tweaked to set a max folder size ? Can these be stored in RAM or should I create a ramfs and mount it there ?

**Comment by gfxdesigner** [comment]
There is a variable that can be set called "max_size".

If this variable is not set then the cache size can fill the remaining space on your drive but this can be set to any value that fits your server size.

Once the cache fills up the max size set spacethe systems "cache manager" will remove the oldest/least used items to conserve space.

**Comment by tuwid** [comment]
I didnt changed it but as I can see the value is set to 500m. Is that an appropriate value ?

**Comment by gfxdesigner** [comment]
I believe that would be sufficient from my limited research. However, I am pretty new to this, so perhaps someone else can make a comment.

**Comment by tuwid** [comment]
I've seen in default whm installations that the tmp folder is not on a separate partition (this is a very bad thing from a security perspective btw) so basically the cache never fills up as it would proceed to fill up the entire disk first. The /dev/sh thats mounted on ram usually has access to half of the ram installed in the system and its paritioned (so it can be filled up )

**Comment by tuwid** [comment]
Fixed by doing this workaround:

```
mkdir /dev/shm/engintron_dynamic
mkdir /dev/shm/engintron_static
mkdir /dev/shm/engintron_temp
chown nginx /dev/shm/engintron*

```
And i altered the nginx.conf file as follows 
```

  # Proxy Settings
  proxy_cache_path /dev/shm/engintron_dynamic levels=1:2 keys_zone=engintron_dynamic:20m inactive=10m max_size=500m;
  proxy_cache_path /dev/shm/engintron_static levels=1:2 keys_zone=engintron_static:20m inactive=10m max_size=500m;
  proxy_temp_path /dev/shm/engintron_temp;
```

This is also way faster

**Comment by codep0et** [comment]
@tuwid this is great and way faster. Only thing I noticed is in WHM, on the Engintron plugin page, the status of the cache still shows the /tmp folder sizes. Do you have an idea where to edit that so it shows up the right info ?

Thanks

**Comment by tuwid** [comment]
@codep0et thats hardcoded in the php file at https://github.com/engintron/engintron/blob/master/app/engintron.php line here 
https://github.com/engintron/engintron/blob/master/app/engintron.php#L353 : 

`$ret .= trim(shell_exec("du -sh /tmp/engintron_*"))."<br /><br />";`

and here : 

https://github.com/engintron/engintron/blob/master/app/engintron.php#L90 
```
	case "nginx_cleanup":
			$command = shell_exec("find /tmp/engintron_dynamic/ -type f | xargs rm -rvf; find /tmp/engintron_static/ -type f | xargs rm -rvf; find /tmp/engintron_temp/ -type f | xargs rm -rvf");
			if(empty($command)) {
				$output = "<p>No output generated. Nginx cache & temp folders are probably empty.</p>";
			} else {
				$output = "<p>".nl2br($command)."</p>";
			}
			break;
```

**Comment by codep0et** [comment]
@tuwid Ah I see, thanks for the info !

**Comment by fevangelou** [comment]
v1.8.0 or 1.9.0 of Engintron will offer a configuration/options page where you'll be able to set the path to the temp files used by Engintron.
