### ISSUE TITLE
No auto ( Cleanup cache & temp files ) Function

### ISSUE THREAD

**Issue by bissan789** [engintron/engintron#232]
Hello, 

Great plugin for sure . It just will be amazing if there is that function auto  ( Cleanup cache & temp files ) . 

It is really important most of time my site getting high load and every time I did  ( Cleanup cache & temp files ) it solved that . 

So would you tell me please how to setup that auto function to be running every 10 minutes ? 

Thanks

**Comment by tuwid** [comment]
Try the solution at the end of this issue
https://github.com/engintron/engintron/issues/229

I would suggest to set a tmpfs partition with a fixed size of several gigs and set the temp there.

**Comment by bissan789** [comment]
@tuwid

Thank you for your response . Yes I read that and it is really not what I was looking . 

the file size is normal it just I am looking for away to do clean regularly in cron job . Is it possible to make it do clean every 10 minutes , 

And I have a question away from this point : 

When the plugin will be supported at apache 4 ? 

Thanks

**Comment by bissan789** [comment]
Any response ?

**Comment by tuwid** [comment]
@bissan789 
1 - whats the issue with the cronjob ? 
2 - You can refer to issue https://github.com/engintron/engintron/issues/233 for a followup on easyapache4

The cleanup function its located here 
https://github.com/engintron/engintron/blob/master/app/engintron.php#L90
and it goes as follows:


```
		case "nginx_cleanup":
			$command = shell_exec("find /tmp/engintron_dynamic/ -type f | xargs rm -rvf; find /tmp/engintron_static/ -type f | xargs rm -rvf; find /tmp/engintron_temp/ -type f | xargs rm -rvf");
			if(empty($command)) {
				$output = "<p>No output generated. Nginx cache & temp folders are probably empty.</p>";
			} else {
				$output = "<p>".nl2br($command)."</p>";
			}
			break;
```
I really dont see the need for an autoclean function but if you really need that you basically you should put a simple script like follows 

```
#!/bin/bash
find /tmp/engintron_dynamic/ -type f | xargs rm -rvf 
find /tmp/engintron_static/ -type f | xargs rm -rvf 
find /tmp/engintron_temp/ -type f | xargs rm -rvf
```

**Comment by fevangelou** [comment]
@bissan789 You don't really need an autoclean option with a cron job, as Nginx makes sure to keep its cache/temp folders tidy.
