### ISSUE TITLE
Cant start nginx

### ISSUE THREAD

**Issue by duohost** [engintron/engintron#234]
Hello, i have installed engintron and it cant install nginx.

**Comment by KingServer** [comment]
try command


centos 6
# service nginx restart

centos 7 
# systemctl restart nginx

**Comment by duohost** [comment]
I tryed but it didnt restarted

**Comment by katmai** [comment]
then it would be nice if you read the logs and provide some errors if 
you wanted any help at all. i have no idea how some of you guys even 
manage to get people to pay you to provide services when you don't know 
basics.

**Comment by duohost** [comment]
After secon install, it have been everything good. Thank you for help. I know that i have to show my log and all, this is not first time, i asking for help here.
