### ISSUE TITLE
*** EasyApache 4 & Engintron v1.7.0 bug reports HERE ***

### ISSUE THREAD

**Issue by fevangelou** [engintron/engintron#235]
Please post any bug reports related to EasyApache 4 & Engintron v1.7.0 here.

Thank you.

**Comment by ihfbib** [comment]
How to enable Wildcard DNS with it for WordPress Multisites as subdomain?

**Comment by fevangelou** [comment]
@ihfbib how is this specific to EA4 and v1.7.0 of Engintron?

**Comment by ihfbib** [comment]
@fevangelou  here is article from worddpress.org 
https://codex.wordpress.org/Configuring_Wildcard_Subdomains_for_multi_site_under_Plesk_Control_Panel
and here is how to enable it with Apache:
http://www.inmotionhosting.com/support/edu/cpanel/cpanel-manage-domains/wildcard-subdomains-and-dns

Thanks

**Comment by fevangelou** [comment]
Do not cross post please. You have already opened another issue. Respond there.

**Comment by brinsleyparagao** [comment]
Hello, the bug with cpanel/webmail subdmain persists
http://imgur.com/qBar5nf
And i try comment the string but the error its here !
> proxy_set_header    X-Forwarded-Host $host;

**Comment by fevangelou** [comment]
@brinsleyparagao this does not relate to EasyApache 4. Continue at the other issue please.

**Comment by vacancy12345** [comment]
After making ripe for cloudFlare custom_rules setting out for Nginx opened over other sites that do not use CloudFlare's IP address falls to the default page, I think there is a problem VHOST origin.

Should we add all IP addresses on the server?

**Comment by wandiabdullah** [comment]
I have server using cpanel and EA 4 engintron already installed on my server,but nginx is not working properly. I have screenshot error from my server. https://s4.postimg.org/puunf0itp/engintron.jpg

**Comment by fevangelou** [comment]
@wandiabdullah were you already using another Nginx plugin for cPanel? If so, remove that first and then install Engintron. Or provide more info for your system and the changes you've made that could affect this.

@vacancy12345 are you calling IPs or domain names? If you it's the latter, do they have proper DNS records?

**Comment by wandiabdullah** [comment]
@fevangelou no, server is fresh and latest version. I'm not change configuration for the server. Server suing default config and fresh i tried install engintron and having problem.

**Comment by vacancy12345** [comment]
DNS records are good. It analyzes the website address is resolv IP address.

No problems with the site on the main ip address. Problem only additional ip adress and sites.

**Comment by fevangelou** [comment]
@wandiabdullah Re-install Engintron just in case.

@vacancy12345 Can you mention one of your domains in a separate IP?

**Comment by wandiabdullah** [comment]
@fevangelou how to re install engintron?

**Comment by fevangelou** [comment]
Look closer at the Engintron WHM app...

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by hostmikroid** [comment]
engintron is not working properly in my server
it's always '504 Gateway Timeout'

```
[root@sclnode etc]# curl -I -L sclnode.myhosting.com
HTTP/1.1 504 Gateway Time-out
Server: nginx
Date: Sat, 20 Aug 2016 06:33:40 GMT
Content-Type: text/html
Content-Length: 176
Connection: keep-alive

```

**Comment by fevangelou** [comment]
Did you have any other plugin for Nginx previously installed? Cause I don't
see Engintron specific headers in that curl command.

**Comment by hostmikroid** [comment]
@fevangelou always '504 Gateway Timeout' due to upstream timeout
 ```
2016/08/22 00:20:59 [error] 11547#11547: *1 upstream timed out (110: Connection timed out) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: localh$
2016/08/22 00:22:36 [error] 11547#11547: *14 upstream timed out (110: Connection timed out) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: local$
2016/08/22 00:26:54 [error] 11546#11546: *16 upstream timed out (110: Connection timed out) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: local$
2016/08/22 00:27:09 [error] 11546#11546: *24 upstream timed out (110: Connection timed out) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: localho$
 ```

**Comment by fevangelou** [comment]
Can you call Apache (any domain) by using port :8080?

**Comment by hostmikroid** [comment]
yes i can call any domain and ip address using port 8080

**Comment by fevangelou** [comment]
504 errors are usually related to a slow backend (=Apache). How many 
seconds does it take to load one of the sites you tested with Apache?

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by hostmikroid** [comment]
this is weird, i can't curl to website hosted in my server
i think it's related with why engintron always timeout
an error happens and i don't know what/why

**Comment by fevangelou** [comment]
@hostmikroid Make sure port 8080 is open internally just in case - this is probably the reason Nginx can't communicate with Apache.

**Comment by fevangelou** [comment]
To ALL: Closing this issue as it appears the issues are not SPECIFICALLY related to Engintron and EasyApache4. Please open separate issues if you still need support to each issue you've already referenced here.
