### ISSUE TITLE
Auto Restart when down

### ISSUE THREAD

**Issue by ahlul** [engintron/engintron#239]
Hi,

Is nginx service will start again automatically when it down?

Thanks :)

**Comment by fevangelou** [comment]
I believe so, cause it's registered as service. You can test it out. Issue:
`$ service nginx stop`

5 to 10 seconds later execute:
`$ pstree`

If you see "nginx" in the list, it has restarted automatically.

**Comment by ahlul** [comment]
Ok thanks :) I'll try.
