### ISSUE TITLE
How to installing http2 module?

### ISSUE THREAD

**Issue by mgilank** [engintron/engintron#241]
Hi, how to compiling nginx so it get module http2? https://nginx.org/en/docs/http/ngx_http_v2_module.html
thanks!

**Comment by katmai** [comment]
httpd/2 works only with ssl ... engintron doesn't support ssl yet ...

**Comment by mgilank** [comment]
Alright. I want to know if i used nginx for reverse proxy like this, where
should we put http2 module? Is that in apache or nginx?

Thanks!

**Comment by fevangelou** [comment]
HTTP/2 is supported right out of box in the newest Nginx releases, the 
ones installed from the official Nginx repo, as used by Engintron. 
However enabling HTTP/2 (it's just a setting, no need to compile any 
additional modules) affects only HTTPS traffic which is currently not 
supported by Engintron's Nginx setup. This is a feature coming soon. 
However for HTTP traffic you get all the benefits of caching/fast 
delivery and low server responses.

Follow Engintron in one of the 3 social accounts I run to get notified 
when the new release is out.

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by mgilank** [comment]
Cool, i just want to let you know, that we can follow this tutorial i found to implement http2 on cpanel server with easyapache 3, it works for me with engintron installed
here you go: https://vpsineu.com/blog/how-to-setup-http2-in-cpanelwhm-linux-vps-using-easyapache3/

**Comment by fevangelou** [comment]
This is really ALL you need: https://bjornjohansen.no/enable-http2-on-nginx

The complicated bit though is making HTTPS global for Nginx in the current
version of Engintron.

The link you referenced explains a generic (and incomplete) way to install
Nginx on cPanel. But how does Nginx connect with Apache? Is this for one
domain only? Engintron already does more.

**Comment by mgilank** [comment]
Hi, i have seen that link to. my concern is implementing http2 along side EA3 and engintron. the link i provide is work in all my server.
cheers!

**Comment by fevangelou** [comment]
Considering the issue resolved for now.
