### ISSUE TITLE
Remove X-Server-Powered-By: Engintron from headers?

### ISSUE THREAD

**Issue by johnknock** [engintron/engintron#247]
Can you tell me how best to remove 'X-Server-Powered-By: Engintron' from my headers please?

I currently have set expose_php = off but it still shows.

Thank you.

**Comment by brinsleyparagao** [comment]
@johnknock go to
whm > plugins > engintron > edit proxy_params_common
and in this line just comment
`# add_header X-Server-Powered-By "nginx";`

**Comment by johnknock** [comment]
Perfect, thank you for your help.
