### ISSUE TITLE
How I can install testcookie nginx module?

### ISSUE THREAD

**Issue by privatery** [engintron/engintron#250]
Hello

I want to install testcookie module for nginx. It blocks me ddos attacks Layer 7.
How I can add this module in nginx? 

Thanks for help!

**Comment by fevangelou** [comment]
Never heard of it. URL?

**Comment by privatery** [comment]
Is not popular module, but very  helpful against ddos layer7 attacks.

Here on github?
https://github.com/kyprizel/testcookie-nginx-module

I'm wondering how I can add modules to nginx?

**Comment by fevangelou** [comment]
Until it's turned to a dynamic module, you won't be able to use it. Plus a) it does not mitigate DDos attacks (impossible with one server either way) nor DoS attacks (CSF is better here) and b) it looks like you don't really need it if its purpose it to block crawling bots...
