### ISSUE TITLE
Easyapache build error

### ISSUE THREAD

**Issue by johnknock** [engintron/engintron#252]
When following the Wiki (https://github.com/engintron/engintron/wiki/Beyond-Engintron:-cPanel-WHM-initial-optimal-setup) and using the easyapache build here:

`https://engintron.com/files/cpanel/engintron.dtd`

I get the following error:

`!! The profile item 'Cpanel::Easy::PHP5' is set to an out-of-date or unavailable version. EasyApache set the version to the latest version, '5_38', by default. !!`

Is it just a case of selecting PHP v5.6 and keeping everything else as it is?

**Edit
Just to add, I have now upgraded to easyapache 4, maybe you could supply your latest, recommended build in JSON format for dropping into /etc/cpanel/ea4/profiles/custom/ directory?

Thanks.

**Comment by fevangelou** [comment]
That was just a warning, nothing that would stop you from finishing the build with EA3. I haven't yet made an EA4 profile but I plan to upgrade both soon now that Engintron supports both.
