### ISSUE TITLE
Engintron issue

### ISSUE THREAD

**Issue by zsrik** [engintron/engintron#253]
Hi,
I am trying to install engintron on a new server. After installation, nginx and apache are both active however the website on the server wont load.
After disabling engintron, it loads fine. Any inputs would be appreciated.

**Comment by wgalafassijr** [comment]
I have the same issue. New server installed Engintron and i have 504 Gateway Time-out

ps. i'm running at amazon ec2

**Comment by Mike981874** [comment]
Are you guys using CloudFlare?

**Comment by wgalafassijr** [comment]
I'm using AWS with NAT

**Comment by wgalafassijr** [comment]
To make Engintron work i have to do this: https://github.com/engintron/engintron/wiki/Engintron-&-(under-development)-domains-that-don't-yet-resolve-(point)-to-your-cPanel-server

But i believe that Engintron have in the future to detect this kind of "setup" and do this in a automated way...

**Comment by fevangelou** [comment]
Engintron can't detect this. And of course, no production server works with tweaks in the devs hosts file, right?

**Comment by wgalafassijr** [comment]
I believe in some way Engintron need to detect when the server is in a nat enviroment because it's impossible to manually manage this if we have alot of domains hosted. Today Amazon is a big player and in my opinion make Engintron compatible with their environment it's a good idea. Thanks for make this great plugin.

**Comment by fevangelou** [comment]
However AWS does not impose a NAT in any way. That is your setup. BTW, all you probably had to do is also open port 8080 in your NAT setup and have it point where 80 does already...

**Comment by wgalafassijr** [comment]
All AWS environment is based in nat and dhcp (even Cpanel made some changes to recognize this and work without problems)

**Comment by fevangelou** [comment]
What changes did cPanel implement? And if you're talking about EC2, no NAT
is enforced anywhere.

**Comment by wgalafassijr** [comment]
I'm mentioning Cpanel nat support.

**Comment by fevangelou** [comment]
If you're referring to this https://documentation.cpanel.net/display/ALD/1%3A1+NAT cPanel have created a web service which cPanel (installed on your server) uses to identify a site's actual public IP. Even so, you actually need to configure cPanel for that, it cannot do so automagically. If you setup a NAT, I'll repeat that it's your responsibility to setup networking properly.

**Comment by windsofchange** [comment]
Update we just got Engintron working on AWS NAT config just by ensuring
- port 8433 8080 are open incoming & outgoing on all firewall / VPC etc
- add NAT local IP to csf.allow (or whichever firewall you are using)
- in custom_rules configure
if ($host ~ "website.com") {
     set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX";

**Comment by fevangelou** [comment]
The first 2 rules are purely network related due to your setup. The last is
what Engintron requires to redirect Nginx to Apache ;)
