### ISSUE TITLE
admin-ajax.php cache

### ISSUE THREAD

**Issue by manojENTITY** [engintron/engintron#256]
Hi,
On earlier version 1.7.1 we are able to cache one of our request using admin-ajax.php to deliver content. method is get. and we were also getting hit on cache status however after new update 1.7.2 that request giving bypass cache status. how we can solve that. and it's giving default max-age=0 on response headers.

**Comment by fevangelou** [comment]
See proxy_params_dynamic for the added changes. You're probably hitting some rule there which switches off caching for dynamic content.
