### ISSUE TITLE
Certain domains still served by apache

### ISSUE THREAD

**Issue by Mike981874** [engintron/engintron#257]
Hello,

I have Engintron installed (latest cPanel as of 8/31), I have a couple accounts with different domains, one account has a generic forum software and it's being served through Nginx perfectly fine. However on a different cPanel account a domain is being served directly by Apache; it's a basic html/css page on the main site and a php software in its own directory. I'm not too fond of the Nginx configurations, what would I do to troubleshoot this?

**Comment by fevangelou** [comment]
Is the second domain served over HTTPS?

**Comment by Mike981874** [comment]
Yes, it is.

**Comment by fevangelou** [comment]
Engintron sets up Nginx for HTTP traffic only for now. It's in the FAQ.

**Comment by Mike981874** [comment]
Thanks, didn't see that. I'll take another look.
