### ISSUE TITLE
Images not caching (x-cache-status: miss)

### ISSUE THREAD

**Issue by johnknock** [engintron/engintron#258]
Hi Fotis,

Following on from our earlier emails, I have changed the following lines in proxy_params_dynamic in a hope of experimenting with caching dynamic content (1 minute):

```
set $EXPIRES_FOR_DYNAMIC "1m";
proxy_cache_valid       1m;
```

Although you mention in the email that it is working fine, whenever I check any pages on the site (I have already sent you link), all of the images are showing x-cache-status: miss when the page is refreshed within the minute.

Am I doing something wrong?

Thank you.

**Comment by fevangelou** [comment]
Use the terminal with "curl -I http://your_url_here". That's the only reliable way. I tested your site and it worked just fine.

**Comment by johnknock** [comment]
Does that return the page as a whole though?  Is there a way of seeing what has been cached for each page element?

For example, if I use online checkers to see what elements of my pages are cached or not, I'm seeing that some things are cached, but most aren't.  This is the same for all online checkers I have come across so far.

Even basic speed test sites such as gtmetrix.com have a waterfall chart that show what elements of the page have been cached and what hasn't.  I'm seeing some are being cached, but most aren't?

Thanks for your help/insight with this.

**Comment by fevangelou** [comment]
The entire output is cached. Simply change something in the actual HTML that renders the output and see if it changes instantly for you.

The tools you've used can't tell you if the page they render (during testing) is a server-side snapshot of the actual website as in the case of Engintron.

**Comment by johnknock** [comment]
Thank you for the information, I will experiment some more.

My first question however is shouldn't the cached page show a lot faster than the initial page?  If you remember from my earlier emails to you, the initial page is generated dynamically via a remote API so the cached page should negate the need for this and should show a lot faster?  I'm not seeing this however.

**Comment by johnknock** [comment]
Just further information - I am doing as you suggest and changing the HTML.  The changes are immediate on page refresh and are not caching for the minute as it should.  Anything else you would like me to try that might help you to help me?

Thanks.

**Comment by fevangelou** [comment]
It works. You have to be more precise with your tests though. If you call a page, then go to change something in that page which takes you more than a minute and then you refresh the page, as you understand the content will change and the cache created in the very first hit will have expired now and a new one will be created.

**Comment by johnknock** [comment]
I was careful of this.  I will change it to 60 minutes to be sure.  Feel free to contact me to observe this happening when you are free.

**Comment by fevangelou** [comment]
On a second look, you're talking about images and yes, caching is not done server side because a cookie is passed. Do this. Edit "proxy_params_static" and you should see 2 lines commented at the bottom. Uncomment "#proxy_hide_header          Set-Cookie;" first, restart Apache/Nginx and check. If you don't see a HIT message after the first "curl -i URLtosome.jpg", the uncomment the 2nd line as well and re-test.

**Comment by johnknock** [comment]
Thank you.  Do I keep the proxy_params_dynamic changes I have already made whilst carrying out the above?

**Comment by fevangelou** [comment]
Yes, because that affects the dynamic content (HTML generated by WP in your case). You can also adjust the cache time Nginx does for static content in the "proxy_params_static" file from 1m that is now to more. This time value instructs Nginx how long to keep and serve a static file retrieved from Apache, without re-requesting from Apache. If you content changes rarely you can increase that time value to hours and you'll see a significant performance boost.

**Comment by johnknock** [comment]
Thank you very much for your help with this.

I have carried out the changes you outlined to proxy_params_static (uncommenting both lines) and I restarted nginx/apache each time, but html changes are still happening on browser refresh.  I currently have proxy_params_static set to the following to ensure no timeouts:

```
set $EXPIRES_FOR_DYNAMIC "30m";
proxy_cache_valid       30m;
```

Is there anything else I could try?  Weird that it isn't working for me and me alone though.

**Comment by fevangelou** [comment]
Let's clear things out a bit. Caching for dynamic content (HTML) is different to static content like CSS, JS and image files. Curl'ing your home page indicates a HIT. Curl'ing a static image file returns a MISS (always). I can spot a "Pragma: no-cache" header injected in both. That's probably some WP plugin (I guess).

So try this. Set the contents for proxy_params_dynamic to:
```
# /**
#  * @version    1.7.2
#  * @package    Engintron for cPanel/WHM
#  * @author     Fotis Evangelou
#  * @url        https://engintron.com
#  * @copyright  Copyright (c) 2010 - 2016 Nuevvo Webware P.C. All rights reserved.
#  * @license    GNU/GPL license: http://www.gnu.org/copyleft/gpl.html
#  */

# === MICRO CACHING ===
# 1 second (1s) micro-caching enabled for all proxied dynamic HTML content
# If you wish to have longer cache times, adjust lines any "1s" occurrence
set $CACHE_BYPASS_FOR_DYNAMIC 0;
set $EXPIRES_FOR_DYNAMIC "30m";

# CMS (& CMS extension) specific cookies (Joomla, K2, WordPress)
if ($http_cookie ~* "joomla_[a-zA-Z0-9_]+|userID|comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $EXPIRES_FOR_DYNAMIC 0;
}

# Invision Power Board (IPB)
if ($cookie_member_id ~ "^[1-9][0-9]*$") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $EXPIRES_FOR_DYNAMIC 0;
}

# Admin sections & generic entry point names for CMSs
if ($request_uri ~* "/administrator|/wp-admin|/wp-login.php|/ucp.php|/login|/connect") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $EXPIRES_FOR_DYNAMIC 0;
}

# Generic query string to request a page bypassing Nginx's caching
if ($query_string ~* "nocache") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $EXPIRES_FOR_DYNAMIC 0;
}

proxy_no_cache          $CACHE_BYPASS_FOR_DYNAMIC;
proxy_cache_bypass      $CACHE_BYPASS_FOR_DYNAMIC;

proxy_cache             engintron_dynamic;
proxy_cache_key         "$request_method$scheme$host$request_uri";
proxy_cache_lock        on;
proxy_cache_methods     GET HEAD;
proxy_cache_use_stale   error timeout invalid_header updating http_500 http_502 http_503 http_504; # Additional options: http_403 http_404
proxy_cache_valid       200 30m; # Adjust for longer cache times (unfortunately, we cannot use a variable here)
proxy_ignore_headers    Expires Cache-Control Set-Cookie Vary;
proxy_hide_header       Expires;
proxy_hide_header       Cache-Control;
proxy_hide_header       Vary;

# Headers
expires                 $EXPIRES_FOR_DYNAMIC;
add_header              Pragma "public";
add_header              Cache-Control "public";
add_header              Vary "Accept-Encoding";
```

Now set the contents of proxy_params_static to:
```
# /**
#  * @version    1.7.2
#  * @package    Engintron for cPanel/WHM
#  * @author     Fotis Evangelou
#  * @url        https://engintron.com
#  * @copyright  Copyright (c) 2010 - 2016 Nuevvo Webware P.C. All rights reserved.
#  * @license    GNU/GPL license: http://www.gnu.org/copyleft/gpl.html
#  */

# === STATIC ASSET CACHING ===
# Proxy Cache Settings for static files ONLY.
# Preset to a 1 minute internal cache time so file changes on static files that don't use
# cache busting techniques are visible after 1 minute.
# To increase, simply adjust the value for "proxy_cache_valid"
# Respects Expires, Cache-Control & Vary headers already set in default.conf
# for client-side caching.

proxy_cache                 engintron_static;
proxy_cache_key             "$request_method$scheme$host$request_uri";
proxy_cache_lock            on;
proxy_cache_min_uses        1;
proxy_cache_revalidate      on;
proxy_cache_use_stale       error timeout invalid_header updating http_500 http_502 http_503 http_504; # Additional options: http_403 http_404
proxy_cache_valid           200 301 302 1m; # Covers 200, 301 & 302 responses, caching time set to 1 minute
proxy_ignore_headers        Expires Cache-Control Set-Cookie Vary;
proxy_hide_header           Expires;
proxy_hide_header           Set-Cookie;
proxy_hide_header           Cache-Control;
proxy_hide_header           Vary;
proxy_set_header            Cookie "";
```

Save both files and restart Apache/Nginx. Test.

**Comment by johnknock** [comment]
Thank you.

I have made the changes you asked.  I have removed all temp cache.  I have restarted nginx and apache (from with Engintron's WHM's backend) but I'm still seeing changes to any HTML instantly - there is no caching.

Thanks.

**Comment by johnknock** [comment]
Just to add, I'm testing this by changing the HTML using the theme's options (Wordpress, developed for me).  Currently this is just placing the picture descriptions above or below the image - this is what is happening instantly for me.  Thought I should mention that in case I'm not doing what you expect of me in regards to testing.

**Comment by johnknock** [comment]
Looks like I am now getting a HIT on the images though :)  The cache for the images expires in a minute or so - is that correct?

Hope all of this info helps you to help me.  Let me know if you need further info on how best to proceed with engintron and my setup

**Comment by fevangelou** [comment]
I guess it's because the session cookie is gone for static files. But I still see the "Pragma: no-cache" header in both html and static content. Do you perhaps have any other service or appliance after Nginx?

**Comment by johnknock** [comment]
Hmm, not that I know of.  Was standard Apache before Engintron.

I'll look everything I can think of over now, but I'm no sysop so limited I'm afraid as to my searching.

**Comment by fevangelou** [comment]
Open up port 8080 (Apache) in your firewall (I guess you have CSF or something similar) so I can inspect Apache's headers too.

**Comment by johnknock** [comment]
Ok, can you try that please?

**Comment by fevangelou** [comment]
Can't access http://phonesbros.com:8080/

**Comment by johnknock** [comment]
Ahhh, this will be to do with my other problem I was having: https://github.com/engintron/engintron/issues/251

Maybe the remote reverse proxy is causing this (pragma: no_cache)?  I'm unsure how to check that..

With this in mind, is there a work around to achieve what I want in regards to whole page/items caching?

**Comment by johnknock** [comment]
Would me emailing you my main server IP help you eliminate whether it is coming from the source?

**Comment by fevangelou** [comment]
Not really.

**Comment by fevangelou** [comment]
Last solution: Setup a new cPanel server and test. Just get the stock installation, configure PHP, Apache etc. via EasyApache and install Engintron.

**Comment by johnknock** [comment]
I will do this soon.  Interested to see if I can get the whole page to cache for my chosen timeframe rather than just elements of the page.

Will let you know.

**Comment by fevangelou** [comment]
Re-open the issue when you're ready. Closing for now...
