### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by brinsleyparagao** [engintron/engintron#259]
Hello fotis

I thinking... how can some user make a donations to you ?

**Comment by fevangelou** [comment]
Thank you Brinsley. Since others also mentioned this, I'll setup a 
donate button and let you know :)


Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by fevangelou** [comment]
Here it is: https://engintron.com/?upd

**Comment by brinsleyparagao** [comment]
@fevangelou check your paypal :+1:

**Comment by fevangelou** [comment]
:+1:
