### ISSUE TITLE
Engintron Compatible with xVarnish

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#261]
Please can you let me know that does Engintron Compatible with xVarnish ?

About xVarnish: https://repo.xvarnish.com/

**Comment by fevangelou** [comment]
You don't need Varnish. Varnish is for accelerating one or two sites per server. Beyond that it's difficult to maintain practically. And unless Varnish is really, really well configured you probably won't benefit at all as either caching won't work or you'll get user session issues.
