### ISSUE TITLE
Facebook authentication 

### ISSUE THREAD

**Issue by laurfx** [engintron/engintron#262]
Hello,

I have a problem with a facebook authentification script, the redirection url which is accesed when the login with facebook it's finish, it doesn't load, and give me 504 Gateway Time-out, the url is: 

site.com/facebookAuth?code=AQBDMqk8wkU2K1Efpognksn3HaDJyGYfphwqmSPoL6Te6c-_F9FxQSfKg02E15qXPG-X5RZlXKu3cRUjxqvmOsT1_WfYyOrae5YyYNzofHb33oWTFHVxf_rdOzFcuog7zi7vg9vIAL5Dg-peN_r4y4VNiToWTZoHNVRhT3SMwijGev7Xt4ha2ahYCGTyjuNhjOXhGX58y2O-ohikSG9Dt5VOM5enbJHb2kWdPHvdcndF0oTugX0rgEhgOVDMWlKmqt7K8Kb1K12Eis9mYD1YWA-R1MqovQ7SzK8AiDmqXovRgULdxgfgewxachtb107dsCs87Te2Y0h7g1tVTSvlrITh&state=ccx92a456524ce20654bbf604271cdxb#_=_

This don't works, the same problem.
if ($host ~ "xxxx.com") {
    set $PROXY_DOMAIN_OR_IP  "IP";
}

It can be from 	large_client_header_buffers ? Any ideas?

Thank you.

**Comment by fevangelou** [comment]
Increase the 3 buffer timeout values in proxy_params_common and restart Apache/Nginx.

**Comment by laurfx** [comment]
Hello,

I did this already amd doesn"'t fix it. Is there any way to disable engintron for a site? 

Thanks

**Comment by laurfx** [comment]
Hello,

I have this error : 2016/09/08 11:57:39 [error] 30601#30601: *62102 upstream timed out (110: Connection timed out) while reading response header from upstream, client: MYIP, server: localhost, request: "GET /facebookAuth?code=AQAqvW7n09uHbGzO6n5qUjXLvcvT5I0_kXCu_NYNVSWJJimpIqdky1V17gCFqzr8H3IMbAu5I5W8Oh--0ceFK_dlOZVFaTM3m-ee6IeI-6gpqrigBI_r624PMrNgUb47gnUeaoGCny0yaOe216OxdZGTGGXIi12ARjNsN2-g0Q7h1LQnv_diMdptpdlgL488nlKUoUOJus8L4xgi01SJVmQavPqt6t6u7YFNSwYnS50Y-jq15CpV5xzfkuw29zrgKxCI0ZGHXbwzlfeRg12-Vt1c7AjVDYLtwiasW4vxsv3oqvq3jmUqTimrsp2qVK38e8J1loBvxoMfJXivIiYAF80A&state=7989b99125f15d4f3ca798dd0583f882 HTTP/1.1", upstream: "http://SERVER-IP:8080/facebookAuth?code=AQAqvW7n09uHbGzO6n5qUjXLvcvT5I0_kXCu_NYNVSWJJimpIqdky1V17gCFqzr8H3IMbAu5I5W8Oh--0ceFK_dlOZVFaTM3m-ee6IeI-6gpqrigBI_r624PMrNgUb47gnUeaoGCny0yaOe216OxdZGTGGXIi12ARjNsN2-g0Q7h1LQnv_diMdptpdlgL488nlKUoUOJus8L4xgi01SJVmQavPqt6t6u7YFNSwYnS50Y-jq15CpV5xzfkuw29zrgKxCI0ZWGvbwzlfeRg12-Vt1c7AjVDYLtwiasW4Zc9v3oqvq3jmUqTimrsp2qVK38e8J1loBvxoMfJXivIiYAF80A&state=7989b99125f15d4f3ca798dd0583f882", host: "www.mysite.com", referrer: "http://www.mysite.com/login"


Anyway, the problem persist when I disable Engintron so i close it.

Thank you.

**Comment by fevangelou** [comment]
Did you manage to spot the problem?

**Comment by laurfx** [comment]
Hello,

Yes, the problem was with my PHP script, i am sorry.

I have another problem, after a while the Apache dies but don't kill the procces and i get 502 Bad Gateway, i will look at the logs and maybe i will post a issue if i don't found anything.

Thank you very much.

**Comment by fevangelou** [comment]
Increase the timeout values in proxy_params_common so Nginx waits longer for Apache to respond. Again some PHP script is probably taking longer to execute. Additionally, have a look at the optimization guides I provide, especially for Apache & PHP (I hope you have at least FastCGI for PHP).

**Comment by laurfx** [comment]
I increased the timeout, it wasn't that the problem, it was from my php script not server.

The problem what i have with the server sometimes it's get 502 on all websites and i must restart apache + nginx to work again. I will look on logs when i have the time and when will happen again and i will post if i see something that i can't solve and is related with Engintron.

And yes, i have FastCGI.

Thank you.
