### ISSUE TITLE
Engintron/asl issue

### ISSUE THREAD

**Issue by copernic2006** [engintron/engintron#264]
Hello
Looking for a cache solution, I discovered Engintron.
Using it is intuitive and pleasant, but one worries after run  Easyapache3.
Indeed, I noticed:
1. Real IP is no longer detected
2. ModSecurity is not up, for information, I use ASL (complete solution, not just the rules, https://atomicorp.com/features/)

To remedy this, I have to do:
asl -s -f (scan and fix)
reinstall Engintron (from the interface)

For information:
Centos 6.8
Apache 2.2

Can you please help me fix the problem permanently?

Regards

**Comment by brinsleyparagao** [comment]
Hello, apache 2.2 have issue PERM in remote IP, a nice tip is upgrade to apache 2.4

in apache 2.4 (EA3 or EA4) remote IP work fine and perfect

**Comment by fevangelou** [comment]
Try re-installing for starters. Engintron will install an Apache module (it doesn't matter whether you use Apache 2.2 or 2.4) to pass the visitor IP (RealIP) from Nginx to Apache. The installation of that module sometimes fail when installing Engintron. So re-install and if this is not fixed, let me know.

**Comment by copernic2006** [comment]
Hello,
As suggested by brinsleyparagao, I switched to apache 2.4.
Engintron works perfectly including the detection of the real IP address (remote IP) but by executing EA3, is the IP address of the server that is displayed (of course, reinstalling Engintron solve the problem).
Honestly, I think this is due to the interaction with ASL, I encountered the same problem by testing xvarnish.
