### ISSUE TITLE
Cache 

### ISSUE THREAD

**Issue by rapidcloubr** [engintron/engintron#265]
CSS file is not updated

Hello,

My clients are reporting that after installing Engintron on the server, the CSS files uploaded to the FTP are not atulizados, something like infinite cache.

How to solve this issue? Is there any way to turn off certain domain Nginx?

**Comment by brinsleyparagao** [comment]
Try comment [ # ] the JS and CSS engintron cache...
late this purge cache and restart nginx & apache

**Comment by rapidcloubr** [comment]
# Enable browser cache for CSS / JS (TTL is 30 days)
	location ~* \.(?:css|js)$ {
		include proxy_params_common;
		include proxy_params_static;
		expires 30d;
		add_header Pragma "public";
		add_header Cache-Control "public";
		add_header Vary "Accept-Encoding";
		access_log off;
	}

Are these adjustments above?

**Comment by fevangelou** [comment]
Either use cache-busting (the right way, but hard if you don't control the sites affected - https://css-tricks.com/strategies-for-cache-busting-css/) or simply lower Nginx's internal 1m cache to say 3s by changing line 24 in proxy_params_static from:
`proxy_cache_valid           200 301 302 1m; # Covers 200, 301 & 302 responses, caching time set to 1 minute`

to:
`proxy_cache_valid           200 301 302 3s; # Covers 200, 301 & 302 responses, caching time set to 1 minute`

That should fix your issues.

**Comment by wtleaver** [comment]
I'm having the same sort of issue with caching of CSS files. They are being cached server-side for far longer than 1 minute. I haven't changed any of the settings. Any ideas what could cause this? On the client side I'm using Safari with caches disabled. I made a change to a CSS file 30 minutes ago while troubleshooting this for a hosting client, and the change still hasn't chown up in the browser. Using Engintron 1.7.2.

**Comment by gfxdesigner** [comment]
If you use the ?nocache query at the end of the url, does it show the most recent version?

**Comment by wtleaver** [comment]
I can add any sort of modifier to the end of the URL and see the new file. I simply can't see the changes using the URL directly to the css file. Asking a few thousand hosting clients to switch to cache busting techniques isn't going to cut it though. If the cache would properly expire after a minute there wouldn't be an issue.

**Comment by wtleaver** [comment]
Okay, this is weird. The default cache time in proxy_params_static is:

proxy_cache_valid           200 301 302 1m; # Covers 200, 301 & 302 responses, caching time set to 1 minute

If I change it from 1m to 60s:

proxy_cache_valid           200 301 302 60s; # Covers 200, 301 & 302 responses, caching time set to 1 minute

Everything works, and as soon as I make a change to a css file I can see it in the browser, even before the minute has expired. Set it back to 1m and I can't see updates again.

What's up with that? I'm no nginx expert, and just started using engintron. Does 1m actually mean 1 minute? Does 60s equal 60 seconds? Why would one work and not the other?

**Comment by rapidcloubr** [comment]
It's really weird.

I had to stop using this nginx on my servers.

I could not solve the problem of cache.

I have many dedicated servers with over 1,000 hosted accounts, I wanted to be able to use this nginx.

**Comment by wtleaver** [comment]
Yep it's weird. I thought I had a workaround but it stopped working. I have no clue what is causing the issue but it unfortunately leaves Engintron unusable. I'm bummed because other than this it's a fantastic plugin. Maybe it's a nginx bug that will get fixed in a new version.

**Comment by rapidcloubr** [comment]
I stopped using it. I am waiting for the solution of this problem in order to install on all my servers.

**Comment by fevangelou** [comment]
Could be an Nginx bug specific to these options. In any case, stick to seconds if it works for you, it's still valid.

**Comment by wtleaver** [comment]
Seconds don't actually work either. Thought they did, but no. 

I'd love to donate to help a couple things figured out like this and php rate limiting. Right now because of the cache probl I can't use it.

**Comment by fevangelou** [comment]
I need to have access to your server to troubleshoot. It's difficult otherwise. I can only perform such a task as a paid gig though. If you're interested you can email me at engintron [at] gmail [dot] com.
