### ISSUE TITLE
IPB w/ w/o cloudflare not working correctly

### ISSUE THREAD

**Issue by slimbit90** [engintron/engintron#266]
So the issue arises even with the new version and the conf files for dynamic changes. I set to say 60s and users are still switched to other users during login (regular user gets switched to site admin) etc. I had cloudflare on removed cloudflare and it still creates this problem. Or doesn't allow a shoutbox script to work correctly. 

IPB seems to be the only issue I have run into so far, what does everyone recommend for settings for IPB. I'd love to use it because when it works in our Cloudlinux environment it is amazingly fast and boost's performance for this medium sized community and other users on the server.

**Comment by fevangelou** [comment]
CloudFlare has no effect here. To resolve the issue, Nginx has to know where your users login. You see, the cookie bypass setting is probably not enough with a 60s cache (as in your cache). If you have specific entry points for users, you can use these in Nginx's config to turn off caching. See joomlaworks.net as an example and try logging in from any place - you are always redirected to the same login page before continuing in the site as a user. If you do something similar, Nginx will know when a user tries to login. After that point the cookie will be set correctly and Nginx will switch off its caching for the logged in user.

It will also help me if you tell me which IPB version you're using and it would of course greatly help if you can provide me with the URL of the actual site so I can check cookies set there.

**Comment by fevangelou** [comment]
(sorry for the late reply but you caught me on summer vacation)
