### ISSUE TITLE
LogFormat Changes

### ISSUE THREAD

**Issue by Leykis** [engintron/engintron#271]
Hi,

The LogFormat changes that Engintron is making in the Apache configuration upon installation require more than just running the distiller script, which is all the Engintron installer is doing : 

```
    echo "=== Distill changes in Apache's configuration and restart Apache ==="
    /usr/local/cpanel/bin/apache_conf_distiller --update
    /scripts/rebuildhttpdconf
    /scripts/restartsrv httpd
```

As mentioned in a previous thread #216, according to cPanel you have to use a vhost.local configuration file : https://documentation.cpanel.net/display/EA/Custom+Templates

Currently every time the Apache configuration is rebuilt, the changes that Engintron requires and makes during the installation are being reverted.

Do you have any plans to correct this?

**Comment by fevangelou** [comment]
I can add a simple switch (link) to simply launch the distill process. How's that sound?

**Comment by Leykis** [comment]
Sorry, I'm not sure you understand. Running the distill process is not storing the changes, which means as soon as the httpd.conf is rebuilt, it is reverted. 

"The Apache configuration distiller script does not guarantee that cPanel & WHM will not overwrite your direct modifications to your httpd.conf file."

Due to this, the changes have to be made in a vhost.local config.

Am I the only one experiencing this issue?

**Comment by fevangelou** [comment]
I think I'm gonna go with this: https://documentation.cpanel.net/display/EA/Advanced+Apache+Configuration#AdvancedApacheConfiguration-ModifytheApacheconfigurationwithincludefilesviaCLI

Seems a cleaner option overall.

**Comment by fevangelou** [comment]
Sorry, forget what I wrote above.

I think it's best to update any changes needed for httpd.conf with a simple switch in Engintron's WHM app. Faster than re-installing Engintron just to update httpd.conf only.
