### ISSUE TITLE
Alternative address.

### ISSUE THREAD

**Issue by marcelodelta** [engintron/engintron#273]
Problem accessing alternative address using IP.

http://IP#/~username
https://IP#/~username

**Comment by JorgeMarcelino-HS** [comment]
Message: Not supported

I have the same problem.

**Comment by fevangelou** [comment]
I believe this is now a cPanel change. @marcelodelta When you call the second address using HTTPS, you're not even calling Nginx. So either you've chosen the setting in cPanel that prevents calling a website by its username or your server is not built to allow that (e.g. you can't do this when PHP runs as a FastCGI module)...

**Comment by fastwebhost** [comment]
If you are using the shared IP for accessing temp URL. Might be your host as disabled the temp URL access

**Comment by fevangelou** [comment]
Closed due to inactivity.
