### ISSUE TITLE
Dedicated IP in domain does not work

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#275]
Hello, I'm currently testing Engintron, I have added a dedicated IP for a domain, but is not working. When I try to access, go to the "default cgi" page. Do not open the website.

some configuration is required? This IP will be used for all resell hosting.

**Comment by Teranode** [comment]
when i do it it takes me to the nginx page

**Comment by fevangelou** [comment]
Are you calling the site using the IP directly (and not a domain name)? If so, it won't work. The domain has to properly propagate (in DNS) to the actual IP.

**Comment by JorgeMarcelino-HS** [comment]
Dear, I know that! The problem is that websites with dedicated IPs are not working, you know?

example: [http://uoool.layerserver.com/](http://uoool.layerserver.com/) 

Already propagated and the dedicated IP, but goes to the default cgi page.

**Comment by fevangelou** [comment]
If you use CSF or any other firewall, can you please open up port 8080 so I can troubleshoot?

**Comment by JorgeMarcelino-HS** [comment]
The port 8080 opened at this time.

**Comment by fevangelou** [comment]
Add an index.html file - at the moment http://uoool.layerserver.com:8080/ this returns directory listing. This is not a valid web file per se.

**Comment by JorgeMarcelino-HS** [comment]
Hello, I have added one index.html

http://uoool.layerserver.com/index.html

How can I access this? without placing the port?

**Comment by fevangelou** [comment]
Dude, it's important to use a proper HTML file, not a "test" string. Do that, restart Apache/Nginx once to clear any caches and you'll see your site.

It's really simple.

**Comment by JorgeMarcelino-HS** [comment]
I have done this in several tests just putting the port 8080, working.

I keep seeing the page "default cgi", even cleaning the cache

**Comment by fevangelou** [comment]
Place this inside index.html:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Testing</title>
  </head>
  <body>
    Testing
  </body>
</html>
```

Now save the file and restart Apache/Nginx. Check http://uoool.layerserver.com/ using a new private window in your browser as your main browser window may have cached the redirect to the .cgi page from cPanel.

BTW< do you have ANY other site on this server?

**Comment by JorgeMarcelino-HS** [comment]
Restarting Apache...
Stopping httpd: [  OK  ]
Starting httpd: AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/conf/httpd.conf:7780
[  OK  ]

Restarting Nginx...
Stopping nginx: [  OK  ]
Starting nginx: [  OK  ]

Yes, several sites but using the IP main

**Comment by fevangelou** [comment]
I still see the "test" string and no HTML code... http://uoool.layerserver.com:8080/?t=1

Perform what I said and we'll discuss later.

**Comment by JorgeMarcelino-HS** [comment]
I have done it! see: [http://uoool.layerserver.com:8080/?t=1](http://uoool.layerserver.com:8080/?t=1)

Restarting Apache...
Stopping httpd: [ OK ]
Starting httpd: AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/conf/httpd.conf:7780
[ OK ]

Restarting Nginx...
Stopping nginx: [ OK ]
Starting nginx: [ OK ]

**Comment by fevangelou** [comment]
Something else is messing up with the redirect. An .htaccess rule perhaps?

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by JorgeMarcelino-HS** [comment]
No there .htaccess.

see: Starting httpd: AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/conf/httpd.conf:7780

That does not mean anything?

**Comment by fevangelou** [comment]
No, this message does not affect anything. Still. There is something setup for this domain that causes this issue. In any case, if Nginx didn't work, you wouldn't even see the redirect page. Consult your hosting company for more as this is probably beyond the scope of the support I can provide for Engintron.

**Comment by JorgeMarcelino-HS** [comment]
Hello, I'm using EA4, you must enable a module?

**Comment by fevangelou** [comment]
Ask your hosting company.

**Comment by JorgeMarcelino-HS** [comment]
Hello, I found the problem!

set $PROXY_DOMAIN_OR_IP "108.61.48.99";

I have done this so that the cloudflare works, but dedicated IP does not work because of it.
I need to do for the dedicated IP?

**Comment by fevangelou** [comment]
In custom_rules add this:

```
if ($host ~ "uoool.layerserver.com") {
    set $PROXY_DOMAIN_OR_IP "108.61.48.99";
}
```

Restart Apache/Nginx.

In the future READ THE FREAKING WIKI please.

**Comment by JorgeMarcelino-HS** [comment]
I understand that, but I will use this dedicated IP for more websites within a resale, how do?

**Comment by Teranode** [comment]
I use dedicated IPs but its like when i enable engintron it shows the nginx landing page, but every other page works fine, If i put index.php directly for the home page it will show my regular page and if not it will shows the nginx landing page. (ive also left it alone for a while and deleted cache to see if it was a dns/cache issue and it still persisted)

**Comment by fevangelou** [comment]
@Teranode You need to verify whether something redirects the / request (.htaccess file perhaps).

**Comment by JorgeMarcelino-HS** [comment]
@fevangelou I will use this dedicated IP for more websites within a resale, how do?

**Comment by dannymichel** [comment]
Yeah, if @JorgeMarcelino-HS is saying what i think he is, then this seems flawed. We can't possibly keep track of everyone's domains for CloudFlare.
No way to wildcard this?
