### ISSUE TITLE
Does not support CentOS 7

### ISSUE THREAD

**Issue by tdilhan** [engintron/engintron#280]
service nginx restart
Redirecting to /bin/systemctl restart  nginx.service
Failed to restart nginx.service: Unit nginx.service failed to load: No such file or directory.

**Comment by fevangelou** [comment]
Of course it supports CentOS. If you didn't have another Nginx-for-cPanel plugin already installedm re-install Engintron and check again. If that doesn't work simply reboot your server.

**Comment by fevangelou** [comment]
Closed as inactive.
