### ISSUE TITLE
Connection refused /Timeout errors

### ISSUE THREAD

**Issue by 1uhost** [engintron/engintron#282]
Just installed engintron on cpanel 58 with cloudlinux.  Getting lots of errors in /var/log/nginx/error.log  Example timeout:
2016/09/26 06:36:36 [error] 8061#8061: *13598 connect() failed 2016/09/26 06:36:18 [error] 8063#8063: *13537 connect() failed (110: Connection timed out) while connecting to upstream, client: 208.94.147.100, server: localhost, request: "GET /ping.html HTTP/1.1", upstream: "http://64.22.67.130:8080/ping.html", host: "domain.com"
We tried increasing proxy_read_timeout to 300; in proxy_params_common but error persists.

Example refused
2016/09/26 06:36:37 [error] 8060#8060: *13711 connect() failed (111: Connection refused) while connecting to upstream, client: 180.76.15.13, server: localhost, request: "GET /robots.txt HTTP/1.1", upstream: "http://107.189.160.195:8080/robots.txt", host: "mail.domain.com"

Would appreciate any suggestions.

**Comment by fevangelou** [comment]
See this please: https://github.com/engintron/engintron/wiki/Fix-%22110:-Connection-timed-out%22-errors-appearing-in-Nginx-logs
