### ISSUE TITLE
Not so busy site, first load slow...

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#283]
When I enable Engintron, the first time I visit a site it takes quite long before the site is shown... the second time it goes fast, but when I wait an hour it's slow again (unless just crawled by Google orso).

How come?

The only thing I have changed is the resolver:

	resolver						8.8.8.8 8.8.4.4;

In the nginx config... could that be the culprit?

**Comment by fevangelou** [comment]
Changed to what? Cause this is one freakin' important option.

**Comment by Friends4U** [comment]
I enabled it... when it's disabled Engintron does nothing and I keep getting BAD gateway.
But with it enabled it works but with the problem stated earlier...

I have disabled Engintron now :(

**Comment by fevangelou** [comment]
You should leave that option on otherwise Engintron's Nginx will not work.

**Comment by Friends4U** [comment]
The issue is not closed... Again when that option is enabled engintron works but it's slow on first load (every site).

**Comment by Friends4U** [comment]
I really don't understand why you close this issue as it's not solved...

**Comment by Friends4U** [comment]
Ok, I re-submitted the question...
