### ISSUE TITLE
Symfony stopped working after replacing nginxcp with Engintron

### ISSUE THREAD

**Issue by bramanis** [engintron/engintron#285]
Any ideas, what should I include from the Symfony recommended Nginx configuration to yours?

http://symfony.com/doc/current/setup/web_server_configuration.html#nginx

One of the URLs to test with: http://snapp.ie/manutd

Friendly URLs nor PHP files are not parsed currently.

**Comment by fevangelou** [comment]
You don't need to include any Nginx configuration. Nginx does not serve web content directly but as a reverse caching proxy. Stick to Apache rules and Nginx will do its magic automatically.

**Comment by bramanis** [comment]
Why does it stop working then when I install Engintron?

**Comment by fevangelou** [comment]
Uninstall any other Nginx plugins you might have had already. See here: https://github.com/engintron/engintron/wiki/How-to-uninstall-other-Nginx-plugins-for-cPanel-(before-installing-Engintron)
