### ISSUE TITLE
WooCommerce (WordPress) issue

### ISSUE THREAD

**Issue by copernic2006** [engintron/engintron#286]
Hello,
I just noticed that connecting two users (two different browsers), the shopping cart of each show orders from two customers.
Can you please help me solve this problem?

Regards

**Comment by db306** [comment]
I don't think it has anything to do with enginetron. At least, I don't have that issue.

**Comment by copernic2006** [comment]
Indeed, the situation does not recur, I conducted several tests following your response, I do not understand what happened.
This will allow me to deploy Engintron on production servers (hopefully version 1.8 is imminent).

**Comment by fevangelou** [comment]
There are no WooCommerce exclusions in place in 1.7.2 but that's coming with 1.8.0.

In the meantime, simply edit your "proxy_params_dynamic" config file via Engintron's WHM app and change this line https://github.com/engintron/engintron/blob/master/nginx/proxy_params_dynamic#L17 to this:
```
if ($http_cookie ~* "joomla_[a-zA-Z0-9_]+|userID|wordpress_[a-zA-Z0-9_]+|wp-postpass|comment_author_[a-zA-Z0-9_]+|woocommerce_[a-zA-Z0-9_]+|wp_woocommerce_[a-zA-Z0-9_]+") {
```

**Comment by copernic2006** [comment]
Configuration update (proxy_params_dynamic).
Thank you very much.

**Comment by fevangelou** [comment]
Awesome :)
