### ISSUE TITLE
Build for EasyApache 4

### ISSUE THREAD

**Issue by ImLuke954** [engintron/engintron#287]
Hi, can you add the JSON file for the Easy apache build. In the wiki you have uploaded the build for EasyApache 3 which doesn't work with EasyApache4. 
 https://github.com/engintron/engintron/wiki/Beyond-Engintron:-cPanel-WHM-initial-optimal-setup

**Comment by ytlevine** [comment]
Having the same issue, the previous build worked nicely, but I've been holding off on moving to EA4 until this is updated...
Thanks!

**Comment by Leykis** [comment]
I am using the CloudLinux + ZendGuard build on EA4 without any issues, apart from Awstats not working.

**Comment by fevangelou** [comment]
@ImLuke954 It's on my todo list after I release v1.8.0. In the meantime, since cPanel v60 is now available, just make sure PHP5-FPM is what you use to serve content and then follow the optimization guides for Apache, MySQL et al at the Engintron Wiki.
