### ISSUE TITLE
errors in error log every 15 seconds

### ISSUE THREAD

**Issue by revcomllc** [engintron/engintron#288]
Every 15 seconds we get this error in the error log:
/var/log/nginx/error.log

2016/10/05 19:32:15 [error] 914385#914385: *50805 localhost could not be resolved (3: Host not found), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"

**Comment by jcatello** [comment]
This sounds like an issue with your server, not nginx.

Make sure localhost is set in /etc/hosts

127.0.0.1               localhost

**Comment by revcomllc** [comment]
Yes we do have it set. It is set to:


127.0.0.1		localhost.localdomain localhost

**Comment by fevangelou** [comment]
Did you restart both Apache/Nginx after the change?

**Comment by revcomllc** [comment]
Yes we did fevangelou. Several times

**Comment by jcatello** [comment]
Can you actually ping it?

**Comment by revcomllc** [comment]
yes we can ping it

**Comment by sterlingken** [comment]
@revcomllc were you able to figure this out? I just installed and am seeing the same errors being logged. As far as I can tell everything is working properly - all sites are accessible.

**Comment by revcomllc** [comment]
@sterlingken no we have not. Still seeing same errors

**Comment by fevangelou** [comment]
Solution here: https://github.com/engintron/engintron/wiki/Fix-%22localhost-could-not-be-resolved%22-entries-in-your-Nginx-log-files
