### ISSUE TITLE
Caching the cPanel "sorry - defaultwebpage.cgi" website instead of the real website. Engintron 1.7.2, EA4, cPanel 58

### ISSUE THREAD

**Issue by ciscospirit** [engintron/engintron#289]
Hello,

we found out a problem today with the caching plugin in version 1.7.2, cPanel 58 and EA4.

If you visit the site "http://www.xxx123.at" and refresh the site several times, suddenly you will be redirected to "http://www.xxx123.at/cgi-sys/defaultwebpage.cgi".
The website is a static website with just a picturebanner on it. so no dynamic content.

Some times it is the global sorry website and sometimes it is the sorry website of the domain (you see another mail contact adress there)

We checked several log files but can't find any advice why this happens.

The access works until Engintron is creating the caching files.
If Engintron creates the caching files and you refresh the site again, you get redirected to the sorry defaultwebpage.

`
/tmp/engintron_dynamic/5/37/148c61608e27e55bab24af30a56ba375:KEY: GEThttpwww.xxx123.at/cgi-sys/defaultwebpage.cgi
`
`
/tmp/engintron_dynamic/2/6d/9607a591df18120469a88a97e35766d2:<html><head><META HTTP-EQUIV="refresh" CONTENT="0;URL=/cgi-sys/defaultwebpage.cgi"></head><body></body></html>
`

any idea what could be the problem with that and how i can solve it?
it is also possible to exclude a website?

**Comment by ciscospirit** [comment]
We found out the problem!

This issue with the default Apache page seemingly randomly displaying when visiting http://xxx123.at was caused by there being 2 root httpd processes running:

=====

[21:04:14 s11 root@7770767 ~]cPs# ps aux | grep [h]ttpd | grep root
root      701844  0.0  0.1 204936 19504 ?        Ss   Oct10   0:04 /usr/sbin/httpd -k start
root      874361  0.0  0.1 204700 18840 ?        Ss   Oct02   0:25 /usr/sbin/httpd -k graceful

=====

I manually stopped the Apache service and killed the additional httpd process by running the following commands:

/scripts/restartsrv_httpd --stop
kill 874361

I then started the Apache service back up by running the following command:

/scripts/restartsrv_httpd --start

I'm no longer able to reproduce the default Apache page when visiting http://xxx123.at. I refreshed the site over 15 times and not once did the default Apache page display again. You may need to clear your internet browser's cache if you're still seeing the default Apache page when visiting that site.

**Comment by fevangelou** [comment]
Thanks for sharing. Weird indeed.
