### ISSUE TITLE
Want NGINX to reference WHM's DNS versus public NS records.

### ISSUE THREAD

**Issue by gfxdesigner** [engintron/engintron#292]
Hello, 

When testing a website on my server, where the domain already exists publicly on another server, I just set my local workstation's hosts file to the IP of my server to be able to access it. 

However, I noticed that NGINX attempts to reference the publicly accessible domain and then returns with a "502 Bad Gateway". In other words, it's ignoring the DNS entries in WHM and looking up the real public NS records for the location. 

Here is an example from my Engintron error log (with masked IPs and domain): 
2016/10/12 11:34:00 [error] 15425#15425: *152 connect() failed (110: Connection timed out) while connecting to upstream, client: xx.xx.xx.xx, server: localhost, request: "GET / HTTP/1.1", upstream: "http://xx.xx.xx.xx:8080/", host: "example.com" 

How do I force it to reference what WHM's DNS is reporting?

**Comment by fevangelou** [comment]
Update accordingly here: https://github.com/engintron/engintron/blob/master/nginx/nginx.conf#L44

**Comment by gfxdesigner** [comment]
Thank you so much for the clarification! That worked.
