### ISSUE TITLE
PageSpeed Module

### ISSUE THREAD

**Issue by msivakr** [engintron/engintron#295]
Could you please add the ngx_pagespeed module?

**Comment by SashRaven** [comment]
Engintron does NOT install it's own nginx package. It's installed from official nginx repo.

**Comment by fevangelou** [comment]
Once ngx_pagespeed becomes a "dynamic" module, it will be very easy to include it as well. This depends on the devs of that module though as to when they'll adapt the codebase to make the module "dynamic".

Dynamic modules were introduced early 2016: https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/
