### ISSUE TITLE
500 internal server errors

### ISSUE THREAD

**Issue by fastwebhost** [engintron/engintron#298]
Hi,

We are using Cloudlinux LVE Manager in our server, recently we enabled engintron on our server. All was fine for first 2 weeks later on we started facing "500 internal server errors" on all websites. we increased the resource limits on site and then website was working fine. And again after 4-5 days we are facing the same issues now on all websites "500 internal server errors".

Your suggestions are important to us.

**Comment by Leykis** [comment]
What are you seeing in the error logs when this occurs? Apache error log, NGINX error log, PHP error log, etc...

**Comment by fastwebhost** [comment]
Hi,

Below are the logs for NGINX 
===
2016/10/22 05:24:00 [error] 646407#646407: *2705267 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 46.4.107.49, server: localhost, request: "GET /wp-includes/SimplePie/Cache/dirs3.php HTTP/1.1", upstream: "http://131.153.37.4:8080/wp-includes/SimplePie/Cache/dirs3.php", host: "m.underdogwealthmanagement.com"
2016/10/22 10:54:40 [error] 646423#646423: *3335729 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 131.153.37.4, server: localhost, request: "GET /wp-admin/admi
ajax.php?action=wordfence_doScan&isFork=0&cronKey=66cd91982134d6a361566741 HTTP/1.1", upstream: "http://131.153.37.4:8080/wp-admin/admin-ajax.php?action=wordfence_doScan&isFork=0&cronKey=66cd91982134d6a361566741", host: "www.billpottle.com"
2016/10/22 12:55:08 [error] 646425#646425: *3560595 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 181.232.120.228, server: localhost, request: "POST /batch?id=4&op=do HTTP/1.1", upstream: "http://131.153.37.4:8080/batch?id=4&op=do", host: "www.nautylustec.com", referrer: "http://www.nautylustec.com/batch?op=start&id=4"
===
Apache logs are below.
===
[Wed Oct 19 04:00:47.709424 2016] [:error] [pid 822301] (12)Cannot allocate memory: [client 131.153.37.4:47809] 
====

**Comment by GeorgeD12** [comment]
Are you using CF on that domain? if so please make sure you enable CF on Engintron, more info on https://github.com/engintron/engintron/wiki/Engintron-&-the-%22Custom-Rules%22-file-(for-Nginx)

**Comment by fastwebhost** [comment]
Hi,

No the domain is not using CF and we have enabled  CF on Engintron the domains which are using CF in this server.

**Comment by fastwebhost** [comment]
Hi,

No the domain is not using CF and we have enabled CF on Engintron for the domains which are using CF in this server.

**Comment by fevangelou** [comment]
As the logs indicate, this form POST process simply takes too long to finish and Nginx cuts it off. Simply bump up the:
```
proxy_read_timeout            180s;
proxy_send_timeout            180s;
```
...inside "proxy_params_common". Change from 180s to 360s (for 3 mins) which should be more than enough.

**Comment by brixly** [comment]
Hi there,

We are getting this issue still.

Our servers run fine for maybe 24 hours at a time. Following that though our monitoring tools are throwing intermittent 500 errors throughout all sites.

We just donated in the hope to get some one-on-one assistance.

We have tried increasing the recommended settings but still get it after a short while.

Really need some help please were losing customers almost daily for the same issue
