### ISSUE TITLE
CSF Port Block

### ISSUE THREAD

**Issue by barchard** [engintron/engintron#299]
It looks like the port isn't opened in CSF

```
Time: Sat Oct 22 00:28:15 2016 +0000 
UID: 985 (nginx) 
Hits: 11 

Sample of port hits: 
Oct 22 00:28:03 mayo kernel: Firewall: *TCP6OUT Blocked* IN= OUT=eth0 SRC=ipv6 DST=ipv6 LEN=80 TC=0 HOPLIMIT=64 FLOWLBL=0 PROTO=TCP SPT=46900 DPT=8080 WINDOW=28800 RES=0x00 SYN URGP=0 UID=985 GID=980 
```

**Comment by Leykis** [comment]
Port 8080 isn't needed unless you are planning on accessing it directly..

If so, just add it to /etc/csf/csf.conf: 

```
# Allow incoming TCP ports
TCP_IN = "20,21,22,25,26,53,80,8080,110,143,443,465,587,993,995,2077,2078,2082,2083,2086,2087,2095,2096"

# Allow outgoing TCP ports
TCP_OUT = "20,21,22,25,37,43,53,80,8080,110,113,443,465,587,873,2087,2089,2703"
```

```
# Allow incoming IPv6 TCP ports
TCP6_IN = "20,21,22,25,26,53,80,8080,110,143,443,465,587,993,995,2077,2078,2082,2083,2086,2087,2095,2096"

# Allow outgoing IPv6 TCP ports
TCP6_OUT = "20,21,22,25,37,43,53,80,8080,110,113,443,465,587,873,2087,2089,2703"
```

**Comment by sshcli** [comment]
> just add it to /etc/csf/csf.conf:

This solution works. 
I have tested this on my servers, and I'm not receiving more alert emails about this.

**My Question:**
Why not added in the following documentation?
https://engintron.com/docs/#/pages/Restrict-access-to-ports-8080-&-8443-used-by-Apache-only-for-Nginx

**Comment by fevangelou** [comment]
Cause that document is different to CSF. If you read the basics of using Engintron, you should understand that in order to access ports 8080 & 8443, you obviously need to add them as exclusions in CSF (if you use it).

**Comment by sshcli** [comment]
So, let me see if understand 
if I have Cpanel + Engintron + CSF installed in my server
is mandatory to allow/deny in/out ports 8080/8443 in CSF?
or is this is something optional that can be skipped without any security risk?

**Comment by fevangelou** [comment]
It's optional. But it's handy if/when a site breaks and you want to check if it's Apache by calling e.g. domain.tld:8080 or https://domain.tld:8443...
