### ISSUE TITLE
Getting Nginx Welcome Message on all homepages

### ISSUE THREAD

**Issue by theret** [engintron/engintron#302]
Hey

Installed Engintron (very easy and smooth!) on my Centos 6 VPS.

Now, all my site's homepages show the 'Welcome to Nginx!" page. Other pages on the sites are working fine. It's only the homepages. I guess it has to do with Nginx reading index.html as the default file for each site. How do I stop that from happening?

Thanks

**Comment by juliowriter** [comment]
Same problem here. Thanks.

**Comment by fevangelou** [comment]
No, that's not the case. Nginx proxies the requests to Apache, so Apache decides whether to show index.html (or index.php) first. Were you both using any other plugin for Nginx previously?

**Comment by juliowriter** [comment]
In my case, was the vhosts configuration path that was wrong. Thanks.

**Comment by fevangelou** [comment]
What vhosts paths? Are you sure you're not talking about some other plugin?

**Comment by juliowriter** [comment]
We had a previous installation of CPanel in another server and migrated the accounts to a new one. The path structure for the vhosts files were /etc/nginx/vhosts not /etc/nginx/conf.d. Engintron was pointing to /etc/nginx/conf.d in the configuration file, I just changed it and everything is working fine now.

**Comment by juliowriter** [comment]
Just figured out that we were using 2 plugins at the same time and that Engintron doesn't need the vhosts files at all. We removed the old plugin and the vhosts files. Everything is working 100%. Congratulations for the plugin. It's awesome.

**Comment by fevangelou** [comment]
Glad you sorted it out :)

**Comment by SwiftThemes** [comment]
Removed the default NGINX html folder at `/usr/share/nginx/html`, all good now.

**Comment by greenleafmedia** [comment]
I moved the default NGINX html folder as well and it fixed it.  Seems pretty hacky though.  Everything works fine with NGINX disabled.  I guess I'll roll with it.  Don't feel good about it though. :)

**Comment by fevangelou** [comment]
@greenleafmedia & @SwiftThemes If you're facing such issues, it's probably because you did not remove any other plugins for Nginx before installing Engintron. It's clearly mentioned in the wiki...

**Comment by greenleafmedia** [comment]
I haven't installed any other Nginx plugins.  It's just an old-ass machine that's had a whole bunch of WHM upgrades (I believe it was 58 back when I spun it up) and manual upgrade from EA3 to EA4 back in the day.

Love the plugin.  I have it on many machines and the new installs work splendidly.  I've just been having random issues on machines that have gone through a bunch of upgrades.

There's no danger to removing the default NGINX html folder, right?

**Comment by ericleonardo** [comment]
@fevangelou I had the same problem after installing SSL with Certbot-Auto (Lets Encrypt) and restarting Apache.

Solved the problem of default Nginx page being shown on homepage by renaming folder **/usr/share/nginx/html/** to **/usr/share/nginx/html-2/**

Despite all seems perfect now, do you think this procedure of renaming html folder can cause any problem to Engintron/Nginx?

**Comment by ericleonardo** [comment]
Well, after I updated Engintron to new version, had to reinstall SSL with Certbot-Auto..
But now my homepage is very slow to start loading.. Other pages are very fast.

**Comment by fevangelou** [comment]
@ericleonardo Why mess with Certbot when cPanel has a way better solution via AutoSSL?

https://documentation.cpanel.net/display/CKB/The+Let%27s+Encrypt+Plugin

**Comment by ericleonardo** [comment]
@fevangelou I was using AutoSSL and really like it.. But it didn't renew my certificate because my cPanel license is expired and have no money buy another license now. Well, it seems I got to fix the slow homepage: deleted the old expired SSL certs and privkey (issued by AutoSSL) on **/home/mydomain/ssl/** and reinstalled the new SSL running Certbot-auto again. Then, renamed **/usr/share/nginx/html/** to **/usr/share/nginx/html-2/** to remove the Nginx default homepage.
It seems the slow homepage was being caused by keeping old and new certificates.. don't know.

All is working perfectly until now (1 hour after).. Hope it keeps working.. Sure I will buy new cPanel license as soon as I have enough money. Engintron is so nice. Can't keep my site without it. Thanks

**Comment by webaholicsteam** [comment]
The recent WHM/cPanel update on 12/13/2018 "76.0.14" appears to have brought this issue back

**Comment by fevangelou** [comment]
@webaholicsteam Open a separate issue please if this still stands...

**Comment by hoomanjavadpoor** [comment]
I have the same issue after installing the Lua module from the OpenResty rep on Nginx 
I tried reinstalling and all method
but I figure that you just need to remove /etc/Nginx/HTML directory

:)

**Comment by fevangelou** [comment]
@hoomanjavadpoor Yeah, well, it's not really part of the stock Nginx setup, right?

**Comment by hoomanjavadpoor** [comment]
@fevangelou 
Yea actually it happens cause I use 3rdparty version of Nginx named OpenResty

**Comment by Chipmank** [comment]
I have the same issue, on fresh cpanel installation on Almalinux 8.3. I've renamed the html folder and that has fixed the issue. 
Could you please provide the proper way to fix the issue? Why is the system opening html page firstly?

**Comment by fevangelou** [comment]
Haven't tested Engintron with any RHEL 8 variant, which includes CentOS 8, Almalinux 8 etc.

**Comment by utechs** [comment]
Same issue here cloudlinux 8  I've renamed the html folder and that has fixed the issue.

**Comment by mofolo** [comment]
The issue was for me, using AWS Security groups, I had to allow Port 8443 and 8080
