### ISSUE TITLE
New install issues with timeout and strange connections to IPv6

### ISSUE THREAD

**Issue by mediumt** [engintron/engintron#305]
Hi, just installed the latest stable release of engintron on cPanel 58.0 (build 34), running 64bit Linode CentOS 7.2.1511 and latest Linode kernel. EasyApache 4 is installed

Server Version: Apache/2.4.23 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 AIX
Server MPM: prefork

The issue that some pages on the main site do not respond for a long time. In the logs, I see connection to IPv6 for a strange reason. Before Engintron, everything was working beautifully, this is logs:

2016/11/06 13:44:58 [error] 16306#16306: *13 upstream timed out (110: Connection timed out) while connecting to upstream, client: my.ip.add.ress , server: localhost, request: "GET /images/main_arrow.gif HTTP/1.1", upstream: "http://[2002:42eb:b46b::2]:8080/images/main_arrow.gif", host: "www.ourdomain.com", referrer: "http://www.ourdomain.com/"
2016/11/06 13:44:58 [error] 16306#16306: *11 upstream timed out (110: Connection timed out) while connecting to upstream, client: my.ip.add.ress, server: localhost, request: "GET /images/main_linuxhosting.gif HTTP/1.1", upstream: "http://[2002:42eb:b46b::2]:8080/images/main_linuxhosting.gif", host: "www.ourdomain.com", referrer: "http://www.ourdomain.com/"
2016/11/06 13:45:02 [error] 16306#16306: *19 upstream timed out (110: Connection timed out) while connecting to upstream, client: my.ip.add.ress, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[2002:42eb:b46b::2]:8080/", host: "www.ourdomain.com"
2016/11/06 13:45:03 [error] 16306#16306: *23 upstream timed out (110: Connection timed out) while connecting to upstream, client: my.ip.add.ress, server: localhost, request: "GET /images/main_arrow.gif HTTP/1.1", upstream: "http://[2002:42eb:b46b::2]:8080/images/main_arrow.gif", host: "www.ourdomain.com", referrer: "http://www.ourdomain.com/"

$ netstat -anp | grep :80 | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -n

      1 
      2 0.0.0.0
      2 127.0.0.1
      5 2002
     11 my.ip.add.ress

=====

I checked the config, IPv6 config was disabled, I enabled it , that did not make a difference.
I also disabled CSF Firewall, no change
There are no modsec rules or tools installed.

The IPv6 address listed above does not belong to us, and we don't use any other 3rd party service.

Any suggestions?

Thanks,

Tim

**Comment by mediumt** [comment]
Just bit more information, the nginx simply hangs for period of time. Disabling IPv6 on the server temporarily using:

sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1

Appears to have resolved the problem!!

INSTALLED MODULES
=================
nginx version: nginx/1.11.5
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic'

**Comment by mediumt** [comment]
Now we see this error in the log, although the site appears to be working ok:

2016/11/06 14:13:34 [crit] 19884#19884: *68 connect() to [2002:42eb:b46b::2]:8080 failed (99: Cannot assign requested address) while connecting to upstream, client: 184.169.155.78, server: localhost, request: "HEAD / HTTP/1.1", upstream: "http://[2002:42eb:b46b::2]:8080/", host: "www.ourdomain.com"

**Comment by fevangelou** [comment]
If IPv6 traffic is routed to your server, it means IPv6 is still enabled (I guess). Maybe you should check with your hosting company why this occurs.

Of course you could just add:
```
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
```
...to your /etc/sysctl.conf file so there changes are permanent.
