### ISSUE TITLE
Uninstall Nginx Admin Plugin after installing Engintron

### ISSUE THREAD

**Issue by juliowriter** [engintron/engintron#306]
Hi,

I was using Nginx Admin and didn't uninstall it before installing Engintron. How do I remove Nginx Admin without problems? Can I just run the Nginx Admin uninstall? I took a look at the uninstall script and seems that it removes Nginx entirely from the server.

Thanks.

**Comment by fevangelou** [comment]
Execute the uninstaller as described in their docs. Then install Engintron. Done.

**Comment by fevangelou** [comment]
```
cd /usr/local/src
wget http://nginxcp.com/latest/nginxadmin.tar
tar xf nginxadmin.tar
cd publicnginx
./nginxinstaller uninstall
```

(if I recall properly)
