### ISSUE TITLE
Cache always shows as expired

### ISSUE THREAD

**Issue by CarlosLopezES** [engintron/engintron#308]
Hi,

First of all, thank your for this plugin, is really good 👍 

I have a problem, if i retrieve the headers of a picture, the first is miss and the second and so on it's hit, so it's right, but when i retriefe the headers of a full web, like a Wordpress (a tried with more than 10), the cache status always says EXPIRED.

This is normal behaviour?

Thanks!

King regards,

**Comment by Quazz** [comment]
You're likely hitting the dynamic cache or microcache which only lives for 1 second. So yes, it's normal.

**Comment by CarlosLopezES** [comment]
Thanks! :)
