### ISSUE TITLE
Pure NGINX vs Engintron (Reverse Proxy)

### ISSUE THREAD

**Issue by MarcusChiang** [engintron/engintron#309]
Hello, does anyone knows whether Pure NGINX or using Engintron is faster? Thanks.

**Comment by ntorga** [comment]
NGINX as web server will be faster and lighter, no doubt (google for benchmarks). However, if you have to have .htaccess for your customers, Engintron it's your the best choice. Unless you want to pay ~$30 per node to LiteSpeed.

Engintron is a NGINX well pre-configured as reverse proxy with a WHM interface. If you configure your Apache correctly, I suppose it will be fast and easy as LiteSpeed.

To configure your Apache correctly, I suggest using MPM Event:
http://ntorga.com/2016/11/tuning-optimizing-apache-cpanel-servers/

If you don't care about .htaccess files, go for NGINX directly.

**Comment by MarcusChiang** [comment]
Thanks! It answered to my question :)
