### ISSUE TITLE
Engintron folders / files left in place after uninstall

### ISSUE THREAD

**Issue by Sovjohn** [engintron/engintron#311]
Hello,

I recently found out that for reasons unknown, having Engintron installed in the server it used to be installed made it a quite prime target for Chinese botnets. Since it's not the first time I've encountered "Chinese botnets" and "engintron-enabled server" in the same sentence, I can only assume that the default port number of 8080 used under Engintron is a red herring (?) or otherwise a lure for such attacks, considering I only had this configuration enabled in one server, but no others, even in the same datacenter, were ever affected even by chance.

Anyhow, it was not used enough to justify keeping it, and the DDoS attacks, alive, so it is now uninstalled.

**The question is:**

Even after uninstallation and a reboot, I still see some folders engintron_something in a /secure.tmp backup generated by CPanel it seems.

Is it safe to delete those, since they are close to 40 GB in size? Apart from engintron_temp and engintron_dynamic should I look for anything else that was not deleted during the uninstall process?

Thanks a lot, and hopefully when I re-use Engintron it will have less fervent links with Chinese random attackers 👍

**Comment by fevangelou** [comment]
If you had such traffic on your server, you could just swap the Apache port from 8080 to anything else. Or you could just block access to port 8080 except for traffic coming from 127.0.0.1 (aka Nginx).

In you case, the files you see inside /tmp are just the cache leftovers, so they are safe to be deleted. There are no other files left in place. Actually a reboot should have already purged the contents of /tmp.
