### ISSUE TITLE
Issue with IPB

### ISSUE THREAD

**Issue by CJF077** [engintron/engintron#312]
Guys having an issue with Enginetron installed on a server with the latest version of invision power board. We are having user's log on and then next time they come back to the PC they are logged on as another user. We have been told by IPB that it is related to enginetron and it caching sessions in which it shoudnt. Need to resolve urgently as its causing security issues. Please let me know how to resolve.

**Comment by sterlingken** [comment]
Try to disable the micro cache feature and see if that fixes it.

https://github.com/engintron/engintron/wiki/About-Engintron's-micro-caching-features

**Comment by fevangelou** [comment]
It's not caching sessions (that's not possible)... Some, I repeat some, users just happen to see a cached/stale copy of another user's profile. This could be a result of a slow backend, causing Nginx to withhold cached pages longer, as it's built to do just that, in case Apache goes down.
