### ISSUE TITLE
mod_remoteip is available EA 4

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#317]
Hello,

Please let me know that Does engintron skip install mod_remoteip for EasyApache 4? mod_remoteip is available EasyApache 4. You can check out the full listing of packages by running: yum list "ea-*"

The install is:
yum install ea-apache24-mod_remoteip

Thanks

**Comment by fevangelou** [comment]
I'll add a check in the installer.

Thanks for letting me know.

**Comment by Nirjonadda** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Yes , add check in the installer for EasyApache 4. Check if mod_remoteip already installed or not.


Sent from Yahoo Mail for iPhone


On Sunday, November 20, 2016, 11:51 AM, Fotis Evangelou <notifications@github.com> wrote:

I'll add a check in the installer.

Thanks for letting me know.
