### ISSUE TITLE
HTTPS configuration is lost after upgrading to 1.7.3

### ISSUE THREAD

**Issue by dcordovez** [engintron/engintron#319]
My custom files in /etc/nginx/conf.d/"midomain.ssl.conf" are lost after upgrade nginx to 1.7.3 
If someone has custom files for nginx to respond by https, they should make a backup before upgrading, and change the apache configuration to listen on 443 until they load their custom files.

**Comment by fevangelou** [comment]
You are probably mistaking Engintron with some other plugin. The only file in /etc/nginx/conf.d/ as setup by Engintron is "default.conf".

**Comment by dcordovez** [comment]
Hello @fevangelou , I'm 100% sure that I'm not confusing the plugin. ;) .
I have custom config files in /etc/nginx/conf.d/  to enable SSL for Nginx 
(based on this post: https://github.com/engintron/engintron/issues/106#issuecomment-252431666)

**Comment by fevangelou** [comment]
Then you must re-apply your modifications. The only file you can freely update without losing changes is custom_rules.

**Comment by dcordovez** [comment]
@fevangelou , I understand that I must re-apply the modifications to the engintron files, but in this case what is lost are files that one has added and no modifications to the engintron files. Anyway it was to warn users that they have used the same @jcatello solution to enable SSL.   Thanks!

**Comment by fevangelou** [comment]
The installer does not overwrite files for sure. Maybe something else is wrong. Tell me the exact changes you've done so I can help you.

**Comment by dcordovez** [comment]
Thanks @fevangelou .
I tested with two servers in which in the folder /etc/nginx/conf.d/ I had additional files called (for example) domain1_com.ssl.conf and domain2_com.ssl.conf, based on the solution of @jcatello to enable SSL manually in engintron for specific domains. 
After updating engintron to version 1.7.3, these configuration files were deleted, so engintron was no longer listening on port 443, and these domains no longer responded. 

The solution is simple, just restore the files from some backup, or put Apache back to listen on port 443; But I consider it opportune that other users of engintron that would have applied the same solution for SSL keep it in mind.

**Comment by fevangelou** [comment]
It seems I've indeed added a command to cleanup anything within /etc/nginx/conf.d/, presumably to make sure that folder is kept tidy. Either way, v1.8.0 will be released this week, which will address the TLS/SSL issue.

However, if you are interested in maintaining your custom configurations, maybe I could create a separate folder for that and have nginx.conf pick up any file put in there. How's that sound?

**Comment by dcordovez** [comment]
Thanks @fevangelou sounds great.
