### ISSUE TITLE
Awstat date issue,

### ISSUE THREAD

**Issue by bashcode** [engintron/engintron#321]
Hello,

Awstat is showing bad date after engintron installation, you can see issue here
 [Awstat ERROR](http://image.prntscr.com/image/3a88ae1b22c54977a4626203c58878e0.png)

**NOTE**: server date time is correctly configured.

Thanks

**Comment by dcordovez** [comment]
Hi, I had the same problem when I started using Engintron, and to solve it I added this configuration to apache: (in WHM: Apache Configuration -> Include Editor -> Pre VirtualHost Include - >All Versions)

`<IfModule mod_log_config.c>
    LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%a %l %u %t \"%r\" %>s %b" common
    LogFormat "%{Referer}i -> %U" referer
    LogFormat "%{User-agent}i" agent
    CustomLog logs/access_log common
</IfModule>`
