### ISSUE TITLE
httpd-devel package

### ISSUE THREAD

**Issue by truls1502** [engintron/engintron#324]
Hi @fevangelou 

To install httpd-devel package "httpd dev tools" for mod_remoteip to work perfectly but cPanel is not recommending it.

We are using CloudLinux 7.3 in the server and are using vendor-provided distributions (recommended) and httpd-devel is excluded in the yum configuration and hence mod_remoteip is not working as required and wonder if there is an alternative/work around for this?

**Comment by fevangelou** [comment]
First install Engintron. Then install the mod_remoteip package provided by EasyApache4. Update the LogFormat line in your Apache config from "%h %l..." to "%h %a %l...". Distill changes in Apache with:
```
$ /usr/local/cpanel/bin/apache_conf_distiller --update; /scripts/rebuildhttpdconf; /scripts/restartsrv httpd
```

Done.

**Comment by truls1502** [comment]
With EA4 mod_rewrite is enabled by default as it is compiled along (built-in) with Apache, but it's not listed while checking through WHM --> EasyApache4 --> Current Profile

**Comment by fevangelou** [comment]
Did you mean mod_remoteip?

**Comment by truls1502** [comment]
Hi @fevangelou 

I can see mod_remoteip listed while checking through WHM --> EasyApache4 --> Current Profile. It is mod_rewrite which is enabled by default as it is compiled along (built-in) with Apache, but it's not listed while checking through WHM --> EasyApache4 --> Current Profile.

**Comment by fevangelou** [comment]
That's a cPanel issue and it does not affect either Engintron or Nginx. You should definitely contact cPanel support for that.

**Comment by truls1502** [comment]
cPanel support respond that this doesn't appear to be an issue with cPanel or its bundled software. They checked the FAQ within the GitHub and found a topic that appears to apply to your issue; https://github.com/engintron/engintron/issues/356 This FAQ does have a link to the following as well; https://github.com/engintron/engintron/issues/168. The best option would be to consult with the developers of Engintron for additional assistance.

**Comment by truls1502** [comment]
Hi @fevangelou , is it possible to re-open this issue and you could give me the feedback regarding previous post? :)

**Comment by fevangelou** [comment]
You said above:
> It is mod_rewrite which is enabled by default as it is compiled along (built-in) with Apache, but it's not listed while checking through WHM --> EasyApache4 --> Current Profile.

Again, mod_rewrite is NOT installed or used by Engintron.

If you refer to mod_remoteip (totally different thing), you won't see it in EasyApache if I recall properly.
