### ISSUE TITLE
How can exclude a domain in Engintron?

### ISSUE THREAD

**Issue by aledel76** [engintron/engintron#327]
Hi, I need to exclude a specific domain from engintron. How can I do this?

**Comment by hostfusion** [comment]
Hi,
you can exclude in Edit custom rules

# === WHEN TO SPECIFY A DOMAIN IP ===
# By default, Nginx will redirect requests to the right domain IP by using DNS resolving.
# However there are cases where you want to specify an IP for use with Nginx:
# - When you use CloudFlare for certain domains only on your server,
#   regardless of whether these domains use the server's shared IP or a dedicated IP.
# - When you are working on a domain which does not yet (DNS) resolve to your server,
#   but you want to access it by modifying your computer's "hosts" file.
#
# To specify the domain IP in such cases, simply enter a domain or subdomain in an "if" block
# (as shown below) and inside that block set the appropriate shared or dedicated IP to point to.
#
# To specify the IP for a domain simply uncomment the following 3 lines and make sure you replace
# example.com with your actual domain or subdomain and also replace XXX.XXX.XXX.XXX with the actual
# IP assigned to that domain. To specify the IP for more domains, simply copy that "if" block
# (per domain) and change accordingly.
#
#if ($host ~ "example.com") {
#    set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX";
#}

Regards

PS

**Comment by fevangelou** [comment]
See the Wiki as @hostfusion mentioned :)
