### ISSUE TITLE
Nginx not launching automaticaly at the end of the script

### ISSUE THREAD

**Issue by undisconnected** [engintron/engintron#328]
Hey guys, 

Just installed Engintron and wanted to report a small bug : Nginx didn't start automaticaly at the end of the installation. My website wasn't working just after install. But everything seems to happend normally. So from the WHM dashboard I just checked Nginx status and it was off, so I just turned it on and everything was working fine :) 

Thanks for a great software :)

**Comment by fevangelou** [comment]
Did you use another plugin for Nginx on cPanel previously?
