### ISSUE TITLE
Issue with import after installing enginetron

### ISSUE THREAD

**Issue by marijana** [engintron/engintron#330]
Hello!

We have import that first grabs a file from remote server and copies it to our server and then runs import to mysql.
Since we installed engintron, the file copying part of import has stopped working.

This is the error we get after running the php file for import:
Warning: filesize(): stat failed for ssh2.sftp://Resource id #3/D17894_02_12_2016.xml in /home/mysite/public_html/import/import.php on line 20

We have PHP 5.4.45
Engintron v1.7.3. 
Ngnix version : 1.10.2
Kernel Version  2.6.32-604.16.2.lve1.3.54.el6.x86_64

We did no changes to import file. 
We can still reach remote files via filemanager (filezilla), so connection is fine.
We also tried to add this domain to exceptions for enginetron, didn't help.

Any idea what could be happening here?

**Comment by fevangelou** [comment]
Can you provide the code you're using? Comment out or replace the important bits if you may...

**Comment by marijana** [comment]
`$ftp_server='ftp.page.com';
$ftp_user='user';
$ftp_pass='pass';
$local_file='pricelist.xml';
$datum=date("d_m_Y");
$remote_file="D17894_$datum.xml";


$connection = ssh2_connect($ftp_server, 22) or die("Couldn't connect to $ftp_server"); 
ssh2_auth_password($connection, $ftp_user, $ftp_pass);
$sftp = ssh2_sftp($connection);
$stream = @fopen("ssh2.sftp://$sftp/$remote_file", 'r');
if (! $stream) throw new Exception("Could not open file: $remote_file");
$size = filesize("ssh2.sftp://$sftp/$remote_file");            
$contents = ''; $read = 0;
$len = $size;
while ($read < $len && ($buf = fread($stream, $len - $read))){
 $read += strlen($buf);
 $contents .= $buf;
}        
file_put_contents ($local_file, $contents);
@fclose($stream);`

**Comment by marijana** [comment]
This was not engitron related issue.
Closing it.
Thank you for your time!
