### ISSUE TITLE
Subdomains not showing up after creating in Cpanel

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#334]
After I installed Engintron, I am having an issue with Cpanel created subdomains.

When i create a subdomain in Cpanel, normally the directory would automatically be created in the domains account but in my case the directory is not being created automatically.   Inside WHM i can see the created subdomain, but the directory isn't created where i can upload my files to.

Is this a coincidence and really a CPanel problem, or does it have something to do with Engintron?

Thanks for any assistance.

**Comment by fevangelou** [comment]
There's an option recently added in cPanel that allows other domains and subdomains within the same account to be outside of the /home/USERNAME/public_html/ folder. Maybe that's the case.

**Comment by WebSavvyGuy** [comment]
yeah i think it was that issue.   Subdomains were put in /home/username/  instead of /home/username/public_html
