### ISSUE TITLE
Domain exclusion does not work

### ISSUE THREAD

**Issue by daredevil04** [engintron/engintron#335]
Hello!

The user has own  cms, and when he make "post" and put the picture (.jpg) , but not show immediately (.jpg),
we set in : "Edit your custom_rules for Nginx":

`if ($SITE_URI ~* "somesite.com") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
    set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}`

But not work, the client always make ctrl+f5 how to able to see picture (.jpg).

Also we try disable temporarily in "default.conf" micro cache, 

` # === MICRO CACHING ===
        # Comment the following line to disable 1 second micro-caching for dynamic HTML content
     #   include proxy_params_dynamic;
    }`

restart all service , but it still shows that the cached.

We try in "proxy_params_static" set to 3s : 
`proxy_cache_valid       200 301 302 3s; # Adjust for longer server-side cache times (unfortunately, we cannot use a variable here)`

but it still shows that the cached.

Do you have any advice

**Comment by fevangelou** [comment]
Did you resolve this?
