### ISSUE TITLE
Sessions got mixed with update 1.7.3

### ISSUE THREAD

**Issue by Mecanik** [engintron/engintron#338]
I did the horrible mistake by pressing the update link to 1.7.3, since then all my customer`s sessions got messed up. I host many gaming websites, and 5 minutes later after this upgrade someone showed me what happened, by just refreshing the page on a busy website it was showing accounts logged in randomly. 

Basically 1 refresh you saw "john" logged in, another refresh and you saw "David" logged in, and of course you could access his virtual money and everything. 

This stopped after I disabled the plugin, and everything went back to normal. I never had problems with this module, ever. Everything was smooth and running really nice, the only thing was missing is SSL support.

I hope this information helps, and you can fix it as it`s a very serious issue...

**Comment by SashRaven** [comment]
It's a microcache feature. You can dissable domain's microcache by editing custom rules file. Or disable it completely for web-server.

**Comment by fevangelou** [comment]
1.7.2 to 1.7.3 had no changes in the way caching is performed. You just noticed a stale cache object. And like @SashRaven said, it's pretty easy to add domain specific exclusions or turn off micro caching entirely. See the Wiki for more.
