### ISSUE TITLE
`create_temp_reseller_for_ticket_access` script can't access WHM interface

### ISSUE THREAD

**Issue by Hostert** [engintron/engintron#339]
cPanel support uses a script called `auto_repair` to login to WHM without requesting root password:

```
# /scripts/autorepair create_temp_reseller_for_ticket_access
Requesting script ... info [autorepair] Successfully verified signature for cpanel (key types: release).
Done
Auto Repair is running...ENTER_TEMP_RESELLER_AND_PASSWORD: 
```

The requirement, is to set a user starting with `cptkt`, for example, `cptkt_user pass123`.

Ok, this is the method I use to access all my customers servers, without requesting their root passwords.
But, in new versions of Engintron, I can't access the UI interface anymore: `You do not have sufficient permissions to access this page...`

Can you restore this permission in the ACL?
Thanks

**Comment by fevangelou** [comment]
I'll have a look. Can you access other 3rd party plugins by the way? E.g. CSF, Munin etc.

**Comment by Hostert** [comment]
Yes, the `cptkt` user have access to many things in root level, including CSF, Munin and many other plugins.

**Comment by fevangelou** [comment]
Can't find anything search for "cptkt" in cPanel documentation site: https://documentation.cpanel.net/dosearchsite.action?queryString=cptkt

Got any other reference?

**Comment by Hostert** [comment]
You can see references about AutoFixer in https://documentation.cpanel.net/display/64Docs/WHM+FAQ#WHMFAQ-WhatistheWHMAutofixer?

But, in this page you'll not find references to [`create_temp_reseller_for_ticket_access`](http://httpupdate.cpanel.net/autofixer2/create_temp_reseller_for_ticket_access) script. You shoud take a look at [autofixer repository](http://httpupdate.cpanel.net/autofixer2/).

Short explaining:

1. Run `/scripts/autorepair create_temp_reseller_for_ticket_access`
2. Enter any user and password. The rule to work is to start the user with `cptkt` username. For example: cptkt_fevangelou is valid, but fevangelou is not.
3. After this, you can login to your WHM interface using this newly created user and password.
4. When you close your SSH session, the user will be automagically removed.

**Comment by Hostert** [comment]
Looking to [create_temp_reseller_for_ticket_access](http://httpupdate.cpanel.net/autofixer2/create_temp_reseller_for_ticket_access) script, they changed the user requirement to start with `cp` only:

```
if ( $user !~ /^cp/ ) {
    die "User must start with cp";
}
```
