### ISSUE TITLE
Optimizing CentOS - Unknown key & permission denied

### ISSUE THREAD

**Issue by mcpacific** [engintron/engintron#341]
I made the changes as suggested, and when I issued the command syssctl -p I get this:

net.ipv4.ip_forward = 0
net.ipv4.tcp_syncookies = 1
error: "net.bridge.bridge-nf-call-ip6tables" is an unknown key
error: "net.bridge.bridge-nf-call-iptables" is an unknown key
error: "net.bridge.bridge-nf-call-arptables" is an unknown key
error: permission denied on key 'net.core.netdev_max_backlog'
net.core.somaxconn = 65535
error: permission denied on key 'net.ipv4.tcp_max_syn_backlog'
error: permission denied on key 'fs.file-max'

**Comment by fevangelou** [comment]
You're probably using a VM and depending on the virtualization platform, you may not be allowed to change some values. E.g. OpenVZ or LXC/LXD virtualization do not allow for all values to change in your sysctl.conf file.
