### ISSUE TITLE
whats server

### ISSUE THREAD

**Issue by brinsleyparagao** [engintron/engintron#344]
Hello...
In my server have some sites, and some these appear with nginx and anothers with apache server in header connection. Why ?

**Comment by windsofchange** [comment]
The apache server site are most likely being called over https...

**Comment by brinsleyparagao** [comment]
OK, but if i empty the publichtml dir or use only html elements the head is "nginx"

but if i use some wordpress, joomla, or some dinamic site, its showme apache
