### ISSUE TITLE
Engintron installation error

### ISSUE THREAD

**Issue by Jeanpjm** [engintron/engintron#346]
### Hello,

The installation of Engintron is giving error in my server according to information below. Can someone help me

This is what is being reported by Apache when trying to start it after installing the Engintron: 

==============
httpd.service - Apache webserver managed by cPanel EasyApache
Loaded: loaded (/etc/systemd/system/httpd.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Thu 2016-12-15 10:00:26 BRST; 1min 57s ago
Process: 746029 ExecStart=/usr/local/cpanel/scripts/restartsrv_httpd --no-verbose (code=exited, status=1/FAILURE)
Main PID: 527062 (code=killed, signal=KILL)

Dec 15 10:00:26 server1.hostday.com.br systemd[1]: Starting Apache webserver managed by cPanel EasyApache...
Dec 15 10:00:26 server1.hostday.com.br restartsrv_httpd[746029]: AH00526: Syntax error on line 4 of /usr/local/apache/conf/includes/remoteip.conf:
Dec 15 10:00:26 server1.hostday.com.br restartsrv_httpd[746029]: RemoteIP: Error parsing IP RemoteIPInternalProxy (Name or service not known error) for RemoteIPInternalProxy
Dec 15 10:00:26 server1.hostday.com.br restartsrv_httpd[746029]: Unknown operation 'nginx'.
Dec 15 10:00:26 server1.hostday.com.br systemd[1]: httpd.service: control process exited, code=exited status=1
Dec 15 10:00:26 server1.hostday.com.br systemd[1]: Failed to start Apache webserver managed by cPanel EasyApache.
Dec 15 10:00:26 server1.hostday.com.br systemd[1]: Unit httpd.service entered failed state.
Dec 15 10:00:26 server1.hostday.com.br systemd[1]: httpd.service failed.
==============

Thanks
Jean

**Comment by fevangelou** [comment]
Did you previously have another Nginx for cPanel plugin installed?
