### ISSUE TITLE
SSL + Engintron

### ISSUE THREAD

**Issue by brinsleyparagao** [engintron/engintron#347]
Hello...

In cpanel if use this plugin https://letsencrypt-for-cpanel.com/ the engintron no work, make a bypass to apache.

How to make SSL work fine with Engintron ?

**Comment by windsofchange** [comment]
This is a TODO 
expected in version 1.8

**Comment by ALEXTHQ** [comment]
Hello,

Please let me know the expected time when version 1.8 with SSL will be released. 

Hope to hear from you soon.

**Comment by fevangelou** [comment]
v1.8.0 resolves this. Upgrade now. You can also use the AutoSSL feature in cPanel with this: https://documentation.cpanel.net/display/CKB/The+Let's+Encrypt+Plugin
