### ISSUE TITLE
it take too much time to load than apache

### ISSUE THREAD

**Issue by ayyoobvm** [engintron/engintron#348]
I am installed and activated it.i experiance too time to  low to load page than apache.why? Any change needed?

**Comment by fevangelou** [comment]
How the heck should I know. You haven't provided any system info or
history, not even some domain to check.

**Comment by ayyoobvm** [comment]
site
http://Xtrawap.Com

**Comment by ayyoobvm** [comment]
Server response time is high

**Comment by ayyoobvm** [comment]
Total processors: 4

Processor #1

    Vendor
        GenuineIntel

    Name
        Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz

    Speed
        3587.625 MHz

    Cache
        8192 KB

Processor #2

    Vendor
        GenuineIntel

    Name
        Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz

    Speed
        3427.125 MHz

    Cache
        8192 KB

Processor #3

    Vendor
        GenuineIntel

    Name
        Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz

    Speed
        3591.375 MHz

    Cache
        8192 KB

Processor #4

    Vendor
        GenuineIntel

    Name
        Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz

    Speed
        3540.375 MHz

    Cache
        8192 KB
32 GB Memory..Easy apache 4 With Php56-Cgi

**Comment by cmerola** [comment]
@ayyoobvm Are you running CloudLinux?

If not try, run: yum install htop

Then once installed, run: htop

From there it should be apparent whether CPU or Ram is a bottleneck. My .02..
