### ISSUE TITLE
Cloudflare and Engintron

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#349]
We installed Engintron and have several domains (all our domains are on the cloudflare network but not all are passing through cloudflare if that makes sense.   In other words some just use it for DNS (the cloud thing in the DNS is unclicked for some domains)

So, what happened yesterday was i added a new domain that was actuallly fully using Cloudflare so we created a custom rule as per the instructions for a domain that is associated with a dedicated IP and using cloudflare.

if ($host ~ "mydomain.com") {
set $PROXY_DOMAIN_OR_IP "xxx.xxx.xxx.xxx";
}

After that i restarted and i noticed that all my domains except that one went down.

So, i want to know is it true that once you create 1 custom rule for a cloudflare associated domain, you must do it for ALL of them???

The only way we got the rest of our sites up was to create custom rules for all of them (which we never had done before)   Again, everything was working fine before without custom rules on domains that were on the cloudflare network but not actually fully using cloudflare.

I just want to make sure that is what i was supposed to do or if there is some sort of bug caused by this.

**Comment by fevangelou** [comment]
Does your server have one shared IP only? If not, are the CF domains on the
same or different IPs?

**Comment by WebSavvyGuy** [comment]
No the server has a bunch of dedicated IPs (and 1 shared one).    The CF domains are on a combination of shared and some have their own IPs.    All the domains are on CF though.  However, some do not have the domain going through Cloudflares services (cloud is not checked)  but every domain is using CFs DNS system.

What i have found is that if you have even one custom rule for a domain that will affect all your other domains and you must make custom rules for every single domain or it will bring a 502 error to those not placed within a custom rule.

I don't know if that is how its suppose to operate or there is a bug or maybe its just my server has a bug......but it would be nice if i can add some domains with custom rules and some without.  I am sure that a lot of people run Cloudflare, but don't have every single domain they own going through it.

**Comment by fevangelou** [comment]
Most servers usually have a single shared IP. So you can easily make one
rule using that IP and cover all domains regardless of where their domains
are hosted (locally, CF or other DNS provider).

In your case, since you have multiple IPs and all domains on CF you need to
add IP definitions for all your domains. To make things simpler, use just
the naked domain if all its subdomains point to the same IP.

**Comment by WebSavvyGuy** [comment]
Yes i have done that now.   I was just wondering why some domains that dont have Cloudflare "on" (cloud clicked) still need rules even though when there are  NO custom rules, the domains work fine, but as soon as one custom rule is placed in there, all the domains break (502 nginx error).

Maybe that can be fixed in a future update.

**Comment by dannymichel** [comment]
What if you run a hosting company and you can't keep track of every client using cloudflare?
Seems a bit weird we have to set custom rules for every website, no?

**Comment by fevangelou** [comment]
I assume because CloudFlare still does proxying, but not IP masking. I have various solutions in mind (in general) which will materialize in v2.x.
