### ISSUE TITLE
How to stop Nginx responding to invalid hosts?

### ISSUE THREAD

**Issue by ImLuke954** [engintron/engintron#351]
On checking the error log, I found a lots of request to spoofed hosts to which nginx responded. How can we make nginx throw a 444 response to spoofed hosts? 
Here is a part of the error log:
`2016/12/22 04:12:48 [error] 14360#14360: *329770 www.x6cssf.com could not be resolved (2: Server failure), client: 104.148.75.115, server: localhost, request: "GET / HTTP/1.1", host: "www.x6cssf.com"
2016/12/22 04:12:53 [error] 14360#14360: unexpected response for www.x6cssf.com
2016/12/22 04:22:34 [error] 14359#14359: *330050 www.x6cssf.com could not be resolved (2: Server failure), client: 104.148.75.114, server: localhost, request: "GET / HTTP/1.1", host: "www.x6cssf.com"
2016/12/22 04:22:39 [error] 14359#14359: unexpected response for www.x6cssf.com
2016/12/22 04:26:06 [error] 14359#14359: *330188 www.x6cssf.com could not be resolved (2: Server failure), client: 23.247.72.4, server: localhost, request: "GET / HTTP/1.1", host: "www.x6cssf.com"
2016/12/22 04:26:11 [error] 14359#14359: unexpected response for www.x6cssf.com
2016/12/22 04:26:34 [error] 14359#14359: *330195 www.x6cssf.com could not be resolved (2: Server failure), client: 23.247.88.27, server: localhost, request: "GET / HTTP/1.1", host: "www.x6cssf.com"
2016/12/22 04:26:39 [error] 14359#14359: unexpected response for www.x6cssf.com
2016/12/22 06:45:50 [error] 14360#14360: *333852 connect() failed (110: Connection timed out) while connecting to upstream, client: 104.148.75.82, server: localhost, request: "GET / HTTP/1.1", upstream: "http://104.20.192.38:8080/", host: "www.mudao168.com"
2016/12/22 06:46:53 [error] 14360#14360: *333852 connect() failed (110: Connection timed out) while connecting to upstream, client: 104.148.75.82, server: localhost, request: "GET / HTTP/1.1", upstream: "http://104.20.193.38:8080/", host: "www.mudao168.com""`

**Comment by fevangelou** [comment]
Try this: https://github.com/engintron/engintron/wiki/Restrict-access-to-ports-8080-&-8443-used-by-Apache-only-for-Nginx
