### ISSUE TITLE
Cpanel + Engintron  Default page redirect

### ISSUE THREAD

**Issue by josephmiller2000** [engintron/engintron#352]
I have too many domains in my dedicated server and using engintron for a while now..

All site works good.. but this new domain i have added was loading at first time when we try to access the site.. and when we refresh the page... it takes to default cpanel page...

It is soo weird.. all other site works fine without any issues... just this domain and i got dedicated ip for this site..

**Comment by fevangelou** [comment]
Does it propagate (DNS wise) to your server?
