### ISSUE TITLE
nginx and magento in cpanel order issue

### ISSUE THREAD

**Issue by ncostis** [engintron/engintron#355]
I have installed engintron nginx and magento in cpanel. I left engintron in its defaults but there was a huge mess with orders from magento, the were confused and one could see the others. Any suggestions?

Nick

**Comment by fevangelou** [comment]
They just saw snapshots, not actual data. Have a look at the wiki and you'll see ways to either disable the 1s micro-cache entirely or to add a certain domain exception to it. You can also have a look at the "custom rules" files which includes examples on how to do such tasks.
