### ISSUE TITLE
Wrong IP Visitor - EA3

### ISSUE THREAD

**Issue by rafaelppaulucci** [engintron/engintron#356]
Hi guys,

im having a issue with IP visitor at Apache with EA3.
At the Nginx, the ip is showed correctly.
At httpd fullstatus, the public of my server still appears at connection info. (obviusly same at engitron apache info).

How i can fix this?
regards.

**Comment by rafaelppaulucci** [comment]
I Found another topic about that, but was EA4.
i create one file with this content:

<?php echo $_SERVER["REMOTE_ADDR"]; ?>

The public IP server is showed, and not my client ip.

Regards.

**Comment by arabgenius** [comment]
Hello
I had same problem
but I edited the file /usr/local/apache/conf/includes/remoteip.conf
find
RemoteIPHeader X-Real-IP
replace it to
RemoteIPHeader X-Client-IP

**Comment by timeassistant** [comment]
try and click reinstall engintron this was a previous issue referenced here https://github.com/engintron/engintron/issues/168
