### ISSUE TITLE
Bulk Exceptions for Cloudflare + Major Security Issue on Xenforo

### ISSUE THREAD

**Issue by ichadi** [engintron/engintron#357]
> So, if you have any domains hosted on your cPanel server that use CloudFlare for their CDN, you just set your server IPs inside your "custom_rules" Nginx configuration file (the file is commented for your help) and just restart Nginx for the changes to take effect.

Just installed this on my main box, but want to install also for shared hosting customers on a few other servers running Centos / cPanel. The issue is many clients use Cloudflare and in some cases, dedicated IPs (especially on reseller hosting servers). Is there a bulk, automated way to insert this in the custom rules file?

**Comment by ichadi** [comment]
Another issue, my domain (same server here) uses Cloudflare and runs Xenforo. When Enigtron is enabled and domain is added to custom rules file, users including me are logged into ANOTHER user's account! This is crazy. How can this be fixed?

**Comment by ichadi** [comment]
Anyone?

**Comment by WebSavvyGuy** [comment]
Yes, i am also getting this issue with Vbulletin.   But its not a security issue in the sense that it refreshes the their normal account upon next action (refresh the page or navigate to another page) but, yes, it is a bit unsettling to say the least.

**Comment by petethumped** [comment]
try this https://github.com/engintron/engintron/issues/12

**Comment by WebSavvyGuy** [comment]
Hi Pete

Thanks ive changed that from 0 to 1.

I hope this can help and hope @fevangelou can confirm this is the solution to solve these dynamic forums issues alot of us are getting.

Thanks.

**Comment by ichadi** [comment]
Is this referring to default.conf? I changed it to 

set $CACHE_BYPASS_FOR_DYNAMIC 1;

Is that the only thing needed aside a restart?

Side note, how can I compare performance between Enigtron disabled and enabled? Thanks!

**Comment by jimcouts** [comment]
@ichadi On a remote machine it's best to use the ab (apachebench) tool if you like while watching top / htop on the source machine. 

`i.e. ab -c 10 -t 30 -n 100000 -k http://yourdomainname.com/`

**Comment by WebSavvyGuy** [comment]
@petethumped I have noticed ever since changing the value to 1, when i do a header test it returns a value of "X-Cache-Status BYPASS" instead of "X-Cache-Status HIT"....

Any ideas of the advantages or disadvantages of this and why is it happening?  (it happened for a header test for a static page on our site)

**Comment by fevangelou** [comment]
@WebSavvyGuy "X-Cache-Status BYPASS" means Nginx is handling the response but no caching is performed, the request is proxied to Apache as is. "X-Cache-Status HIT" means Nginx handled the request and also served the response from cache.

Additionally, if you do "set $CACHE_BYPASS_FOR_DYNAMIC 1;" then micro-caching will turn off for dynamic content but will run just fine for static assets.

@ichadi There is no automated way at the moment.

**Comment by WebSavvyGuy** [comment]
@fevangelou Thanks for the reply.

Actually i just checked again and now its saying HIT for static pages and bypass for dynamic pages...so looks like its working fine.

**Comment by bobalo2** [comment]
I'd like to reopen this just to ask if it's possible to exclude certain sites from caching for example xenforo's login page in order to prevent this from happening. I have the same issue with users logging in as another users but I'd like to retain the caching and disable it on the login page (IF it'll work).

**Comment by fevangelou** [comment]
Have a look at the wiki or just read what's inside the "Custom Rules" config file in Engintron's WHM app.
