### ISSUE TITLE
CPANEL error in http awstats correct in https connections

### ISSUE THREAD

**Issue by avoulvou** [engintron/engintron#359]
Engintron version :v1.7.3 (Nginx version: 1.10.2)
CPANEL  WHM 60.0 (build 28)  WITH  CLOUDLINUX 
Server Version: Apache/2.4.23 
Error in awstats display only one visitor

Installed / unistalled and checked both with Nginx stable and Nginx mainline without change the results

The strange of this situation the sites with SSL  the stats displayed without problem

**Comment by georgemoralis** [comment]
awstats reads from apache logs . Since http requests go through nginx and not apache awstats calculation are wrong

**Comment by lmfreitas** [comment]
On the engintron.sh

I replaced the %h %a for %a and its working is there a need for the %h access_log?

77c77
<               sed -i "s:LogFormat \"%h %l:LogFormat \"%a %l:" /usr/local/apache/conf/httpd.conf
---
>               sed -i "s:LogFormat \"%h %l:LogFormat \"%h %a %l:" /usr/local/apache/conf/httpd.conf
91c91
<               sed -i "s:LogFormat \"%a %l:LogFormat \"%h %l:" /usr/local/apache/conf/httpd.conf
---
>               sed -i "s:LogFormat \"%h %a %l:LogFormat \"%h %l:" /usr/local/apache/conf/httpd.conf
119c119
<                               sed -i "s:LogFormat \"%h %l:LogFormat \"%a %l:" /etc/apache2/conf/httpd.conf
---
>                               sed -i "s:LogFormat \"%h %l:LogFormat \"%h %a %l:" /etc/apache2/conf/httpd.conf
149c149
<                       sed -i "s:LogFormat \"%h %l:LogFormat \"%a %l:" /usr/local/apache/conf/httpd.conf
---
>                       sed -i "s:LogFormat \"%h %l:LogFormat \"%h %a %l:" /usr/local/apache/conf/httpd.conf
162c162
<               sed -i "s:LogFormat \"%a %l:LogFormat \"%h %l:" /etc/apache2/conf/httpd.conf
---
>               sed -i "s:LogFormat \"%h %a %l:LogFormat \"%h %l:" /etc/apache2/conf/httpd.conf
168c168
<                       sed -i "s:LogFormat \"%a %l:LogFormat \"%h %l:" /usr/local/apache/conf/httpd.conf
---
>                       sed -i "s:LogFormat \"%h %a %l:LogFormat \"%h %l:" /usr/local/apache/conf/httpd.conf

**Comment by avoulvou** [comment]
confused what you suggest to do ?

**Comment by lmfreitas** [comment]
In https.conf remove the %h in all LogFormat.
That's what it's returning the 2 ips in access_log.

You muse restart apache after changing this.

**Comment by fevangelou** [comment]
Or upgrade to the latest release of Engintron which has reworked IP proxying overall.
