### ISSUE TITLE
ENGINTRON Error

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#362]
Hello, On some openvz servers, engintron stop working! When trying to restart, I see the error below:

[Fri Jan 06 04:42:40.264720 2017] [alias:warn] [pid 15889] AH00671: The Alias directive in /etc/apache2/conf/httpd.conf at line 3906 will probably never match because it overlaps an earlier Alias.
[Fri Jan 06 04:42:40.264781 2017] [alias:warn] [pid 15889] AH00671: The Alias directive in /etc/apache2/conf/httpd.conf at line 3909 will probably never match because it overlaps an earlier Alias.
[Fri Jan 06 04:42:40.264785 2017] [alias:warn] [pid 15889] AH00671: The Alias directive in /etc/apache2/conf/httpd.conf at line 3911 will probably never match because it overlaps an earlier Alias.
[Fri Jan 06 04:42:40.264788 2017] [alias:warn] [pid 15889] AH00671: The ScriptAlias directive in /etc/apache2/conf/httpd.conf at line 3913 will probably never match because it overlaps an earlier ScriptAlias.
[Fri Jan 06 04:42:40.264791 2017] [alias:warn] [pid 15889] AH00671: The Alias directive in /etc/apache2/conf/httpd.conf at line 3914 will probably never match because it overlaps an earlier Alias.
[Fri Jan 06 04:42:40.264797 2017] [alias:warn] [pid 15889] AH00671: The ScriptAlias directive in /etc/apache2/conf/httpd.conf at line 3919 will probably never match because it overlaps an earlier ScriptAlias.
[Fri Jan 06 04:42:40.264800 2017] [alias:warn] [pid 15889] AH00671: The Alias directive in /etc/apache2/conf/httpd.conf at line 3920 will probably never match because it overlaps an earlier Alias.

How to solve?

**Comment by qant** [comment]
You need to show what you have in /etc/apache2/conf/httpd.conf at lines 3906, 09, 11, 13.

Also i can be wrong but doubt if warnings can stop nginx working... may be another logs in some other place?

**Comment by fevangelou** [comment]
Agree with @qant.
