### ISSUE TITLE
Using only UI of Engintron on installed nginx on cpanel?

### ISSUE THREAD

**Issue by qant** [engintron/engintron#363]
Hi there, i am new administrator of the server and i see in cpanel the nginx is installed:
http://joxi.ru/v29JbW7HvVwvAG.jpg

Can i some how install and use only UI of this beauty?

Or, if this is not possible, how i can reinstall this and use same configuration of current nginx?
What should i save for use this?
Thank you.

**Comment by fevangelou** [comment]
Clear your browser's cache or check with a private window. There is no .cgi file used in Engintron anymore. What you see is cached behaviour from your browser.
