### ISSUE TITLE
Engintron turning itself off

### ISSUE THREAD

**Issue by lucianozanita** [engintron/engintron#364]
On this morning from 06 to January 7 I had a multiple drop of 2 engintron, where both the access to them were with apache offline, at the moment I did not understand anything.
It seems to be some kind of conflict, I do not know the good.
I am using the same 2 servers in the same configuration:
CloudLinux
Engintron
Cpanel
Easy Apache 4

Could someone tell me what could cause this failure?
Well, it was with the two servers and they were both functioning normally throughout the week, having problems only now and just the same day the two together.

**Comment by ImLuke954** [comment]
Nginx probably died after cPanel upgrade. See #345 for restarting nginx automatically

**Comment by ImLuke954** [comment]
I got the same issue last night around 3 am (server time) last night i.e 3 am on 13th January.
My configuration:
Cloudlinux  
Engintron  
Easy Apache 4  
cPanel 60 (Build 34)

**Comment by lucianozanita** [comment]
Hello, I got the same problem tonight in the update you had from CPanel.
The Engintron has no explanation and resolution yet, the way to keep an eye on it.

**Comment by ImLuke954** [comment]
I tried the solution suggested in #343 but it seems it is not working.

**Comment by lucianozanita** [comment]
I'm in the same situation, and this only happens with Easy Apache 4, I have other servers in Easy Apache 3 does not occur.

**Comment by fevangelou** [comment]
Does anyone have LetsEncrypt with AutoSSL installed and enabled?

**Comment by ImLuke954** [comment]
Yes I have LetsEncrypt with AutoSSL enabled in one server. In another server, LetsEncrypt is not installed. 
Nginx died in both the machines during cpanel upgrade.

**Comment by fevangelou** [comment]
Nginx will be added to the list of monitored services in cPanel in v1.8.1. This will resolve such issues. Closing for now.
