### ISSUE TITLE
WHM 60.0 build 31 issues

### ISSUE THREAD

**Issue by DaRkRaGe** [engintron/engintron#366]
After the update to build 31, the plugin is not working properly, I get the following error on nginx:

[error] 16898#16898: *1215 connect() to [2a02:26f0:c000:18a::201a]:8080 failed (101: Network is unreachable) while connecting to upstream, client: 192.168.1.1, server: localhost, request: "POST / HTTP/1.0", upstream: "http://[2a02:26f0:c000:18a::201a]:8080/", host: "gp.symcd.com:80"

The weird thing is, apache works for 1 minute and then no response.

**Comment by Quazz** [comment]
Working fine on my end. Is it possible your host is having network issues? Also, it's trying to connect to ipv6 address, have you tried using the ipv4?

**Comment by DaRkRaGe** [comment]
All the configurations are set to default, so I haven't changed anything specific to ipv6. Where is this option? Thank you

**Comment by DaRkRaGe** [comment]
I just re-enabled nginx and now seems to be working ok. I will keep monitoring and let you know guys

**Comment by windsofchange** [comment]
@DaRkRaGe - when that happens open port 8080 and call the url in browser over port 8080 like http://domain.com/file.htm:8080 It should show the actual error
