### ISSUE TITLE
How to optimize Server Response Time ?

### ISSUE THREAD

**Issue by Cavain** [engintron/engintron#369]
Our server response time is too low we are checking it here > developers.google.com/speed/pagespeed/insights/ i am using Engintron  all services are working perfect but we are getting only one issue server response time too low is there any way to configure engintron to increase server response time ?

**Comment by Kjramey** [comment]
What is your current response time ? Are you using cloudflare or another CDN?

**Comment by fevangelou** [comment]
Networking is probably crap on your host. Provide a URL and let us know where you host so we can verify.

**Comment by mofolo** [comment]
Probably outside of the scope of this git. Maybe try Serverfault? 
Generally everything works pretty quickly out of the box, it starts getting slower when you do more things with your software (especially when using Wordpress + Plugins)

**Comment by fevangelou** [comment]
Considering this resolved.
