### ISSUE TITLE
connect() failed (111: Connection refused) 

### ISSUE THREAD

**Issue by theret** [engintron/engintron#371]
Hey

Keep getting this error non stop

'connect() failed (111: Connection refused) while connecting to upstream, client: 46.32.238.28, server: localhost, request: "GET / HTTP/1.1", upstream: "http://46.32.238.28:8080/", host: "dragonfly.productions"'

The IP address is my servers' IP address. 

Ideas? 

Thanks

**Comment by fevangelou** [comment]
I loaded the IP using both port 80 and port 8080 and the cPanel default page came up. So I assume it's resolved. If not, check that port 8080 is not blocked in your firewall.
