### ISSUE TITLE
Seeing default Tomcat home page after enabling engintron instead of website

### ISSUE THREAD

**Issue by coldplug** [engintron/engintron#373]
Hello,

New cpanel installation 60.0 build 35, EA4 default configuration. Webiste works OK. After installing Engintron, istead of website I get 
"Apache Tomcat/5.5.36"
"If you're seeing this page via a web browser, it means you've setup Tomcat successfully. Congratulations!

As you may have guessed by now, this is the default Tomcat home page. It can be found on the local filesystem at: ....... "

Have no idea what is going on. Used engintron a lot before on other servers, never happen this problem.

Disable/Enable, restart Apache/Nginx, and reinstalling engintron, does not help.

Thank you.

**Comment by fevangelou** [comment]
Tomcat is for Java based websites :)

Is the domain in question one that does not yet resolve to your cPanel server?
