### ISSUE TITLE
cPanel preview URL doesn't work

### ISSUE THREAD

**Issue by ciscospirit** [engintron/engintron#377]
Hello,

i found out a problem with engintron and cpanel preview urls.

I tried to deactivate mod_userdir security feature per user but it doesn't work. I got back a 404 error.
Just if I deactivate mod_userdir on the whole server preview urls work.

is there any known problem with engintron and preview urls?

**Comment by ciscospirit** [comment]
We also did this: https://github.com/engintron/engintron/wiki/Engintron-&-(under-development)-domains-that-don't-yet-resolve-(point)-to-your-cPanel-server

**Comment by fevangelou** [comment]
How is PHP compiled in your system? As Apache module, CGI/FastCGI module or otherwise?

**Comment by ciscospirit** [comment]
We use lsapi as php and it is compiled with easypache 4.

the main problem is, that if "mod_userdir" is active it is not possible to use the cpanel preview url: http://host.example.com/~username

also if we create the exlude for this user, it doesn't work.

any idea what this could be?
