### ISSUE TITLE
Disable microcache Only for some domains

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#378]
Hello, is possible disable microcache only for some domains?

I'm having some "session" problems in some domains and need to disable, but I do not want the whole server.

**Comment by fevangelou** [comment]
https://github.com/engintron/engintron/wiki/Excluding-specific-domains-or-domain-paths-from-micro-caching

**Comment by JorgeMarcelino-HS** [comment]
Hello, There are several, which one should I put down? see: http://pasteboard.co/qL5ARGA3N.png

**Comment by JorgeMarcelino-HS** [comment]
Hello @fevangelou There are several, which one should I put down?

**Comment by JorgeMarcelino-HS** [comment]
see: http://pasteboard.co/qL5ARGA3N.png

**Comment by fevangelou** [comment]
I've updated the wiki post. https://github.com/engintron/engintron/wiki/Excluding-specific-domains-or-domain-paths-from-micro-caching

You do the exclusions in your Custom Rules file now.

**Comment by JorgeMarcelino-HS** [comment]
@fevangelou Great!!! If I understood correctly, each domain I separate with a |?

example: "1domain.com|2domain.com|3domain.com"

its correct?

**Comment by fevangelou** [comment]
Yes.
