### ISSUE TITLE
nginx dead but subsys locked

### ISSUE THREAD

**Issue by rapidcloubr** [engintron/engintron#379]
Hello,

I use Engintron on multiple servers, and recently I noticed that it is stopping running on multiple servers at the same time!

When I enter the server and search for NGINX states, the following message is returned:

```
[Root @ server ~] # service nginx status
Nginx dead but subsys locked
```

Just run: service nginx restart that everything goes back to work.

This problem is complicating me with my clients, as I offer nginx as a solution.

Anyone know how to solve this?

**Comment by mikeatdesk** [comment]
This happens to me once every couple of weeks, too. Usually during the wee hours of the morning.

Happened this morning at 2:14am, killing every domain on the entire server.

Would love to see a fix.

**Comment by rapidcloubr** [comment]
Yes! The same with me! My Zabbix monitoring system sent the alert this morning at 1:40.

It needs a fix, as each server runs more than 1000 sites, all went offline.

**Comment by fevangelou** [comment]
Do you both have LetsEncrypt in AutoSSL configured? I think this may be causing issues as it brings up a server to verify certificates.

**Comment by rapidcloubr** [comment]
Yes, on some servers I have Lets Encrypt, and in others, AutoSSL.

**Comment by fevangelou** [comment]
@rapidcloubr That may be the issue. I'll investigate further.

**Comment by rapidcloubr** [comment]
A function that would solve this problem: After the NGINX stops, a script or setting will automatically restart it.

@fevangelou Please help us solve this problem, I have more than 15 servers running Engintron.

**Comment by kebirhost** [comment]
Hello,

We also have the same issue. After cpanel internal upgrades at the midnight all web sites go down. We tried to find a bash script to restart nginx but no work. 

I hope you (@fevangelou) find a solution. We do not want to remove nginx from our servers.

Thanks.

**Comment by kebirhost** [comment]
Hello Again,

We found a solution for this issue. Adding a bash script to monitor nginx.

pico /nginx-monitor.sh

`#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin
case "$(pidof nginx | wc -w)" in

0)  echo "Restarting nginx:"
    service nginx restart
    ;;
*)  echo "nginx already running"
    ;;
esac
`


Adding to crontab:
*/1 * * * * /nginx-monitor.sh >/dev/null 2>&1


I hope this is will fix the issue. We tried and it worked.

Thanks,
Melih

**Comment by rapidcloubr** [comment]
@kebirhost 

```
[root@server ~]# ./nginx-monitor.sh
./nginx-monitor.sh: line 5: syntax error near unexpected token `"Restarting nginx:"'
./nginx-monitor.sh: line 5: `echo "Restarting nginx:"'
```

```
[root@server ~]# vi nginx-monitor.sh
#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin
case "$(pidof nginx | wc -w)" in

echo "Restarting nginx:"
service nginx restart
;;
*) echo "nginx already running"
;;
esac
```

**Comment by kebirhost** [comment]
Hello,

You can download from:
http://dosyalar.kebirhost.net/nginx-monitor.sh

Thanks,
Melih

**Comment by rapidcloubr** [comment]
Thank You @kebirhost .

This will help while the official fix is not released.

**Comment by rapidcloubr** [comment]
@kebirhost I've put together a script to automate the process and help us.

This script asks if you want to install Engintron, if you respond Y, it will install Engintron and configure cron along with the monitor. If you answer N, the script will only install cron with the monitor.

[](https://rapidcloud.com.br/sh/nginx-install.sh)

I hope it helps! : D

**Comment by fevangelou** [comment]
Agree with @Azuka - this will be implemented in v1.8.1.

**Comment by kebirhost** [comment]
Hello,

There is no monitoring system yet. Nginx dead when cpanel run some updates and this is major issue.

Melih

**Comment by fevangelou** [comment]
Pushed for v1.8.2. It's not a major issue as less than 10 people have reported about it out of the thousands using it...

**Comment by kebirhost** [comment]
Hello,

They can fix this by themselves. This is the issue for who are using cpanel. You can be sure that, it is very important issue for hosting firms.

Thanks,
Melih

**Comment by neamtua** [comment]
I'm having this issue as well. Happened second time just 24 hours after the first time.
Any solutions to this?

**Comment by rapidcloubr** [comment]
I also have problems again, on all servers. It seems that something in cPanel causes nginx to die. Several servers were affected at the same time.

**Comment by kebirhost** [comment]
Hello,

Nginx is not working properly with cpanel. After cpanel update or some internal updates nginx starts to down. We were using nginx on our 35 servers as hosting services but every week it failed on midnigths. Now we remove nginx from all servers.

We are waiting for cpanel to add nginx in Easyapache. They do not give any importance to nginx usage.

Thanks,
Melih

**Comment by rapidcloubr** [comment]
@fevangelou , please help us.

**Comment by fevangelou** [comment]
Try this:
```
rm -f /var/lock/subsys/nginx
/engintron.sh res
```
