### ISSUE TITLE
New functions to new version

### ISSUE THREAD

**Issue by brinsleyparagao** [engintron/engintron#380]
If possible implement this functions on the new engintron version :

- Content-Security-Policy
- X-Frame-Options
- X-XSS-Protection
- X-Content-Type-Options

**Comment by ExoUNX** [comment]
If you need the features in the meantime you can set HTTP Headers through .htaccess and/or your back-end scripting language like PHP.

**Comment by tux-tn** [comment]
You can add those headers to custom_rules using engintron web interface

As an example:

`add_header X-Frame-Options SAMEORIGIN;`
`add_header X-Content-Type-Options nosniff;`
`add_header X-XSS-Protection "1; mode=block";`
`add_header Content-Security-Policy default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';`

**Comment by fevangelou** [comment]
Agree with @tux-tn - best to leave these out for now. E.g. someone may wish to have their site included via an iframe elsewhere (e.g. for a widget). If Engintron shipped with the headers by default, it would prevent such a choice.
