### ISSUE TITLE
When Google fetches our site they are hit with X-Cache-Status: EXPIRED

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#382]
When I am in Search Console and i fetch a webpage, they header response they always see is:

X-Cache-Status: EXPIRED

We are using Cloudflare with Engintron (Nginx/Apache)

Any ideas?

**Comment by fevangelou** [comment]
Engintron uses a 1 sec micro-cache for dynamic content by default.

So this is normal (again) for dynamic content, so it doesn't cause issues with user logins etc. It does not affect your performance though. It's a safe middle solution.

A high traffic site can have a very low TTL for its frontpage for example, but this is not a performance downside, it's a business decision.

Your static assets on the other hand (which must have a long expiration time) are handled differently. Caching headers varying from 1 hour to 60 days are sent along.

**Comment by WebSavvyGuy** [comment]
Sorry for reopening this but the X-Cache-Status: EXPIRED messages from the headers that Google is showing is from STATIC webpages, not dynamic.

**Comment by fevangelou** [comment]
Example URL to a static page?

**Comment by WebSavvyGuy** [comment]
@fevangelou 

Please check these three HTTP headers and let me know if its normal and what i have done is proper and why it reacts the way it does.

Using default Engintron set up (latest 1.8), .htaccess file as shown below, and default Cloudflare set up.

1) www. chat-avenue dot com

This main page is static and has HIT occasionally but EXPIRED most of the time.

It is set up with .htaccess rules as follows:

## EXPIRES CACHING ##
<IfModule mod_expires.c>
ExpiresActive On
ExpiresByType image/jpg "access plus 1 year"
ExpiresByType image/jpeg "access plus 1 year"
ExpiresByType image/gif "access plus 1 year"
ExpiresByType image/png "access plus 1 year"
ExpiresByType text/css "access plus 1 month"
ExpiresByType application/pdf "access plus 1 month"
ExpiresByType text/x-javascript "access plus 1 month"
ExpiresByType application/x-shockwave-flash "access plus 1 month"
ExpiresByType image/x-icon "access plus 1 year"
ExpiresDefault "access plus 1 day"
</IfModule>
## EXPIRES CACHING ##

With default (Standard) caching from Cloudflare which i believe is for image, css, etc files only (not HTML)

Just wondering why it says EXPIRED most of the time.    Shouldn't it say HIT all the time, at least based on my .HTACCESS rules.



2) www. chat-avenue dot com/images/chat-logo dot png

Same set up as above.

This one is showing both HIT from X-NGINX-Cache AND CF-CACHE so i am a bit confused as to why this one is always HIT and also why is it HIT in two places.  Is that normal or set up wrong?


3) Finally, this third resource which is on another server but same set up:

www.teen-chat dot org/images/teen-chat dot png


Why does this have MISS from X-NGINX-Cache and HIT from CF-Cache?


I am just trying to get to the bottom of how to set things up properly given my current set up of Engintron, Nginx/Apache and Cloudflare and why they all react differently.  Which one is correct, if any?

Please add some comments.  I am sure others have the same set up as myself and probably wondering also.

**Comment by fevangelou** [comment]
Let me "curl" that for you...

The first URL seems to have a short expiration time of 1 day.

```
curl -I https://www.chat-avenue.com/
HTTP/1.1 200 OK
Date: Wed, 22 Feb 2017 09:11:58 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=dc23385c492957086004476ba405f29c71487754717; expires=Thu, 22-Feb-18 09:11:57 GMT; path=/; domain=.chat-avenue.com; HttpOnly
Vary: Accept-Encoding
Last-Modified: Tue, 21 Feb 2017 03:30:06 GMT
Cache-Control: max-age=86400
Expires: Thu, 23 Feb 2017 09:11:57 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: EXPIRED
X-Server-Powered-By: Engintron
Server: cloudflare-nginx
CF-RAY: 3351504b7a225c8d-ATH
```

Engintron does not modify any cache control headers here and that is normal. CloudFlare also does not cache .html files (anything beyond CSS, JS and images to be precise), so it's normal too that there is no "CF-Cache-Status:" header from CloudFlare displayed.

The 2nd URL is properly enhanced by Nginx and has a long expiration time:
```
curl -I https://www.chat-avenue.com/images/chat-logo.png
HTTP/1.1 200 OK
Date: Wed, 22 Feb 2017 09:13:08 GMT
Content-Type: image/png
Content-Length: 4446
Connection: keep-alive
Set-Cookie: __cfduid=de2880f13c92a0573024d4703270c2f4d1487754788; expires=Thu, 22-Feb-18 09:13:08 GMT; path=/; domain=.chat-avenue.com; HttpOnly
Last-Modified: Mon, 20 Feb 2017 14:36:03 GMT
Expires: Sun, 23 Apr 2017 09:13:08 GMT
Cache-Control: public, max-age=5184000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: REVALIDATED
X-Server-Powered-By: Engintron
Pragma: public
Vary: Accept-Encoding
CF-Cache-Status: HIT
Accept-Ranges: bytes
Server: cloudflare-nginx
CF-RAY: 33515205b8fc5cc9-ATH
```

The last one is also properly cached:
```
curl -I https://www.teen-chat.org/images/teen-chat.png
HTTP/1.1 200 OK
Date: Wed, 22 Feb 2017 09:14:49 GMT
Content-Type: image/png
Content-Length: 17505
Connection: keep-alive
Set-Cookie: __cfduid=d4444ef5f7c18c8ea21795513fc19b69d1487754889; expires=Thu, 22-Feb-18 09:14:49 GMT; path=/; domain=.teen-chat.org; HttpOnly
Last-Modified: Mon, 20 Oct 2014 07:36:24 GMT
Expires: Sun, 23 Apr 2017 09:14:49 GMT
Cache-Control: public, max-age=5184000
X-Cache-Status: REVALIDATED
X-Server-Powered-By: Engintron
Pragma: public
Vary: Accept-Encoding
CF-Cache-Status: HIT
Accept-Ranges: bytes
Server: cloudflare-nginx
CF-RAY: 3351547cdae45cb7-ATH
```

Never mind that is says "X-Cache-Status: REVALIDATED". This is a snapshot of the Nginx headers when CloudFlare reads that static file and caches it. The right header to check in this case is "CF-Cache-Status: HIT". As the name indicates, it's a cache HIT. So caching is working correctly.

To wrap things up (as it's taken some time already to explain the same thing over and over), adjust your .htaccess file properly for HTTPS traffic and you should be OK. Static assets are already properly cached.
