### ISSUE TITLE
Bad gateway errors on sites that use an IP

### ISSUE THREAD

**Issue by dtayl20** [engintron/engintron#384]
Hi Guys

Just installed in WHM.  Because I use the server for development, all my sites point to an IP eg http://223.27.24.201/~graphic/ rather than a fully quallified domain.

All sites now get bad gateway errors.  

Just wondering if there is an easy fix for this?

Thanks.

**Comment by fevangelou** [comment]
See the wiki please: https://github.com/engintron/engintron/wiki/Engintron-&-(under-development)-domains-that-don't-yet-resolve-(point)-to-your-cPanel-server
