### ISSUE TITLE
Are Visitor IPs Getting Properly Logged On My Server?

### ISSUE THREAD

**Issue by adam-mazzei** [engintron/engintron#385]
Is this script working properly ???
[https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron](https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron)

The comparison on line 4 should not be ' != ' (Different)?
Because if it is different, the verdict is YES.
This would mean that the visitor IP is different from the IP of the server and would be properly written to the logs.

Has anyone else noticed this or am I completely mistaken?

**Comment by ImLuke954** [comment]
Are you seeing the real visitor IP or the server IP?

**Comment by adam-mazzei** [comment]
As I install on my server and access the page, the two IPs appear.
"Your real IP address is" = IP of the server
"Your server is IP address is" = my IP
And the verdict says NO

**Comment by arabgenius** [comment]
Hello
Iam too facing the same problem
I reinstall the engintron but still the same .. showing me the server ip
plz help

**Comment by ubidzz** [comment]
There 2 codes in that page to get the IPs

$realIP = trim(file_get_contents("http://ipecho.net/plain")); // this will always return your server IP
$loggedIP = $_SERVER["REMOTE_ADDR"]; // this will always return the user real IP

the problem is that using trim(file_get_contents("http://ipecho.net/plain")) to that page will show the server IP because your server is connection to that page and not the user so it sending back the server IP and not the user IP.

When you do a connection to a different website from a php page the user IP is not used and the server IP is. You can load this in your browser http://ipecho.net/plain and it will show your IP because your connecting to it and not the server. So remember any connections to a different page from a php code it wont use the user IP and will use the server IP because that is what is connecting to that page.

Your correct user IP is being logged in the nginx server.

**Comment by arabgenius** [comment]
what are you saying man @ubidzz .. do you think we are talking about php ?
we are talking about the revers proxy nginx
we know that $loggedIP = $_SERVER["REMOTE_ADDR"] weill return user real ip in php ... but not in engintron 
it did not .. yet it return shared ip of server

**Comment by adam-mazzei** [comment]
@arabgenius, to resolve this, I needed to uninstall and reinstall Engintron. After that, $_SERVER ['REMOTE_ADDR'] started to display my IP.
Obs.:Using the Re-Install tool did not work for me. 

@ubidzz  I believe the error in this script is in comparison, because the $realIP variable will always be the Server IP and the var $loggedIP is the IP of the person who is accessing the page. That is, the verdict should be YES, when the variables are different.

`$realIP = trim(file_get_contents("http://ipecho.net/plain"));
$loggedIP = $_SERVER["REMOTE_ADDR"];
$verdict = ($realIP==$loggedIP) ? '<h2 style="color:green;">Verdict: YES</h2>' : '<h2 style="color:red;">Verdict: NO</h2>';`

**Comment by timeassistant** [comment]
It could be a previous issue that used to exist where the mod_Remoteip module didnt install correctly, usually you can just click the reinstall button on the engintron cp 

this issue was referenced here in the past - https://github.com/engintron/engintron/issues/168

**Comment by adam-mazzei** [comment]
Yes I understand.
On my server everything is working properly now.
ModSec and Apache Logs take the visitor's IP correctly.
$ _SERVER ['REMOTE_ADDR'] = Visitor Ip.

But to solve this, I needed to uninstall Engintron and Install again.
Using Reinstall button in the Engintron CP, did not work for me.

But the question I raised initially in this thread is about a possible error in the @fevangelou script, which is in the WIKI.
[Check if visitor IPs are properly logged in Apache after installing Engintron](https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron)

The script assumes that the variable $realIP will bring the IP of the visitor, but this is impossible because this code `trim(file_get_contents("http://ipecho.net/plain"));` will return the IP of the server and not the Visitor IP.

Look at this part of the script
$realIP = trim(file_get_contents("http://ipecho.net/plain"));
Your real IP address is $realIP

**Comment by arabgenius** [comment]
I removed engintron and installed it again via ssh
...
am not relying on the script to tell me my ip
I know that verdict script is wrong

**Comment by fevangelou** [comment]
The script works fine. The check to ipecho.net will report the server's IP. The next bit will report the IP that Nginx passes on to Apache. If they match, it means Apache gets the server's IP and the related module for Apache is either not properly installed or the Apache configuration was changed.

**Comment by arabgenius** [comment]
@fevangelou do you mean that if my server ip is 123.123.123.123
so those vars should be like this ?
$realIP = 123.123.123.123
$loggedIP =123.123.123.123

**Comment by fevangelou** [comment]
If Nginx passes the correct user IP (aka yours, visiting that page), then the second variable should be your IP. If it's not and you get the same IP for both, it means there's a problem. Re-install Engintron to resolve it.

**Comment by adam-mazzei** [comment]
> If it's not and you get the same IP for both, it means there's a problem

@fevangelou , But that's why I opened this issue.

The IF comparison is wrong.
If the IPs are different, the VEREDICT should be YES.
If the IPs are EQUAL, the VEREDICT should be NO.

The script is wrong.

No one is seeing this ??? Look at the snippet below
`$verdict = ($realIP==$loggedIP) ? 'Verdict: YES' : 'Verdict: NO';`

**Comment by fevangelou** [comment]
Fixed.
