### ISSUE TITLE
Single SSL Website on server -> Use Engintron for https

### ISSUE THREAD

**Issue by inventivo** [engintron/engintron#386]
Whch changes do I have to do to the defautl.conf to have engintron working with https for a single domain / IP which is located on a dedicated server?

I had something like:

listen 443 ssl;
    server_name localhost;
    ssl on;
    ssl_certificate ###mycertificate###;
    ssl_certificate_key ###mykey###;

and changed set $PROXY_TO_PORT 8080; to set $PROXY_TO_PORT 8443;
And have set apache SSL Port to 8443.

But this didn't work. Am I missing something?

**Comment by ubidzz** [comment]
I posted how to add SSL website to nginx at https://github.com/engintron/engintron/issues/106#issuecomment-279130833 it will give you the directions on how to install a website SSL on nginx.

**Comment by inventivo** [comment]
I will give ot a try, thank you.

**Comment by inventivo** [comment]
This worked but I keep getting an ssl chain issue. The cert is installed properly via WHM.

**Comment by inventivo** [comment]
#106 Solved here

**Comment by fevangelou** [comment]
v1.8.0 is now available. It resolves any issues with HTTPS traffic.
