### ISSUE TITLE
Static assets showing "Server: Apache"

### ISSUE THREAD

**Issue by jon-evm** [engintron/engintron#387]
Sorry if this is wrong place to ask this question but, just installed latest version on an up to date cPanel server CentOS7 and am looking at one of my Wordpress sites in Firebug and all the static assets show Server: "Apache" and not Server: "nginx".

**Comment by ubidzz** [comment]
Is the website running SSL? iIf not check the apache port to see if it is 80 or 8080.

You can check it by going to WHM > Tweak Settings -> System and change Apache non-SSL IP/port to 8080.

The nginx server use port 80 then it passes it to the httpd port of 8080. So if your httpd port is 80 that means it using the httpd = apache and not nginx.

**Comment by jon-evm** [comment]
Some sites are using SSL and some are not. The ones non-SSL sites show Server: "nginx".

netstat -nalpt | grep 'nginx' returned:
`tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      25384/nginx: master`

netstat -nalpt | grep 'httpd' returned: 
`tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      25215/httpd`
`tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      25215/httpd`

Apache non-SSL IP/port is already set to 8080.
Apache SSL port is set to 443.

**Comment by ubidzz** [comment]
As of right now the nginx server only handles non-SSL sites and if you want it to also handle SSL you will have to manually add the each websites SSL.conf to the nginx server. 

You can find the directions at https://github.com/engintron/engintron/issues/106#issuecomment-279130833 on how to add the SSL.conf files.

**Comment by fevangelou** [comment]
Engintron v1.8.0 is now released so both HTTP & HTTPS traffic is passed through Nginx.
