### ISSUE TITLE
engintron doesn't show real ip

### ISSUE THREAD

**Issue by arabgenius** [engintron/engintron#388]
Hello
Am using EA3 .. Latest WHM
I had tried all the suggested codes and changes in this forum to show the correct ip address of the client
but all leads to big fail

```
RemoteIPHeader X-Real-IP
#RemoteIPHeader X-Forwarded-For
#RemoteIPHeader X-Client-IP
#RemoteIPHeader X-Remote-Addr
```
all shows server ip insted of client ip
and I did change logformat %h to %a ... no benefit

and this is my **Verdict**
http://www.abqariservice.com/try.php
plz help

**Comment by ubidzz** [comment]
Not sure what your asking but i do see my real IP in that page.
**Your server logged IP address is**
show my IP

It just looks like that page code is backwards if it is using PHP coding in that page use these codes to get the IPs.

Gets the user IP
> $_SERVER['REMOTE_ADDR']

Gets the server IP
> $_SERVER['SERVER_ADDR']

**Comment by arabgenius** [comment]
@ubidzz am sorry
what didn't you understand ?
what Iam asking is how to show my real ip using engintron?
this variable $_SERVER["REMOTE_ADDR"] should show me my ip but it shows server share ip

**Comment by ubidzz** [comment]
I tested $_SERVER["REMOTE_ADDR"] on my nginx and it is working correctly so i have no idea why it not working for you.

**Comment by timeassistant** [comment]
There was an issue in the past where the mod_remoteip module didnt pass the visitor address correctly


Try click the reinstall engintron link that used to correct it for me. 

further details can be found in this older issue

#https://github.com/engintron/engintron/issues/168

**Comment by fevangelou** [comment]
Agree with @timeassistant - I'll add an option in v1.8.1 to be able to re-apply these rules without the need to do a full re-installation/update of Engintron.
