### ISSUE TITLE
Engintron not sending Vary: Accept-Encoding header

### ISSUE THREAD

**Issue by CrowdForge** [engintron/engintron#389]
Just using the out of the box config I find that Engintron is not sending Vary: Accept-Encoding, although looking at the nginx.conf it seems it should be.  Am I the only one experiencing this problem?

**Comment by dannymichel** [comment]
Same problem

**Comment by fevangelou** [comment]
Check the domain with curl at both ports 80 and 8080 (Nginx & Apache respectively). Paste back the responses you get. The command to run from a terminal is "curl -I www.your-domain.tld".

**Comment by CrowdForge** [comment]
Hmmm.  Well when I do that test, I get Vary: Accept-Encoding

Server: nginx
Date: Sun, 19 Feb 2017 19:17:33 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
**Vary: Accept-Encoding**
Link: <http://www.deathnerve.com/wp-json/>; rel="https://api.w.org/"
Expires: Sun, 19 Feb 2017 20:17:33 GMT
Pragma: public
Cache-Control: max-age=3600, public
Last-Modified: Sun, 19 Feb 2017 19:17:33 GMT
ETag: "8935190f175c717833530ca30699af61"
X-Cache-Status: MISS
X-Server-Powered-By: Engintron

On a single file that is being reported by tools.pingdom.com as not having the header, I get it twice:

Server: nginx
Date: Sun, 19 Feb 2017 19:18:32 GMT
Content-Type: text/css
Content-Length: 119920
Connection: keep-alive
**Vary: Accept-Encoding**
Last-Modified: Sat, 28 Jan 2017 13:15:12 GMT
ETag: "1d470-547275f511800"
Expires: Tue, 21 Mar 2017 19:18:32 GMT
Cache-Control: max-age=2592000
X-Cache-Status: MISS
X-Server-Powered-By: Engintron
Pragma: public
Cache-Control: public
**Vary: Accept-Encoding**
Accept-Ranges: bytes

Pingdom is reporting both of these as NOT having Vary: Accept-Encoding.  So maybe it's a pingdom issue?

**Comment by fevangelou** [comment]
Yeap, for sure. "curl" is the golden rule to check that and it's usually available in your cPanel server already.

By the way, it seems you're using an older release of Engintron. v1.8.0 is now available to download :)

**Comment by savoures** [comment]
Hello 
I have the same problem
