### ISSUE TITLE
Ignore domain upon instalation

### ISSUE THREAD

**Issue by ruicruzpt** [engintron/engintron#390]
Hello,

Is there a way to ignore engintron in one particular domain?
I read that this was plannet, but not sure if this was implemented yet.

Thanks,
R.

**Comment by fevangelou** [comment]
You can simply have Nginx pass traffic directly to Apache without caching the output or modifying any headers. You can find such examples in the "custom rules" file. In your case, it would be something like:

```
if ($SITE_URI ~* "domain-to-exclude.com") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
    set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}
```

It's impossible to disable Nginx completely as you can't have different services (Nginx and Apache) bind to the same port at the same time, even if they respond on different domains.
