### ISSUE TITLE
ModSecurity record server ip rather than real ip

### ISSUE THREAD

**Issue by arabgenius** [engintron/engintron#392]
Hello
Am using EA3 .. Latest WHM
after a lot of modification and installing/uninstalling ..
I got engintron to work $_SERVER["REMOTE_ADDR"] to show client ip
yet .. in ModSecurity . it still shows server shared ip?

what should I do ?

**Comment by thiagomgo** [comment]
+1

**Comment by timeassistant** [comment]
I used to have this problem now and again. Sometimes it was a simple case of clicking the reinstall engintron option.

I cant remember exactly what it is but, it was something to do with a mod_ip module not installing / running correctly.

try the reinstall option it should hopefully correct your problem - alternatively try search through previous issues as I'm certain a solution was posted in another thread in the past

**Comment by timeassistant** [comment]
Just found the issue I referenced      https://github.com/engintron/engintron/issues/168

**Comment by arabgenius** [comment]
@timeassistant I did every thing
and am sure that remoteip is working so nice .. but modsec shows server ip rather than client ip

**Comment by fevangelou** [comment]
Seen this? https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron

**Comment by arabgenius** [comment]
@fevangelou 
Ok I had enough 
I reinstalled it again via app "Update (or re-install) Engintron [Nginx mainline]"
and did not fix the problem
every thing is fine but not the verdict script and not modsec 
both are wrong

here is the log .. plz fix it for me 
[update_log.zip](https://github.com/engintron/engintron/files/786195/update_log.zip)

**Comment by arabgenius** [comment]
@fevangelou 
 sorry .. here is the script
http://www.abqariservice.com/try.php

**Comment by fevangelou** [comment]
This is beyond the scope of the free support I provide here, as all
possible ways to fix your issue have been exhausted.

I would have to login to your server and see what's going on. And such a
task falls under commercial support only and charged by the hour. If you
want such support contact engintron at gmail dot com for further
instructions.

**Comment by arabgenius** [comment]
Am gonna wait .. my budget is low already
if you want to login my server then just tell me
you will gain good knowledge of this problem which will help you develop engintron

**Comment by fevangelou** [comment]
mod_security has nothing to do with Engintron really. Your sites are served
fast but users IPs are not recorded properly in mod_security. That seems
like a configuration issue with the latter, so it's hardly any knowledge in
developing Engintron.

**Comment by arabgenius** [comment]
maybe not modsec
what about verdict script
http://www.abqariservice.com/try.php
