### ISSUE TITLE
Engintron nginx in cloudlinux installation problem

### ISSUE THREAD

**Issue by mcl21us** [engintron/engintron#395]
Installing : nginx-1.11.10-1.el6.ngx.x86_64                               1/1 
warning: /etc/logrotate.d/nginx created as /etc/logrotate.d/nginx.rpmnew
warning: /etc/nginx/conf.d/default.conf created as /etc/nginx/conf.d/default.conf.rpmnew
warning: /etc/nginx/mime.types created as /etc/nginx/mime.types.rpmnew
error: unpacking of archive failed on file /etc/nginx/modules: cpio: rename

  Verifying  : nginx-1.11.10-1.el6.ngx.x86_64                               1/1 

Failed:
  nginx.x86_64 0:1.11.10-1.el6.ngx                                              

Complete!

**Comment by fevangelou** [comment]
Explain more please.

**Comment by mcl21us** [comment]
Hi fevangelou, 

No worries i already resolve it it :) the target nginx source was not found

See the error bellow during installation

Downloading Packages:
http://nginx.org/packages/centos/6/x86_64/RPMS/nginx-1.11.10-1.el6.ngx.x86_64.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623
If above article doesn't help to resolve this issue please open a ticket with CloudLinux Support.

Error Downloading Packages:
  nginx-1.11.10-1.el6.ngx.x86_64: failure: RPMS/nginx-1.11.10-1.el6.ngx.x86_64.rpm from nginx: [Errno 256] No more mirrors to try.

/bin/cp: cannot create regular file `/etc/nginx/conf.d/': Is a directory
error reading information on service nginx: No such file or directory

**Comment by fevangelou** [comment]
That's weird. It seems for CentOS 6, the repo lists only up to v1.10.x. See here: http://nginx.org/packages/centos/6/x86_64/RPMS/
