### ISSUE TITLE
wrong path /var/cpanel/ssl/cpanel/mycpanel.pem - 1.8.0

### ISSUE THREAD

**Issue by KristijanL** [engintron/engintron#397]
Hi,

after upgrading to 1.8.0 version it creates a file /etc/nginx/conf.d/default_https.conf with wrong paths
ssl_certificate /var/cpanel/ssl/cpanel/mycpanel.pem;
ssl_certificate_key /var/cpanel/ssl/cpanel/mycpanel.pem;
ssl_trusted_certificate /var/cpanel/ssl/cpanel/mycpanel.pem;

on my Cloudlinux 7.3 its
/var/cpanel/ssl/cpanel/cpanel.pem;

Kristijan

**Comment by fevangelou** [comment]
Thanks for the tip, I'll add an exception and push to 1.8.0. I'll notify
you again to update Engintron.

**Comment by fevangelou** [comment]
Fixed in the latest build. Upgrade please.
