### ISSUE TITLE
New Version Problem

### ISSUE THREAD

**Issue by kakitube** [engintron/engintron#398]
Hello engintron

after i updated to new version i got error cant start nginx 

this is error log i got

=exited, status=1/FAILURE)
 Main PID: 38299 (code=exited, status=0/SUCCESS)

Feb 18 03:59:15 ns12.webmalaya.com.my systemd[1]: Starting nginx - high perfo...
Feb 18 03:59:15 ns12.webmalaya.com.my nginx[38463]: nginx: [emerg] BIO_new_fi...
Feb 18 03:59:15 ns12.webmalaya.com.my nginx[38463]: nginx: configuration file...
Feb 18 03:59:15 ns12.webmalaya.com.my systemd[1]: nginx.service: control proc...
Feb 18 03:59:15 ns12.webmalaya.com.my systemd[1]: Failed to start nginx - hig...
Feb 18 03:59:15 ns12.webmalaya.com.my systemd[1]: Unit nginx.service entered ...
Feb 18 03:59:15 ns12.webmalaya.com.my systemd[1]: nginx.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@ns12 /]# /bin/systemctl restart  nginx.service
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

Any solution for this issue?

Thanks

**Comment by jcatello** [comment]
You need to post the actual error:

journalctl -xe

**Comment by fevangelou** [comment]
What does "nginx -t" output in the terminal, when logged in as root user?

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by fevangelou** [comment]
I see an error starting with "nginx: [emerg] BIO_new_fi..." in the (incomplete) log you provide. Check if you had another Nginx for cPanel plugin already installed. If that's the case, remove that plugin and re-install Engintron.
