### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ImLuke954** [engintron/engintron#400]
After updating to engintron 1.8, I am getting 502 Bad gateway error in all the domains. Domain IP is specified in the custom rules yet it is throwing 502 error. I have reverted to engintron 1.7.3 now.
My config : Cloudlinux 6.8 + WHM 62

**Comment by KristijanL** [comment]
Same here
EA4, Cloudlinux 7.3

**Comment by kakitube** [comment]
yup same 
Centos 7

**Comment by jcatello** [comment]
Same

**Comment by jollysolutions** [comment]
Same here Centos 6  WHM 62 EA3

**Comment by fevangelou** [comment]
For one, make sure open_basedir is not restricted in your system.

Secondly, update to v1.8.0 build 20170219.

Let me know.

**Comment by ImLuke954** [comment]
Build 20170217 solved the problem.

But curl command is not able to validate the certificate. I am getting this error:

[root@xyz ~]# curl -I https://www.domain.com
curl: (60) Peer certificate cannot be authenticated with known CA certificates
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by ImLuke954** [comment]
Build 20170217 solved the problem.

But curl command is not able to authentic the certificate. Not getting any warning in Firefox and Chrome though.

> [root@xyz ~]# curl -I https://www.mydomain.com
curl: (60) Peer certificate cannot be authenticated with known CA certificates
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, the certificate verification probably failed due to a
problem with the certificate (it might be expired, or the name might
not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
the -k (or --insecure) option.

**Comment by fevangelou** [comment]
Do you mind sharing the actual URL please? Break the format like "www dot domain dot tld" if you don't want Google to crawl it here. ;)

**Comment by WebSavvyGuy** [comment]
Same here all domains 502 now (using Cloudflare, Centos 7)

Is the 20170217 version known as "Update (or re-install) Engintron [Nginx mainline] ?

**Comment by ImLuke954** [comment]
@fevangelou I am sorry can't reveal the domain publicly here but can PM you. Is there any way to PM in github?

@WebSavvyGuy Do this:

> Update (or re-install) Engintron [Nginx mainline] > Restart Apache & Nginx > Purge cache & temp files

**Comment by WebSavvyGuy** [comment]
Thanks i will try that now.  This is very disappointing.

**Comment by ImLuke954** [comment]
@WebSavvyGuy Let us know if it solves the 502 error. It worked for me.

**Comment by WebSavvyGuy** [comment]
Yes, i just did that and now all the domains are working.  (i didnt need to restart Apache/Nginx or Purge the cache files but i did that anyways)

Do i need to open ports 8080,8443 as per instructions if im running csf?   TCP in? TCP out?

Thanks a lot!

**Comment by fevangelou** [comment]
@WebSavvyGuy Yes.

@all Please update once more as I have resolved some CA chain related issues and also enabled OCSP stapling. Double bonus :)

**Comment by ImLuke954** [comment]
The latest build is good to go. All problem solved. However Apache died after the update so I had to manually restart apache.

**Comment by jollysolutions** [comment]
Im getting an Chain issues Incorrect order now

**Comment by fevangelou** [comment]
@jollysolutions Can you provide me with an actual URL please? You may be seeing a cached response in your browser. Alternatively, clear Nginx's caches from the Engintron WHM app & restart Apache/Nginx, then test the domain in question using: https://www.ssllabs.com/ssltest/

**Comment by jollysolutions** [comment]
flushed caches etc and tested on ssllabs where is where the error showed

url is

ds dot ukna dot org

**Comment by fevangelou** [comment]
It doesn't seem to be an issue though: https://www.ssllabs.com/ssltest/analyze.html?d=ds.ukna.org&hideResults=on (gets a Grade A) >> http://jmp.sh/5oXvK60

It also loads fine on both desktop and mobile browsers.

**Comment by jollysolutions** [comment]
if you scroll down that page. it then shows the problem


Additional Certificates (if supplied)
Certificates provided	3 (4156 bytes)
Chain issues	Incorrect order

**Comment by ImLuke954** [comment]
I am getting the same issue with one of my domains using Comodo Wildcard Certificate. But no such issues with domains using Lets Encrypt Auto SSL
> Im getting an Chain issues Incorrect order now

**Comment by fevangelou** [comment]
I noticed that as well. However SSL Labs still gives a Grade A. Can you please check yours @ImLuke954?

**Comment by TONTRI-TECH** [comment]
Hello,

@fevangelou  I am truly sorry for that 3rd party installation thing on #403 ... 

But, php **open_basedir** Protection in WHM was turned off from the day I installed cPanel/WHM - http://jmp.sh/sqboxwa

However, I am waiting for the confirmation on the SSL issue @ImLuke954  mentioned ... 

Thanks for the update.

**Comment by WebSavvyGuy** [comment]
Hi

I am using Cloudflare issued SSL certificates as opposed to Cpanel free ones.   Will this be an issue?  Is there anything i need to do on Cpanels end like shut off their auto SSL's, etc?

For the SSL Labs test i am getting an A grade.  Having said that i just notice a slight delay in load times for our sites now.

Thanks

**Comment by ImLuke954** [comment]
@fevangelou  Apparently engintron is putting the "Comodo Trust Certificate" ahead of the "Domain Valiadtion Certificate". That's why SSLTest is showing chain issue incorrect issue.
1. In apache, DV Cert ahead of Trust Cert - No chain issue - http://prnt.sc/eayj7m
2. In nginx, Trust Cert ahead of DV Cert - Incorrect Order - http://prnt.sc/eayj56

**Comment by fevangelou** [comment]
@WebSavvyGuy No, you're cool. It's also best to select "Flexible SSL" in CF's crypto settings.

@ImLuke954 Each "fullchain" certificate is a concatenation of the issued certificate file and a generic CA (certificate authority) certificate bundle. The certificate file goes first and the bundle file 2nd.

https://support.comodo.com/index.php?/Knowledgebase/Article/View/1091/0/certificate-installation--nginx

Now, why this craps out on SSL Labs tool and still get a Grade A is beyond me. Unless you see a problem in any browser, I'd recommend you just ignore it.

**Comment by ImLuke954** [comment]
The issue can be solved by adding the DV Cert above the Trust Cert in the Certificate Bundle Field during installation of the SSL

**Comment by fevangelou** [comment]
I'll stick with what Comodo says. There is no further issue to discuss here. SSL Labs gives a grade A. The incorrect order doesn't mean there's an actual problem.
