### ISSUE TITLE
Cannot restart Nginx after upgrading to Engintron v1.80 

### ISSUE THREAD

**Issue by gbassoc** [engintron/engintron#402]
Hi
I upgraded Engintron to v 1.80, now I am unable to restart Nginx, the error message is below
nginx: [emerg] BIO_new_file("/var/cpanel/ssl/cpanel/mycpanel.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/cpanel/mycpanel.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

For the time being I have disable Engintron until youcam suggest how to fix this

**Comment by jcatello** [comment]
The location is wrong in /etc/nginx/conf.d/default_https.conf

however that is the correct path for me so not sure why yours is different.

Try doing:

`# find /var/cpanel/ -type f -name mycpanel.pem`

then update the path in /etc/nginx/conf.d/default_https.conf

and restart nginx

`# service nginx restart`

**Comment by jcatello** [comment]
Actually, it looks like newer versions its:

/var/cpanel/ssl/cpanel/cpanel.pem

Does that exist for you?

**Comment by fevangelou** [comment]
I've update v1.8.0 to build 20170219. Just update/re-install from within the WHM app (or terminal).

Let me know.
