### ISSUE TITLE
open_basedir restriction causes issues in v1.8.0 Bug

### ISSUE THREAD

**Issue by TONTRI-TECH** [engintron/engintron#403]
Hello,

I saw people are talking about the new version issue. I wasn't able to load websites over SSL and it was showing connection refused. After reading about few issues I opened the new HTTPS NGINX CONF file and replaced the .pem path with a valid one and then restarted NGINX and other services too.

But it started showing 502 Bad Gateway instead of previous error connection refused. However, I think this is not with the .pem path only, there are some other issues too.

I love Engintron a lot and it's previous version stability just didn't amazed but also amazed whoever used it. I hope it will be fixed very soon or any temporary solution will be great too.

Thanks.

**Comment by TONTRI-TECH** [comment]
Hello,

I have managed to find a temporary fix you guys may want to try. Follow these steps:

- Take backup of your custom configurations
- Uninstall Engintron using guide - https://github.com/engintron/engintron/wiki/03.-Uninstalling
- Make sure you don't have engintron.sh in /
- Then run below command to install Engintron Version 1.7.3

cd /; rm -f engintron.sh; wget --no-check-certificate http://185.166.238.238/engintron.sh; bash engintron.sh install

- Once installed you will have Engintron Version 1.7.3 though it will show 1.8.0 within WHM.
- After that everything should work fine like Engintron Version 1.7.3

This worked for me ... I am using CentOS & cPanel/WHM latest production. I can't guarantee if it will work for you or not.

Thanks.

**Comment by Silviu-LS** [comment]
On my side seems the script can't generate vhosts.

/etc/nginx/utilities/https_vhosts.php

Do you have any issues with this ?

**Comment by TONTRI-TECH** [comment]
Hello,

I am not sure about the bug as my websites have 301 permanent redirects to HTTPS so, I just saw that it's not loading and later on saw few issues thread which was telling that .pem path is incorrect. 

and they were right, the path was incorrect but even after changing it didn't solved and started 502 Bad Gateway which may be an issue you mentioned (issues with vhosts).

Better wait for Engintron developers to reply about these issues. But honestly, I didn't expect these major bugs from Engintron though 1.8.0 is going to be cool :)

Thanks.

**Comment by Silviu-LS** [comment]
Hi ,

Could you please check if /etc/nginx/conf.d/default_https.conf exists on your side ?

**Comment by Silviu-LS** [comment]
Hi,

Seems I have find the problem 👍 

file_get_contents(): open_basedir restriction in effect.

**Comment by TONTRI-TECH** [comment]
Hello,

It doesn't exist as I am running Version 1.7.3 over Version 1.8.0 skin.

it's glad to know that you have solved your problem. 👍

**Comment by Silviu-LS** [comment]
I think you got the same issue , not fixed yet thinking on a solution.

**Comment by TONTRI-TECH** [comment]
Ok, don't forget to update if you are able to fix the issue.

**Comment by fevangelou** [comment]
Enable open_basedir as it's 2017 and upgrade to today's build of Engintron.

I would refrain from installing Engintron from a 3rd party server. You've been warned.
