### ISSUE TITLE
Version 1.8.0 Bug - Can't process vhosts

### ISSUE THREAD

**Issue by Silviu-LS** [engintron/engintron#404]
Hi,

After upgrading to Version 1.8.0 I see that the script ( /etc/nginx/utilities/https_vhosts.php ) can't generate vhosts. The first reason was php open_basedir and the second is the script that reads the SSL paths.
...
            'SSLCertificateFile' => $certfile[1],
            'SSLCertificateKeyFile' => $certkey[1],
            'SSLCACertificateFile' => $certbundle[1]

Is generating /etc/nginx/conf.d/default_https.conf without vhosts , just the main hostname.

After I manually added the vhosts , it's working fine , but the function needs to be fixed.

**Comment by fevangelou** [comment]
If it's not creating vhosts it means it can't read your Apache configuration. What's the location of your httpd.conf file?

**Comment by Citizen-K** [comment]
Had the same problem. Temporarily disabled the "PHP open_basedir Tweak" settings in security settings and https.conf built as intended after that.

**Comment by fevangelou** [comment]
You must leave it enabled, as the vhosts are regularly auto-updated.
