### ISSUE TITLE
SSL revoked on Mac Sierra

### ISSUE THREAD

**Issue by mikeatdesk** [engintron/engintron#405]
I went to some of my domains this morning from a brand new laptop, and find that their SSL certs are being rejected as issued by an untrusted authority.

When I disable Engintron, everything works properly.
When I re-enable it, I get untrusted connections again.

When googling this, it looks to be an issue with how the intermediate cert is being served in conjunction with Engintron.

Would like a fix, as this looks to be a fairly major issue.

**Comment by fevangelou** [comment]
Can you provide an example URL please?

**Comment by mikeatdesk** [comment]
https://www.mikejandreau.com/

Engintron is enabled right now, so you can see the error.

**Comment by mikeatdesk** [comment]
Even more strange, it seems to only be browsers on 10.12.2. 

My iPhone and iPad aren't having any issues with the veers on any of my domains.

**Comment by fevangelou** [comment]
Working just fine on my end. See: http://jmp.sh/bZO6Vt1

Your issue is probably related to this: https://support.apple.com/kb/PH18677?locale=en_GB

**Comment by tux-tn** [comment]
As i said in #394 the issue is related to the fact that engintron is not sending out the certificate chain. Browsers that haven't seen the intermediate signing certificate in the past will complain about certificate error.
It's not working on my Chrome browser for android (Freshly installed, never used): https://imgur.com/a/DzJyE

@fevangelou you should really consider bundling certificates, may be a solution like the one i am using here: https://github.com/engintron/engintron/issues/106#issuecomment-279740556 will do the trick

**Comment by mikeatdesk** [comment]
I'm glad it's working for you. But it's not for me in my testing so I'll have to disable Engintron for now and hope a future version fixes this.

**Comment by fevangelou** [comment]
@tux-tn You're right about mobile browsers. I'll sort it out.

@mikeatdesk Your issue remains related to your macOS version or Safari version. It's a know issue as I pointed out. At least Chrome, Firefox & IE that make up 90%+ of browser usage aren't affected.

**Comment by mikeatdesk** [comment]
@fevangelou 100% of the browsers on my Mac show the same untrusted authority error. Firefox, Safari and Chrome. All of them, across all of my domains.

With Engintron turned off, there is no error.

Ergo, it's Engintron's issue and fault. Not my Mac or my browser or my certs or my server.

**Comment by fevangelou** [comment]
@mikeatdesk Mike, honestly, it's a macOS issue. Keep it in mind if you face this issue again in the future.

In the meantime update Engintron to get the certificate fixes I mention below.

@tux-tn I implemented the certificate concatenation in the HTTPS vhosts generation. I think this will now allow me to also enable OCSP Stapling, but I need to verify first.

Now sites get a grade A, e.g. https://www.ssllabs.com/ssltest/analyze.html?d=www.centiva.gr&hideResults=on&latest

**Comment by fevangelou** [comment]
@tux-tn Enabled OCSP stapling as well, example: https://www.ssllabs.com/ssltest/analyze.html?d=www.sweetsalty.gr&hideResults=on

Upgrade/re-install to get the updates please.

**Comment by tux-tn** [comment]
@fevangelou the `ssl_trusted_certificate` directive is not needed for OCSP stapling? i am seeing it in many documentations despite the fact that i have two servers with OCSP stapling status ok, who are using only the same directives you've added in your last commit

**Comment by fevangelou** [comment]
@tux-tn It's needed as a reference in Nginx, but it is just the same file as the main certificate file (in this case the concatenated Apache cert file and the CA bundle).

**Comment by fevangelou** [comment]
I'm considering this resolved now. Again @mikeatdesk just upgrade Engintron to have the CA chain issues resolved.
