### ISSUE TITLE
X-Cache-Status: EXPIRED Showing up in Google Search Console under Fetching

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#406]
Hi 

Sorry for bringing this issue up again but:

When I am in Search Console and i fetch a webpage, the header response they always see is:

X-Cache-Status: EXPIRED

We are using Cloudflare with Engintron (Nginx/Apache).    Do not have anything in our .htaccess.

You mentioned this is normal for dynamic content, however, where this is showing is on pages that do not have dynamic content and all STATIC content.

Before Engintron, I was used to always seeing X-Cache_Status as HIT and I never saw EXPIRED before.

**Comment by WebSavvyGuy** [comment]
Actually now this is my response header, it doesnt even have X-Cache-Status anymore:


HTTP/1.1 200 OK => 
Date => Mon, 20 Feb 2017 02:43:14 GMT
Content-Type => text/html; charset=UTF-8
Connection => close
Set-Cookie => __cfduid=d4501a3d99fd0497e52177bf50a1114ec1487558594; expires=Tue, 20-Feb-18 02:43:14 GMT; path=/; domain=.mydomain.com; HttpOnly
Vary => Accept-Encoding
Last-Modified => Sun, 19 Feb 2017 11:27:55 GMT
X-Server-Powered-By => Engintron
Server => cloudflare-nginx
CF-RAY => 333e9c1f0e9c1894-EWR





Not sure what I am doing wrong, hope someone can help here.

**Comment by fevangelou** [comment]
Gotta give me a URL. Can't help you otherwise.

**Comment by WebSavvyGuy** [comment]
www.chat-avenue.com

**Comment by WebSavvyGuy** [comment]
@fevangelou www. chat-avenue dot com

**Comment by fevangelou** [comment]
This is what curl outputs:

```
curl -I (you know the URL)

HTTP/1.1 200 OK
Date: Mon, 20 Feb 2017 10:26:45 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d4d6c2feea0dcfdb44dba255c9de852651487586405; expires=Tue, 20-Feb-18 10:26:45 GMT; path=/; domain=.chat-avenue.com; HttpOnly
Vary: Accept-Encoding
Last-Modified: Sun, 19 Feb 2017 11:27:55 GMT
X-Server-Powered-By: Engintron
CF-Cache-Status: HIT
Expires: Mon, 20 Feb 2017 14:26:45 GMT
Cache-Control: public, max-age=14400
Server: cloudflare-nginx
CF-RAY: 3341431779bf5ca5-ATH
```

**Comment by WebSavvyGuy** [comment]
@fevangelou Sorry i updated my comment after you replied.  I set CF to cache everything to get the hIT but if i turn that rule off i dont even get an X-Cache-Status at all.   I just turned it off so you can see.

**Comment by fevangelou** [comment]
All is working well. Apache or perhaps CF already set the right cache-control headers. If you wish to override this, you can simply be done within the "proxy_params_dynamic" file. At the bottom you'll see a line:

```
#expires                $EXPIRES_FOR_DYNAMIC;
```

Change it to:
```
expires                $EXPIRES_FOR_DYNAMIC;
```

Then in your "custom rules" file, add a domain exception for specific caching.

```
if ($host ~ "example.com") {
    set $EXPIRES_FOR_DYNAMIC 5m;
}
```
This will "tell" browsers to cache the output for 5 mins as this option will override Cache-Control & Expires headers. Simple.

Remember to restart Apache/Nginx.

**Comment by WebSavvyGuy** [comment]
@fevangelou Ok i can try that but please keep in mind this site is mostly static, not dynamic (except the forums part)

**Comment by fevangelou** [comment]
Engintron cannot enforce a Cache-Control by default for a ton of reasons. The most important ones though are:
a) you're using your own Cache-Control headers in your app, so it would be a dick move to override this
b) you have a forum or members area in your site which has to have Cache-Control zero when users login. It would be a double-dick move to enforce caching on private sections of a site.

Adding Cache-Control headers is easily done in .htaccess.

Engintron enforces long Cache-Control headers only for static content such as CSS, JS, images, web fonts etc. It does not enforce caching for .html and it only enforces a 1 hr caching for content such as json, xml, rss & atom (feeds).

You have a solution already, but I highly recommend you control caching through .htaccess. More over, if your pages are actually .html static files, then there is no overhead in Nginx to serve those. It will even cache their output internally for a 1 minute.
