### ISSUE TITLE
After update to 1.8.0 nothing works (502 bad gateway)

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#409]
He even resets the resolver to the IPv4 version?
I disabled Engintron now because it's a production server :(

Trying mainline now...

**Comment by Friends4U** [comment]
mainline works... but some of my certificates are invalid now (let's encrypt)

**Comment by Friends4U** [comment]
HTTP/1.1 200 OK => 
Server => nginx
Date => Mon, 20 Feb 2017 17:53:04 GMT
Content-Type => text/html
Content-Length => 1368
Connection => close
Vary => Accept-Encoding
Last-Modified => Tue, 25 Aug 2009 20:34:46 GMT
X-XSS-Protection => 1; mode=block
X-Content-Type-Options => nosniff
X-Nginx-Cache-Status => MISS
X-Server-Powered-By => Engintron
Accept-Ranges => bytes


What does that MISS mean (X-Nginx-Cache-Status)?

**Comment by Friends4U** [comment]
None of my certs are valid now :(

**Comment by fevangelou** [comment]
Did you have any previous customizations done in Nginx or related yo HTTPS
traffic?

**Comment by mgmaik** [comment]
I got the same problem after updating to mainline. 
This is the certs error: "ERR_CERT_COMMON_NAME_INVALID"

I haven't made any precious customizations in Nginx or HTTPS. I only opened the 8080, 8443 ports in ServerConfig firewall

**Comment by Friends4U** [comment]
Nee, no previous settings... 1.7x worked perfectly... 1.8 does only with http, https not working.

**Comment by lafrance** [comment]
Hello!

Was this resolved? as having the same problems

**Comment by mcravtov** [comment]
Still the same error in HTTPS http is working fine

**Comment by fevangelou** [comment]
Apache seems to get stuck for some reason and can't get restart. Either restart Apache from WHM (via Home » Restart Services »HTTP Server (Apache)) or simply upgrade Engintron once more (to today's build) which does the above automatically on update.

Let me know.

**Comment by mgmaik** [comment]
I updated engintron and apache both didn't work. Still get the HTTPS "ERR_CERT_COMMON_NAME_INVALID" error.  Apache restarted fine. 

The webpage does loads when I click: "Continue load unsafe webpage" But the webpage stays "Not Secure".

So I think it's a ssl error? 
It all worked perfectly before the upgrade.

**Comment by fevangelou** [comment]
No, this is not an SSL error. This means that you're just calling a URL from HTTPS and the page loading is simply trying to load resources over HTTP. Browsers will flag such a site as insecure. Correct any references in that site to CSS, JS or image files from HTTP to HTTPS and you should be fine.

**Comment by mgmaik** [comment]
When I disable Engintron, HTTPS works perfectly. Browser won't flag it too.

**Comment by mofolo** [comment]
Restarting HTTPD worked for me:
`/etc/init.d/httpd restart`

**Comment by Paralda** [comment]
A fix for this:

Uninstall, install 1.7.2:

https://github.com/engintron/engintron/releases/tag/v1.7.2

Then:

rm -f /etc/nginx/conf.d/default_https.conf

Wait for the cron job to recreate the https.conf automatically, and you should be set.

This PHP script seems to be broken in 1.8.0:
/etc/nginx/utilities/https_vhosts.php
1.7.2 uses a different PHP script for its cron, which seems to be working.

**Comment by Friends4U** [comment]
So we need to roll back to 1.7.2 and not upgrade to 1.8 anymore?

**Comment by Friends4U** [comment]
I'll leave it off for now and wait for newer build... I hope fevangelou will fix the bugs of this version...

**Comment by lafrance** [comment]
Well I did this
cd /; rm -f engintron.sh; wget --no-check-certificate https://raw.githubusercontent.com/engintron/engintron/master/engintron.sh; bash engintron.sh install

and reinstall it made sure tweak was set to port 8080 and work like a charm now

**Comment by lafrance** [comment]
Ah though it work however did not and I see no way to revert to 1.7.2

**Comment by Friends4U** [comment]
Which tweak do you mean?
I am running Engintron for a long time now, but now as of 1.8 is simply does not work anymore (on https sites)...
What tweak do I need to get it running? I am willing to try :)

**Comment by fevangelou** [comment]
Update to today's build please. The issue may have been caused by domains with no SSL certificates assigned to them.

**Comment by Friends4U** [comment]
The domains with ssl certs also did not work (I am using let's encrypt (not the autossl from cpanel)).
* Updated
* Emptied cache
Im sorry, the update of today did not work for my setup :(

**Comment by Friends4U** [comment]
Also the sites with "real" certs do not work.
I am not testing https sites without certificate...

**Comment by fevangelou** [comment]
@Friends4U can you locate where the TLS/SSL certificates are stored from that other plugin you use? Or is it LetsEncrypt's certbot?

**Comment by mgmaik** [comment]
I updated to today's build but still no luck. I had to disable engintron to make SSL sites work. 
Cleared cache and restarted nginx, apache, httpd.

I use CentOS 7.3 with AutoSSL from LetsEncrypt

This is the error message when I want to access a SSL website
"NET::ERR_CERT_COMMON_NAME_INVALID"

**Comment by fevangelou** [comment]
I've updated how SSL blocks in Nginx are created as it seems there are differences in the syntax of the Apache configuration file. Just released v1.8.1, you might wanna try that out.

**Comment by mgmaik** [comment]
I just updated to 1.8.1 but still the same SSL error (clear cached and restarted everything etc)
"NET::ERR_CERT_COMMON_NAME_INVALID"

Do you want me to send the httpd.conf file?

**Comment by fevangelou** [comment]
@mgmaik Yes, please.

**Comment by fevangelou** [comment]
@mgmaik And please tell me on which domain you're getting this error... Are there any other domains on your server that work perhaps?

**Comment by Friends4U** [comment]
I will wait for this outcome, because it's a production server for me...

**Comment by lafrance** [comment]
Hello @Friends4U 
Did you make the same mistake as me trying another cpnginx or varnish?
I had varnish install and it re did all my engintron set up
Even after installing it was still on server

**Comment by Friends4U** [comment]
The version prior to 1.8 worked flawlessly, I tried other versions before yes but they are all gone. And I am not the only one with the problem luckily. However I must say that I use cloudlinux and not the default autossl from cpanel. as said before in this topic :)

**Comment by fevangelou** [comment]
@Friends4U The thing is, uninstalling older plugins does not always work right. For example, @lafrance's server had Unixy's plugin for Nginx/Varnish (which BTW is utter crap) and to fully uninstall it, I had to remove 3rd party repos installed by that plugin which may not see related in the first place.

In any case, if v1.7.x worked fine, maybe Apache's processes get stuck. Or maybe AutoSSL is borked on your server. Try this. Install the LetsEncrypt plugin for cPanel (https://documentation.cpanel.net/display/CKB/The+Let's+Encrypt+Plugin), delete all SSL hosts under "Manage SSL hosts", reset AutoSSL to use LetsEncrypt and re-issue certificates for all users. When this is done (check the logs tab in AutoSSL), reboot your server.

Let me know.

**Comment by Friends4U** [comment]
I do no use AutoSSL sorry... the older plugin was only nginx (i completly removed that).

**Comment by fevangelou** [comment]
So no HTTPS sites? Shouldn't make a difference for you then.

**Comment by mcravtov** [comment]
The same on my side. 
After installing the new version all HTTPS sites stop working.

**Comment by fevangelou** [comment]
@mcravtov First go to the Engintron WHM app and under the Nginx menu, click on "Check configuration for errors". What does it output?

**Comment by Friends4U** [comment]
I have normal certificates... they do not work anymore with 1.8

**Comment by Friends4U** [comment]
No errors!

**Comment by mcravtov** [comment]
After updating to 11.62.0.15 cpanel - Engintron app icon has disaperead from WHM

**Comment by fevangelou** [comment]
@mcravtov Simply re-install.
@Friends4U do you have any wildcard domains in Apache's config? E.g. *.somedomain.com

**Comment by Friends4U** [comment]
Nope

**Comment by jannohordijk** [comment]
After update to 1.8 I have problem with only one domain while I have several Comodo certs on the server and for the other sites I have AutoSSL from cPanel running. I updated already to 1.8.2. Remove the cert from the sever, reinstalled it again, purged the cache and tempfiles, restarted all processes but it still gives me 'This page is not secure' and <pre>There are issues with the site's certificate chain (net::ERR_CERT_COMMON_NAME_INVALID).</pre>.

CentOS 6.8, WHM 62.0 build 16. Domain: imediators.nl

Best regards, Janno

**Comment by Friends4U** [comment]
@jannohordijk , lekker responsive je server :) goede host?

**Comment by jannohordijk** [comment]
@Friends4U op zich wel, CloudVPS Vind je hem traag reageren?

**Comment by Friends4U** [comment]
Nee, juist niet... Reageert lekker vlot :)

**Comment by jannohordijk** [comment]
OK, ik ben zelf niet helemaal tevreden vandaar dat ik Fastest Cache in WordPress gebruik, PHP 7 en PHP-FPM en dan nu daarbij Engintron. Wat gebruik jij?

**Comment by fevangelou** [comment]
First off, please post in English only. Posts in other languages from now on will be deleted.

Secondly, Comodo certificates seem to have issues. Enable the LetsEncrypt plugin in cPanel and simply re-issue your certificates with LetsEncrypt. Purge the Nginx cache after that and restart both Apache & Nginx. Done.

**Comment by Friends4U** [comment]
I will try this...

**Comment by highacid** [comment]
@fevangelou I cannot just move my Comodo users to Lets encrypt just because comodo might have issues. This is absurd, All certs have issues with verifiyng OCSP Stapling on SSL certs. The fact you dont get all errors now, is maybe not all people are aware of them or not bother with them. I too see TWO main issues in the past 6 year 502 BAD Gateways and now with this SSL support the OCSP and few other SSL glitches are in. ALto I warned you about the 502 issue it was not yet been solved, This not only cause Apache to crach and corrupt itself after few days, but is like untraceable if Apache get stuck, and it does so quite often. It picks random sites, with or without SSL and it just throw 502, while other sites on same server works well. As of me posting and reporting the issue many times or just stating real issues, I got just banning warnings, and NEVER a real answer human solution, ignorance is not bliss... I guess we were all trying to help you help us... Or you just like to hit same errors on and on. If even now when are more then 6 tickets closed with 5xx errors and multiple about other SSL issues you dont see there are some issues in latest version, it's all I can do. Alto your threats were not necesarry, and If I do not open a thread more times, other will cause you never got it serious in first place. A good product is give by your ability to understand others and co work with them. I am not against you. Anyhow I do understand your side, leaving small glitches here and there, someone might enquire directly to solve them .. :) have fun!

**Comment by fevangelou** [comment]
@highacid Oh boy...
a) OCSP can easily be switched off if your server has network issues.
b) If you've issued the free Comodo certificates with AutoSSL, it takes 5 mins to re-issue them with LetsEncrypt. Don't be lazy.
c) Out of the thousands of users with Engintron on their servers, it's you and only you who have constantly had issues. Uninstall Engintron and do everyone a favour. Really, I'm bored with your constant problems.
d) Your server is obviously screwed by you already because you have no clue at managing it. Leave that to the professionals, will ya?
e) If money was my main objective you imbecile, I wouldn't provide Engintron for free. Some people, unlike you, like to build stuff and share it with the world, so others can benefit. This is open source. And you are clearly an idiot not to understand that.

**Comment by katmai** [comment]
i just fell inlove with @fevangelou :)

**Comment by Friends4U** [comment]
Darn... everybody is hijacking my topic :)

I removed the plugin which i used, activated AutoSSL and gave everybody an SSL cert (lol, I did not know AutoSSL does that like it does), but still... not working, also still not on my normal paid SSL certs...

**Comment by lafrance** [comment]
If you are using version 1.8.2 it should work with no problem 
check https://hostingrage.ca for paid SSL it work
and client site using let's encrypt also working
https://www.curriewayneclayton.com/

Are you sure you did not do any edit to any of the server files?

**Comment by Friends4U** [comment]
I'm to stupid to do that...
But I am using CloudLinux, perhaps that makes a difference...

**Comment by lafrance** [comment]
Ah try to reach out to them and see if there as been a problem?

I choose not to install cloud Linux due to a few problems

**Comment by Friends4U** [comment]
Hmmm... suddenly it works now...

**Comment by Friends4U** [comment]
Omg...

**Comment by lafrance** [comment]
Happy dance 👍  maybe a cache on your server

**Comment by Friends4U** [comment]
Nah... I think the plugin I used was not good... and the second time I tested I was just impatient :)
Tnx everybody!

Only thing that's to bad is that the certs issued by AutoSSL are in chrome specified as not completely safe, the plugin I used, those carts where completely safe (not commodo) I believe.

But perhaps I need to do some more reading into this...

**Comment by Friends4U** [comment]
Found it: https://documentation.cpanel.net/display/CKB/The+Let's+Encrypt+Plugin
That way, AutoSSL uses Let's Encrypt (which DO validate) :)

**Comment by Friends4U** [comment]
Or not... Hmmm... Strange...

**Comment by fevangelou** [comment]
After you re-issue certificates using cPanel's plugin for LetsEncrypt, it may take a while for the changes to have effect on Engintron.

The link you mentioned is the right one.

**Comment by ibrahimrafeeq** [comment]
SSL sites didn't load for me as well after installing the engintron. My issue was the cronjob that is supposed to create the default_https.conf was not there on the crontab. So I manually ran the php script and it created default_https.conf. Restart nginx and sites load after that. 

~]# cd /etc/nginx/conf.d/
~]# ls
default.conf  default.conf.bak
~]# php /etc/nginx/utilities/https_vhosts.php
Content-type: text/html; charset=UTF-8

HTTPS vhosts for Nginx re-created.
~]# ls
default.conf  default.conf.bak  default_https.conf
~]# service nginx restart

**Comment by fevangelou** [comment]
@ibrahimrafeeq Just open the file /etc/crontab via Engintron's WHM app and hit save. This will fix line endings in that file and resume all cron jobs referenced there.
