### ISSUE TITLE
Need to enable ALPN with engintron

### ISSUE THREAD

**Issue by windsofchange** [engintron/engintron#410]
Need to recompile Engintron nginx with custom openssl 1.02 to support ALPN 

Any ideas anyone?

**Comment by tux-tn** [comment]
Hello @windsofchange 
You can try the solution i provided here : https://github.com/engintron/engintron/issues/368#issuecomment-273250846. 
It's working for me

**Comment by windsofchange** [comment]
Thank you @tux-tn 
That's quite sweet. A simple repo install, update, restart nginx and clear cache

How good are CodeIT guys with updates and security fixes?

**Comment by tux-tn** [comment]
They seem to be quite fast, the last stable release 1.10.3 was updated on the repo with 1 day interval

**Comment by windsofchange** [comment]
Mainline version works fine, but the binary did not work for me?

**Comment by Citizen-K** [comment]
So far, so good. Thanks for the lead @tux-tn 
Pretty simple procedure.
Repo install, yum makecache, system update, graceful reboot, re-install Engintron, re start nginx.
