### ISSUE TITLE
Wrong Visitor IP (Centos7+CloudLinux, WHM62, EA4)

### ISSUE THREAD

**Issue by MikeyPixel** [engintron/engintron#411]
Tried the previous posts for trying to get the real visitor IP going (updating/reinstalling), just updated to 1.8.0 but Apache still logs server IP. Any ideas on getting this working?

**Comment by fevangelou** [comment]
Seen this? https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron

Upload the mentioned code in a public URL and check.

**Comment by MikeyPixel** [comment]
Yes, did that and still shows the server IP. I uninstalled remoteip (ea-apache24-mod_remoteip.x86_64) manually thru command line and then reinstalled Engintron, still showing server IP in the logs. This is the package of remoteip module being installed when installing Engintron:

=== Installing mod_remoteip for Apache ===
Loaded plugins: fastestmirror, rhnplugin, universal-hooks
This system is receiving updates from CLN.
Loading mirror speeds from cached hostfile
 * EA4: 208.43.108.66
 * cloudlinux-x86_64-server-7: xmlrpc.cln.cloudlinux.com
Package 1:ea-apache24-mod_remoteip-2.4.25-4.el7.cloudlinux.x86_64 already installed and latest version
Nothing to do

**Comment by fevangelou** [comment]
Released v1.8.2 today which improves Nginx IP forwarding to Apache. Update (hit re-install in the Engintron WHM app) and let me know.

**Comment by MikeyPixel** [comment]
Still showing server IP, should I manually uninstall remoteip again and click on the update in Engintron?

**Comment by fevangelou** [comment]
Can you reboot your server once please?

**Comment by fevangelou** [comment]
No, it's not needed. Check if "remoteip" is present in "Show loaded modules" under the Apache menu in Engintron's WHM app.

Also load this script https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron somewhere public so I can have a look as well.

**Comment by Nirjonadda** [comment]
@fevangelou "Show loaded modules" under the Apache menu in Engintron's WHM app are not come any output. All are blank, Is this bug or not?

**Comment by MikeyPixel** [comment]
Can confirm @Nirjonadda output the same as mine, no modules listed.

**Comment by Nirjonadda** [comment]
I have opened bug here : https://github.com/engintron/engintron/issues/456

**Comment by bober2000** [comment]
Having the same trouble with visitors IP. Tried reinstalling/removing - not helped.
uname -r && cat /etc/redhat-release && httpd -v && service httpd
3.10.0-327.36.3.el7.x86_64
CentOS Linux release 7.3.1611 (Core) 
Server version: Apache/2.4.25 (cPanel)

httpd -M
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 mpm_event_module (shared)
 cgid_module (shared)
 access_compat_module (shared)
 actions_module (shared)
 alias_module (shared)
 asis_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 include_module (shared)
 log_config_module (shared)
 logio_module (shared)
 mime_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 proxy_http_module (shared)
 remoteip_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_dbm_module (shared)
 socache_shmcb_module (shared)
 status_module (shared)
 unique_id_module (shared)
 unixd_module (shared)
 userdir_module (shared)
 version_module (shared)
 ssl_module (shared)
 bwlimited_module (shared)
 security2_module (shared)
 suphp_module (shared)

mod_remoteip installed ok, Engintron v1.8.3, Nginx version: 1.12.0 script shows that everything is ok https://www.pre.4for4.com/fantasy-football/ip.php but logs are still showing servers IP. When disable Engintron - it's ok.
