### ISSUE TITLE
Log not work with real IP and manual solution not work

### ISSUE THREAD

**Issue by abkrim** [engintron/engintron#413]
Veredict NO
https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron

Try reinstall 5 times.

Sceneario
CENTOS 7.3 x86_64 kvm – srv108 WHM 62.0 (build 15) 
Easyapache 4

**Comment by ubidzz** [comment]
that test wont work because it connecting to a website to get the IP but it the server that is connection to the site so it going to log your server ip and not the user.

trim(file_get_contents("http://ipecho.net/plain"));

that code is telling the server to connect to that site not the user.

If this code shows your IP then it is working
$_SERVER["REMOTE_ADDR"]

I have centos 7, EA4, WHM 62 and mine works. people don't realize when you use a php code to load info from a off site website it not going to use your user IP and will use the server IP because that is what is making the connection to the website to pull the data from it. I am a website developer and i have made codes to do what he is doing. If you have CSF installed look in the logs and you will see the user IP is being logged in it.

**Comment by abkrim** [comment]
Hi

I think the speech and the illustration are great. But the issue is that the apache log does not display the actual ip of the visitor but the ip of the server. And that's what it's all about, that the real ip of the visitor is written in the apache logs.

**Comment by fevangelou** [comment]
There's a typo in the original file to show you whether IPs are properly logged or not. Get the updated code from https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron and re-run on your server.

**Comment by abkrim** [comment]
Well. ip. check it's good, but log not.

http://abdel-karim.es/ip.php

log-->
```
176.31.31.233 - - [01/Mar/2017:15:47:34 +0100] "GET / HTTP/1.1" 200 1366 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
176.31.31.233 - - [01/Mar/2017:15:47:37 +0100] "POST /wp-login.php HTTP/1.1" 403 5 "http://abdel-karim.es/wp-login.php" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36"
176.31.31.233 - - [01/Mar/2017:15:47:38 +0100] "GET /ip.php HTTP/1.1" 200 3285 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
```

Version Engintron 1.8.1

Best regards.

**Comment by fevangelou** [comment]
You have to do some digging on your own. First off, please upgrade to Engintron again (I released a minor update a few minutes ago adding some Apache utils in the Engintron WHM app). After upgrading Engintron, go to the Engintron WHM app and click the option "Show loaded modules". Do you see "remoteip_module (shared)" in there?

**Comment by abkrim** [comment]
- Disable Engitron form WHM
- Update (or re-install) Engintron [Nginx stable] 

Not work.

`176.31.31.233 - - [02/Mar/2017:08:14:14 +0100] "GET /style.css HTTP/1.1" 404 23729 "http://abdel-karim.es/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"`

Try from reinstall (full)
- Disable Engitron form WHM
- cd /; rm -f engintron.sh; wget --no-check-certificate https://raw.githubusercontent.com/engintron/engintron/master/engintron.sh; bash engintron.sh install

`176.31.31.233 - - [02/Mar/2017:08:19:10 +0100] "GET / HTTP/1.1" 200 43843 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
176.31.31.233 - - [02/Mar/2017:08:19:11 +0100] "GET /style.css HTTP/1.1" 404 23729 "http://abdel-karim.es/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"`

Show loaded modules show in red only--->

`Show compiled modules...`

Not show anything about remoteip_module (shared)
![srv108_ _webhost_manager](https://cloud.githubusercontent.com/assets/1238625/23497018/84c64660-ff21-11e6-9cc6-878d3da18628.jpg)


Best regards

**Comment by fevangelou** [comment]
The above command should at least display something. What OS version do you have? E.g. CentOS 6, CentOS7 etc.

To see the real output, login as root via a terminal and execute this:
```service httpd -M```

This module requires a dependency to be installed which you may be missing:
```yum install httpd-devel```

Let me know.

**Comment by Nirjonadda** [comment]
@fevangelou I'm unable to install httpd-devel using : ````yum install httpd-devel````

````
[root@na ~]# yum install httpd-devel
Loaded plugins: fastestmirror, tsflags, universal-hooks
Loading mirror speeds from cached hostfile
 * EA4: 91.197.228.252
 * EA4-experimental: 91.197.228.252
 * base: mirrors.coreix.net
 * epel: mirror.cs.princeton.edu
 * extras: mirrors.coreix.net
 * updates: mirrors.coreix.net
No package httpd-devel available.
Error: Nothing to do
[root@na ~]#
````

**Comment by abkrim** [comment]
Hi.

CENTOS 7.3 x86_64 kvm – srv108  WHM 62.0 (build 16)
`service httpd -M
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.`

Instead
`httpd -M
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 mpm_prefork_module (shared)
 cgi_module (shared)
 access_compat_module (shared)
 actions_module (shared)
 alias_module (shared)
 asis_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cache_module (shared)
 dav_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 include_module (shared)
 log_config_module (shared)
 logio_module (shared)
 mime_module (shared)
 mime_magic_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 proxy_http_module (shared)
 remoteip_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_dbm_module (shared)
 socache_shmcb_module (shared)
 speling_module (shared)
 status_module (shared)
 suexec_module (shared)
 unique_id_module (shared)
 unixd_module (shared)
 userdir_module (shared)
 usertrack_module (shared)
 version_module (shared)
 ssl_module (shared)
 bwlimited_module (shared)
 security2_module (shared)
 suphp_module (shared)`

About httpd-devel

` cat /etc/yum.conf
[main]
exclude=courier* dovecot* exim* filesystem httpd* mod_ssl* mydns* mysql* nsd* p0f php* proftpd* pure-ftpd* spamassassin* squirrelmail*`

User need modify for this yum.conf offcial for Cpanel.

After, `yum install httpd-devel` work

But try process, and already not work

- Disable engitron
- cd /; rm -f engintron.sh; wget --no-check-certificate https://raw.githubusercontent.com/engintron/engintron/master/engintron.sh; bash engintron.sh install
- Show compiled empty
-  httpd-devel-2.4.6-45.el7.centos.x86_64 obsolete by ea-apache24-devel-2.4.25-5.5.1.cpanel.x86_64, already installed (poor trasnlate from spanish)
Nothing for made

`176.31.31.233 - - [02/Mar/2017:11:19:23 +0100] "GET / HTTP/1.1" 302 210 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"`

**Comment by abkrim** [comment]
Now..

`
Show precompiled Nginx modules...

nginx version: nginx/1.10.3
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-file-aio --with-threads --with-ipv6 --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie'
`

**Comment by fevangelou** [comment]
@abkrim I lost you. You said "httpd-devel" was installed. And I also see mod_remoteip also installed. Does user IP logging work now for you or not?

**Comment by abkrim** [comment]
No. Not work @fevangelou 
`176.31.31.233 - - [02/Mar/2017:11:29:28 +0100] "GET /wp-content/uploads/2014/11/anuncio_triana.jpg HTTP/1.1" 302 255 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8
176.31.31.233 - - [02/Mar/2017:11:29:52 +0100] "GET /smf/index.php?topic=3221.msg133080 HTTP/1.1" 200 144633 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
176.31.31.233 - - [02/Mar/2017:11:29:53 +0100] "GET /smf/index.php?thememode=mobile;redirect=http://timspump.com/board_wnYh20/256763 HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
`

**Comment by fevangelou** [comment]
I'm looking again at this: http://abdel-karim.es/ip.php

I can see my IP where it should be. I've triple checked it on other servers I manage for clients. If the verdict script is correct, logging works. And the right user IP appears in Nginx logs.

I have no idea why this happens to you. If you've modified httpd.conf or have installed any other plugins in cPanel that could affect IP reporting, it's impossible for me to troubleshoot unless I can login as root user on your server.

**Comment by fevangelou** [comment]
Alternatively, try this (just in case)...

If you use EA4, locate the mod_remoteip config file. It should be here:
/etc/apache2/conf.modules.d/*_mod_remoteip.conf (* will be some number, e.g. 360)

If you use EA3, locate the mod_remoteip config file. It should be here:
/usr/local/apache/conf/includes/remoteip.conf

In either case, find this line:
```Replace RemoteIPHeader X-Real-IP```
and change it to:
```Replace RemoteIPHeader X-Forwarded-For```

Save the file and restart both Apache & Nginx.

Does logging work for you now?

Edit the file /

**Comment by abkrim** [comment]
`cat /etc/apache2/conf.modules.d/360_mod_remoteip.conf
# Enable mod_remoteip
LoadModule remoteip_module modules/mod_remoteip.so
RemoteIPInternalProxy 127.0.0.1 127.0.0.1 176.31.31.233 176.31.31.234 176.31.31.235 176.31.31.236 176.31.31.237 176.31.31.238 176.31.31.239 176.31.31.240 176.31.31.212 176.31.31.250
RemoteIPHeader X-Forwarded-For
`

not work after restart apache & niginx from whm

`176.31.31.233 - - [02/Mar/2017:12:20:16 +0100] "GET /wp-content/uploads/2014/11/anuncio_triana.jpg HTTP/1.1" 302 255 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
176.31.31.233 - - [02/Mar/2017:12:21:04 +0100] "GET /wp-content/themes/flowers-20/images/header.jpg HTTP/1.1" 200 44133 "http://abdel-karim.es/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8
`

**Comment by abkrim** [comment]
Hi.

9 days a ago, on top message

> Sceneario
> CENTOS 7.3 x86_64 kvm – srv108 WHM 62.0 (build 15)
> Easyapache 4

```
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 mpm_prefork_module (shared)
 cgi_module (shared)
 access_compat_module (shared)
 actions_module (shared)
 alias_module (shared)
 asis_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cache_module (shared)
 dav_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 include_module (shared)
 log_config_module (shared)
 logio_module (shared)
 mime_module (shared)
 mime_magic_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 proxy_http_module (shared)
 remoteip_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_dbm_module (shared)
 socache_shmcb_module (shared)
 speling_module (shared)
 status_module (shared)
 suexec_module (shared)
 unique_id_module (shared)
 unixd_module (shared)
 userdir_module (shared)
 usertrack_module (shared)
 version_module (shared)
 ssl_module (shared)
 bwlimited_module (shared)
 security2_module (shared)
 suphp_module (shared)
```

Httpd-devel cant' installed on Cpanel system, but for debug purposes, delete httpd* from exclude on yum.

```
 yum install httpd-devel
Complementos cargados:tsflags, universal-hooks
EA4                                                                                                                                                                                                                                                                                                | 2.9 kB  00:00:00
MariaDB100                                                                                                                                                                                                                                                                                             | 2.9 kB  00:00:00
base                                                                                                                                                                                                                                                                                                   | 3.6 kB  00:00:00
cpanel-plugins                                                                                                                                                                                                                                                                                         | 2.9 kB  00:00:00
extras                                                                                                                                                                                                                                                                                                 | 3.4 kB  00:00:00
nginx                                                                                                                                                                                                                                                                                                  | 2.9 kB  00:00:00
remi-safe                                                                                                                                                                                                                                                                                              | 2.9 kB  00:00:00
updates                                                                                                                                                                                                                                                                                                | 3.4 kB  00:00:00
zabbix                                                                                                                                                                                                                                                                                                 |  951 B  00:00:00
zabbix-non-supported                                                                                                                                                                                                                                                                                   |  951 B  00:00:00
The package httpd-devel-2.4.6-45.el7.centos.x86_64 becomes obsolete with ea-apache24-devel-2.4.25-5.5.1.cpanel.x86_64, which is already installed
Nothing to do
```


Best regards

**Comment by Nirjonadda** [comment]
@abkrim From cPanel response https://forums.cpanel.net/threads/install-httpd-devel.594631/#post-2405723

````
You can't install httpd* anything from upstream repositories, as EasyApache 4 will conflict with them.

You can install ea-apache24-devel to get the same scripts and binaries that are in httpd-devel
 ````

**Comment by ubidzz** [comment]
If you run a clean/standard cPanel build and build your PHP in EA4 then install Engintron you should not have any issues. For example i do not install extra services or repo in my server and just run what cPanel installed and Engintron with CodeIT repo for the nginx server and i don't have 1 issue. Well i do have 1 issue but that with the OCSP stapling but it seems the more stuff you add in your server the more issues you will get. I do not use Httpd-devel and only use mod_remoteip and all my IPs are logged correctly. 

My server is running CENTOS 7.3 x86_64 standard, WHM 62.0 (build 16) and EA4

@abkrim what @fevangelou commented about the RemoteIPHeader should be using this
`RemoteIPHeader X-Forwarded-For`

**Comment by fevangelou** [comment]
...Or just update to v1.8.2

If you are on EA4, then Engintron installs the EA4 provided mod_remoteip module.

If nothing works for you and logging still fails, something else is wrong, so better contact your hosting company. I'm out of ideas.

**Comment by abkrim** [comment]
I'm my own hosting. And I use Engintron because it's a solid tool. But after read your comment... oops... something break. 

Best regards and a good weekend

**Comment by fevangelou** [comment]
I cannot possibly know what you've done in your server, can I?

**Comment by abkrim** [comment]
It's not one server.... It's 5 servers with same problem. On one server, try also develop version, instead main version.
Do like acces to one on them?  On my profile is my email, ... for any hours.

Best regards

**Comment by jcatello** [comment]
I have the same issue on a bunch of servers, the IP logs correctly in Nginx:

Example:

Nginx

```
root@server [/home/user/public_html]# tail -1 /var/log/nginx/access.log
117.197.81.204 - - [09/Mar/2017:09:50:02 -0500] "POST /wp-content/plugins/simple-ads-manager/sam-ajax.php HTTP/1.1" 200 47 "http://www.domain.com/2014/05/07/easy-lemon-crinkle-cookies-free-printable/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
```

Apache:

```
root@server [/home/user/public_html]# tail -1 /usr/local/apache/domlogs/domain.com
50.31.99.183 - - [09/Mar/2017:09:50:56 -0500] "GET /2016/03/29/tips-for-traveling-with-a-preschooler/? HTTP/1.1" 200 61263 "-" "ADmantX Platform Semantic Analyzer US - Turn - ADmantX Inc. - www.admantx.com - support@admantx.com"
```

50.31.99.183 being the server IP.

root@server [/]# httpd -M |grep -i remote
 remoteip_module (shared)

running 1.8.2

I'm not asking you to help resolve this, I just want to confirm with you @fevangelou that the IP shows the actual user IP for you in both logs?

**Comment by jcatello** [comment]
That's clearly what I posted, if you look at the log I posted, its me tailing the exact path you just pointed out:

"tail -1 /usr/local/apache/domlogs/domain.com"

**Comment by fevangelou** [comment]
Make sure you do "tail -f /usr/local/apache/domlogs/domain.com-ssl_log" as well though if you're default traffic comes from HTTPS and not HTTP.
