### ISSUE TITLE
header issue with Strict-Transport-Security and missing importing headers

### ISSUE THREAD

**Issue by ubidzz** [engintron/engintron#415]
This will fix the HSTS problem and should give you a A+ or A rating for SSL tests.

>     #   if ($scheme = 'https') {
>     #   add_header                Strict-Transport-Security "max-age=86400; includeSubDomains" always;
>     #    }

This wont work and will kill all the other headers that are being set and the only way to make it work correctly is by making 2 **if** statements with all the headers.

Here the working code and the missing header that should be set.

>      #    Security Headers
> if ($scheme = "https") {
>     #   Info
>     add_header                    X-Nginx-Cache-Status $upstream_cache_status;
>     add_header                    X-Server-Powered-By "Engintron";
>     
>     #    Security Headers
>     add_header                    Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
>     add_header                    Referrer-Policy "origin" always;
>     add_header                    X-Frame-Options SAMEORIGIN;
>     add_header                    X-Content-Type-Options nosniff;
>     add_header                    X-XSS-Protection "1; mode=block";
> }
> 
> if ($scheme = "http"){
>     # Info
>     add_header                    X-Nginx-Cache-Status $upstream_cache_status;
>     add_header                    X-Server-Powered-By "Engintron";
>     
>     # Security Headers
>     add_header                    Referrer-Policy "origin" always;
>     add_header                    X-Frame-Options SAMEORIGIN;
>     add_header                    X-Content-Type-Options nosniff;
>     add_header                    X-XSS-Protection "1; mode=block";
> }

By doing it this way all the headers will be set and no matter if the connection is http or https.

This is for @fevangelou you should consider using awk command and not file_get_contact to get the data from the httpd.conf file and to have nginx use it own SSL stuff and this will help fix the issues with the PHP open_basedir Tweak because it wont be used. I made a script that looks in to the httpd.conf file to pull the SSL and copy it to the nginx folder with it own SSL cert, key, caboundle and separated vhosts so each domain has it own vhost.conf file and same with the SSL stuff so that the Admin can easilly find and edit thoughts files and it also fix the SSL chain because the crt, and caboundle have to be in 1 SSL file for nginx to work correctlly. You are also missing a lot of parameters in the nginx.conf file that is shown below with your parameters and the missing ones.

> ## Basic Settings ##
>     client_body_buffer_size        128k;
>     client_header_buffer_size      1k;
>     large_client_header_buffers    4 4k;
>     output_buffers                 1 32k;
>     postpone_output                1460;
>     client_body_timeout            20s; # Use 5s for high-traffic sites
>     client_header_timeout          20s; # Use 5s for high-traffic sites
>     client_max_body_size           1024m;
>     keepalive_timeout              20s;
>     keepalive_requests             100000;
>     port_in_redirect               off;
>     sendfile                       on;
>     send_timeout                   3m;
>     server_names_hash_bucket_size  1000;
>     server_name_in_redirect        off;
>     server_tokens                  off;
>     tcp_nodelay                    on;
>     tcp_nopush                     on;
>     types_hash_max_size            2048;
>     open_file_cache                max=1000 inactive=20s;
>     open_file_cache_valid          30s;
>     open_file_cache_min_uses       5;
>     open_file_cache_errors         off;
> 

You can use my script or you can see how i made it work.
https://github.com/ubidzz/SSL-plugin-for-engintron-BETA/tree/master/scripts

**Comment by fevangelou** [comment]
What you're doing is irresponsible as you do NOT understand how HSTS works.

If HSTS is enabled on a server, then ALL HTTP URLs are redirected to HTTPS URLs. Most sites using CMSs like Joomla, Drupal, WordPress etc. MAY NOT have all resources fetched relatively of better still from HTTPS (e.g. Google Fonts, jQuery remotely etc.).

If HSTS is enabled, then such sites will appear broken.

**Comment by ubidzz** [comment]
If you look at the Strict-Transport-Security it is only in the https **if** statement and i have been testing it on my server and i don't have any problems with it and ever website works. I do have users on my server that are using Joomla, WordPress on non-SSL and SSL with out any problems.

**Comment by ubidzz** [comment]
This apply to this comment to fix the Strict-Transport-Security and add other Security headers.

I did a clean install and everything does work but i did find the fix for the Strict-Transport-Security that is shown below added in the proxy_params_common file with the other Security headers that should be added.

if ($scheme = "https") {
    add_header                    X-Nginx-Cache-Status $upstream_cache_status;
    add_header                    X-Server-Powered-By "Engintron";
    add_header                    Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
    add_header                    Referrer-Policy "no-referrer-when-downgrade" always;
    add_header                    X-Frame-Options SAMEORIGIN;
    add_header                    X-Content-Type-Options nosniff;
    add_header                    X-XSS-Protection "1; mode=block";
}

if ($scheme = "http"){
    add_header                    X-Nginx-Cache-Status $upstream_cache_status;
    add_header                    X-Server-Powered-By "Engintron";
    add_header                    Referrer-Policy "no-referrer-when-downgrade" always;
    add_header                    X-Frame-Options SAMEORIGIN;
    add_header                    X-Content-Type-Options nosniff;
    add_header                    X-XSS-Protection "1; mode=block";
}

**Comment by tux-tn** [comment]
You shouldn't send HSTS header for all your  clients websites, at least you should put a shorter max-age period or you will break their websites if they don't support HTTPS (mixed-content,  invalid certificate,...)

@ubidzz Without wishing to be in the least critical or unpleasant, i think you should read more about every http headers you are using before enabling it, `HSTS` `X-Frame-Options` and other headers can break things if they are misused.
