### ISSUE TITLE
 Connection timed out

### ISSUE THREAD

**Issue by mcravtov** [engintron/engintron#416]
I have moved a web site to my server and try to check it by editing a local machine hosts file.
But the server still keep to connect to OLD Ip not to current
*127394 connect() failed (110: Connection timed out) while connecting to upstream, client: X.X.X.X, server: localhost, request: "GET / HTTP/1.1", upstream: "http://195.22.228.187:8080/", host: "example.com"

this is a remote server IP not my localhost.

**Comment by fevangelou** [comment]
https://github.com/engintron/engintron/wiki/Engintron-&-(under-development)-domains-that-don't-yet-resolve-(point)-to-your-cPanel-server
