### ISSUE TITLE
ALPN not supported

### ISSUE THREAD

**Issue by Technopope** [engintron/engintron#417]
Hello, 

Congratulations for integrating HTTP/2 with the latest version of Engintron. 
However, the issue is that ALPN is not supported, and hence HTTP/2 won't work in Google Chrome because it requires ALPN to use the HTTP/2 protocol.

A few nginx installers do support ALPN on CentOS 6 installations. They've probably compiled the latest version of OpenSSL on their own and hence it is working with ALPN aswell. 

Engintron is my favourite Nginx installer, It would be great if you guys can also support ALPN so that HTTP/2 can be integrated on all websites in my server.

**Comment by tux-tn** [comment]
Hello @Technopope 
Please check https://github.com/engintron/engintron/issues/410 if you want to fix that in your side

**Comment by Technopope** [comment]
@tux-tn Thank you for the links :) It helped.

**Comment by fevangelou** [comment]
This is true with Chrome as far as I know. But even if you ask cPanel to upgrade CentOS, you'll get this: https://features.cpanel.net/topic/replace-openssl-with-libressl

**Comment by fevangelou** [comment]
@tux-tn I could use these 3rd party repos as an option for those interested.

**Comment by tux-tn** [comment]
@fevangelou that would be great

**Comment by fevangelou** [comment]
This Twitter conversation is interesting for the matter...

https://twitter.com/engintron_sh/status/834340201229066240
