### ISSUE TITLE
sites not served by nginx ? apache stil on port 80

### ISSUE THREAD

**Issue by TheMongooseBytes** [engintron/engintron#418]
How can I see if a website on my Cpanel server is served by nginx on port 80 ? IMHO i think it is not and sometimes Apache and Nginx (Engintron) conflict on port 80.

I had hoped to use Nginx as proxy for static normal non SSL content

**Comment by tux-tn** [comment]
You can see if the website is served by nginx by checking the returned http headers.
If the server is returning `X-Nginx-Cache-Status` and `X-Server-Powered-By : Engintron` you are good.
you can use curl to see server headers:

`curl -I http://example.com` 

Or by using the network tab of your browser devtools
(Nginx and Apache can't both listen on port 80, Apache won't start if there is a process using the same port)

**Comment by TheMongooseBytes** [comment]
@tux-tn 

No sorry

> curl -I http://example.com

only gets me this 

> HTTP/1.1 200 OK
Date: Wed, 22 Feb 2017 13:41:07 GMT
Server: Apache
Vary: User-Agent
Content-Type: text/html; charset=utf-8

**Comment by TheMongooseBytes** [comment]
@tux-tn 

No sorry that did not do it for me.

> curl -I http://example.com

Gives me the following result

> HTTP/1.1 200 OK
Date: Wed, 22 Feb 2017 13:41:07 GMT
Server: Apache
Vary: User-Agent
Content-Type: text/html; charset=utf-8

**Comment by tux-tn** [comment]
The headers show that pages are served directly by Apache
Is Engintron enabled? What does the nginx status page in engintron WHM page show?

**Comment by TheMongooseBytes** [comment]
@tux-tn 

It says Engintron is ENABLED

**Comment by TheMongooseBytes** [comment]
@fevangelou 

Any idea why this is ? I did follow your instructions on the engintron wiki. 
PS

I did not receive a response from you in terms of paid support.

**Comment by TheMongooseBytes** [comment]
Never mind I just deinstalled Engintron
