### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by itseasy21** [engintron/engintron#419]
I am facing 500 Error on all Sites, even though everything seems fine from server side.

Any suggestions what could be possible issue?

Sample URL: http://www.marathifunny.com/index.php?sort=load&id=2404

**Comment by ImLuke954** [comment]
Your site is loading fine on my end without the query string. It's probably an issue with your app not with engintron

**Comment by webhost247** [comment]
I'm having the exact same issue

**Comment by ubidzz** [comment]
Make sure that PHP open_basedir Protection is turned off and then wait a few minutes and the cronjob will run this command /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1 and it will fix your default_https.conf file.

**Comment by itseasy21** [comment]
Hi @ubidzz thanks for the suggestion, but PHP open_basedir Protection is already turned off.

**Comment by itseasy21** [comment]
ok, so finally i fixed the issue by following : https://github.com/engintron/engintron/issues/368#issuecomment-273250846 and https://github.com/engintron/engintron/issues/410#issuecomment-281283899

**Comment by itseasy21** [comment]
Had to Re-Open this issue, as at first the page started working with above solution but eventually the error came again. 
there is nothing in error log :(

**Comment by fevangelou** [comment]
Do an update to today's build. The script that builds the HTTPS blocks for Nginx was not taking into account the fact that some domains may not have a certificate installed for them.
