### ISSUE TITLE
Letsencrypt doesn't work after update to 1.8

### ISSUE THREAD

**Issue by asolopovas** [engintron/engintron#421]
Hi,
I am on WHM 62.0 (build 15). Just updated to 1.8 and it started throwing some errors. To begin with nginx would not start, pointing to /etc/nginx/conf.d/default_https.conf
```
server {
    listen 443 ssl http2;
    #listen [::]:443 ssl http2; # Uncomment if your server supports IPv6
    server_name domain.com mail.domain.com www.domain.com;
    # deny all; # DO NOT REMOVE OR CHANGE THIS LINE - Used when Engintron is disabled to block Nginx from becoming an open proxy
    ssl_certificate ;
    ssl_certificate_key ;
    ssl_trusted_certificate ;
    include common_https.conf;
}
```
The problem was that path for ssl_certificate was not included. I tried to update these manually by pointing them to /etc/letsencrypt/live/domain.com/fullchain.pem and privatekey.pem. The problem is that letsencrypt in cpanel does not store new certificates in these folders anymore for some reason. So I can'g get this to work any suggestion on what can I do? Thanks.

**Comment by asolopovas** [comment]
I have also noticed that in httpd.conf it refers to different path for these certificates
```
    SSLCertificateFile /var/cpanel/ssl/installed/certs/mail_lyntouch_com_af435_68f69_1495575300_add50b61676faef82f6a22ee7a9c96d5.crt
    SSLCertificateKeyFile /var/cpanel/ssl/installed/keys/af435_68f69_554d8feb8603d748deacf4a553d1e862.key
	SSLCACertificateFile /var/cpanel/ssl/installed/cabundles/Let_s_Encrypt_d5a69d0f2effae8513e08eaced2ccf28_1615999246.cabundle
```

Is there a way to get those to default_https automatically?

**Comment by ubidzz** [comment]
Use cPanel AutoSSL it has let's encrypt installed and all installed SSL by cPanel is listed in the httpd.conf file.

Your server is not using /etc/letsencrypt/live/ for the certs cPanel installs them in the /var/cpanel/ssl/installed/ folders unless you are using a different plugin for the let's encrypt certs. All you need is cPanel AutoSSL and that has let's encrypt that will do everything for you all you do is turn it on for the users.

This is all you need if let's encrypt is not installed in the AutoSSL.
https://blog.cpanel.com/announcing-cpanel-whms-official-lets-encrypt-with-autossl-plugin/

**Comment by asolopovas** [comment]
@ubidzz I think you misunderstood me. I am using Auto SSL in cpanel it places certificates into different folder and Enginton is not adding the paths of those in default_https.conf which causing the failure when trying to start nginx,  I could do it manually but I am afraid that autossl may be changing the names upon the renewal of certification every two months, so that would mean I would have to be amending default_https.conf  regularly to reflect the file change upon renewal. I though letsencrypt  installed manually prior Autossl feature became available.

**Comment by ubidzz** [comment]
That weird because i use AutoSSL with let's encrypt and i have no problems and i use the same paths that is shown in your httpd.conf file. I don't even have a folder path to /etc/letsencrypt/live/ on my server.

server
Centos 7.3
WHM  62 (Build 15)
EA4

**Comment by asolopovas** [comment]
Well my vps is on centos 6,  everything else is same as yours, but it doesn't work for some reason. 

⁣Sent from BlueMail ​

**Comment by tux-tn** [comment]
@asolopovas your `default_https.conf` file contains all your domains?

**Comment by asolopovas** [comment]
@tux-tn yes it does, but  path for   ssl_certificate ;    ssl_certificate_key ;    ssl_trusted_certificate ;  for each domain is blank

**Comment by tux-tn** [comment]
When you do 
```
cat /etc/apache2/conf/httpd.conf | grep SSLCertificateFile
```
Are you seeing all your certificates path?
 (httpd.conf path would be : `/usr/local/apache/conf/httpd.conf` if you are using EasyApache3)

**Comment by asolopovas** [comment]
@tux-tn yes all certificates are present, I have mentioned this already (asolopovas commented 17 hours ago • edited). I am on EasyApache4

**Comment by tux-tn** [comment]
May be you can try to run https vhost generator manually to see if there is any php error
```shell
php /etc/nginx/utilities/https_vhosts.php
```

**Comment by Shadowized** [comment]
this is the same issue as #407 , https_vhosts.php is broken and fails to parse the certs, it throws warnings in an error_log in the same folder.

**Comment by Shadowized** [comment]
I believe I debugged and solved this issue, although my php syntax understanding is a bit trash, I'm using Apache 2.4 and PHP7 if that makes any difference. anyways after poking at the https_vhosts.php file, I changed these lines on 80, 81, and 82 from this

```
preg_match("#SSLCertificateFile (.+?)\n#s", $sslBlockContents, $certfile);
preg_match("#SSLCertificateKeyFile (.+?)\n#s", $sslBlockContents, $certkey);
preg_match("#SSLCACertificateFile (.+?)\n#s", $sslBlockContents, $certbundle);
```

to this

```
preg_match("#SSLCertificateFile (.+?)\n#s", $vhost, $certfile);
preg_match("#SSLCertificateKeyFile (.+?)\n#s", $vhost, $certkey);
preg_match("#SSLCACertificateFile (.+?)\n#s", $vhost, $certbundle);
```

after that I had some warning about duplicate values related to ssl_stapling, but I think thats another issue entirely, after messing with that I then inspected the values and everything is correctly set in the generated config (/ etc/nginx/conf.d/default_https.conf ), it all seems to be in perfectly working order, nginx starts properly, and all the sites that I've enabled SSL on work perfectly.

seems it tries to get the certs from inside 
`preg_match("#\<IfModule ssl_module\>(.+?)\<\/IfModule\>#s", $vhost, $sslblock);`

but it seems my apache config doesn't store them like that, they get thrown into the VirtualHost block that binds on 443/8443, good to know that its just a regex problem though.

**Comment by fevangelou** [comment]
@Shadowized What you did just opened the regex to the entire domain block, while the original regex looks for the certificate line only if there is a "<IfModule ssl_module>..." block. It makes no difference.

What I can do though is explicitly check if there is an "<IfModule ssl_module>..." block in the first place. That should prevent any errors for folks with no certificates issued yet for their domains.
