### ISSUE TITLE
This site can’t be reached, the website refused to connect

### ISSUE THREAD

**Issue by db306** [engintron/engintron#425]
I'm getting this error message when installing 1.8
I have tried to reinstall mainline and stable versions, restarted all services, nginx apache. I haven't touched or tweaked any settings, everything as default.

Any ideas ?

**Comment by db306** [comment]
I was using WHM 60, updated to 62 and the error persist. Even restarting nginx, httpd. Out of ideas as per what could be wrong. Keeps giving me the same error on the browser when trying to access any of the websites I host: ERR_CONNECTION_REFUSED

**Comment by ubidzz** [comment]
Make sure that PHP open_basedir Protection is turned off and then wait a few minutes and the cronjob will run this command /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1 and it will fix your default_https.conf file.

**Comment by Cavain** [comment]
@db306 I got that same issue on my Nodejs website . The solution is once you Upgraded Engintron purge all cache files and disable the Engintron then re-enable it after that it will starts working . I hope it will works for you.
Have a great day!

**Comment by db306** [comment]
@ubidzz open_basedir protection is turned off, how can I force that script to run? Waiting doesn't seem to work for me.

@Cavain This didn't work for me ! :( 

any other suggestions ?

**Comment by db306** [comment]
Seems like my domains with http work but when trying to access 443 it doesn't work. So seems like things work in port 80 but not 443. Any ideas?

**Comment by ubidzz** [comment]
SSH /etc/nginx/utilities/https_vhosts.php then in WHM click Purge cache & temp files and then click restart for the nginx server.

**Comment by db306** [comment]
Running the command manually fixed my issues. Thanks

**Comment by evil4u** [comment]
This command is not working /etc/nginx/utilities/https_vhosts.php I have cPanel v76

**Comment by evil4u** [comment]
I think ngintrion is not suitable for cPanel v76

**Comment by fevangelou** [comment]
Check the log in /etc/nginx/utilities and please open a new ticket with more info.
