### ISSUE TITLE
no OCSP responder URL in the certificate

### ISSUE THREAD

**Issue by ubidzz** [engintron/engintron#429]
When i do a nginx test in WHM i am getting this error 
`nginx: [warn] "ssl_stapling" ignored, no OCSP responder URL in the certificate`
and when i do a test at ssllabs.com the OCSP stapling works when it wants to meaning there is times i have load the website in my browser a few time and then do a test and the OCSP stapling works. It don't work 100% of the time and it more like a 50/50 shot if it will work.

I get the same result when i run this command in SSH
`openssl s_client -servername my-hosted-website.com -connect my-hosted-website.com:443 -tls1 -tlsextdebug -status|grep OCSP`

It's a 50/50 shot and i get this when they do work and don't work
**Works**
```
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
```

**Didn't work**
`OCSP response: no response sent`

I do notice after a successful OCSP like after 5 minutes later the test will fail or have to run the test more then 1 time and get lucky it use OCSP stapling.

**Comment by fevangelou** [comment]
Simply comment out the OCSP lines in /etc/nginx/common_https.conf

**Comment by ubidzz** [comment]
The wouldn't that stop using OCSP and i been testing it and seems the first connection wont enable OCSP and if i do a test again on the same domain then OCSP is enable on the 2nd test.

**Comment by fevangelou** [comment]
OCSP was built to relieve CA servers from traffic. If OCSP is off, browsers will ping CA servers. This is normal.
