### ISSUE TITLE
User gets Auto logged out of Xenforo

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#434]
Hello,

Why I am getting auto logout issue, problem with xenforo sessions? Also have issue users I'm being logged as a different user, A strange thing happening, Every time I am logging in, I'm being logged as a different user (probably with the ID's in my friend's list). After one or two refresh; I am being logged as prinanad. This is happening in every browser, with different Ids also. logged into my xenforo forum started showing up under other logged-in users' sessions, gaining full access to the other person's account. Including mine. Not good. Unsure if the problem affected other session stuff.

Logout and Login demo: https://drive.google.com/file/d/0B2u7wGh_C3_LV0VYMmc1aE9IWGs/view?usp=sharing

**Comment by WebSavvyGuy** [comment]
There are alot of related tickets about this.  It has to do with the micro-caching and you can turn them off for your forums (dynamic content).  Try a search in the closed tickets.

**Comment by Nirjonadda** [comment]
@WebSavvyGuy I have not find out any real solutions. Please do you have any chance to find out the solutions for me?

Thanks

**Comment by WebSavvyGuy** [comment]
But you even commented in one of the threads im referring to. https://github.com/engintron/engintron/issues/12

**Comment by Nirjonadda** [comment]
@WebSavvyGuy disable micro-caching for dynamic content. Comment out line 70 in default.conf via Engintron's WHM app.

Is this correct ?

>  location @backend {
        include proxy_params_common;
        # === MICRO CACHING ===
        # Comment the following line to disable 1 second micro-caching for dynamic HTML content
        #include proxy_params_dynamic;
    }

**Comment by WebSavvyGuy** [comment]
Actually for our forums i just used this section:

`#if ($SITE_URI ~* "example.com|example2.com/path|example3.com/some/other/path|subdomain.example4.com") {
#    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
#    set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching`

**Comment by Nirjonadda** [comment]
> location @backend {
include proxy_params_common;
# === MICRO CACHING ===
# Comment the following line to disable 1 second micro-caching for dynamic HTML content
#include proxy_params_dynamic;
}

I am used this option but still are not fixed auto logout or login issue.

**Comment by Nirjonadda** [comment]
@WebSavvyGuy , I am adding this to on my the custom rules at the bottom. Is this correct?

if ($SITE_URI ~* "mysite.com|mysite.com/index.php?login/|mysite.com/login|/register|/logout|/admin.php") {
set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
#set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching

Is this correct?

if ($SITE_URI ~* "mysite.com|/index.php?login|/login|/register|/logout|/admin.php") {
set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching

**Comment by Nirjonadda** [comment]
@fevangelou I found one more steps. Does its correct way better to add exceptions in my "custom rules" file ?

> if ($request_uri ~* "/login|/register|/logout|/admin.php") {
    set $CACHE_BYPASS 1;
    set $EXPIRES_FOR_DYNAMIC 0;
}

**Comment by Nirjonadda** [comment]
@ubidzz Do you have any solution for this issue? I am now using this. Does this correct steps?

if ($SITE_URI ~* "mysite.com|mysite.com/login|mysite.com/register|mysite.com/logout|mysite.com/admin.php") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
#    set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching

**Comment by fevangelou** [comment]
@Nirjonadda you are spamming the project's GitHub issues for anything that may come up in your mind. If I see one more such post when all the info you need is in the Wiki, I will be forced to ban you from this project's Issues section.
