### ISSUE TITLE
Reboot Virtual Server - Nginx Status failed

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#439]
I am doing Reboot Virtual Server now Nginx Status failed, Not working. Please let me know the fix.

Nginx Status:

Redirecting to /bin/systemctl status  nginx.service
● nginx.service - nginx - high performance web server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2017-02-25 21:02:22 BDT; 3min 5s ago
     Docs: http://nginx.org/en/docs/
  Process: 9767 ExecStartPre=/usr/sbin/nginx -t -c /etc/nginx/nginx.conf (code=exited, status=1/FAILURE)
 Main PID: 6049 (code=exited, status=0/SUCCESS)

Feb 25 21:02:22 sa.mysite.com systemd[1]: Starting nginx - high performance web server...
Feb 25 21:02:22 sa.mysite.com nginx[9767]: nginx: [emerg] unexpected end of file, expecting "}" in /etc/nginx/custom_rules:99
Feb 25 21:02:22 sa.mysite.com nginx[9767]: nginx: configuration file /etc/nginx/nginx.conf test failed
Feb 25 21:02:22 sa.mysite.com systemd[1]: nginx.service: control process exited, code=exited status=1
Feb 25 21:02:22 sa.mysite.com systemd[1]: Failed to start nginx - high performance web server.
Feb 25 21:02:22 sa.mysite.com systemd[1]: Unit nginx.service entered failed state.
Feb 25 21:02:22 sa.mysite.com systemd[1]: nginx.service failed.

----------------------------------
Nginx Status:

Redirecting to /bin/systemctl status  nginx.service
● nginx.service - nginx - high performance web server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2017-02-25 21:07:01 BDT; 45s ago
     Docs: http://nginx.org/en/docs/
  Process: 10679 ExecStartPre=/usr/sbin/nginx -t -c /etc/nginx/nginx.conf (code=exited, status=1/FAILURE)
 Main PID: 6049 (code=exited, status=0/SUCCESS)

Feb 25 21:07:01 sa.mysite.com systemd[1]: Starting nginx - high performance web server...
Feb 25 21:07:01 sa.mysite.com nginx[10679]: nginx: [emerg] unexpected end of file, expecting "}" in /etc/nginx/custom_rules:99
Feb 25 21:07:01 sa.mysite.com nginx[10679]: nginx: configuration file /etc/nginx/nginx.conf test failed
Feb 25 21:07:01 sa.mysite.com systemd[1]: nginx.service: control process exited, code=exited status=1
Feb 25 21:07:01 sa.mysite.com systemd[1]: Failed to start nginx - high performance web server.
Feb 25 21:07:01 sa.mysite.com systemd[1]: Unit nginx.service entered failed state.
Feb 25 21:07:01 sa.mysite.com systemd[1]: nginx.service failed.
Feb 25 21:07:22 sa.mysite.com systemd[1]: Unit nginx.service cannot be reloaded because it is inactive.

**Comment by Nirjonadda** [comment]
@fevangelou This issue happened with option "Edit your custom_rules for Nginx" Not working nginx with any custom rules.

**Comment by tux-tn** [comment]
it looks like you have a typo error in your custom_rules file, can you try to find the error or paste the file here (don't forget to remove any sensitive data)

**Comment by Nirjonadda** [comment]
@tux-tn only added rules for non-www URL and one comment the line.

> #####################################################################
# === Place your custom Nginx rules here ===
#
# [comments used below updated for Engintron v1.8.0]
#
# Some examples:
# - HTTP to HTTPS redirect when using CloudFlare
# - Setting up domains with dedicated IPs on the system
# - Any other global rule (redirect or process)
#
#####################################################################

# === FOR USE WITH CLOUDFLARE ===
# For up to date info see the Engintron wiki at: https://github.com/engintron/engintron/wiki
#
# a) If your server has a single shared IP ONLY and you wish to use CloudFlare for any (or all) of your sites
#    you will have to specify this shared IP address below otherwise you'll get errors from CloudFlare.
#    This change will simply tell Nginx to skip DNS resolving and simply forward traffic to the shared IP.
#    Uncomment the following line if all your sites on the shared (main) IP of your server are on CloudFlare:
#
#set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX"; # Use your cPanel's shared IP address here
#
# b) If you utilize CloudFlare on a cPanel server with BOTH a shared IP and dedicated IPs for domains, you will
#    have to set the IP ONLY for each such domain at the "WHEN TO SPECIFY A DOMAIN IP" section lower in this file.
#
# c) It is possible to force-redirect all your domains on CloudFlare to HTTPS if you have SSL enabled
#    in CloudFlare's "Crypto" settings page. Make sure you use "Flexible SSL" there so CloudFlare proxies
#    traffic from HTTPS to Nginx's HTTP port (80). This way you can utilize Nginx's caching & performance
#    benefits to the fullest. If you use "Strict SSL" in CloudFlare's "Crypto" settings page, then CloudFlare
#    will proxy all HTTPS requests to your Apache's HTTPS port (443) and therefore you will miss any benefits
#    from Nginx's caching & overall performance features.
#    To redirect to HTTPS, simply remove ONLY the FIRST # character from each line of the following block
#    and make sure you set the domains you DO NOT want to automatically redirect to HTTPS.
#
# # === Protocol redirect handling when using CloudFlare [start] ===
#
# set $redirToSSL "";
# if ($http_cf_visitor ~ '{"scheme":"http"}') {
#     set $redirToSSL "on";
# }
#
# # Set each domain you DO NOT want to automatically redirect to HTTPS when using CloudFlare only below
# # and repeat the process with additional "if" blocks for more domains
#
# if ($host ~ 'domain-to-exclude-from-redirect.com') {
#     set $redirToSSL "off";
# }
# if ($redirToSSL = "on") {
#     return 301 https://$host$request_uri;
# }
#
# # === Protocol redirect handling when using CloudFlare [finish] ===



# === WHEN TO SPECIFY A DOMAIN IP ===
# By default, Nginx will redirect requests to the right domain IP by using DNS resolving.
# However there are cases where you want to specify an IP for use with Nginx:
# - When you use CloudFlare for certain domains only on your server,
#   regardless of whether these domains use the server's shared IP or a dedicated IP.
# - When you are working on a domain which does not yet (DNS) resolve to your server,
#   but you want to access it by modifying your computer's "hosts" file.
#
# To specify the domain IP in such cases, simply enter a domain or subdomain in an "if" block
# (as shown below) and inside that block set the appropriate shared or dedicated IP to point to.
#
# To specify the IP for a domain simply uncomment the following 3 lines and make sure you replace
# example.com with your actual domain or subdomain and also replace XXX.XXX.XXX.XXX with the actual
# IP assigned to that domain. To specify the IP for more domains, simply copy that "if" block
# (per domain) and change accordingly.
#
#if ($host ~ "example.com") {
#    set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX";
#}



# === DOMAIN AND URL PATH EXCLUSIONS FROM CACHING ===
# If you wish to exclude certain domains, subdomains or even full URL paths from micro-caching and/or
# static file caching, simply specify them below and use a colon (|) character as a separator.
# Remember that if you specify a "naked" domain name, e.g. mynicedomain.com, every subdomain e.g.
# support.mynicedomain.com will also be excluded from caching. Decide wisely!
# If you wish to disable ONLY micro-caching, then comment the line "set $CACHE_BYPASS_FOR_STATIC".
# If you wish to disable ONLY static file caching, then comment the line "set $CACHE_BYPASS_FOR_DYNAMIC".
#
# Note: Don't include the "http://" portion of a URL.
#
if ($SITE_URI ~* "mysite.com|mysite.com/login|mysite.com/register|mysite.com/logout|mysite.com/admin.php") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
#    set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
#}

if ($host = 'mysite.com' ){
    rewrite ^/(.*)$ $scheme://www.mysite.com/$1 permanent;
}

**Comment by tux-tn** [comment]
Can you please edit your comment to use syntax highlighting for code, the actual form is a complete mess.

You can use this markdown code:

    ```nginx
    [your code here]
    ```

**Comment by Nirjonadda** [comment]
@tux-tn Fixed, Please check now.

**Comment by tux-tn** [comment]
the closing brace of your first rule is commented, try to uncomment it and restart nginx

**Comment by Nirjonadda** [comment]
@tux-tn Like this?

```nginx
if ($SITE_URI ~* "mysite.com|mysite.com/login|mysite.com/register|mysite.com/logout|mysite.com/admin.php") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
#set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}
```

**Comment by tux-tn** [comment]
Yes!
Could you try?
