### ISSUE TITLE
Engintron is DISABLED - Nginx  Status

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#440]
If Engintron is DISABLED - Nginx  Status page are not loading correctly.

Ex: http://image.prntscr.com/image/8c8adab3e4bd493581924c421a7a00ce.png

**Comment by Nirjonadda** [comment]
@fevangelou  Sorry, I am not a spammer and I like to let you know that what issue I have found from Engintron. If this Ways to Improve our Engintron Product? Are you still like to ban me from this project?

**Comment by fevangelou** [comment]
Are you 100% sure you haven't edited engintron.php?

**Comment by Nirjonadda** [comment]
@fevangelou Yes i have edited engintron.php from this post https://github.com/engintron/engintron/pull/433/commits/0daa6342bcbc8b79289e07480c69de7fa0fdee3f Is this any issue happen with engintron.php?

````
/scripts/restartsrv_mysql
````
To
````
service mysqld restart
````
````
service mysql status
````
To
````
service mysqld status
````

**Comment by fevangelou** [comment]
Then your edit simply broke the syntax in the file. So is this a problem with Engintron? I don't think so...
