### ISSUE TITLE
Problems with port 80

### ISSUE THREAD

**Issue by rauliox** [engintron/engintron#441]
Hello, I have installed engintron  and  the apache port has changed to 8080 (as it was supposed) .
I realized that the website is working  in this url : www.website.com:8080 but when i opened www.website.com  -  there was an error message.

Error 1000 Ray ID: 336ef471e38d1858 • 2017-02-25 23:32:08 UTC
DNS points to prohibited IP  (Cloudflare error)
https://gyazo.com/4c3415ace5e32e0382d3d7f58e36bbad   (The ip is well configured in cloudflare)

Before install Engintron everything was working fine in the port 80.

I am also using cloudflare and the services nginx and httpd are up.

Here some details about what i am using :
CENTOS 6.8 /WHM 62 / easyapache4 with mod_remoteip(to get the real ip of cloudflare )

I would apreciate some advices , Thanks.

**Comment by itseasy21** [comment]
Have a look at this; https://github.com/engintron/engintron/wiki/Engintron-&-CloudFlare

**Comment by rauliox** [comment]
Very usefull advice,the problem was solved.
Thanks @itseasy21
