### ISSUE TITLE
Add option to enable custom nginx repo with ALPN support

### ISSUE THREAD

**Issue by tux-tn** [engintron/engintron#442]
Many people are asking about ALPN/H2 support as seen in #410 #417 #435 #437 

We should have an option to choose between nginx officiel repo and the one provided by CodeIT (See #368 ) to let people easily  switch between them.

Or at least let's add a wiki entry to explain how to enable CodeIT repo and have Nginx with latest OpenSSL version.

May be i will create a pull request containing the necessary modifications to enable that option

**Comment by tux-tn** [comment]
I find out another Nginx repo : https://github.com/istenrot/centos-nginx-http2 providing prebuild packages built against OpenSSL 1.1.0 (Support for ChaCha20-Poly1305 and X25519 ECDH) and nginx pagespeed module (bortli_ngx is not enabled but i already asked for support and they said that they will look into it)

I changed the Issue title from `Add option to enable CodeIT nginx repo` to `Add option to enable custom nginx repo with ALPN support`.

**Comment by fevangelou** [comment]
I fully understand your kind intentions, but this is beyond what I wish to offer for cPanel. Firstly, I don't trust 3rd party repos. Secondly, this is something either CentOS or cPanel will have to deal with pretty soon as the installed version of OpenSSL is outdated in CentOS and it's the only real obstacle to support HTTP/2 (because of the lack of ALPN support).

It's best to just fork Engintron and do your modifications. That's why it's open source.

**Comment by tux-tn** [comment]
Thank you for your response, i understand your motivations and the need to maintain the appropriate balance between stability, security and new features providing. 

May be people concerns about ALPN can be adressed in a wiki page proposing the appropriate suggestions about it.

**Comment by fevangelou** [comment]
The wiki is open to contributions. If you wish to write an article about it, I'd be happy to have it included.

**Comment by BOPOHA** [comment]
You can build and use your own COPR repo, like me: https://copr.fedorainfracloud.org/coprs/vorona/nginx-alpn/

    $ nginx -V
    nginx version: nginx/1.11.10
    built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
    built with OpenSSL 1.1.0e  16 Feb 2017

**Comment by tux-tn** [comment]
@BOPOHA still the same Trust issues, COPR is a 3rd party community project and is not supported by Fedora

**Comment by BOPOHA** [comment]
YES, Copr is not yet officially supported by Fedora Infrastructure.
My main message is that openssl is only **Buildrequires** for NginX.
I gave you the specs, you can compile it anywhere, without COPR.

**Comment by Nirjonadda** [comment]
@fevangelou EasyApache 4 added HTTP2 Support: https://features.cpanel.net/topic/htt2-support

**Comment by fevangelou** [comment]
@Nirjonadda cPanel build their own versions of Apache either way, so they can bundle Apache with OpenSSL latest in their RPMs. Engintron uses Nginx's official repos.
