### ISSUE TITLE
Serving up Brotli with Engintron Nginx

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#443]
Please can you add Brotli Support with Nginx? Enable Brotli compression in Engintron.

How it Works With the Browser: https://st.ayesh.me/files/static/node/150/brotli-comparison.png

More Info here: https://afasterweb.com/2016/03/15/serving-up-brotli-with-nginx-and-jekyll/

Nginx has a Brotli extension: https://github.com/google/ngx_brotli

Nginx has a Brotli extension offered by Google requiring you to compile Nginx by yourself in order to use it.

**Comment by wp-networks** [comment]
...perhaps [#442](https://github.com/engintron/engintron/issues/442) might address brotli as well?

**Comment by fevangelou** [comment]
Off-topic.

**Comment by Nirjonadda** [comment]
@fevangelou Are still thinking its off-topic of brotli_compression? Brotli is a relatively new compression format that provides 20% more compression over deflate.

**Comment by fevangelou** [comment]
Yes, very much off-topic as it is NOT SUPPORTED BY NGINX REPOS OFFICIALLY.
