### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by highacid** [engintron/engintron#445]
Hi,

I have upgraded to latest version, HTTPS works, yet all my cpanel hosted sites, fail after 2 3 days from running nginx with 502 errors, or not being available at all. Anyone any ideas on this? There was a previous thread who got many but useless replies to this issue. I have searched on my own, and did many upgrades in engintron since, nothing helped. I would like to use it, and is a great job here alto it was taking a long road to get here... Yet such small glitches are not to be happening, this comes from nowhere and disables all sites.

`2017/02/26 21:02:35 [warn] 10379#10379: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:10
2017/02/26 21:02:35 [emerg] 10379#10379: BIO_new_file("/var/cpanel/ssl/cpanel/mycpanel.pem") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/var/cpanel/ssl/cpanel/mycpanel.pem','r') error:2006D002:BIO routines:BIO_new_file:system lib)
2017/02/26 21:02:56 [error] 9980#9980: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:unable to get issuer certificate) while requesting certificate status, responder: ocsp1.wosign.com
2017/02/26 21:03:28 [error] 9980#9980: *1 connect() failed (110: Connection timed out) while connecting to upstream, client: 68.180.231.62, server: localhost, request: "GET /?p=1325 HTTP/1.1", upstream: "http://151.80.200.229:8080/?p=1325", host: "highpassion.ch"
2017/02/26 21:03:36 [error] 9980#9980: *5 connect() failed (110: Connection timed out) while connecting to upstream, client: 89.102.21.128, server: localhost, request: "GET / HTTP/1.1", upstream: "http://151.80.200.229:8080/", host: "maexont.com"`

**Comment by highacid** [comment]
Upon disabling Engintron all sites works fine.

**Comment by fevangelou** [comment]
Cool for you. And stop double-posting or you'll be banned for good.

**Comment by highacid** [comment]
@fevangelou well if someone would give some resolution that helps I am sure no one will double post, or without to close threads if they are not solved... I was thinking this is the meaning of this all. Feel free to ban me, if that makes you feel better, or that you solved something by it.

**Comment by fevangelou** [comment]
Stop whining. Here and in cPanel forums. And upgrade Engintron.
