### ISSUE TITLE
NETSTAT - Visitor's Real IP

### ISSUE THREAD

**Issue by rauliox** [engintron/engintron#447]
Hello, I am using cloudflare / nginx (engintron) / apache and everything is working Fine ( I have configured nginx and apache and i  can see the real ip of the visitor in the logs).

I want to discard that  my server is receiving DDOS attacks  and i am trying to see the connections on port 80  sorted by IP , using the follow  command.

netstat -anp | grep :80 | awk '{print $5}' | cut -d: -f1 | sort | uniq -c | sort -n

But when i execute this command i still get the cloudflare ip.  
there is something that need to be configured? or another way to identify the amount of connections by real ip?

Any suggestion is welcome, Thanks a lot.

**Comment by fevangelou** [comment]
It's normal to see CF IPs using Engintron's built-in traffic utilities, because CF is proxying outside traffic to your server. If you are under DDoS, CF has tools to mitigate that, but I'm sure they do that automatically.

**Comment by rauliox** [comment]
Thanks for the answer.
Of course cloudflare helps, that is why my site always is up , but i have to activate the mode "I'm Under Attack" , and after that , the problem is solved. 
I was trying to ban in realtime the ips watching the number of connections, But it seems there is not much information, however i have realized that analysing logs throught ssh it's really powerful.
