### ISSUE TITLE
Disable engintron on Https on one domain

### ISSUE THREAD

**Issue by omarkhatibco** [engintron/engintron#448]
Hello 
Since  I update Engintron to 1.8 one of my client start to complain that he has a problem with his website 
he uses ssl and https 

so how I can Exclude his website from https caching like 1.7 https works with apache only

**Comment by fevangelou** [comment]
You can disable caching (which is what your client probably complains about). But you can't switch off Nginx HTTPS and pass to Apache HTTPS for one domain only.
