### ISSUE TITLE
after i have install engintron sites not working

### ISSUE THREAD

**Issue by foxpcteam** [engintron/engintron#449]
Hi,
I have fresh centos7 with one website using ssl.
I have open the ports as asked [here](https://github.com/engintron/engintron/wiki/Restrict-access-to-ports-8080-&-8443-used-by-Apache-only-for-Nginx)
my website working fine when engintron is off.
error log:
`2017/02/27 19:49:44 [error] 29296#29296: *1 connect() failed (110: Connection timed out) while connecting to upstream, client: 77.126.4.89, server: mysite.com, request: "GET /deals/view/6011377 HTTP/1.1", upstream: "https://205.154.70.110:8443", host: "www.mysite.com"`

what i need to do to make the website work with engintron? 

Thanks

**Comment by fevangelou** [comment]
What was it?

**Comment by rockethost-israel** [comment]
i was working with localhost. so i have add this code:

if ($host ~ "example.com") {
    set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX";
}

**Comment by foxpcteam** [comment]
i was working with localhost. so i have add this code:

if ($host ~ "example.com") {
set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX";
}
