### ISSUE TITLE
Any upgrade?

### ISSUE THREAD

**Issue by lafrance** [engintron/engintron#450]
Hello!

As for version 1.8.0 break most server can we expect an update or upgrade soon?

**Comment by dcordovez** [comment]
Just to comment my experience:
I use Engintron for a long time without any problem on 7 servers, even in 2 I was already using HTTPS manually modifying the configuration files for the sites that required it.
He had not updated to 1.8 just for all the error messages he had seen here; However two days ago I went to update two of the servers where I have less clients, and the result was perfect. The only detail (which in reality is nothing) was that after updating I had to restart Apache. All my servers have Centos 6.8, WHM 62.0 and I do not use cloudlinux.

**Comment by Nirjonadda** [comment]
@fevangelou Please update with ALPN support and bug fix update.

**Comment by lafrance** [comment]
seem the problem is with nginx[22527]: Stopping Nginx daemon: nginxcat: /var/run/nginx.pid

for ALPN no idea what that all about sorry :(

**Comment by ngnmedia** [comment]
We have also upgraded to version 1.8 but after that on one server all SSL domains worked fine on all others https sites went down so we had to disable Engintron.

**Comment by fevangelou** [comment]
@Nirjonadda ALPN support is OpenSSL dependent, aka OS dependent. Either CentOS or cPanel should address this.

As for the original question, upgrade for what? v1.8.0 is working just fine.

**Comment by ngnmedia** [comment]
Why then disabling Engitron SSL and HTTPS started working as they should?

**Comment by Nirjonadda** [comment]
@fevangelou But other cPanel nginx plugin support ALPN without OS OpenSSL. 

cPnginx, XtendWeb, ApacheBooster Enabled http2 and ALPN support.

**Comment by fevangelou** [comment]
@Nirjonadda use those then
@ngnmedia How the heck should I know. Did you provide any meaningful info for me to debug. You're just saying "it doesn't work": http://importblogkit.com/2015/07/does-not-work/

**Comment by lafrance** [comment]
Hello!
Here my erros

Dec 20 13:48:06 server.XXX.XX nginx[22527]: Stopping nginx daemon: nginxcat: /var/run/nginx.pid: No such file or directory
Dec 20 13:48:06 XXX.XX nginx[22527]: kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Dec 20 13:48:06 XXX.XXnginx[22527]: not running.

**Comment by fevangelou** [comment]
@lafrance Check your email Pierre ;)
