### ISSUE TITLE
php-cgi cpu usage went through the roof

### ISSUE THREAD

**Issue by wislem** [engintron/engintron#451]
After upgrading to 1.8.0 php-cgi cpu usage went through the roof!

Apache is listening to 8080 and 8443. Https sites open up properly. Everything seems fine apart from the overall cpu usage of PHP.

gossipgr user has the most visited website on my server

![image](https://cloud.githubusercontent.com/assets/1381586/23404875/f7bb1e92-fdbf-11e6-9f91-010c1e518baf.png)

**Comment by fevangelou** [comment]
What was it?

**Comment by wislem** [comment]
Accidentaly closed it...

**Comment by fevangelou** [comment]
First off, don't use plain CGI. FastCGI does a much better job. Secondly, unless PHP usage is steadily high, seeing usage spikes is normal while Nginx is warming its cache.

**Comment by wislem** [comment]
I'm using EasyApache 4 and a setup with Apache mpm-event. This configuration only offers cgi and suphp as handler options.

I changed the gossipgr user to PHP 7 and suphp. Seems a bit better. Usage went down from 12 to ~6.

EA4 setup below:
```
Current Profile

The currently installed packages on the server.

Apache 2.4
config
config-runtime
mod_bwlimited
mod_cgid
mod_deflate
mod_env
mod_expires
mod_headers
mod_mpm_event
mod_proxy
mod_proxy_fcgi
mod_proxy_http
mod_remoteip
mod_security2
mod_ssl
mod_suexec
mod_suphp
mod_unique_id
tools
PHP 5.6
build
libc-client
pear
php-bcmath
php-bz2
php-calendar
php-cli
php-common
php-curl
php-dba
php-debuginfo
php-devel
php-enchant
php-exif
php-fileinfo
php-fpm
php-ftp
php-gd
php-gettext
php-gmp
php-iconv
php-imap
php-intl
php-ldap
php-litespeed
php-mbstring
php-mcrypt
php-mysqlnd
php-odbc
php-pdo
php-posix
php-process
php-pspell
php-snmp
php-sockets
php-sourceguardian
php-xml
php-xmlrpc
php-zendguard
php-zip
runtime
PHP 7.0
build
libc-client
pear
php-bcmath
php-bz2
php-calendar
php-cli
php-common
php-curl
php-dba
php-devel
php-enchant
php-exif
php-fileinfo
php-fpm
php-ftp
php-gd
php-gettext
php-gmp
php-iconv
php-imap
php-intl
php-litespeed
php-mbstring
php-mcrypt
php-mysqlnd
php-odbc
php-opcache
php-pdo
php-posix
php-process
php-pspell
php-snmp
php-sockets
php-xml
php-xmlrpc
php-zip
runtime
Others
apr
apr-util
cpanel-tools
documentroot
libmcrypt
modsec-sdbm-util
php-cli
php-cli-lsphp
profiles-cpanel
```

**Comment by fevangelou** [comment]
Engintron installs "htop" as well, which is much better visually compared to plain "top". Just type "htop" ;)

**Comment by fevangelou** [comment]
Closing as resolved for now.

**Comment by wislem** [comment]
It's more steady now at ~7.5 load. I don't know if it's a proper value to be honest :)

![image](https://cloud.githubusercontent.com/assets/1381586/23405789/980577c2-fdc4-11e6-8c96-0d0107c1c7b9.png)

There is 1 large traffic-wise website in there. I don't know if nginx can mitigate all of those spikes (facebook traffic) and keep the server load below 2 or 1.

**Comment by fevangelou** [comment]
The load is fine. Consider improving your MySQL config though. More here: https://github.com/engintron/engintron/wiki/Beyond-Engintron:-Optimizing-MySQL

**Comment by ImLuke954** [comment]
What is the spec of your server? I am actually handling massive traffic spike from facebook (thanks to @fevangelou ) and the load doesn't even reach go beyond 1.

**Comment by wislem** [comment]
@ImLuke954 I would love if you shared your EA4 setup etc, if it would be compatible with mine.

I'm on a VPS with the specs shown below:
8 GB RAM
4 CPU Cores
110 GB SSD Storage
8 TB Monthly Transfer
Centos 7 64bit
Latest cPanel

**Comment by ImLuke954** [comment]
Traffic spike is a subjective term and as such it won't be wise to suggest you anything without knowing the actual scenario. Still you can try extending the micro cache to 1m from the default 1s. And also you can try memcache for caching database queries. Hope that helps.
