### ISSUE TITLE
NPN support

### ISSUE THREAD

**Issue by seebeen** [engintron/engintron#452]
Is there a possibility for NPN support down the road? 

It requires nginx to be compiled against latest version of OpenSSL, and I don't know if that's feasible on cPanel machines.

**Comment by ubidzz** [comment]
check this comment because it the only way to get a updated version of OpenSSL for Nginx with NPN and 100% http/2 for all your hosted websites.

**Comment by seebeen** [comment]
So I just need to add the repo and run the engintron update script?
This will install latest nginx and OpenSSL?

**Comment by seebeen** [comment]
Yes, I just verified it. Adding the codeIT repo enables ALPN.
