### ISSUE TITLE
Chksrvd restarting Apache

### ISSUE THREAD

**Issue by kuteninja** [engintron/engintron#453]
Please, update the file `/etc/chkserv.d/httpd` so that it doesn't check port 80 and checks 8080 instead.

Also add a new `/etc/chkserv.d/nginx` so that if the port 80 fails nginx gets restarted. You could use the same httpd check slightly modified...

```
service[nginx]=80,GET / HTTP/1.0,HTTP/1..,/etc/init.d/nginx restart
```

I think you're editting the httpd one but it get's overriten every time I change something on the Service Manager or if tailwatchd is restarted

**Comment by fevangelou** [comment]
Planned for 1.8.2.

**Comment by ImLuke954** [comment]
After updating to engintron 1.8.2, chksrvd is still monitoring Apache in port 80

> service[httpd]=80,GET`/ HTTP/1.0,HTTP/1..,killall -TERM httpd;sleep 2;killall -9 httpd;/etc/rc.d/init.d/httpd stop;/etc/rc.d/init.d/httpd startssl;/usr/local/apache/bi$

**Comment by fevangelou** [comment]
Disable & re-enable Engintron. It should fix Apache's port.

**Comment by petarkozic** [comment]
@fevangelou 
"Disable & re-enable Engintron. It should fix Apache's port."

This not resolve problem with chkserv.d and httpd listening on port 8080 .
Centos 6.8 > WHM 64 > Engintron 1.8.4

**Comment by fevangelou** [comment]
@petarkozic Re-install then. I can't verify your issue and I manage dozens of servers with various setup combinations.
