### ISSUE TITLE
502 error and website unreachable only on 1 specific domain

### ISSUE THREAD

**Issue by odysseas12** [engintron/engintron#454]
I started getting 502 only on one specific domain. Everything was running fine until today.

Was running Engitron 1.8.0, CENTOS 7.3, WHM 62.0 (build 16) 

I updated to the latest version Nginx Stable.

502 on all SSL websites had to restart apache to get things working.

5 minutes later same website was giving a 502 error. Cleared cache and restarted apache and nginx and it was working again.

At some point it stop working again.

Reinstalled Nginx mainline same website same 502 error.

On thing I notice is that the website would function normally for some time and I would visit it again and it would give a 502 error. Or I had it open in Chrome and browsing it normally but in Firefox it would give a 502.

In the error log I have alot of errors like the one below

2017/03/02 04:35:43 [error] 2120#2120: *790 www.mydomain.com could not be resolved (2: Server failure), client: MYIP, server: mydomaincom, request: "GET /review/proposal HTTP/1.1", host: "www.mydomain.com"

Let me know if you need any more information.

**Comment by odysseas12** [comment]
This most probably is a problem with the dns servers. 
Im using external dns servers for this domains from godaddy and they seem to be having issues at this time. 
NS47.DOMAINCONTROL.COM
NS48.DOMAINCONTROL.COM
I will update once I investigate further.

**Comment by fevangelou** [comment]
That would explain why sometimes it works and other times it doesn't. Let me know how it goes.

**Comment by mdvaldosta** [comment]
I'll get 502 (111: Connection refused) errors in Nginx if DNS resolves to an IP not on the server. This happened today when I used a hardcoded hosts file on my computer to access a client website I just transferred in from another server, but they had not yet updated their nameservers. What I would see is that the upstream IP matched their old server, thus triggering the refusal.

 I resolved this by adding a custom Nginx rule that would force the connection until the customer updated their nameserver:

```
if ($host ~ "somewebsite.com") {
    set $PROXY_DOMAIN_OR_IP "xx.xx.xxx.xxx";
}
```

I also had an issue once where a website with a bad SSL was getting 502 refused by Nginx, and fixing the SSL solved it.

**Comment by odysseas12** [comment]
The problem seems to have fixed it self now that the dns servers are ok.
I disabled engintron temporarily and the 502 error was replaced by a dns_probe_finished_nxdomain error.
Also my ftp client would have problems resolving the domain so we can safely say it wasnt anything wrong with the nginx or apache or ssl related.
