### ISSUE TITLE
could not be resolved (2: Server failure)

### ISSUE THREAD

**Issue by inventivo** [engintron/engintron#455]
After Upgrading to 1.8 I frequently get the error "could not be resolved (2: Server failure)"
Sites are available some time and then get unavailable again and again. The whole thing seems not to be reliable any more as in 1.7.
http:// only websites now get redirected to https.
Am I missing somthing?

**Comment by fevangelou** [comment]
There is no rule in Engintron to redirect HTTP to HTTPS traffic.

The "could not be resolved" error you get is probably related to Apache shutting down.

I released v1.8.2 today (just hit re-install in the Engintron WHM app) and it adds process controls for both Nginx & Apache (for the right ports) in cPanel's TailWatch service. This means that cPanel constantly monitors these 2 services and if any one of them stops and automated restart is attempted.

**Comment by inventivo** [comment]
When I transfer a non ssl site from another WHM server to the one i am talking about above, do i have to take any addiotnal actions regarding engintron than using the transfer tool?

**Comment by fevangelou** [comment]
Not really. But do check for any .htaccess rules causing the redirect from HTTP to HTTPS. Additionally, I would recommend you install LetsEncrypt (https://documentation.cpanel.net/display/CKB/The+Let's+Encrypt+Plugin) and re-issue certificates for all your domains. Then clean Nginx's cache from the Engintron WHM app and simply restart Apache/Nginx.

**Comment by inventivo** [comment]
ok, do i have to manually delete default_https.conf in order to get the latest values or is this file autoupdates on every restart?

**Comment by fevangelou** [comment]
It is updated if a change in Apache is detected. That check in Apache runs every 10 seconds. So the entire process is automated.

**Comment by inventivo** [comment]
uhh. In the end I noticed that the google public dns (8.8.8.8, 8.8.4.4) I use in my wlan config seem to make problems today. Seems that this was totally intefering with all my reinstall and restart and ... actions... 

anyone else who can confirm this?

**Comment by fevangelou** [comment]
I doubt Google's Public DNS went down :) Perhaps you experienced network issues on your server's side.
