### ISSUE TITLE
Engintron not open script

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#457]
Hello, I'm trying to put a pop-up ad script, but engintron does not work, it shows the script code on the screen and not the pop up.

SEE Print: http://prnt.sc/efbyay

With apache it opens the script normally. Must disable the engintron to work, see: http://prnt.sc/efbzee

**Comment by fevangelou** [comment]
Engintron does not mess with code/script parsing. It only proxies traffic.

Something else is wrong. Double-check.
