### ISSUE TITLE
The service “tailwatchd” appears to be down error message

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#458]
Just upgraded to 1.82 Engintron.

Received this Cpanel error message:

Service Name tailwatchd
Service Status	failed ⛔
Notification	The service “tailwatchd” appears to be down.
Service Check Raw Output	(XID qrf8mg) The “tailwatchd” service is down.
Startup Log	Mar 03 00:46:16 server.myhostname.com systemd[1]: Starting tailwatchd...
Mar 03 00:46:16 server.myhostname.com systemd[1]: PID file /var/run/tailwatchd.pid not readable (yet?) after start.
Mar 03 00:46:16 server.myhostname.com restartsrv_tailwatchd[2015]: [Fri Mar 3 00:46:16 2017] Starting /usr/local/cpanel/libexec/tailwatch/tailwatchd daemon
Mar 03 00:46:16 server.myhostname.com restartsrv_tailwatchd[2015]: Log is at /usr/local/cpanel/logs/tailwatchd_log
Mar 03 00:47:46 server.myhostname.com systemd[1]: tailwatchd.service start operation timed out. Terminating.
Mar 03 00:47:46 server.myhostname.com systemd[1]: Failed to start tailwatchd.
Mar 03 00:47:46 server.myhostname.com systemd[1]: Unit tailwatchd.service entered failed state.
Mar 03 00:47:46 server.myhostname.com systemd[1]: tailwatchd.service failed.

Not sure what this is all about but any relation to this latest 1.82 update?

**Comment by fevangelou** [comment]
Reboot your server.

**Comment by WebSavvyGuy** [comment]
haven't got this error message since.  closing for now.
