### ISSUE TITLE
Vary: Accept-Encoding

### ISSUE THREAD

**Issue by odysseas12** [engintron/engintron#459]
I am getting 2 Vary: Accept-Encoding headers send by nginx.

Had to comment out "gzip_vary on" in nginx.conf to fixed it so that only 1 is send;

Not sure if this is unique in my configuration or if others are getting this too, just letting you know.

Im on the latest version of engitron.

**Comment by fevangelou** [comment]
Your CMS/website is sending the first header. It's best to have Nginx hide that and display its own. So I would re-enable the related parameter in /etc/nginx/nginx.conf and then simply uncomment 1 line in /etc/nginx/proxy_params_dynamic like below, from:

```#proxy_hide_header      Vary;```
to
```proxy_hide_header      Vary;```

This way you'll be able to normalize the Vary header across all your sites as Nginx will make sure to always send it to browsers.

**Comment by odysseas12** [comment]
That also hides Vary:User-Agent and I still get 2 Vary: Accept-Encoding on static files css, js.
On dynamic content the second header comes from having "compress all content" setting on, in cpanel website optimization.
Disabling that and enabling gzip_vary on gives me 1 header on php pages.
On css, js files I still get 2 headers. 
Commenting out gzip_vary is the only option that gives me 1 header for all content.

**Comment by fevangelou** [comment]
Then do the same in /etc/nginx/proxy_params_static - that way you can normalize headers for Vary in one place. And of course you can easily re-set them from within Nginx. It's highly recommended you have "gzip_vary on" in nginx.conf. ;)

**Comment by odysseas12** [comment]
proxy_hide_header Vary is already enabled in proxy_params_static. 
Ill find it eventually and enable gzip_vary in nginx.conf.

**Comment by odysseas12** [comment]
Ok first header comes from gzip_vary on.
Second header comes from add_header Vary "Accept-Encoding"; in proxy_params_static
Problem is if I remove add_header Vary "Accept-Encoding"; images dont have the vary header.
If I leave it on css, js files have 2.

**Comment by fevangelou** [comment]
Nope... Check this site on a server I manage:

```curl -I https://www.web-consulting-team.com/images/portfolio/Benoit_Carre.png```

The response is:
```
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 03 Mar 2017 09:37:18 GMT
Content-Type: image/png
Content-Length: 332979
Connection: keep-alive
Last-Modified: Sat, 27 Feb 2016 17:08:29 GMT
Expires: Tue, 02 May 2017 09:37:18 GMT
Cache-Control: max-age=5184000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: Engintron
Pragma: public
Vary: Accept-Encoding
Accept-Ranges: bytes
```

And this is "stock" Engintron.

Now check the home page.
```curl -I https://www.web-consulting-team.com/```

Vary is indeed shown twice, but that's because stock Engintron will not hide the Vary header for dynamic content (everything that doesn't fall into "static" content like images, CSS, JS, web fonts etc.)

**Comment by odysseas12** [comment]
I disabled compression in Cpanel.
Commented out add_header Vary "Accept-Encoding"; in proxy_params_static.
Added image/png, image/jpg, image/gif, image/jpeg in gzip_types and "gzip_vary on" nginx.conf.
Now I get a single header on all content type.

**Comment by fevangelou** [comment]
There's a reason nginx.conf does not include JPG, PNG and GIF files for gzipping. The performance gain is nearly zero but it will cause higher CPU usage. Perhaps exceedingly high depending on your existing traffic.

Use with caution.

Closing this issue as resolved.

**Comment by odysseas12** [comment]
The reason you only get 1 very header in https://www.web-consulting-team.com/images/portfolio/Benoit_Carre.png is because image/png is not included in gzip_types.

If i do curl -I https://www.web-consulting-team.com/media/mod_falang/css/template.css 

I get 

HTTP/1.1 200 OK
Server: nginx
Date: Fri, 03 Mar 2017 09:50:36 GMT
Content-Type: text/css
Content-Length: 1200
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Sat, 27 Feb 2016 11:26:52 GMT
Expires: Sun, 02 Apr 2017 09:50:36 GMT
Cache-Control: max-age=2592000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: Engintron
Pragma: public
Vary: Accept-Encoding
Accept-Ranges: bytes

**Comment by fevangelou** [comment]
You're right. ```add_header Vary "Accept-Encoding";``` is redundant in proxy_params_static.

"gzip_vary on" is sufficient for the file types that are meant to be compressed. And like I said, it's not recommended to do compression for formats that already use compression (such as JPG, PNG etc.).

**Comment by odysseas12** [comment]
Yes you are right there is no sense in compressing already compressed images. 
Ive put "gzip_vary on" and the only thing I removed is the add_header Vary "Accept-Encoding"; in proxy_params_static.

**Comment by fevangelou** [comment]
Added in v1.8.3 just released. ;)
