### ISSUE TITLE
SSL: error:1417D18C in Error logs

### ISSUE THREAD

**Issue by Citizen-K** [engintron/engintron#460]
I am starting to see the error log filling up with entries like the one below.

`SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) while SSL handshaking, client: 165.xx, server: 0.0.0.0:443`

Is this something to be concerned about?

**Comment by lafrance** [comment]
In my tweak setting this is what I have for ssl

0.0.0.0:8443

**Comment by tux-tn** [comment]
Looks like the client was using sslv3 and not supporting TLS (very old web browser)
By the way,, SSLv3 is dead since 2014 because of the POODLE attack

**Comment by Citizen-K** [comment]
Thank you gentlemen.

**Comment by fevangelou** [comment]
@tux-tn Good catch man! Kudos
