### ISSUE TITLE
Not creating majority of websites in default_https.conf

### ISSUE THREAD

**Issue by Cronus89** [engintron/engintron#464]
Just installed for first time on OS: CentOS release 6.8 (Final)  

Everything went great, and some websites are in default_https.conf but most are not in there?

If there are any logs of this script running and its output that would be helpful. Not sure where to go from here.

**Comment by fevangelou** [comment]
Can you compare 2 domains from httpd.conf, one that's ported over to Nginx and one that fails to do so? What are the differences?

**Comment by Cronus89** [comment]
Great Idea, i figured it out! If the VirtualHost in apaches httpd.conf has an ipv6 address in there, It does not get setup in default_https.conf. Below are examples of this.

<VirtualHost ***.***.83.138:443 [****:****:0002:01a5:0000:0000:0000:0008]:443>   # Does NOT get added to default_https.conf

<VirtualHost ***.***.83.138:443> # DOES get added

**Comment by 8BallBomBom** [comment]
That seems to have resolved my issues also reported [here](https://github.com/engintron/engintron/issues/465) and [here](https://github.com/engintron/engintron/issues/431) so i guess no ipv6 for a while.

**Comment by fevangelou** [comment]
Continue to the other threads. Your issues seem to relate to IPv6 usage.
