### ISSUE TITLE
Missing data in default_https.conf & REMOTE_ADDR Issue - Temporary Possible Solutions

### ISSUE THREAD

**Issue by tonmoy-ajize** [engintron/engintron#465]
Hello,

I wanted to create a new issue thread just to make clear about the issues I have and many people have.
I am using CentOS latest production & cPanel & WHM 62.0 (build 16).

**Data missing in default_https.conf**:

Even PHP open_basedir Tweak is disabled for all domains still, Engintron doesn't generate data for few of the domains. But that's not all, even if you have written the data manually, data will be removed during different actions within Engintron WHM app.  :( 

**Temporary Solution:** Enter data manually for the missing domains and hope that it will not get removed :D  ... As I am really not sure when does it exactly get removed automatically but I am sure it's not because of the commands within crontab. 

------------------------------------------------------------------------------------------------------------------

**REMOTE_ADDR Issue**:

For me, it's creating conflict only on the accounts has 1/more IPv6 address assigned. Sometimes it's showing assigned IPv6 as result for **REMOTE_ADDR** and at the same time it's showing real IP within result for **HTTP_X_FORWARDED_FOR**.Rest of the times it shows real IP within result for **REMOTE_ADDR** and at the same time, there's no **HTTP_X_FORWARDED_FOR** in header :O

This issue is not happening on other domains have only IPv4 or even if you have a shared IPv6 address. Also, I don't see anything within Show compiled modules / Show loaded modules. 

**Temporary Solution:** Use **HTTP_X_REAL_IP** until Engintron fix the issue.

------------------------------------------------------------------------------------------------------------------

To Engintron, my intention is only to make the issue more clear by sharing my own experience. Temporary solutions I mentioned is to help people to keep using the latest version of Engintron and keep everything fine temporarily. Still, I would not mind if you need to close this issue.

However, I love Engintron so much and I am expecting fixes for these 2 issues very shortly. Hope, I will not be disappointed. 

Thanks to Everyone.

**Comment by fevangelou** [comment]
Regarding "Data missing in default_https.conf". You need to tell me which data it doesn't generate. Try and find any differences (in httpd.conf) between domains that work and those that don't.

Regarding "REMOTE_ADDR Issue". The way things are implemented now is correct. It's also the recommended way from Nginx, as well as CloudFlare, for reverse proxying. If it works for other domains and not the IPv6 one, then perhaps you server is somehow not properly configured to fully support IPv6.

**Comment by tonmoy-ajize** [comment]
httpd.conf has data for all domains and for same domains, default_https.conf don't have data.

by data, I meant vhosts which required to work SSL for those domains.

hope you may already know about it as other people have the same issues too.

However, I never blamed Engintron for any type of issues. I just wanted Engintron to fix these issues.  :(

**Comment by 8BallBomBom** [comment]
Also having the same issue.
The default_https.conf file only generates a default vhost.
Nothing else.

Ending result, every domain uses the main servers certificate for https.

**Comment by Cronus89** [comment]
This seems to be the same issue I have on https://github.com/engintron/engintron/issues/464

**Comment by fevangelou** [comment]
@tonmoy-ajize "httpd.conf has data for all domains and for same domains" this doesn't say much. Mail me your httpd.conf to engintron at gmail dot com to have a look.

@8BallBomBom & @Cronus89 Please email me your httpd.conf as well to have a look.

**Comment by fevangelou** [comment]
Post here for updates: https://github.com/engintron/engintron/issues/431
Your issues seem to relate to IPv6 usage.
