### ISSUE TITLE
Config files overwritten

### ISSUE THREAD

**Issue by kuteninja** [engintron/engintron#467]
On every update all the configuration files get overwritten, I especially care for the custom_rules and proxy_params_dynamic which I have edited, and cause our PHP dynamic files to be cached (which I don't want) and Cloudflare to be blocked.

You should use a system similar to RPM where the new file is left in place with a different extension and it's not overwritten nor used, in cases where the current file doesn't match the previous file md5sum (ie. only replace the file if you haven't modified it previously).

The custom_rules UI shows a "(view default)" button, perhaps do something like that but saying "(view differences)" when the current file and the one from the distribution don't match.

**Comment by fevangelou** [comment]
You can do lots of things in "custom rules", including switching off the micro-cache for all or specific domains, or even for subdomains or directories.

If you keep this as a rule, Engintron will never overwrite that file, but it will overwrite all others as they are important to make sure Nginx works as expected.

The overwritten files are indeed left as copies which you can explore via SSH only, within the /etc/nginx block.

This was in the Wiki as well: https://github.com/engintron/engintron/wiki/Engintron-&-the-%22Custom-Rules%22-file-(for-Nginx)

**Comment by kuteninja** [comment]
I'm not following, I do edit those files but when I update to a newer version (recently 1.8.1 and 1.8.2) they are rolled back to the default and thus I have a few minutes of customers complaining while I apply all the needed changes again.

I want to avoid the new files stepping over my changes, and only manually fix them if needed, I don't want to edit them again, manually, every time I update, or having to restore backups every time.

O could use chattr to avoid them getting changed but that would prevent me from getting the new version of those files as well

**Comment by fevangelou** [comment]
You can only safely edit "custom rules". This file will not be overwritten. The others will.
