### ISSUE TITLE
/tmp alerts and cron job

### ISSUE THREAD

**Issue by ytlevine** [engintron/engintron#468]
Getting a bunch of DISKCRITICAL alerts that the /tmp partition/mount point is filling up, after installing version 1.8.2.

After checking a few things, it appears that the cron file has this:

'find /tmp/engintron_dynamic/ -type f | xargs rm -rvf; find /tmp/engintron_static/ -type f | xargs rm -rvf; find /tmp/engintron_temp/ -type f | xargs rm -rvf' > /dev/null 2>&1

The quotes seem to be causing an issue though, since it doesn't seem to be running automatically.

Is there any way to get this fixed (assuming that's causing the issue)?

Thanks a lot!

**Comment by fevangelou** [comment]
Engintron does not set any cron job to delete Nginx's cache & temp files.

You or someone else added this.

**Comment by ytlevine** [comment]
Looking back, I had probably added that based on the original Engintron cleanup command (referenced here: https://github.com/engintron/engintron/issues/232), going to remove it.

But it seems like the /tmp partition is filling up way too fast, mainly since the most recent update, and I'm getting the DISKCRITICAL alerts, so I need to run something to clean it every so often - any recommendations?

Thanks.

**Comment by fevangelou** [comment]
You have 2 options. Either enlarge your /tmp partition or simply point Nginx's cache/temp folders (defined in nginx.conf) to a different location (which is in a partition with enough space available).
