### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by tallesairan** [engintron/engintron#469]
Today I had a problem with my engintron, the pages were inaccessible and in error_log had the following message

`2017/03/07 14:41:17 [crit] 19513#19513: *11601 open() "/tmp/engintron_temp/0045438890" failed (28: No space left on device) while reading upstream, client: 66.102.8.141, server: localhost, request: "GET /dl/AxDRb69WE27.html HTTP/1.1", upstream: "http://xxxxxxxxxx:8080/dl/AxDRb69WE27.html", host: "www.xxxxxxxxxxx.com", referrer: "http://xxxxxxxxx"`
I checked my tmp partition and was being used only 40% I did not understand the error, I gave a purge In the files and came back but I would like a resolution for this since I have enough traffic on my sites

**Comment by tallesairan** [comment]
`
/dev/sda2       1.2T  754G  368G  68% /
tmpfs            25G   16K   25G   1% /dev/shm
/dev/sda1       243M  131M  100M  57% /boot
/usr/tmpDSK     4.0G  277M  3.5G   8% /tmp
`

**Comment by fevangelou** [comment]
This mapping of /tmp to /usr/tmpDSK may be an issue. Can you contact your hosting company first and see if they've seen something similar before?

**Comment by tallesairan** [comment]
I have already given this problem to another server on the ovh, but now I have given this one, the solution was to change the /tmp folder, I changed it to /home/engitron / there all files stay there

**Comment by fevangelou** [comment]
I'll add an option in the future to allow you to specify that location and have it stick even after Engintron is upgraded.
