### ISSUE TITLE
DNS points to prohibited IP

### ISSUE THREAD

**Issue by curda** [engintron/engintron#470]
Having cloudflare and csf active, when I active the engintron all goes bad when desactivate engintron all is working fine!

**Comment by tallesairan** [comment]
On engintron dashboard click on 
Edit your custom_rules for Nginx 
on this var set to you real ip, and cloudflare works
`set $PROXY_DOMAIN_OR_IP "xxx.xxx.xxx.xxx";`
> https://github.com/engintron/engintron/wiki/Engintron-&-CloudFlare
