### ISSUE TITLE
Error with visitors

### ISSUE THREAD

**Issue by leisegang** [engintron/engintron#474]
In awstats i have 1 visitor with 400.000 pageviews. that visitor is the IP address that is on that account. could you please help med fix this problem, i want visitors to be shown in statistics not just the webserver. i belive this might be with the proxy of some sort?

**Comment by Friends4U** [comment]
Same problem here

**Comment by Friends4U** [comment]
@fevangelou when I test for IP the verdict is yes, but that's not correct because sometime I get my own ip but other times I get the IPv6 adres of my server.

**Comment by fevangelou** [comment]
Nginx feeds Apache logs with 2 IPs. The first one is the hostname (aka server) IP and the second one is the actual user IP. I guess for some reason, AWStats can't understand that.

What you can do is modify how Apache logs the traffic it gets from Nginx. More specifically, execute this command as root using SSH:

If you Apache config file is: /usr/local/apache/conf/httpd.conf
```
sed -i "s:LogFormat \"%h %a:LogFormat \"%a:" /usr/local/apache/conf/httpd.conf
```

If you Apache config file is: /etc/apache2/conf/httpd.conf
```
sed -i "s:LogFormat \"%h %a:LogFormat \"%a:" /etc/apache2/conf/httpd.conf
```

The above command will have Apache display the user IP as first element in the logs, thus making AWStats work properly.

Make sure you cleanup Nginx's cache/temp files and restart Apache/Nginx for the changes to take effect.

Let me know.

**Comment by Friends4U** [comment]
Will this be overwritten when using EA4?

**Comment by fevangelou** [comment]
It'll work, don't worry. I'm thinking of making this the default change in the next update of Engintron, as there is no point in keeping the hostname IP in the logs.

**Comment by rflack1717** [comment]
This won't work actually. When rebuildhttpdconf is performed, the httpd.conf file is regenerated and these changes are lost. To make them permanent you need to update the EA4 template files.

**Comment by fevangelou** [comment]
It'll temporary work. Besides, Engintron has a restore option now for the LogFormat changes. Apply it and then run the "sed" command. And like I said, I'll change it in the next update of Engintron.

**Comment by rflack1717** [comment]
You need to stop being so defensive, both here and in other issues that have been reported. You haven't actually said anywhere you'll update it in the next update of Engintron, so how can we be expected to know you'll do so? Relax, guy.

**Comment by fevangelou** [comment]
> I'm thinking of making this the default change in the next update of Engintron
https://github.com/engintron/engintron/issues/474#issuecomment-289746500

So you probably can't read English, right @rflack1717 ?

Either use the software or don't use it. But don't be an asshole.

**Comment by rflack1717** [comment]
You're the one being an asshole and being defensive, guy. Don't post a public project on Github if you can't handle bug reports and criticism. Loser.

**Comment by fevangelou** [comment]
Boo-fucking-hoo @rflack1717.

**Comment by fevangelou-asshole** [comment]
Yes, boo-fucking-hoo to you, who cries when people report bugs and issues in the software. Can't handle it? Don't make open public repos, douchebag.

**Comment by katmai** [comment]
it's always easy to talk smack and demand for things and then complain 
that someone that's putting in free hours of work to give you a great 
free product gets edgy.

as @fevangelou said - use it or don't use it and if you wanna be a 
critic, take that and shove it where the sun doesn't shine.
