### ISSUE TITLE
Settings for https concurrent connects

### ISSUE THREAD

**Issue by windsofchange** [engintron/engintron#477]
A customer asked us to show the server performance under load. We saw if the called connection was https, nginx CPU usage skyrocketed (+50% per nginx thread) overloading server. But if the called connection was http CPU usage barely changed.

This got me thinking maybe there is a settings tweak we are missing. Any ideas?

**Comment by windsofchange** [comment]
Update: Disabling gzip and enabling brotoli cut cpu usage by 40%... testing further

**Comment by Citizen-K** [comment]
If you don't mind me asking; 

`brotli on;
    brotli_static on;
    brotli_types *;` ?

or do you have something more sophisticated going in conf?

**Comment by windsofchange** [comment]
Yes that what I have there.

**Comment by laurfx** [comment]
How do you installed the module? is there a rpm and it's working like dynamic module or you recompile the NGINX?

**Comment by Citizen-K** [comment]
This one: https://codeit.guru/en_US/

Caveats: You are on your own with it.....

**Comment by laurfx** [comment]
@Citizen-K, thanks.

@fevangelou how about to use this rpm with OpenSSL 1.1.0e and ngx_brotli with Engintron? This will activate HTTP/2

**Comment by fevangelou** [comment]
@windsofchange You're using a 3rd party repo and assuming things may work as expected... That's beyond the scope of my support.

@laurfx I prefer security and stability over a couple of features.
