### ISSUE TITLE
SSL issue after migration

### ISSUE THREAD

**Issue by Psarmidani** [engintron/engintron#479]
Hello

SSL doesn't work after account migration (WHM migration tool). The domain has a (free) autossl from cPanel.

When we migrate a account from a server (without engintron) to a server with engintron. Engintron doesn't seem to recognize the changed httpd.conf.

I tested this a few times, we waited several hours. But the SSL won't load on nginx/engintron.

It works fine when we disable engintron/nginx

Let me know if you need more information

**Comment by ubidzz** [comment]
Make sure that PHP open_basedir Protection is turned off.

**Comment by Psarmidani** [comment]
Hi,

Thank you for the reply. 
The PHP open_basedir Protection is already turned off.
Do you have other suggestions?

**Comment by ubidzz** [comment]
Try this and run these 2 commands.

```
rm -rf /etc/nginx/conf.d/default_https.conf

/etc/nginx/utilities/https_vhosts.sh
```

**Comment by Friends4U** [comment]
And clean your cache!

**Comment by fevangelou** [comment]
Considering resolved due to inactivity.

**Comment by Psarmidani** [comment]
Hi,

Sorry for my late response.

I have tried that but still no luck.
And yes i have cleaned the cache.

**Comment by fevangelou** [comment]
As @ubidzz said, did you try executing these 2 commands via SSH?
```
rm -rf /etc/nginx/conf.d/default_https.conf
/etc/nginx/utilities/https_vhosts.sh
```

The above will force-create the vhosts for HTTPS.

**Comment by Psarmidani** [comment]
Yes i did.
I try it again to be sure.
I will get back to you soon.
Thanks for the support so far!

**Comment by fevangelou** [comment]
You're welcome :) Let me know.

**Comment by MarkCanada** [comment]
I have the same problem with transfers from another server with the Transfer Tool (AutoSSL cPanel certificates - but that part may be irrelevant). 
I found the "easiest" fix to be to disable Engintron and the re-enable it.
It seems that without that Engintron uses the server's main certificate...at least on the last one which I checked.

**Comment by qlpqlp** [comment]
Hello,

We have almos the same problem. After we update a few days to lates engintron, everithing was OK, after we issue new auto ssl certificates, the new ones dosent seam to load properly, sometimes load ok, some times load the default server ssl.

We have tried the first solution above without results (we also have clean tmp files):
`rm -rf /etc/nginx/conf.d/default_https.conf
/etc/nginx/utilities/https_vhosts.sh`

After that we execute the "Update (or re-install) Engintron [Nginx stable]" command and have fix it all, but doing this averytime we issue an new SSL in cPanel AutoSSL is a pain :)

We didnt try the outher solution: "Disable Engintron/Enable Engintron"

What could be missing in Engintron 1.8.2?

**Comment by qlpqlp** [comment]
Problem solved :)

After the transfer, termination or creation osf an AutoSSL certificate just go to WHM->Engintron->CleanCahe

lol, I must have missed that some what, because all new certificates on 1.8.2 are caching the HTTPS url from the account witout the certificate and its causing the issues :)

Maybe, when executing the https_vhosts.sh clean the cache for that domain(s) on NGINX to fix it :)

**Comment by Psarmidani** [comment]
Unfortunately that's not a good solution for us. We migrate accounts because of upgrades etc (so it's not a entire server migration). Is there no other way to trigger the vhost synchronisation after migrations in the engintron script?

**Comment by fevangelou** [comment]
When you move an account, Apache's config is updated. Engintron will pick up this change in 10 secs tops and reflect to its own config for Nginx.

**Comment by Psarmidani** [comment]
Unfortunately that is not the case.

**Comment by fevangelou** [comment]
@Psarmidani is open_basedir restriction enabled in your system?

**Comment by Psarmidani** [comment]
No the open_basedir restriction is not enabled.

**Comment by fevangelou** [comment]
Then after you do any migration, simply execute this line:

```rm -rf /etc/nginx/conf.d/default_https.conf; /etc/nginx/utilities/https_vhosts.sh;```

**Comment by Psarmidani** [comment]
Thank you, i will consider this as a temporary solution. 
Will there be a fix for this issue in the future?

**Comment by fevangelou** [comment]
@Psarmidani It looks specific to your setup so it's difficult to reproduce. What I could do is offer a button to click in the Engintron WHM app instead of opening a terminal to do so.

**Comment by Psarmidani** [comment]
Thank you for the offer. We will run some extra tests our self. 
I will get back to you on that.

You can close this topic for now :)

**Comment by ubidzz** [comment]
I bet it the php setup in the server because Engintron don't use a bash script to build the conf files and use php that not really a good Idea because if a function is turned off in php it will mess up Engintron on trying to build the conf. @fevangelou should change it to a bash script with awk to loop each apache vhost and not use php and would have less problems.

**Comment by fevangelou** [comment]
@ubidzz I'm using PHP to maintain my sanity here. If Bash was a better fit, I'd use it as I already do in the installer and a dozen other parts of Engintron.

**Comment by ubidzz** [comment]
I total understand why you want to use php because it easier to use it but keep in mined that people may have things turned off in there php that maybe needed in your plugin and is why it's better to use bash script to build the conf files.

**Comment by MarkCanada** [comment]
On a related issue - we had a change in the SSL certificate on a site and it only showed up after doing "Purge cache & temp files". 
This function does work well on migrations as @qlpqlp had mentioned and has been a savior in many instances to quickly take care of SSL issues.
It seems that somehow Engintron isn't always notified of SSL changes in the system.

**Comment by fevangelou** [comment]
@ubidzz If you have open_basedir restriction enabled, then a lot of things won't work in sites and CMSs. That's why it's off by default when you install cPanel. In any case, maybe Engintron is not for everyone.

@MarkCanada If the cron job set by Engintron does not work for you, open /etc/crontab FROM the Engintron WHM app and simply hit save. A bug in the editor window in v1.8.0 or 1.8.1 added wrong line endings invalidating any cron job in there. Simply opening and saving the file via Engintron's WHM app fixes that.

**Comment by faca5** [comment]
Hello.

/etc/nginx/conf.d/default_https.conf still don't have vhosts for https.

We have tried:
rm -rf /etc/nginx/conf.d/default_https.conf; /etc/nginx/utilities/https_vhosts.sh;

Any idea?
