### ISSUE TITLE
[HTTPS] Problem with PrestaShop

### ISSUE THREAD

**Issue by moreirawebmaster** [engintron/engintron#480]
I'm having a problem after the installation, the new product images that take root from the system are not loading.

Another point I noticed is that some images from WHM are not loaded too, is there a problem?

**Comment by Friends4U** [comment]
WHM is excluded from Engintron so I believe you have another problem...

**Comment by fevangelou** [comment]
A URL would also help...

**Comment by theoxgr** [comment]
this is a problem that has to do with the "performance > mediaserver" i guess you have setup a pseudo-cdn in prestashop using subdomains. if you do, then you will have to add SSL to each one of those subdomains. otherwise remove them from prestashop config and go to seo & urls and save.

**Comment by fevangelou** [comment]
Good catch @theoxgr :)
