### ISSUE TITLE
Wordfence Wrong IP

### ISSUE THREAD

**Issue by zagnu** [engintron/engintron#481]
I recently installed this on a fresh EA4 based cPanel install (fresh install) and it seems that Wordfence now thinks my IP = the Server's IP. I ran your ip.php and the oddness is it says all is good however:

http://cloud.thrustnet.com/2C2a0t41300F

I get the server IP listed as my own, and the server IP is blank. How do I fix this because as it stands all traffic good and bad is being marked as the server IP in Wordfence. Likely going to have to disable if I can't find a solution as this creates some serious issues with folks logging into their Wordpress installs.

**Comment by Friends4U** [comment]
https://docs.wordfence.com/en/Wordfence_options#Use_the_X-Forwarded-For_HTTP_header._Only_use_if_you_have_a_front-end_proxy_or_spoofing_may_result.

**Comment by zagnu** [comment]
I did find that - however wasn't the key solution as honestly other apps do require an external IP, so I'm starting to think the setup simply isn't for me.

**Comment by Friends4U** [comment]
Did you check this?

https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron

**Comment by zagnu** [comment]
Sadly it says "Yes" but the displayed IP is still that of the server. I've disabled things for the time being, just too many issues with customers at the moment :-(

**Comment by fevangelou** [comment]
@zagnu I think @Friends4U is right. Enable the option mentioned here: https://docs.wordfence.com/en/Wordfence_options#Use_the_X-Forwarded-For_HTTP_header._Only_use_if_you_have_a_front-end_proxy_or_spoofing_may_result.

Then cleanup Nginx's temp/cache files, restart Apache/Nginx and cleanup any WordPress caches for the changes to take effect.

**Comment by zagnu** [comment]
@fevangelou I appreciate the reply, I actually ran through all of that, just not a seamless as I'd like at the moment, and as this was done with the idea it'd be a + for customers to a new server, I can't give them more hassle at the moment so once things calm down I'll re-try it all again and see if I can work it out.
