### ISSUE TITLE
X-Nginx-Cache-Status is always EXPIRED

### ISSUE THREAD

**Issue by brinsleyparagao** [engintron/engintron#482]
Hello,,, in some tests in various SSL tests this is always set EXPIRED

X-Nginx-Cache-Status is always show EXPIRED, how to fix this?

PS: in http and https is a same: EXPIRED

**Comment by fevangelou** [comment]
The micro-cache is kept for 1 sec. It's normal for you to see this. You have to execute multiple curl commands in a terminal to see that the cache is HIT.
