### ISSUE TITLE
Microcaching

### ISSUE THREAD

**Issue by Mike981874** [engintron/engintron#484]
Hello,

How would one disable microcaching for Nginx as a whole? I host many sites and can't keep up with adding each domain to the custom rules, and it would be much better for me to disable the microcaching altogether.

**Comment by Friends4U** [comment]
Not install it?

**Comment by fevangelou** [comment]
@Mike981874 it's all in the wiki: https://github.com/engintron/engintron/wiki/About-Engintron's-micro-caching-features & https://github.com/engintron/engintron/wiki/Excluding-specific-domains-or-domain-paths-from-micro-caching

@Friends4U He can still benefit from faster static asset serving if you must know...
