### ISSUE TITLE
Webp to Firefox

### ISSUE THREAD

**Issue by CarlosLopezES** [engintron/engintron#488]
Hi,

I have this .htacces:

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP_ACCEPT} image/webp
RewriteCond %{REQUEST_FILENAME} (.*)\.(jpe?g|png)$
RewriteCond %{REQUEST_FILENAME}\.webp -f
RewriteRule (.+)\.(jpe?g|png)$ %{REQUEST_FILENAME}.webp [T=image/webp,E=accept:1]
</IfModule>
<IfModule mod_headers.c>
Header append Vary Accept env=REDIRECT_accept
</IfModule>
AddType image/webp .webp
```

And this is not working with Nginx as proxy reverse, so i put this into nginx.conf:

```
map $http_accept $webp_suffix {
    default   "";
    "~*webp"  ".webp";
  }
```

But still not working, the web is delivering webp to Firefox. Any ideas?

Thank you!

**Comment by fevangelou** [comment]
That's not gonna work. But if your .htaccess redirect works, Nginx will have no issue sending back .webp.

**Comment by CarlosLopezES** [comment]
But i have disabled Engintron and suddenly works fine, and if i re-enable, stop working after cache refreshing :(

**Comment by fevangelou** [comment]
Try this https://wp.sarmento.org/hackeando-o-nginx-condicionais-multiplas/ it may work. The snippet you mentioned above is incomplete. Let me know.

**Comment by CarlosLopezES** [comment]
Thank you! Looks very nice!

One question, can i make a config file for only one domain? Because if i put it to all domains, maybe it's a little slow to check every single picture.

Thanks!

**Comment by fevangelou** [comment]
Replace this in /etc/nginx/conf.d/default.conf & in /etc/nginx/common_https.conf:
```
    # Enable browser cache for images (TTL is 60 days)
    location ~* \.(?:ico|jpg|jpeg|gif|png|webp)$ {
        include proxy_params_common;
        include proxy_params_static;
        expires 60d;
    }
```

with this:
```
    # Enable browser cache for images (TTL is 60 days)
    location ~* \.(?:jpg|jpeg|png)$ {
        include proxy_params_common;
        include proxy_params_static;
        expires 60d;

	set $rw "";
	if ($host ~ 'yourdomain.tld') {
		set $rw "A";
	}
	if ($http_accept ~* "webp") {
		set $rw "${rw}B";
	}
	if (-f $request_filename.webp) {
		set $rw "${rw}C";
	}
	if ($rw = "ABC") {
		add_header Vary Accept;
		rewrite (.*) $1.webp redirect;
	}
    }

    location ~* \.(?:ico|gif|webp)$ {
        include proxy_params_common;
        include proxy_params_static;
        expires 60d;
    }
```

You'll easily notice the custom domain flag to replace. This is untested, so try it and let me know.

**Comment by CarlosLopezES** [comment]
Amazing! Now it's working perfect, delivers webp to compatible browsers and jpg to Firefox and IE.

Thank you!

**Comment by fevangelou** [comment]
I'll add this as a generic option in an upcoming release. You'll be able to switch it on/off for the entire server or just selected domains.

**Comment by Jon007** [comment]
@fevangelou did you add this as a option in any upcoming release?
I've looked at this a few times and never found it to work.

**Comment by fevangelou** [comment]
I didn't add it because it's too specific. Even if I made it generic, it would still involve unnecessary file system calls.

I would recommend either using e.g. CloudFlare for delivering webp where possible or just integrating that option in your app/site (if you have control over that of course).
