### ISSUE TITLE
Dynamic Proxy Pass Host?

### ISSUE THREAD

**Issue by bdtech** [engintron/engintron#490]
Was curious, why is proxy pass dynamic based on the host header? Nginx should only be routing traffic locally. You'd want to prevent proxying to non local "system IP's".

set $PROXY_DOMAIN_OR_IP $host;
proxy_pass          http://$PROXY_DOMAIN_OR_IP:$PROXY_TO_PORT;

My solution currently is:
resolver 127.0.0.1;

**Comment by rflack1717** [comment]
Indeed, I'd like to know if there was a design decision behind this or this is just an anomaly. Routing traffic locally via the proxy makes more sense than going externally for sure.

**Comment by tux-tn** [comment]
I guess it's due to the fact that Apache is setup to listen on domain ip for each virtualhost

**Comment by bdtech** [comment]
Its troublesome as you can easily override the host header and start proxying any external site. This opens a big can of security concerns.

My solution currently is:
resolver 127.0.0.1;

**Comment by Shadowized** [comment]
I also use 127.0.0.1 for the resolver, but for performance reasons, I had noticed a long delay of 2500-5000ms depending on which external resolver was set, never really figured out the cause but using the local resolver solved it, though it does break ocsp lookups for me.

![external vs 127.0.0.1](http://i.imgur.com/rZrOWxB.jpg)

**Comment by lmfreitas** [comment]
you must be resolving proxy from ouside your server.

**Comment by Shadowized** [comment]
well, the default config in engintron uses external DNS to resolve domains so yeah...

**Comment by fevangelou** [comment]
It depends on your cPanel setup really. For those that 127.0.0.1 works as a resolver, I can only assume they have a DNS server already running in cPanel. But if you don't run a DNS server, 127.0.0.1 would yield nothing.

**Comment by bdtech** [comment]
You'd want to add a check to see if CP DNS is running locally on 127.0.0.1. Which is much safer than relying on the provided host header. Alternatively, if server has only one "system_ip", you can route the proxy there by default. Otherwise, you're potentially enabling an open/public proxy out of the box (as is).

**Comment by fevangelou** [comment]
@bdtech you can mitigate any traffic abuse by hardening your firewall rules a bit. Your suggestions on checking if a DNS server is present and checking for a single system IP do make sense of course. However the admin MUST know Nginx's config is set to use the shared IP by default in case they add a new IP in the system. Or you check this behaviour with a cron etc. etc. which may overcomplicate things. This needs some thinking to be honest.

**Comment by bdtech** [comment]
I would encourage escalating this issue as it's a severe vulnerability as an open proxy for anyone running this. You may want to consider making it "safe by default" or at least a CP plugin configuration option. The firewall hardening won't work as this allows any host header (which is not at the same layer).

**Comment by fevangelou** [comment]
First off, this is how Nginx does proxying. Apache doesn't listen to 127.0.0.1 in cPanel's setup. And using hardcoded IPs is obviously not an option when they can change at any time. Otherwise you might as well use any of the other Nginx-for-cPanel plugins (and good luck with that).

Since proxying happens from Nginx to port 8080 and yes, it can be used to redirect traffic elsewhere (albeit not everyone can do this), you can block outgoing TCP connections to port 8080 and you should be fine. Another user had brought this up in the past (see here https://github.com/engintron/engintron/issues/301).

Since IPtables is really a brainfuck to me, I used a generator for a rule like that. You can try it out:
`iptables --append OUTPUT --match tcp --protocol tcp --dport 8080 --jump REJECT`

Or use CSF and make sure port 8080 is not in the TCP outgoing ports list. Should be simpler.

Let me know.

**Comment by bdtech** [comment]
Your best bet moving forward is to default Nginx.conf to use the local 127.0.0.1 resolver if CP DNS is available locally. If DNS is not available locally, and system has only one WAN IP,  proxy_pass directly there (which is essentially what's being done none minus the DNS lookup). You can even make mention in the config that using public resolvers is dangerous as the host header can be overridden with anything. There's no way of stopping it at the firewall level because Nginx will initiate an outbound connect :80 remotely if the host header is forged. I can show you an example if you want.

**Comment by fevangelou** [comment]
Yes, please show me an example as I can't verify on my end. Just tried faking the host name on a couple of servers I manage that don't even block outgoing port 8080 and I get no proxying done to outside domains.

**Comment by bdtech** [comment]
I'd rather not list sites publicly but it's very common to run various control panels on :8080. Additionally this can be leveraged to traverse local (LAN) IPs which gets very scary. 

One big ballpark example:
https://blog.cloudflare.com/cloudflare-now-supporting-more-ports/

**Comment by fevangelou** [comment]
First off, there is no known control panel working on port 8080. Secondly, you're not giving me an example. Try faking the host name for a site that would respond on port 8080 (not google.com obviously, a site on a server that uses Engintron for example and you know has Apache listening on port 8080) by querying an Engintron server which again you know will try to proxy traffic to port 8080. Doesn't work.

**Comment by fevangelou** [comment]
Additionally, the fact that CF supports more ports is irrelevant to the matter.

**Comment by bdtech** [comment]
It's not irrelevant. There's millions of CF sites, just using their name servers, you can find plenty listen on 8080. There are actually many apps that use 8080 especially in the corporate world (plus the LAN aspect).

**Comment by bdtech** [comment]
Override the host header with cpanel.com if you wish

**Comment by bdtech** [comment]
Feel free to try digitalocean.com too. Should I keep going?

**Comment by fevangelou** [comment]
Show me the output of such a command.

**Comment by bdtech** [comment]
It would be equivalent to a standard GET/HEAD/POST request in browser or command line cURL.
