### ISSUE TITLE
Connections going out to the public IP?

### ISSUE THREAD

**Issue by ytlevine** [engintron/engintron#491]
I have Engintron set up, with my domains going through CloudFlare, and the necessary settings in the custom_rules file.

Recently, I've been seeing what appears to be a SYN flood on my server, but when I run "netstat -nap | grep SYN". it shows that pretty much all of the connections are from the nginx process on the server itself, going out to port 8443 on the external IP address.

Any idea what might be causing this, and if there's any way to make sure that all connections are internal (127.0.0.1), instead of going out over the external IP address?
Unless that has something to do with the CloudFlare configuration settings?

It doesn't seem like anything changed in the past while on my server though, not sure why it would have only started recently...

Thanks!

**Comment by fevangelou** [comment]
That's normal if you consider Nginx proxies traffic to Apache. And it does so by using the server's public IPs as it "reads" them from Apache's config. Either way, Apache is not configured to listen on 127.0.0.1 for its domains.

**Comment by ytlevine** [comment]
Seems like the underlying issue was an attempted attack on my server, it otherwise seems to be working nicely, so probably not an issue that you have to worry about...

Thanks for all your work on an awesome product!

**Comment by fevangelou** [comment]
You're welcome.
