### ISSUE TITLE
ALPN Support

### ISSUE THREAD

**Issue by b00rek** [engintron/engintron#492]
First of all, thanks for developing Engintron, you're awesome! Also, thanks for making TLS supported now, Engintron upgraded nicely and works even more awesomely. 👍 

Now, what about ALPN? It's my understanding that it is supported in Nginx, but depends on a certain version of OpenSSL... So I guess the real question is, how hard would it be for Cpanel / Engintron to switch to that supported OpenSSL version?

**Comment by Shadowized** [comment]
disable the current nginx repo in /etc/yum.repos.d and add/enable the one mentioned in #368 by @tux-tn, then from what I remember just force an upgrade or reinstall on nginx and you're good to go.

**Comment by fevangelou** [comment]
@b00rek Either go with @Shadowized proposal (3rd party repo alert here) or wait until cPanel resolves this issue which either way affects the entire system (e.g. Apache). It boils down to OpenSSL's (old) installation in CentOS.
