### ISSUE TITLE
AutoSSL Expiry issue

### ISSUE THREAD

**Issue by mofolo** [engintron/engintron#493]
Hey team,

We have AutoSSL enabled on every domain on our server.

Today, March 23rd, one of our domains threw an expired certificate error, saying that the certificate was valid until the 22nd of March.

I checked cPanel to confirm that AutoSSL had re-generated a new SSL certificate, and it did, valid to the 23rd of June. 

I proceeded to WHM and pressed Restart Apache & Nginx.
This fixed the issue.

Now I am concerned that Nginx's SSL is being cached and the checks are not frequent enough in the event of an AutoSSL update.

Is this a known bug?

Thanks!

**Comment by Shadowized** [comment]
hmm yeah that is a bit of an interesting issue, I maybe wrong but I don't think engintron has any logic setup for that currently.

perhaps it could be set to monitor the vhost file and if changes are detected it should trigger a reload of nginx?

**Comment by fevangelou** [comment]
@Shadowized It already does that. But it will be a problem if cPanel does not update Apache's config if it keeps the same filenames for re-generated certificates.

Need to investigate further in any case.

**Comment by rflack1717** [comment]
Probably worth checking the creation/modification timestamp of the certificates to determine whether or not a reload and emptying of cache is necessary.

**Comment by jhawkins002** [comment]
Greetings. So this was closed with no comments - since we are experiencing this issue, any related info would be great!
