### ISSUE TITLE
Nginx do not restart after Cpanel auto updated!

### ISSUE THREAD

**Issue by xuanduoc84** [engintron/engintron#494]
After  cPanel Update (upcp)
Nginx doesn't restart automatic
I try loged to whm and click restart nginx => server working again

Please check and fix that

**Comment by ryus666** [comment]
ok, could be the cause of my issue (nginx crashing). Looks like it is the same thing (not starting up after upcp). Can it be fixed soon ?

**Comment by rflack1717** [comment]
I'm also seeing this but only on one server, yet others are fine. Perhaps we should start sharing more information? 

The only server this is a problem on for me is a CentOS 6.8 server. CentOS 7+ is fine. When I check the nginx status it says "dead but subsys locked", but a simple restart fixes it.

**Comment by ryus666** [comment]
yeah. Centos 6.8 here as well. And a simple restart fixes it. Any way to automate it ?

**Comment by rflack1717** [comment]
What works for me is changing the /etc/chkserv.d/nginx file from socket based monitoring to process based monitoring:

```service[nginx]=x,x,x,service nginx start,/usr/sbin/nginx,root```

**Comment by obosor** [comment]
Are you using latest 1.8.2 version? This version solved the issue.

**Comment by johnknossis** [comment]
It stated that 1.8.2 would fix this issue, but it seems that wasn't the case as the issue remains and it seems to be more frequent now than ever.

**Comment by ryus666** [comment]
Yes, I am using the latest 1.8.2 and as mentioned above by John, is it more frequent since the update.

**Comment by fevangelou** [comment]
Guys, this looks like a cPanel bug. See here: https://github.com/engintron/engintron/issues/496#issuecomment-289739103
