### ISSUE TITLE
Nginx crashing regularly

### ISSUE THREAD

**Issue by ryus666** [engintron/engintron#495]
Hi,

I am running Engintron on a cpanel server with just 1 website. For some reason, nginx keeps crashing every other day and the site becomes unreachable till I go and restart nginx. When restarting, I get : 
Sropping Nginx : (Failed)
Starting Nginx : OK

This is happening way too often now. I am using all default settings for Engintron + with FCGI handler (EA4). Latest version of WHM and Engintron. What could be the reason ? Here are some error log entries : 

`2017/03/23 09:20:35 [error] 28314#28314: *223036 upstream prematurely closed connection while reading upstream, client: CLIENT_IP, server: localhost, request: "GET /url-to-a-site-article/ HTTP/1.1", upstream: "http://SERVER_IP:8080/url-to-a-site-article/", host: "WEBSITE NAME" `

Any ideas what is going on ?

**Comment by KayCaesar** [comment]
Same here!

**Comment by jcatello** [comment]
Its from cPanel updates, after it installs all the new RPM's it restarts Apache but not Nginx, not sure why chkservd takes so long to restart Nginx, but you may want to go into Tweak Settings and set the interval that chksrvd checks from 300 to 60

But in the long run, I think there needs to be some kind of hook or something we can use to restart Nginx everytime cPanel restarts Apache after the updates?

**Comment by ryus666** [comment]
Exactly. It used to get started on its own before. But not happening now for some reason. Probably the last couple of updates to the plugin changed something ?

**Comment by jcatello** [comment]
Its weird that cPanel knows to kill off nginx:

[2017-03-23 02:57:19 -0500]      [8074] Aligning modsec config to Whostmgr
[2017-03-23 02:57:19 -0500]      [8074] Waiting for “httpd” to stop ……
[2017-03-23 02:57:19 -0500]      [8074] Gracefully Terminating processes: nginx           with pids 9852 and owner root....
[2017-03-23 02:57:19 -0500]      [8074] ...waited 1 second(s) for 1 process(es) to terminate....Done
[2017-03-23 02:57:19 -0500]      [8074] …finished.
[2017-03-23 02:57:19 -0500]      [8074] Waiting for “httpd” to start …
[2017-03-23 02:57:19 -0500]      [8074] …
[2017-03-23 02:57:19 -0500]      [8074] waiting for “httpd” to initialize ………finished.

**Comment by johnknossis** [comment]
I have the same issues. I'd greatly appreciate if someone could share a possible solution for this problem. The only thing we've done so far is changing the way chkservd checks for nginx and force an update every 5 minutes if it detects that it's down. But that's clearly not a fix for the actual problem.

**Comment by fevangelou** [comment]
@jcatello It's probably identifying which service is hooked on port 80 and then it kills Nginx as you mentioned.

@all I don't know why this happens to a few folks. To be honest, I manage several cPanel servers with external monitoring on specific domains and I've never had such an issue. Maybe this occurs on cPanel servers with a specific setup (I notice Mod Security on @jcatello 's log above which I don't use on the setups I do). Since I can't verify on my end, I'd appreciate it if you can provide additional evidence that could help troubleshoot this issue you're facing.

**Comment by ryus666** [comment]
I am using a normal setup. WHM + CSF + Engintron (no mod security or anything else).

**Comment by fevangelou** [comment]
@ryus666 Seems like a cPanel bug with EA4's auto-updater. See here: https://github.com/engintron/engintron/issues/496

**Comment by jcatello** [comment]
They ever say anything about the bug, just had it happen on 2 servers within the past couple hours.

**Comment by fevangelou** [comment]
Same here, however it only occurs at night when cPanel update runs and for a couple of mins only until tailwatchd restarts Nginx & Apache.

No word from cPanel though.
