### ISSUE TITLE
cPanel Local domain resolution

### ISSUE THREAD

**Issue by PetaByet** [engintron/engintron#498]
Why does Nginx have to resolve domains externally (and potentially causing issues with Cloudflare if not configured)? Highly inefficient and is prone to be affected by network slowdowns.

There is a simple way to dump all IPs and its domains through a cPanel script and perhaps, parse it into the hosts file or have a local DNS resolver?

The script is: `/scripts/ipusage`

Sample output:
```

# /scripts/ipusage
12.34.56.78 [http: site1.com,subdomain.site1.com,site2.com]
```

**Comment by fevangelou** [comment]
It's a simpler setup. And DNS resolving is cached. And it works. And you only need to add a couple of exclusions for CloudFlare which would either way freak out as it's "proxy to proxy".
