### ISSUE TITLE
Port 8443 to use port 443

### ISSUE THREAD

**Issue by lafrance** [engintron/engintron#499]
Hello!

Is there a way to be able to use port 443 instead of 8443 so that nginx server http2

At this time it seem it apache that server it?

 curl -I --http2 https://smalljournal.ca/
HTTP/2 200
date: Sat, 25 Mar 2017 19:29:44 GMT
server: Apache
link: <https://smalljournal.ca/wp-json/>; rel="https://api.w.org/", <https://smalljournal.ca/>; rel=shortlink
set-cookie: wfvt_252490629=58d6c5297ee76; expires=Sat, 25-Mar-2017 19:59:45 GMT; Max-Age=1800; path=/; HttpOnly
cache-control: max-age=600
expires: Sat, 25 Mar 2017 19:39:44 GMT
vary: Accept-Encoding
content-type: text/html; charset=UTF-8

**Comment by fevangelou** [comment]
Nginx already binds to port 443. It seems Engintron is disabled in your server, that's why you see Apache there.

**Comment by lafrance** [comment]
Sorry Fotis forgot to turn it back on the right port 8443

**Comment by fevangelou** [comment]
Everything seems OK now, no Apache in the headers referenced:

```
$ curl -I "https://smalljournal.ca/"
HTTP/1.1 200 OK
Date: Wed, 29 Mar 2017 01:45:55 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d7164dfd52669569cecdedd04921827021490751955; expires=Thu, 29-Mar-18 01:45:55 GMT; path=/; domain=.smalljournal.ca; HttpOnly
Vary: Accept-Encoding
X-Mod-Pagespeed: 1.11.33.4-0
Vary: Accept-Encoding
Cache-Control: max-age=0, no-cache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: EXPIRED
X-Server-Powered-By: Engintron
CF-Cache-Status: EXPIRED
Server: cloudflare-nginx
CF-RAY: 346f2707fe795cb1-ATH
```

What's the issue?

**Comment by lafrance** [comment]
Hello!

As you can see it is http/1.1 cannot use http/2. with the port 8443

**Comment by ubidzz** [comment]
To be able to use http/2 you have to install nginx that is compiled with OpenSSL 1.0.2 or higher and from your nginx info your nginx is complied with OpenSSL 1.0.1e-fips that cant use http/2. To use http/2 you will have to manual install the nginx server with a compiled openSSL 1.0.2 or higher.

**Comment by lafrance** [comment]
Hello!

Make sense hunting google to help me on that point
so far no luck for centos 7

**Comment by lafrance** [comment]
Ok this what it show now

 openssl version -a
OpenSSL 1.0.2k  26 Jan 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx)
compiler: gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/ssl"

However nginx still show

built with OpenSSL 1.0.1e-fips 11 Feb 2013


grrrrrr

**Comment by ubidzz** [comment]
are you using only engintron install to do the nginx install or do you have other nginx repo in your server. If you are only using the engintron install file and it will install the default nginx with openSSL 1.0.1e you would need to delete the default nginx and then go to their site to get the download link and then you would have to go to OpenSSL website to get their software and then you would have to compile a newer version of OpenSSL with nginx on the install.

**Comment by lafrance** [comment]
Hello!

No only engintro Fotis as clean all old stuff on server I try to re install and notice engintron loaded old openssl not the one on the server

**Comment by ubidzz** [comment]
engintron does not use a newer version of OpenSSL unless he change the way it it is installed. He pulls the default nginx server that is compiled with OpenSSL 1.0.1

**Comment by lafrance** [comment]
Ah that explain why it still show old version In another word I am flup until nginx update openssl?

**Comment by ubidzz** [comment]
Or you can use a 3nd party repo to install nginx like codeIT repo that will install nginx with a new version of OpenSSL.

CodeIT website to get the repo
https://codeit.guru/en_US/

**Comment by lafrance** [comment]
Hello!

I do have have that repo forgot how too use it though

**Comment by ubidzz** [comment]
I forgot if you use CodeIT repo you maybe able to run the repo to install a new version but if it don't you will have to unstaill the nginx in your server and delete the repo and then run CodeIT repo to install nginx.

**Comment by ubidzz** [comment]
When i installed that repo i use WHM system update to have it run the repo.

**Comment by lafrance** [comment]
Ah thanks will try that and thanks for all the help

**Comment by ubidzz** [comment]
Here is my nginx info from CodeIT

```
nginx version: nginx/1.11.11
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
built with OpenSSL 1.1.1-dev  xx XXX xxxx
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_perl_module=dynamic --add-dynamic-module=njs-1c50334fbea6/nginx --with-threads --with-stream --with-stream_ssl_module --with-http_slice_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --add-module=/tmp/nginx/ngx_brotli --with-openssl=/tmp/nginx/openssl --with-http_v2_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wno-deprecated-declarations'
```

**Comment by lafrance** [comment]
what command did you use again ?
Also do I really have to delete my version of nginx?

**Comment by ubidzz** [comment]
I used this command
`cd /etc/yum.repos.d && wget https://repo.codeit.guru/codeit.el`rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release)`.repo`

and i think to install it you can use `yum update` if it didn't work you can then try `yum clean all` then try `yum update` again.

**Comment by lafrance** [comment]
thanks yum update see nothing

**Comment by ubidzz** [comment]
Try this!
`cd /etc/yum.repos.d`
`dir`
if you see nginx.repo in the list run this command
`rm -rf nginx.repo`
then run this command to clean your repo list
`yum clean all`
then try this command to see if codeIT repo runs
`yum update`

**Comment by lafrance** [comment]
seem nothing work for me

**Comment by ubidzz** [comment]
Think i missed a command because i think repo have a database and there is a command to run to clean it but i cant remember it and it is posted on here some place and i am looking for it.

**Comment by ubidzz** [comment]
Here is a thread that codeIT was talked about a lot on how to install it.
https://github.com/engintron/engintron/issues/437

**Comment by ubidzz** [comment]
Good news i found the command that i missed here it is and try this.

```
rm /etc/yum.repos.d/nginx.repo
rpm -e --justdb --nodeps nginx
yum update
```

**Comment by lafrance** [comment]
hello thanks will try that

**Comment by ubidzz** [comment]
that should work because that is removing the repo file and in the rpm db and then it is running the update to see if any rpm needs to be updated

**Comment by ubidzz** [comment]
OH i forgot if you reinstall engintron it will readd the nginx repo and you will have to do this all over again. But it can be changed if you change it in the /engintron.sh file by replacing the code that is getting the nginx repo to CodeIT repo.

**Comment by lafrance** [comment]
thanks again seem that did the trick

nginx version: nginx/1.11.11
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
built with OpenSSL 1.1.1-dev  xx XXX xxxx
TLS SNI support enabled

**Comment by lafrance** [comment]
ah good to know I am sure soon nginx will update openssl we can only hope :)

**Comment by ubidzz** [comment]
Your all set now and your nginx is using http/2 and if you want more Security add this that adds more headers and you can read what they do by doing a search on the internet for these headers.

Referrer-Policy
Strict-Transport-Security
X-XSS-Protection
X-Content-Type-Options
X-Frame-Options

Replace all the add_header codes in the proxy_params_common file to this that is shown below. It has to be in a IF statement between http and https or the header wont work

```
if ($scheme = "https") {
    # Info
    add_header X-Nginx-Cache-Status $upstream_cache_status;
    add_header X-Server-Powered-By "Engintron";

    # Security Headers
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
}

# General http header Settings
if ($scheme = "http"){
    # Info
    add_header X-Nginx-Cache-Status $upstream_cache_status;
    add_header X-Server-Powered-By "Engintron";

    #Security Headers
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
}
```

**Comment by lafrance** [comment]
Done thanks again :)
+1
