### ISSUE TITLE
Deprecated: Non-static method

### ISSUE THREAD

**Issue by tammyrocks** [engintron/engintron#500]
hi
i dont know if this is issue enginetron or my site coding 
since the last update  it started to cache https content 
and everything seamed to work fine 
but when try use facbook login i get this error 
turn macro cache off and is still error 

Deprecated: Non-static method _CLASS_Core::getInstance() should not be called statically, assuming $this from incompatible context in /home/xxxxxxxx/xxxxxl/xxxx/xxxxxxxx/controllers/socialbridge.php on line 193

line 193 is 

$obj = YNSOCIALBRIDGE_CLASS_Core::getInstance("facebook");

**Comment by tammyrocks** [comment]
adding this to php ini fixed it 
well hides it not fixes it 
error_reporting = E_ALL & ~E_DEPRECATED

**Comment by fevangelou** [comment]
That is not an Engintron issue. That's a PHP deprecated notice.
