### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by tammyrocks** [engintron/engintron#503]
since the last update it started cache on my https site 
which is awesome 
but it seams to be only cache half of what it should 
i have 2 folders that have static content in them
/static
/userfiles

is there any way of telling engintron to cache anything form a given directory, folder

**Comment by fevangelou** [comment]
You don't need to specify which folders to cache. If the folders you mention hold static files only, then they are cached. Use "curl -I https://path/to/file" in a terminal to check caching headers.

**Comment by tammyrocks** [comment]
i tried few files 
i am guess that is say server apache  means its not cached 
also pingdom shows lots of stuff thats not servered from static domain 
at a guess its caching maybe half of what it should be 

a js file gives this 
HTTP/1.1 200 OK
Date: Sun, 09 Apr 2017 01:53:12 GMT
Server: Apache
Last-Modified: Sat, 10 Sep 2016 23:07:03 GMT
Accept-Ranges: bytes
Content-Length: 7199
Cache-Control: max-age=31536000
Expires: Mon, 09 Apr 2018 01:53:12 GMT
Vary: Accept-Encoding,User-Agent
X-XSS-Protection: 1; mode=block
Content-Type: application/javascript

a ccs file 

HTTP/1.1 200 OK
Date: Sun, 09 Apr 2017 01:55:42 GMT
Server: Apache
Last-Modified: Sun, 09 Apr 2017 01:26:21 GMT
Accept-Ranges: bytes
Content-Length: 830
Cache-Control: max-age=2592000
Expires: Tue, 09 May 2017 01:55:42 GMT
Vary: Accept-Encoding,User-Agent
X-XSS-Protection: 1; mode=block
Content-Type: text/css

**Comment by fevangelou** [comment]
It means Engintron is not installed basically. Maybe the installation failed if you had another plugin for Nginx on cPanel previously installed.

**Comment by tammyrocks** [comment]
yes  your right was disabled  my server updated and was say kernel  need updating so may had some thing to do with that  as to why it was disabled

i rebooted the server and updated the kernal  
and enabled engintron 

now on all the files that it should cache i get this for css

HTTP/1.1 200 OK
Server: nginx
Date: Thu, 13 Apr 2017 12:04:25 GMT
Content-Type: text/css
Content-Length: 76284
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Thu, 28 Jul 2016 07:21:51 GMT
Expires: Sat, 13 May 2017 12:04:25 GMT
Cache-Control: max-age=2592000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: Engintron
Pragma: public
Vary: Accept-Encoding
Accept-Ranges: bytes

and a js file 

HTTP/1.1 200 OK
Server: nginx
Date: Thu, 13 Apr 2017 12:08:15 GMT
Content-Type: application/javascript
Content-Length: 21397
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Thu, 28 Jul 2016 07:21:52 GMT
Expires: Sat, 13 May 2017 12:08:15 GMT
Cache-Control: max-age=2592000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: Engintron
Pragma: public
Vary: Accept-Encoding
Accept-Ranges: bytes

a static image 

Server: nginx
Date: Thu, 13 Apr 2017 12:10:00 GMT
Content-Type: image/jpeg
Content-Length: 1406
Connection: keep-alive
Last-Modified: Sun, 17 Jul 2016 09:26:45 GMT
Expires: Mon, 12 Jun 2017 12:10:00 GMT
Cache-Control: max-age=5184000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: Engintron
Pragma: public
Vary: Accept-Encoding
Accept-Ranges: bytes

**Comment by fevangelou** [comment]
Call each file one more time and you'll see that "X-Nginx-Cache-Status" switches to "HIT".

**Comment by tammyrocks** [comment]
when i look in /tmp/engintron_dynamic/
and static all there is is heaps of empty folders  with nothing in them

**Comment by tammyrocks** [comment]
Server: nginx
Date: Thu, 13 Apr 2017 12:16:51 GMT
Content-Type: image/jpeg
Content-Length: 1406
Connection: keep-alive
Last-Modified: Sun, 17 Jul 2016 09:26:45 GMT
Expires: Mon, 12 Jun 2017 12:16:51 GMT
Cache-Control: max-age=5184000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: REVALIDATED
X-Server-Powered-By: Engintron
Pragma: public
Vary: Accept-Encoding
Accept-Ranges: bytes

**Comment by fevangelou** [comment]
The cache is for 1 min (server-side) but client-side caching is 30 to 60 days. Browsers use the latter. It works just fine.

**Comment by tammyrocks** [comment]
ok so cache is working 
how do i get it to be server from cookieless domain

i am shore i seen here somewhere about the cache is served from cookieless domain
on pingdom and other tests all say my static content is not from cookieless domain

**Comment by fevangelou** [comment]
Do you see any cookies in the curl response? Cause I don't see any.

**Comment by tammyrocks** [comment]
but even engintron off in the first tests i posted has same no cookies but thats 100% from domain with cookies

**Comment by fevangelou** [comment]
Doesn't matter. What matters is that static assets are loaded with no cookies in the response. This means that caching is more efficient on the browser's side. The html page linking these files can have cookies of course but this is not a problem.

I consider the resolved now.

**Comment by tammyrocks** [comment]
yes thanks

**Comment by efelinto** [comment]
I have the same problem ... can I post here?
https://i.imgur.com/ymvg9Hm.png
It follows its guidelines, but the cache is simply not working for static files. The main page of the site, the posts and all the rest are ...
As you can see in print I made the same call twice but "X-Nginx-Cache-Status" simply did not change.
