### ISSUE TITLE
Not so easy to understand

### ISSUE THREAD

**Issue by vietzon** [engintron/engintron#504]
Hello

I just installed WHM 62.0 and engintron. Every went OK. But i am not sure what to do next? I mean i create an account with domain. When i enter the domain, i see 502 bad gateway. So i type domain.com:8080 and i can see the website. 

So, i wonder, is that correct? User should not type 8080 right? I tried to read the wiki but nothing about setup account  xyz.com or how-to.

I am disabling the plugin for now. It should be some wiki about how to setup after installation!

Cheers

**Comment by lafrance** [comment]
Have you made sure that whm tweak setting as port 8080 chosen ?

**Comment by vietzon** [comment]
Hello

I do not see any mention about that. A manual or guide about setup a demo
domain would be really helpfum for those who are devops :)

Den 27 mars 2017 6:57 PM skrev "lafrance" <notifications@github.com>:

**Comment by vietzon** [comment]
Hello

Yeah i just checked the tweak setting. It's 8080 as default. Still same problem. 

![srv03_ _webhost_manager](https://cloud.githubusercontent.com/assets/635831/24399815/557ad5dc-13ae-11e7-95ec-f6023837d3ff.png)

**Comment by fevangelou** [comment]
First off, there's a ton of documentation here: https://github.com/engintron/engintron/wiki
Secondly, you don't need to do anything really, in terms of Engintron setup.

If you add a site in Apache and you get a 502 error in Nginx, it probably means the domain you added does not resolve to the server yet. So Nginx cannot really fetch content from Apache.

Was that the case? Is this a domain that does not yet resolve to your server and which you only see from hardcoded entries in your computer's "hosts" file?

**Comment by vietzon** [comment]
Yes, i did read the wiki from the first moment. But when i get 502, and nothing on wiki about this. I assumed "there must be more settings that i dont know about"

If you say "no need to do anything", then i guess need to test again.

And yes, the account created by WHM and it was helloworld.com, and using "hosts". Can you explain why the domain and website shows correct if i use 8080? Does engintron check if helloworld.com is actually point to our server?

Is this the way to go:

1. Add real domain the server
2. Point A record to the server
4. Go to www.newrealdomain.com
5. It will work?


Cheers

**Comment by fevangelou** [comment]
Yes, it checks if it's an actual domain. And had you actually read the wiki you would have seen this: https://github.com/engintron/engintron/wiki/Engintron-&-(under-development)-domains-that-don't-yet-resolve-(point)-to-your-cPanel-server (pokes your eye out)
