### ISSUE TITLE
Magento too many redirects issue on Admin and Client page

### ISSUE THREAD

**Issue by Ylmzef** [engintron/engintron#505]
When i enabled Engintron on server Magento Admin and Client url's not loading due the too many redirects error. The domains on CloudFlare with Flexible SSL and HSTS enabled only on Magento there no configuration on CloudFlare for SSL and page rules. How can i fix this issue?

**Comment by fevangelou** [comment]
Your setup doesn't make sense man. CF's "Flexible SSL" means CF proxies HTTPS traffic to HTTP (port 80) on your server. HSTS enforces the browser to always load the HTTPS version of a site, even if there is no redirect in place for HTTP to HTTPS.

So now this is what happens to your site:

CF HTTPS > Server HTTP > HSTS redirects to HTTPS and the loop goes on.

HSTS is also cached in your browser. So the real solution is to a) use "Strict SSL" in CF Crypto settings and b) clear your browser's cache for the changes to take effect.

**Comment by Ylmzef** [comment]
"c) It is possible to force-redirect all your domains on CloudFlare to HTTPS if you have SSL enabled
in CloudFlare's "Crypto" settings page. Make sure you use "Flexible SSL" there so CloudFlare proxies
traffic from HTTPS to Nginx's HTTP port (80). This way you can utilize Nginx's caching & performance
benefits to the fullest. If you use "Strict SSL" in CloudFlare's "Crypto" settings page, then CloudFlare
will proxy all HTTPS requests to your Apache's HTTPS port (443) and therefore you will miss any benefits
from Nginx's caching & overall performance features."

**Comment by fevangelou** [comment]
But I don't mention HSTS there. Duh.

HSTS is what causes the freaking redirect loop.

**Comment by fevangelou-asshole** [comment]
@fevangelou Stop being such a defensive asshole and little whiny bitch. If you can't handle bug reports and criticism, don't have a public repo on github. Fucking idiot.

**Comment by Ylmzef** [comment]
I will queto so for better understanding

> If you use "Strict SSL" in CloudFlare's "Crypto" settings page, then CloudFlare
> will proxy all HTTPS requests to your Apache's HTTPS port (443) and therefore you will miss any benefits
> from Nginx's caching & overall performance features.

**Comment by fevangelou** [comment]
These options make no difference to the fact that you enabled HSTS. This is the problem.

If you wanna use HSTS, go with Strict SSL.

**Comment by Ylmzef** [comment]
I disabled HSTS and still the issue.
Also when i switch to Strict SSL i am getting ssl error.

**Comment by fevangelou** [comment]
Depending on how HSTS was setup your browser may have cached the redirect and you have to clean its entire cache to remove the redirect it causes.

Use another browser which you didn't open when you had made the changes to enable HSTS.

**Comment by Ylmzef** [comment]
I done it but still same..

**Comment by Ylmzef** [comment]
Can you provide me configuration when someone using Engintron + Cloudflare + Magento 2.
I tired all things on your documentation, but there no solution for it.

**Comment by kauanguesser** [comment]
Got same problem... the page dont load fully, still loading forever and got 504 gateway timeout :(
