### ISSUE TITLE
Engintron not working with cpanel.domain.com or whm.domain.com

### ISSUE THREAD

**Issue by urbaman** [engintron/engintron#506]
Hi,

Engintron 1.8.2 and cPanel 11.62.17

whm.domain.com or cpanel.domain.com not working.
They get redirected to domain.com:2087 and domain.com:2083 (I do not want this) or get "TO MANY REDIRECTS" error.

What's the correct WHM/Engintron configuration to get them work properly?
Both http and https please.

Thank you.

**Comment by fevangelou** [comment]
They should work unless a) there are no DNS records for them (aka you use external DNS with cPanel) or b) you've somehow modified the default behaviour for these redirects in cPanel (if I recall there are a couple of settings to always enforce switching to a port in Tweak Settings).

**Comment by urbaman** [comment]
Hi,

Do you mean I have to use local DNS records for that to work? I have them (cpanel, whm, webmail) properly set on my registrar.
And I'm quite sure they work, without Engintron.

**Comment by fevangelou** [comment]
I'm sorry I can't help you like this. Either provide me with actual URLs to check and/or a screenshot of the related section from "Tweak Settings".

**Comment by urbaman** [comment]
Hi,
Here are the screenshots.
Hostname is srv1.urbaman.it
Domain is www.urbaman.it (so: whm.urbaman.it ...)

![redirects](https://cloud.githubusercontent.com/assets/26753344/24498846/177cfe3e-1540-11e7-8f1b-966f8f580be8.png)
![subdomains](https://cloud.githubusercontent.com/assets/26753344/24498847/178268e2-1540-11e7-8a1b-ad79f7031a7f.png)

Actually, they get redirected with default Engintron conf, and get TOO MANY REDIRECTS if I change the proxy rules for them in Engintron.

**Comment by fevangelou** [comment]
I think you forgot to mention you also have Varnish enabled on your server. This is probably the issue. BTW, Varnish is not needed. Nginx is much more efficient with micro-caching.

**Comment by urbaman** [comment]
I think I already tried without Varnish, I'll try again and report back.

**Comment by urbaman** [comment]
Ok, disabled varnished, and tried connecting form a different machine (so no browser caching/cookies involved) and it gets redirected as well, not fixed though.

**Comment by urbaman** [comment]
Sorry, problems with engintron when tried to restart.

**Comment by urbaman** [comment]
Hi,

- I uninstalled engintron and xvarnish
whm.urbaman.it and cpanel.urbaman.it worked as expected.

- I re-installed engintron (so: default conf)
whm.urbaman.it and cpanel.urbaman.it got redirected.
this is with "Proxy cPanel specific subdomains" part commented or not.

- I unchecked "Proxy subdomains" in Tweak settings"
whm.urbaman.it and cpanel.urbaman.it get to "http://whm.urbaman.it/cgi-sys/defaultwebpage.cgi" (default cpanel for "no website")

- I rechecked "Proxy subdomains" in Tweak settings"
whm.urbaman.it and cpanel.urbaman.it got redirected.
this is with "Proxy cPanel specific subdomains" part commented or not.

So I think Engintron is actually doing the tricky part.

**Comment by fevangelou** [comment]
Did you have some other plugin for Nginx on cPanel previously installed?

---

Regards,

Fotis Evangelou

Engintron is Nginx on cPanel, done right!
Learn more at: https://engintron.com

**Comment by urbaman** [comment]
Hi,

I might have tried some, and manual installation as well, but not in this build of the server, as I remember.
Is there a better way to clean any other installation (already tried the ones you provide in the wiki)

Just can't get them to work.

**Comment by fevangelou** [comment]
Uninstall Engintron and then delete entirely the folder /etc/nginx/. Finally, have a look at /etc/yum.repos.d/ where all YUM repos are located. When you uninstall Engintron, it will delete its nginx.repo entry. Check if you see anything else beyond stock CentOS repos which start with "centos...". Afterwards reboot your server in case there were any processes stuck.

When you're done with the above, re-install Engintron.

**Comment by urbaman** [comment]
Did as you said, these are my repos after clearing:
cl-mysql.repo                cloudlinux.repo          imunify360.repo
cloudlinux-ea4.repo          EA4.repo                 kernelcare.repo
cloudlinux-ea4-testing.repo  imunify360-alt-php.repo

After Engintron re-installation:
I had a connection already established to https://whm.urbaman.it and it stayed there (I can navigate through it).
http does not, it gets redirected to srv1.urbaman.it:port. So I think this is the problem.

I solved by doing this to Engintron default.conf:

`    # Proxy cPanel specific subdomains
    if ($host ~* "^webmail\.") {
#        set $PROXY_DOMAIN_OR_IP "127.0.0.1";
#        set $PROXY_TO_PORT 2095;
        return 301 https://$host$request_uri;
    }
    if ($host ~* "^cpanel\.") {
#        set $PROXY_DOMAIN_OR_IP "127.0.0.1";
#        set $PROXY_TO_PORT 2082;
        return 301 https://$host$request_uri;
    }
    if ($host ~* "^whm\.") {
#        set $PROXY_DOMAIN_OR_IP "127.0.0.1";
#        set $PROXY_TO_PORT 2086;
        return 301 https://$host$request_uri;
    }
    if ($host ~* "^webdisk\.") {
#        set $PROXY_DOMAIN_OR_IP "127.0.0.1";
#        set $PROXY_TO_PORT 2077;
        return 301 https://$host$request_uri;
    }
    if ($host ~* "^(cpcalendars|cpcontacts)\.") {
#        set $PROXY_DOMAIN_OR_IP "127.0.0.1";
#        set $PROXY_TO_PORT 2079;
        return 301 https://$host$request_uri;
    }`

This solved for me, redirecting to https correctly proxying.
And that's better for me as well: much secure.

Hope this helps.

**Comment by fevangelou** [comment]
OK, I got you now. There are no HTTPS definitions for these special subdomains, only HTTP ones. I'll issue an update to fix this.

**Comment by fevangelou** [comment]
Scratch that. I guess it's too late here... The definitions are in place already. They are in: /etc/nginx/common_https.conf - and they work.

What you did above is essentially kill these rules when they are called via HTTP. So, essentially, the rules in common_https.conf are what kicks in and redirects correctly.

To verify, try calling http://whm.urbaman.it & https://whm.urbaman.it (HTTP and HTTPS version respectively) in a new "private" browser window, separately.

Maybe the issue it did not work for you in the first place is a modified default value in cPanel's redirections. If you notice "SSL redirect destination [?]" is by default set to " SSL Certificate Name". Despite the fact that this option is disabled (because "Always redirect to SSL" is set to "On"), perhaps it sticks with the rules. So switch "Always redirect to SSL" to "Off", revert "SSL redirect destination" to "SSL Certificate Name" and then switch back "Always redirect to SSL" to "On" again. Then save, cleanup Nginx's cache/temp files and restart Apache/Nginx.

**Comment by urbaman** [comment]
Hi,

I think you got it the other way around: https already worked for me as I found out (at least in the last settings), http was not: infact I changed default.conf, not common_https.conf.
Or it's me not getting your point.

In my configuration, I think SSL (as defined in common_https.conf) always worked.
It's http that was not proxying, but redirecting from http://whm.urbaman.it to htts://srv1.urbaman.it:2087
And not beacause any of the "redirect" Tweak settings, as they worked without Engintron.

Now, with http->https returns in /etc/nginx/default.conf (as per my code above) and
Non-SSL redirect destination [?] -> Origin Domain Name default
SSL redirect destination [?] -> Origin Domain Name
in "Tweak settings":
http subdomains redirect to https subdomains (more secure), and https subdomains are workingas wanted.

**Comment by fevangelou** [comment]
I got where you did the changes (you mention the file either way). What was borked in your server though is HTTP (Nginx) to HTTP (cPanel/ports 2086 etc.) to HTTPS (cPanel/ports 2087 etc.).

This shouldn't happen. But anyway. If it's working for you, then cool. Just remember to apply your changes whenever you update Engintron.

**Comment by urbaman** [comment]
Ok, got you now, thank you.

Tryied again to switch to the default "redirection" Tweak Settings, and Engintron's default.conf back to default, not working.

I have to stick to my configuration.

Thank you very much for your patience and support!

**Comment by fevangelou** [comment]
You're welcome.
