### ISSUE TITLE
.htaccess banning?

### ISSUE THREAD

**Issue by greenot** [engintron/engintron#507]
Seeing a strange issue since installing Enginetron.  We are occasionally get the server's ip listed in client accounts .htaccess in a deny line which effectively shuts the site down.

Is this something Enginetron is doing and if so, is there a way to stop it?

Or is this just coincidence?

**Comment by fevangelou** [comment]
.htaccess files don't work like firewalls by dynamically adding block rules for IPs.

Additionally, why would anyone block their own IP (also the server's) in their .htaccess file?

Unless they use something like this https://perishablepress.com/how-to-block-proxy-servers-via-htaccess/ which would never make it to any default CMS .htaccess rules by the way...

Nginx does use the X-Forwarded-For header to pass each visitor's IP on to Apache. Rules as mentioned in the link I gave you above would block such legitimate traffic and they should be removed. Such rules could be applied by a plugin if your clients use a CMS like WordPress, Joomla etc.

**Comment by greenot** [comment]
Yeah, we got this sorted.  The mod_rpaf was not properly installed and required adjustments.
