### ISSUE TITLE
proxy_cache_path size

### ISSUE THREAD

**Issue by tallesairan** [engintron/engintron#513]
## and recommended increasing the size of the cache ?, as I did below. 
` proxy_cache_path /data/nginx/engintron_dynamic levels=1:2 keys_zone=engintron_dynamic:10000m inactive=60m max_size=10000m use_temp_path=off;
    proxy_cache_path /data/nginx/engintron_static levels=1:2 keys_zone=engintron_static:10000m inactive=60m max_size=10000m use_temp_path=off;
    proxy_temp_path /data/nginx/engintron_temp;`
### **I don't know if I've done right is working so far**

**Comment by fevangelou** [comment]
Leave the defaults please. Your values are invalid.
