### ISSUE TITLE
SSL Certificates Broken with NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by wppronto** [engintron/engintron#514]
Hi,

First, thanks for all of your great work!

When Engintron is enabled, SSL certificates on the server show a security warning with:

NET::ERR_CERT_COMMON_NAME_INVALID

It looks like the sites are trying to pull up the SSL certificate for the server's hostname, not the particular site.

When we disable Engintron, the issue goes away.

We're using cPanel AutoSSL with the Comodo option (not Let's Encrypt).

Thanks!

**Comment by theoxgr** [comment]
i had the same issue. try to restart apache and try again with a clean browser.

**Comment by wppronto** [comment]
Hi theoxgr, thank you. I still had the issue after restarting Apache, and many clients were still reporting it. :-(

Has the problem gone away for you or did it ever come back and require another restart of Apache?

**Comment by theoxgr** [comment]
what provider are you using for the AutoSSL? comodo or let's encrypt?

**Comment by wppronto** [comment]
Comodo.

**Comment by wppronto** [comment]
Thanks. Do you mean Engintron is only compatible with Let's Encrypt?

**Comment by xuanduoc84** [comment]
Today, one of some ssl domain got that error
Yestoday, all ssl working fine

**Comment by bubblemedialtd** [comment]
I have just updated Engintron to 1.8.2, now all sites that were SSL enabled are using the WHM default SSL certificate, for the server hostname. I have attempted to re-install SSL certificates on individual domains, but they are still using the default host SSL.

Please advise

**Comment by fritolays** [comment]
Given that now with v64 we can get AutoSSL for all proxy subdomains the 5 cert limit per domain that Let's Encrypt (Fleet SSL) has is, just that, limiting.
The included Comodo provider does not have this limitation.
So consider this a +1 to having Comodo supported properly.

I can confirm that Engintron + Comodo AutoSSL produces a 500 error, when attempting to issue a cert; specifically when Comodo checks the temporary domain file.

Disabling Engintron will allow certs to be issued.
Then you can re-enable Engintron, and restart http services to use the issued certs.

I realize this is not a proper workaround as one will need to disable Engintron every 3 months to reissue certs; but it will get you up an running.

**Comment by fevangelou** [comment]
@all

Some considerations...

a) Prefer The Let's Encrypt Plugin by cPanel -
 info here: https://documentation.cpanel.net/display/CKB/The+Let's+Encrypt+Plugin

b) Enable AutoSSL, make sure all your domains have it on and make sure auto-updating is also enabled. If you have certificates from previous providers for domain validation only (which you don't really need now), delete them from the SSL Manager and re-issue from AutoSSL

c) Once done with (a) and (b), cleanup Nginx's cache/temp files and restart Apache/Nginx.

Everything should work as expected now.

The free Comodo certificates seem to cause chain issues for god knows why. The solution above is simpler.

**Comment by Friends4U** [comment]
Had the same problem here... the Let's Encrypt from CPanel solved it.

**Comment by veryDead** [comment]
I have the same problem but I am on an older cpanel version that does NOT have AutoSSL.

The client's comodo certificate was installed manually through WHM, but it is not being used when engintron is enabled. The server main hostname SSL certificate is being used instead.

I have manually deleted the comodo cert and key from the server, then I purged the nginx cache and restarted nginx apache. Then I reinstalled the comodo certificate in WHM. Same problem, serving the main hostname ssl instead of the proper ssl for the dedicated ip/domain.

The only way I can get it to work is to then just disable engintron, which of course is not what I want to do.

Another oddity, when I have removed the SSL certificate from the server and disabled engintron, it fails in a browser as it should. But when I enable engintron and purge the cache, it still serves the main server SSL cert even though NO ssl is installed on the IP/domain in question. That seems like incorrect behavior.

Any ideas?

**Comment by fevangelou** [comment]
@veryDead Why can't you update to the latest cPanel release?

**Comment by jhawkins002** [comment]
Greetings! I just wanted to add a quick note regarding the use of Lets Encrypt for AutoSSL.

Lets Encrypt and Comodo do not handle rate limits in the same fashion; if you have a use case (such as a university) where you have many clients requesting certificates within highly nested sub-domains Lets Encrypt's domain rate limits will be hit almost instantly. For instance LE considers lab.department.college.uni.edu to be the exact same domain as uni.edu for the purposes of rate counts. Comodo does not, and thereby is the only viable AutoSSL provider in such a use case. 

I just wanted to bring this up to make clear that treating Lets Encrypt as drop in replacement for Comodo is not universally applicable unfortunately. After struggling with this for a few months, I think the long and short of this may be that some of us may have to stop using Engintron and perhaps lobby cPanel to speed up internal NGINX support via EasyApache.

**Comment by youstable** [comment]
I am still facing this issue with Let's Encrypt, we are providing Shared to our customers from https://youstable.com and after we enable Lets Encrypt every site which has Lets Encrypt SSL goes down with error message that site is not secure.
