### ISSUE TITLE
Update to 1.8.2 from 1.7.3 without SSL certificates on all domains possible?

### ISSUE THREAD

**Issue by ciscospirit** [engintron/engintron#515]
Hello,

 i am not sure about to upgrade to the latest 1.8.2 from 1.7.3 cause I read something in the changelog and i am not sure what that means:

`Finally addressed the elephant in the room. Engintron now fully supports both HTTP and HTTPS traffic. Additionally HTTP/2 is enabled by default. It's important that domains already have an issued TLS/SSL certificate via cPanel. With the option to issue free such certificates from within cPanel (AutoSSL feature) there's no cost reason not have any domain without a TLS/SSL certificate. It's important to note that since Nginx now binds to both ports 80 & 443, if you have CSF or any other firewall installed, you must allow ports 8080 and 8443 respectively which now bind to Apache.`

Does this mean that, if I upgrade to 1.8.2 EVERY Domain need an SSL zertificate??? I sell the AutoSSL function as a service, so this is not activated by default on all accounts. So is there a problem to upgrade to 1.8.2 with out having SSL on every domain? And if yes, what settings i must take to work arround this.

thank you.

**Comment by ciscospirit** [comment]
does anybody has an information for me?

**Comment by theoxgr** [comment]
noone replies here never lol

**Comment by fevangelou** [comment]
@ciscospirit 
a) Install cPanel's free Let's Encrypt Plugin >> https://documentation.cpanel.net/display/CKB/The+Let's+Encrypt+Plugin
b) Enable AutoSSL for all domains and have it issue or re-issue certificates for all your domains
c) Upgrade Engintron to v1.8.3.

**Comment by ciscospirit** [comment]
Hello,

like i wrote above, i cannot Enable AutoSSL for every Domain, cause we sell the autossl function as a service.

is there any other way?

**Comment by fevangelou** [comment]
Well, since this is a free feature in cPanel, I don't see why you should sell it. And I'm afraid there no other way if you wanna move to Engintron v1.8.3.

**Comment by ciscospirit** [comment]
hm okay, thank you... then we need to think about it or stay at 1.7.3
will there maybe in future release an option to exclude this?

**Comment by dcordovez** [comment]
@fevangelou, ¿In Engintron 1.8.2 and 1.8.3 is really mandatory that each site has an activated SSL certificate?
HTTPS use more cpu load. May be little for a single website, but on a server with multiple sites and traffic, it  can be a considerable additional CPU consumption.  In my case, not all my clients require the use of SSL (for services like mail, cpanel or FTP, we have a certificate issued to the host name). 

In one server I have Engintron 1.8.1 and in this server i have sites with ssl certificate and without ssl certificate, and both works fine.

**Comment by fevangelou** [comment]
@dcordovez TLS/SSL certificates are of course NOT mandatory in order for Engintron to work fine. :)

**Comment by ciscospirit** [comment]
so what does this mean?

Do I need SSL on every Domain or not for Engintron to work?

your last message contradicts your message before... i want to update to 1.8.3 but 80% of my hosts (arround 200 on this deployment server) does not have SSL and autossl is no option.

**Comment by fevangelou** [comment]
My response does not contradict anything. I simply mentioned the easiest route to have all your sites served over HTTPS. If you have domains that don't use any certificate, Engintron will still serve them just fine over HTTP.
