### ISSUE TITLE
Wiki document initial optimization ea4

### ISSUE THREAD

**Issue by picateclas** [engintron/engintron#516]
Hello,

I'm looking at this part of the guide, but the part of installing the profile I think is for ea3, not being compatible with ea4.

https://github.com/engintron/engintron/wiki/Beyond-Engintron:-cPanel-WHM-initial-optimal-setup

Could someone put the recommendation for ea4? Or any recommended profile for ea4?

Thank you very much

**Comment by fevangelou** [comment]
You don't really need one. If you are using EasyApache 4, a great start is the profile named "All PHP Options + OpCache".

I also updated the related guide to reflect that.
