### ISSUE TITLE
How To: Disable OCSP Stapling

### ISSUE THREAD

**Issue by tess0072** [engintron/engintron#517]
Where would be the correct place to disable OCSP stapling, cant seem to find the directive anymore. I could have sworn it used to be in common_https.conf.

**Comment by bdtech** [comment]
Check out the Utils folder. You can can comment it out in the script that builds the Nginx conf.

**Comment by tess0072** [comment]
I've tried this but I still receive the errors in the error log:

2017/04/11 19:10:37 [error] 344442#344442: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:unable to get issuer certificate) while requesting certificate status, responder: ocsp2.globalsign.com

**Comment by bdtech** [comment]
It will take effect on the next Nginx conf build. Feel free to run the script manually then reload Nginx.

**Comment by fevangelou** [comment]
As of v1.8.3, OCSP stapling is off as it's causing more issues that it's supposed to solve.

If you upgrade to v1.8.3, OCSP stapling will switch off.
