### ISSUE TITLE
SSL sites not working

### ISSUE THREAD

**Issue by ehcanada** [engintron/engintron#518]
For some unknown region our ssl sites are no longer coming up after working well with engintron for months. Can anyone assist?

**Comment by fevangelou** [comment]
What Engintron version are you using?
Are certificates issued from AutoSSL?
The more info you provide, the more I can help you.

**Comment by ehcanada** [comment]
Fevangelo!! Thank you for getting back to me!
Once the issue occurred we upgraded to 1.8.2.which seemed to resolve the issue. Although i am unfamiliar with the working of it and do not know if further tweaking is required.
It is currently running nginx and apache together, is there a significant advantage to running nginx on it's own. 
Our host is helpful, but do not officially support nginx or engintron, so I get flack from them whenever an issue arises.
I don't believe our certs are autossl

**Comment by fevangelou** [comment]
Running Nginx on its own would be a hack. Engintron is your safest bet. And if you need any help, you always got this place.

Is the SSL issue resolved?

**Comment by ehcanada** [comment]
yes, it is resolved. Thank you.
Is there any way to get someone to help in a quicker fashion?
i.e. are you available to content to get help as soon as an issue arises? 
available for contract  work?
thanks again
Colin

**Comment by fevangelou** [comment]
Yes, of course. You can email "engintron at gmail dot com" for more info.
