### ISSUE TITLE
"http2" parameter requires ngx_http_v2_module

### ISSUE THREAD

**Issue by KacemRostom** [engintron/engintron#519]
Hey everybody,

So i installed Nginx on my server which uses Http/2 for all my websites, but i keep getting this message when starting Nginx:
Restarting nginx daemon: nginxnginx: [emerg] the "http2" parameter requires ngx_http_v2_module in /etc/nginx/conf.d/default_https.conf:5

I did the standard setup for Nginx using the provided procedure with no hope, could you please advice on what to be performed to resolve this issue?

I'm using Centos 7 with WHM/Cpanel 62.0

**Comment by ubidzz** [comment]
the http/2 module is already being used in the engintron plugin but it won't use it because you need to compile a OpenSSL 1.0.2 or higher to the nginx server. With out a new version of OpenSSL all your websites will use the http 1.1 protocol and not h2 protocol. The engintron plugin use the default OpenSSL that is installed with cPanel and that is 1.0.1e.

**Comment by KacemRostom** [comment]
Thanks, i tried this to overcome that issue but i struggled to fix it:
https://www.joomlagate.com/index.php?option=com_content&view=article&id=325&Itemid=19

**Comment by lafrance** [comment]
this may help

https://github.com/engintron/engintron/issues/499

**Comment by princejha95** [comment]
Here's my nginx configuration:

nginx version: nginx/1.13.8
built by gcc 6.3.0 (GCC) 
built with OpenSSL 1.0.2q-fips  20 Nov 2018 (running with OpenSSL 1.0.2l-fips  25 May 2017)
TLS SNI support enabled

But i am still facing issue **http2" parameter requires ngx_http_v2_module** while using http2 in nginx conf. Can anyone please tell how to fix this ?

**Comment by jeon3029** [comment]
@princejha95  you may install nginx with custom flag

`configure --with-http_v2_module`

see this will help.
https://www.nginx.com/resources/wiki/start/topics/tutorials/installoptions/
https://nginx.org/en/docs/http/ngx_http_v2_module.html
