### ISSUE TITLE
http2 not working within Chrome [ALPN ISSUE?]

### ISSUE THREAD

**Issue by webhost247** [engintron/engintron#522]
Hello, after re-following the instructions within #437 to enable h2 / HTTP/2 on my server with Nginx, Nginx is now is installed correctly with:
> OpenSSL 1.1.0e

But for some reason chrome is not receiving requests using HTTP2 and instead uses HTTP/1.1, I have read that this has something to do with ALPN but nginx should be built with ALPN from the repo I installed from #437 

> Name : nginx
Arch : x86_64
Epoch : 1
Version : 1.11.13
Release : **1.el7.codeit**
Size : 9.3 M
Repo : installed

Edit "I know this is not a direct issue with engintron and I am sorry @fevangelou for opening this issue, I just want to get this working, I know this is a custom modification"

@ubidzz
@tux-tn

**Comment by windsofchange** [comment]
@webhost247 
I guess when you installed the CodeIt repo, you did not disable the nginx.repo !

Nginx released new stable/mainline versions which CodeIt has not built. So I guess your install updated nginx version from nginx sources (higher version no.) and you lost your alpn support

You need to disable nginx.repo (not delete) and the run yum downgrade nginx and then clear cache and restart nginx from Engintron

BTW has Engintron only support nginx repo, CodeIT issues are beyond their scope

**Comment by tux-tn** [comment]
Hello @webhost247 ,
Can you verify the output of to confirm what @windsofchange said
```shell
nginx -V
```
