### ISSUE TITLE
Nginx Block Bad Bots

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#523]
How to install this add-on https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker with engintron?

**Comment by Nirjonadda** [comment]
@mitchellkrogza added fix from here: https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/24

**Comment by bdtech** [comment]
Have you tried including both bad bot conf files into custom_rules? That way it will be preserved with future engintron updates. @Nirjonadda

**Comment by mitchellkrogza** [comment]
Will look at this in the morning, family time now.

**Comment by mitchellkrogza** [comment]
@bdtech just looking at this now, how would one specify that in the custom_rules.dist file ???

Never used Engintron and simply trying to help make this easy for people to use my blocker. 

Documentation on the custom_rules.dist is a bit vague for me, please can you assist with easy statement/syntax to tell Enginetron custom_rules.dist to retain extra files in /conf.d/ and also to do the necessary includes in vhosts?

**Comment by bdtech** [comment]
You could append the one or two nginx includes to /etc/nginx/custom_rules
This file will be preserved through engintron updates. @mitchellkrogza

**Comment by mitchellkrogza** [comment]
so if I simply add

```
include /etc/nginx/conf.d/globalblacklist.conf;
include /etc/nginx/conf.d/botblocker-nginx-settings.conf;
```
just like that into custom_rules.dist it will preserve the existing files on an update? 

No if {} statements required as per your examples in custom_rules.dist ????

**Comment by bdtech** [comment]
Yes but just "custom_rules" actually. custom_rules.dist is overwritten and updated by engington. Test it out of course :)

**Comment by mitchellkrogza** [comment]
Great added it in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/b43fc03e77ef69e6f31c15eeacaf90cace7030ba if @Nirjonadda or others using the blocker can test the files are not deleted from /etc/conf.d/ after an update and feed back to me I would appreciate it.

**Comment by Nirjonadda** [comment]
@mitchellkrogza I am back to home. Yes its remove files /etc/nginx/conf.d/botblocker-nginx-settings.conf and globalblacklist.conf with Enginetron update but are not remove /etc/nginx/bots.d/ folder.

**Comment by mitchellkrogza** [comment]
Report it on Enginetron as that was following their instructions

**Comment by bdtech** [comment]
@Nirjonadda The engintron.sh updater clears out conf.d. You'd want to use a folder to preserver.

`/bin/rm -f /etc/nginx/conf.d/*.conf`

**Comment by mitchellkrogza** [comment]
Will try another fix in the morning otherwise you really are on your own,as this blocker was designed for Nginx and not for all other strange derivatives of it which use cpanel and other things. I've gone beyond my call of duty on helping you already

**Comment by mitchellkrogza** [comment]
@Nirjonadda look at lines 316 > 318 of https://github.com/engintron/engintron/blob/master/engintron.sh

you will see this

```
    fi
    /bin/rm -f /etc/nginx/conf.d/*.conf
    /bin/cp -f $APP_PATH/nginx/conf.d/default.conf /etc/nginx/conf.d/
```

Try changing it to this (simply commenting out the removal of all custom conf files in /etc/conf.d)

```
    fi
    #/bin/rm -f /etc/nginx/conf.d/*.conf
    /bin/cp -f $APP_PATH/nginx/conf.d/default.conf /etc/nginx/conf.d/
```

**Comment by Nirjonadda** [comment]
OK, I am asking to @fevangelou If he can implemented in engintron.sh

**Comment by Nirjonadda** [comment]
@fevangelou I am added here: https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/29

**Comment by fevangelou** [comment]
Instead of modifying the installer, which doesn't really make sense, why not simply change WHERE you store these extra files? E.g. in /etc/nginx/extras/. Then simply include them in your config FROM that location.

**Comment by mitchellkrogza** [comment]
@fevangelou thanks, that's a much wiser solution. I'm not really familiar with Enginetron ust trying to help users and also to do it cleanly without modifying code. I will test this later and amend my EngineTron example on https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker to rather use the extras folder. 👍

**Comment by fevangelou** [comment]
Thanks. BTW it's Engintron, not Enginetron ;)

**Comment by mitchellkrogza** [comment]
Yes  I make that typo every single time 😀

**Comment by mitchellkrogza** [comment]
@fevangelou where is your documentation on the /extras folder and how to configure it? The zipped up nginx folder originally sent to me by @Nirjonadda does not have any /extras folder.

**Comment by mitchellkrogza** [comment]
@fevangelou also how can I test Engintron without actually having CPanel and a license for CPanel??

**Comment by Anthesum** [comment]
I get an error when checking the config:
nginx: [emerg] unknown directive "geo" in /etc/nginx/conf.d/globalblacklist.conf:4822

What is wrong in my configuration?

**Comment by mitchellkrogza** [comment]
Your Nginx has been configured or built without the geoip module. If you are on Ubuntu it's as simple as running 

sudo apt-get install nginx-extras

You can check what modules Nginx has been compiled with using 

sudo nginx -V

Kind Regards
Mitchell Krog
Visit me at https://mitchellkrog.com

License or buy my images at http://www.gettyimages.com/search/photographer?excludenudity=true&family=creative&page=1&photographer=mitchell%20krog&sort=best#license

**Comment by Anthesum** [comment]
I'm using for the installation the script  nginx-autoinstall.sh which includes modules like pagespeed and brotli. My server runs under debian and I installed 

nginx version: nginx/1.12.0
built by gcc 4.9.2 (Debian 4.9.2-10)
built with OpenSSL 1.0.1t  3 May 2016
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --user=nginx --group=nginx --with-cc-opt=-Wno-deprecated-declarations --without-http_ssi_module --without-http_scgi_module --without-http_uwsgi_module --without-http_geo_module --without-http_split_clients_module --without-http_memcached_module --without-http_empty_gif_module --without-http_browser_module --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_mp4_module --with-http_auth_request_module --with-http_slice_module --with-http_stub_status_module --with-http_realip_module --add-module=/usr/local/src/ngx_pagespeed-1.12.34.2-beta --add-module=/usr/local/src/ngx_brotli --add-module=/usr/local/src/headers-more-nginx-module-0.32

Still:
service nginx configtest
nginx: [emerg] unknown directive "geo" in /etc/nginx/conf.d/globalblacklist.conf:4822
nginx: configuration file /etc/nginx/nginx.conf test failed

Do you have any tip for me? Thank you

**Comment by mitchellkrogza** [comment]
Hi Ralph

Your output of Nginx -V clearly shows that the geo module and many other extra modules for Nginx have not been compiled into Nginx you can see this in your output below with all the --without configuration parameters 

Please Try

sudo apt-get install nginx-extras

Kind Regards
Mitchell Krog

**Comment by mitchellkrogza** [comment]
@Anthesum did you manage to get this sorted ??

**Comment by idevwebs** [comment]
Has anyone gotten the geo modules and successfully implemented the blocker?

**Comment by xuhaibkhan1122** [comment]
If someone is still looking for how to block bad bots. This might help. Add this to [custom_rules for Nginx]

# Block certain bots
if ($http_user_agent ~* (ahrefs|domaincrawler|dotbot|mj12bot|semrush|AhrefsBot|MauiBot|petalbot|MJ12bot|BLEXBot|Python|SemrushBot|coccocbot-image|seostar|AlphaBot|ZoominfoBot|rogerbot|PHPCrawl|magpie-crawler|SeznamBot|ZumBot|MaxPointCrawler|Nutch|Buzzbot|DataForSeoBot|aiHitBot|Barkrowler|BDCbot|Buck|cyencebot|Exabot|ExtLinksBot|FemtosearchBot|Fever|GarlikCrawler|Gigabot|gobuster|GrapeshotCrawler|istellabot|Jersey|Jobkicks|Cliqzbot|linkdexbot|LinkpadBot|ltx71|LumtelBot|Riddler|Scrapy|Seekport|Siteimprove|SMTBot|VelenPublicWebCrawler|yacybot|Yeti|YisouSpider|CCBot|BLP_bbot|OnPageBot|ScoutJet|seoscanners.net|Mail.Ru|lua-resty-http|brokenlinkcheck.com|Megaindex.ru|NL-Crawler)) {
    return 403;
}
