### ISSUE TITLE
Multiple Shared IPs on server

### ISSUE THREAD

**Issue by umarmeo** [engintron/engintron#525]
Hello,
I have 1 main shared IP and each reseller account is set with its own shared IP. So server have 1 main shared IP, few reseller's shared IPs and some dedicated IPs for domains.
I added custom rules for the domains which use cloudflare. 
Shared IP sites and the domains which is using cloudflare worked fine but all reseller's domains went down and start showing Cpanel's default page. 
When I removed all custom rules all domains start working again. 
I can't add each domain with its IP to custom rules as there are alot of accounts. Is it possible that I add all shared IPs only? Or any quick solution for this situation.??

**Comment by xuanduoc84** [comment]
Yes, we need script to automatic add new site to custome rules

**Comment by naja7host** [comment]
same issue here, all resellers accounts give error from when they use cloudflare . how we can enable reseller's ip address also to the custom rules .

**Comment by fevangelou** [comment]
Guys, what you ask may be part of a "Pro" offering of Engintron in the future.

In the meantime, set exceptions. More info in the wiki.
