### ISSUE TITLE
Issue after installing latest version of Nginx in whm/cpanel

### ISSUE THREAD

**Issue by ravi1868** [engintron/engintron#530]
The plugin of engintron for using Nginx and Apache is installed successfully. But when engintron is enabled then my site gets down. (https://cloud.githubusercontent.com/assets/28014066/25396222/73ac3384-2a01-11e7-9ca2-52788950063c.png)
So I have to make it disable to run so that it can run on apache.
My website is www.yollodeals.com
build on PHP framework : codeigniter 
Database : Mysql
server : Apache 2.2

This site can’t be reached

yollodeals.com refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
Please let me know how can i resolve this?

**Comment by fevangelou** [comment]
You'll have to provide more info. First off, the installation log. Secondly, did you have a previous Nginx for cPanel plugin installed on your server?
