### ISSUE TITLE
tmp folder is full

### ISSUE THREAD

**Issue by pablosbs** [engintron/engintron#531]
Hello,

My tmp folder has 4GB of disk space but is full due to engitron tmp files, how can I change the tmp folder of engitron to /home ?

Thank you so much.

**Comment by spirogg** [comment]
not really an answer but just thinking is there a way to run a cron to empty the temp folder after so may GB or every 24 hours 2 days etc ??
 might be easier than changing to /home directory and filling up all that space  

just wondering for my own refrence ? if so can someone write a cron for this or how to ?

thanks

Spiro

**Comment by fevangelou** [comment]
@pablosbs Execute the following:

```
mkdir -p /var/nginx/cache
chown -R nginx:nginx /var/nginx/cache
sed -i "s:/tmp:/var/nginx/cache:" /etc/nginx.conf
nginx -t
service nginx restart
```

Or in line:
`mkdir -p /var/nginx/cache; chown -R nginx:nginx /var/nginx/cache; sed -i "s:/tmp:/var/nginx/cache:" /etc/nginx.conf; nginx -t; service nginx restart`

@spirogg Edit /etc/crontab and add this at the bottom of the file:
```
0 2 * * * root "/engintron.sh purgecache" >> /dev/null 2>&1
```
This will cleanup the cache at 2am every day.
