### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by KPCPS** [engintron/engintron#533]
Hello,

since the last 3 updates of Engintron we are battling to fix this:
Access to Font at 'https://www.XYZ.com/XXX/glyphs.ttf' from origin 'https://www.XYZ.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'https://www.XYZ.com' is therefore not allowed access.

I am not sure if it has something to do Engintron, but it certainly appeared just after the updating of Engintron.

**Comment by ubidzz** [comment]
I have the same problem if i use https://www.test.com it works but if i use https://test.com the CORS policy error comes up. I been trying for months to find a fix and nothing has worked because it seems there something loading that i cant see or find that is making this problem.

**Comment by laurfx** [comment]
I have the same issue but with fonts, for now i comment the location, and I will look tonight to see what's happen, i will post update.

# Enable browser cache for fonts & fix @font-face cross-domain restriction (TTL is 60 days)
#location ~* \.(eot|ttf|otf|woff|woff2|svg|svgz)$ {
#    add_header Access-Control-Allow-Origin *;
#    include proxy_params_common;
#    include proxy_params_static;
#    expires 60d;
#}

**Comment by ubidzz** [comment]
I still could not find a fix but my CORS Policy was stopping my font from loading so i committed the font code in https and http and just added this code to the proxy_params_common page to fix my problem in till i find out why the other code is not working.

`add_header                    Access-Control-Allow-Origin *;`

**Comment by fevangelou** [comment]
It's best to add such an HTTP header from your app, e.g. via PHP. The related header in the font files is in place for older versions of Firefox.
