### ISSUE TITLE
SSL/TLS Session Cache Status

### ISSUE THREAD

**Issue by tammyrocks** [engintron/engintron#534]
SSL/TLS Session Cache Status

i am not shore if enginetron should do this 
or its something i need fix on my server 

it seams to be enabled but its not working 

cache type: SHMCB, shared memory: 1024000 bytes, current entries: 0
subcaches: 32, indexes per subcache: 177
index usage: 0%, cache usage: 0%
total entries stored since starting: 0
total entries replaced since starting: 0
total entries expired since starting: 0
total (pre-expiry) entries scrolled out of the cache: 0
total retrieves since starting: 0 hit, 0 miss
total removes since starting: 0 hit, 0 miss

**Comment by fevangelou** [comment]
Sorry, no idea what that is. Sessions are usually controlled by the app.

**Comment by tammyrocks** [comment]
heres a few pages on nginx and  Session Cache 
https://www.bjornjohansen.no/optimizing-https-nginx
https://coderwall.com/p/qb7fua/ssl-session-caching-in-nginx
https://medium.com/@mvuksano/how-to-properly-configure-your-nginx-for-tls-564651438fe0
https://books.google.com.au/books?id=fQOLBAAAQBAJ&pg=PA486&lpg=PA486&dq=SSL/TLS+Session+Cache+Status+nginx&source=bl&ots=sGbkNVGkJ6&sig=EddrsOSZOW2JUw1dpkUa2CBna0s&hl=en&sa=X&ved=0ahUKEwj005Pkw43VAhXEVbwKHe9DDO44ChDoAQg5MAI#v=onepage&q=SSL%2FTLS%20Session%20Cache%20Status%20nginx&f=false
https://leandromoreira.com.br/2015/10/12/how-to-optimize-nginx-configuration-for-http2-tls-ssl/
lol dont know what this is but come up in google search 
https://github.com/openresty/lua-ssl-nginx-module

**Comment by tammyrocks** [comment]
any update on this 
is it something enginetron should do ?
