### ISSUE TITLE
SSL Hostname

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#536]
When you enable a new SSL (AutoSSL) new domain, it is the SSL hostname and shows how unsafe, you must restart apache and nginx every time. Any solution?

**Comment by FernandoRafs** [comment]
The same problem here! Every time a new AutoSSL is configured or renovated have to restart Nginx, and many times we have to clear the cache. It's giving a lot of work.

**Comment by abkrim** [comment]
Same for me. And use tips on this threat [ssl cert not update](https://github.com/engintron/engintron/issues/529)

On last months I deactivate 4 times engintron because there're too many issues and those issues are important for production servers.

**Comment by fevangelou** [comment]
Resolved in v1.8.4.

Also make sure to open your /etc/crontab file via the Engintron WHM app and just hit save.
