### ISSUE TITLE
Default Nginx Test page showing instead of websites (amazon linux ami whm/cpanel)

### ISSUE THREAD

**Issue by buckneri** [engintron/engintron#538]
I installed engintron and have nginx running but whenever i go to any of my sites i see the test html page.
I assume i need to tell it the root, but when i set it to the folder that houses my user folders for each site, it just throws a 404.   so then i am thinking i need to include a file that says "hey now that you are at /home/ which is the root, you need to serve up files from each of these user folders in here."??? maybe?  help!!!

Jason

**Comment by buckneri** [comment]
Solved.     i had been trying  "root /home/;"   but needed to put root /home/~;" notice the tilde.

**Comment by spirogg** [comment]
@buckneri where did you edit root /home/ to root /home/~ what file was edited to not get your error ? i get 502 error after install so not sure where to try and edit so my site works ?

thanks

**Comment by buckneri** [comment]
Hey sorry i never saw the alert that someone had commented on this. You probably already figured it out but if not its in the default config file.

I am using engintron, so i edit it from WHM/cPanel but its located at:
/etc/nginx/conf.d/default.conf

You're looking for the section that starts with:

server {

    listen 80 default_server;
    #listen [::]:80 ipv6only=on;

    server_name localhost;

Just add  "root /home/~;" or "root /var/www/~" without the quotes right after that localhost line.

**Comment by fevangelou** [comment]
@buckneri Please don't do that. Nginx will not work fine. You do not set the root path in reverse caching proxy scenarios.

**Comment by zstergios** [comment]
After upgarde to 
v1.8.8Build 20180316
(Nginx version: 1.12.2)

I have the some issue. It's the only one server that I have that issue

**Comment by fevangelou** [comment]
@zstergios Restart PHP-FPM and Apache from within WHM. Then purge Nginx's cache/temp files.

**Comment by spirogg** [comment]
From whm go to plugin and try to install - update (enginetron) bottom left inline. Should work afterwards. Please let me know. Thanks. 

Spiro

**Comment by ruy-silva** [comment]
Hi,

Have the same issue after upgrade to v1.8.8Build 20180316.

Try install - update (enginetron) and restart PHP-FPM and Apache from within WHM with no success.

I'm using CLOUDLINUX 7.4 standard with cPanel v68.0.36 and EA4.

**Comment by spirogg** [comment]
Did you Then purge Nginx's cache/temp files

**Comment by spirogg** [comment]
Also which update did you do ? There are two options in enginetron plugin. ?

**Comment by ruy-silva** [comment]
Yes I have purge cache/temps on engintron plugin. 
I have made use Update (or re-install) Engintron [Nginx stable]

**Comment by spirogg** [comment]
Try upgrsde the other one.

**Comment by spirogg** [comment]
Update reinstall. I think it says inline.

**Comment by spirogg** [comment]
I'm not at computer right now but that's the one that worked for me in cpanel when cloudlinux 7

**Comment by lukapaunovic** [comment]
I am also seeing welcome to nginx....
i removed engintron.
did upcp force
scripts rebuildhttpdconf

then installed again

purged cache

not working

**Comment by lukapaunovic** [comment]
This was some kind of bug?
it works with mainline version.

_Update (or re-install) Engintron [Nginx mainline]_

**Comment by fevangelou** [comment]
By using mainline my guess is that you are simply forcing the Nginx repo
instead of some other (EPEL perhaps?).

See the wiki for the solution (the post mentioning "welcome to fedora").
