### ISSUE TITLE
Php sessions are mixing

### ISSUE THREAD

**Issue by halit89** [engintron/engintron#539]
1 - One user logs in and creates his own session
2 - Another user logs in and creates his own session
3 - First user refreshes page and sees second users session. Its the same for all users.

We tried "session.entropy_length = 32" but did not work.

Version is PHP 7.1.

Thank you.

**Comment by gondp** [comment]
I have had the same problem in prestashop, user sessions are crossed, the solution I have used for me is to disable the caching for the domain

**Comment by lunarthegrey** [comment]
I've just seen the same issue and can confirm it's real.

Going to see if I can find any logs to prove it.

**Comment by lunarthegrey** [comment]
Found a fix. This is caused by micro caching in proxy_params_dynamic. If you change the proxy_cache_valid directive from 1s to 0s you won't have the issue anymore.

**Comment by fevangelou** [comment]
It's easier to disable micro caching in "Custom Rules". But no-one ever reads the docs, right? https://github.com/engintron/engintron/wiki

**Comment by lunarthegrey** [comment]
Shouldn't micro caching be disabled by default? It seems to serve a silly purpose and causes more confusion than anything. If several people visit a page where a user has to log in they're going to see the first person's account and it has the potential to expose details. In real-world use I'd say this is a non-feature and is quite useless.

Either way, my way of doing it or what's on the wiki does the same thing really.

**Comment by fevangelou** [comment]
@lunarthegrey that's one way to see this. A 1 sec micro-cache hardly causes issues. Worse case scenario you'll see the avatar of another user or their profile page. Hardly an issue "exposing details". And of course, you can always add exceptions for CMSs or any site that is not already supported in proxy_params_dynamic.

**Comment by lunarthegrey** [comment]
@fevangelou I've actually seen it expose the admin page of a logged in Drupal user. So yes, it could have the potential to expose details. One of the customers of the company I work for submitted a ticket. That's how it came to my attention.

**Comment by fevangelou** [comment]
What does the admin page expose exactly? The username of another user. It's difficult to add exclusions for Drupal. So just disabling it is easy. A task that takes 10 secs tops to implement. Which is far outweighed by the benefits Engintron brings to your server overall.

**Comment by lunarthegrey** [comment]
@fevangelou Potentially anything an admin user can see... Which could be sensitive.

I'm not saying to add exclusions for Drupal or any other CMS. This discussion has drawn out for a while now. I'm just glad this can be left here for any other users that may experience the odd behavior of micro caching.

**Comment by atmar** [comment]
Just found this thread after people seeing and being able to do user sensitive actions on another user's behalf, very dangerous

**Comment by gonzela2006** [comment]
I faced the same issue so I disabled the micro cache but I think this is not a better solution.

**Comment by adrianbecker013** [comment]
We are facing same issue, that is mentioned in this page
https://stackoverflow.com/questions/50969663/user-session-mixed-up-with-another-user

Anyone have proper solution for it ?

**Comment by fevangelou** [comment]
@BassemN Disabling the micro cache for a certain domain or path is much more practical.

**Comment by adrianbecker013** [comment]
@BassemN, Hmmm...thanks, but we are not using micro cache in website, can you please look into below, that we are using in our website

Actually same issue we are facing atm so

Few point related to this issue:
1. We are using Memecache to store session and PHP version is 5.3.3.
2. Traffic on our site is very nominal (not exceeded more than few hundred requests per minute) and so we dont doubt session_id() gets duplicated.
3. Our current cache control header "no-store, no-cache, must-revalidate, post-check=0, pre-check=0" is already informing client to not cache anything. So as per our understanding, it should not be anything related to cache.
4. As per our debugging, we can see that, somehow session values of User-1 is getting overwritten by the data of User-2. So it looks that, User-2 never see any problem in his account, but User-1 is able to see the account of User-2. Also, we can see that User-2 is consistently active on the service.

**Comment by fevangelou** [comment]
@adrianbecker013 I doubt that's Nginx causing this when micro-caching is off.

**Comment by adrianbecker013** [comment]
You mean that, this happen may be micro-caching is off in our Nginx Server ?, Should we test with enable micro-caching in our Nginx server?
 

Sent: Monday, April 01, 2019 at 12:11 AM
