### ISSUE TITLE
504 Gateway Timeout 

### ISSUE THREAD

**Issue by gondp** [engintron/engintron#540]
I am trying to install prestashop and I get this error, it aunmented the time but it does not work

  proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;

**Comment by fevangelou** [comment]
You need to specify "600s", not just 600. This is an invalid number and causes Nginx to switch to default values which are pretty low. Semantics.
