### ISSUE TITLE
Bad nginx performance

### ISSUE THREAD

**Issue by andreioss** [engintron/engintron#541]
Hi, I've faced with interesting problem of nginx config file reading efficiency with a lot of https vhosts.

`grep -c server_name /etc/nginx/conf.d/default_https.conf 
2645`

`# nginx -v
nginx version: nginx/1.12.0`

engintron 1.8.2

`# cat /etc/redhat-release 
CloudLinux release 7.3 (Yury Malyshev)`

`Cpanel 64`
============

`# time nginx -t

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

real    0m8.783s
user    0m7.629s
sys     0m1.141s`

> `% time     seconds  usecs/call     calls    errors syscall
> ------ ----------- ----------- --------- --------- ----------------
>  28.80    0.054977           1     55638         1 open
>  19.49    0.037212           1     55702           close
>  16.75    0.031979           1     50744           pread
>  15.26    0.029133           1     55633           fstat`

It's obvious that huge count of include statements is causing such behaviour.
And as result, when your script is doing regenerate ssl vhost config every minute and reload nginx, it's going crazy, and consume more than 20Gb RAM, as all old nginx pool processes don't have time to exit correctly.
Maybe you could come up with some fix in future version of engintron...
Thanks a lot for your work!

**Comment by fevangelou** [comment]
I doubt Nginx consumes 20GBs of RAM. Furthermore, Nginx does not regenerate its HTTPS vhosts every minute. It does that when Apache's config changes only.

**Comment by andreioss** [comment]
Okay, it doesn't matter actually about memory, original problem is in huge amount includes, that causing a lot of open/close syscalls and in its turn - slow reloading.
I think this is problem, but here we have doube-edged sword, because generate one monolithic config for https also really bad decision.
So, it can turn out, that we haven't any reasonable decision here :(

**Comment by fevangelou** [comment]
You can't do much about this but embed the includes (which makes the process tedious).

Google how GitHub faced similar issues with Nginx and GitHub pages some time ago.

BTW, how many sites are you hosting on a single server?

**Comment by andreioss** [comment]
Thanks, I'll read!
Several thousands of sites actually, it's big server, yeah ;)

**Comment by fevangelou** [comment]
Yeah, that's the issue obviously. Same was for Github's servers hosting thousands of static sites.
