### ISSUE TITLE
nginx does not work with sucuri

### ISSUE THREAD

**Issue by graz68a** [engintron/engintron#543]
Hello

I have some domain name using Sucuri. Sucuri requires to compile nginx with the --with-http_realip_module . 

https://kb.sucuri.net/cloudproxy/Troubleshooting/same-user-ip#nginx
https://www.x4b.net/kb/RealIP-Nginx

Unluckly Engintron install script does not compile from source but install nginx from repository, so I can't see how to use Engintron with nginx compiled from source with the --with-http_realip_module .

If you could change the installation module with nginx installation from source, you could provide
us possibility to add nginx modules during the installation setup.

I hope you add this in future versions, for now I needed to uninstall 
Engintron because it does not work with Sucuri .

Thank you for considering !! 
Graziano

**Comment by fevangelou** [comment]
This is out of the scope of what I want Engintron to offer. Mainly updates to Nginx when the system updates. I don't see how Sucuri can be a problem related to improving your server's performance.

And by the way, Nginx passes the correct IP to Apache. So it's not needed.
