### ISSUE TITLE
Resellers with 'All' privileges access broken

### ISSUE THREAD

**Issue by jhawkins002** [engintron/engintron#544]
Greetings - per the resolved bug at https://github.com/engintron/engintron/issues/135 resellers with the 'All' privilege set should be able to access the Engintron plugin, but that seems to not be working in the current builds. 

This has become a large issue for us, as we now have to restart apache/nginx and dump the cache every time AutoSSL generates a certificate for a new site. Resellers need to have this level of access - at least until the AutoSSL compatibility bugs are fixed in Engintron.

**Comment by fevangelou** [comment]
This is done automatically since v1.8.4. Just upgrade.

**Comment by jhawkins002** [comment]
Thanks for the update! Just tested on our current 1.8.4 build and fully privaliged reseller accounts still throw an insufficient permissions error. 

To be specific, the error we are reporting is relating to reseller access to Engintron, not the AutoSSL element used as an example use case in the OP.

**Comment by fevangelou** [comment]
Either way, the cache is flushed when changes are detected in Apache's config so I doubt you need access to it anymore.

**Comment by jhawkins002** [comment]
We certainly do! The whole point of having reseller access to high-level WHM permission sets are to allow access to WHM functionality - including plugins - without relying on root. We have encountered a number of issues when running NGINX where we have had to rely on our central, administrative root WHM login to modify Engintron functions where the issues really should have been handled by the respective reseller accounts. Previously the bug was more of an annoyance - but this was the simply the first instance where it was a full-blown production deal-breaker, so to say.   

I somewhat fear from the response this may be simply un-fixable?

**Comment by jhawkins002** [comment]
Just a quick update - We processed a service call this afternoon on 1.8.4 whereby a newly created domain had a newly generated certificate via AutoSSL but after an hour NGINX still had not detected the change. A manual Apache/NGINX restart was required, but as the reseller account who typically has access to perform these types of service calls for our org did not have access to Engintron, the issue was escalated so that the appropriate service technician with full root access could perform the quick restart.

**Comment by Simoneworks** [comment]
"Either way, the cache is flushed when changes are detected in Apache's config so I doubt you need access to it anymore."

Sorry but i am not so sure about that, for me seems that this "cache flush" does not work right.

**Comment by jhawkins002** [comment]
We also had an incident yesterday where a newly created domain did not have its certificate detected by NGINX.

We had to restart Engintron - unfortunately the support personnel who we have manage these types of service calls were unable to access the tool (we, as I am sure is the case with many other hosts, do not provide root logins to all staff). Hence the topic of this bug. 

The issue was escalated to the sysadmin level where it was dealt with (luckly) promptly.

**Comment by fevangelou** [comment]
Are you 100% your crontab syntax is not broken (for both of you)? https://github.com/engintron/engintron/wiki/SSL-certificate-changes-not-visible-in-Nginx%3F-Here's-a-possible-explanation-&-solution

**Comment by jhawkins002** [comment]
Unfortunately yes.

**Comment by fevangelou** [comment]
Closing this issue as @jhawkins002 you have submitted like 4-5 already for what is probably related to Apache and SSL only. Gather as much info as possible, close any old issues here on GitHub and post a new one with the updated info.

**Comment by jhawkins002** [comment]
Definitely understood - however I have only submitted 2 issues: this one (which only dealt with SSL tangentially, as an example use case) and the other pertinent to NGINX failing to restart. We've tried to make very sure all other discussions/contributions stay on established issue threads created by other users - so we don't duplicate.

I submitted this particular item here as support for reseller access control lists must be incorporated by plugin authors per https://documentation.cpanel.net/display/SDK/Guide+to+WHM+Plugins+-+Access+Control+Lists

I primarily work with systems support, but Ill see what we can do to possibly contribute the respective code to the project.

**Comment by fevangelou** [comment]
Seems they updated ACL checking. I'll include the code in the next update, in the coming days.

**Comment by fevangelou** [comment]
For the record, cPanel never properly provided a PHP way to "speak" to cPanel. This appears to have changed since v66 and it seems that support for PHP based cPanel plugins will only improve in the future.

**Comment by fevangelou** [comment]
Released v1.8.5 with the ACL fix. You can close the issue.

**Comment by jhawkins002** [comment]
Thank you!!

I think this item has been closed since July 15, let me know if I need to do anything more though - will be happy to.
