### ISSUE TITLE
Wrong Visitor IP (Centos7 +WHM 64.0 (build 22) + EA4

### ISSUE THREAD

**Issue by bober2000** [engintron/engintron#545]
Having the same trouble as in https://github.com/engintron/engintron/issues/411 with visitors IP. Tried reinstalling/removing - not helped.
uname -r && cat /etc/redhat-release && httpd -v && service httpd
3.10.0-327.36.3.el7.x86_64
CentOS Linux release 7.3.1611 (Core)
Server version: Apache/2.4.25 (cPanel)

httpd -M
Loaded Modules:
core_module (static)
so_module (static)
http_module (static)
mpm_event_module (shared)
cgid_module (shared)
access_compat_module (shared)
actions_module (shared)
alias_module (shared)
asis_module (shared)
auth_basic_module (shared)
authn_core_module (shared)
authn_file_module (shared)
authz_core_module (shared)
authz_groupfile_module (shared)
authz_host_module (shared)
authz_user_module (shared)
autoindex_module (shared)
deflate_module (shared)
dir_module (shared)
env_module (shared)
expires_module (shared)
filter_module (shared)
headers_module (shared)
include_module (shared)
log_config_module (shared)
logio_module (shared)
mime_module (shared)
negotiation_module (shared)
proxy_module (shared)
proxy_fcgi_module (shared)
proxy_http_module (shared)
remoteip_module (shared)
rewrite_module (shared)
setenvif_module (shared)
slotmem_shm_module (shared)
socache_dbm_module (shared)
socache_shmcb_module (shared)
status_module (shared)
unique_id_module (shared)
unixd_module (shared)
userdir_module (shared)
version_module (shared)
ssl_module (shared)
bwlimited_module (shared)
security2_module (shared)
suphp_module (shared)

mod_remoteip installed ok, Engintron v1.8.3, Nginx version: 1.12.0 script shows that everything is ok https://www.pre.4for4.com/fantasy-football/ip.php but logs are still showing servers IP. When disable Engintron - it's ok.

**Comment by Friends4U** [comment]
Verdict is: YES here... tried 10 times for you.

**Comment by bober2000** [comment]
Verdict is: YES but Apache logs shows server IP. Also CMS Drupal think that all users are using server IP so I have to truncate flood table often

**Comment by weservit-raoul** [comment]
Having the same problem here. Reinstalled a couple times. Restored the default cpanel vhost templates. When I disable Engintron the domlogs show the right IP address.

2.6.32-673.26.1.lve1.4.27.el6.x86_64
CloudLinux Server release 6.9 (Igor Volk)
Server version: Apache/2.4.25 (cPanel)
Server built:   Apr 14 2017 12:43:32


Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 mpm_prefork_module (shared)
 cgi_module (shared)
 access_compat_module (shared)
 actions_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 include_module (shared)
 log_config_module (shared)
 logio_module (shared)
 mime_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 proxy_http_module (shared)
 remoteip_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_dbm_module (shared)
 socache_shmcb_module (shared)
 status_module (shared)
 suexec_module (shared)
 unique_id_module (shared)
 unixd_module (shared)
 userdir_module (shared)
 ssl_module (shared)
 bwlimited_module (shared)
 fcgid_module (shared)
 security2_module (shared)
 hostinglimits_module (shared)

**Comment by bober2000** [comment]
I'm ready to provide any necessary information to resolve this issue

**Comment by kvillios** [comment]
I have the same problem on our servers with visitors IP. 
All server are cPanel, Cloudlinux 7.3, Engintron 1.8.3, Nginx version: 1.12.0.

Tried reinstalling but not helped.

3.10.0-427.36.1.lve1.4.40.el7.x86_64
CloudLinux release 7.3 (Yury Malyshev)
Server version: Apache/2.4.25 (cPanel)

Loaded Modules:
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 mpm_worker_module (shared)
 cgid_module (shared)
 access_compat_module (shared)
 actions_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 expires_module (shared)
 filter_module (shared)
 headers_module (shared)
 include_module (shared)
 log_config_module (shared)
 logio_module (shared)
 mime_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_fcgi_module (shared)
 proxy_http_module (shared)
 remoteip_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_dbm_module (shared)
 socache_shmcb_module (shared)
 status_module (shared)
 suexec_module (shared)
 unique_id_module (shared)
 unixd_module (shared)
 userdir_module (shared)
 ssl_module (shared)
 bwlimited_module (shared)
 security2_module (shared)
 passenger_module (shared)
 lsapi_module (shared)
 hostinglimits_module (shared)
 proctitle_module (shared)

How can solve this issue guys? Any other ideas?

**Comment by fevangelou** [comment]
Upgrade to v1.8.4.

**Comment by bober2000** [comment]
Upgraded already but still no luck.
Nginx access log show right IP but apache is no.
RemoteIP module is loaded through /etc/apache2/conf.modules.d/360_mod_remoteip.conf

LoadModule remoteip_module modules/mod_remoteip.so
RemoteIPHeader        X-Forwarded-For
RemoteIPInternalProxy 127.0.0.1 50.28.52.98

My LogFormat after install:

<IfModule mod_log_config.c>
    LogFormat "%v:%p %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combinedvhost
    <IfModule logio_module>
        LogFormat "%v %{%s}t %I .\n%v %{%s}t %O ." bytesvhost
    </IfModule>
    LogFormat "%v:%p %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%v:%p %h %l %u %t \"%r\" %>s %b" common
    LogFormat "%{Referer}i -> %U" referer
    LogFormat "%{User-agent}i" agent

            
            <IfModule logio_module>

**Comment by fevangelou** [comment]
Did you just upgrade to 1.8.4?

**Comment by bober2000** [comment]
Yes

**Comment by fevangelou** [comment]
Then you'll need to wait at least a day for the logs to rotate. I assume you're watching them via AWStats or something like that. Come back in a couple of days and let me know.

**Comment by bober2000** [comment]
I'm watching domain log under SSH
Nginx access log shows me right IP: 46.39.83.92 - - [15/Jul/2017:17:02:38 -0400] "GET / HTTP/1.1" 200 12945
Apache access log show me IP of my server: 50.28.52.98 - - [15/Jul/2017:17:02:38 -0400] "GET / HTTP/1.1" 200 66071

**Comment by fevangelou** [comment]
Click on "Restore Nginx IP forwarding in Apache" in the Engintron WHM app, delete Nginx cache/temp files & all access/error logs, then check again.

**Comment by bober2000** [comment]
"Restore Nginx IP forwarding in Apache" log https://pastebin.com/BJRPNqif
Purge access & error log files log https://pastebin.com/L44p0Sdf
Delete cache/temp log https://pastebin.com/darfFUFf

Situation is the same 46.39.83.92 - - [15/Jul/2017:17:10:57 -0400] "GET / HTTP/1.1" 200 22701  in NGINX Access log where 46.39.83.92  is my IP
50.28.52.98 - - [15/Jul/2017:17:10:57 -0400] "GET / HTTP/1.1" 200 161587 in Apache access log where 50.28.52.98 is server IP

**Comment by fevangelou** [comment]
What's the output of this?

`grep "LogFormat \"%a %l" /etc/apache2/conf/httpd.conf`

**Comment by bober2000** [comment]
Empty output

**Comment by fevangelou** [comment]
This means that your httpd.conf file is not properly modifed so Apache can parse the traffic data Nginx passes to it.

I recommend you rebuild your Apache config - just go to the global settings in WHM and hit save.

Then uninstall and re-install Engintron.

Let me know.

**Comment by kvillios** [comment]
Hello guys,

I try to "Restore Nginx IP forwarding in Apache" in the Engintron WHM app, delete Nginx cache/temp files & all access/error logs" and now I take the RIGHT ip!

In addition on # grep "LogFormat \"%a %l" /etc/apache2/conf/httpd.conf I take the following output:
    LogFormat "%a %l %u %t \"%r\" %>s %b" common
    LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined

So all it's ok on my machine.

Thanks @fevangelou for the solution and for the excellent job.
Kostas

**Comment by fevangelou** [comment]
You're welcome @kvillios :)

**Comment by bober2000** [comment]
Regenerated config at Home »Service Configuration »Apache Configuration »Global Configuration in WHM.
Reinstalled Engintron - still the same.

**Comment by fevangelou** [comment]
@bober2000 Something has changed your LogFormat directive in httpd.conf and obviously Engintron cannot find the default pattern so it can replace it. From what you pasted above, your LogFormat directives start with `LogFormat "%v:%p %h %l`. If you did not do this, perhaps you might want to consult with the person who setup your server. Otherwise just replace any such entry with `LogFormat "%a %l`

**Comment by bober2000** [comment]
The problem is that in template /var/cpanel/templates/apache2_4/ea4_main.default LogFormat is:

**Comment by fevangelou** [comment]
Change it there.

**Comment by bober2000** [comment]
@fevangelou changed - all seems to be working but I maybe we have to check this stuff in installer or add this info to wiki

**Comment by fevangelou** [comment]
If this was default behaviour, the testing servers I have would not work. :)
