### ISSUE TITLE
Engintron 502 error after fresh install

### ISSUE THREAD

**Issue by ramjke** [engintron/engintron#546]
1. Just installed centos 6.9 and the latest fresh WHM (DNS server disabled).
2. Created a new Cpanel account website.test. I checked that the site is open on http://website.test.
3. Installed Engintron with no errors.
4. Now http://website.test returns 502 Bad gateway. http://website.test:8080 works.
I need to configure the config after installation?

**Comment by OleksaBaida** [comment]
The same issue here. How to rebuild  Nginx virtualHosts, after adding a new cPanel account?

**Comment by jcmdln** [comment]
I've detailed this in issue #563, basically you will either have to add the domain + IP to your `proxy_params` or actually have some sort of nameservers for the new cPanel account to register DNS changes against.

**Comment by fevangelou** [comment]
@ramjke If "website.test" is non existent, Nginx will not be able to resolve it.
@jcmdln You don't need to modify core files. There is "custom rules" where you can set your server's IP. See the Engintron Wiki for more or just read the comment in that file thought the Engintron WHM app.

**Comment by jcmdln** [comment]
@fevangelou Sure, I could manage a set of custom rules, proxy_params, and etc but for anyone who has more than a few IP's and a handful of customers, that's quite a bit of additional work compared to the option that I've suggested.

**Comment by fevangelou** [comment]
@jcmdln I don't see how the Google resolvers is a problem. Unless you're blocking them. The fix I mention is uber-simple and applies to all domains, you don't need to map all domains to the same IP. Read the custom rules file examples.
