### ISSUE TITLE
Clarify docs + Question

### ISSUE THREAD

**Issue by ihadeed** [engintron/engintron#549]
Hey there,

Awesome work! Thanks for your efforts.

I just have a quick comment about the docs, I feel like part of it is a bit confusing.

In your README.md, last part. The sixth point you talk about using Flexible SSL on CloudFlare.

> If additionally you use CloudFlare's SSL, by choosing "Flexible SSL" in CloudFlare's "Crypt" settings you can direct CloudFlare HTTPS traffic to your cPanel's HTTP port served by Nginx, thus further improving web serving over HTTPS as well. A true win-win situation.

Then in the eighth point you say that the library now supports HTTPS.

> Eighth, Engintron allows for both HTTP and HTTPS traffic to flow through Nginx entirely, as of version 1.8.0.

I'm assuming that we can now use Full or Full (strict) SSL with CloudFlare and it should still work. Correct?

Also, does this app/plugin have any known side effects? I plan to use AutoSSL (Comodo or Let's Encrypt) to automatically issue SSLs to each domain on the server. Will I have any issues or will everything work fine?

**Comment by fevangelou** [comment]
You can use Engintron either way. In the first case, you just don't need to deal with certificates on your server.

If there were issues, it wouldn't support HTTPS in cPanel, so there would not be point 8.

**Comment by ihadeed** [comment]
Thanks for the clarification!

**Comment by fretelweb** [comment]
Sorry for put my question here but I already install engintron in my cpanel web server and I like it, but I have some issue with the SSL certificates.
Whe I let wngintron handle the port 443 and reditect to 8443 httpd the browser show me a warning about the certificate but when I let httpd handle the port all my domain works well.

I use let's crypt for the ssl keys.

Thanks
