### ISSUE TITLE
fresh install SSL error

### ISSUE THREAD

**Issue by theoxgr** [engintron/engintron#550]
i have an error in a fresh install vps server. please help. thank you in advance

Checking Nginx configuration...
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/cpanel/ssl/installed/keys/f1e68_37747_21dc496a74f6e1f81d698ce2adff2647.key") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/installed/keys/f1e68_37747_21dc496a74f6e1f81d698ce2adff2647.key','r') error:20074002:BIO routines:FILE_CTRL:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by lupetalo** [comment]
@theoxgr go to /etc/nginx/conf.d/default_https.conf and delete rule with f1e68_37747_21dc496a74f6e1f81d698ce2adff2647
do a string search.

**Comment by theoxgr** [comment]
@lupetalo ok i have removed it. there was 4 lines inside and i deleted them.
but now i get another error:

Checking Nginx configuration...
nginx: [emerg] no "ssl_certificate_key" is defined for certificate "/etc/ssl/engintron/sissicore_ch_f1e68_37747_1499754660_59a0f729413d8b532b6689bb8fb6d684.crt"
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by lupetalo** [comment]
delete whole rule block. Watch syntax...

**Comment by theoxgr** [comment]
@lupetalo i remove one block. then another ssl block with different key gives error. there is error with all keys. and there are 2 ssl keys in each block

**Comment by lupetalo** [comment]
You can remove all and reinstall engintron... I do not have a better solution for you, sorry. Removing one block helped me...

**Comment by fevangelou** [comment]
Open up /etc/crontab via the Engintron WHM app and just hit save. Purge Nginx's cache and temp files and check again. Let me know.
