### ISSUE TITLE
cPanel AutoSSL not working in safari browser in mac and iphone with Engintron

### ISSUE THREAD

**Issue by ribo72** [engintron/engintron#551]
Hello, i use cPanel AutoSSL for some websites and the latest version of plugin engintron.  In safari 10.1 as they reported me the ssl not work and it shows "Safari Can't Open the Page". When i disable Engintron the site with ssl of cpanel works in safari.

**Comment by BionicClick** [comment]
is this still an issue with the latest release?

**Comment by ribo72** [comment]
Yes

**Comment by fevangelou** [comment]
I think the issue relates to Comodo certificates. Switch to LetsEncrypt and should be fine.

More info here: https://github.com/engintron/engintron/wiki/SSL-certificate-considerations-with-cPanel's-AutoSSL

**Comment by ribo72** [comment]
And let say that someone don t want to use LetsEncrypt( for example if any user have windows xp and google chrome which is not update it with xp then LetsEncrypt gives error with certificate) and wants to use Comodo with apache in 443 hos no problem in safari loading but with engintron and nginx have. So i think that it is better if we can find exactly what is the reason for this.

**Comment by fevangelou** [comment]
Why not ask Comodo then?

**Comment by ribo72** [comment]
Because comodo with cpanel and apache works fine in safari. The same ask will be and from comodo

**Comment by fevangelou** [comment]
You should ask them why concatenating their certificates in Nginx must be
in reverse order than those from LE or other certificate authorities.

Cause that's the issue.

**Comment by denialhost** [comment]
we try changing to let´s encrypt and nothing same error... :(

**Comment by botonakis** [comment]
The same error here.

**Comment by markimark8** [comment]
With a attitude like this guys, this issue will never get resolved and thousands of users will look to blame engintron

**Comment by fevangelou** [comment]
Comodo makes money. Engintron is free and open source. Connect the dots.

And you know what? I'd prefer supporting LetsEncrypt than Comodo. So integrate L/E into cPanel and be done with it.

Wanna support really old browsers and L/E is too modern for you? Add freakin' CloudFlare for such sites.

There are always alternatives.
