### ISSUE TITLE
HTTP/2 Support with CloudLinux Alt PHP?

### ISSUE THREAD

**Issue by wppronto** [engintron/engintron#552]
Hi,

We're still looking for a way to implement HTTP/2 support, which Engintron 1.8 supports but (as discussed in other threads) it doesn''t work 100% because of the OpenSSL issue.

CloudLinux has released a beta of their alt-php that does support HTTP/2 by integrating the needed version of OpenSSL.

https://www.cloudlinux.com/cloudlinux-os-blog/entry/beta-alt-php-with-http-2-support-released

Before we test it, we're wondering if this would play nice with Engintron, or if the Engintron proxy would preclude the HTTP/2 support from the PHP version?

Thanks,

Mark

**Comment by fevangelou** [comment]
OpenSSL must be updated server wide so Nginx can use it. Unfortunately, it is my understanding that OpenSSL is such an integral part of the OS and common apps and/or libraries, that a proper solution is for CentOS to finally update it or cPanel jump in-between and do it for CentOS.

I believe the cPanel folks are well aware of this issue and will try to find a final solution sooner or later as it's also preventing Apache from utilising HTTP/2.

**Comment by Nirjonadda** [comment]
@fevangelou Just wanted to share here that the upcoming release of RHEL 7.4 comes with OpenSSL 1.0.2k. Obviously it will take a few weeks for CentOS 7.4

More information and the beta release notes: [https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7-Beta/html/7.4_Release_Notes/index.html](url)

**Comment by ribo72** [comment]
When you use http2 for apache with pre release, it wirks with apache https://features.cpanel.net/topic/htt2-support . My question is why this don t work with engintron and nginx?

**Comment by fevangelou** [comment]
If the OpenSSL is bundled with the system, then HTTP/2 will work for Engintron. Of you course, after you upgrade your system, you need to re-install Nginx via Engintron (=update).
