### ISSUE TITLE
SSL + CloudFlare CDN issues

### ISSUE THREAD

**Issue by ihadeed** [engintron/engintron#554]
Just installed Enginron on a server with CentOS 7 and latest WHM. All sites have AutoSSL enabled and they have valid certificates. 

The websites that are configured to use CloudFlare stopped working (unless if I disable the CDN option on CloudFlare and use the DNS-only option). All other sites that do not use CloudFlare work fine. 

Is there any additional configuration that I have to do if my websites use CloudFlare CDN?

**Comment by Quazz** [comment]
Yes, on the engintron panel, you have to edit your custom_rules for Nginx, instructions are included in the file

**Comment by ihadeed** [comment]
Thanks @Quazz
