### ISSUE TITLE
Wordpress homepage not work

### ISSUE THREAD

**Issue by lucatocco** [engintron/engintron#555]
Hi,
I have installed engintron on Centos 7.3 and Cpanel 64.0.24.
When try to open website homepage it show "nginx welcome page"
If open internal page it works. I have tried all possible solutions.
https://www.sos-server.it/
https://www.sos-server.it/features/
Thanks

**Comment by lucatocco** [comment]
resolved, some file of previous nginxcp make this error. Removed and now work.

**Comment by fevangelou** [comment]
This was referenced in the Engintron Wiki already. I hope you had a look :)

**Comment by SatishGandham** [comment]
@lucatocco , Can you please tell which files.
