### ISSUE TITLE
SSL Requires Restart - No Cron

### ISSUE THREAD

**Issue by brixly** [engintron/engintron#556]
Hi there, would really appreciate your help on this one as it causes us a huge amount of support enquiries.

We use LetsEncrypt as a plugin for cPanel, as well as AutoSSL. When a certificate is installed, the site doesn't go secure until we have restarted using the 'Restart Apache & Nginx' option within Engintron.

Under the 'cron' section of Engintron, I can see this...

* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1

However, im not too sure this is even running. Is there any way we would be able to tell?

I can see within the https_vhosts.sh file, it runds service nginx reload following the regeneration.

Is service nginx reload enough to get the SSL working? We have tried this in the past, but the site still shows as insecure until we restart both Apache and Nginx.

We obviously don't want to alter the code to restart nginx and apache entirely through a cron, incase of syntax errors etc.

Could you just clarify where we are going wrong please?

**Comment by brixly** [comment]
Ok, so I can verify from the logs the script appears to be running through the cron...

Jun  8 15:07:01 cloud07 CROND[406963]: (root) CMD (/etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1)
Jun  8 15:08:01 cloud07 CROND[408380]: (root) CMD (/etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1)

If that is the case, why are the sites not secure until we restart Apache and Nginx entirely?

Many thanks,

Dennis

**Comment by Mike981874** [comment]
Same here. I created a cron to restart apache and nginx once a day, but when it ran Nginx didn't start and gives a 'No such file or directory' error for one of the ssl files in /var/cpanel/ssl/installed/keys/, so I would recommend against doing cron restarts. I had to disable Engintron for now.

**Comment by imagina** [comment]
Ok, in my case i found the problem.

It was ngintron cron requiring to read files outside of /home and we were limiting that option in php.ini with open_basedir

Remove open_basedir restriction in your main php.ini file and it should run fine.

**Comment by omikron** [comment]
We do not limit anything with open_basedir, and we have the same problem.

Even when adding a new domain and having AutoSSL generate a new SSL, Nginx has to be restarted for the certificate to take effect.

**Comment by fevangelou** [comment]
Open /etc/crontab via the Engintron WHM app and just hit save. It's important to do this through the Engintron WHM app as a previous version of the code editor used would break line endings in that file and cause custom cron jobs to break, thus refreshing the Nginx config for HTTPS would not work.

**Comment by brixly** [comment]
I have continued the thread here...

https://github.com/engintron/engintron/issues/662#issuecomment-343190324

**Comment by lukapaunovic** [comment]
This is finally how I fixed this.
I looked when my autossl cron is running

`cat /etc/cron.d/cpanel_autossl`

Mine runs at 

`26	4	*	*	*	root	/usr/local/cpanel/bin/autossl_check --all`

So I added this to run hour later.

`30 5 * * * /usr/sbin/service nginx restart > /dev/null 2>&1`

This works beautifully.
