### ISSUE TITLE
Content-type application/json

### ISSUE THREAD

**Issue by optimanrr** [engintron/engintron#557]
Hello,
I am trying to find out how to change response header content type from text/html to application/json, can you please help me with any advice?

The Request Method is Get, content-encoding is gzip, here are more details:

HTTP/1.1 200 OK
Server: nginx
Date: Fri, 09 Jun 2017 08:18:19 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Pingback: http://www.domainname.tld/xmlrpc.php
Set-Cookie: PHPSESSID=vhf65087bmblrkcr2iuge051e3; path=/
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: Engintron

I have tried adding the charset in nginx.conf, but this doesn't seems to change the result.

Thank you in advance!

**Comment by BionicClick** [comment]
leaving this open without an answer for 18 days is making me rethink installing this product? last updates were 19 hours ago..

**Comment by fevangelou** [comment]
@optimanrr this is out of the scope of what Engintron is and does, sorry. If the response should be json but it's not, it's probably broken at source (by some WP plugin). PHP can send any HTTP headers you like. It's not an Nginx problem to deal with.

@BionicClick Engintron is open source. I answer in batches as you'll notice from time to time. I can't be answering questions daily. Not at the moment at least. I do have plans on offering commercial support though (and hire additional folks to help out).
