### ISSUE TITLE
Custom rule for one domain?

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#558]
Hi,

For a WordPress site of one of my customers I need to make a custom rule:

```
If you are using NginX, you probably need such a bit of code in your configuration file:
location / {
rewrite \.(?:jpe?g|gif|png)$ /wp-content/plugins/adaptive-images/adaptive-images-script.php;
}
```

How would I go about this?

**Comment by Friends4U** [comment]
For example, I would like to use a nginx_app.conf at the root of my httpdocs.

**Comment by Friends4U** [comment]
@fevangelou , can you tell me :)

**Comment by fevangelou** [comment]
This won't work. What this does it that it passes all static files of image type to a PHP script which I assume performs image optimizations.

Engintron's Nginx is not configured to do this. Additionally, calling the PHP engine for every image file is a bad-bad-bad idea. Consider using a plugin that periodically scans your WP images and optimizes them on site so they can be served directly to the browser.

**Comment by Friends4U** [comment]
That's to bad :) Tnx anyway!
