### ISSUE TITLE
Nginx dynamic image resizing...

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#559]
On the following site is an example to use dynamic image resizing with Nginx.
Is this possible with Enintron too?

https://stumbles.id.au/nginx-dynamic-image-resizing-with-caching.html

I think it would be great (for WordPress sites) if this could be done... So we can serve scaled images.

**Comment by Friends4U** [comment]
Another post about it... but I think the first one is best because the size is retrieved from the site and not precoded. However, the rate limiting from the second post is also important.

**Comment by fevangelou** [comment]
Requires a third-party module which does not come from the official repos. So, it's a no-go for now. But I'll keep an eye on it.

The best thing you can do is install mod_pagespeed on Apache which can optimize the images among other things.

See the sourcecode in thieme dot com to get an idea of what the page output will be. In a similar case, I installed mod_pagespeed in Apache and traffic was being proxied to Apache via Varnish. Same thing can happen with Nginx as well.

**Comment by Friends4U** [comment]
But it's in NGINX or am I reading this wrong (the second post is about plus, yes, but the first link I shared isn't)?

"The Nginx web server comes with a handy image filter module, but most tutorials don't configure it with performance in mind. Performance means caching."

http://nginx.org/en/docs/http/ngx_http_image_filter_module.html#image_filter

I think it would be a great addition to Engintron, most host server WordPress and alike, this would greatly improve site speeds on GTMetrix. Hell... I would gladly pay something for an Engintron "Plus"  :)

**Comment by Friends4U** [comment]
I've installed page speed and it's running... but it does not really looks like doing anything (in the headers I can see it's running). From the pagespeed manual: https://modpagespeed.com/doc/configuration I need to add something to nginx.conf, but I really don't know how, because when I add the lines I get an error on testing the config.

**Comment by fevangelou** [comment]
Yes, mod_pagespeed will require additional configuration. `nginx -t` will let you know where the error comes up. It's probably syntax related.

**Comment by Friends4U** [comment]
I did nothing but it looks like its working now... or MUST I change something in nginx?
