### ISSUE TITLE
View Real IP from Visitor

### ISSUE THREAD

**Issue by rapidcloubr** [engintron/engintron#562]
Hello,

I do not know if there is a solution to this problem, I researched and did not find it.

My clients need real IP to be displayed instead of server IP. Can you adjust?

Thanks.

**Comment by fevangelou** [comment]
It's already done in v1.8.4 for AWStats. It was always done the right way, but AWStats was just not able to properly pick up the right IP.

**Comment by edibarboza** [comment]
I have the same problem and the problem is in Engintron. When Engintron came up it already had Awstats. So, it's not Awstats's fault, because it already works perfectly in Apache.

Engintron is very good, but its developers need to be humble, to take over and correct this problem

**Comment by erojiraiya** [comment]
Here is the solution.
https://www.damchey.com/2018/01/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel/

Try it.
