### ISSUE TITLE
[Wiki] Clarify on 'DNS Resolver' behavior

### ISSUE THREAD

**Issue by jcmdln** [engintron/engintron#563]
Something that I believe should be clarified is that since many users of Engintron will already have their own nameservers, they may configure their DNS resolver to use the nameserver that their VPS is registered against. This is highly recommended for those that may be hosting their DNS directly from their VPS or through paid offerings, and removes the need to rely on the resolver making that additional check at the specified external nameservers.

```
...

## DNS Resolver ##
resolver                       ns1.myvpsnameserver.com ns2.myvpsnameserver.com;

...
````

I hope I have outlined this well, though please let me know if I should clarify on this change and it's behavior

**Comment by BionicClick** [comment]
what if you have multiple cPanel accounts and every single domain uses custom name servers and the DNS is served on the cpanel server itself, and the domains are registered at google?

**Comment by jcmdln** [comment]
@BionicClick 
    what if you have multiple cPanel accounts and every single domain uses custom name servers and the DNS is served on the cpanel server itself, and the domains are registered at google?

This isn't about external DNS resolution, it's about utilizing internal DNS resolution to prevent 502 errors. It makes no difference which nameservers are associated with a domain because that's simply pointing the domain to the IP address associated with your server. The issue is that Engintron is configured to call out to the nameservers specified in the resolver, and if it hasn't propagated then it will not resolve until it does.

The initial DNS records are added by cPanel when creating an account, and if configured to do so, it will sync those changes to Bind or whichever nameserver software you're running. By there already being a set of nameservers that are registering the internal IP a domain points to, the DNS lookup is being handled locally, and bypassing propagation. This prevents the 502 errors which are seen when a domain isn't propagated yet, or you're using a hosts file mod to test a site you're migrating without having to perform an internal forward of the domain+IP as what is currently specified in the documentation.

If you aren't running ANY nameservers whatsoever, then this change would not work. Only when you have nameservers that are actively syncing changes will you be able to utilize what I've described. You can even take it a step further and provide a list of nameservers you want it to try, but the idea is that this relies on a local lookup which means that this is a very hands-off process to manage.


Let's try a few real-world examples. I'll reinstall Engintron so that it is a fresh install, but the server configuration is not important here. The idea is that if I have local nameservers or a paid nameserver service, it should register DNS changes in cPanel quickly.

1) I want to try a fresh WordPress installation in a new cPanel user. Let's say the domain is `fdsafdsafdsa.com`. If I create the account and perform a hosts file modification to the correct IP address, it will show a `502 Bad Gateway` error because by default the resolver is looking for the correct DNS record within Google's nameservers. If this is a real domain, I can wait for it to propagate to the nameservers specified in the resolver line. If this is not a real domain, it will never resolve. If I simply replace the resolver line to the nameservers that my cPanel is registering DNS changes to, then the domain will resolve whether the domain is real or not. immediately after making this change to the resolver, the domain will function over a hosts file mod. If you switch back to using the default Google DNS resolver line and restart Nginx, you will see the 502 error again.

2) I have a cPanel VPS that has Bind running, and I have a domain through Google Domains. Without modification to Engintron, when I create the cPanel account and point that domain to the cPanel server I will see 502 errors if I perform a hosts file modification. You may either wait for the domain to propagate, or you may adjust your resolver line to point to the nameservers your DNS changes are being registered against and the site will now load.


The key takeaway here is that Engintron can NOT do this any more automagically than it does already. There could be some assumptions that you are running a local nameserver, but for many admins who may be running a fleet that is associated with a set of nameservers this completely solves the 502 errors without further intervention. Again, if you don't want to or refuse to link cPanel with any nameservers then you're best option is to perform the domain+IP proxy rule as the documentation states, but this is PAINFUL when you have more than a handful of customers who have domains, subdomains, addon domains, parked domains, sites they want to test on your services before migrating, etc.


I hope I outlined this well, as this is a very important tweak for those who manage large clusters or don't want to manually intervene every time a customer is adding some type of domain or new site. Feel free to ask me more about this if needed.

**Comment by fevangelou** [comment]
@jcmdln I think you can write up your own Wiki article here https://github.com/engintron/engintron/wiki - I'll have a look then and if all is OK, I'll publish it. If you can't see a way to add a new article in the wiki, let me know.
