### ISSUE TITLE
Apache http/2

### ISSUE THREAD

**Issue by lafrance** [engintron/engintron#564]
Hello!

WHM as release in v X.66 HTTP/2 However if I turn it on on EA4 all site will not load via safari all others browser work. " All Sites are https"

Is this a bug in gninx or ?

If I turn NGINX off it will work on all browser

**Comment by BionicClick** [comment]
Oh my goodness, this is stopping me right in my tracks. i cannot install enginetron unless http2 works flawlessly.

**Comment by BionicClick** [comment]
@lafrance - how did you even get x.66 cPanel version? as x.65 is in edge, not .66.

please elaborate.

**Comment by lafrance** [comment]
BionicClick  oops click on wrong key it is X.64

**Comment by ribo72** [comment]
Did you tested it with engintron 1.8.4?

**Comment by lafrance** [comment]
Yes still no joy

**Comment by fevangelou** [comment]
When you do what you do, Apache is probably trying to switch back to port 80. That's why hell breaks loose. Nginx has no issue proxying traffic to Apache, even if it worked on HTTP/2030.

**Comment by lafrance** [comment]
Hello!

Just check after changing too http/2 port did not change still the same and still get 502 error or page will just hang and not load

**Comment by fevangelou** [comment]
Increase the 3 timeout values defined in proxy_params_common (https://github.com/engintron/engintron/blob/master/nginx/proxy_params_common#L33) to "300s". Purge Nginx's cache/temp files and check again.

**Comment by lafrance** [comment]
HHello!

Did as you said and purge 3 time cache and sites still will not load

**Comment by fevangelou** [comment]
@lafrance I'm sure it's something else you probably changed that causes this behaviour. Unless you provide me with more info, I can't possible know. You can start with the Nginx access and error log files from within Engintron. Use the option to clean these files, the restart Apache and Nginx. Visit a couple of sites and then check the logs generated (both access and error). Paste them back here.

**Comment by lafrance** [comment]
Hello!

You are right it is Safri as it will load no problem with others browsers

**Comment by fevangelou** [comment]
Perhaps then the issue is related to this: https://github.com/engintron/engintron/wiki/SSL-certificate-considerations-with-cPanel's-AutoSSL

**Comment by lafrance** [comment]
Is there a way to pm you the logs?

**Comment by fevangelou** [comment]
Use engintron at gmail dot com.

**Comment by lafrance** [comment]
Right brain freeze here should of known that send

**Comment by RedDot-3ND7355** [comment]
Guys, did you tried 66?

**Comment by VDPloeg** [comment]
I'm having the same issue. Standard install of Engintron, with the Cloudflare [change](https://github.com/engintron/engintron/wiki/Engintron-&-CloudFlare). WHM 64, Engintron 1.8.4. My sites load fine everywhere except IOS. Purged my logs and have no errors but here's my access log.

64.231.19.52 - - [26/Jul/2017:11:48:21 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:22 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:22 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:22 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:22 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:22 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:22 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:22 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:23 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:23 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:23 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:23 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:24 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:24 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:24 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:24 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:25 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:25 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:25 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:25 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:25 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:25 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:26 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:26 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:26 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:26 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:26 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:26 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:26 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:26 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:27 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:27 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:28 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:28 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:28 -0400] "GET / HTTP/2.0" 200 8602 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
64.231.19.52 - - [26/Jul/2017:11:48:29 -0400] "GET / HTTP/2.0" 200 0 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/60.0.3112.72 Mobile/14F89 Safari/602.1"
180.76.15.149 - - [26/Jul/2017:11:48:40 -0400] "GET /lazarus-vol-1-family/ HTTP/1.1" 301 0 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
180.76.15.155 - - [26/Jul/2017:11:48:41 -0400] "GET /lazarus-vol-1-family/ HTTP/1.1" 200 9880 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)"
107.150.28.16 - - [26/Jul/2017:11:48:49 -0400] "POST /wp-cron.php?doing_wp_cron=1501084129.2177839279174804687500 HTTP/1.1" 200 0 "https://ebabble.net/wp-cron.php?doing_wp_cron=1501084129.2177839279174804687500" "WordPress/4.8; https://ebabble.net"
64.231.19.52 - - [26/Jul/2017:11:48:49 -0400] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 78 "https://ebabble.net/wp-admin/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
107.150.28.16 - - [26/Jul/2017:11:48:53 -0400] "POST /wp-cron.php?doing_wp_cron=1501084133.1761040687561035156250 HTTP/1.1" 200 0 "https://aeindex.org/wp-cron.php?doing_wp_cron=1501084133.1761040687561035156250" "WordPress/4.8; https://aeindex.org"
64.231.19.52 - - [26/Jul/2017:11:48:54 -0400] "GET /wp-admin/admin-ajax.php?action=blc_dashboard_status&random=0.11845348398383049 HTTP/1.1" 200 294 "https://aeindex.org/wp-admin/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
66.249.79.40 - - [26/Jul/2017:11:49:09 -0400] "GET /previews/fantagraphics-studio-editions-hal-fosters-prince-valiant-charles-burns-black-hole/ HTTP/1.1" 200 13977 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.87 - - [26/Jul/2017:11:49:16 -0400] "GET /fan-expo-2010-day-one-art-and-hardcovers/?relatedposts=1 HTTP/1.1" 301 0 "http://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.87 - - [26/Jul/2017:11:49:16 -0400] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 0 "http://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.87 - - [26/Jul/2017:11:49:17 -0400] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 0 "http://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.85 - - [26/Jul/2017:11:49:18 -0400] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 0 "http://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.51 - - [26/Jul/2017:11:49:18 -0400] "GET /fan-expo-2010-day-one-art-and-hardcovers/?relatedposts=1 HTTP/1.1" 200 9656 "http://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.48 - - [26/Jul/2017:11:49:20 -0400] "OPTIONS /fan-expo-2010-day-one-art-and-hardcovers/?relatedposts=1 HTTP/1.1" 200 9657 "http://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.84 - - [26/Jul/2017:11:49:31 -0400] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 0 "https://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.86 - - [26/Jul/2017:11:49:31 -0400] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 0 "https://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.86 - - [26/Jul/2017:11:49:32 -0400] "GET /fan-expo-2010-day-one-art-and-hardcovers/?relatedposts=1 HTTP/1.1" 301 0 "https://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.86 - - [26/Jul/2017:11:49:32 -0400] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 0 "https://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.49 - - [26/Jul/2017:11:49:33 -0400] "GET /fan-expo-2010-day-one-art-and-hardcovers/?relatedposts=1 HTTP/1.1" 200 9647 "https://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.79.49 - - [26/Jul/2017:11:49:35 -0400] "OPTIONS /fan-expo-2010-day-one-art-and-hardcovers/?relatedposts=1 HTTP/1.1" 200 9648 "https://www.ebabble.net/fan-expo-2010-day-one-art-and-hardcovers/" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

**Comment by noesisconsultancy** [comment]
Same here, works on one server, and on another it breaks on iOS

**Comment by lmfreitas** [comment]
I think it is related with HTTP2 from EA4 and Nginx.
Maybe Nginx Config from Engitron?
It returns, at least to my case a blank page, disable engitron and returns to normal.

I happens only on IOS, Macs browser.

Has any one has, HTTP2 from EA4 and Engitron on a Mac working?

Thanks

**Comment by philsward** [comment]
For those of you with the Safari problem, are you on CentOS6 or 7?

**Comment by ribo72** [comment]
Centos 6

**Comment by lmfreitas** [comment]
CENTOS 6.9

**Comment by philsward** [comment]
Thanks @ribo72 & @lmfreitas 

I'm also experiencing this problem on a bone-stock install of engintron, so the idea that "I changed something to cause it" can't be valid.

Do a google search for "[nginx safari problem](https://www.google.com/search?q=nginx+safari+problem&oq=nginx+safari+problem)" and you will find others with the same problem.  I don't have a mac system to test against safari and since browsershots.org is painfully slow, it's difficult for me to troubleshoot further.

For those of us on CentOS6, HTTP/2 has "nothing" to do with it because engintron isn't compiling against a version of openssl that will serve http2 pages through the protocol that all "modern" browsers recognize (APLN).  Unless engintron is installing nginx in such a way that it truly believes it's supposed to be serving http2 and since it isn't, it's getting confused when falling back to http1, I highly doubt this issue is a direct result of http2.

See issue: https://github.com/engintron/engintron/issues/648 for a better understanding of why nginx on CentOS6 isn't serving http2
