### ISSUE TITLE
 502 Bad Gateway with engintrom & Let's Encrypt cPanel plugin.

### ISSUE THREAD

**Issue by robertmonroe** [engintron/engintron#565]
My VPS had engintrom after I installed  Let's Encrypt cPanel plugin websites would not use the Let's Encrypt issued SSLs they would revert to the self signed cPanel SSLs. After 2 days I got 502 Bad Gateway on my websites.

After I submit a support ticket I was told the problem was conflict between engintrom & Let's Encrypt cPanel plugin.

https://letsencrypt-for-cpanel.com/

**Comment by BionicClick** [comment]
Hello,
Can you tell me, is "letsencrypt" the default cPanel SSL provider? I only ask because I use the very latest stable release of cPanel and I want to avoid installing egintron and having issues. All my certificates are provided by cpanel, and I never had to install letsencrypt to do that.

**Comment by fevangelou** [comment]
@robertmonroe That's crap from your host. Lame host imho. I've used this 3rd party plugin with several servers. They all worked just fine. The conflict is probably between cPanel's LE implementation and using this plugin AT THE SAME time.

@BionicClick He used a 3rd party plugin. Whole different story.

**Comment by RedDot-3ND7355** [comment]
@fevangelou Engintron is third party, same goes for Let's Encrypt. x')
I'm using Both on my VPS + CF and everything works fine. xD

Just remove all certificate given by cpanel/autossl on the account, except server root.
and re/issue ssl cert with Let's Encrypt. Everything works fine.

**Comment by fevangelou** [comment]
@RedDot-3ND7355 Didn't get your remark, sorry... As for LE, there is the official cPanel plugin and there's also a 3rd party plugin provided (the one originally mentioned from @robertmonroe).
