### ISSUE TITLE
.htaccess

### ISSUE THREAD

**Issue by 8BallBomBom** [engintron/engintron#568]
Having a weird issue that started happening randomly.
Tried using the mainstream and stable releases without any results.

Any sites which use .htaccess are having 404 page errors for rewrites.
What is weird is it never used to happen and if i disable engintron everything goes back to loading fine.

Any ideas?

**Comment by ramphy** [comment]
We are getting the same error...

**Comment by ramphy** [comment]
Problema resuelto.

Sólo necesitas reconfigurar el Apache, vía fácil: WHM > Apache Configuration > Global Configuration  (make any change) - Save And rebuild httpd.conf

Saludos.

**Comment by 8BallBomBom** [comment]
Thanks, that didn't help me specifically but I'm glad others are willing to help :)
That might help someone else with the same issue.

What resolved the problem for me was making sure all of my PHP versions were updated and then running an apache recompile.
I'm using CloudLinux, EA4 and the CloudLinux PHP Packages.
