### ISSUE TITLE
Engintron - SSL sites give 403 error, non SSL work fine

### ISSUE THREAD

**Issue by buckneri** [engintron/engintron#569]
I recently uninstalled engintron so that i could get cPanel to help with an issue i had upgrading to easy apache 4.  Now that EA4 is installed and running i am trying to get Engintron back on the server.

Last time with ea3 the only issue i ran into was that i needed to set my root to /home/~; in the config file because pages were loading to the default nginx index.html.

This time after setting that in the default.conf my normal websites will load but SSL gives me a 403 error.
As i am typing this i remembered that i deleted the default index.html from the nginx folder so this 403 error might actually be that it is pointing to the default nginx folder when i try to go to SSL sites on my server and since the index.html is not there i get a 403. 

SSL is done via Auto SSL lets encrypt (which worked fine with engintron and ea3)

Either way, i'm either getting directed to the wrong root only for SSL or some other 403 reason is happening.

Any ideas?  be easy on me, i'm still getting used to running my own server.

**Comment by buckneri** [comment]
As an update, i AM getting directed to the default index.html so it seems that for some reason SSL is ignoring the root folder setting...

**Comment by djlynux** [comment]
I'm facing the same issue at the moment. I've fixed the port 80 case by adding

>  root /home/~;

 in default.conf file. Now SSL ports are redirecting always to the default Nginx page. I'm using Cpanel certificate powered by Comodo.

**Comment by buckneri** [comment]
still no fix on my end, i have disabled nginx for now and am just running with apache.  Nobody has any input on this?

**Comment by fevangelou** [comment]
@buckneri if you needed to setup a root folder for Nginx, this means Nginx will not work for you as expected. So if you did this again, things will break. Leave the config as is, then try again. Modifying files that should not be modified unless you SPECIFICALLY know what you're doing, will result in problems.
