### ISSUE TITLE
Wiki modification: Cron job to purge Nginx cache & temp files

### ISSUE THREAD

**Issue by ramphy** [engintron/engintron#570]
Hello,

First of all, I want to thank for this wonderful project.

I would like to contribute a grain of sand, in relation to the WIKI:

Https://github.com/engintron/engintron/wiki/Cron-job-to-purge-Nginx-cache-&-temp-files

If nginx is not restarted, the cache deletion has no effect. Especially for the cPanel auto-ssl.

engintron.php:  case "nginx_purgecache":
        $ret = shell_exec("bash /usr/local/src/engintron/engintron.sh purgecache");
        $ret .= shell_exec("service nginx restart");

Please add in the WIKI:
service nginx restart

Thank you!

**Comment by fevangelou** [comment]
You're not reading the code. `/usr/local/src/engintron/engintron.sh purgecache` will restart both Apache and Nginx after it deletes the cache files.

As I've stated elsewhere, make sure your /etc/crontab is not broken. Simply open the file via the Engintron WHM app and just hit save.
