### ISSUE TITLE
Sites not accessible after install.

### ISSUE THREAD

**Issue by hiddenmagic** [engintron/engintron#571]
Read through just about everything I could in the Wiki and elsewhere. I REALLY want nginx!

Server with several dozen sites on it. 
Multiple IP addresses: 3
MYSQL disabled on server with separate MYSQL host
Two DNS Only installs in a cluster

Obviously I only need Engintron on the web server. Starting the service out of the box results in connections being refused for all sites http & https.

HOWEVER! If I go to www.example.com:8083 or www.example.com:8443 we're good. Everything loads as it should. Even the certificates load without error which surprised me.

Now obviously this isn't how everything is supposed to work, so I turn to you guys for some help. 

I'm really not sure if I should mess with any custom rules, if statements or what. I am NOT running CSF, and depend on a hardware firewall, and good old iptables to do the dirty work for me.

I can confirm when Engintron is enabled it tweaks the ports for Apache, and no errors show in the logs.

**Comment by fevangelou** [comment]
Nginx will try and resolve the IP of each domain using Google's Public DNS servers by default. This is in /etc/nginx/nginx.conf. If for some reason you're blocking such traffic, change to your internal DNS server or just 127.0.0.1.

Did you previously have any other Nginx for cPanel plugin installed on your server?

**Comment by hiddenmagic** [comment]
No, there was no need, as when we were doing the research it was pretty obvious Engintron was the only real contender.

I did configure the resolver to point to our nameservers, and they still are in fact:

resolver                       ns1.mydnsserver.com ns2.mydnsserver.com;

Any thoughts?

**Comment by fevangelou** [comment]
If Nginx can be started and it binds to ports 80 and 443, have a look at its logs at /var/log/nginx/ for any errors related to web traffic.

**Comment by hiddenmagic** [comment]
Well, I think we're onto something here:

2017/06/27 09:24:33 [emerg] 22118#22118: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/06/27 09:24:33 [emerg] 22118#22118: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/06/27 09:24:33 [emerg] 22118#22118: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/06/27 09:24:33 [emerg] 22118#22118: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/06/27 09:24:33 [emerg] 22118#22118: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/06/27 09:24:33 [emerg] 22118#22118: still could not bind()
2017/06/27 09:48:52 [emerg] 25950#25950: listen() to 0.0.0.0:443, backlog 511 failed (98: Address already in use)
2017/06/27 09:48:52 [emerg] 25950#25950: listen() to 0.0.0.0:443, backlog 511 failed (98: Address already in use)
2017/06/27 09:48:52 [emerg] 25950#25950: listen() to 0.0.0.0:443, backlog 511 failed (98: Address already in use)
2017/06/27 09:48:52 [emerg] 25950#25950: listen() to 0.0.0.0:443, backlog 511 failed (98: Address already in use)
2017/06/27 09:48:52 [emerg] 25950#25950: listen() to 0.0.0.0:443, backlog 511 failed (98: Address already in use)
2017/06/27 09:48:52 [emerg] 25950#25950: still could not bind()


Like I said, if I launch Engintron, and browse to mydomain.com:8080 or mydomain.com:8443 it comes up just fine. 

Where do you think I should go from here? Also, thanks for your help.

**Comment by fevangelou** [comment]
Something else already binds to ports 80 and 443.

Run `lsof -i :80` and `lsof -i :443` to see which service is that and then use `killall NAME_OF_SERVICE` to stop it/them.

**Comment by hiddenmagic** [comment]
Oh this is fun...

The error log shows the most recent errors:
2017/06/27 10:09:56 [emerg] 32078#32078: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/06/27 10:09:56 [emerg] 32078#32078: bind() to 0.0.0.0:443 failed (98: Address already in use)

However. The only processes attached to ports 80 and 443 are nginx and httpd:
lsof -i :80 <
COMMAND   PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
nginx   32330  root    6u  IPv4 1136994      0t0  TCP *:http (LISTEN)
nginx   32331 nginx    6u  IPv4 1136994      0t0  TCP *:http (LISTEN)
nginx   32331 nginx   12u  IPv4 1140644      0t0  TCP myserver:http->host-212-253-111-131.reverse.superonline.net:61989 (ESTABLISHED)
nginx   32331 nginx   15u  IPv4 1140281      0t0  TCP localhost:http->localhost:41416 (CLOSE_WAIT)

And lsof -i :443 <
nginx   32330  root    7u  IPv4 1136995      0t0  TCP *:https (LISTEN)
nginx   32331 nginx    7u  IPv4 1136995      0t0  TCP *:https (LISTEN)

Purged all cache and files. Same result as before, and still accessible via mydomain:8080 and mydomain:8443

**Comment by fevangelou** [comment]
`killall nginx`
Execute this a few times until you get a warning that no service is found. Then do `service nginx start`.

**Comment by hiddenmagic** [comment]
Same result. Actually did that in my previous post, just didn't mention it.

I have no idea what's causing this. Any other thoughts? It would kill me to think I can't get Engintron to work, but I understand if I have to wait, and try another build maybe.

**Comment by fevangelou** [comment]
Try a reboot. If that doesn't work, uninstall Engintron, reboot, re-install. If nothing works, ask your hosting company to have a look or any other pro sysadmin.

**Comment by hiddenmagic** [comment]
Yeah, I'll do that now. This is our own machine, and we do have have engintron running just fine on a clients machine as well. Same setup as our and the specs are close too. Same Centos7 as well. I'll reboot and try what you mentioned. I'll keep you posted whether I fail or fix it.

**Comment by hiddenmagic** [comment]
Alright. Uninstalled, rebooted, reinstalled and the same result. Even tried changing the resolvers again with another reboot. No luck.

I appreciate your help, but it looks like Engintron isn't for me just this second. No one was asking for it specifically anyhow, we just wanted to speed things up a bit and lower our overall load.

Thanks for all your help, and we'll be tuned in for future releases, and I'll be sure to try them all till we get somewhere. 

Guess I'll try some varnish to lighten the load a bit. IT doesn't compare to Nginx, but it's something.

Thanks again!
