### ISSUE TITLE
Magento 2 multiple websites/stores

### ISSUE THREAD

**Issue by HoffStarr** [engintron/engintron#572]
Magento 2 has documentation for multiple websites using nginx - http://devdocs.magento.com/guides/v2.0/config-guide/multi-site/ms_nginx.html

It requires virtual hosts to be created, passing $MAGE_RUN_CODE to the host which relates to the Magento website you are targeting.

Is there a different way to do this with Engintron? Can I set environment variables based on host?

**Comment by fevangelou** [comment]
The setup you refer to applies only when Nginx is the direct webserver. In cPanel's case, Nginx acts as a reverse caching proxy passing traffic back and forth to Apache. So any multi-site configs you need to do should be done on Apache (and .htaccess files I presume).
