### ISSUE TITLE
Engintron do not working cleaning folder /tmp

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#574]
Hello, Engintron v1.8.4 do not working cleaning folder /tmp automatic.

**Comment by JorgeMarcelino-HS** [comment]
Hello, Bug not fixed! AutoSSL only active after restarting NGINX :(

**Comment by Simoneworks** [comment]
I can confirm it like i wrote here

#582

**Comment by fevangelou** [comment]
Use the other thread.
