### ISSUE TITLE
[core:error] [pid 18977:tid 140379560892544] (2)No such file or directory: AH00095: failed to remove PID file /run/apache2/httpd.pid

### ISSUE THREAD

**Issue by spirogg** [engintron/engintron#575]
Hi nit sure if this is an issue or why I get this in my logs after restarting apache and nginx ? i cleared all logs and cache but I keep getting this no such file found and the rest of the log ? any Idea if i should worry about this my server is running: 

  CENTOS 7.3 x86_64 standard – server1  cPanel & WHM 64.0 (build 29

[Sat Jul 01 09:42:55.377055 2017] [core:error] [pid 18977:tid 140379560892544] (2)No such file or directory: AH00095: failed to remove PID file /run/apache2/httpd.pid

Log Messages
	[Sat Jul 01 09:56:31.342027 2017] [mpm_worker:notice] [pid 14376:tid 140553530169472] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:56:04.632252 2017] [mpm_worker:notice] [pid 14376:tid 140553530169472] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:55:27.876115 2017] [mpm_worker:notice] [pid 14376:tid 140553530169472] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:54:34.747723 2017] [mpm_worker:notice] [pid 14376:tid 140553530169472] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:54:34.721247 2017] [:notice] [pid 14375:tid 140553530169472] ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/) configured.
	[Sat Jul 01 09:54:27.552117 2017] [mpm_worker:notice] [pid 13620:tid 140441006958720] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:54:27.061137 2017] [mpm_worker:notice] [pid 13620:tid 140441006958720] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:54:24.908603 2017] [mpm_worker:notice] [pid 13620:tid 140441006958720] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:54:24.885412 2017] [:notice] [pid 13619:tid 140441006958720] ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/) configured.
	[Sat Jul 01 09:54:22.877737 2017] [mpm_worker:notice] [pid 13268:tid 139664449357952] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:54:22.853739 2017] [:notice] [pid 13265:tid 139664449357952] ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/) configured.
	[Sat Jul 01 09:54:21.965635 2017] [mpm_worker:notice] [pid 13064:tid 140122740951168] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:54:21.941129 2017] [:notice] [pid 13063:tid 140122740951168] ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/) configured.
	[Sat Jul 01 09:51:07.002342 2017] [mpm_worker:notice] [pid 949:tid 139779582380160] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:49:55.851779 2017] [mpm_worker:notice] [pid 949:tid 139779582380160] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:44:30.301856 2017] [mpm_worker:notice] [pid 949:tid 139779582380160] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:44:30.237289 2017] [:notice] [pid 919:tid 139779582380160] ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/) configured.
	[Sat Jul 01 09:42:55.377055 2017] [core:error] [pid 18977:tid 140379560892544] (2)No such file or directory: AH00095: failed to remove PID file /run/apache2/httpd.pid
	[Sat Jul 01 09:40:26.249601 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:39:15.414047 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:38:46.647191 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:37:10.891170 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:37:05.926936 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:36:47.401379 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:36:28.822115 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:36:13.706104 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:36:02.897470 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:34:47.847858 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:18:56.824339 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:16:58.690801 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 09:03:06.152376 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/conf/httpd.conf:784
	[Sat Jul 01 08:02:06.465476 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 07:03:42.435840 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 06:04:59.567013 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 05:39:57.777266 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 04:07:53.796814 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 02:11:08.925929 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Sat Jul 01 00:14:24.374379 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Fri Jun 30 22:00:59.063718 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Fri Jun 30 20:04:14.340558 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Fri Jun 30 18:07:29.670332 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Fri Jun 30 16:10:44.696950 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Fri Jun 30 14:13:59.955587 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations
	[Fri Jun 30 12:00:34.583041 2017] [mpm_worker:notice] [pid 18977:tid 140379560892544] AH00292: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 configured -- resuming normal operations

httpd restarted successfully.

Restarting Nginx...
Redirecting to /bin/systemctl restart  nginx.service

**Comment by omikron** [comment]
I get the same, did you figure out what the problem is?

**Comment by ramphy** [comment]
Hi, this problem, if I remember correctly, just make a change in: WHM > Apache Configuration> Global and save + rebuild httpdf.

Them restart the gracefull server. If this is correctly, let me know!

Good Luck!

**Comment by fevangelou** [comment]
Did you resolve this?

**Comment by spirogg** [comment]
No sir. Still the same. I can email you my server login if you want to
check. I get the same Everytime I restart.

Thanks. Spiro

**Comment by fevangelou** [comment]
@spirogg Send it to engintron at gmail dot com. I'll have a look now. Make sure you allow access to all IPs

**Comment by spirogg** [comment]
sent it sir thank you

**Comment by fevangelou** [comment]
@spirogg These are just notices. Nothing stopping your server from operating normally. And checking the sites hosted on your server, things seem to work just fine.

**Comment by spirogg** [comment]
Ok wasn't sure it there was misconfiguration somewhere or if that was ok.
Should I stick with what I installed. Or use inline ??

Thanks for checking.

Spiro

**Comment by fevangelou** [comment]
You're fine. No need to change anything. The notices will probably go away when you update your EA4 configuration or when cPanel updates the various packages installed related to these notices (e.g. the mod_bwlimited Apache module).
