### ISSUE TITLE
Internal Server Error 500 - Nginx

### ISSUE THREAD

**Issue by rapidcloubr** [engintron/engintron#576]
Hello,

We noticed that after a few days running ENGINSTRON, the sites started to display Internal Server Error 500 Nginx.

To solve the problem, we simply re-start ENGINSTRON and everything works again.

The server runs with Cloud Linux, has 24GB of RAM memory and 8 cores.

http://prntscr.com/fqin4o

**Comment by rapidcloubr** [comment]
Please, i need help!

**Comment by fevangelou** [comment]
Rule #1. Check the freaking error log in Nginx.

If you see messages related to no memory etc., it means you need to optimize your server to save RAM and CPU usage.

It's all here: https://github.com/engintron/engintron/wiki#beyond-engintron---optimization-guides
