### ISSUE TITLE
fresh install. SSL port went offline :/

### ISSUE THREAD

**Issue by systemroot** [engintron/engintron#578]
i did a fresh install,

i was using ssl in some websites, but after engintron installation SSL port went offline,

```bash
[root@cpanel /]# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
[root@cpanel /]# 
```
no errors just went off.
help please?

**Comment by systemroot** [comment]
-.- fixed!

**Comment by systemroot** [comment]
nope!.

it's working for ex main domain `https://example.com` but SSL is offline for subdomains ex `https://ex.example.com`

**Comment by systemroot** [comment]
ok fixed now.

**Comment by fevangelou** [comment]
Magic :)
