### ISSUE TITLE
memory usage high needs explained

### ISSUE THREAD

**Issue by digitaliway** [engintron/engintron#579]
after install I am showing the following usage and wanted to know if this is normal?

Processors: 4 CPU(s)

RAM: 11.35 GB

Memory Usage:
             total       used       free     shared    buffers     cached
Mem:         11627      11438        189        263        844       6287
-/+ buffers/cache:       4306       7321
Swap:         1023         59        964

**Comment by fevangelou** [comment]
Nginx does not increase RAM or CPU usage. Something else is to blame. You'll need to provide more info on your setup.
