### ISSUE TITLE
Delete a domain from engintron

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#580]
Hello, Is it possible to delete a domain from engintron? For the domain to work only with apache!

**Comment by fevangelou** [comment]
No. Nginx binds to port 80. Apache to port 8080. The can't bind to both ports.

Use custom rules to bypass caching entirely. It's the same thing.

**Comment by JorgeMarcelino-HS** [comment]
@fevangelou Hello, The problem is in a slider jQuery that is not loading, it only works after disable Engintron.

How to solve this? It seems to be the MIME version...

**Comment by fevangelou** [comment]
Enable Engintron and send me the URL of the site in question.

**Comment by JorgeMarcelino-HS** [comment]
Refused to execute script from 'http://hidroservdesentupidora.com.br/sig/js/jquery-1.9.0.min.js' because its MIME type ('application/x-httpd-php') is not executable, and strict MIME type checking is enabled.

**Comment by fevangelou** [comment]
Some .htaccess file is messing the headers up.
