### ISSUE TITLE
webmail 

### ISSUE THREAD

**Issue by perfectwebtech** [engintron/engintron#581]
in cpanel  webmail.domain.com not working

after login getitng connectino timeout

but when try   domain.com/webmail is working fine

is there any help or guidance would be very appreiciate

Thanks
Parbat
http://www.omlinux.com

**Comment by felipegabriel** [comment]
version of Engintron v1.8.4?

**Comment by perfectwebtech** [comment]
yes latest one

**Comment by perfectwebtech** [comment]
hello

issue resolved by 

comment  x host and x  server also both commented and

working fine without issue

thanks a lot you guy did great work really

enjoying your nginx really wonderfull thanks a nd appreciate 

why not make like panel like cpanel competitor if may be some group together

and make   cpanel competitor :) if need server i can give free server for testing

but i think this is time  make great open source for every hosting company and customers free 

with dontation only ha ha ha really it possible if some guys together in group can do it :)

**Comment by fevangelou** [comment]
Resolved.
