### ISSUE TITLE
Restarting the server to apply the ssl

### ISSUE THREAD

**Issue by vipxr** [engintron/engintron#582]
Hello 
first I want to thank you for your great work
I have one little problem that I need to restart the server 
every time after adding the SSL to a domain
Is this can be fixed ?
for example restarting a specific service every 5m automatically without anyone notice ?

Thank you

**Comment by tgerov** [comment]
Hello,

You can test my patch for nginx/utilities/https_vhosts.sh - https://github.com/tgerov/engintron/blob/64c5e7599777c63df16da75e30a3a6984753ab96/nginx/utilities/https_vhosts.sh

**Comment by JorgeMarcelino-HS** [comment]
@tgerov Hello,  Is it possible to delete a domain from engintron? For the domain to work only with apache?

I have some problems with slider in JQuery!

**Comment by simonenetsons** [comment]
Hi

if i run

```
RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php)
echo $RUN_CHECK
No changes in Apache's vhosts configuration. HTTPS vhosts for Nginx unchanged.
```
Instead of 0  (like output)

or
```
RUN_CHECK=$(/usr/bin/php -c /dev/null /etc/nginx/utilities/https_vhosts.php)
echo $RUN_CHECK
echo "HTTPS vhosts for Nginx re-created.\n";

```
Instead of 1 (like output)

So the check [[ $RUN_CHECK == 1 ]]  in  https_vhosts.sh  will always fail AND so the command 

bash /usr/local/src/engintron/engintron.sh purgecache

will be never execute.

Am I wrong? Can you check?

Best Regards

**Comment by ramphy** [comment]
https://github.com/engintron/engintron/issues/566#issuecomment-311133634

**Comment by Simoneworks** [comment]
Hi

i red the #566 (comment) and i understood that a crontab can be a good  workaround, but in the file

`/etc/nginx/utilities/https_vhosts.sh`

is already present the commad 

`bash /usr/local/src/engintron/engintron.sh purgecache`

the problem is that the IF condition will be never verficated (according to me) and so the command will be not executed.

Am I wrong?

thanks

**Comment by ramphy** [comment]
I have no idea, but the developers recommend purging via cronjob: https://github.com/engintron/engintron/wiki/Cron-job-to-purge-Nginx-cache-&-temp-files

Greets!

**Comment by Simoneworks** [comment]
I hope some dev read this thread and answer to us;

The cronjob purge can NOT be in a solution in a production server.

**Comment by fevangelou** [comment]
When Apache's config changes, Nginx will pick up the changes and refresh its config.

The only way I can think of that this process is broken is by a broken /etc/crontab file. Open that file via the Engintron WHM app, check if everything is OK and SAVE it. It's important to SAVE the file even if everything is OK.

**Comment by zstergios** [comment]
I have the same issue.
Also when everything is worked with Engintron enabled, when I deactivate every ssl site does not load.
Strange....

@fevangelou  I can give you access to check the issue
