### ISSUE TITLE
Nginx Failure, SSL

### ISSUE THREAD

**Issue by 8BallBomBom** [engintron/engintron#583]
After a new client has been assigned SSL Nginx needs a reboot before the certificates are applied.
I'm running the latest version of Engintron and the current Mainline Nginx.
After a restart Nginx stopped working with this error.

`
Jul 06 14:23:18 nginx[1016]: nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/cpanel/ssl/installed/keys/c0d3b_2af75_02e73d7cb593b855fa2524f496a74b4f.key") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/installed/keys/c0d3b_2af75_02e73d7cb593b855fa2524f496a74b4f.key','r') error:20074002:BIO routines:FILE_CTRL:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)
Jul 06 14:23:18 nginx[1016]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jul 06 14:23:18 systemd[1]: nginx.service: control process exited, code=exited status=1
`

Seems as if AutoSSL is breaking the Nginx config.

**Comment by ramphy** [comment]
https://github.com/engintron/engintron/issues/566#issuecomment-311133634

**Comment by fevangelou** [comment]
Update to the latest release. If Nginx does not autorefresh its config when Apache's config changes, there may be something else causing this problem (broken /etc/crontab file for example).

**Comment by jhawkins002** [comment]
Hi there @8BallBomBom 

See issue https://github.com/engintron/engintron/issues/561

If you can determine that is the same error you have reported here, I would suggest closing this report and following that thread to help @fevangelou sort through duplicates. ;)
