### ISSUE TITLE
New installation: Bad Getaway

### ISSUE THREAD

**Issue by desfire** [engintron/engintron#584]
Hi,
I just made a fresh installatron of both cPanel and Engintron and without running engintron sites look fine but once I enable it all sites show Bad Getaway issue, how do I fix this?

**Comment by fevangelou** [comment]
Is that a 502 error? If so, it means Apache is taking ages to respond to Nginx in which case Nginx cuts off the connection after 3-4 mins.

Optimize Apache https://github.com/engintron/engintron/wiki/Beyond-Engintron:-Optimizing-Apache to resolve this and/or possibly increase the wait times in Nginx (in proxy_params_common under "Timeouts" https://github.com/engintron/engintron/blob/master/nginx/proxy_params_common#L33).
