### ISSUE TITLE
https_vhosts.php does not generate correct configuration

### ISSUE THREAD

**Issue by lupetalo** [engintron/engintron#585]
Https config file default_https.conf is not correct. The script used to generate it is writing down certificates that are deleted from cPanel. Even from the accounts that are terminated. This results in errors like this:
```
Checking Nginx configuration...
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/cpanel/ssl/installed/keys/{key}.key") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/installed/keys/{key}.key','r') error:20074002:BIO routines:FILE_CTRL:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)
nginx: configuration file /etc/nginx/nginx.conf test failed
```
that can prevent Nginc from starting. I am on newest Engintron (1.8.4), cPanel 64.0 b29, CloudLinux,
What can be done?

**Comment by fevangelou** [comment]
Engintron will only read what's on your Apache config. If you see files like these in Nginx's configs, it means they were not deleted in Apache. It's not magic, it's plain logic.

**Comment by brixly** [comment]
So, let's get a logical answer - are we able to run /scripts/rebuildhttpdconf prior to the above script running? Would that provide a solution?

I know currently this is a timing issue - we face it also (as I'm sure everyone running on a decent scale will).

It's not sarcasm were after, it's just solutions to problems we face - it isn't criticism were all strong believers in the product. Myself, a huge fan of engintron. There are just a few things to iron out (like this) where we need your comments.

**Comment by devteam9200** [comment]
I also have the same issue. I am wondering if anyone here can assist. It appears that Engintron has stopped adding newly created cpanel accounts domains to the /etc/nginx/con.d/default_https.conf  confguration file? How can i resolve this please?
