### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by systemroot** [engintron/engintron#586]
**problem 1.**
`.htaccess` file sometimes work and some times doesn't work. weird!

**problem 2.**
using a custom config to redirect from `http` to `https` doesn't work. as i know engintron automatically redirect domains to ssl but my domain wasn't redirected to ssl. so i've wrote the rule manually like..
```bash
if ($host ~ 'mydomain.com') {
    set $redirToSSL "on";
}
if ($redirToSSL = "on") {
    return 301 https://$host$request_uri;
}
```
wroting that manually i get ```ERR_TOO_MANY_REDIRECTS```

**problem 3.** (not confirmed) as the point of the "cache" is to store some caches. this doesn't happen. if i change one image it will be replaced with 1 refresh :confused:  in previous engintron versions this was good i was needed to purge caches and image was changed but not just with 1 refresh!

```bash
[root@cpanel ~]# lsof -i :80
COMMAND  PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
nginx   9439  root    6u  IPv4 3949592      0t0  TCP *:http (LISTEN)
nginx   9647 nginx    6u  IPv4 3949592      0t0  TCP *:http (LISTEN)
nginx   9648 nginx    6u  IPv4 3949592      0t0  TCP *:http (LISTEN)
nginx   9649 nginx    6u  IPv4 3949592      0t0  TCP *:http (LISTEN)
nginx   9650 nginx    6u  IPv4 3949592      0t0  TCP *:http (LISTEN)
[root@cpanel ~]# lsof -i :8080
COMMAND   PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
httpd    9406 nobody    3u  IPv4 3394141      0t0  TCP *:webcache (LISTEN)
httpd    9406 nobody    4u  IPv6 3394143      0t0  TCP *:webcache (LISTEN)
httpd    9407 nobody    3u  IPv4 3394141      0t0  TCP *:webcache (LISTEN)
httpd    9407 nobody    4u  IPv6 3394143      0t0  TCP *:webcache (LISTEN)
httpd    9408 nobody    3u  IPv4 3394141      0t0  TCP *:webcache (LISTEN)
httpd    9408 nobody    4u  IPv6 3394143      0t0  TCP *:webcache (LISTEN)
httpd    9409 nobody    3u  IPv4 3394141      0t0  TCP *:webcache (LISTEN)
httpd    9409 nobody    4u  IPv6 3394143      0t0  TCP *:webcache (LISTEN)
httpd    9410 nobody    3u  IPv4 3394141      0t0  TCP *:webcache (LISTEN)
httpd    9410 nobody    4u  IPv6 3394143      0t0  TCP *:webcache (LISTEN)
httpd   16788   root    3u  IPv4 3394141      0t0  TCP *:webcache (LISTEN)
httpd   16788   root    4u  IPv6 3394143      0t0  TCP *:webcache (LISTEN)
[root@cpanel ~]# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
[root@cpanel ~]# 
```

**Comment by fevangelou** [comment]
1. Nginx does not mess with .htaccess files. If things don't work for you, then the rules in .htaccess are wrong.

2. Avoid doing such rewrites in Nginx. Prefer to do them in .htaccess files. The reason you got too many redirects is probably because there was already some rule in a .htaccess file.

3. It depends. The static cache has a 1 min duration. You probably just stumbled upon a cache refresh. Modify the proxy_params_static file to increase the cache time for static files. Do not confuse this with cache-control headers. The latter can be invalidated with a hard-refresh on your browser or just by opening a new private window/tab.

**Comment by fevangelou** [comment]
Updated the title of the issue as it reminded me of this: http://importblogkit.com/2015/07/does-not-work/

**Comment by systemroot** [comment]
>Updated the title of the issue as it reminded me of this: http://importblogkit.com/2015/07/does-not-work/ 

hm sorry.

about what you say about my issues, 

1. i tried alot of things one day i got it to work. next day wasn't working. ofcourse i've clear cookies and i've tried on different browsers. anyway i will try to check maybe i've did something wrong while working with security. 

2. i tried to delete .htaccess i got the same error :confused: 

4. well i will try thanks for info..

**Comment by systemroot** [comment]
also i didn't mean to say "engintron doesn't work" as that blog says something about "doesn't work" 

but i've tried engintron before https://github.com/engintron/engintron/issues/426 and for me the latest version isn't going that good as my first time trying this project. because was more then 1 problem i didn't know what to put as title so i wroted "doesn't work **good**
