### ISSUE TITLE
After updating Apache, Nginx don't work !

### ISSUE THREAD

**Issue by petarkozic** [engintron/engintron#587]
I have several WHM servers and I have same problem. Every time when Apache is update, Nginx stop working and I must to restart manually. If I remember this problem is resolved adding Engintrons in CPanel as registered service, but I have still this problem.

Some resolution, thank you ?

**Comment by petarkozic** [comment]
Does anyone have some solution. Last night Apache is updated and stop working. 20 minutes my shared hosting servers were down :(

**Comment by petarkozic** [comment]
Tonigh again !

Apache status:
httpd dead but pid file exists

After manualy restarted apache, everything works !

**Comment by fevangelou** [comment]
The problem seems to be Apache specific in the latest v66 release of cPanel. You should probably file a ticket with cPanel for that as I can't possibly know why Apache tries to bind to port 80, thus killing Nginx.
