### ISSUE TITLE
Response time of nginx

### ISSUE THREAD

**Issue by Simoneworks** [engintron/engintron#588]
Hi

we use Pingdom to monitor our server (CloudLinux * Cpnale EA4) and we found a possible issue with "Response Time".

After we enable Engitron we find that some time the respons time of server (tested by a simple query on db via php) take UP to 5 seconds to response while in the normal case it would take about 300ms (less or more).

What can i do to avoid this slow answer from server ? 
Ps. I am sure that the problem is NOT the load of server for 2 important reasons:

1) from statistic of server, it did not have load of any kind
2) If i switch off engitron i never see this slow response 

I hope you can help me.

FYI:
17/07/2017 11:40:12	2m ago	282 ms	United States Atlanta, GA
17/07/2017 11:39:12	3m ago	283 ms	Canada Toronto 3, Canada
17/07/2017 11:38:12	4m ago	110 ms	United Kingdom London 2, UK
17/07/2017 11:37:12	5m ago	237 ms	United States Philadelphia 3, PA
17/07/2017 11:36:12	6m ago	380 ms	United States Seattle, WA
17/07/2017 11:35:12	7m ago	270 ms	United States Dallas, TX
17/07/2017 11:34:12	8m ago	5.073 ms	France Strasbourg 5, France
17/07/2017 11:33:12	9m ago	448 ms	United States San Jose, CA
17/07/2017 11:32:12	10m ago	5.157 ms	Sweden Stockholm 2, Sweden
17/07/2017 11:31:12	11m ago	310 ms	United States St. Louis 2, MO
17/07/2017 11:30:12	12m ago	237 ms	United States Atlanta, GA
17/07/2017 11:29:12	13m ago	264 ms	Canada Toronto 3, Canada
17/07/2017 11:28:12	14m ago	130 ms	United Kingdom London 2, UK
17/07/2017 11:27:12	15m ago	210 ms	United States Philadelphia 3, PA
17/07/2017 11:26:12	16m ago	356 ms	United States Seattle, WA
17/07/2017 11:25:12	17m ago	325 ms	United States Dallas, TX
17/07/2017 11:24:12	18m ago	5.074 ms	France Strasbourg 5, France
17/07/2017 11:23:12	19m ago	590 ms	United States San Jose, CA
17/07/2017 11:22:12	20m ago	155 ms	Sweden Stockholm 2, Sweden
17/07/2017 11:21:12	21m ago	291 ms	United States St. Louis 2, MO
17/07/2017 11:20:12	22m ago	5.255 ms	United States Atlanta, GA
17/07/2017 11:19:12	23m ago	5.303 ms	Canada Toronto 3, Canada
17/07/2017 11:18:12	24m ago	74 ms	United Kingdom London 2, UK
17/07/2017 11:17:12	25m ago	239 ms	United States Philadelphia 3, PA
17/07/2017 11:16:12	26m ago	4.988 ms	United States Seattle, WA
17/07/2017 11:15:12	27m ago	295 ms	United States Dallas, TX
17/07/2017 11:14:12	28m ago	5.090 ms	France Strasbourg 5, France
17/07/2017 11:13:12	29m ago	462 ms	United States San Jose, CA
17/07/2017 11:12:12	30m ago	127 ms	Sweden Stockholm 2, Sweden

**Comment by greenwebbd** [comment]
i think if you turn off gzip compression it will solve first byte reading time increasing problem. you can use less compression to improve the first byte reading time.

**Comment by Simoneworks** [comment]
I already turn off gzip compression.

My problem is that the responde time is good in many case, but sometime it is **very bad**

Do you have any idea about the cause of this behaviour ?

**Comment by fevangelou** [comment]
Network congestion is the problem. Your host is sometimes busy and sometimes it isn't. Or Pingdom's hosting provider is busy. These tools should be taken with a grain of salt.
