### ISSUE TITLE
SSL Termination

### ISSUE THREAD

**Issue by kmzby** [engintron/engintron#590]
Hi,

Could you please shed some light on the reasons of choosing the following approach:
`proxy_pass                    $scheme://$PROXY_DOMAIN_OR_IP:$PROXY_TO_PORT;`

Proxying HTTPS to HTTPS seems a bit inefficient and should be avoided, according to nginx authors.
Besides, I see no sense in using domain name as upstream address, and it causes additional overhead on DNS lookups.

Thanks in advance.

**Comment by fevangelou** [comment]
a) DNS lookups are cached in Nginx. So the overhead is for the first user to request any given domain after the DNS cache is refreshed every 15 or 30 mins. And we're talking about milliseconds here.
b) Proxying is symmetrical (HTTP to HTTP or HTTPS to HTTPS) to avoid redirect loops on sites that use .htaccess redirect rules from HTTP to HTTPS (which is dead-common).

Engintron improves performance in many ways, not just server-side but also client-side. Test it with ApacheBench or Siege to see for yourself.
