### ISSUE TITLE
Login cache issue

### ISSUE THREAD

**Issue by rahulnagpal1989** [engintron/engintron#592]
When i login with my user credentials, it'll open some another account randomly. I want to disable cache for dynamic content.

**Comment by lakshmish2004** [comment]
i am also facing same issues the users session swapping on multiple request

**Comment by fevangelou** [comment]
Check the damn wiki then.

**Comment by rahulnagpal1989** [comment]
Please provide a solution for this as currently i am using apache again by disabling Engintron but i want to use nginx for my server, but this issue force me to disable nginx.

**Comment by rahulnagpal1989** [comment]
@fevangelou is there any way to solve this issue. Please help me fix this issue as nginx is very fast as compare with apache.
