### ISSUE TITLE
Wordpress login page not found 404 error

### ISSUE THREAD

**Issue by ronibd07** [engintron/engintron#594]
I have installed engintron in one of my server with almost 300 websites. I have lots of wordpress site. After installing engintron, i am getting 404 not found error when trying to go to my wordpress login page by www.example.com/wp-admin. 
But if i disable engintron, then this error is not shown and i can login wordpress dashboard without any problem.

I have cloud linux installed and my cpanel and cloudlinux version is:
CLOUDLINUX 6.9 x86_64 standard – server5  cPanel & WHM 64.0 (build 36)

Could anyone faced the same problem and have any solution?

**Comment by fevangelou** [comment]
Some .htaccess file is probably messing things up. There is no reason for Nginx to serve a different file from what you requested unless there's an .htaccess rule that checks the referrer or something like that.
