### ISSUE TITLE
403 Forbidden- nginx upstream pointing to false IP - Connection refused

### ISSUE THREAD

**Issue by catalincolesnicov** [engintron/engintron#595]
Hello,
after transfering all websites to an new server, nginx is pointig the upstream of the sites to the old server. any ideas solving the problem?

the output of the error log is:

2017/07/30 09:27:09 [error] 28172#28172: *500 connect() failed (111: Connection refused) while connecting to upstream, client: 199.30.xx.xx, server: xxxxxxxxxxxxxx.at, request: "GET /wp-content/themes/up/js/translate-dictionary.js HTTP/1.1", upstream: "https://OLD-SERVER-IP:8443/wp-content/themes/up/js/translate-dictionary.js", host: "www.xxxxxxxxxxxxxxxx.at"

Regards

**Comment by iRickyJ** [comment]
Well, should be resolved by now as its more DNS propagation issue. If it is seeing this error then you can point IP manually in config.
