### ISSUE TITLE
502 Bad Gateway on 1 website

### ISSUE THREAD

**Issue by gbassoc** [engintron/engintron#596]
Hi
I have several websites on the same server same IP, I'm using cPanel, LetsEncrypt, engintron 1.8.4
All the websites are working fine except one which has one html page. When I enable Engintron the website   fail to load with "502 Bad Gateway" when I disable Engintron the websiteit works fine.

Engintron error log has the following entry, but I really cannot be sure what it is telling me.

2017/08/01 02:30:32 [error] 2719#2719: *120 wpfan.club could not be resolved (2: Server failure), client: 37.228.253.1, server: localhost, request: "GET / HTTP/1.1", host: "wpfan.club"
2017/08/01 02:30:37 [error] 2719#2719: *122 wpfan.club could not be resolved (2: Server failure), client: 37.228.253.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "wpfan.club"

Can you help with this, I have disabled  Engintron for the time being but really want in on again 

Thanks

gbassoc

**Comment by revcomllc** [comment]
@gbassoc  did you find a resolution to this yet? as we are experiencing the same issue with only 1 site as well

**Comment by fevangelou** [comment]
"wpfan.club could not be resolved"

This is your issue. Check the wiki on how to resolve such issues when using domains that do not yet resolve to your server.
