### ISSUE TITLE
Running apache on 127.0.0.1:8080

### ISSUE THREAD

**Issue by codenamerana** [engintron/engintron#598]
I want to run apache on 127.0.0.1:8080 and want nginx to proxify requests from 0.0.0.0:80

When i set that i no longer can connect to websites. 

My configuration is
# Initialize important variables
    set $CACHE_BYPASS_FOR_DYNAMIC 0;
    set $CACHE_BYPASS_FOR_STATIC 0;
    set $PROXY_DOMAIN_OR_IP "127.0.0.1";
    set $PROXY_TO_PORT 8080;
    set $SITE_URI "$host$request_uri";

Do i need to do anything else ?

:

**Comment by fevangelou** [comment]
Apache, as set by cPanel does not listen to 127.0.0.1, but only on specific IP addresses. In other words, you can't do what you want.

It's better to just block access to Apache externally by configuring your firewall.

**Comment by codenamerana** [comment]
Ok got it. 
What about L7 protection for nginx ?

**Comment by fevangelou** [comment]
Nginx does not prevent DoS, let alone DDoS (watch the double D). To safeguard your server from DoS, use CSF and set CT_LIMIT to something like 300. For DDoS you need a cloud solution like CloudFlare (cheap) or a specialised solution from your hosting provider (usually an expensive firewall).

**Comment by MoHD20** [comment]
> Apache, as set by cPanel does not listen to 127.0.0.1, but only on specific IP addresses. In other words, you can't do what you

@fevangelou  Thanks for the info but can you please get the docs for that? I wan't it in an argument :D
