### ISSUE TITLE
cloudflare conflict

### ISSUE THREAD

**Issue by mcl21us** [engintron/engintron#60]
Error 1000 Ray ID: 2710da41e3cd0d43 • 2016-02-07 17:35:39 UTC
DNS points to prohibited IP
What happened?
You've requested a page on a website (mydomainname.com) that is on the CloudFlare network. Unfortunately, it is resolving to an IP address that is creating a conflict within CloudFlare's system.

**Comment by ImLuke954** [comment]
If you use Cloudflare you should also set your server's shared IP address inside proxy_params_common.

**Comment by fevangelou** [comment]
Tomorrow I'll be releasing version 1.5.2 with various updates like CentOS 7
support and updating from within WHM. I'll make sure to publish a distinct
guide on how to use with CloudFlare effectively including some nice tricks
like forcing SSL redirects for all domains and more.

**Comment by fevangelou** [comment]
1.5.2 is now out (a bit earlier), so expect a documentation update by tomorrow.

**Comment by mcl21us** [comment]
Thank you Luke and Fevangelau such a great plugin this is better than nginxcp my sites is 10x faster with  Engintron + mod_pagespeed + xcache

NginxCP+mod_pagespeed +xcache Load time 7.58s 
vs 
Engintron  + mod_pagespeed + xcache Load time 727ms

**Comment by fevangelou** [comment]
Glad to know :)

I'd really appreciate it if you wrote a short review on the cPanel
Applications Directory at: https://github.com/nuevvo/engintron

**Comment by masteranalyze** [comment]
mcl21us,with what did you done the benchmark?what tools did you used?

Did you tryed engintron +apcu+opcache ?and check if the time is even more better then 727ms?

Anyhow the difference between 7seconds .58second and just 727,is like earth to SKY.

Anyhow fev,when you benchmarked in joomla with Varnish +engintron +apcu+opcache,what results on that project you got ?

The stackoverflow,anyhow obtains about 50ms ,per page,it will be an perfect match,if we somehow can achieve those kinds of results in an sort of mix up.

Unde 1 sec is good anyhow,but maybe mcl21us you can tell us the size page in MB? and results on First loading,and secondly,after the cache.....and on what cms.

Thanks!

**Comment by fevangelou** [comment]
I use Apache Benchmark for initial tests but using something like Siege would yield more accurate results. If of course you enable APC(u), optimize php.conf (provided you have PHP as FastCGI module), optimize MySQL (make sure you also use InnoDB) and finally optimize Apache, then you'd get the best difference (before and after).

**Comment by masteranalyze** [comment]
Do you remember if it was on joomla and what timmings you get ? On joomla?with varnish +nginx working togheter ?

Or with this new build,you don`t think is neccesarry anymore Varnish on an simple http website?I mean if engitron results are approaching engintron+varnish...

You used PHP FPM or just the normal FAST CGI Module?From reviews PHP FPM ,works even more better and fast.

The mariadb ,also it seems to me it`s working an little bit fast on joomla then mysql 5.6.x too.

**Comment by mcl21us** [comment]
Hi masteranalyze i am using fcgi+mariadb+engintron+mod_pagespeed this is my 
the site is a classified ads with high traffic, i also have google adsense and other http pool like fb and google.

I use pingdom to test the speed of my sites
  
my loading time
without GOOGLE/fb/g+ request --> Page size 1.8MB Load time 799s Requests 116
With GOOGLE/fb/g+ request --> Page size 1.8MB Load time 1.79s Requests 116


Test for Joomla site i hosted
www.englishbrid....
Tested from San Jose, California, USA on February 8 at 23:49:00
Page size
2.0MB
Load time
650ms
Requests
46
Perf. grade
70/100
Your website is faster than 95% of all tested websites

test for wordpress i hosted
http://www.providencetower...…
Tested from San Jose, California, USA on February 8 at 23:53:45
Page size
2.5MB
Load time
727ms
Requests
96
Perf. grade
79/100
Your website is faster than 94% of all tested websites

**Comment by masteranalyze** [comment]
Seems the results are more good on joomla then wp,but the wp website page is a bit larger then joomla.

That is wonderfull.

I guess without google/fb, the time is 799ms right ?not 799 seconds?

Under 1 second is the way to go,but i`m sure,we can get with some tweaks under 500ms.

I use mariadb too,i`m still waiting for an domain transfer to be made into my new server,then i will be able to run some tests as well.

About mariadb did you notice an speed up comparated to the mysql 5.6. x?!

Try gtmetrix.com as well,and see what results you get ,as in there it`s testing on first loading without no cache,and let us now the differences.

I will use Apcu+Opcache+Php FPM + Engitron +php 5.6 +joomla 3.xxx,without tweaks on mysql+apache,and i will let you know the results once i will be able to run the tests.

**Comment by mcl21us** [comment]
hi masteranalyze, result at the bottom for joomla site

I migrated to mariadb to handle more database process as i hosted also Piwik analytics and a  cargo system and inventory trucking that is more on database  process. When im using mysql 5.6 and when  the traffic get spike to the sites i hosted sometimes i get 403 or 503  error when a high load of traffic comes in even i tweak and optimize it a couple of times, but when i migrated to mariadb and optimize to handle large process and request  i never get those error, on db speed its depends on how you tweak your db server im also using query cache and memcache.

Report generated:
Mon, Feb 8, 2016, 9:03 AM -0800
Test Server Region:
 Vancouver, Canada
Using:
 Firefox (Desktop) 39.0.3, PageSpeed 1.12.16, YSlow 3.1.8
Looks like you might not be using a CDN
Why should I use a CDN? »
Performance Scores
PageSpeed Score
(84%) 
YSlow Score
(86%) 
Page Details
Page Load Time
857s 
Total Page Size
1.95MB 
Requests
45

**Comment by fevangelou** [comment]
MySQL caching makes a huge difference. See my guides ;)

As for Joomla vs WP, if you use the right caching in both, you can get amazing results with very cheap infrastructure. We're talking about being able to serves dozens of millions of pageviews per month with less than 200 USD/m.

**Comment by fevangelou** [comment]
Considering the topic resolved due to inactivity. If something changes, comment again and I'll re-open it.
