### ISSUE TITLE
Doing a custom "include" based on domain as the variable

### ISSUE THREAD

**Issue by penguinmaid44** [engintron/engintron#600]
What would be the correct syntax to include the wp-rocket default.conf file IF = TO "X" DOMAIN?  More like is there an way to do an include with a variable or a way to redirect a domain to a custom "insert?"

**Comment by fevangelou** [comment]
Don't do this. It can bring your server down if the WP site is hacked. See this: https://blog.tarq.io/root-your-box-with-w3tc-and-nginx/

Any redirects you want done, either prefer .htaccess rules or use Engintron's "custom rules" file.
