### ISSUE TITLE
Subdomain functional however on engintron once cloudflare is added website breaks.

### ISSUE THREAD

**Issue by Kjramey** [engintron/engintron#601]
I have the main domain on both CloudFlare and Engintron no issues.
However, the sub domain refuses to function likewise. I can only run on either engintron or cloudflare separately.  I have made all ( within my knowledge ) the necessary addition to the rules for the shared IP ( used by the subdomain ).
 
 Any ideas regarding other causes. All dns entries have been replicated on cloudflare for both domains. 
Ideas are appreciated thanks 

I am on the latest build.

**Comment by Kjramey** [comment]
Status remains subdomain continues to break with both services enabled. I am currently running on only Engintron. These domains concerned are all part of the shared ip, which seems to be functioning normally. 
Any ideas any one ?

**Comment by fevangelou** [comment]
What did you add in your "custom rules" option in Engintron?

**Comment by Kjramey** [comment]
set $PROXY_DOMAIN_OR_IP "Shared IP";

As required as well as other static IPs

Do you need all?

**Comment by fevangelou** [comment]
If the syntax or command order is wrong, then this may be the problem.

Paste back you entire config and swap the last part of each IP with XXX, YYY etc.

**Comment by Kjramey** [comment]
#####################################################################
# === Place your custom Nginx rules here ===
#
# [comments used below updated for Engintron v1.8.2]
#
# Some examples:
# - HTTP to HTTPS redirect when using CloudFlare
# - Setting up domains with dedicated IPs on the system
# - Any other global rule (redirect or process)
#
#####################################################################

# === FOR USE WITH CLOUDFLARE ===
# For up to date info see the Engintron wiki at: https://github.com/engintron/engintron/wiki
#
# a) If your server has a single shared IP ONLY and you wish to use CloudFlare for any (or all) of your sites
#    you will have to specify this shared IP address below otherwise you'll get errors from CloudFlare.
#    This change will simply tell Nginx to skip DNS resolving and simply forward traffic to the shared IP.
#    Uncomment the following line if all your sites on the shared (main) IP of your server are on CloudFlare:
#
set $PROXY_DOMAIN_OR_IP "192.ZZ.XX.YY"; # Use your cPanel's shared IP address here

# b) If you utilize CloudFlare on a cPanel server with BOTH a shared IP and dedicated IPs for domains, you will
#    have to set the IP ONLY for each such domain at the "WHEN TO SPECIFY A DOMAIN IP" section lower in this file.
#
# c) It is possible to force-redirect all your domains on CloudFlare to HTTPS if you have SSL enabled
#    in CloudFlare's "Crypto" settings page. Make sure you use "Flexible SSL" there so CloudFlare proxies
#    traffic from HTTPS to Nginx's HTTP port (80). This way you can utilize Nginx's caching & performance
#    benefits to the fullest. If you use "Strict SSL" in CloudFlare's "Crypto" settings page, then CloudFlare
#    will proxy all HTTPS requests to your Apache's HTTPS port (443) and therefore you will miss any benefits
#    from Nginx's caching & overall performance features.
#    To redirect to HTTPS, simply remove ONLY the FIRST # character from each line of the following block
#    and make sure you set the domains you DO NOT want to automatically redirect to HTTPS.
#
# # === Protocol redirect handling when using CloudFlare [start] ===
#
 set $redirToSSL "";
 if ($http_cf_visitor ~ '{"scheme":"http"}') {
set $redirToSSL "on";
 }
#
# # Set each domain you DO NOT want to automatically redirect to HTTPS when using CloudFlare only below
# # and repeat the process with additional "if" blocks for more domains
#
# if ($host ~ 'gadgets.useoftechnology.com') {
 #  set $redirToSSL "off";
#}
#if ($redirToSSL = "on") {
#return 301 https://$host$request_uri;
#}
#
# # === Protocol redirect handling when using CloudFlare [finish] ===



# === WHEN TO SPECIFY A DOMAIN IP ===
# By default, Nginx will redirect requests to the right domain IP by using DNS resolving.
# However there are cases where you want to specify an IP for use with Nginx:
# - When you use CloudFlare for certain domains only on your server,
#   regardless of whether these domains use the server's shared IP or a dedicated IP.
# - When you are working on a domain which does not yet (DNS) resolve to your server,
#   but you want to access it by modifying your computer's "hosts" file.
#
# To specify the domain IP in such cases, simply enter a domain or subdomain in an "if" block
# (as shown below) and inside that block set the appropriate shared or dedicated IP to point to.
#
# To specify the IP for a domain simply uncomment the following 3 lines and make sure you replace
# example.com with your actual domain or subdomain and also replace XXX.XXX.XXX.XXX with the actual
# IP assigned to that domain. To specify the IP for more domains, simply copy that "if" block
# (per domain) and change accordingly.
#
if ($host ~ "cookingwithnekeray.com") {
   set $PROXY_DOMAIN_OR_IP "149.56.XX.YYY";
}
if ($host ~ "onetechworld.com") {
   set $PROXY_DOMAIN_OR_IP "149.56.YY.XX";
}
if ($host ~ "justsmartliving.com") {
   set $PROXY_DOMAIN_OR_IP "192.95.YY.XX";
}
#if ($host ~ "useof.technology.com") {
#   set $PROXY_DOMAIN_OR_IP "192.168.YYY.XX";
#}

# === DOMAIN AND URL PATH EXCLUSIONS FROM CACHING ===
# If you wish to exclude certain domains, subdomains or even full URL paths from micro-caching and/or
# static file caching, simply specify them below and use a colon (|) character as a separator.
# Remember that if you specify a "naked" domain name, e.g. mynicedomain.com, every subdomain e.g.
# support.mynicedomain.com will also be excluded from caching. Decide wisely!
# If you wish to disable ONLY micro-caching, then comment the line "set $CACHE_BYPASS_FOR_STATIC".
# If you wish to disable ONLY static file caching, then comment the line "set $CACHE_BYPASS_FOR_DYNAMIC".
#
# Note: Don't include the "http://" portion of a URL.

#if ($host ~ "gadgets.useoftechnology.com") {
#set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
#set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
#}

**Comment by fevangelou** [comment]
Seems fine, but don't leave configuration that you don't use (e.g. set $redirToSSL "";...).

Make sure no .htaccess redirects break anything.

And be more specific as to the problems you have. If a site is inaccessible, what error code(s) do you see?

**Comment by Kjramey** [comment]
ok apologies thanks, 
regarding site it is fully accessible however i typically incorporate cloudflare on all my sites.  all stated sited are fine except gadgets.useoftechnology.com, when cloudflare is activated for this it breaks the site immediately, if i bypass engintron caching and activate cloudflare it functions with no issues. I have no    
.hta redirects for my sites. 
All sites are Https thus the SSL redirect.

what other information would be helpful to troubleshoot

**Comment by fevangelou** [comment]
The perhaps your Crypto settings in CF are wrongly set for this domain. If it's set to Flexible, the CF will request port 80 from your server. If there's an .htaccess redirect in place, you'll end up with a redirect loop. Verify all these work as CF works for other domains you have.

**Comment by Kjramey** [comment]
Thanks I'll check it out. and provide an update. 

Thanks again

**Comment by Kjramey** [comment]
Update Cloudflare Noted - 

The issue appears to be gadgets.useoftechnology.com is redirecting to www.gadgets.useoftechnology.com and there is no certificate to encrypt traffic for that website.

Cloudflare's SSL only covers one level of subdomains - *.useoftechnology.com & useoftechnology.com - and www.gadgets.useoftechnology.com is a second level sub domain.

The quickest way to resolve this is to stop gadgets.useoftechnology.com from redirecting and use gadgets.useoftechnology.com as the website address to serve your content from.


AKA My fault. thanks fevangelou

**Comment by fevangelou** [comment]
Thanks for letting me know.
