### ISSUE TITLE
Engintron not reading correct apache and executing php binary

### ISSUE THREAD

**Issue by codenamerana** [engintron/engintron#602]
I am running php selector (Cloudlinux ) instead of easyapache 4 and my apache conf file is different than what is mentioned in https_vhosts.php.

Also it is not executing correct php binary as i am using alt-php and not easyapache 4 php.

Is it safe to correct paths in https_vhosts.php ?

**Comment by fevangelou** [comment]
Yes, but they will be overwritten on subsequent updates. If you can send me the paths, I can add checks in the code for their existence. If these files do exist, the HTTPS vhost generator will use these instead.

**Comment by codenamerana** [comment]
Great, all fine now :)
