### ISSUE TITLE
Temporary timeout problem!

### ISSUE THREAD

**Issue by codenamerana** [engintron/engintron#603]
I am noticing a strange problem but not really sure whether it is because of engintron or not.

My site is using https and sometimes when i click on a link after being idle for 10 minutes, i see a timeout and suddenly the site again loads.

Modsecurity is set to log reports only (verbose mode) ---> OWASP.
CSF is installed!

What can be the problem ?

**Comment by fevangelou** [comment]
Could be many things. Is it a recurring pattern (after days of trying)?

**Comment by codenamerana** [comment]
Hmm no i uninstalled everything and then again installed. Its ok now.

Thanks :)

**Comment by fevangelou** [comment]
Cool.
