### ISSUE TITLE
Where to put this code?

### ISSUE THREAD

**Issue by IkenHuub** [engintron/engintron#604]
Hi,

Since you do it so differently I want to know where I do have to put the code mentioned under tip 5:
https://www.nginx.com/blog/9-tips-for-improving-wordpress-performance-with-nginx/

**Comment by fevangelou** [comment]
Nowhere, really. All this (and more, performance-wise) is already setup for you by Engintron.

**Comment by IkenHuub** [comment]
Hmm ok, sounds great.

So there is nothing more I need to do performance wise regarding Nginx and Wordpress ?

**Comment by fevangelou** [comment]
Nope :)
