### ISSUE TITLE
cgi-sys/defaultwebpage.cgi page after installing Engintron

### ISSUE THREAD

**Issue by tomidjx** [engintron/engintron#606]
I installed engintron on centos 7 with cpanel, followed the procedure, open ports as instructed on cfs firewall, open_basedir is disabled, everything seems ok but with engintron enabled I get the cgi-sys/defaultwebpage.cgi page when visiting a domain. The install has been done on a freshly rebuilt vps, so with no previous install of nginx plugins. With Engintron disabled everything works fine. VPS is in germany. I tried to reinstall from WHM engintron but didn't work. Tried to restart serveces with no result. Any advice would be much appreciated.  Thanks in advance

**Comment by tomidjx** [comment]
update: after several reinstall and recompile with easy apache 4, using "all php + op cache" as encouraged in the FAQ section. The result is a strange behaviour.  

I loaded 2 test site on this VPS, just to test if I can get Engintron working. 

If i try to load http://(any-url).com i will get the "cgi-sys/defaultwebpage.cgi", 
with https:// I will get the page loaded. (the site normally works without https, no cloudflare.)

Furthermore, if i reload the http version and refresh the page several times, occasionally it would load the page, let say 3 times out of 10. I tried to clear the cache, browser cache, always with the same result.

If I disable Engintron everything works fine, as usual.

Obviously, Engintron needs in my case some configuration, is not working out of the box.
Could somebody help?

thanks.

**Comment by fevangelou** [comment]
Have a look at the Engintron Wiki first: https://github.com/engintron/engintron/wiki

**Comment by tomidjx** [comment]
Sorry to bring this up, but i did have a look at the wiki doc and couldn't find a solution. I tried again many months later, to build another VPS, i tried with centos 6 and centos 7, with both I have exactly the same problem, when i enable engintron i get the cgi-sys/defaultwebpage.cgi page, if i refresh i get at random the cgi-sys/defaultwebpage.cgi or the website page.
Could anybody help? 
Thanks
