### ISSUE TITLE
HTTPD_CONF Change Detection in https_vhosts.php

### ISSUE THREAD

**Issue by bdtech** [engintron/engintron#607]
I see the shell script runs every ten seconds looping and initiates via cron every minute. Why not remove that loop and replace this

`define('HTTPD_CONF_LAST_CHANGED', 10); /* In seconds */`
`(filemtime(HTTPD_CONF) + HTTPD_CONF_LAST_CHANGED) > time())`

This seems more effective ...

`(filemtime(HTTPD_CONF) > (filemtime(NGINX_DEFAULT_HTTPS_VHOST))`

**Comment by fevangelou** [comment]
Because you're polling 2 files your way, while my way polls 1 file only. Plus, you don't really care when the Nginx file changed.

**Comment by bdtech** [comment]
Yes the Nginx file should Change always after the source (httpd) file changes. I have my cron running every five minutes now without looping :)

**Comment by fevangelou** [comment]
The loop is done so you get a 10 sec resolution for the cron job as by default cron jobs can only run at least every minute. There is no "second" resolution for cron jobs.

So if within these 10 secs a change in the Apache config is detected, the Nginx file is recreated.

I think you're confusing a few things...

Keep in mind that whenever you do a change in Nginx configs, delete cache/temp files so what you see is current and not cached.

**Comment by bdtech** [comment]
This causes a race condition on larger installs. I would recommend runnnig the cron each minute without looping.

**Comment by bdtech** [comment]
Cache TTL is set at one second? Why is this a concern to purge?

**Comment by bdtech** [comment]
HTTPS sites have delay from CA certificate issuance anyway. Running this every 10 seconds isn't necessary.

**Comment by fevangelou** [comment]
10 secs is a good-enough interval.

**Comment by brixly** [comment]
Both of you have very valid points I believe. 

Quick question - if the httpd.conf is rebuilt and the cron runs, but it hadn't rebuilt in the last 15 seconds then the purgecache isn't called at all?

An attempt at an example below...

00:01 /scripts/rebuildhttpdconf
00:10 [cron] https_vhosts.sh (change recognised < 15 seconds) = purgecache

Second Example...

00:01 /scripts/rebuildhttpdconf
00:45 [cron] https_vhosts.sh (change NOT recognised as > 15 seconds) = DO NOTHING

So - is this correct? That the second example will never purge the caches?

As such, does it mean we should simply increase HTTPD_CONF_LAST_CHANGED to something like 30 seconds or so?

**Comment by fevangelou** [comment]
No reason for cross-posting.
