### ISSUE TITLE
Nginx not logging bandwidth when there is a cache hit

### ISSUE THREAD

**Issue by josenobile** [engintron/engintron#608]
Hello, 

When the request reach Apache, the bandwith consume is log in /var/log/apache2/domlogs/example.org-bytes_log
However when the answer came only from nginx (x-nginx-cache-status: HIT) there is not log in bytes_log file. This mean that potentially a account can get unmetered bandwith if all content is served from nginx cache and not way to detect which account is consuming all the port capacity.

In a perfect cPanel integration this bug is a blocker (except for the companies  who are "all smoke and mirrors" with unlimited bandwith/transfer).

**Comment by fevangelou** [comment]
I doubt it'll get unmetered bandwidth... There is a 1 min internal cache for static files and a 1 sec micro cache for HTML/dynamic content. There will be a deviation from the recorded bandwidth consumption but we're talking about just a 10-15%.

**Comment by josenobile** [comment]
Hello, it is more for sites with 35 million daily hits / 1 TB daily.

**Comment by fevangelou** [comment]
First-world problems. Sorry man, but this is not an issue with Engintron.

**Comment by fevangelou** [comment]
Apache comes with a module for tracking bandwidth. Nginx doesn't by default.

You'll have to figure out a different method to do b/w tracking or simply don't sweat about it unless it costs you real money.

**Comment by josenobile** [comment]
Hello, 

Is there a way to log bandwith when the request is served from cache?

Or just mention this bug in the documentation: "Nginx will not log bandwith when the request is served from cache"

**Comment by fevangelou** [comment]
Again, it's not a bug. It's how things work with Nginx.

One solution could be utilizing Munin for vhost b/w tracking in Nginx. Engintron already sets up Nginx with Munin if you have it installed already. If you don't have Munin installed via cPanel plugins, install it, then re-install Engintron.

There's a plugin to track vhost b/w in Munin for Nginx: https://github.com/joanpc/nginx_vhost_traffic

**Comment by josenobile** [comment]
Hello, 

The requeriment is not just log bandwith in any place, is log bandwith in cPanel log files in order to apply the bandwith limits defined in WHM.
Regard to bandwith log in Apache there is this config:

<IfModule mod_log_config.c>
    <IfModule logio_module>
        LogFormat "%v %{%s}t %I .\n%v %{%s}t %O ." bytesvhost
        CustomLog "|/usr/local/cpanel/bin/splitlogs --main=server3.hostingfacil.co --suffix=-bytes_log --buffer=no --sslport=8443" bytesvhost
    </IfModule>
</IfModule>

cPanel have enabled Piped Log. It sends the logs to a binary. I need to do it with nginx only for request served from cache.

**Comment by fevangelou** [comment]
I've already given you a possible solution.

**Comment by josenobile** [comment]
It is not a solution to log the bandwith in the cPanel defined files:  /var/log/apache2/domlogs/example.org-bytes_log
