### ISSUE TITLE
Can I use rocket-nginx with Engintron ?

### ISSUE THREAD

**Issue by IkenHuub** [engintron/engintron#609]
Can I use rocket-nginx with Engintron ?

**Rocket-Nginx**

Rocket-Nginx is a Nginx configuration for the WordPress cache plugin WP-Rocket. It enables Nginx to serve directly previously cached files without calling WordPress or any PHP. It also adds headers to cache CSS, JS and medias in order to leverage browser's cache by reducing request to your web server.

See: https://github.com/maximejobin/rocket-nginx

**Comment by fevangelou** [comment]
Nginx, as set up by Engintron, already does client-side (browser) caching for static assets. However configuring Rocket-Nginx to serve cached HTML via Nginx will not really work properly. In fact, it will probably break the functionality for everything else. The right way is to use .htaccess rules so Apache does not invoke PHP if a static HTML copy is found. The result in terms of performance will be great. So Nginx proxies traffic to Apache and then Apache checks whether a cached copy of the URL requested exists already. If it does, it serves this cached file.

**Comment by efelinto** [comment]
@fevangelou , how can I configure this in Engintron? 
And is there an explanation why you do not activate it by default or provide a way to activate it easily?

**Comment by fevangelou** [comment]
You can't.

**Comment by efelinto** [comment]
Why not ?

**Comment by lukapaunovic** [comment]
Here's how.

First install rocket-nginx.

```
cd /etc/nginx
git clone https://github.com/satellitewp/rocket-nginx.git
cd rocket-nginx
cp rocket-nginx.ini.disabled rocket-nginx.ini
php rocket-parser.php

```

Edit **/etc/nginx/utilities/https_vhosts.php**

Before 

`include common_https.conf;`

add

`include rocket-nginx/conf.d/default.conf;`

Restart
