### ISSUE TITLE
MIME problem Engintron

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#610]
I have a problem with loading the JS, login system do not work either, only resolves by disabling Engintron.

 www.hidroservdesentupidora.com.br/sig

Error log:

Refused to execute script from 'http://hidroservdesentupidora.com.br/sig/js/jquery-1.9.0.min.js' because its MIME type ('application/x-httpd-php') is not executable, and strict MIME type checking is enabled.

**Comment by fevangelou** [comment]
Engintron does not change the MIME type for JS. That would a) be stupid and b) break every site already.

Look in .htaccess files.
