### ISSUE TITLE
Engintron  is not removed from WHM Dashboard

### ISSUE THREAD

**Issue by sshcli** [engintron/engintron#611]
**Steps to reproduce the issue**
Run this command as root: /engintron.sh remove

**Actual result**
Engintron for Cpanel/WHM is not removed from plugins section in WHM Dashboard

**Expected result**
Engintron for Cpanel/WHM should be removed from plugins section in WHM Dashboard

**Comment by fevangelou** [comment]
Reload WHM.

**Comment by sshcli** [comment]
Please help,
Please tell me if I'm missing a step or if there is a compatibility problem.

I tried to install Engintron twice in my production site, no success.

I have used this command to install it:
`cd /; rm -f engintron.sh; wget --no-check-certificate https://raw.githubusercontent.com/engintron/engintron/master/engintron.sh; bash engintron.sh install
`

I have used this command to uninstall it after fail:
`/engintron.sh remove`

I have enabled the ports in csf as mentioned here:
https://github.com/engintron/engintron/wiki/Restrict-access-to-ports-8080-&-8443-used-by-Apache-only-for-Nginx

I have disabled open_basedir protection as mentioned here:
https://github.com/engintron/engintron/wiki/Requirements

I don't have another nginx plugin installed.

I have these packages installed in my server:

Apache 2.4
config
config-runtime
mod_asis
mod_auth_digest
mod_authn_anon
mod_authn_dbd
mod_authn_dbm
mod_authn_socache
mod_authnz_ldap
mod_bwlimited
mod_cache
mod_cgid
mod_dbd
mod_deflate
mod_expires
mod_headers
mod_ldap
mod_mpm_event
mod_proxy
mod_proxy_fcgi
mod_proxy_http
mod_security2
mod_ssl
mod_suexec
mod_suphp
mod_unique_id
tools

PHP 5.6
build
libc-client
pear
php-bcmath
php-bz2
php-calendar
php-cli
php-common
php-curl
php-dba
php-devel
php-enchant
php-exif
php-fileinfo
php-fpm
php-ftp
php-gd
php-gettext
php-gmp
php-iconv
php-imap
php-intl
php-ioncube
php-ldap
php-litespeed
php-mbstring
php-mcrypt
php-mysqlnd
php-odbc
php-opcache
php-pdo
php-pgsql
php-posix
php-process
php-pspell
php-snmp
php-soap
php-sockets
php-tidy
php-xml
php-xmlrpc
php-zip
runtime

PHP 7.1
build
libc-client
libc-client-devel
pear
php-bcmath
php-bz2
php-calendar
php-cli
php-common
php-curl
php-dba
php-dbg
php-devel
php-enchant
php-exif
php-fileinfo
php-fpm
php-ftp
php-gd
php-gettext
php-gmp
php-iconv
php-imap
php-intl
php-ldap
php-litespeed
php-mbstring
php-mcrypt
php-mysqlnd
php-odbc
php-opcache
php-pdo
php-pgsql
php-posix
php-process
php-pspell
php-snmp
php-soap
php-sockets
php-tidy
php-xml
php-xmlrpc
php-zip
runtime

Others
apr
apr-util
apr-util-ldap
cpanel-tools
documentroot
libcurl
libmcrypt
libnghttp2
libtidy
modsec-sdbm-util
nghttp2
php-cli
php-cli-lsphp
profiles-cpanel 

This is the error I get in chrome:
<img width="205" alt="error" src="https://user-images.githubusercontent.com/12942731/29051370-2be076cc-7bb0-11e7-96ed-dbb395d50778.PNG">
