### ISSUE TITLE
AutoSSL - Not reload new SSL

### ISSUE THREAD

**Issue by faca5** [engintron/engintron#612]
Hello.

AutoSSL created new SSL certificate for domain name exp. example.com.

We have visited https://www.example.com/ but SSL not loaded.

We have manually "reload", "nginx" and now SSL start working. 

Do you have any solution for automatically reload nginx when SSL certificates has been installed using AutoSSL?

Thank you!

**Comment by Shadowized** [comment]
my solution is to have a custom script that restarts everything after checking for new certs, pretty simple.

```
#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# cpanel autossl check
/usr/local/cpanel/bin/autossl_check --all

# update engintron vhost config
php /etc/nginx/utilities/https_vhosts.php

# restart apache and nginx
/usr/local/cpanel/scripts/restartsrv_httpd
service nginx restart
```

**Comment by faca5** [comment]
Cool!

**Comment by Shadowized** [comment]
I should also mention that the latest engintron versions should do auto-restart with that one http-generator cronjob that runs every minute
`* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1`
or at the very least they are supposed to upon detecting changes. I think somebody even wrote a patch for that https_vhosts file as well, so you've got some options.

**Comment by faca5** [comment]
Hello.

Good! We can set time (exp. each 1 hour, 24 hours...)

Can we set restart or reload? nginx need just reload new SSL and not restart.

**Comment by Shadowized** [comment]
yeah either way works, I believe that line in https_vhosts with the purgecache does that anyway.

**Comment by wowdancing** [comment]
Hi.
I have the same problem. Where do I place the script you wrote?

Thanks.
