### ISSUE TITLE
Document root not working on SSL?

### ISSUE THREAD

**Issue by blauwhelm** [engintron/engintron#613]
Hi,

I'm new to Engintron. After installing, all my sites seem to work fine, except 2 sites from which I modified the Document root via /var/cpanel/userdata/USERNAME/DOMAIN.COM, before installing Engintron. When going to the http version everything is fine, but when going to the https version I land at the wrong folder and the site won't function correctly. This is a Document root problem as far as I can tell. Any idea why this i happening? Thanks!

Jan

**Comment by SatishGandham** [comment]
Same problem !!

**Comment by fevangelou** [comment]
The Apache config file generated by cPanel probably does not see these changes. Nginx does not use the document root. It doesn't need to when proxying traffic. The problem is in Apache.

**Comment by SwiftThemes** [comment]
No, it was seeing the document root. It worked after deleting the nginx default document root.
I installed nginx before enhintron, default files from it were present.

**Comment by fevangelou** [comment]
You should have uninstalled the old copy of Nginx first and removed its
files under /etc/nginx.

**Comment by blauwhelm** [comment]
New sites with document root that I added do work with SSL. For me this is resolved now.
