### ISSUE TITLE
Performance (caching) with Engintron

### ISSUE THREAD

**Issue by blauwhelm** [engintron/engintron#614]
Hi,

The reason I installed Engintron is to work with Varnish in combination with Nginx and multiple SSL certificates for multiple domains. It's awesome that Engintron automatically generates the correct config files, so that SSL is correctly handled by Nginx! 

I know that Varnish isn't supported directly and that the performance upgrade should be negligible, but I don't see this currently in my configuration. I used Varnish previously for full-page caching and this gives a very large (5 - 20 times) faster loading speed upgrade in comparison to my current setup. Is there a way to use full-page caching with Engintron or something similar to gain a more significant performance upgrade?

Thanks again!
Jan

**Comment by fevangelou** [comment]
a) You don't need Varnish. It will significantly complicate things.
b) You can increase the dynamic cache time from 1 second (1s) to minutes. The result will be full page caching, both server and client side. That's why you don't need Varnish.

**Comment by blauwhelm** [comment]
Ok, thanks for your response. I'll tinker with the dynamic caching then.
