### ISSUE TITLE
cakephp random csrf cookie missing /csrf token Mismatch error

### ISSUE THREAD

**Issue by StreetJammer** [engintron/engintron#616]
On my cakephp site its throwing these errors randomly , if i disable engintron it works properly 

CSRF token mismatch
Missing CSRF token cookie

How do i fix this ? any idea ? 

And where to put these server directives mentioned here 

 https://book.cakephp.org/3.0/en/installation.html#nginx

**Comment by fevangelou** [comment]
Cookies are stripped for static files. I hope CakePHP doesn't use cookies for such files. Perhaps it's also related to dynamic (micro) caching. You can disable that entirely or for a specific site. See the wiki for more info.
