### ISSUE TITLE
SSL Cert mismatch

### ISSUE THREAD

**Issue by Islandhosting** [engintron/engintron#617]
Brand new cPanel 66.0.13 server with Engintron 1.8.4, AutoSSL with Let's Encrypt.  Trying Engintron out for the first time.

SSL works fine when Engintron is disabled, but when enabled I get a certificate mismatch.  It's getting the server's cPanel certificate, not the AutoSSL cert for the domain I'm trying to access.

Purging the cache makes no difference.

**Comment by fevangelou** [comment]
Since this is a new server, perhaps the LE certificate failed to issue. Make sure it's active on Apache.
