### ISSUE TITLE
custom rules and cloudflare...

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#619]
Hi,

What to do when only one domain is on cloudflare?

I only see explanation for all and how to make exceptions... but I have many domains and only one on cloudflare.

**Comment by tux-tn** [comment]
Hello @Friends4U 
You just need to use the same rule in your ```custom_rules``` file. For example:
```nginx
if ($host ~ "example.com") {
    set $PROXY_DOMAIN_OR_IP "X.X.X.X";
}
```
and of course the X.X.X.X should be replaced by your domain ip
