### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by frilogg** [engintron/engintron#62]
Now I at least got it two work after the the alst update in Centos 7.2. but now I get "502 Bad Gateway"

**Comment by fevangelou** [comment]
Cleanup the Nginx cache/temp folders and restart both Apache & Nginx in
that order.

Open up port 8080 for Apache so you can troubleshoot if something's wrong
with Apache, e.g. broken php script.

Finally check the error log from within Engintron in WHM for any hints. You
can easily adjust the number of lines to fetch, you are not limited to just
100 as the default option is.

**Comment by frilogg** [comment]
Did it yesterday. I will give it a new try to day in one hour at midnight Norwegian time.  The port is open that was the first thing I did of course. And the error shows the same. access denied...

**Comment by fevangelou** [comment]
The logs should indicate something. If you use v1.5.2, you could also re-install via WHM and then grab the installation log and paste it here so I can check it for any errors.

**Comment by frilogg** [comment]
I now tried again.  Still same error. 502 Bad Gateway so there must be something that we are mising..
The error.log only show errors like : 

[error] 28639#0: *357 connect() failed
 (111: Connection refused) while connecting to upstream, client: 80.69.225.169, 

After installation at the end it says

=== Restarting Apache & Nginx... ===
Redirecting to /bin/systemctl restart  httpd.service
Job for httpd.service failed because the control process exited with error code. See "systemctl status httpd.service" and "journalctl -xe" for details.
Redirecting to /bin/systemctl start  nginx.service

Seems that Nginx starts but Apache doesnt want to start again?!

**Comment by frilogg** [comment]
So I now figured out that apache is not restarting du to 

=== Switch Apache to port 8080 ===

=== Distill changes in Apache's configuration and restart Apache ===
Distilled successfully
Initial configuration generation failed with the following message:

Configuration problem detected on line 3 of file /usr/local/apache/conf/includes/remoteip.conf:	RemoteIP: Error parsing IP peer (Name or service not known error) for RemoteIPInternalProxy

**Comment by fevangelou** [comment]
I've extensively tested CentOS 7 and did not have any issues with installing mod_remoteip.

You can manually fix it though. First, can you please paste back here the contents of the file  /usr/local/apache/conf/includes/remoteip.conf

Additionally, how many IPs does your server control?

**Comment by InteractM** [comment]
IMO you need to be on Apache 2.4 to have mod_remoteip to working properly.

**Comment by frilogg** [comment]
Ofc. Im on Apache 2.4

**Comment by fevangelou** [comment]
Have you resolved this?

**Comment by InteractM** [comment]
I have similar issue but with different situation. I have used your installation script on a development box, which has different IPs from productions sites. When I try to use modified host file on a local computer to point particular domain to the IP of a dev server it returns 502 Bad Gateway with ngnix error which looks like

`2016/02/11 13:09:29 [error] 27871#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: localhost, request: "GET / HTTP/1.1", upstream: "http://69.176.101.67:8080/", host: "www.childrensmedgroup.com"`

Any clue why ngnix is getting live site IP instead domain name in the URL?

**Comment by frilogg** [comment]
I have resolved my problem. After installation I had to run easy Apache 3 once more then everything worked. Now Im just strugling with 504 Gateway Time-out, but that is a issue not related to this issue

**Comment by fevangelou** [comment]
504 means that the backend takes too long to respond. I hope you're already using v1.5.2 of Engintron. If you don't, simply install it on top of any older release. Then check the file "nginx.conf" via WHM > Plugins > Engintron. In this file, in lines 13 & 14 we have the same 20s value. If you already have 20s and you still get 504 errors, increase it progressively to 30s or 40s. Re-check to see if you still get 504 errors.

**Comment by JorgeMarcelino-HS** [comment]
I also have the same problem: "502 Bad Gateway"

**Comment by fevangelou** [comment]
@frilogg & @JorgeMarcelino-HS First clarify whether you previously had any other plugins for Nginx on cPanel installed on your server. Secondly, provide snapshots from your Nginx error.log. It's impossible otherwise to know for sure why such an error occurs. 502 errors in proxy mode should not occur to my understanding. 500 and 504 yes, but not 502.

**Comment by JorgeMarcelino-HS** [comment]
@fevangelou I already used NGINXCP and I did not have that problem. It only seems to occur in static pages, maintenance pages etc...

**Comment by fevangelou** [comment]
Uninstall Nginxcp first. That's the problem you have. See the wiki for instructions.

**Comment by wgnsa** [comment]
##### Edit proxy_params_common ######    LINE 11 ####

proxy_pass          http://$PROXY_DOMAIN_OR_IP:$PROXY_TO_PORT;

###### if nat then make sure but your static internal ip $PROXY_DOMAIN_OR_IP  ######## 
proxy_pass          http://192.168.1.200:$PROXY_TO_PORT;

**Comment by ercelyildiz** [comment]
wgnsa; I solved the problem with my brother. thank you :)

**Comment by Tomicapo** [comment]
Hi. I managed to make this work for my main shared IP on an Amazon AWS EC2 instance after hardcoding the main IP like this:
Edit proxy_params_common # LINE 11
from => proxy_pass http://$PROXY_DOMAIN_OR_IP:$PROXY_TO_PORT;
to= > proxy_pass http://[MY SERVER'S PRIVATE IP]:$PROXY_TO_PORT;

The problem is, I have many more IPs for other domains that have dedicated IP. And when I try to browse those domains, I get a "nice" cPanel SORRY! error. If I hardcode that domains IP, it works great, but then I break all the other domains on my main IP.

Any ideas on how to make this dynamic? Or fix it in any way?
