### ISSUE TITLE
FASTCGI

### ISSUE THREAD

**Issue by bitsavvy** [engintron/engintron#620]
Hi there,

In the Beyond Engintron: Optimizing PHP FastCGI tutorial you state that "After you edit this file, it is VERY IMPORTANT that you "merge" these changes with cPanel so they don't get reset to the defaults when Apache's configuration is updated."

Could you possibly indicate what is needed to accomplish this as I am unsure.

Kind regards
Francois Wessels

**Comment by fevangelou** [comment]
Merging means making the changes permanent for Apache. If you follow the rest of the articles, it explains how to do it (3 commands in the terminal).

However this tutorial is about cPanel servers with EasyApache 3. The newest EasyApache 4 has a different format, so you shouldn't really bother with it. I've updated the wiki article to specify that the guide is for EasyApache.
