### ISSUE TITLE
httpd not starting after update to FASTCGI

### ISSUE THREAD

**Issue by bitsavvy** [engintron/engintron#621]
Hi there, we get the below error when trying to implement FastCGi as per https://github.com/engintron/engintron/wiki/Beyond-Engintron:-Optimizing-PHP-FastCGI

Would it be possible for you to assist?

Kind regards
Francois Wessels

=============================

`Restarting Apache...
Waiting for “httpd” to start ………Gracefully Terminating processes: nginx           with pids 5221 and owner root.......waited 1 second(s) for 1 process(es) to terminate....Done
……failed.

Service Error
	(XID a7ndpc) The “httpd” service failed to start.

Startup Log
	httpd: Syntax error on line 228 of /etc/apache2/conf/httpd.conf: Syntax error on line 13 of /etc/apache2/conf.d/php.conf: Cannot load modules/mod_fcgid.so into server: /etc/apache2/modules/mod_fcgid.so: cannot open shared object file: No such file or directory

===============================

**Comment by fevangelou** [comment]
The error is there for you and it's in Apache. Totally unrelated to Engintron or Nginx. Consult cPanel via their ticket system.
