### ISSUE TITLE
some noob questions about star running engintron

### ISSUE THREAD

**Issue by cocodrino** [engintron/engintron#622]
Hello..good day...I'm reading about engintron, the setup looks pretty simple but I'm a bit afraid about how is the integration with the whm:  I've several sites right now using apache, I'd like change one of them for use nginx...how is the process for replace an apache site for nginx...

thank you so much, hope you can give me a more clear idea about this...thank you!!!

**Comment by tux-tn** [comment]
Hello @cocodrino ,
You can't enable nginx for only one website. Engintron will let nginx control 80/443 ports and change Apache config to listen on 8080/8443, since 80/443 are default ports for HTTP/HTTPS, all your connections will go through nginx.
You can only disable caching for specific website using engintron ```custom_rules```

**Comment by cocodrino** [comment]
ok @tux-tn now I can understand better this, nginx act as a proxy so the whole traffic pass through nginx and then apache...would be possible then skip than pass through apache: I'm installing nextcloud (owncloud simil) and seems than it has some problems with apache and works better with nginx, so I'd prefer use nginx as server...

sorry for the noobs question but I'm a bit unfamiliar with these setups...thank you!!!

**Comment by fevangelou** [comment]
Nextcloud may work better with Nginx (as every other site of course) compared to Apache, but you can't ditch Apache in cPanel. Just install Engintron and the performance will be better than if you just had Apache only.
