### ISSUE TITLE
cPanel 66.x

### ISSUE THREAD

**Issue by rapidcloubr** [engintron/engintron#624]
Hello,

I wonder if Engintron is working correctly in the new version 66.0 of cPanel.

Thank you.

**Comment by rapidcloubr** [comment]
In my tests ENGINTRON is not working correctly on cPanel 66.x.

**Comment by jhawkins002** [comment]
@rapidcloubr Can you elaborate?

**Comment by rapidcloubr** [comment]
When installing NGINX in cPanel version 66.x, sites are only loading. They do not display.

**Comment by django554** [comment]
Same here, connection is refused.

**Comment by rapidcloubr** [comment]
@django554 Exactly, the loading has become slow, sometimes the pages can not open.

**Comment by WebSavvyGuy** [comment]
i had noticed the slowness also along with a couple bugs. (which forced me to uninstall it)  Hope this can be fixed soon.

**Comment by rapidcloubr** [comment]
Yes, that's a problem.

I was running ENGINTRON on more than 20 servers. We have done a great job to readjust everything.

We look forward to an update.

**Comment by amin0181** [comment]
hi
i want install ngnix on my cpanel server
but get error : [root@cpanel publicnginx]# ./nginxinstaller install
access key doesn't exist
go to WHM > Cluster/Remote Access > Setup Remote Access Key
and click on the Generate New Key button
when search about this realize i must do this : 
go to WHM > Cluster/Remote Access > Setup Remote Access Key
and click on the Generate New Key button
but in new version (v 66 ) just have Configuration Cluster and 
DNS Cluster

**Comment by fevangelou** [comment]
@amin0181 Seriously? The plugin you mention is not Engintron. Furthermore, why the heck are you posting on another topic?

@rapidcloubr It works just fine. Why shouldn't it? Nginx is a standalone service. It just works. If performance was degraded, it's probably related to Apache or other internal changes related to PHP. The upgrade to v66 has been problematic for many. I can only assume cPanel know this and should release updates soon.

**Comment by WebSavvyGuy** [comment]
@fevangelou

I think all of these issues might be related to that new htaccess feature WHM has and were all blaming engintron (assuming you are 100% sure its unrelated)

Thanks for your efforts

**Comment by kotsias** [comment]
Hi, if anyone has issues in version 66 with rewrites etc. Then the solution is to change the new option (includes in 66) in Service Configuration > Apache Configuration > Global Configuration --> Optimize .htaccess dropdown to "Search"/" and below (No optimization, Search Full Path)". In version 66 the default value is the third choice "Search Home Directory...etc" and this is issue for url rewrites (especially in wordpress). For me after update to v66 this fix a lot of issues. Thanks

**Comment by WebSavvyGuy** [comment]
I have been told by a CPanel tech that "Yes, Engintron affects the Apache configuration templates. "

I would advise into looking into that if you have any further issues.
