### ISSUE TITLE
wordpress user ip bug - resolved [bug]

### ISSUE THREAD

**Issue by lawrenceamer** [engintron/engintron#625]
After using alot of whm nginx plugins , i have discovered that when proxy mode is on , the real ip of users who try to comment on wordpress or use wordpress as registered users resolve to ip of dedicated server , in case the wordpress is installed in dedicated server , in this case all users ip resolve into ip address of dedicated server , this bug affects all plugins that use proxy mode to use nginx with apache, so i have pushed a wordpress plugin + code to explain more how to fix it easily , for more information about it just explore the code and installed the plugin 
https://secploit.com/view/218ec6e4

thanks 
Lawrence Amer

**Comment by jhawkins002** [comment]
Engintron patches for this fyi. If it doesn't work out of the box, you can use the 'Restore NGINX IP forwarding in Apache' link in the WHM plugin to land the appropriate configuration patch.
