### ISSUE TITLE
https_vhosts.php ignoring virtualhosts when multiples ServerAlias exist

### ISSUE THREAD

**Issue by ie39fk3jd** [engintron/engintron#627]
I have some customers with > 20 parked domains (aliases) and cPanel adds them as multiple ServerAlias lines. The script https_vhosts.php  doesn't expect more than 1 ServerAlias per VirtualHost.

**Comment by fevangelou** [comment]
Thank you for letting me know. I'll update the script and support this as well.

**Comment by jhawkins002** [comment]
We just experienced this as well! Here is direct feedback from cPanel support:

> ... this behavior is intentional and it has been around for a while.  Essentially, when the ServerAlias line reaches 8192 characters in length.  The 8192nd character will get read as a separate newline which in turn will cause apache to fail to start due to a configuration error.  Due to this, I found that we split the ServerAlias into multiple lines once its length reaches 4096 characters or more to be safe.  

I think they must have recently updated this practice, however, as our ServerAlias blocks are being broken up at character limits much fewer than 4096. 

In any event - if you need a work-around until a formal Engintron patch lands, and you are certain the combined length of your ServerAlias blocks will not exceed 8192 characters, you can create a custom Vhost template to remove the cPanel's ServerAlias character-size checks for your affected domain(s). 

Information on how to do this can be found at: https://documentation.cpanel.net/display/EA/Custom+Templates

The relevant code to excise should be located towards the top of the template:
`[% IF vhost.serveralias_array.size -%]`
`[% FOREACH alias IN vhost.serveralias_array -%]`
 ` ServerAlias [% alias %]`
`[% END -%]`

**Comment by ie39fk3jd** [comment]
I used the [patch made by dariofg](https://github.com/engintron/engintron/pull/511/files#diff-f0148a3ed308f9167587390f206099b6) and it worked perfectly.

**Comment by ie39fk3jd** [comment]
Sorry, I mean, the file https_vhosts.php
