### ISSUE TITLE
Blank Page on Edit custom rules

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#628]
I recently upgraded to WHM 66.0.14 and i noticed that when i click "Edit your custom_rules for Nginx" it just has a blank black screen.

Its trying to load something but doesn't load it and stalls.

This along with some recent weird server activity.  (Sometimes webpages will load very slow and other times very fast) Kind of intermittent.

Not sure if all this is a coincidence but one thing for sure is once i disabled Engintron everything became fast again.

This only started happening after updating WHM automatically (yes i restarted the server)

Any suggestions here?    I think I might try a reinstall.

**Comment by WebSavvyGuy** [comment]
Big mistake.  Pressed the install button and it just stalled.  Ended up breaking something as all our pages went Cpanel 404 (i guess it defaulted to Apache and Apache broke or something)

We got an admin to fix it but that was scary for a while.   Now upon reinstalling it, seeing 1000 Error from Cloudflare so reverted back to Apache alone.

Still want to get this back up and running but the original issue of blank custom rules page is concerning and so are those 1000 Cloudflare issues.

**Comment by fevangelou** [comment]
No issue on any of the servers I manage which have been upgraded to cPanel v66. If you see a blank page, as you say, the file was probably emptied. Which means if YOU didn't do it, someone else did. The CloudFlare issue is clearly documented in the Wiki. You should have your IP set in the custom rules. You don't because it's empty. And that's why CloudFlare failed.

**Comment by WebSavvyGuy** [comment]
Noone has access to my server except myself.

My words blank might be a little inaccurate.   I think it just wasnt loading (which could be a connection issue)

**Comment by fevangelou** [comment]
So why be quick and blame the plugin before examining the problem in detail?

**Comment by WebSavvyGuy** [comment]
yes that was a mistake on my part.

I just thought it was incompatible with the new update.

**Comment by WebSavvyGuy** [comment]
Of course this is all looking back after a few days

If something was updated in WHM and suddenly the rules werent loading, you probably would have blamed engintron also.

**Comment by fevangelou** [comment]
Not really. A blank file means someone deleted its contents. And this was causing the issues with CloudFlare. If noone else has access to the server but you, well...

**Comment by WebSavvyGuy** [comment]
Again, wasn't loading (thus a black screen).

Anyways after a few days passed now and realized any number of things to cause that.   The fact that when i tried to even disable it and it was stalling on load probably means this was all a connection issue.

When the dust has settled and Cpanel fixes their bugs ill get engintron back in there.
