### ISSUE TITLE
NGINX Fails with SSL-related error, will not restart until rebuilt

### ISSUE THREAD

**Issue by jhawkins002** [engintron/engintron#629]
This weekend we had an issue whereby our NGINX instance failed and cPanel's service auto-restart attempts also failed. Logs show the following error:

```
Aug 26 07:57:27 systemd[1]: Starting nginx - high performance web server...
Aug 26 07:57:27 nginx[100530]: nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/cpanel/ssl/installed/keys/c85fb_d83f9_2778bdc7b5af240a983feeb3391ef131.key") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/installed/keys/c85fb_d83f9_2778bdc7b5af240a983feeb3391ef131.key','r') error:20074002:BIO routines:FILE_CTRL:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)
Aug 26 07:57:27 nginx[100530]: nginx: configuration file /etc/nginx/nginx.conf test failed
```

Once a client made us aware of the issue we attempted to resolve the problem by purging the cache, etc. but ultimately only the reinstall allowed us to bring NGINX back online.

This is not the first time this has happened. This week we will probably deploy a CRON that checks to make sure the service is up every few minutes - if it is not, attempt to bring it back online - and if that fails automatically run the re-install script. 

Side note: we are increasingly relying on custom scripts to work around bugs or oddities - and there is little dialog from the team here on Github to get to the bottom of issues, particularly SSL  related ones. : (

**Comment by fevangelou** [comment]
The "team" is one person. And the project is open source. Be my guest and contribute. As for the issue, as the error indicates, Nginx was reading a reference to an SSL certificate that did not actually exist. Did someone edit the Apache file manually? Nginx is only mirroring Apache's configuration, so if the latter is broken, Nginx will break as well. Simple, really.

**Comment by etechwebcomm** [comment]
Hi there! No manual edits occur. It usually happens around 3 or 4am so I suspect it happens as cPanel/AutoSSL are wrapping up update runs. 

Re: contribution - of course! We are trying to participate by reporting items we encounter and sharing script tidbits that we find beneficial as work-arounds - as we have them. If we get to the point of feeling comfortable enough that our "hacks" are of reliable enough quality to submit to the core product we will definitely check them in. As it stands presently we have no real way to confirm if elements we encounter are specific to us or are global issues.

**Comment by jhawkins002** [comment]
Hi there! No manual edits occur. It usually happens around 3 or 4am so I suspect it happens as cPanel/AutoSSL are wrapping up update runs.

Re: contribution - of course! We are trying to participate by reporting items we encounter and sharing script tidbits that we find beneficial as work-arounds - as we have them. If we get to the point of feeling comfortable enough that our "hacks" are of reliable enough quality to submit to the core product we will definitely check them in. As it stands presently we have no real way to confirm if elements we encounter are specific to us or are global issues.

**Comment by fevangelou** [comment]
Then why not request help from cPanel? They may be able to detect what the heck is wrong with Apache far better than I can over GitHub issues.

**Comment by fevangelou** [comment]
Then why not request help from cPanel? They may be able to detect what the heck is wrong with Apache far better than I can over GitHub issues as they get to access your server (I can't).

**Comment by jhawkins002** [comment]
Prior to submitting this item we did - and they directed us here as core services were working as intended and the issue was pertinent to a third party plugin.

We now have a work-around CRON script in place to verify NGINX is stable, so Im going to close this issue. Our intent is to be constructive participants in projects and I fear our dialog may be going a little beyond that.
