### ISSUE TITLE
After installation Sites Doesnt Work

### ISSUE THREAD

**Issue by Brijendrasial** [engintron/engintron#632]
Hello,

I am installing it on cpanel easyapache4 and after installation the site doesnt work. May I know what could be the cause of it.

**Comment by rapidcloubr** [comment]
Try restarting Apache & NGINX. Sometimes when I do a new installation I have to do this procedure.

**Comment by Brijendrasial** [comment]
Did everything but that doesnt make it work.

**Comment by rapidcloubr** [comment]
When you check the status of NGINX what is returned?

**Comment by Brijendrasial** [comment]
Everything is showing normal dont know why its not working.

**Comment by rapidcloubr** [comment]
root@chserver1 [~]# service nginx status
nginx (pid  534785) is running...
root@chserver1 [~]#

When you query the status it returns executing?

**Comment by Brijendrasial** [comment]
yes

**Comment by rapidcloubr** [comment]
Do you have any firewall running? Have you checked whether ports 8080 and 8443 are open?

**Comment by Brijendrasial** [comment]
Now that worked but cloudflare started giving error.


Error 1000 Ray ID: 397a5599943172fb • 2017-09-01 18:36:18 UTC
DNS points to prohibited IP

**Comment by rapidcloubr** [comment]
This error is why you use CloudFlare, try this: https://github.com/engintron/engintron/wiki/Engintron-&-CloudFlare

**Comment by Brijendrasial** [comment]
Thanks it works now :)

**Comment by rapidcloubr** [comment]
@Brijendrasial 😄
