### ISSUE TITLE
High PHP-CGI

### ISSUE THREAD

**Issue by zmkhan90** [engintron/engintron#633]
Hello,
Since last couple of weeks i m facing High PHP-CGI usage and when I restart apache and nginx the cpu usage goes down and become normal.

Its happening twice aday since last couple of weeks.

Please find the below given SSH Screenshot.

[https://imgur.com/a/gF0cT](url)

And here the WHM screenshot of processes.
[https://imgur.com/a/gF0cT](url)

**Comment by zmkhan90** [comment]
I am using the latest version of Engitron on WHM 64.x build 38

**Comment by iRickyJ** [comment]
Do you traffic spike when you see high load , try domain.com/nginx_status (if its enabled) to see actual number of request at that time to cross-check.

If its during traffic spike then you need more optimization.
