### ISSUE TITLE
How to hide Engintron in Reseller Account?

### ISSUE THREAD

**Issue by Cavain** [engintron/engintron#634]
Hello,

I recently upgraded my engintron from 1.8.4 to 1.8.5 but when i saw the change log their is showing " Added proper ACL checks for resellers to the Engintron WHM app. " but we don't want that feature how can we remove this?

Thank you

**Comment by jhawkins002** [comment]
Hi @Cavain - Engintron is only accessible to resellers if they are have appropriate permissions. 

For example, we have a number of reseller accounts that have "all" permissions in WHM (for all intents and purposes root-level access). As of this latest update, they can now work with Engintron. We have other resellers that have more restrictive permissions set. They cannot access Engintron. 

Basically, the changelog should not be taken to mean that all resellers can access the tool. I hope this helps!
