### ISSUE TITLE
Duplicate headers sent

### ISSUE THREAD

**Issue by pavsid** [engintron/engintron#635]
Hi, just installed Engintron last week - great work, thank you :)

Although it's been mostly smooth rolling, webfonts (which are served from a different static host to main site) started not loading due to an error with the CORS header being sent.

Turned out it was due to `Header set Access-Control-Allow-Origin "*"` being sent twice, which made it invalid. The fix was to remove the header from the site's `.htaccess` file, and leaving Nginx to send it automatically.

However, other headers are also being sent twice, and although not causing an issue, I wondered if this is normal, and how this is normally prevented - should such headers be removed from the `.htaccess` file and left for Nginx to send?

Thanks again.

**Comment by fevangelou** [comment]
You need to provide a few URLs to check. Headers are replaced where
possible, not sent twice. If you see double headers maybe the issue is
elsewhere.

As for the fonts, you are right, such a header is sent by default from
Nginx as most apps or CMSs usually don't bother with such a header.

**Comment by pavsid** [comment]
Hi @fevangelou thanks for your reply, and for clarifying the font header will be sent twice.

As for URLs, are the response headers ok?

This is a site which is served via Cloudflare:

```
cache-control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
cf-ray:399b3afdf8553446-LHR
content-encoding:gzip
content-type:text/html; charset=UTF-8
date:Tue, 05 Sep 2017 18:25:19 GMT
expires:Thu, 19 Nov 1981 08:52:00 GMT
myheader:D=337602 t=1504635919066115
pragma:no-cache
server:cloudflare-nginx
status:200
vary:Accept-Encoding
vary:Accept-Encoding
x-content-type-options:nosniff
x-content-type-options:nosniff
x-nginx-cache-status:EXPIRED
x-powered-by:PHP/5.6.31
x-server-powered-by:Engintron
x-ua-compatible:IE=edge
x-xss-protection:1; mode=block
```
As you can see there are a couple of headers sent twice i.e. `vary` and `x-content-type-options`, although as I mentioned they don't seem to be posing an issue.

These are the headers sent by a site which is not served by Cloudflare:-

```
Cache-Control:max-age=0
Cache-Control:no-cache, private
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html; charset=UTF-8
Date:Tue, 05 Sep 2017 18:23:18 GMT
Expires:Tue, 05 Sep 2017 18:23:18 GMT
Server:nginx
Set-Cookie:laravel_session=XXXXX; expires=Tue, 05-Sep-2017 20:23:18 GMT; Max-Age=7200; path=/; httponly
Set-Cookie:XSRF-TOKEN=XXXXX; expires=Tue, 05-Sep-2017 20:23:18 GMT; Max-Age=7200; path=/
Transfer-Encoding:chunked
Vary:Accept-Encoding
Vary:Accept-Encoding
X-Content-Type-Options:nosniff
X-Content-Type-Options:nosniff
X-Nginx-Cache-Status:EXPIRED
X-Powered-By:PHP/5.6.31
X-Server-Powered-By:Engintron
X-UA-Compatible:IE=edge
X-XSS-Protection:1; mode=block
```

Again, the same two headers as the example above are sent twice, as well as `Cache-Control` but the values are different so that might be acceptable.
