### ISSUE TITLE
PHP-FPM and engintron issue

### ISSUE THREAD

**Issue by iRickyJ** [engintron/engintron#636]
Hi, 

PHP-FPM is supposed to be more efficient than old php-cgi but in my case where I have enginx installed, I can serve 2500-3000 request easily without any significant load with CGI as php handler but as soon as I switch to PHP-FPM (using  Multiphp Manager of EA4) , now can't even server 1000 requests without significant load, and on around 1500 requests, its almost non-responsive. 

**top** gives us couple of PHP-FPM process with 100% cpu usage. 
There is no disk load at all.
Almost 80% RAM is not used 

Even simple page with only phpinfo()  won't open using php-FPM.

Is that Engintron with PHP-FPM needs something special instead of out-of-box setup ?, do anyone have any advice or experience or guide to configure PHP-FPM with apache for high traffic site ?

I tried several docs but no help. What could be bottleneck for default cpanel php-fpm config, where can I start working.?

**Comment by dws122** [comment]
Have you started here with updating the base config? https://github.com/engintron/engintron/wiki/Beyond-Engintron:-Optimizing-Apache

Also make sure you PHP-FPM pool size for the account is set to handle the load you expect (in MultiPHP Manager) and that the pool size doesn't exceed your base config.

**Comment by spopadiin** [comment]
I think a config suggestion script will be very helpful to the Operations page. I am saying that not because its such a hard thing to optimize settings per se, but because Engintron is for WHM which is usually used for many clients, many domains, many services. And optimizing all pools and setting best Apache config will need a lot log analysis and A/B config test.

**Comment by rvencu** [comment]
I get similar issues. Having the Apache timeout of 20 is not helping at all, I got a lot of 504 errors with high and low traffic. I put back the default 300 value and even if the visitor stay longer the page is still served. This is important when I rebuild cache with tools like WP Rocket, if the spider is getting 504 errors there is nowhere to go. Though I did not try to exit PHP-FPM and use CGI only. I should try that.
In my case though the issue does not happen all the time. When my CPU load goes to 10x the number of processors usually just rebooting the server solves the issue. I can do the same action, like cache rebuilding, with normal load of CPU. When the high load CPU is happening I noticed the Apache gets stuck on W state for hundreds of connections, so it looks like Nginx does not accept the answer from Apache and does not clean the request.

**Comment by iRickyJ** [comment]
It is actually issue with Apache, in my case it wore issue with how PHP-FPM is configured, in cPanel its not straight forward to optimize PHP-FPM, if you can then you can serve I suppose 30% more request on same hardware. 

Anyways, so I ditched cPanel altogether for this particular setup, now its Nginx + PHP-FPM only.

Coming to your condition, Apache can handle a particular number of simultaneous request depending upon lots of factors , and you are just running out of it regularly. Restarting Apache should also resolve issue other than server restart. 

In your case, two possible solution : 1 -- Ditch php-cgi and move to php-fpm however, you need to make sure your FPM settings are as per your traffic needs
2. Ditch apache altogether , go to some barebone setup where you can manage all aspects of nginx+php-fpm better. If you can move to PHP7, then even better.
