### ISSUE TITLE
Upgraded from EasyApache 3 to EasyApache 4 and installed Engintron

### ISSUE THREAD

**Issue by faca5** [engintron/engintron#641]
Hello.

Today We have upgraded EA3 to EA4 and installed Engintron.

SSL certificates doesn't work for all users using nginx.

URL:
https://example.com

Error:
Your connection is not secured.

If we disable Enigtron it works. Any idea?

Thank you!

**Comment by djprmf** [comment]
See this: https://github.com/engintron/engintron/issues/643#issuecomment-329980407

**Comment by faca5** [comment]
Hello.

Thank you!
