### ISSUE TITLE
Disabling Engintron breaks shared SSL

### ISSUE THREAD

**Issue by 01i** [engintron/engintron#643]
I disabled enginetron and all sites on my server that use SSL no longer function. All are now serving the default SSL certificate for the server, rather than their own domain specific certificates. The only way to fix it, seems to be to run the full uninstallation process

**Comment by djprmf** [comment]
For some reason, the last version appears to change the SSL certificates from cPanel, putting them under the shared IP of the server. So, if a account have a SSL issued to a specific IP, that will break...

To solve this problem remove and reinstall the SSL under the WHM.
Make sure that, if the account is under a dedicated IP, that IP is correct in the SSL installation process...

**Comment by 01i** [comment]
All SSL certificates were issued by AutoSSL and none of the sites on the server are on dedicated IP's all are shared IPs, and every single AutoSSL issued certificate was broken until I ran the full uninstall shell script. If engintron changes certificates, then the disable script should undo it, rather than require manual intervention, or full uninstallation. There's little point in a disable option if uninstall is required.

**Comment by faca5** [comment]
Hello.

Do you have any better solutions? We cannot re-install all SSL certificates.

We have re-installed one of SSL certificate via cPanel but it doesn't work at all.

**Comment by 01i** [comment]
Better solution? I don't know the backend of your code, nor have I got the knowledge to go through the disable scripts, but if you have a disable option, then it should put the system back to a functional place. If that's not possible, then you should remove the disable option, and force people to do the full uninstall.

When you uninstall engintron with "bash /engintron.sh remove" it fixes the problem. So IMO you should either find the part of the uninstall that corrects the problem, and put it into the disable engintron script, (and add the opposite to the renenable engintron script), or replace the disable engintron in the GUI to an uninstall engintron instead.

**Comment by djprmf** [comment]
@01i we are only users tring to help. Me or @faca5, we aren't the developer of engintron...
@fevangelou should check this, but i'm starting to think that engintron is becoming a little unsupported at all, based in the last issues created without any answer...

**Comment by 01i** [comment]
Sorry guys, didn't realise that I wasn't getting responses from developers. It sounded like I was just getting palmed off, makes more sense if your users. I guess for now I'll stick with engintron in the uninstalled state, and hope cPanel hurry up with a native nginx integration

**Comment by SirDev** [comment]
I second this issue. I added a new account today with cpanel, the autoSSL feature on Cpanel automatically grabbed some cmodo certs, and when I navigated to the https-version of the site, the certificate of the server (not the domain) is served, e.g. client.myhosting.com certificate in stead of myclientsite.com. When I disable engintron this is gone and the right certificate is served.

This is the first time this happened
Cpanel: v66.0.23
Engintron: v1.8.4, v1.8.5

Disabling Engintron fixed the solution for now, but I'd rather thave it turned on as the performance increase is huge.

**Comment by faca5** [comment]
Hello.

Did you "reload" nginx? When you add new SSL certificate you need always "reload" or "restard" nginx. Then nginx will grap new SSL certificate.

------------------

We have already re-installed nginx. Removed and then install. What we did different is only that we have copied config from another server. This could be one of the last note to check. We believe there wasn't huge changes between latest versions (config for SSL).

**Comment by JorgeMarcelino-HS** [comment]
Reinstall Engintron, this should solve!

**Comment by faca5** [comment]
It doesn't work. SSL certificate via nginx doesn't load.

We have tried:
1. Uninstall
bash engintron.sh remove
bash engintron.sh install

2. AutoSSL check
/usr/local/cpanel/bin/autossl_check --all

3. Restart VHOSTS
rm -rf /etc/nginx/conf.d/default_https.conf
/etc/nginx/utilities/https_vhosts.sh

4.
We have uninstalled SSL certificate. Now we are waiting for new SSL certificate via AutoSSL.


Attachments:
http://www.pagelink.si/download/1.png
http://www.pagelink.si/download/2.png

Logs:
===================================================================
=== Clean Nginx cache & temp folders and restart Apache & Nginx ===
===================================================================

Restarting Nginx...
Stopping nginx:                                            [  OK  ]
Starting nginx:                                            [  OK  ]


Waiting for âhttpdâhttpdâ

Service Status
        httpd (/usr/sbin/httpd -k start) is running as root with PID 16748 (pidfile+/proc check method).

Log Messages
        [Tue Sep 26 06:45:21.167004 2017] [mpm_prefork:notice] [pid 16748] AH00163: Apache/2.4.27 (cPanel) OpenSSL/1.0.2k mod_bwlimited/1.4 configured -- resuming             normal operations
        [Tue Sep 26 06:45:21.088299 2017] [:notice] [pid 16747] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.
        [Tue Sep 26 06:45:10.114965 2017] [mpm_prefork:notice] [pid 16311] AH00163: Apache/2.4.27 (cPanel) OpenSSL/1.0.2k mod_bwlimited/1.4 configured -- resuming             normal operations
        [Tue Sep 26 06:45:10.029321 2017] [:notice] [pid 16300] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.
        [Tue Sep 26 06:45:09.787589 2017] [core:error] [pid 16264] (2)No such file or directory: AH00095: failed to remove PID file /var/run/apache2/httpd.pid
        [Tue Sep 26 06:45:09.771069 2017] [core:alert] [pid 16264] AH00050: Child 16269 returned a Fatal error... Apache is exiting!
        [Tue Sep 26 06:45:09.771061 2017] [core:alert] [pid 16264] AH00050: Child 16268 returned a Fatal error... Apache is exiting!
        [Tue Sep 26 06:45:09.771053 2017] [core:alert] [pid 16264] AH00050: Child 16267 returned a Fatal error... Apache is exiting!
        [Tue Sep 26 06:45:09.771018 2017] [core:alert] [pid 16264] AH00050: Child 16266 returned a Fatal error... Apache is exiting!
        [Tue Sep 26 06:45:09.227542 2017] [mpm_prefork:notice] [pid 16264] AH00163: Apache/2.4.27 (cPanel) OpenSSL/1.0.2k mod_bwlimited/1.4 configured -- resuming             normal operations
        [Tue Sep 26 06:45:09.152104 2017] [:notice] [pid 16260] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.
        [Tue Sep 26 06:45:07.966329 2017] [mpm_prefork:notice] [pid 16237] AH00163: Apache/2.4.27 (cPanel) OpenSSL/1.0.2k mod_bwlimited/1.4 configured -- resuming             normal operations
        [Tue Sep 26 06:45:07.893792 2017] [:notice] [pid 16236] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.
        [Tue Sep 26 06:45:03.120118 2017] [mpm_prefork:notice] [pid 16178] AH00163: Apache/2.4.27 (cPanel) OpenSSL/1.0.2k mod_bwlimited/1.4 configured -- resuming             normal operations
        [Tue Sep 26 06:45:03.031194 2017] [:notice] [pid 16177] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.

httpd started successfully.
Stopping nginx:                                            [  OK  ]
Starting nginx:                                            [  OK  ]

**************************************
*       Installation Complete        *
**************************************

**Comment by djprmf** [comment]
The problem here appears that nginx is "forcing" the server SSL to be used in all website, instead of the main SSL for every domain...
Thats what cause the issue. Uninstall doesn't solve the problem.

In my case, the problem was because engintron changed all SSL in the accounts to the shared IP of the server (even those with a dedicated IP). Reinstall the SSL fix that issue.
But, indeed, SSL for every account is a "random game", with some working and others using the main server SSL certificate.

I don't think there is a easy way to fix this. And i don't see the developer working on this anymore (sadly).
I think is time to start thinking about uninstall engintron completly, as this is becoming more problematic every day and without any support.

**Comment by 01i** [comment]
When I suggested earlier, that to fix it you could "bash engintron.sh remove", I wasn't suggesting following up with "bash engintron.sh install". Sadly I only "fixed" it by getting rid of engintron

**Comment by trgcyln** [comment]
I'm having exactly the same problem. I had to remove engintron.
I'll be waiting for the next update.

**Comment by faca5** [comment]
Can we turn off only HTTPS on engintron?

HTTP = engintron
HTTPS = Apache

**Comment by fevangelou** [comment]
@djprmf 

> In my case, the problem was because engintron changed all SSL in the accounts to the shared IP of the server (even those with a dedicated IP)

Seriously? Where exactly does the code in Engintron do that?

@all Unless you provide any logs, I have no idea what's happening although my guess is either leftover references to deleted certificates or the use of Comodo's free certificates via AutoSSL (since LetsEncrypt is also supported in AutoSSL, it's best to use that - see the wiki for more info).

**Comment by djprmf** [comment]
@fevangelou I mean, i don't really know either... But the issue appear right after update Engintron. The accounts or SSL configuration have changed to the main server IP instead of the dedicated IP of the accounts, leading to the problems.
Unfortunately i have since then fixed this, so i cannot provide a specific log about it...

**Comment by faca5** [comment]
We have found solution!

When we have upgrade from EasyApache 3 to EasyApache 4 it created new folder "/usr/local/apache.ea4/conf/httpd.conf".

We have changed default folder "/usr/local/apache/conf/httpd.conf" to "/usr/local/apache.ea4/conf/httpd.conf" in file "/etc/nginx/utilities/https_vhosts.php".

Then We have run this commands:
rm -Rf /etc/nginx/conf.d/default_https.conf
/etc/nginx/utilities/https_vhosts.sh
service nginx restart

Now It works without any problems!


Note: When you ugrade EasyApache it created new folder, it doesn't use previous one.

**Comment by jcrist1027** [comment]
Interestingly, I just started testing an Inmotion VPS and selected their PHP Optimized setup and ran into the same issue with the main site SSL cert being used for all domains despite a valid SSL for each domain being used.  Maybe they are using engintron, if not, this is some sort of WHM/Nginx bug it looks like?

**Comment by boutzamat** [comment]
I simply ran "service nginx reload" in SSH (root) and the HTTPS sites started working again.
Thanks!
