### ISSUE TITLE
v 1.8.5 errors with magento

### ISSUE THREAD

**Issue by mbdwey** [engintron/engintron#644]
After upgrading from 1.8.4 magneto websites failed 
It's require JS errors some JS files not found 
I tried to clear magneto all caches and recompile asset files 
--------- Magneto ---------
rm -fr ../var/cache
rm -fr ../var/di
rm -fr ../var/generation
rm -fr ../var/page_cache
./magento cache:clean
./magento cache:flush
./magento setup:upgrade
./magento setup:di:compile
./magento setup:static-content:deploy  -f
--------- Engintron ---------
* clear nginx temp 
* reinstall

issues resolved after updating install script to install old 1.8.4 realize
I also noted that Magneto admin return 404 not found

ENV
 CLOUDLINUX 6.9 virtuozzo [host1] v66.0.22 

may be related to
https://github.com/engintron/engintron/issues/594

**Comment by fevangelou** [comment]
First off, it's Magento. Not Magneto. Semantics.

Secondly, look for .htaccess rules that could modify incoming requests (e.g. rules based on referrer). You're the first one to report such an issue with Magento. And the issue you mention is again 99,999% related to bad or obsolete .htaccess rules.

**Comment by mbdwey** [comment]
Sorry I can't replicate upgrade scenario to check the rules ,Closed for now
