### ISSUE TITLE
Can we do some load balancing with Engintron

### ISSUE THREAD

**Issue by iRickyJ** [engintron/engintron#645]
Is it possible to pipe some of the request to other server for some or all domain through Engintron Nginx config for load balancing ?
I need weighted load balancing where want to keep about 70% traffic on same machine, rest from other machine. I have real time database replication in place along with file replication. 
Looking around I found following example.. 

upstream myproject {
     ip_hash;
    server 127.0.0.1:8000 weight=3;  
    server xx.xx.xx.xx:80 ; #My other machine
    }
server {
        location / {
            proxy_pass http://myproject;
        }
    }
}

But I am not sure where to apply this concept or this is even worthy or not.

**Comment by fevangelou** [comment]
Nginx is great for load balancing but you'd probably need to take care of other issues first besides DB replication, like site files and cPanel settings synchronisation. If you're doing all this to host a handful of sites, I would not use cPanel for that job. Instead I'd use a small cluster where 1 server uses Nginx for load balancing, reverse proxying and caching, 1 server acts as mounted NFS storage and then sets of servers to act as webservers (where the NFS server is mounted) and DB servers for the replication you already do. Much cleaner, much easier to handle, scalable.
