### ISSUE TITLE
The PHP session even expires with activity in the browser.

### ISSUE THREAD

**Issue by felippebueno** [engintron/engintron#647]
Hello,

I'm having problems with php sessions when engintron is enabled.

For some reason the session variables are deleted, shortly afterwards, sometimes it takes 20 min, sometimes 3 min. Even with browsing activity.

This becomes bad when we have a shopping cart or login control.

I created a script to test and I recorded a video demonstrating the error.

**Create session:** https://www.camisetasdahora.com/_nginx-test/file1.php
**Code in txt:** https://www.camisetasdahora.com/_nginx-test/file1-code.txt

**Record session:** https://www.camisetasdahora.com/_nginx-test/file2.php
**Code in txt:** https://www.camisetasdahora.com/_nginx-test/file2-code.txt

**Log of recordings:** https://www.camisetasdahora.com/_nginx-test/file3.txt

**Video with error:** https://www.dropbox.com/s/smxuljktp371dh2/v2.mp4?dl=0

I searched the internet for possible corrections but I did not succeed, if anyone can help me, I thank you.

**Comment by felippebueno** [comment]
Sorry, my message is wrong after google translator, it has already been corrected.

**Comment by fevangelou** [comment]
What was the problem?

**Comment by felippebueno** [comment]
The problem is that session variables are destroyed in minutes sometimes in a few seconds, forcing the user to log in again or shopping cart.

This only happens when the engintron is active, so I had to deactivate it and re-use apache.

**Comment by isarantis** [comment]
Im having a kinda similar problem with my laravel installation. I cant get users to login in, and in my log files i get newly generated session files every time i refresh the page.

**Comment by fevangelou** [comment]
Prefix the session cookie you set so you can add it to the exceptions in
proxy_params_dynamic (similar to how it's done in CMSs).

**Comment by isarantis** [comment]
added the http cookie name to the exceptions like the other but still not seeing it on the browser.
