### ISSUE TITLE
Engintron 1.8.5 centOS6 WHM 66 no HTTP2

### ISSUE THREAD

**Issue by philsward** [engintron/engintron#648]
I'm a bit of a noob to nginx, ok, a big noob, but after installing engintron, I noticed http2 quit working.  (It was working with EA4)

Nginx is NOT serving http2 pages, despite the default_https.conf showing that all of the domains "should" be serving http2.  After an hour or so of scouring, the only thing I could come up with was engintron wasn't building around openssl 1.0.2 which is required now (thanks to chrome and RHEL's slow package cycles).  But, after "updating" engintron, I realized the script IS in-fact building nginx against it's own install of openssl 1.0.2.  So, now I'm completely clueless... any ideas why it wouldn't serve http2?

Bone stock install of engintron and nginx.  I literally installed the script and fired it up.  All fingers point in the direction that it should work? But it doesn't.

BTW, kudos to the maintainers.  Very well put-together.  I paid for unixy's varnish plugin a while back and for it being a paid plugin, it pales in comparison to the work done here.

**Comment by philsward** [comment]
Did some more digging.

```
nginx -V

nginx version: nginx/1.13.5
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)
built with OpenSSL 1.0.1e-fips 11 Feb 2013
```

So, the question now is whether this is a bug in the engintron install or something else?

nginx is obviously being built off the systems RHEL open ssl which is 1.0.1e, but it SHOULD be built off the easy apache open ssl binary located in: /opt/cpanel/ea-openssl/bin/openssl

I know I saw in the log output when I updated yesterday, something about openssl 1.0.2 but for some reason, it isn't actually using that version.

**Comment by lmfreitas** [comment]
But is this responsible for IOS/Mac blank page?

Same here:

nginx version: nginx/1.12.1
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled

**Comment by philsward** [comment]
@lmfreitas I don't think it is.  If you do a generic google search against "[nginx safari problem](https://www.google.com/search?q=nginx+safari+problem&oq=nginx+safari+problem)", there are a number of folks who are experiencing the same thing.

I'm not ruling it out yet though.

**Comment by TeknoVenus** [comment]
We've got the same issue on CentOS 7. 

nginx version: nginx/1.12.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled

But we do have OpenSSL 1.0.2 installed on the server.

**Comment by philsward** [comment]
@TeknoVenus Huh, I was under the impression that CentOS 7 was using openssl 1.0.2 as the core openssl...  Maybe it's a cPanel thing to keep it at 1.0.1e for the system due to other cPanel related issues.  Out of my scope.

Keep in mind that easyapache 4 is compiled to run against a custom install of openssl 1.0.2 specifically so http2 will work with apache.  This might be the openssl 1.0.2 you're thinking of?

**Comment by TeknoVenus** [comment]
Yeah, openssl 1.0.2 is the system version:

[~]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

But nginx is built with 1.0.1e-fips, as per nignx -V So I'm not quite sure how nginx has been built against 1.0.1e

**Comment by philsward** [comment]
@TeknoVenus that's even more odd... No idea at this point unless your platform is overriding the openssl available in the repos.  Plesk might do that.  cPanel seems to use whatever is in repos for the system, then compiles their own software against a custom install of openssl.

**Comment by fevangelou** [comment]
I think CentOS 7 has already upgraded to the newer OpenSSL release which would allow HTTP/2 in Nginx. However, since the pre-compiled Nginx package is installed directly from nginx.org's CentOS repos, perhaps (and most likely) it has not yet been updated to use the new OpenSSL release. Try re-installing/upgrading Engintron. If that doesn't work, uninstall Engintron (to remove Nginx entirely) and then install again.

**Comment by lmfreitas** [comment]
Stable Version
Centos 7
nginx version: nginx/1.12.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled

same result Mac/Safari timeout, Mac/Chrome works has expected showing content. 

MainLine
Centos 7
nginx version: nginx/1.13.5
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled

Same result Mac/Safari timeout, Mac/Chrome works has expected showing content.
