### ISSUE TITLE
Alternative Port

### ISSUE THREAD

**Issue by brixly** [engintron/engintron#650]
I was wondering if it was possible to run on alternative ports?

Currently, our backup solution requires port 8443, which is currently in use by Engintron / Apache.

We have checked with them, and they are unable to alter the supported port, so I was thinking it would be easier to alter the Engintron port?

**Comment by fevangelou** [comment]
You'd have to modify the installer and replace all 8443 instances with the port you like. But you'd have to manually get the engintron.sh file every time and performance this replacement to maintain that custom port.
