### ISSUE TITLE
AutoSSL issue when multiple ServerAlias blocks exist in httpd.conf for a site.

### ISSUE THREAD

**Issue by savaticus** [engintron/engintron#653]
I have discovered that if an account has a domain that is the same domain name as the hostname for the server, the stapling randomly returns the cert for WHM instead of the cert for the site. I am having the client put that domain (which is an add-on domain) in it's own account to stop it from affecting every domain in their account.

**Comment by savaticus** [comment]
I was completely wrong about this. The issue is actually that /etc/nginx/utilities/https_vhosts.php only processes a single ServerAlias block, even if a site has more than one. Here is a sample that has been sanitized of real data:

`<VirtualHost 173.248.148.116:8080>
  ServerName hostname.com
  ServerAlias hostname2.com ....
  ServerAlias www.hostname.com ...`

The second ServerAlias block is ignored and the default certificate get's returned instead. I manually fixed it by editing default_https.conf and adding the required names to the site's server block.

Please consider this a bug report.

**Comment by fevangelou** [comment]
See this: https://github.com/engintron/engintron/pull/511

It will be merged on the next update of Engintron.

**Comment by savaticus** [comment]
Awesome, thanks. Sorry I missed issue 511.
