### ISSUE TITLE
permanent BYPASS out of the box

### ISSUE THREAD

**Issue by spopadiin** [engintron/engintron#654]
Hello,

First of all thank you for the nice piece of software adaptation you have done for WHM.
You certainly deserve a donation.
However, it did not work out of the box.
I have a very standard WP install with few plugins and no caching plugin.
I installed the ngintron and checked the page load times. It appeared that I get for home and subpages X-Nginx-Cache-Status:"BYPASS", so no caching.

Since you mentioned "install and forget" I tried only to comment out bypass rules to see if this is culprit
```
# CMS (& CMS extension) specific cookies (e.g. Joomla, K2 for Joomla, WordPress, WooCommerce)
#if ($http_cookie ~* "(joomla_[a-zA-Z0-9_]+|userID|wordpress_[a-zA-Z0-9_]+|wp#-postpass|comment_author_[a-zA-Z0-9_]+|woocommerce_[a-zA-Z0-9_]+|wp_woocommerce_[a-zA-Z0-9_]+)") {
    #set $CACHE_BYPASS_FOR_DYNAMIC 1;
    #set $EXPIRES_FOR_DYNAMIC 0;
#} 
```
But It didnt help.
I searched through other config files and did not see anywhere rules that could cause this.
Please, advise what should I look for.
10x

**Comment by fevangelou** [comment]
The cache in WP is bypassed only when certain criteria are met, e.g. a user is logged in (you perhaps, as WP's cookie sticks for a long time). The only true way to test caching is by opening a single private window in your browser or using curl from a terminal (e.g. `$ curl -I http://yoursite.com`).
