### ISSUE TITLE
Weird problem with cache miss

### ISSUE THREAD

**Issue by tamtam22** [engintron/engintron#656]
Hello,

I installed engintron a few months back, using it together with Cloudflare.

However, I notice that many of my resources were not cached by nginx, e.g. (you will need to refresh the URL as hotlinking protection is active):

https://x/wp-content/uploads/love-icon.png
https://x/wp-content/plugins/add-to-any/addtoany.min.js

**### X-Nginx-Cache-Status:MISS**

I am not sure if there is anything wrong with my settings which is not allowing nginx to cache those contents.

Please kindly assist, thank you very much!

**Comment by fevangelou** [comment]
Curl'ing there URLs reveals a modified Engintron Nginx installation. If that's the case, you gotta tell me what you changed. And hotlinking protection is probably the issue as it's not implemented to take into account the fact that you have Nginx as a proxy in front of Apache.

**Comment by tamtam22** [comment]
Hi,

I have disabled Hotlinking protection in Cloudflare.

I did not change or modify the Engintron nginx installation other than
- commenting away the X-Powered-By line in proxy_params_common
- configure cloudflare using the 1-liner in custom_rules


You can view my full configs here:

**/etc/nginx/custom_rules** (ip concealed & only showing modified line)
```set $PROXY_DOMAIN_OR_IP "198.x.x.x"; # Use your cPanel's shared IP address here```

**default.conf**:
https://gist.github.com/tamtam22/f2728f1d1f17a83120a1efecc210ba23

**proxy_params_common** (commented x-powered-by)
https://gist.github.com/tamtam22/93f42bf6e5c75f2c07b619748ef35b2e

**proxy_params_dynamic**
https://gist.github.com/tamtam22/c22e6533ab4d113491cf2aee151f4bb9

**proxy_params_static**
https://gist.github.com/tamtam22/45eb4ef069fd1320d392dcdf0e91af69

**common_https.conf**
https://gist.github.com/tamtam22/bee14b6a9174d9740a12991690015f17

**nginx.conf**
https://gist.github.com/tamtam22/78a02f0359505bf476d27914092df4cb

**Comment by windsofchange** [comment]
@tamtam22 I think you have missed the point here. Engintron and nginx seem to be working correctly. Cache is for higher traffic websites. When you add CF infront of Engintron, then the traffic  load is taken by CF and not Nginx. Typically say on first hit CF pull page from Nginx (at that point the pass is not in nginx cache and then the MISS header). This page is stored in CF cache and subsequent traffic is serviced from this CF cache which contains the page with MISS nginx header. The short of this is once CF is in front of nginx check of CF cache hit and ignore nginx cache header.
