### ISSUE TITLE
commercial support

### ISSUE THREAD

**Issue by dws122** [engintron/engintron#657]
Is commercial support available for Engintron? I submitted the contact form at the bottom of the About section of Engintron for cPanel/WHM a while back and haven't heard anything.

I would be interested in such support.

**Comment by fevangelou** [comment]
You can email engintron [at] gmail [dot] com directly if you want.

**Comment by dws122** [comment]
thanks. I've done that a few times. and also filled out the contact form in the About Section.
I sent the email to that address just now.
