### ISSUE TITLE
Add one site to cloudflare

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#658]
Hi,

I want to add 1 site to cloudflare, but I don't really understand how to modify Engintron for one site...

**Comment by djprmf** [comment]
There is a complete guide in the wiki: https://github.com/engintron/engintron/wiki/Engintron-&-CloudFlare
If you don't know the basic to change the files from Engintron, then you should invest in someone to do it for you, honestly.

**Comment by Friends4U** [comment]
I did see it, but this is what the custom rules say:

# a) If you wish to use CloudFlare for any (or all) of your sites that use your server's SHARED IP address, you will have
#    to provide this shared IP address below otherwise you'll get errors from CloudFlare.
#    Uncomment the following line if all your sites on the shared (main) IP of your server are on CloudFlare:
#set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX"; # Use your cPanel's shared IP address here

In the first line it speaks about all (or any) but in the last line it speaks about all, so I do not understand... The other custom rules do not apply in my scenario I believe.

**Comment by djprmf** [comment]
If you have a website in Cloudflare, then uncomment that line and add the cpanel shared IP to it.
After that, if you have any account with a dedicated IP, change the custom rules file and add the "if" block (as is explained there) with the correct IP for every domain.

In this case, if you only have one website in your server, and is using the cPanel shared IP, the only thing needed is uncomment that line:

set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX"; # Use your cPanel's shared IP address here

**Comment by Friends4U** [comment]
And why wouldn't that be always uncommented (even if you do not use cloudflare?)
