### ISSUE TITLE
ALPN Issue

### ISSUE THREAD

**Issue by windsofchange** [engintron/engintron#660]
I have Apache with http2+ALPN working. If I enable Engintron 1.8.5, the website no longer supports ALPN. What am I missing here?

**Comment by djprmf** [comment]
Hi,

What is the output of the command "nginx -V"?
I think this is related with the OpenSSL version used, probably...

Don't know about the Engintron end if something can bec ausing troubles...

**Comment by windsofchange** [comment]
nginx version: nginx/1.12.1
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie'

**Comment by djprmf** [comment]
If i'm not wrong, i think the server must have OpenSSL 1.0.2 or above to support ALPN...
Check this: https://bugzilla.redhat.com/show_bug.cgi?id=1276310#c6

**Comment by windsofchange** [comment]
@djprmf please see my 1st post. We have apache+http2+alpn working on server.

Now we enable Engintron and lose alpn. So the issue Enginetron has disabled alpn which is already working in apache.

**Comment by Quazz** [comment]
Possible solution in : https://github.com/engintron/engintron/issues/437
