### ISSUE TITLE
Sites with SSL not working in Safari on Mac

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#663]
Hi,

After previous update, I cannot open any site with https (and a valid cert) with Safari on Mac anymore. This really only occurs with Safari on a Mac, alle other browsers on PC or Mac have no problems.

https://cb-s.nl

When I disable Engintron, all works OK.

**Comment by jollyjoyjoy** [comment]
I remember encountering this problem where my clients using Safari experienced slow performance on my websites via https. http didn't pose any issues. I found this thread which helped me: https://github.com/engintron/engintron/issues/526

**Comment by tiagomreis** [comment]
Explained on #664

**Comment by Friends4U** [comment]
I'll reply in the other post.

**Comment by Friends4U** [comment]
It did not work, instead it breaks everything. I now have completely disabled engintron  :(

**Comment by Friends4U** [comment]
I change from suphp to model isapi, Could that be the culprit?

**Comment by Friends4U** [comment]
All settings are correct, it works in every browser BUT safari for Mac.
For now I have disabled Engintron :(

**Comment by tiagomreis** [comment]
That's because Safari is more strict when detects two certificates.

When you activate the Engintron, please check which IP is configured on:

httpd.conf (Port :443)
userdata of that domain (_SSL)
list accounts

**Comment by Friends4U** [comment]
I only have 1 IP... And the problem is after the previous update... I used Engintron for over a year now without problems.

**Comment by bosen** [comment]
perhaps its http2 issue, try add this in the config and restart
`proxy_hide_header             Upgrade;`

**Comment by Friends4U** [comment]
Huh? Where and what does it do...

**Comment by fevangelou** [comment]
@bosen Thanks for that. Just pushed to Engintron in today's build. You can all test it out.

**Comment by Friends4U** [comment]
Works!

**Comment by fevangelou** [comment]
Good to know!
