### ISSUE TITLE
server 502 error in all engintron installations

### ISSUE THREAD

**Issue by botonakis** [engintron/engintron#667]
So, we are using engintron since almost day one. 
Currently 12 servers with WHM and Engintron. After updating to 1.8.5, after 3 days of everything working fine, we encouraged a problem with all the servers, the same time.

Apache in port 8443 went down and 502 error occurred for every hosted website.
After some investigation this happened after attack in port 8443 and apache fails.

So we disabled engintron and left the machines with only apache in port 80. Latest and greatest build. Everything now works fine even after an other attack. CPU load is higher but, they websites still work.

Any ideas or suggestions so Engintron can detect apache having problems and rebuilding it or auto-fixing errors?

**Comment by savaticus** [comment]
You can block external access to 8443 and 8080. Try CSF to make this easy. https://configserver.com/cp/csf.html

**Comment by botonakis** [comment]
All the servers have CSF installed and Immunify360. So, if I block the port you say it will work properly. Let's say this is true.
Now that Apache is running in port 80 and the attacks keep continue every day why is not going down? Port 80 is opened in CSF.

**Comment by fevangelou** [comment]
In CSF's configuration, set CT_LIMIT to something like 200 or 300. This will block single DoS attacks (not Distributed DoS mind you...) as it tracks the number of concurrent connections from a single IP. More than 200 or 300 connections to your server from a single IP means someone is running Siege on you (a benchmarking tool) and can easily bring your server down.

Keep in mind that Nginx is able to handle many more connections compared to Apache. However, depending on your cache strategy, it's normal for Nginx to pass large traffic to Apache under a DoS scenario. Now that you only have Apache and as you say, it's not going down, this means 3 things: either the attack was on port 8443 specifically, or it is no longer as large as it previously was, or that Immunify360 kicks in **_specifically_** for Apache traffic (on port 80) and keeps things sane.

In any case, CT_LIMIT is your #1 configuration value to set in CSF when installing it for the first time (default value is set to 0 which means no connection tracking - protection - at all).

To wrap things up, try setting CT_LIMIT first and re-enable Engintron/Nginx. And as @savaticus said, you can block external direct traffic to Apache's port (8443).

**Comment by fevangelou** [comment]
See this for blocking external access to Apache ports when Nginx is enabled: https://github.com/engintron/engintron/wiki/Restrict-access-to-ports-8080-&-8443-used-by-Apache-only-for-Nginx

**Comment by fevangelou** [comment]
As a sidenote, a 502 error means that Nginx did not get a response from Apache in time. Which further solidifies my point that port 8443 was 99,999% under attack and not port 80.

**Comment by nanomo** [comment]
im expriencing the same issue here but im not recieving any attack on 80/443/8080 very weird
