### ISSUE TITLE
Make all IPs skip DNS

### ISSUE THREAD

**Issue by savaticus** [engintron/engintron#669]
set $PROXY_DOMAIN_OR_IP $server_addr;

This has been tested and works great.

**Comment by fevangelou** [comment]
If you do this in default.conf, the domain checks following will fail (e.g. for cPanel's webmail, cPanel access etc.).

**Comment by savaticus** [comment]
Why would you do that? You put this in custom_rules, the full line once edited then says:
`set $PROXY_DOMAIN_OR_IP $server_addr; # Use your cPanel's shared IP address here`

**Comment by tylermolamphy** [comment]
Bump. This should be here by default -- saves a lot of time establishing each connection.

**Comment by savaticus** [comment]
It's been awhile since I posted this, and I haven't seen any activity. This would solve a lot of peoples issues and make engintron work with cloudflare out of the box. I can't see why you wouldn't make this simple change. Also, since it removes DNS lookups from the equation it improves the speed of engintron.
