### ISSUE TITLE
Nginx on but not detected by CMS

### ISSUE THREAD

**Issue by drjjw** [engintron/engintron#67]
Hello,

Akeeba Backup's Admin Tools for Joomla has an nginx configuration tool that will activate if the application detects nginx. It uses:

$_SERVER['SERVER_SOFTWARE']

to detect this. After installing Engitron, nginx appears to be running as verified by response header and according to WHM plugin, yet according to Akeeba, nginx is not installed. Indeed, I checked with the response to $_SERVER['SERVER_SOFTWARE'] and received:

Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9

Akeeba support says they look for 'nginx' in the response to this check and hence why the tool does not appear.

Jordan

**Comment by fevangelou** [comment]
Nginx works in reverse caching proxy mode so it's not directly visible to any PHP CMS. Joomla should (rightfully) consider that your "application" server, aka the server parsing PHP content, is still Apache. And for that reason, you only have to deal with .htaccess files.

After installing Engintron, there is NO additional configuration you need to add. It works as a black box.

**Comment by drjjw** [comment]
Thanks very much. I realized this this after the fact and it now makes perfect sense. The Engintron plugin is a work of art and a great contribution - one that I'm sure people (including I) would pay for.

**Comment by fevangelou** [comment]
When the new site launches, we will offer (affordable) yearly support packages and it's in our plans to have some premium features integrated in the coming months.
