### ISSUE TITLE
Uninstall, site broken

### ISSUE THREAD

**Issue by rmonst3r** [engintron/engintron#670]
Hello,

 I've uninstalled Engintron and now Cpanel is displaying:

SORRY!
If you are the owner of this website, please contact your hosting provider: 
It is possible you have reached this page because:

Any idea what could of happened here?

**Comment by rmonst3r** [comment]
I reinstalled and the site worked again but i need to remove Engintron.

I have an https redirect that leads to the site.

Any ideas?

**Comment by fevangelou** [comment]
Uninstall Engintron and refresh your browser cache, which is what you're probably seeing already.
