### ISSUE TITLE
Latest (or the one but last) update of Engintron breaks MemberPress (for WordPress)

### ISSUE THREAD

**Issue by mschilder** [engintron/engintron#673]
Hi,

We're using MemberPress (for WordPress) on several sites and MemberPress uses Custom URIs to make certain files or pages only available to specific Members. More on this functionality can be read here: https://docs.memberpress.com/article/179-understanding-rewrite-rules

Since our (one but last) update of Engintron, this functionality no longer works. When openening a 'protected' file (e.g. a PDF), the user ends up in an infinite redirect loop.

We've added MemberPress' suggestion to default.conf in Engintron:

`location ~* \.(zip|gz|tar|rar|doc|docx|xls|xlsx|xlsm|pdf|mp4|m4v|mp3|ts|key|m3u8)$ { proxy_pass http://localhost:PORT_HERE; }`

Still this doesn't work, the infinite redirect loop is still there. 

Can you guys help me sort this thing out. Maybe in cooperation with the guys behind MemberPress?

Hope you can help!

Keepupthegoodwork://Menno

**Comment by mschilder** [comment]
PS. We've also tried the rule above for HTTPS:

`location ~* \.(zip|gz|tar|rar|doc|docx|xls|xlsx|xlsm|pdf|mp4|m4v|mp3|ts|key|m3u8)$ { 
proxy_pass https://127.0.0.1:OUR_HTTPS_PORT;
set $CACHE_BYPASS_FOR_STATIC 1;
set $CACHE_BYPASS_FOR_DYNAMIC 1;
}`

And we've tried using these custom_rules:

`if ($SITE_URI ~* "subomain.mywebsite.nl") {
set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}`

Nothing helped...

**Comment by cartpauj** [comment]
I can't exactly say why it's not working - but I can say how it's supposed to work if that helps.

1) We install some .htaccess rewrite rules
2) User visits PDF link
3) .htaccess rules intercept the request and check if the current user has access to that PDF file
3a) Part of this is to check if the user already has an mplk cookie set that matches a file. If so, we don't do anything and allow the file to be loaded in their browser.
4a) If they do have access, we set a cookie (mplk) and store a file in /wp-content/uploads/mepr/rules/. The name of the file matches the value of the cookie. And then we redirect them back to the file.
4b) if they don't have access, we redirect them to the login page.

So the redirect loop will happen for 2 reasons usually.
1) The cookie is not being set (typical with proxies)
2) The /wp-content/uploads/mepr/rules/ directory is not writable (less common)
