### ISSUE TITLE
Websites with private IP and Cloudflare

### ISSUE THREAD

**Issue by kuteninja** [engintron/engintron#674]
As far as I've seen on the custom rules I can add a single IP for Cloudflare, and afterwards I can setup each domain that I want to have a custom IP different to the default one, but this forces a manual customization that will make all the next parked / addon domains that those users create not work unless we manually change that file and reload / restart nginx. Also, manual setups are prone to errors that can cause nginx not to start again if we use regex or just type something wrong.

Isn't there something that you can do to automatically set this up by reading the /etc/domainips file and /etc/domainusers (to match all other domains from that user), or directly the userdata files so that these cloudflare redirects are setup automatically? 

Cloudflare is used by many of our customers, and some of them have acquired dedicated IPs on the past before SNI was a standard on SSL, and also to handle DNS services remotely trusting that the IP they have won't change.

**Comment by kuteninja** [comment]
I don't know in what language is Engintron internally built, but you could use this bash script to generate that information (or maybe modify it to the language that you prefer):

```
# params: domain ip
function print_nginx_information {
   echo "if(\$host ~ \"$1\")";
   echo "    set \$PROXY_DOMAIN_OR_IP \"$2\";";
   echo "}";
}

mainip=$(grep "^ADDR " /etc/wwwacct.conf | awk '{print $2}')
echo "set \$PROXY_DOMAIN_OR_IP \"$mainip\";";

for line in $(cat /etc/domainips | sed 's/ //' | grep ':');
do
   read -r ip domain <<<$(echo $line | sed 's/:/ /');
   print_nginx_information $domain $ip

   user=$(grep $domain /etc/domainusers | cut -d: -f1)
   for extra_domain in $(grep ": $user$" /etc/userdomains | grep -v "^$domain: $user$" | cut -d: -f1);
   do
      print_nginx_information $extra_domain $ip
   done
done
```

**Comment by kuteninja** [comment]
Why did you close this issue? It's **not** fixed.

If you have websites with a dedicated IP, they must use THAT IP to access Apache, or you'll see a "Site moved" error page on nginx. I've checked this again, and it doesn't just apply to Cloudflare, it applies to all the websites with a dedicated IP.

Manually editing the custom_rules on nginx is not viable, since any new park/addon domain or sub-domain will need to be added manually, and we need our customers to have freedom on whatever they do with their websites

The script I've written above generates the needed rules, but it doesn't do it automatically nor it adds it to nginx, there's still some work needed for this to work and to run on each domain / subdomain change. Perhaps there's a better way to do it.

**Comment by ncabete** [comment]
@kuteninja I know this is quite old, but did you ever end up finding a solution for this?

**Comment by kuteninja** [comment]
Sorry I've left the company which used this tool, however the bash script that I've pasted above worked at the time as a workaround, I didn't know how to get it on the Engintron code but I connected it to regenerate these files via [cPanel hooks](https://forums.cpanel.net/threads/hooking-into-domain-processes.330952/)

**Comment by fevangelou** [comment]
Unless these sites are on CloudFlare or cPanel is behind a NAT (e.g. in AWS), in which case Nginx cannot DNS-resolve their IPs, this step is not needed.
