### ISSUE TITLE
Huge engintron_temp

### ISSUE THREAD

**Issue by diego-vieira** [engintron/engintron#677]
```
root@ [/tmp/engintron_temp]# df -h

Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5       9.8G  7.9G  1.4G  86% /tmp

root@ [/tmp/engintron_temp]# ls -lah
-rw------- 1 nginx nginx 7.6G Nov  2 11:50 0000510037
```

Using `Purge cache & temp files` resolves. Is there a way to run this as a cron?
All configuration is default.

Thank you

**Comment by fevangelou** [comment]
A cron job to do this every 3 hours:

`0 */3 * * * root engintron.sh purgecache >> /dev/null 2>&1`

Place this in /etc/crontab or just edit your server's crontab file directly via Engintron's WHM app.

**Comment by diego-vieira** [comment]
Thank you!
