### ISSUE TITLE
Invalid Mutex

### ISSUE THREAD

**Issue by mpxbrasil** [engintron/engintron#680]
hi guys, i'm facing this error everytime i reboot my server:

`Error:
The “/usr/sbin/httpd” command (process 30693) reported error number 1 when it ended.
Configuration problem detected on line 134 of file /etc/apache2/conf/httpd.conf.work.2YOqr_by:  Invalid Mutex directory in argument file:/run/apache2

        --- /etc/apache2/conf/httpd.conf.work.2YOqr_by ---
        128</IfModule>
        129
        130# This can be configured in the cPanel 'Leech Protection' interface.
        131<IfModule rewrite_module>
        132    RewriteEngine on
        133    RewriteMap LeechProtect prg:/usr/local/cpanel/bin/leechprotect
        134 ===>     Mutex file:/run/apache2 rewrite-map <===
        135</IfModule>
        136
        137<IfModule mime_module>
        138    TypesConfig conf/mime.types
        139
        140    AddType application/x-compress .Z
        --- /etc/apache2/conf/httpd.conf.work.2YOqr_by ---
`

Some times i just reboot and it switch back on.. any clue ?

**Comment by mpxbrasil** [comment]
Apparently when i create the "/run/apache2" directory now apache starts normally..

Anyone know why ?

**Comment by fevangelou** [comment]
Please use the ticket system for issues directly related to Engintron. Your question should be directed to the cPanel forum, not here.
