### ISSUE TITLE
SSL is not working

### ISSUE THREAD

**Issue by Brijendrasial** [engintron/engintron#681]
Hello,

I have latest version of engintron but ssl is not working when software is enabled. Disabling the software enables ssl functionality. Is there anything I can do to resolve this issue?

**Comment by herrerogarcia** [comment]
im have the same problem. after last upgrade stop working cpanel ssl. Only work if im disable engitron,

**Comment by DMKITServices** [comment]
same here

**Comment by rabihmb** [comment]
This simply doesn't work with SSL. Installed it to find immediately all sites running SSL certificates stopped working giving blank page,
