### ISSUE TITLE
Hiding server: nginx header

### ISSUE THREAD

**Issue by amirvenus** [engintron/engintron#682]
Hi,

I have installed Engintron on a cPanel server and so far it's been working perfectly fine like a charm but I am just wondering if the server data can be hidden from the visitors so they won't easily find out what web server we are using. 

I have tried adding different options such as the following did not help:

more_set_headers 'Server:  NYB';
server_tokens off;

**Comment by fevangelou** [comment]
Only the latter will hide the version number, but you can't kill "nginx". It's by design (from Nginx) like this.
