### ISSUE TITLE
Custom port for Blog

### ISSUE THREAD

**Issue by crkdown** [engintron/engintron#683]
Hello,

I have a blog with Ghost (Node.js), that works at www.xxxxx.com/blog and the service works by port 61108

I entered the following custom rules on Engintron

   if ($ host ~ "xxxxxx.com/blog") {
         set $ PROXY_DOMAIN_OR_IP "0.0.0.0";
         set $ PROXY_TO_PORT 61108;
         set $ prot "http";
     }

But it does not work. I test with IP 127.0.0.1 and Main ip server too.

If I log in like this, http://www.xxxxxx.com:61108/blog works well.

Where is the inconvenience?

Thanks!

**Comment by fevangelou** [comment]
a) Engintron is not meant to proxy traffic anywhere else but Apache
b) Your if condition is wrong - you only set the naked domain, not a path to a subfolder.
