### ISSUE TITLE
Broken SSLs, using combined cert files.

### ISSUE THREAD

**Issue by Martin-Blackman** [engintron/engintron#686]
With the update to SSL certificate handling in 67.9999.64;
Implemented case CPANEL-15084: Added combined file support to SSL File obj.
issues have been seen with the Nginx integration.

The issue lies with how Engintron is updating the default_https.conf file.

Each time an SSL is installed or updated, it executes the PHP script to query the Apache configuration and takes parameters from that.

In file:
/etc/nginx/utilities/https_vhosts.php

Line 85:

                preg_match("#SSLCertificateKeyFile (.+?)(\n|\r)#s", $vhost, $certkeyfile);

Amend to:

                preg_match("#SSLCertificateFile (.+?)(\n|\r)#s", $vhost, $certkeyfile);

In the original, the "SSLCertificateKeyFile" does not exist in the Apache configuration, as it's using a combined file.

As such, the PHP script output is null.
If we tell it to use the "SSLCertificateFile" it can pull the combined file location and insert that into our default_https.conf.

This may not suit every case, but it certain appears to work on the one server I have that's using Engintron.

**Comment by danutzu117** [comment]
Hello Martin, thanks for info and I'd like to add another thing, for WHM 68.0.13, it has been changed the way of keeping certificates and the old location (/var/cpanel/ssl/installed/certs/) is no longer available. 

What have I done in https_vhosts.php is the following:

commented out this:
 // $fullChainCertName = str_replace('/var/cpanel/ssl/installed/certs/', '/etc/ssl/engintron/', $vhostCertFile);

and replaced with:
 $fullChainCertName = str_replace('/var/cpanel/ssl/apache_tls/', '/etc/ssl/engintron/', $vhostCertFile);
