### ISSUE TITLE
Server giving it's own ip on visitors page.

### ISSUE THREAD

**Issue by jakesullyneytiri** [engintron/engintron#691]
Hi,

how do I set so visitors own ip appears on visitors page in cpanel again?

It started with servers own ip once I installed this engintorn to my server.

/Thanks

**Comment by chaoswithcontrol** [comment]
Tried this: https://github.com/engintron/engintron/wiki/Check-if-visitor-IPs-are-properly-logged-in-Apache-after-installing-Engintron ?

**Comment by jakesullyneytiri** [comment]
well thing is when i enable the engingtron and then go to cpanel ---> visitors it spams the server ip as visitors ip instead of visitors own ip.

**Comment by elchaka** [comment]
Hello guys,

i have exactly the same :*(.
The skript shows "Verdict:", but the Apache LogFile is only filled with the server IP adress!
We are using EA3

**Comment by jakesullyneytiri** [comment]
@elchaka Does it says Vertdict: Yes or No?  I mean that it must have word Yes or No after it. Mine said Yes after.

**Comment by elchaka** [comment]
Oh sorry - forgott to type the Word "yes"! So:
"Verdict: YES"

**Comment by acuadro** [comment]
Hello, 
I'm having the same problem with the visitors Ip, and the test page shows "Verdict: YES" .
Does anyone found any solution?

**Comment by elchaka** [comment]
unfortunality *no* :*(
