### ISSUE TITLE
installation got stuck, now what

### ISSUE THREAD

**Issue by coolguruji** [engintron/engintron#692]
Hi,

I was trying to install this plugin in my webserver and in the end i got the following issue:

=== Distill changes in Apache's configuration and restart Apache ===
warn [apache_conf_distiller] apache_conf_distiller --update is not supported for                                                                                        EasyApache 4. Please edit config files as detailed in the EasyApache 4 document                                                                                       ation: https://go.cpanel.net/EA4AdvApacheConf
Built /etc/apache2/conf/httpd.conf OK
Waiting for “httpd” to start ……

---It was keep waiting for httpd to start and nothing happened. I dont know why?

After that i run the following command : service httpd start

Starting httpd: (98)Address already in use: AH00072: make_sock: could not bind t                                                                                       o address [::]:8080
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.                                                                                       0:8080
no listening sockets available, shutting down
AH00015: Unable to open logs
                                                          [FAILED]

----------------------------------------------------------------------------------------------
Server config:
CENTOS 6.9 kvm with cpanel/whm - Its a vps
I am also using Cloudflare for the domain.

Please guide me what to do?

**Comment by h3artbl33d** [comment]
> `Starting httpd: (98)Address already in use: AH00072: make_sock: could not bind t o address [::]:8080`

Something is already listening on port 8080. Do you happen to know what that could be? `netstat -tulpn` should list programs with open network connections. It should list whatever is listening on 8080. Perhaps you can move that application to another port, or move Apache to another port (through the httpd config file) and edit the nginx/Engintron config to route to the different port.
