### ISSUE TITLE
"too long parameter"

### ISSUE THREAD

**Issue by rafaelppaulucci** [engintron/engintron#694]
Hi Guys,

I have a problem with engintron and nginx.
One customer account has a lot of domains parked. (About 350 domains).
The engintron write the default_https.conf normally. When nginx will start, this error is displayed: 
"too long parameter" at line ... Exactly the line of this specific domain.
So, the engintron is now disabled.
Is there any way to fix this?

Regards.

**Comment by influenist** [comment]
28 days since this is reported. I have the same issue, can someone pick up this matter?

**Comment by fevangelou** [comment]
Gotta provide more info...

> "too long parameter" at line ...
doesn't say much. If it's a long string, I need to know how many characters. Although of course, this is probably Nginx related, so googling around doesn't hurt...

**Comment by rafaelppaulucci** [comment]
@fevangelou there is no problem to google and discover how to solve the problem.
But, when you create a new customer and the Cpanel and Engintron will update the file with this new content, the server will stop again, and again, and again.
Everytime this thing needs a proper manual config to work. 
If engintron can provides this automatically, everything is gonna be fine, without intervention manually.

Actually i have aproximatelly 300 domains at one account. (=~ 9600 characters)
There is a lot of domains.

Regards.

**Comment by influenist** [comment]
@rafaelppaulucci 
Please see my quick fix in https://github.com/engintron/engintron/issues/713
