### ISSUE TITLE
gzip on https

### ISSUE THREAD

**Issue by rroethof** [engintron/engintron#697]
There is a problem with Engintron and GZIP on HTTPS (port 8443). On HTTP (Port 8080) it works fine.
We already tried to turn off HTTP/2 and change PHP handler to CGI but nothing helpt. It wont work, settings are default like we have set it up automatically

**Comment by davje88** [comment]
I've seen the same issue, unfortunately i was unable to find a fix. Does anyone have an idea? 
We're also using the default setup.
