### ISSUE TITLE
Engintron compatibility with mod_pagespeed module?

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#70]
Please can you let me know, Does Engintron compatibility with mod_pagespeed module?

mod_pagespeed module: https://github.com/pagespeed/cpanel

**Comment by fevangelou** [comment]
There is no issue here as Nginx "sits" in front of Apache and mod_pagespeed is an Apache module. So no conflicts, they will all work together just fine. Besides, mod_pagespeed is for content optimization and transformations, in other words, it's what Apache will pass on to Nginx ;)

**Comment by mofolo** [comment]
Sorry to re-open this on you @fevangelou  - 
I've noticed that there are, occasional times where our websites will throw 404 on assets (jpg, png, css, js) and restarting Apache/Nginx is the only solution.

Your thoughts?

**Comment by fevangelou** [comment]
This means that these files were actually deleted in Apache and the micro-cache maintained references to them, but only for a split second (literally). Unless you changed micro-caching to higher values.
