### ISSUE TITLE
SSL Integration Hosed

### ISSUE THREAD

**Issue by UWH-David** [engintron/engintron#703]
Any updates to this since November 21st? The build really hoses up sites with SSL and dedicated IPs. We have had to uninstall it unfortunately due to its issues.

**Comment by idevwebs** [comment]
I had 1.8.5 which had the ssl issue. Some certs needed updating and failed. Disabled engintron, updated ssls, updated engintron and all seems fine. Can you provide any info on what you're experiencing in case I missed some issues that aren't popping out?
