### ISSUE TITLE
Possible to specify user directory/path (~/user) in $PROXY_DOMAIN_OR_IP ?

### ISSUE THREAD

**Issue by banditz009** [engintron/engintron#707]
Hello,

First, I just wanted to say, THANK YOU for this amazing piece of software.  The fact that it is free is a true testament to the character of the developer(s). 

Here is what I am trying to accomplish:

I have two servers, server1 and server2. They are at completely different datacenters with different hosting companies. Server1 has all my files, databases, PHP, etc.   Server2 has engintron installed. What I am trying to do is use Server2 to pull content from Server1 (nginx reverse proxy) and then display said content to the end users. I don't want the end users to find out the true source / origin IP of Server1. Cloudflare is not an option, so I have decided to do it this way and I think it's viable.

So, let's say on server1, we have the IP of 1.2.3.4. which we have multiple user accounts. user1, user2, user3. for this example let's say that I want to use domain2.com (which is pointed to my engintron server2 IP) to display let's say a file hello.php on http://1.2.3.4/~user3/hello.php  (which is on server1)  -   so that my end users could type in domain2.com/hello.php and it works.

So in my conf file, I have the following:

`if ($host ~* "domain2.com") {
        set $PROXY_DOMAIN_OR_IP "1.2.3.4/~user3/";
        set $PROXY_TO_PORT 80;
    }`

I know this is incorrect. I'm sure $PROXY_DOMAIN_OR_IP was not made to handle paths / directories. Nginx DOES try and pull from the correct IP (1.2.3.4.) but it ignores the /~user3 part. 

It would be absolutely amazing if there was a way to accomplish this? I know it's a bit complicated but hopefully there is a solution. Thank you so much in advance.

**Comment by fevangelou** [comment]
Engintron was not built to proxy content between servers, so I'm afraid its beyond the scope of the (free) support I offer here.
