### ISSUE TITLE
engintron stopped working with SSL

### ISSUE THREAD

**Issue by ehcanada** [engintron/engintron#708]
working great for long time now. Not sure what happened by stopped working with SSL.
here is the log file. Any assistance is appreciated.

2017/12/09 03:24:46 [error] 48056#48056: *9285963 www.hetinkislodge.com could not be resolved (2: Server failure), client: 207.228.78.161, server: hetinkislodge.com, request: "GET /apple-touch-icon-120x120-precomposed.png HTTP/2.0", host: "www.hetinkislodge.com"
2017/12/09 03:29:18 [error] 48058#48058: *9286486 puntledgerv.com could not be resolved (2: Server failure), client: 104.236.64.77, server: localhost, request: "GET / HTTP/1.1", host: "puntledgerv.com", referrer: "http://puntledgerv.com"
2017/12/09 04:32:34 [error] 48056#48056: connect() to [2600:1407:21::17d7:6841]:80 failed (101: Network is unreachable) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, peer: [2600:1407:21::17d7:6841]:80, certificate: "/etc/ssl/engintron/littlebeachresort_com_d55a0_997cb_1515234324_dc4491c6b5e98afbb4da92ef362d7c8c.crt"
2017/12/09 07:54:05 [error] 48056#48056: OCSP_check_validity() failed (SSL: error:2707307D:OCSP routines:OCSP_check_validity:status expired) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, peer: 23.215.104.34:80, certificate: "/etc/ssl/engintron/dev_ehcanadatravel_com_b7161_fc75d_1494955860_1cb6418ab4a12ce473223f3a0305d684.crt"
2017/12/09 07:59:07 [error] 48057#48057: connect() to [2600:1407:21::17d7:6841]:80 failed (101: Network is unreachable) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, peer: [2600:1407:21::17d7:6841]:80, certificate: "/etc/ssl/engintron/ehcanadatravel_com_c36b3_a4e0b_1515147921_46d23d7ea2ab5cb02d9c419384887c2c.crt"
2017/12/09 08:18:48 [error] 48057#48057: connect() to [2600:1407:21::17d7:6822]:80 failed (101: Network is unreachable) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, peer: [2600:1407:21::17d7:6822]:80, certificate: "/etc/ssl/engintron/harbour_house_com_b028b_a02b5_1516530322_78a2a58d38c3fd368dc6b209522c1bd7.crt"
2017/12/09 08:49:56 [error] 48057#48057: connect() to [2600:1407:21::17d7:6841]:80 failed (101: Network is unreachable) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, peer: [2600:1407:21::17d7:6841]:80, certificate: "/etc/ssl/engintron/hetinkislodge_com_c75e4_4fd93_1513938360_3285202a6eaa624d2a419a7f1db47ac4.crt"
2017/12/09 10:30:11 [emerg] 34486#34486: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 11:35:45 [emerg] 47495#47495: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 11:38:11 [emerg] 47907#47907: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:56
2017/12/09 12:20:03 [emerg] 56426#56426: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 12:21:42 [emerg] 57069#57069: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 12:22:32 [emerg] 57776#57776: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 12:22:32 [emerg] 57776#57776: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 12:22:32 [emerg] 57776#57776: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 12:22:32 [emerg] 57776#57776: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 12:22:32 [emerg] 57776#57776: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 12:22:32 [emerg] 57776#57776: still could not bind()
2017/12/09 12:24:12 [emerg] 58001#58001: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 12:24:12 [emerg] 58001#58001: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 12:24:12 [emerg] 58001#58001: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 12:24:12 [emerg] 58001#58001: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 12:24:12 [emerg] 58001#58001: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 12:24:12 [emerg] 58001#58001: still could not bind()
2017/12/09 12:30:15 [emerg] 60658#60658: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:00:25 [error] 59819#59819: *2849 connect() failed (111: Connection refused) while connecting to upstream, client: 68.180.231.58, server: localhost, request: "GET /gallery/picture/4813-canoe002/tags/454-southern_lakes HTTP/1.1", upstream: "https://67.227.222.38:8443/gallery/picture/4813-canoe002/tags/454-southern_lakes", host: "www.ehcanadatravel.com"
2017/12/09 13:00:25 [error] 59819#59819: *2851 connect() failed (111: Connection refused) while connecting to upstream, client: 207.46.13.111, server: localhost, request: "GET /british-columbia/vancouver-island/lodging/view,rss.html HTTP/1.1", upstream: "https://67.227.222.38:8443/british-columbia/vancouver-island/lodging/view,rss.html", host: "www.ehcanadatravel.com"
2017/12/09 13:00:28 [error] 59816#59816: *2853 connect() failed (111: Connection refused) while connecting to upstream, client: 164.132.161.19, server: localhost, request: "GET /gallery/picture.php/3761-buildings/tags/4-nwt/314-home HTTP/1.1", upstream: "https://67.227.222.38:8443/gallery/picture.php/3761-buildings/tags/4-nwt/314-home", host: "www.ehcanadatravel.com"
2017/12/09 13:00:28 [error] 59818#59818: *2854 connect() failed (111: Connection refused) while connecting to upstream, client: 207.46.13.111, server: localhost, request: "GET /british-columbia/whistler/whistler-bc/parks-trails/5093-loggers-lake-trail.html HTTP/1.1", upstream: "https://67.227.222.38:8443/british-columbia/whistler/whistler-bc/parks-trails/5093-loggers-lake-trail.html", host: "www.ehcanadatravel.com"
2017/12/09 13:00:28 [error] 59816#59816: *2857 connect() failed (111: Connection refused) while connecting to upstream, client: 207.46.13.111, server: localhost, request: "GET /blog/travel-stories/page/5/ HTTP/1.1", upstream: "https://67.227.222.38:8443/blog/travel-stories/page/5/", host: "www.ehcanadatravel.com"
2017/12/09 13:04:30 [emerg] 59815#59815: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:05:18 [emerg] 68526#68526: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:05:27 [emerg] 68666#68666: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:06:31 [emerg] 68941#68941: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:08:36 [emerg] 70267#70267: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:09:50 [emerg] 71151#71151: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:10:40 [emerg] 71864#71864: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:15:32 [emerg] 73563#73563: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:15:37 [emerg] 73581#73581: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:15:38 [emerg] 73702#73702: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:15:38 [emerg] 73812#73812: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:15:40 [emerg] 73974#73974: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:17:01 [emerg] 74951#74951: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:17:01 [emerg] 74951#74951: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:17:01 [emerg] 74951#74951: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:17:01 [emerg] 74951#74951: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:17:01 [emerg] 74951#74951: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:17:01 [emerg] 74951#74951: still could not bind()
2017/12/09 13:18:41 [emerg] 75173#75173: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:18:41 [emerg] 75173#75173: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:18:41 [emerg] 75173#75173: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:18:41 [emerg] 75173#75173: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:18:41 [emerg] 75173#75173: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:18:41 [emerg] 75173#75173: still could not bind()
2017/12/09 13:19:31 [emerg] 75372#75372: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:19:31 [emerg] 75372#75372: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:19:31 [emerg] 75372#75372: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:19:31 [emerg] 75372#75372: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:19:31 [emerg] 75372#75372: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:19:31 [emerg] 75372#75372: still could not bind()
2017/12/09 13:20:21 [emerg] 76099#76099: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:20:21 [emerg] 76099#76099: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:20:21 [emerg] 76099#76099: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:20:21 [emerg] 76099#76099: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:20:21 [emerg] 76099#76099: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:20:21 [emerg] 76099#76099: still could not bind()
2017/12/09 13:21:12 [emerg] 76293#76293: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:21:12 [emerg] 76293#76293: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:21:12 [emerg] 76293#76293: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:21:12 [emerg] 76293#76293: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:21:12 [emerg] 76293#76293: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:21:12 [emerg] 76293#76293: still could not bind()
2017/12/09 13:23:18 [emerg] 77589#77589: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:25:36 [emerg] 79581#79581: invalid number of arguments in "ssl_certificate_key" directive in /etc/nginx/conf.d/default_https.conf:45
2017/12/09 13:26:27 [emerg] 79701#79701: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:26:27 [emerg] 79701#79701: bind() to 0.0.0.0:443 failed (98: Address already in use)
2017/12/09 13:26:27 [emerg] 79701#79701: bind() to 0.0.0.0:443 failed (98: Address already in use)

**Comment by bdtech** [comment]
ssl_certificate_key Issue is due to the new version of CP. check the readme for engitron and update it
