### ISSUE TITLE
cscart session cookie problem

### ISSUE THREAD

**Issue by nikosalexiou** [engintron/engintron#709]
when engintron on cpanel with multiple accounts running cscart ecommerce platform, session cookies are being messed up..
customers see products in cart from other customers..  I think that, the same problem, triggers a mess with the customer information during checkout.

**Comment by fevangelou** [comment]
Does CS-Cart have a cookie or header specific to logged in users like other CMSs/eCommerce apps have? If so, I can add it to the list of exclusions in the configuration of micro-caching which would resolve any issues.

**Comment by nikosalexiou** [comment]
yes, it has a cookie that holds the session key.
Storefront: sid_customer_xxxxx
Backend: sid_admin_xxxxx

**Comment by sioulisn** [comment]
hey guys! 
May i  know which file i have to edit in enginitron and what do i have to add to resolve this issue?
i have cs cart 4.5.2 version and when i enable enginitron causes this problem

**Comment by fevangelou** [comment]
Fixed in: https://github.com/engintron/engintron/commit/3b60b444ce30339d6c4af7ce6c540e7bdd38b813
