### ISSUE TITLE
How to Use of Apache - Nginx - Varnish - Elasticsearch with SSL on Engintron

### ISSUE THREAD

**Issue by vinaykumar9999** [engintron/engintron#711]
Hi

Using CentOS 6. Installed Correctly but confused with the settings of Apache, Nginx, Varnish and Elasticsearch with SSL installed.

I am having issue with using all of them together with engintron on Magento 2. 
Using
Apache on Port 8080
Varnish on Port 80
Ngnix not starting on port 80 so i have changed to port 8083
Elasticsearch is not working with SSL if i am using this on Port 9200

Please someone help me in using all the above with SSL. Having lot of difficulty in running my website with all above with engintron.

Best Regards

**Comment by fevangelou** [comment]
Engintron does not work with Varnish out of the box, it requires changes to the default ports used and configured automatically. So it's out of the scope of the support I can provide for you, sorry.

**Comment by JackWormUK** [comment]
I am doing the same thing and it is actually quite easy if using SSL for your site/s. I assume varnish is running on port 80;

1) In WHM go to
Edit default.conf and change the port to an unused port number (not 80) if you are using SSL (if not using SSL then you don't really need Engintron anyway, but you should be using SSL!!!!)

2) Go to
/etc/nginx/conf.d/default_https.conf
Find the Definition Block for the domain name that you wish to send to varnish and add this line in the server section before # deny all
set $serverhttpname mydomain.com;	

3) In WHM go to 
Edit proxy_params_common
Then at the top add this code
if ($serverhttpname ~ mydomain.com) {
    set $PROXY_SCHEME http;
    set $PROXY_TO_PORT 80;
}

Repeat 2 and 3 for all of the domains and sub domains that you would like to varnish

Now you can use the great Engintron with Varnish and Engintron will do all of the SSL decoding work for you

@fevangelou  - I really appreciate you putting this great piece of software out there, thank you.

NOTE - If using elastic search, it cant understand SSL.  Give elasticsearch a subdomain to access it and then set $PROXY_TO_PORT 9200; for the sub domain
Really though you should use Nginx/Engintron to put simple user authentication on Elastic as well or anyone can access it (you can do that in the Definition Block for the sub domain).

**Comment by atifabro1979** [comment]
>     2\. if ($PROXY_DOMAIN_OR_IP ~ mydomainoripetc.com) {
>         set $PROXY_SCHEME http;
>         set $PROXY_TO_PORT 8080;
>         }

hello
how are you?
i want to install Nginx + Varnish + Apache "cPanel", work hard and tries so many things but doesn't work, do you have any idea about this issue?
thanks

**Comment by JackWormUK** [comment]
You need to give more details. Are you using ssl?

What errors are you getting?

What are all of your port settings?

Have you checked the proxy domain or ip variable matching is correct?

Also note that port 8080 is an example. You must set this to the port that varnish runs on. By default this is 80 and enginton sets Apache to port 8080. 

You also need to make sure engintron is not listening on port 80 which is its default. Set enginton to 8081 or another unused port number

**Comment by atifabro1979** [comment]
> You need to give more details. Are you using ssl?
> 
> What errors are you getting?
> 
> What are all of your port settings?
> 
> Have you checked the proxy domain or ip variable matching is correct?
> 
> Also note that port 8080 is an example. You must set this to the port that varnish runs on. By default this is 80 and enginton sets Apache to port 8080.
> 
> You also need to make sure engintron is not listening on port 80 which is its default. Set enginton to 8081 or another unused port number
> 
> NOTE I have updated the code in my original answer to point to port 80 (default for varnish)

hello
yes i using SSL
the error is ERR_TOO_MANY_REDIRECTS
i'm using nginx as front-end on 80 and 443 ports and proxy pass to 6081
and varnish listen on 6081, and pass to 8080
apache listen to 8080
i want to nginx handle SSL and de-crypte it then pass it to varnish..

Thank you so much!
i'm working from 2 day's without any result hehehe

**Comment by JackWormUK** [comment]
Sounds to me like it is an issue with Varnish and its VCL file.

You can confirm this by;
1) Going to http://www.mywebsite.com:6081 (checks that varnish is working)
2) Bypassing varnish and sending NGinx 443 port straight to apache 8080 port (checks that the SSL decryption is working)

There are many VCL files available for download on the internet.

Most of the time it is an issue with headers.  Normally this one;
X-Forwarded-Proto: https

However, i had this problem as well.  Turned out under backend default { } in the Varnish VCL file I couldn't use 127.0.0.1, I had to set .host to my servers actual IP address.

**Comment by atifabro1979** [comment]
> Sounds to me like it is an issue with Varnish and its VCL file.
> 
> You can confirm this by;
> 
>     1. Going to http://www.mywebsite.com:6081 (checks that varnish is working)
> 
>     2. Bypassing varnish and sending NGinx 443 port straight to apache 8080 port (checks that the SSL decryption is working)
> 
> 
> There are many VCL files available for download on the internet.
> 
> Most of the time it is an issue with headers. Normally this one;
> X-Forwarded-Proto: https
> 
> However, i had this problem as well. Turned out under backend default { } in the Varnish VCL file I couldn't use 127.0.0.1, I had to set .host to my servers actual IP address.

hello
i download some VCL files and tried it but same problem.
1. yes, it's working, and i can download by wget and see this header:
Server: nginx
Date: Fri, 23 Nov 2018 05:50:48 GMT
Content-Type: image/jpeg
Content-Length: 406534
Connection: keep-alive
Last-Modified: Tue, 20 Nov 2018 22:58:57 GMT
X-Varnish: 98358 32777
Age: 802
Via: 1.1 varnish-v4
X-Cache: cached

2. yes already working well From Nginx >> Apache without varnish.

maybe the configuration i do wrong, please can you help me and explain the steps to make Nginx as front-end (http,https) and varnish in middle, then apache
Nginx >> Varnish >> Apache
my site using WordPress with full SSL.
in default.vcl when i use 127.0.0.1 varnish not working at all, but when write actual IP working by wget but by browser see: The page isn’t redirecting properly (With SSL and green icon nextto link bar)

Thank you

**Comment by JackWormUK** [comment]
My personal setup is;
Nginx
http - 8081 -> 8080
https - 443 -> 80 (via the code i show in here) otherwise
https - 443 - 8443

Varnish
http 80 -> 8080

Apache
http - 8080
https - 8443

Yours should work fine though.  I dont use Nginx for http. I just put it through varnish

Like i say, i suspect you have a header issue.  Have you looked at something like this?
https://serverfault.com/questions/933659/wordpress-err-too-many-redirects-through-varnish-but-not-through-apache

**Comment by atifabro1979** [comment]
> My personal setup is;
> Nginx
> http - 8081 -> 8080
> https - 443 -> 80 (via the code i show in here) otherwise
> https - 443 - 8443
> 
> Varnish
> http 80 -> 8080
> 
> Apache
> http - 8080
> https - 8443
> 
> Yours should work fine though. I dont use Nginx for http. I just put it through varnish
> 
> Like i say, i suspect you have a header issue. Have you looked at something like this?
> https://serverfault.com/questions/933659/wordpress-err-too-many-redirects-through-varnish-but-not-through-apache

thank you for help, the problem was in VCL file, after searching and try some file + put the code mention in serverfault.com link on wp-config.php now the site it's working good!
but there one wired problem, when refresh the page with CTRL + F5 got blank page, need to reload page with F5 to get it!
do you have any idea about it?
if you can share me your VCL file to try it if the problem from it.
Thanks

**Comment by atifabro1979** [comment]
> > My personal setup is;
> > Nginx
> > http - 8081 -> 8080
> > https - 443 -> 80 (via the code i show in here) otherwise
> > https - 443 - 8443
> > Varnish
> > http 80 -> 8080
> > Apache
> > http - 8080
> > https - 8443
> > Yours should work fine though. I dont use Nginx for http. I just put it through varnish
> > Like i say, i suspect you have a header issue. Have you looked at something like this?
> > https://serverfault.com/questions/933659/wordpress-err-too-many-redirects-through-varnish-but-not-through-apache
> 
> thank you for help, the problem was in VCL file, after searching and try some file + put the code mention in serverfault.com link on wp-config.php now the site it's working good!
> but there one wired problem, when refresh the page with CTRL + F5 got blank page, need to reload page with F5 to get it!
> do you have any idea about it?
> if you can share me your VCL file to try it if the problem from it.
> Thanks

sorry, i see now it's working with full link only, but when i reach MYDOMAIN.com only see same problem "reidrect", but when write MYDOMAIN.com/index.php it's working!

**Comment by JackWormUK** [comment]
That issue might be something to do with the way wordpress does its redirects, I am not sure.  

My VCL is specially designed for Magento, so would not work with your word press site i am afraid.  Maybe you should discuss the issue in a word press related forum to get the last bit to work?

**Comment by vinaykumar9999** [comment]
Hi @JackWormUK 

Glad to see that Varnish is working with engintron, but i am still struggling to get it work.

I have followed the steps you have mentioned but still it is not woking on my side -

On WHM go to
Edit default.conf and change the port to an unused port number (not 80) if you are using SSL (if not using SSL then you don't really need Engintron anyway, but you should be using SSL!!!!)

In WHM go to
Edit proxy_params_common
Then at the top add this code
if ($PROXY_DOMAIN_OR_IP ~ mydomainoripetc.com) {
set $PROXY_SCHEME http;
set $PROXY_TO_PORT 80;
}


Could you please help me in getting this work


I have setup all the things in following manner -

Step 1 -

Changed the 80 port to 8081 in default.conf
---------------------------------------

> server {
>     #listen 80 default_server;
>     listen [::]:80 default_server ipv6only=off;
> 
>     server_name localhost;
> 
>     # deny all; # DO NOT REMOVE OR CHANGE THIS LINE - Used when Engintron is disabled to block Nginx from becoming an open proxy
> 
>     # Set the port for HTTP proxying
>     set $PROXY_TO_PORT 8080; "


---------------------------------------

Step 2 - 

Edit proxy_params_common
Then at the top add this code

> if ($PROXY_DOMAIN_OR_IP ~ mydomain.com) {
> set $PROXY_SCHEME http;
> set $PROXY_TO_PORT 80;
> }


Step 3 - 

Change port 6081 and 6082 to port 80 in etc/varnish/varnish.params

> # VARNISH_LISTEN_ADDRESS=192.168.1.5
> VARNISH_LISTEN_PORT=6081
> 
> # Admin interface listen address and port
> VARNISH_ADMIN_LISTEN_ADDRESS=127.0.0.1
> VARNISH_ADMIN_LISTEN_PORT=6082
> 

Step 4 -

Apache Ports are already set by Engintron

WHM > Tweak Settings > 

Apache non-SSL IP/port [?] |                0.0.0.0:8080

Apache SSL port [?] |                0.0.0.0:8443



With all above steps still didn't get it work. Struggling from so many days to make varnish to work with Engintron.

Regards

**Comment by JackWormUK** [comment]
@vinaykumar9999 

Sorry, i have been very busy.  Are you still having an issue with this?

**Comment by vinaykumar9999** [comment]
@JackWormUK 

I have found another way to reduce TTFB, I have increase dynamic cache time to 1440m in File proxy_params_dynamic

Changed the following
set $EXPIRES_FOR_DYNAMIC 1440m;

and 

proxy_cache_valid              200 1440m; # Adjust for longer server-side cache times (unfortunately, we cannot use a variable here)

For Magento 2 cart, checkout and customer pages, i have added exception in custom rules so those pages will not affect with dynamic cache.

Thanks

**Comment by JackWormUK** [comment]
@vinaykumar9999  Ok. Remember that Magento/Varnish implements cleanup using tags, rather than leaving expired data or doing a re-cache at your time interval (1440)

**Comment by vinaykumar9999** [comment]
@JackWormUK You are right, i am facing the issue with caching as this is creating lot of issues.

Could you please help me or guide me in proper setting of Magento/Varnish with Engintron.

It will be very helpful for me and other who are seeking this sort of solution.

Regards

**Comment by JackWormUK** [comment]
@vinaykumar9999   I already gave a full guide to setting it up which has worked for me and someone else.

I need to know your exact issue?

Did you test that varnish/magento was working before you installed Engintron?  The varnish VCL file can often cause problems

**Comment by vinaykumar9999** [comment]
@JackWormUK 

I am getting this error on all pages ( Frontend and Backend)

--------------------------
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 65911

Varnish cache server
--------------------------


Configuration -

1. Edit default.conf

changed 
listen [::]:80 default_server ipv6only=off;
to
listen [::]:8081 default_server ipv6only=off;

2. Edit proxy_params_common

Added to the top of file

if ($PROXY_DOMAIN_OR_IP ~ yoursite.com) {
set $PROXY_SCHEME http;
set $PROXY_TO_PORT 80;
}

3. Downloaded Varnish file from Magento 2.3.4 Admin Panel

4.  Edit /etc/varnish/varnish.params

Done the following changes to the file

# Default address and port to bind to. Blank address means all IPv4
# and IPv6 interfaces, otherwise specify a host name, an IPv4 dotted
# quad, or an IPv6 address in brackets.
# VARNISH_LISTEN_ADDRESS=192.168.1.5
VARNISH_LISTEN_PORT=80

# Admin interface listen address and port
VARNISH_ADMIN_LISTEN_ADDRESS=127.0.0.1
VARNISH_ADMIN_LISTEN_PORT=6082

# Other options, see the man page varnishd(1)
DAEMON_OPTS="-p thread_pool_min=5 /
             -p thread_pool_max=500 /
             -p http_resp_hdr_len=65536 /
             -p http_resp_size=98304 /
             -p thread_pool_timeout=300"

5. Edit /etc/varnish/default.vcl

Added the downloaded file from Magento 2 Admin (Step 3)

6.  Started Varnish (Started Correctly) and Restarted All Services Via "Restart all essential services"

7. On this Stage i am getting the error while accessing home page and admin pages


Regards

**Comment by JackWormUK** [comment]
@vinaykumar9999 

Engintron is working by the looks of things, your problem is with Vasrnish

**Comment by JackWormUK** [comment]
@vinaykumar9999 

Another thing I didn't mention on here but should be obvious, close port 8081 in the firewall settings otherwise you will leave an open proxy server for people to use for free...
