### ISSUE TITLE
https & IPv6

### ISSUE THREAD

**Issue by windsofchange** [engintron/engintron#715]
Implemented IPv6 in Engintron by uncommenting but can't get https to work on IPv6

Changes I have already implemented
In default.conf
```
server {
    listen 80 default_server;
    listen [::]:80 ipv6only=on;
    listen [::]:443 ssl ipv6only=on;
```

In nginx.conf
```
    resolver                      8.8.8.8 8.8.4.4 [2001:4860:4860::8888] [2001:4860:4860::8844];
```

What am I missing here?

**Comment by fevangelou** [comment]
https://github.com/engintron/engintron/wiki/Enable-IPv6-support-in-Nginx

**Comment by fevangelou** [comment]
Just pushed v1.11.0 making Engintron IPv6 capable by default. Please upgrade and let me know if you see any issues.
