### ISSUE TITLE
Intermittent 502 errors

### ISSUE THREAD

**Issue by brixly** [engintron/engintron#716]
Hi there,

We are running a dedicated server with a few hundred sites so nothing huge.

There's plenty of resource, ram and CPU.

Still though, customers report an occasional 502 error.

How can we prevent this from happening?

**Comment by xlightwaverx** [comment]
How long does the 502 last for?

**Comment by brixly** [comment]
Next to no time at all. 

A refresh always brings the site back up.

**Comment by lakshmish2004** [comment]
hai had same problem my customers also reporting same issue 502 error, websites monitors also showing sites is down

Err: HTTP/1.1 502 Bad Gateway

**Comment by felipegabriel** [comment]
Confirmed, something with HTTPS...

**Comment by brixly** [comment]
So, I noticed that this happened far more during the night, so I trawled through our logs to see what was going on.

We do run AutoSSL - when this runs, an SSL certificate is installed, then apache restarted (by cPanel, not Engintron).

Shortly following this, the https_vhosts.sh script checks and notices a difference in the nginx configuration and the apache config - as such, it then comes along and runs...

engintron.sh purgecache

This essentially clears down the caches, then restarts the httpd service, shortly followed by an nginx restart.

Whilst this is fine in servers running a few sites, when your working on a larger scale server you have the following scenario...

AutoSSL - "yes, installed a certificate, cPanel restarts httpd"
httpd_vhosts.sh - "found a difference between apache and nginx, lets restart httpd and nginx"

The problem is the above - its clashing.

Also, I am not entirely sure why the nginx restart is needed as this actually causes downtime on larger servers (whereby nginx takes slightly longer to restart the workers, similar to httpd)

I altered the engintron.sh purgecache script to remove the httpd restart entirely, and have changed the nginx restart for an 'nginx reload'

I have been monitoring the logs, and all is looking perfect.

I have an AutoSSL job running on over 1200 sites, so theres a good few httpd restarts happening with the cPanel tool - still not one sign of a 502 error, or a connection timed out error.

If all is well, I will post the suggestion to the developer for his comments.

**Comment by xlightwaverx** [comment]
Sounds good, thanks.

**Comment by lakshmish2004** [comment]
hope this issue will clear soon, mean time I have disabled engintron due to this issue,

**Comment by lakshmish2004** [comment]
any update on this issue friends?

**Comment by brixly** [comment]
Are you getting the 502 error inline with the time in the https_vhosts.log?

**Comment by lakshmish2004** [comment]
currently I have disabled engintron in my server, the 502 error happens every day morning during server softwares get updated

**Comment by brixly** [comment]
OK - so your 502 errors are happening when Engintron is disabled? Or only when enabled?

Your server shouldn't do much in terms of updates nightly, certainly none that would effect the apache service.

Can you tell me if you have AutoSSL enabled?

**Comment by lakshmish2004** [comment]
no I am getting 502 error happening when only Engintron enabled, and in my server auto ssl is enabled

**Comment by brixly** [comment]
The issue with your server showing the 502 errors is due to AutoSSL restarting Apache, then Engintron recognising the difference in the configuration files, then repeating the process.

This means, with AutoSSL running its nightly job, many apache restarts and nginx restarts.

This is what took our server offline - instead, disable AutoSSL and enable Engintron to see if it resolves the problem.

**Comment by lakshmish2004** [comment]
buy I need both running in our server is there any solution currently available for this?

**Comment by brixly** [comment]
Do you use Let'sEncrypt for your AutoSSL?

You can do one of two things...

Modify the Engintron.sh script as per the suggestions are made previously / above.

We use an SSL plug-in called fleetssl which allows for deferred Apache restart - this does help resolve the problem too.

**Comment by lakshmish2004** [comment]
yes I am using Let'sEncrypt Auto ssl , please update me more information regarding  fleetssl

**Comment by xlightwaverx** [comment]
Lets encrypt is fleetssl. Let's stay on track people. :)

On Jan 16, 2018 8:47 AM, "lakshmish2004" <notifications@github.com> wrote:

yes I am using Let'sEncrypt Auto ssl , please update me more information
regarding fleetssl

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/engintron/engintron/issues/716#issuecomment-357965284>,
or mute the thread

**Comment by brixly** [comment]
Actually, that's not correct. My question was referring to AutoSSL, which is a facility in cPanel using their built in LetsEncrypt module - this is where the issue lies.

FleetSSL is indeed LetsEncrypt SSL Certificates, however the software that installs and manages the AutoSSL is completely separate from the cPanel version.

The reason I suggested the alternative was due to the fact it supports 'deferred' restarts - the built in cPanel AutoSSL does not, it instead restarts after each install 👍

**Comment by lakshmish2004** [comment]
So if install fleetssl the problem will get solved right? :)

**Comment by xlightwaverx** [comment]
For 30 usd a server I find it way better than autossl.

**Comment by brixly** [comment]
It will certainly help resolve the nightly issue you were facing. 

Functionality-wise, its just an all round better solution anyway - ensure when its installed to select the 'Deferred Restarts' option.

**Comment by lakshmish2004** [comment]
I have installed fleetssl plugin in my server. I have to select Deferred restarts On or Off ? in configuration

**Comment by brixly** [comment]
Deferred should be 'On'

**Comment by webaholicsteam** [comment]
I'm having the same issue on a new install with Nginx 1.12, CentOS 6.9, and Apache 2.4

at the same time I see the following in the Apache error logs, however, we are only using 25% of the system memory..

[crit] Memory allocation failed, aborting process.

**Comment by damchey** [comment]
I am having the same issue as well, the server works well for about a week, then intermittent 502 error occurs every other second. I check the /var/log/nginx/error_log and it shows memory allocation errors, something like the following:

[emerg] 6812#6812: *4744024 malloc(270336) failed (12: Cannot allocate memory) while sending to client, client: X.X.X.X, server: localhost, request: "GET / HTTP/1.1", upstream: "http://X.X.X.X:8080/", host: "www.somedomain.com"

The server has 12GB of RAM, and it shows there's still 4GB free (cache/buffers). I restart nginx and the problem goes away, only to come back after a week or so.

By the way, each nginx process consumes about 400MB of RAM, I haven't seen nginx using that much on other servers running nginx and php-fpm (non-cpanel).

**Comment by redphoenixlimited** [comment]
Just encountered this issue.  Go to Tweak settings/cpanel memory limit = unlimited
