### ISSUE TITLE
Awstats not updating!

### ISSUE THREAD

**Issue by giannis78** [engintron/engintron#717]
Hello,
Happy new year,

After installing engitron everything works perfect but awstats are not updating.
Any solution for this?
Thank you

**Comment by joqrom** [comment]
Hello,

i have the same problem. My configuration:
CLOUDLINUX 7.4 v68.0.21
Apache/2.4.29 with Package 1:ea-apache24-mod_remoteip-2.4.29-1.el7.cloudlinux.x86_64
Engintron for cPanel/WHM - v1.8.7

Any help ? Thank you.

**Comment by giannis78** [comment]
Apache config is configured like this

<IfModule mod_log_config.c>
    LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combinedvhost
    <IfModule logio_module>
        LogFormat "%v %{%s}t %I .\n%v %{%s}t %O ." bytesvhost
    </IfModule>  
    LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b" common
    LogFormat "%{Referer}i -> %U" referer
    LogFormat "%{User-agent}i" agent

But i still see local ip of visitor and not real ip.

**Comment by giannis78** [comment]
Solved this by adding
`LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined`
to post_virtualhost_global.conf Global.

**Comment by joqrom** [comment]
Unfortunately this solution does not work for me :( Have you changed anything else ?

**Comment by joqrom** [comment]
I have manually edited my httpd.conf file and changed %h into %a in and it's working fine now without 

`LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined `

in post_virtualhost_global.conf. But after apache rebuild it's coming back to %h and the problem returns. How can i fix that ?

**Comment by giannis78** [comment]
Hello,
post_virtualhost_global.conf is for that purpose so you put there how you want the LogFormat to be and it will not be overwrite.

**Comment by edibarboza** [comment]
Hi.
I also have this problem on my server, with Engintron installed.

My hosting provider made changes and worked, but WHM was updated and everything failed afterwards.

Does anyone at Engintron have an answer?
Is there no solution?

**Comment by shakensoul** [comment]
I am also not able to resolve this issue of AWstats not updating, currently on v1.8.7 and still problem exists.

Any solution?

**Comment by lfmmp** [comment]
Hello,

the suggested solution is not working: changed IfModule to this

=========================================
<IfModule mod_log_config.c>
    LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combinedvhost
    <IfModule logio_module>
        LogFormat "%v %{%s}t %I .\n%v %{%s}t %O ." bytesvhost
    </IfModule>   
    LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b" common
    LogFormat "%{Referer}i -> %U" referer
    LogFormat "%{User-agent}i" agent              


            <IfModule logio_module>   
        CustomLog "|/usr/local/cpanel/bin/splitlogs --main=host.server.tld --suffix=-bytes_log --sslport=8443" bytesvhost
    </IfModule>
    CustomLog "|/usr/local/cpanel/bin/splitlogs --main=host.server.tld --mainout=/etc/apache2/logs/access_log --sslport=8443" combinedvhost
</IfModule>  
=========================================

the %a is replacing %h, but problem persists; cannot log https logs on it's log_file.

Any idea?

**Comment by lfmmp** [comment]
Hello,

Any idea on the issue reported?

**Comment by fevangelou** [comment]
Until something like this https://www.damchey.com/2018/01/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel/ is baked into Engintron (in one of the soon to come releases), anytime you update Apache's configuration in cPanel, you then have to patch Apache's config from Engintron's WHM app (there's an option for that) to restore IP forwarding.

**Comment by imorandinwnp** [comment]
Fixing this by modifying the template is not the optimal way because if the template changes, you can loose functionality or even worse, something can stop working altogether.

Instead I'm doing this:

1. Add these lines to /etc/apache2/conf.d/includes/pre_virtualhost_global.conf:

```
<IfModule log_config_module>
        LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
</IfModule>
```
2. Restart Apache

This way there is no need to override the template and the change is permanent (unless there is a mayor Log Format change in the future).

NOTE: Piped Logging should be disabled for this to work

**Comment by fevangelou** [comment]
> NOTE: Piped Logging should be disabled for this to work
Where exactly @imorandinwnp?

I'll add your comment in the wiki.

**Comment by imorandinwnp** [comment]
Hi @fevangelou . Update: I now add this code to /etc/apache2/conf.d/includes/pre_virtualhost_global.conf that is compatible with and without piped logging (WHM -> Apache configuration -> Piped Log), so no need to disable it:

```
# NON-PIPED
<IfModule log_config_module>
	LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
</IfModule>
# PIPED
<IfModule mod_log_config.c>
	LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combinedvhost
	LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
	LogFormat "%v:%p %a %l %u %t \"%r\" %>s %b" common
</IfModule>
```
