### ISSUE TITLE
Intermittent 403 errors

### ISSUE THREAD

**Issue by asnapeppo** [engintron/engintron#718]
Hi there,
I'm running a dedicated server with a single website hosted.
I run engintron 1.8.7 on WHM 68.0.21 centos 7.4 standard 64bit
All engintron params are set to default exept for costum_rules where a I add $PROXY_DOMAIN_OR_IP row to work with cloudflare.

Engintron is running on my server for about 7 month without any problem, but since 2 days engintron isn't stable. There are a lot of 403 errors in nginx log, and website is running with some issues.
This is an example of error:
`xxx.xxx.xxx.xxx - - [03/Jan/2018:03:45:00 +0100] "GET /category/page/ HTTP/1.1" 403 12503 "http://mydomain.com/category/page/" "Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1"`

For each error 403 apache return an error like this:
`[Wed Jan 03 03:45:00.583947 2018] [:error] [pid 40758:tid 1284000188160] [client xxx.xxx.xxx.xxx:42892] client denied by server configuration: /home/user/public_html/`

The website display the 404 error page instead of 403.

I've already check .htaccess and file permission but they are ok.

How can I fix this problem?
Thanks for your help and sorry for my English

**Comment by inocc** [comment]
Hello,
Im having the same issue as well, I had to disable engintron to temp resolve the problem.
I refresh the page and randomly would show the site and other times would get the Error 403.

Thank you all.
