### ISSUE TITLE
nginx-rtmp-module

### ISSUE THREAD

**Issue by tomukaskai** [engintron/engintron#720]
Hi,
how can I add nginx-rtmp-module? 
it has /usr/lib64/nginx/modules, but how?

**Comment by tomukaskai** [comment]
Sorry, this is the link
https://github.com/arut/nginx-rtmp-module

**Comment by theraw** [comment]
you can read this https://github.com/engintron/engintron/issues/712
is the same case you can compile and use it as dynamic module.
