### ISSUE TITLE
Nginx not working after cPanel update

### ISSUE THREAD

**Issue by gfserver** [engintron/engintron#725]
Hello, I've been using engintron with nginx since two years ago with no issues, but yesterday after new cPanel update to version 68.0.26 it stopped working and is not starting.

I see errors binding ports 80 and 8443, searched solutions with no luck

Any help please?

Thanks!

**Comment by gfserver** [comment]
Hello, mark this closed.

I disabled engintron, enabled it again and started working

Thanks!

**Comment by nayahost** [comment]
Hi,
In my cause it's still not starting? Tried disabled then enabled and even removing and reinstalling with no luck.

Thanks

**Comment by nayahost** [comment]
Nginx Status:

Redirecting to /bin/systemctl status nginx.service
Unit nginx.service could not be found.
