### ISSUE TITLE
Problem with SSL certificates on cPanel 68 and engintron 1.8.7

### ISSUE THREAD

**Issue by ciscospirit** [engintron/engintron#726]
Hello,

We have detected a problem installing new certificates.
It doesn't matter if this is a paid certificate from comodo or if it is a free cpanel autossl certificate.

A certificate is not recognized until NGINX is reloaded.
Is it possible to tell the plugin that it always has to reload NGINX after a new installation of a certificate?

Do you know anything about that bug?
How can we fix that?

Thank you.

**Comment by fevangelou** [comment]
This is done by default within 15 seconds. If not, check /etc/nginx/utilities/https_vhosts.log for the output of the built-in command.

**Comment by ciscospirit** [comment]
hello,

thanks for your answer.
i checked out, and saw that i have no https_vhosts.log file there...

root@s11 [/etc/nginx/utilities]# ls -l
total 16
drwxr-xr-x 2 root root   51 Nov 29 23:01 ./
drwxr-xr-x 4 root root 4096 Nov 29 23:01 ../
-rwxr-xr-x 1 root root 5824 Nov 29 23:06 https_vhosts.php*
-rwxr-xr-x 1 root root  875 Nov 29 23:06 https_vhosts.sh*

any other idea?

**Comment by ciscospirit** [comment]
But https_vhosts.sh looks valid with 15 seconds and also the logging path...

`  GNU nano 2.3.1                                                        File: https_vhosts.sh

#!/bin/bash

# /**
#  * @version    1.8.7
#  * @package    Engintron for cPanel/WHM
#  * @author     Fotis Evangelou
#  * @url        https://engintron.com
#  * @copyright  Copyright (c) 2010 - 2017 Nuevvo Webware P.C. All rights reserved.
#  * @license    GNU/GPL license: https://www.gnu.org/copyleft/gpl.html
#  */

INTERVAL="15" # Interval in seconds, must not exceed 60 (seconds)
COUNTER="0"

function generate_https_vhosts {
    if [ -f /etc/nginx/utilities/https_vhosts.php ]; then
        RUN_CHECK=$(/usr/bin/php -c /dev/null -q /etc/nginx/utilities/https_vhosts.php; echo $?)
        if [[ $RUN_CHECK == 1 ]]; then
            bash /usr/local/src/engintron/engintron.sh purgecache > /etc/nginx/utilities/https_vhosts.log
        fi
    fi
}

while [ $COUNTER -lt 60 ]; do
    generate_https_vhosts
    sleep $INTERVAL
    COUNTER=$[$COUNTER+$INTERVAL]
done

exit 0`

**Comment by huguesjoyal** [comment]
I have the same problem... 

For me the log (/etc/nginx/utilities/https_vhosts.log) is created but empty. The AutoSSL renew doesn't restart Nginx also. I have to do it manually.

**Comment by ciscospirit** [comment]
@fevangelou Do you have any idea whats wrong here?

**Comment by ciscospirit** [comment]
any update about this? also with the latest build i still have the same problem... no /etc/nginx/utilities/https_vhosts.log there anywhere... :(

**Comment by DjordjeBojko** [comment]
30 days ago open issue and still no fix :(

**Comment by ciscospirit** [comment]
Any update on this? @fevangelou

**Comment by fevangelou** [comment]
Is PHP's open_basedir restriction enabled?

**Comment by flavioxx** [comment]
@fevangelou 
do I need to enable automatic SSL?

**Comment by ciscospirit** [comment]
Hello,

yes open_basedir Prodection is enabled under WHM > "PHP open_basedir Tweak"

**Comment by ciscospirit** [comment]
@fevangelou 
Hey,

any update on this?

**Comment by DjordjeBojko** [comment]
two months and still no fix

**Comment by DjordjeBojko** [comment]
if cPanel said that is security protection: https://documentation.cpanel.net/display/68Docs/PHP+open_basedir+Tweak
then is necessary to enable.
There is no issue if i remove cPanel or Engitron also. 
But i can't activate SSL if Engitron is enabled so how is this without issue?

**Comment by ciscospirit** [comment]
Hello,

i disabled open_basedir protection 2 weeks ago but have still the same problem!
the file "/etc/nginx/utilities/https_vhosts.log" is even not created.
so i can't see any output in there.

any other idea what could be the problem?

i also checked this today:
https://github.com/engintron/engintron/wiki/SSL-certificate-changes-not-visible-in-Nginx%3F-Here's-a-possible-explanation-&-solution

**Comment by ciscospirit** [comment]
@fevangelou

**Comment by ciscospirit** [comment]
my crontab has this inside:

* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1

and my https_vhosts.sh is this:

![image](https://user-images.githubusercontent.com/15861549/39691278-5ed731b6-51dd-11e8-9a16-1e53480cd7f6.png)

**Comment by fevangelou** [comment]
@ciscospirit Did you hit "save" to fix the line endings in /etc/crontab?
