### ISSUE TITLE
GET /whm-server-status

### ISSUE THREAD

**Issue by virtuali1151** [engintron/engintron#73]
Do you guys know how to fix this WHM error?

3535#0: *531364 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"

**Comment by fevangelou** [comment]
What version of Engintron are you using?

**Comment by fevangelou** [comment]
This has been resolved in v1.5.2. Do you have a modified default.conf file perhaps?

**Comment by virtuali1151** [comment]
I have 1.5.2.. the latest one... I think the problem was with the CSF config change.. I noticed it changed the port to 8081, and I believe it should be 8080 correct for the apache status (PT_APACHESTATUS ).

**Comment by fevangelou** [comment]
So everything is OK now?

**Comment by virtuali1151** [comment]
Yes.. after that change there is no more errors in the log. Tks:)

**Comment by fevangelou** [comment]
Great.
