### ISSUE TITLE
Varnish with Engintron?

### ISSUE THREAD

**Issue by Cavain** [engintron/engintron#731]
Hello,

I wanted to install Varnish on my cPanel server and Engintron is already installed is this possible will both works together ?

Thanks

**Comment by laurfx** [comment]
You can do it If you want to make things complicated, anyway I found proxy reverse cache from NGINX more powerful than Varnish 

https://github.com/engintron/engintron/issues/614
https://github.com/engintron/engintron/issues/210
https://github.com/engintron/engintron/issues/105
