### ISSUE TITLE
Engintron Custom rules WP FASTEST CACHE PLUGIN

### ISSUE THREAD

**Issue by gutenlab** [engintron/engintron#732]
Hi, i am new engintron and Nginx and i was wondering where can i add this code below to proper configure WP FASTEST CACHE PLUGIN. I know that Engintron has a custom configuration file, but when i add this cost the Nginx return a error. Should i follow the tutorial via ssh and copy and paste the following code snippet in the server { } block of “default” file (or whatever the file is being used) located in /etc/nginx/sites-enabled/ ? Thanks in advance.

=============================
```
server {
  listen 80;
  root /var/www/html;
  index index.php index.html index.htm;
  server_name nucuta.com www.nucuta.com;
  
  #CACHE
    set $condition '';
    if ($request_method = POST)
    {
      set $condition "null";
    }
    if ($query_string)
    {
      set $condition "null";
    }
    if ($http_cookie ~* (comment_author|comment_author_|wordpress_logged_in|wp_woocommerce_session))
    {
      set $condition "null";
    }
    set $fullurl '/wp-content/cache/all${condition}';
  #CACHE ENDING
  
  
  location / {
    set $serve_URL $fullurl${uri}index.html;
    add_header Nucuta-Cache-Location $serve_URL;
    try_files $serve_URL $uri $uri/ /index.php$is_args$args;
    
  }
  location ~* \.(css|gif|ico|jpeg|jpg|js|png|woff|woff2|ttf|ttc|otf|eot)$ {
    expires max;
    log_not_found off;
  }
}
```

================

**Comment by stormyqq** [comment]
Hi, I wrote that configuration file. 
It appears as you've copied the whole thing from my tutorial posted in my website, and pasted in your configuration file. Change the server_name to your host name.

**Comment by fevangelou** [comment]
@stormyqq I guess you know now NOT to use personalized details in code examples ;) I updated the comment to remove references back to you.

**Comment by stormyqq** [comment]
> @stormyqq I guess you know now NOT to use personalized details in code examples ;) I updated the comment to remove references back to you.

So you call it's my fault now? If you had read the complete tutorial in my website, then you know I had explained everything from the beginning. I took a lot of time in explaining that. I can't help when people don't read the instructions.

**Comment by fevangelou** [comment]
People read half of what you'll write. That's why you should make sure never to personalize any code you share as others might use it and e.g. harm your SEO for example. Now in this case, there's no harm done cause I could change the text. But what if this is in someone's server or another blog post, right?
