### ISSUE TITLE
Plugin Update also updating whole Server

### ISSUE THREAD

**Issue by ciscospirit** [engintron/engintron#735]
Hello,

i did a plugin update today with this command:

cd /; rm -f engintron.sh; wget --no-check-certificate https://raw.githubusercontent.com/engintron/engintron/master/engintron.sh; bash engintron.sh install

and found out, that the whole sever got updated. is this necessary?
i think updating the complete server should not be triggered by a plugin update...

**Comment by fevangelou** [comment]
How else would it update Nginx from its official repositories?

**Comment by ciscospirit** [comment]
the update has a duration of about 30 minutes... maybe you can restrict the installer to "nginx" and his dependencies only as updating also kernel etc etc

**Comment by fevangelou** [comment]
30 mins? Something's seriously wrong with your server...

**Comment by ciscospirit** [comment]
yah updating cloudlinux with over 1500 update tasks takes his time... maybe it was just 25 minutes, but it takes long to finish all updates.
