### ISSUE TITLE
Cross domain platform

### ISSUE THREAD

**Issue by mg4z** [engintron/engintron#737]
My config has this line but I get error on chrome.
location ~ .(ttf|ttc|otf|eot|woff|woff2|font.css|css|js)$ {
add_header Access-Control-Allow-Origin "*";
}

Access to Font at 'https://cdn.ratanet.com/font/Sans/Sans-Bold.woff' from origin 'https://www.sinagostarcompany.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *, *', but only one is allowed. Origin 'https://www.sinagostarcompany.com' is therefore not allowed access.

**Comment by rvencu** [comment]
I have the same issue. This issue appears to be previously reported with no answer yet.

**Comment by rvencu** [comment]
And, I did something that seemed to help!
I edited these files: default.conf and common_https.conf
I added a command to remove the header just before adding it again:

`# Enable browser cache for fonts & fix @font-face cross-domain restriction (TTL is 60 days)
location ~* \.(eot|ttf|otf|woff|woff2|svg|svgz)$ {
    include proxy_params_common;
    include proxy_params_static;
    expires 60d;
    proxy_hide_header Access-Control-Allow-Origin;
    add_header Access-Control-Allow-Origin *;
}`

**Comment by fevangelou** [comment]
Removed from Engintron. The "Access-Control-Allow-Origin" was referenced to support web fonts in older Firefox releases...
