### ISSUE TITLE
Simple Javascript for WHMCS which show you cart total doesnt render

### ISSUE THREAD

**Issue by NitroD** [engintron/engintron#738]
WHMCS Hosting Billing, Script /feeds/cartnumitems.php which is Javascript doesn't render its value after Install of Engintron, When Uninstalled or Disabled works fine.

This could be problem if some simple scripts stop working with Engintron then its hard to have it production level for all customers.

Thanks

**Comment by cre8gr** [comment]
Maybe you could try disabling micro-caching of Nginx only for the WHMCS directory? I don't know if it's possible and how to disable micro-cacning only for one directory, but I think Nginx's micro-caching is to blame.

**Comment by NitroD** [comment]
Also i try to disable micro-caching in the config file for all domains.
