### ISSUE TITLE
nginx: unrecognized service

### ISSUE THREAD

**Issue by alyai** [engintron/engintron#739]
Hi,

EA4, PHP-FPM, CGI/FASTCGI, HTTP2 CPANEL server.
After installation of engintron got 
httpd restarted successfully.
Stopping httpd:                                            [  OK  ]
Starting httpd:                                            [  OK  ]
nginx: unrecognized service

**************************************
*       Installation Complete        *

Any advice please?

**Comment by fevangelou** [comment]
Run the installer and see if Nginx is actually installed.
