### ISSUE TITLE
Varnish Cache

### ISSUE THREAD

**Issue by Wojozoo** [engintron/engintron#74]
Hi!

First of all, great updates lately!
Will you add Varnish Cache in a future update?

**Comment by Nirjonadda** [comment]
I also like this add Varnish Cache in a future update.

**Comment by fevangelou** [comment]
There is no point for 2 reasons. Nginx does very good caching already - it
also excels at micro caching which does not require any URL exclusions to
work right for sites with user generated content (this is the biggest
advantage compared to Varnish).

Varnish is better for proxying traffic to only a handful of sites and
usually requires setup not just on server level but on application level
too (e.g. Joomla can't work out of the box with Varnish).

However I do have plans to also integrate other Nginx forks with more
capabilities in the future.
