### ISSUE TITLE
deny access to pages.

### ISSUE THREAD

**Issue by katmai** [engintron/engintron#740]
hi, 
i was wondering of a useful feature, since nginx is in front of apache, could we have a way of denying access to a certain page on the server, say in case of a dos attack for instance, having a way of adding that page that keeps getting requested for nginx to instanly give a 503, that would help a lot.

what do you think?

**Comment by fevangelou** [comment]
Configure CT_LIMIT to a value between 200-300 (300 is fine) so you're never
DoS'ed. (D)DoS is another story and no block on pages will save you...

**Comment by fevangelou** [comment]
CT_LIMIT is in CSF's configuration by the way...

**Comment by katmai** [comment]
i sorted it out with a custom deny rule in the custom_parameters file. and it did help, due to the fact that it was a ddos, with a lot of bots accessing a certain php page. and increasing the server load. after denying access to it, everything went back to normal.
