### ISSUE TITLE
has the SSL issue been fixed in the new version of Engintron?

### ISSUE THREAD

**Issue by flavioxx** [engintron/engintron#741]
Hello guys.
Can anyone tell me if this version released on January 19th has already corrected the problem with new accounts that did not have SSL enabled automatically and had to restart NGINX to fix.
Has this problem already been fixed?
Or do you have a solution?
I uninstalled Engintron from my server because of this problem, and I really want to be able to put it back on.

I'm Brazilian and I'm using google translate rsrs

**Comment by jhawkins002** [comment]
Just to chime in; discussion on the cPanel features site today indicates that cPanel has begun implementing API's to allow third party apps to detect SSL installs and modifications on domains. That should put a stake through the heart of these issues for good, I would think! 

Fyi to @fevangelou but Ill bet he is already aware - as this is pretty big and welcome news.

Details at: https://features.cpanel.net/topic/whmapi1-hook-for-ssl-install-and-removal

**Comment by fevangelou** [comment]
@flavioxx Sometimes Apache would get stuck in the process. Restart Apache from WHM and then flush/clear Nginx's caches from Engintron's WHM app.
