### ISSUE TITLE
Websites are refusing to connect

### ISSUE THREAD

**Issue by vowave** [engintron/engintron#742]
Hello,
after installing enigtron and also running the below command in ssh all websites are refusing to connect even without https.
command : /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1
and i had to return apache ports to it defaults.
can anyone help me please ?

**Comment by fevangelou** [comment]
Does the firewall allow connections at ports 8080 and 8443 (the ones Apache
is switched to)?

What errors do you see exactly?

Did you check out the troubleshooting section in the Engintron wiki?

**Comment by vowave** [comment]
I see this error in my error.log
2018/02/13 03:15:49 [emerg] 3055#0: the "http2" parameter requires ngx_http_v2_module in /etc/nginx/conf.d/default_https.conf:5

**Comment by vowave** [comment]
any update here ?!

**Comment by vowave** [comment]
for more information i have centos 7.4 and my autossl version is openssl-1.0.2n

**Comment by fevangelou** [comment]
Re-install just in case.

**Comment by fevangelou** [comment]
If you have the EPEL repo enabled, it probably installed its own copy of Nginx. Check the wiki for the solution.
