### ISSUE TITLE
Apache Handler Discussion

### ISSUE THREAD

**Issue by HostChefs** [engintron/engintron#743]
Hello everybody,

I am collecting some data, on what you are using as PHP Handler for your server.

Mod PHP, FCGid, or?

Thank you guys

**Comment by Citizen-K** [comment]
cpanel cgi

**Comment by vesperax** [comment]
cPanel PHP-FPM (cgi), PHP 7.1

**Comment by fevangelou** [comment]
I believe the cPanel forums are more appropriate for such posts...
