### ISSUE TITLE
Random Blank Pages

### ISSUE THREAD

**Issue by Rockyuk** [engintron/engintron#745]
Hi Everyone,
Not sure if this is a Cloudflare issue or Engintron issue, I have been getting random blank pages across my server recently. It has not happened before when I was using an earlier version of Engintron but after updating to the latest version I have started to get it.

I would say 90% of the sites hosted on my server are WordPress, I have the latest version of Cpanel & CloudLinux 6.9 installed with Modsec/Comodo rules. Most of the sites use CloudFlare SSL and caching for additional security.

Any help or advice would be much appreciated.

Thanks

Rockyuk

**Comment by HostChefs** [comment]
Are there any error logs? What does apache/nginx access/error logs return?

**Comment by Rockyuk** [comment]
Hi HostChefs,
I am still debugging it as it could be something to also do with PHP 7 upgrade on the server. I will report back asap.
