### ISSUE TITLE
How to set engintron to flush ?

### ISSUE THREAD

**Issue by faca5** [engintron/engintron#747]
Hello.

How we set Engintron to flush data direct? This is good or bad idea for high performance?

We like to use ob_flush() in PHP and show code directly (user don't need to wait entire page).

**Comment by fevangelou** [comment]
It's 2018. Even if you did this, JS and CSS would not load entirely and thus the page would look broken. What you mention is a pretty old performance practice but it doesn't make sense nowadays.
