### ISSUE TITLE
How to use GEOIP on Nginx?

### ISSUE THREAD

**Issue by x86fantini** [engintron/engintron#748]
Hi, first of all excelent piece of software! It works great.

i need to install the maxmind geoip DB and use some variables, just like this guide

https://www.howtoforge.com/tutorial/how-to-use-geoip-with-nginx-on-ubuntu-16.04/

how can i do it on engintron? should o do anything special?

thank you
S

**Comment by x86fantini** [comment]
Hello, any updates on this? at least a quick yes/no could be helpfull ;-)

thank you
S

**Comment by fevangelou** [comment]
http://nginx.org/en/docs/http/ngx_http_geoip_module.html

"This module is not built by default".

Engintron installs Nginx from the official nginx.org repo, so you can't have this module until it's included in the Nginx repo builds...
