### ISSUE TITLE
Download page instead load index

### ISSUE THREAD

**Issue by reficul** [engintron/engintron#750]
Hello, I've installed the last engintron plugin on my dedicated server.
It works on all domains except one.

In this domain when I try to navigate the browser download the page instead render the html/php on the browser.

**Comment by fevangelou** [comment]
This behaviour probably occurs with Engintron switched off.

**Comment by reficul** [comment]
@fevangelou I don't understand.

I install engintron, then it's active.

**Comment by fevangelou** [comment]
It's a PHP thing, not related to Engintron. Test using port 8080 to directly call Apache. Check the app/site's error log for more.
