### ISSUE TITLE
Error parsing header X-XSS-Protection: 1; mode=block, : 1; mode=block:

### ISSUE THREAD

**Issue by un4saken** [engintron/engintron#752]
`Error parsing header X-XSS-Protection: 1; mode=block, : 1; mode=block: expected semicolon at character position 14. The default protections will be applied.`

proxy_params_common

`# Security Headers
add_header                    X-XSS-Protection "1; mode=block" always;
add_header                    X-Content-Type-Options nosniff always;`

Why am i getting this error on Chrome Console?

**Comment by fevangelou** [comment]
Is something else perhaps attaching the same header? E.g. via PHP?

As you can see, the Nginx code is clear. It only adds it once.

**Comment by un4saken** [comment]
I commented these two lines and fixed my issue.

> Vary => Accept-Encoding,User-Agent
Last-Modified => Tue, 27 Feb 2018 10:50:12 GMT
X-XSS-Protection => 1; mode=block

Thank you
