### ISSUE TITLE
AutoSSL and cPanel Proxy subdomains with Engintron

### ISSUE THREAD

**Issue by ekaratzas-gr** [engintron/engintron#753]
I faced the problem with AutoSSL not renewing the Proxy subdomains created by cPanel, as described in some of the posts here.
After looking at Nginx configuration by Engintron and the httpd configuration by cPanel, as well as the way AutoSSL renews the certificates I have come up with the following configuration that I placed in custom rules for Nginx.

```
set $cp_proxy_autossl NO;

if ($host ~* "^(autoconfig|autodiscover|cpanel|cpcalendars|cpcontacts|webdisk|webmail|whm)\.") {
    set $cp_proxy_autossl CP;
}

if ($request_uri ~* "^/[0-9]+\..+\.cpaneldcv$|^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?: Comodo DCV)?$") {
    set $cp_proxy_autossl "${cp_proxy_autossl}AUTOSSL";
}

if ($cp_proxy_autossl = CPAUTOSSL) {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
    set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
    set $PROXY_DOMAIN_OR_IP $host;
    set $PROXY_TO_PORT 8080;
}
```

Using it has resulted in updating all the certificates without errors.
This has been tested with Engintron v1.8.7 on CentOS 7.4 with WHM v68.0.29
I have used it in 4 different servers with no problems so far.
I also tested the same configuration on an older server (to be retired) with Engintron v1.8.7 on CentOS 6.9 with WHM v68.0.29 that has EasyApache 3. In this configuration the certificates update still fails.
I hope this can help some of the people using Engintron and facing the same problem!

**Comment by bradwitham** [comment]
Hi ekaratzas-gr,
Previously with Engintron v1.8.7 on CentOS 7.4 with WHM v68.0.29 I was unable to handle AutoSSL so removed the Engintron from servers but after adding above custom rules all AutoSSL started getting update. Thanks mate. Since I have upgraded my all servers on CoS 7.4 and cPanel 68.0.29 so hope someone may post the 6x custom rules.

Kind Regards,
Bradley Witham

**Comment by ekaratzas-gr** [comment]
Hello,
Just to clarify ... The problem with our old server was not CentOS version but EasyApache 3.
After upgrading to EasyApache 4 the certificates are updating as expected (using the code mentioned above)

**Comment by flavioxx** [comment]
I went to
"Edit your custom_rules for Nginx"
I added the code that made it available, this one:
`
set $cp_proxy_autossl NO;
if ($host ~* "^(autoconfig|autodiscover|cpanel|cpcalendars|cpcontacts|webdisk|webmail|whm).") {
set $cp_proxy_autossl CP;
}
if ($request_uri ~* "^/[0-9]+..+.cpaneldcv$|^/.well-known/pki-validation/[A-F0-9]{32}.txt(?: Comodo DCV)?$") {
set $cp_proxy_autossl "${cp_proxy_autossl}AUTOSSL";
}

if ($cp_proxy_autossl = CPAUTOSSL) {
set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
set $PROXY_DOMAIN_OR_IP $host;
set $PROXY_TO_PORT 8080;
}
`
__________________________-

AND SO IT WAS:


#
 if ($host ~ "XXXXXXXXX") {
     set $PROXY_DOMAIN_OR_IP "xx.xxx.xxxx.xx";
 }



# === DOMAIN AND URL PATH EXCLUSIONS FROM CACHING ===
# If you wish to exclude certain domains, subdomains or even full URL paths from micro-caching and/or
# static file caching, simply specify them below and use a colon (|) character as a separator.
# Remember that if you specify a "naked" domain name, e.g. mynicedomain.com, every subdomain e.g.
# support.mynicedomain.com will also be excluded from caching. Decide wisely!
# If you wish to disable ONLY micro-caching, then comment the line "set $CACHE_BYPASS_FOR_STATIC".
# If you wish to disable ONLY static file caching, then comment the line "set $CACHE_BYPASS_FOR_DYNAMIC".
#
# Note: Don't include the "http(s)://" portion of a URL.
#
# if ($SITE_URI ~* "example.com|example2.com/path|example3.com/some/other/path|subdomain.example4.com") {
#     set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
#     set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
# }
`
set $cp_proxy_autossl NO;
if ($host ~* "^(autoconfig|autodiscover|cpanel|cpcalendars|cpcontacts|webdisk|webmail|whm).") {
set $cp_proxy_autossl CP;
}
if ($request_uri ~* "^/[0-9]+..+.cpaneldcv$|^/.well-known/pki-validation/[A-F0-9]{32}.txt(?: Comodo DCV)?$") {
set $cp_proxy_autossl "${cp_proxy_autossl}AUTOSSL";
}

if ($cp_proxy_autossl = CPAUTOSSL) {
set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
set $PROXY_DOMAIN_OR_IP $host;
set $PROXY_TO_PORT 8080;
}
`
______________________________________________

AFTER I SAID AND RESTARTED IN "Restart Apache & Nginx" AND FELL IT ALL.

I had to remove the code and restart the server to re-start everything.

You can help me @ ekaratzas-gr

**Comment by flavioxx** [comment]
@fevangelou 
know how to explain friend

**Comment by ekaratzas-gr** [comment]
Hello flavioxx,
do not include the starting and ending backticks ( ` ) to your configuration file and it should work.
If not check your error logs for other relevant messages

**Comment by mustafamsy** [comment]
@ekaratzas-gr 
Thanks for the fix. All certificates updated with no errors!

**Comment by fevangelou** [comment]
@ekaratzas-gr To be honest, you can just always shut off dynamic and static caching for these subdomains. I'll update the default rules accordingly.

**Comment by feanorknd** [comment]
@fevangelou 

Just disable caching for proxy subdomains, but also sending directly to Apache at the backend, not to the cpanel services ports...

Also considering letsencrypt would be:

`set $cp_proxy_autossl NO;

if ($host ~* "^(autoconfig|autodiscover|cpanel|cpcalendars|cpcontacts|webdisk|webmail|whm).") {
        set $cp_proxy_autossl CP;
}

# AUTOSSL CPANEL
if ($request_uri ~* "^/[0-9]+..+.cpaneldcv$|^/.well-known/pki-validation/[A-F0-9]{32}.txt(?: Comodo DCV)?$") {
        set $cp_proxy_autossl "${cp_proxy_autossl}AUTOSSL";
}

# AUTOSSL LETSENCRYPT
if ($request_uri ~* "^/.well-known/acme-challenge/(.*)$") {
        set $cp_proxy_autossl "${cp_proxy_autossl}AUTOSSL";
}
 
if ($cp_proxy_autossl = CPAUTOSSL) {
        set $CACHE_BYPASS_FOR_DYNAMIC 1;
        set $CACHE_BYPASS_FOR_STATIC  1;
        set $PROXY_DOMAIN_OR_IP $host;
        set $PROXY_TO_PORT 8080;
}`

Great piece of code, thanks @ekaratzas-gr

**Comment by fevangelou** [comment]
@feanorknd Personally I don't use this feature, so I essentially crafted it from user feedback at the time. If you have a look at the current configuration, you'll notice that proxying is indeed off for these cPanel-specific subdomains while using specific ports for each service/subdomain.

Has this changed recently and not working anymore? In other words, should the default action be to to just proxy everything to Apache?

Comments welcome from anyone.

**Comment by CarlosLopezES** [comment]
Hi,

With EA4, cPanel 68.0.33 and CentOS7, in multiple servers, the solution for me was adding the @ekaratzas-gr code and removing the "Proxy cPanel specific subdomains" section in default.conf

King regards and thanks for the work!

**Comment by fevangelou** [comment]
The above exceptions may not be needed at all. Perhaps something's changed with cPanel's proxying of these domains (most likely), so if you guys update to v1.8.10 today, test it out. It should issue certificates for the cPanel-specific subdomains without an issue.

**Comment by fevangelou** [comment]
As a sidenote, it was not caching that caused issues, it was proxying to a different port (e.g. 2082) instead of 80.

**Comment by flavioxx** [comment]
@fevangelou 
I still use version v1.8.11 and still need to restart nginx to appear the green ssl.
What do I have to do to succeed?
The above code I did not use because it did not work with me, so I removed and am using the standard engintron

**Comment by fevangelou** [comment]
@flavioxx Open a different ticket and provide more info, e.g. how many domains you host, your server specs etc. It could be a resource issue.

**Comment by ahsansatti707** [comment]
It was not working for me, but  I fixed it by doing the following logic.

`
set $new_host $host;
# AUTOSSL LETSENCRYPT
if ($SITE_URI ~* "^/[0-9]+..+.cpaneldcv$|/.well-known/acme-challenge/(.*)$|/.well-known/pki-validation/(.*)$") {
    set $new_host "Run by apache";
}

if ($new_host = "example.com") {
    set $PROXY_TO_PORT MyPort;
}
`
