### ISSUE TITLE
cPanel AutoSSL/Letsencrypt Not working Shows Invalid SSL error

### ISSUE THREAD

**Issue by Vsnumimmy** [engintron/engintron#754]
I got Invalid SSL Error after Engintron Installation in my Server.I'm running with Easy apache 4 with cP Version 68.I have contacted the cP Team about the issue and they mentioned its because of the Nginx the issue is occured.Copy of the cP team reply 

Thank you for contacting cPanel support! Currently, it looks like that Nginx may be causing issues with the SSL based on my testing here.

======
DTS-MBA-3:~ suedeyoung$ curl -IL domain.tv
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Sat, 03 Mar 2018 05:48:46 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Location: https://www.DOMAIN.tv/
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Nginx-Cache-Status: MISS
X-Server-Powered-By: Engintron

curl: (60) SSL certificate problem: Invalid certificate chain

After reloading the Nginx it works fine ! There is no log file /etc/nginx/utilities/https_vhosts.log created

**Comment by emildumitrache** [comment]
Hi,
Try to uncoment:
set $redirToSSL "";
if ($http_cf_visitor ~ '{"scheme":"http"}') {
     set $redirToSSL "on";
}

from custom_rules

**Comment by Vsnumimmy** [comment]
I have tried but still it same ! i need to restart the nginx after SSL installation !

**Comment by flavioxx** [comment]
I have the same problem

**Comment by isarantis** [comment]
same problem here

**Comment by fevangelou** [comment]
Read the requirements? https://github.com/engintron/engintron/wiki/Requirements
