### ISSUE TITLE
Error Module 'apcu' already loaded in Unknown:0

### ISSUE THREAD

**Issue by emildumitrache** [engintron/engintron#755]
Hi,
If you encounter this error after you installed APCu from the wiki method just uncomment: apcu.so from /opt/cpanel/ea-phpXX/root/etc/php.d/02-pecl.ini

Cheers!
Emil

**Comment by fevangelou** [comment]
Thanks, I just updated the script here https://github.com/engintron/engintron/blob/master/utilities/install_apcu_in_cpanel_ea4.sh to comment out that line as well.

**Comment by rvencu** [comment]
I also see this error message. Would a reinstall take care of this without manual editing the config files?

**Comment by fevangelou** [comment]
Re-installing will grab the updated script for installing APCu and fixing this. Or just run:

`$ find /opt/cpanel/ -name "*pecl.ini" | xargs grep -l "apcu.so" | xargs sed -i "s/.*\"apcu\.so\"//"`

**Comment by rvencu** [comment]
Solved. thanks
