### ISSUE TITLE
Some weird AJAX response

### ISSUE THREAD

**Issue by rvencu** [engintron/engintron#756]
Hi, I have a long executing AJAX request to the backend. The AJAX executes completely in about 4 minutes but the client receives a 404 after just 20 seconds.

Is there any parameter to let NGINX wait for a longer time to receive an answer from Apache?

**Comment by fevangelou** [comment]
Adjust the timeouts:
```
# Timeouts
proxy_connect_timeout         180s;
proxy_read_timeout            240s;
proxy_send_timeout            240s;
```

in /etc/nginx/proxy_params_common. You're currently reaching the limit there. Set them all to 600s and restart Nginx. Remember to always adjust this value after updating Engintron.
