### ISSUE TITLE
nginx service down after install

### ISSUE THREAD

**Issue by swartjie** [engintron/engintron#757]
Hey Guys,

Very eager to try engintron, but currently sitting with the situation where after I run the install command I keep getting notices from cPanel every minute that nginx is down. Tried restarting it and tried restarting the server, but the service remains down...

Any advise on how to get it resolved, not sure if it is due to the server being a vps running cloudlinux?

Your assistance would be greatly appreciated

**Comment by fevangelou** [comment]
Try re-installing for one.

**Comment by swartjie** [comment]
I have tried reinstalling...
I did notice, If I install it on a 100% clean server after cPanel install it works, but I can't install it on my existing server. How can I debug? Where do I start?

**Comment by fevangelou** [comment]
First off, go to the Services configurator in WHM and disable Nginx monitoring. Then re-enable it. If it still does not work, try forcing a re-install of the last cPanel update (though the cPanel updater, it'sa tick box to do that).

**Comment by swartjie** [comment]
When installing it again now, I don't get a message that nginx is offline anymore, but I do get a message:
This site can’t be reached
domain.co.za refused to connect.

No websites load now... What can be the possible cause?

**Comment by serverok** [comment]
nginx running ? Check with  "ps aux | grep nginx", try start nginx with "service nginx start"

**Comment by swartjie** [comment]
Yes it is running now. All non-ssl sites are working perfectly. But it seems as though all ssl websites are refusing to connect though...

I tried these steps:
SSH then run this command /etc/nginx/utilities/https_vhosts.php then in WHM Engintron plugin click Purge cache & temp files and then click restart for the nginx server.

As detailed here: https://github.com/engintron/engintron/issues/425

But there was no success the same issue persists. SSL site;'s keep saying that the connection was refused?

**Comment by swartjie** [comment]
ok it seems after restarting nginx through command line the SSL issue was resolved :D YAY ;)
no I just have one more question, I am getting the below message, Should i ignore it or fix it?

nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 512; ignoring server_names_hash_bucket_size
Stopping nginx:                                            [  OK  ]
Starting nginx: nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 512; ignoring server_names_hash_bucket_size

**Comment by swartjie** [comment]
Ok I just updated server_names_hash_max_size in my config file of nginx and made it 1024 rather than 512...
Thanks guys, not sure why it was not working before, but working perfectly now ;)...
You guys are golden stars... Does one of you guys know if there is a recommended setup that will improve my server's load speed of all websites, and possibly even server load aswell? Or is the plugin plug and play?

**Comment by fevangelou** [comment]
The plugin is plug and play indeed, however there are parts you can optimize in your server (Apache, MySQL, PHP caching, the system itself) which can further improve performance significantly.

Have a look at the wiki section "Beyond Engintron...": https://github.com/engintron/engintron/wiki#beyond-engintron---optimization-guides

**Comment by swartjie** [comment]
Thanks @fevangelou  for that. Can I ask... Is there a way to test and just make sure that nginx is actually serving the files, and not apache?
Some log I can tail or something? I am 100% unfamiliar with nginx so if you can guide me that would be great... In the meantime, I will see what I can do about the optimizations...

**Comment by fevangelou** [comment]
Use curl. Either from your server's terminal or your Mac/Linux desktop. Or use a webservice equivalent.

The command is: `$ curl -I "http://domain.tld"` (-I is a capital "i")

A valid response will identify the webserver and Engintron's specific HTTP header, e.g.:
```
HTTP/2 200 
server: nginx
date: Sun, 11 Mar 2018 22:09:15 GMT
content-type: text/html; charset=utf-8
vary: Accept-Encoding
p3p: CP="NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM", CP="NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM"
expires: Wed, 17 Aug 2005 00:00:00 GMT
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0, no-cache
pragma: no-cache, no-cache
set-cookie: 110949239d973f23f6d8be817235c729=d384b7a1bc6e32b7346dd4891939b3b6; path=/; domain=www.carersuk.org; secure; HttpOnly
x-frame-options: SAMEORIGIN
last-modified: Sun, 11 Mar 2018 21:56:56 GMT
etag: db2519e2ae8ac24350e4c988c27627f2
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: no-transform
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-nginx-cache-status: HIT
x-server-powered-by: Engintron
```

Do the same for a .jpg or .mp4 file and you'll see they are served from Nginx with different cache times (higher).
