### ISSUE TITLE
nginx rejecting requests without www (the domain itself) 

### ISSUE THREAD

**Issue by amirvenus** [engintron/engintron#761]
I just intalled Engintron on a cPanel server which was previously running apache without problem. 

But now when I try to browse the website, domain.com, or running the command:

curl -ILk https://serverIpAddress -H 'Host: domain.com'

it will get timed out but the following works:

curl -ILk https://serverIpAddress -H 'Host: www.domain.com'

Apachae, on the other hand however, works on both case so I suspect nginx does not like that header. 

Please advise.

**Comment by fevangelou** [comment]
Do both subdomains (naked and "www") point to the same location? Could an .htaccess rule cause a redirect loop perhaps?
