### ISSUE TITLE
Does not speed up server, feels like the opposite

### ISSUE THREAD

**Issue by boutzamat** [engintron/engintron#762]
I recently installed Nginx for cPanel (Engintron) and i expected the server to be supercharged.
The result is far from my expectations. In fact, it feels like the server has become more slow with Nginx.
Should i config anything special for it to be optimized?

The server is running cPanel (latest update as of today) on CentOS 7, with PHP-FPM.
Before i installed Nginx it felt way faster with PHP-FPM only.

**Comment by fevangelou** [comment]
You're a unique exception then.

By the way, instead of "feeling" the difference, it would be more
appropriate to actually measure things a bit, e.g. using simple ApacheBench
tests before and after installing Engintron.

**Comment by boutzamat** [comment]
Well, to know i guess i had to post a issue. Im glad to hear that im an exception then.

I don't know about such tool, so i just tell you what i am experiencing - a slower delivery of websites on the server. But thanks for mentioning ApacheBench. Will try that out.

**Comment by boutzamat** [comment]
I just ran a AB test on the server with Nginx enabled. I actually ran 2, and got 2 different results.

Im not sure how to disable it, because when i go to Nginx config page in WHM, and click on "Disable Engintron", Nginx is still running. If i run "service nginx stop", the webpages won't work at all.

**Comment by boutzamat** [comment]
My "feeling" was right it seems. I have now benchmarked apache with and without nginx.
Without NGINX the server is way faster. I have provided 2 screenshots of my tests. first one with nginx and second one without. Its clearly visible that nginx is slowing down the server.

I even configured Apache according to the guide provided in the wiki:  https://github.com/engintron/engintron/wiki/Beyond-Engintron:-Optimizing-Apache

![with_nginx](https://user-images.githubusercontent.com/4305046/37255498-9bae0806-254d-11e8-81b9-1127f772ecca.PNG)
![without_nginx](https://user-images.githubusercontent.com/4305046/37255499-9bc87b46-254d-11e8-97e1-d50c7595e309.PNG)

**Comment by serverok** [comment]
It is interesting to see the benchmark result. I never tested myself, i just trusted nginx will make it faster.

**Comment by fevangelou** [comment]
Something's wrong here though. Without explaining your setup it doesn't
tell much. Your Nginx running could be leftovers from some other plugin in
which proxying is done badly.

The test also indicates it's performed wrongly. You get no 2xx responses,
aka it's a redirect. In which case the question is: are you benchmarking
the server's IP?

If Nginx is crap I'm pretty sure it wouldn't power the top sites in the
world, let alone the 50k+ servers worldwide using cPanel with Engintron...

**Comment by fevangelou** [comment]
The numbers you saw in your test effectively describe a fast redirect imho.

**Comment by 1edi1** [comment]
This is no exception. I also noticed a delay in loading my site after I installed Engintron - NGINX. In fact, it's a delay in connecting to the server.
If you are with Linode.com do not install Engintron, because without it the Linode server is actually faster. This test was made for Brazil. I can not tell other countries.

My site loads in 41ms without Engintron. 75ms with Engintron. Another detail that caught my attention was the CDN, it does not speed up the loading of my site. I bought CloudFlare, installed Engintron and saw no improvement in loading my site. After I delete all of this, I had a great performance in processing my server. Now I use fewer features and low latency, no caching programs, or any extra tools. I use cPanel / WHM + Apache + Mysql + pure PHP. I do not use any CMS on my site.
To improve the loading of my site, I use dnsmadeeasy, as a DNS manager, I disabled BIND in WHM, I disabled some features, such as: Mysql schema, reduced compression from 6 to 2 and configured mod_ruid2 in apache. My site is flying, with no third-party apps.

But I recognize, that Engintron is a fantastic plugin, I can use it in the future when I need it. If you have Wordpress, it is better to use Engintron, than to fill your Wordpress plugins. It's my private opinion.

**Comment by fevangelou** [comment]
Right...

**Comment by redeventmedia** [comment]
I noticed this too, but it was nothing to do with Engintron.  It was Cloud Linux for me, if I install it, poof, major page load times on DB stuff.  Uninstall it and all works fine again.

**Comment by azizarnold** [comment]
Hi

Anyone figure this out yet? I have the exact same issue doing ab testing. I am however using Cloudlinux aswell.

[root@cp-1 ~]# ab -n 1000 -c 100 https://hidesiteengtron.co.za/
This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking hidesiteengintron.co.za (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:        nginx
Server Hostname:        hidesiteengintron.co.za
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES128-GCM-SHA256,2048,128
Server Temp Key:        ECDH P-256 256 bits
TLS Server Name:        hidesiteengintron.co.za

Document Path:          /
Document Length:        127136 bytes

Concurrency Level:      100
Time taken for tests:   62.060 seconds
Complete requests:      1000
Failed requests:        297
   (Connect: 0, Receive: 0, Length: 297, Exceptions: 0)
Non-2xx responses:      301
Total transferred:      89915040 bytes
HTML transferred:       89463068 bytes
Requests per second:    16.11 [#/sec] (mean)
Time per request:       6206.022 [ms] (mean)
Time per request:       62.060 [ms] (mean, across all concurrent requests)
Transfer rate:          1414.88 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        5   19  28.7      7     125
Processing:    10 5824 2222.9   6691    9286
Waiting:       10 5811 2218.8   6676    9261
Total:         16 5843 2221.5   6699    9293

Percentage of the requests served within a certain time (ms)
  50%   6699
  66%   7111
  75%   7319
  80%   7491
  90%   7844
  95%   8107
  98%   8451
  99%   8599
 100%   9293 (longest request)

Then on Apache MPM-Event with mod_lsapi

[root@cp-1 ~]# ab -n 1000 -c 100 https://hidesiteapache.co.za/
This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking hidesiteapache.co.za (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:        Apache
Server Hostname:        hidesiteapache.co.za
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,2048,256
Server Temp Key:        X25519 253 bits
TLS Server Name:        hidesiteapache.co.za

Document Path:          /
Document Length:        288 bytes

Concurrency Level:      100
Time taken for tests:   4.969 seconds
Complete requests:      1000
Failed requests:        43
   (Connect: 0, Receive: 0, Length: 43, Exceptions: 0)
Non-2xx responses:      957
Total transferred:      5955042 bytes
HTML transferred:       5742464 bytes
Requests per second:    201.24 [#/sec] (mean)
Time per request:       496.918 [ms] (mean)
Time per request:       4.969 [ms] (mean, across all concurrent requests)
Transfer rate:          1170.31 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       11   72  22.6     70     138
Processing:    11  143 479.8     41    3783
Waiting:        7  128 460.8     30    3765
Total:         49  215 481.7    113    3852

Percentage of the requests served within a certain time (ms)
  50%    113
  66%    125
  75%    134
  80%    143
  90%    206
  95%    321
  98%   2449
  99%   3137
 100%   3852 (longest request)


I set the proxy address as per documentation so cloud flare works fine. 
I even disabled CSF and even added the port configs as requested when its was on. No change
I even set the websites to have no limits at all of LVE via cloudlinux. But same result.

Its weird. not sure where to look now

**Comment by fevangelou** [comment]
CloudLinux imposes all sorts of limitations. Either use CentOS & Engintron or use whatever CloudLinux provides.

**Comment by warmwhisky** [comment]
I believe I am experiencing this also. I am on Centos 7 and WHM.

**Comment by fevangelou** [comment]
Believing is one thing. Measuring is another.

**Comment by warmwhisky** [comment]
I did measure. I found the request on a few test pages took 2 seconds without Engintron and then 35 with Engintron. I had no choice but to uninstall. Everything appeared to be installed and working correctly according to the plugin page in WHM.

**Comment by fevangelou** [comment]
Having Engintron disabled. try using CloudFlare for some domain. Does the given domain's performance improve or not?

**Comment by warmwhisky** [comment]
I do not use CloudFlare unfortunately.
