### ISSUE TITLE
Engintron and /wp-admin/admin-ajax.php 404 (Not Found)

### ISSUE THREAD

**Issue by Lucianciurea** [engintron/engintron#763]
Hello,

I noticed that if I did not install https (SSL) on a wordpress site i got this error: http://i65.tinypic.com/29ut81w.png

I have set up:
location ~ /wp-admin/admin-ajax\.php {
    try_files $uri =404;
     
     # With php5-fpm
    fastcgi_intercept_errors on;
    fastcgi_pass 127.0.0.1:9000;
     
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
    }

and still working only on https wordpress websites.

Thanks.

**Comment by fevangelou** [comment]
You should not alter Nginx's configuration.
