### ISSUE TITLE
OCSP stapling instructions

### ISSUE THREAD

**Issue by rvencu** [engintron/engintron#764]
Hi, I try to setup OCSP stapling in Apache and it fails. Can you tell if it should work transparently or do I need to configure Ngunx specifically to allow this?

**Comment by rafaelmagic** [comment]
I found OCSP lines in the following file:

/etc/nginx/conf.d/default_https.conf

It looks like you have to uncomment the following lines:

  #ssl_trusted_certificate /var/cpanel/ssl/cpanel/mycpanel.pem;
  #ssl_stapling on;
  #ssl_stapling_verify on;

Then Restart Apache & Nginx.

Have not tried it myself so please report if it works..

**Comment by rvencu** [comment]
Thanks. I found elsewhere in the issues that the author decided to disable OCSP stapling because it introduces more problems than it solves. So I guess I'll wait for a future, better implementation...
