### ISSUE TITLE
Serve php files with Apache in Engintron

### ISSUE THREAD

**Issue by Lucianciurea** [engintron/engintron#765]
Hello,

Do you know what is the configuration to serve all php files with Apache in Engintron?

Thanks.

**Comment by fevangelou** [comment]
PHP files are already served by Apache.

**Comment by Lucianciurea** [comment]
I have some php file not found if the ssl is not activated for a specific domain....

**Comment by fevangelou** [comment]
Look for .htaccess rules that cause issues.
