### ISSUE TITLE
Unable to use redirect.conf file with list of redirections

### ISSUE THREAD

**Issue by devteam9200** [engintron/engintron#767]
Hi,

I have migrated a website from ubuntu nginx to our wHM with engintron.

The old server had a redirect.conf file with 500 or so redirects in it. 

I am having trouble setting this up in Engintron. If i add it to the /etc/nginx/conf.d/default_https.conf file 
with that server directive it works (temporarily) until engintron restarts or server reboots then it is lost (of course due to needing to use custom config i understand that).

But when i add the below to custom rules conf in wHM engintron plugin it doesnt work anymore (it used to at one stage):

include /home/xxxxx/nginx/redirect.conf;

I have save, cleared cache, reloaded configs everything, but the redirects dont work.

How can i add a custom redirect.conf with all the redirects needed for a site for each site with engintron so they work and b) so they remain and are not deleted.

Thanks Guys!

**Comment by fevangelou** [comment]
It's best to leave any such redirection to Apache's .htaccess rules instead of attempting to include a file in Nginx which originates in a /home folder. The latter is very bad in security terms. Example: https://blog.tarq.io/root-your-box-with-w3tc-and-nginx/

**Comment by devteam9200** [comment]
Ahhh thanks @fevangelou . Would it be ok to use a redirect file that originates in /etc/nginx/conf.d/xxxxx.conf folder? 
Example place all these files into /etc/nginx/conf.d/redirect1.conf  etc etc
Or do all these conf files get removed when engintron is installed upgraded? 

Or is it simply best to do all redirection via Apache full stop. 

Thanks for your great advice much appreciated.

**Comment by devteam9200** [comment]
@fevangelou  thanks for the advice! and the read. All sorted now i just changed all rules in apache 301 rules and saved them in the .htacess file and all working now. All good now. Thank you
