### ISSUE TITLE
Does this count as security problem?

### ISSUE THREAD

**Issue by shahriar-shojib** [engintron/engintron#768]
![image](https://user-images.githubusercontent.com/6505094/37443391-13503772-2836-11e8-80e7-704447393c13.png)

**Comment by jollysolutions** [comment]
I would definitely say so.

**Comment by fevangelou** [comment]
This is only "view" level, I'll restrict it with an update. The actual
files to save are specific and defined in an array, you can't just edit and
save any file.

In any case, if someone has access to this area (root or reseller), viewing
such files is not necessarily a security issue for practical reasons...

**Comment by fevangelou** [comment]
Resolved in https://github.com/engintron/engintron/commit/78322c4fa122df042be6f3b6e0370738aa7ed08f

**Comment by fevangelou** [comment]
Example response:

![screen shot 2018-03-16 at 14 09 03](https://user-images.githubusercontent.com/1301787/37519920-b2241344-2923-11e8-9ed1-c8b5ece5cc7b.png)

Enjoy! :)

**Comment by fevangelou** [comment]
...and v1.8.8 released. See here for more: https://github.com/engintron/engintron/wiki/Changelog
