### ISSUE TITLE
Add 'reuseport' to default 80 and 443 listen blocks

### ISSUE THREAD

**Issue by cloudunboxed-olorinhenderson** [engintron/engintron#771]
Nginx stable and mainline are both capable of using the Linux 'so_reuseport' socket option, which allows multiple nginx worker process to listen to port 80 and 443 at the same time. The kernel can offload connections faster and bypasses queueing, which in turn speeds up connections and lowers server load.

The 'reuseport' option can simply be appended to the end of the 'listen' line in default.conf and /etc/nginx/utilities/https_vhosts.php - eg:

**/etc/nginx/conf.d/default.conf**
Line 12: `listen 80 default_server reuseport;`

**/etc/nginx/utilities/https_vhosts.php**
Line 44: `listen '.NGINX_HTTPS_PORT.' ssl http2 default_server reuseport;`

**Comment by imagina** [comment]
That's a nice feature but it's compatible only with Kernel > 3.9 and nginx dies when kernel is not compatible:

"nginx: [emerg] reuseport is not supported on this platform,"

So i think it can't be added like a default option.

**Comment by fevangelou** [comment]
I could check "uname -r" for the Kernel version and append that option dynamically. I'll note it down.

Thanks guys!

**Comment by fevangelou** [comment]
Noted to include in the next update.

**Comment by gitfan2** [comment]
Hello. Is this and your other contribution (Offload HTTPS traffic to Nginx only) compatible with CloudFlare? Thanks. Norman

**Comment by fevangelou** [comment]
Yes, it is.

**Comment by fevangelou** [comment]
@cloudunboxed-olorinhenderson CloudFlare will always proxy traffic to the origin server for dynamic (HTML) content. They don't do any web acceleration for dynamic content unless the CDN is configured so and ONLY for the 200 USD/m plan or the enterprise plan. So the benefit of using Engintron is of course valid.

**Comment by cloudunboxed-olorinhenderson** [comment]
@fevangelou Let's not get it twisted. The fact is, Engintron is **only** better/faster sitting in front of Apache when the website is serving lots of static or _lightly dynamic_ content. Furthermore, it is **only** faster when operating directly facing the visitors, **NOT** through a reverse proxy.

Apache, even 2.4 with mod_mpm_event or mod_mpm_worker, is not as efficient as Nginx at handling lots of **connections**. Connections, only connections.  Apache can serve **FILES** all day everyday faster than the network uplink. So in the case of CloudFlare, who embrace keepalives at a PoP level, Engintron will never ever be faster than raw Apache, since it is pummeling traffic around the end user's server twice/thrice for no reason.

**Comment by fevangelou** [comment]
@cloudunboxed-olorinhenderson Riiight...
