### ISSUE TITLE
Any plans for adding php handling with php-fpm directly in nginx not in apache ? 

### ISSUE THREAD

**Issue by shahriar-shojib** [engintron/engintron#773]
I know it's a lot to ask but it would be cool to have such an option.
Also, adding a cPanel interface for users to add their own nginx conf directly from cPanel would be very interesting.

**Comment by fevangelou** [comment]
Nginx is not really built for users to add rules. If the configuration parser fails because of a syntax mistake, Nginx is blown sky high. Engintron's Nginx as it is now is your best bet for a middle solution that combines speed/performance with cPanel's ease of use.
