### ISSUE TITLE
Cloudlinux LVE Manager not detecting traffic with Engintron

### ISSUE THREAD

**Issue by couturelp** [engintron/engintron#774]
Hello everyone,
                 after migrating from Centos7 to CloudLinux using their migrate script, I cannot get Engintron to play well with Cloudlinux LVE. Once Cloudlinux Kernel is active, all processes from Nginx show up as "Nginx : worker process" from user "nginx". Process used to appear correctly on Centos7, running under their respective user account name.

Currently Cloudlinux does not detect any activity or traffic on any of my websites, when Cloudlinux is active. It detects them perfectly as soon as I disable Engintron and fall back onto Apache however. I tried and search everywhere and really can't find a solution.

I tried : 
Migrating with Engintron enabled : same result.
Uninstalling Engintron, migrating, resintalling engintron : same result.

Any help would be greatly appreciated!

Best regards,
Louis

**Comment by caroyy** [comment]
Hi,

I have the same issue as well. Lve manager just stopped showing the speed.

**Comment by caroyy** [comment]
Hi Louis,

Can you try to restart apache and nginx? My lve manager seems to be updating after restart apache and nginx. U should try too.

**Comment by fevangelou** [comment]
"nginx" was always the user configured in /etc/nginx/nginx.conf.
