### ISSUE TITLE
Caching HTML in Dynamic Sites?

### ISSUE THREAD

**Issue by rafaelmagic** [engintron/engintron#775]
Hi,

Currently using a Wordpress Caching Plugin.

So the website is cached to wp-content/cache. I am using .htaccess to redirect requests to wp-content/cache/index.html.

I want to cache html longer at Nginx level. In the proxy_params_dynamic file, I set proxy_cache_valid      200 60m;

Will this cache HTML for 60 minutes? Or do I have to add a location nginx config like below?

location / {
    try_files /wp-content/cache/cache-enabler/$http_host/$request_uri/index.html $uri $uri/ /index.php?$args;
}

I might be overthinking this...

**Comment by fevangelou** [comment]
You are right, dynamic caching (aka HTML caching) is set to 60m with this
change. Easy peasy.

**Comment by rafaelmagic** [comment]
@fevangelou 

Spent some time and determined that expires is setting the Expires Header. 

What do you think about the Cache-Control header, is it also necessary to have both Expires and Cache-Control or is Expires enough. What is your insight with using Engintron?? Or does Expires offer better control with Nginx micro caching. Or if Cache-Control may be of benefit, should it just be Cache-Control "public" or Cache-Control "public max-age=120"?

Thanks

**Comment by fevangelou** [comment]
Cache-Control and Expires is the same thing to Nginx.

These values control client-side caching. Nginx's dynamic cache refers to
server-side caching which reduces the load on Apache and therefore the
system.
