### ISSUE TITLE
Bypass Apache completely for static files

### ISSUE THREAD

**Issue by rvencu** [engintron/engintron#776]
I found this project: https://github.com/maximejobin/rocket-nginx and it proposes to bypass completely the Apache and PHP for static files. Would that be advisable? I tried the setup but apparently there is no proper root setting for virtual hosts in Nginx. What I mean is that it tries to deliver static files directly but fails with 404 error and this in error log:
[error] 22051#22051: *3657 open() "**/etc/nginx/html**/wp-content/themes/swift/images/rp-dummy.png" failed (2: No such file or directory)

**Comment by fevangelou** [comment]
Nginx does that already with static file caching. Read the wiki on GitHub
to understand more on how Engintron works.

**Comment by rvencu** [comment]
thank you for clarification

**Comment by imagina** [comment]
It does it only for 1 second and it implies a duplicated file in /tmp.    Not very good. 

I think it should completely bypass Apache like the old plugin nginxcp use to do it but for this we should generate all the vhosts configurations like it's done already for https in  /etc/nginx/utilities/https_vhosts.sh.

**Comment by fevangelou** [comment]
You're wrong, sorry. Dynamic caching at 1 sec works miracles on sudden
traffic spikes. And as for that other plugin you mention, try skimming
through their code: it never worked properly on any level in regards to
Nginx.

**Comment by rvencu** [comment]
Guys, I cannot take part of the debate since I have much less knowlegde about how Nginx and Apache works. What I am after is a fast webpage, as fast as possible for my hardware. My website is not getting spikes, I am almost always under 10 concurrent web connections and I have lots of underused CPU and RAM.
I guess that if Nginx could deliver the static file directly from its location then I can skip some of the processing done by Engintron, and subsequent WP Rocket/PHP scripts, etc. But I might be wrong and the apparent gain could be bombed by various setup and maintenance issues that would arise.
I can only hope the experts will judge and find a better way to do things. So please keep up your good work.

**Comment by fevangelou** [comment]
@rvencu Engintron's Nginx is setup to cover that. So you're fine.
