### ISSUE TITLE
'Welcome to Nginx on Fedora' notice since updating to 1.8.8

### ISSUE THREAD

**Issue by mcpacific** [engintron/engintron#777]
After upgrading I always get the generic 'Welcome to nginx on Fedora!' page. I've tried emptying the cache, reloading, etc. to no avail.

**Comment by fevangelou** [comment]
You obviously have some repo from Fedora which installs its own copy of
Nginx instead of the official repo.

**Comment by gareth-johnstone** [comment]
I'm also having this issue ... any way to resolve it?

**Comment by gareth-johnstone** [comment]
This appears to be an issue for me as well, all i done was update engintron from WHM and all my domains now contain the welcome page.

**Comment by justua** [comment]
The issue happened after upgrade via yum. the case with epel repo. it issue is fresh. can you fix it on the Engintron side or need to add the ignore nginx package to the epel repo?

The version of Nginx from the epel repo: 1:1.12.2-2.el7

**Comment by gareth-johnstone** [comment]
ok - i've excluded nginx from the epel repo, hopefully fixes the issue

**Comment by justua** [comment]
tested, works for me:
yum remove nginx
add to file /etc/yum.repos.d/epel.repo the line: exclude=nginx*
yum clean all
/engintron.sh remove
/engintron.sh install

**Comment by mcpacific** [comment]
Thanks justua, all good now!

**Comment by fevangelou** [comment]
I assume all you guys had the EPEL repo installed after cPanel got installed, right?

**Comment by gaza1994** [comment]
I did yes!

**Comment by mcpacific** [comment]
Yes, same here.

**Comment by fevangelou** [comment]
Although resolved, I'm re-opening for others to easily search.

**Comment by fevangelou** [comment]
Added to the wiki: https://github.com/engintron/engintron/wiki/%22Welcome-to-Nginx-on-Fedora%22-showing-on-all-sites-after-upgrading-Engintron-or-cPanel

**Comment by evolvingant** [comment]
None of this worked for me. Still showing Welcome to Nginx.

**Comment by fevangelou** [comment]
It's been 2 years since that. Care to provide more details?
