### ISSUE TITLE
Nginx is not serving home pages with nginx 1.12.2

### ISSUE THREAD

**Issue by rvencu** [engintron/engintron#778]
I had engintron (with nginx stable) installed and after a yum update the nginx was updated to 1.12.2
At this moment none of the homepages from all accounts were functioning anymore, the default nginx index.html was displayed instead. All other pages were working properly

I disabled engintron. I ran yum remove nginx. I reinstalled engintron but with mainline nginx version this time that loaded nginx 1.13.10. All sites were functioning properly. I ran yum update and there was no update available.

**Comment by conecta6** [comment]
same problem here after update engitron to last version

**Comment by laracroftonline** [comment]
I don't even get to version 1.13.10 no matter what i try.

**Comment by fevangelou** [comment]
Did the "default" page load a "Fedora" message? See this as well: https://github.com/engintron/engintron/issues/777

**Comment by fevangelou** [comment]
Added to the wiki: https://github.com/engintron/engintron/wiki/%22Welcome-to-Nginx-on-Fedora%22-showing-on-all-sites-after-upgrading-Engintron-or-cPanel
