### ISSUE TITLE
Engintron Blocks all websites

### ISSUE THREAD

**Issue by dexterhussain** [engintron/engintron#779]
I have a running Production Server of WHM on my own VPS in Azure. Whenever I activate Engintron all of my websites go down and I cannot see why it is happening? Moving ahead my websites use *:443

**Comment by fevangelou** [comment]
If you have a firewall, make sure ports 8080 and 8443 are not blocked, so Nginx can forward traffic and retrieve content from Apache.

**Comment by dexterhussain** [comment]
Why 8080 ? Nginx should work on 80 ? Isn't ? This 8080 case I cannot
understand. Apache and Nginx both are on same machine.. Apache port should
be changed why Nginx is being changed ?

**Comment by fevangelou** [comment]
When you enable Nginx, it must assume control of ports 80 and 443 to serve HTTP and HTTPS traffic respectively. Apache is switched to 8080 and 8443 respectively. Nginx then proxies traffic from port 80 to 8080 for HTTP content and from port 443 to 8443 for HTTPS content. If ports 8080 and 8443 are somehow blindly blocked in your firewall, Nginx will not be able to proxy traffic to Apache.
