### ISSUE TITLE
Login problems on Joomla

### ISSUE THREAD

**Issue by drjjw** [engintron/engintron#78]
Hello,

Using Engintron 1.6 on Joomla 3.4.8, PHP 5.6 (Opcache enabled). Speed inprovements are noticeable however, I am having problems with logging in to a Joomla site with the plugin enabled - the page simply reloads without showing restricted content. Disabling all Joomla caching did not help. Disabling Engintron seems to solve. Can you suggest how I might fix this issue with Engintron enabled?

Jordan

**Comment by fevangelou** [comment]
That's a first to hear as we have dozens of Joomla sites deployed on servers we manage for other companies and we've never had an issue, especially with sites with user generated content. Can you provide a URL to your site to examine its page headers please?

**Comment by drjjw** [comment]
Hello Fotis,

I had to disable the plugin as the server is active but before doing so, I grabbed the response header for the page in question:

Response
Cache-Control
no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cache-Control
no-transform
Connection
keep-alive
Content-Encoding
gzip
Content-Type
text/html; charset=utf-8
Date
Tue, 16 Feb 2016 13:42:43 GMT
Expires
Mon, 1 Jan 2001 00:00:00 GMT
Last-Modified
Tue, 16 Feb 2016 13:42:39 GMT
P3P
CP="NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM"
Pragma
no-cache
Server
nginx
Set-Cookie
8914c2e5004331afab5178a038be9603=e96e050cfdccea53b68ba9ea9a832729;
path=/;
HttpOnly
Set-Cookie
c0a2a6946cbcc7dbb2748aa0c74f330a=en-GB;
path=/
Transfer-Encoding
chunked
Vary
Accept-Encoding
X-Cache-Status
UPDATING
X-Content-Type-Options
nosniff
X-Frame-Options
SAMEORIGIN
X-Logged-In
False
X-Powered-By
PHP/5.6.15
X-Server-Powered-By
Engintron
X-XSS-Protection
1; mode=block
With the plugin disabled, I get:

Cache-Control
no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cache-Control
no-transform
Connection
Keep-Alive
Content-Encoding
gzip
Content-Type
text/html; charset=utf-8
Date
Tue, 16 Feb 2016 13:47:56 GMT
Expires
Mon, 1 Jan 2001 00:00:00 GMT
Keep-Alive
timeout=5, max=148
Last-Modified
Tue, 16 Feb 2016 13:47:57 GMT
P3P
CP="NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM"
Pragma
no-cache
Server
Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9
Transfer-Encoding
chunked
X-Content-Type-Options
nosniff
X-Frame-Options
SAMEORIGIN
X-Logged-In
False
X-Powered-By
PHP/5.6.15
X-XSS-Protection
1; mode=block

The URL in question is:

http://ukid.cc/216nLVM

You can test login with user/pass: fotis / fotis

Jordan

**Comment by fevangelou** [comment]
I don't see a problem either with the form or with the headers. It could have been stale Nginx cache (just delete Nginx's cache), because I see the "Updating" value for "X-Cache-Status" which indicates that Nginx is processing the output while you're waiting for the page. In this case, you get served a cached copy but that would expire after 1s either way. The last cached copy was obviously the login page itself. So if it was a slow backend (Apache took longer to respond for some reason), then that could be the culprit. Clearing Nginx's cache either manually of via a cron job will help avoid such conflicts in the future.

**Comment by drjjw** [comment]
Thanks Fotis, I guess the only problem there (from my limited understanding) is that if someone happens upon this form just before the cron runs, they might run in to the same issue. I have re-enabled the plugin but left the micro-caching disabled. And this seems to run now without the error - albeit without the benefits of microcaching. You can see it action at the url above, this time with the plugin enabled.

Jordam

**Comment by drjjw** [comment]
...actually 1-2 times out of 10 logins, I can get it to fail again even with microcache off. But still better than with microcache on. With the plugin disabled entirely, can't get it to fail. Weird.

**Comment by fevangelou** [comment]
Out of curiosity, what cache option do you have enabled? Conservative or progressive. If it's the latter, try switching to conservative and enable micro-caching. Something tells me you won't get these errors again.

**Comment by drjjw** [comment]
Believe it or not, I can reproduce this with global and page cache (system plugin) set off.

**Comment by fevangelou** [comment]
I think this is a better solution. If you can modify the plugin or module you use to hide content and make sure that after it redirects to the same page it appends some query string, e.g. /item/23-slug?logged-in, this would force Nginx to create a fresh cache for that file even if the page for guests was accessed by a thousand people at the time (and Nginx would be busy re-generating the cache after each second).

Nginx (like Joomla and many other systems that use caching), matches cache contents with URLs. If the URL does not change but the content does and Nginx is already busy creating the new cache copy, the use might get served the page with the form.

**Comment by drjjw** [comment]
That is very interesting. I will try that!

**Comment by drjjw** [comment]
...by the way, I see you noticed that I use a method to show only-intro text to Guests (which is available on com_content). Its a feature missing from your otherwise incredibly awesome K2.

**Comment by fevangelou** [comment]
It's easier to make this is a K2 plugin so its controls for both listings and items are in one place. Noting it down.

**Comment by drjjw** [comment]
I'm sure there is a more elegant way. This was my workaround :)

**Comment by drjjw** [comment]
Fixed!

For those affected by this, in:

/modules/mod_login/helper.php 

change:

`else
		{
			// Stay on the same page
			$url = JUri::getInstance()->toString();
		}

		return base64_encode($url);`
to:

`else
		{
			// Stay on the same page
			$url = JUri::getInstance()->toString();
			$urlappend = '?logged-in';
			$url2 = $url . $urlappend;
		}

		return base64_encode($url2);`

Jordan

**Comment by fevangelou** [comment]
Nice. I bet if you wanted to contribute this to Joomla, even with a parameter to be able to change that extra query string, it would take at least 2 years of begging the core team to get it integrated...

**Comment by drjjw** [comment]
Haha. You would know better than me, I'm sure.

**Comment by drjjw** [comment]
I just realized an issue with this fix. If someone shares the link with the
?appended then on login there will be a double ?appeneded.
>
>

**Comment by fevangelou** [comment]
You could check if it already exists otherwise append it. That's a more
solid solution.
