### ISSUE TITLE
 slowloris protection

### ISSUE THREAD

**Issue by dexterhussain** [engintron/engintron#780]
I wanted to ask is there any slowloris protection in engintron configuration ?

**Comment by fevangelou** [comment]
If you follow the optimization guides here https://github.com/engintron/engintron/wiki#beyond-engintron---optimization-guides (and especially lower the timeout option in Apache), Engintron's Nginx configuration will cover you from Slowloris attacks. I would also recommend installing CSF and configuring CT_LIMIT to a value like 100, 200 or 300 to cover simpler attacks, e.g. using ApacheBench or Siege.

Some insights on Nginx/Slowloris (which are covered by my optimization guides mentioned above): https://hexadix.com/slowloris-dos-attack-mitigation-nginx-web-server/
