### ISSUE TITLE
After upgrade to 1.8.8 all Sites directing to: Welcome to nginx on Fedora!

### ISSUE THREAD

**Issue by user55777** [engintron/engintron#781]
I just updated Engintron to 1.8.8 and now all the websites on my server are going to a default "Welcome to Nginx on Fedora!" index page. Engintron was working perfectly fine before I updated.

**Comment by user55777** [comment]
I'm running  CLOUDLINUX 7.4 standard [server]  and WHM v68.0.36

**Comment by mediaworksmt** [comment]
I can confirm this issue - The same began happening across the board with all of our websites almost immediately after upgrading to Engintron v1.8.8 , with cPanel v68.0.36 and CENTOS 7.4

Also running Engintron 1.8.8, Build 20180316, Nginx v1.12.2

We've disabled Engintron for the moment, but would definitely like to continue operating with it soon. :-)

Any help or guidance would be appreciated - Thank you, Engintron Team!

**Comment by user55777** [comment]
Is there a way to downgrade back to the previous version of Engintron?

**Comment by gege1010** [comment]
install the version Engintron [Nginx mainline] , this version Nginx is 1.13.1 and it works

![screenshot_1](https://user-images.githubusercontent.com/5798318/38336934-d4e8bd9a-3863-11e8-8802-59d4a14b3eae.png)

**Comment by fevangelou** [comment]
Already posted (and solved) here: https://github.com/engintron/engintron/issues/777

**Comment by fevangelou** [comment]
Added to the wiki: https://github.com/engintron/engintron/wiki/%22Welcome-to-Nginx-on-Fedora%22-showing-on-all-sites-after-upgrading-Engintron-or-cPanel

**Comment by user55777** [comment]
Installing "Engintron [Nginx mainline], with Nginx 1.13.11" worked perfectly. Everything is back up and running great again.
