### ISSUE TITLE
SSL - TLSv1.1 on engintron?

### ISSUE THREAD

**Issue by veqsms** [engintron/engintron#783]
Hello friend,

Im new in Cpanel/WHM, and I have one app for Android and I'm trying to make links of my application with https, but android v4.4 uses TLSv1.1 and do not support TLSv1.2, in apache global configuration i make this changes:

SSL Cipher Suite: ALL
SSL/TLS Protocols: ALL

Now TLSv1.1 works perfectly but my app have huge traffic in specific time one php files requested from 5000-10000 users so Apache Server get down, then I install engintron webserver wich works good also one huge traffic but when I enable engintron it seems TLSv1.1 don't work because my app don't work on Android v4.4

My question is:

How to enable TLSv1.1 to work also with Engintron ?

**Comment by fevangelou** [comment]
Engintron's Nginx setup uses the following protocols:
```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
```

So the problem is either in Apache's configuration or somewhere else...

**Comment by veqsms** [comment]
When I disable engintron everything works well, but when I enable it my app stop working on most Android versions,

Does engintron use PHP-FPM by default or I need to enable it anywhere, it is already enabled on MultiPHP Manager

**Comment by fevangelou** [comment]
Nginx does not use PHP-FPM, FastCGI, suPHP or anything else. It proxies traffic to Apache which may retrieve content from PHP via PHP-FPM.

**Comment by veqsms** [comment]
Sorry cuz I'm beginner on servers, but I'm trying hard to configure so I set up Apache but I have to much users and apache goes down, I install engintron but it blocks my app on some android versions 4.4, 5.0, but it works on 8.0.

Maybe I need to make any config on engintron, could you help me please ?

**Comment by fevangelou** [comment]
Nginx has all options enabled. There's nothing more you can do there. Unless you want SSL protocols enabled which apparently should be avoided.

cPanel's Apache uses TLS 1.2 by default in the latest release of cPanel.

See this as well on client compatibility: https://www.ssllabs.com/ssltest/clients.html

Perhaps your problem lies elsewhere.

**Comment by veqsms** [comment]
No, I need SSL to be enabled, also I just install Engintron with the default configuration, So Do I need to config anything extra or just let it with default configs?

**Comment by fevangelou** [comment]
Read the "requirements" in the wiki (here) and then have a look at the troubleshooting section there.
