### ISSUE TITLE
502 Nginx bad gateway

### ISSUE THREAD

**Issue by Shahzadqayyum** [engintron/engintron#784]
Well i just got some wired thing happening with both of my cpanel servers.
Everything was okay 2 days ago.
May if there is some cpanel update.
Not sure. But one of my server started facing this issue after updating nginx to 1.8.8 however other was facing problem at 1.8.7 so i upgraded that too but still same issues.
Site works well and suddenly it shows 502 error and on next refresh site loads in the the browser?
Can you please tell what thing is causing this issue?

**Comment by fevangelou** [comment]
Check the Nginx error logs...

**Comment by Shahzadqayyum** [comment]
thanks for the quick reply.
2018/04/05 03:09:50 [error] 8218#8218: *478571 connect() failed (111: Connection refused) while connecting to upstream, client: 119.160.118.176, server: localhost, request: "GET /wp-content/uploads/2018/04/Screenshot_55-1-300x287.png HTTP/1.1", upstream: "http://23.xx.xx.178:8080/wp-content/uploads/2018/04/Screenshot_55-1-300x287.png", host: "fburdu.club", referrer: "http://fburdu.club/2018/04/02/8248/"
2018/04/05 03:09:50 [error] 8224#8224: *478573 connect() failed (111: Connection refused) while connecting to upstream, client: 103.255.7.13, server: localhost, request: "GET /2018/04/05/5099/ HTTP/1.1", upstream: "http://23.xx.xx.178:8080/2018/04/05/5099/", host: "video.collect.pk", referrer: "http://m.facebook.com/"
2018/04/05 03:09:51 [error] 8221#8221: *478041 connect() failed (111: Connection refused) while connecting to upstream, client: 43.245.9.38, server: localhost, request: "GET /archives/35457 HTTP/1.1", upstream: "http://23.xx.xx.178:8080/archives/35457", host: "dailydaleel.com"
2018/04/05 03:09:51 [error] 8226#8226: *474740 connect() failed (111: Connection refused) while connecting to upstream, client: 119.160.67.140, server: localhost, request: "GET /2018/04/02/8171/ HTTP/1.1", upstream: "http://23.xx.xx.178:8080/2018/04/02/8171/", host: "fburdu.club", referrer: "http://m.facebook.com"
2018/04/05 03:09:51 [error] 8224#8224: *478568 connect() failed (111: Connection refused) while connecting to upstream, client: 119.160.118.176, server: localhost, request: "GET /wp-content/uploads/2018/04/Screenshot_51-1-300x226.png HTTP/1.1", upstream: "http://23.xx.xx.178:8080/wp-content/uploads/2018/04/Screenshot_51-1-300x226.png", host: "fburdu.club", referrer: "http://fburdu.club/2018/04/02/8248/"
2018/04/05 03:09:51 [error] 8218#8218: *478579 connect() failed (111: Connection refused) while connecting to upstream, client: 119.160.118.176, server: localhost, request: "GET /wp-content/uploads/2018/04/Screenshot_1-3-310x165.png HTTP/1.1", upstream: "http://23.xx.xx.178:8080/wp-content/uploads/2018/04/Screenshot_1-3-310x165.png", host: "fburdu.club", referrer: "http://fburdu.club/2018/04/02/8248/"

**Comment by Shahzadqayyum** [comment]
well, only one server has firewall instalHTTP/1.1", upstream: "https://45.xx.xx.38:8443/lib/fancybox/jquery.fancybox.js", host: "www.domain.com", referrer: "https://www.domain.com/"
2018/04/05 05:30:32 [error] 1366#1366: *6324 connect() failed (111: Connection refused) while connecting to upstream, client: 59.2.72.36, server: domain.com, request: "GET / HTTP/1.1", upstream: "https://45.xx.xx.38:8443/", host: "www.domain.com", referrer: "https://yahan.tv/bbs/board.php?bo_table=javc"
2018/04/05 05:30:33 [error] 1365#1365: *6327 connect() failed (111: Connection refused) while connecting to upstream, client: 59.2.72.36, server: domain.com, request: "GET /lib/fancybox/jquery.fancybox.css HTTP/1.1", upstream: "https://45.xx.xx.38:8443/lib/fancybox/jquery.fancybox.css", host: "www.domain.com", referrer: "https://www.domain.com/"
2018/04/05 05:30:33 [error] 1363#1363: *6326 connect() failed (111: Connection refused) while connecting to upstream, client: 59.2.72.36, server: domain.com, request: "GET /images/slider/responsive/%EC%82%AC%EC%9D%B4%ED%8A%B8_%EB%93%B1%EB%A1%9D.png HTTP/1.1", upstream: "https://45.xx.xx.38:8443/images/slider/responsive/%EC%82%AC%EC%9D%B4%ED%8A%B8_%EB%93%B1%EB%A1%9D.png", host: "www.domain.com", referrer: "https://www.domain.com/"
2018/04/05 05:30:33 [error] 1364#1364: *6330 connect() failed (111: Connection refused) while connecting to upstream, client: 59.2.72.36, server: domain.com, request: "GET /lib/fancybox/jquery.fancybox.js HTTP/1.1", upstream: "https://45.xx.xx.38:8443/lib/fancybox/jquery.fancybox.js", host: "www.domain.com", referrer: "https://www.domain.com/"
2018/04/05 05:30:34 [error] 1365#1365: *6332 connect() failed (111: Connection refused) while connecting to upstream, client: 115.143.98.28, server: domain.com, request: "GET / HTTP/1.1", upstream: "https://45.xx.xx.38:8443/", host: "www.domain.com", referrer: "https://yahan.tv/bbs/board.php?bo_table=korea"led :( but facing same problem on both,

**Comment by laracroftonline** [comment]
the same here , even adjust csf and still this error.
2018/04/05 14:08:18 [error] 2335#2335: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 23.227.183.198, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://91.209.70.5:8080/favicon.ico", host: "forums.strongervision.co"
2018/04/05 14:08:28 [error] 2334#2334: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 83.82.225.41, server: strongervision.co, request: "GET / HTTP/2.0", upstream: "https://91.209.70.5:8443/", host: "strongervision.co"
2018/04/05 14:08:28 [error] 2334#2334: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 83.82.225.41, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://91.209.70.5:8080/favicon.ico", host: "strongervision.co"
2018/04/05 14:08:30 [error] 2336#2336: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 23.227.183.198, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://91.209.70.5:8080/favicon.ico", host: "strongervision.co"
2018/04/05 14:09:01 [error] 2773#2773: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 83.82.225.41, server: strongervision.co, request: "GET / HTTP/2.0", upstream: "https://91.209.70.5:8443/", host: "strongervision.co"

**Comment by rvencu** [comment]
It happened to me right now, after CFS has autoupdated from version 12.01 to 12.02
I had to disable Engintron to make sites online again

**Comment by rvencu** [comment]
I reenabled Engintron and all websites work properly now.
