### ISSUE TITLE
Quick question about stats software - is AWStats reliable in Engintron configuration?

### ISSUE THREAD

**Issue by rvencu** [engintron/engintron#785]
If it is reliable, is there anything else that can improve statistics when engintron is active?

We had implemented GDPR rules on our website and unfortunately we have discovered that number of visitors accepting (statistics) cookies is only 30% of the total. So we need to rely now on old statistics software provided by cPanel just to have a proper figure of downscale of the numbers we see in other analytics software. Thus AWStats will have a comeback and I need to make sure I tune it to the best possible extent.

**Comment by rvencu** [comment]
I have cPanel support answer now that point to Engintron as a provider for customization:

> I would not advise attempting to manually adjust AWStats configuration for the account.  Instead, it is generally best to make sure that the Apache log appropriately writes out a log entry that uses the IP address of the public visitor.

> CloudFlare,  for example, provides an Apache plugin that performs this internally so that all statistics are accurate (not just AWStats).

> Since you are running a custom installation (NGINX), it would be something you would need to investigate, troubleshoot, and implement independently.  However, that would be the advised route.

**Comment by fevangelou** [comment]
When you update Apache's config, you also need to update IP forwarding for Nginx to Apache in Engintron's WHM app. That way logging will work just fine. Or use this https://www.damchey.com/2018/01/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel/ until it's integrated into Engintron.

**Comment by rvencu** [comment]
Used the article and after replacing all h with a (like 6 of them) now the logs show correct IPs. thanks

**Comment by rvencu** [comment]
The IP forwarding stuff did not seem to work. I did it and has no effect.

**Comment by fevangelou** [comment]
Do Apache logs show the user's or the server's IP?

**Comment by rvencu** [comment]
After changing the config file for logging (I remember I modified h int a) it works.

**Comment by sshcli** [comment]
In my case, after install engintron, the https version of my website is not collecting data in awstats.

I did follow the recommendations above:
Change %h for %a + Rebuild Configuration and Restart Apache + Restore Nginx IP forwarding in Apache + Update awstats

Still no data in awstats

What else can I do to fix this problem?

**Comment by fevangelou** [comment]
How long did you wait to check if AWstats for HTTPS show up?

**Comment by sshcli** [comment]
Just 15 minutes, and hit the update button several times in awstats

**Comment by fevangelou** [comment]
Perhaps it requires more time. Or it just doesn't work on your server or something changed in AWstats.

I would recommend a better logging tool either way which can hook up to Nginx directly. Check out GoAccess which can also work real-time. Much better and it can also give you a birds-eye view for your entire server.

**Comment by sshcli** [comment]
Ok, I will try it. Thanks for the recommendation.

**Comment by fevangelou** [comment]
You're welcome.

**Comment by sshcli** [comment]
Just FYI
Awstats is collecting data.
if engintron enabled-> Data is collected under http version of the website in awstats
if engintron disabled-> Data is collected under HTTPS version of the website in awstats
