### ISSUE TITLE
Bind issue while csf is correctly configured.

### ISSUE THREAD

**Issue by laracroftonline** [engintron/engintron#786]
Since 1.8.8 i got this issue

2018/04/05 14:28:25 [emerg] 9330#9330: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/04/05 14:28:25 [emerg] 9330#9330: bind() to 0.0.0.0:443 failed (98: Address already in use)
2018/04/05 14:28:25 [emerg] 9330#9330: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/04/05 14:28:25 [emerg] 9330#9330: bind() to 0.0.0.0:443 failed (98: Address already in use)
2018/04/05 14:28:25 [emerg] 9330#9330: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/04/05 14:28:25 [emerg] 9330#9330: bind() to 0.0.0.0:443 failed (98: Address already in use)
2018/04/05 14:28:25 [emerg] 9330#9330: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/04/05 14:28:25 [emerg] 9330#9330: bind() to 0.0.0.0:443 failed (98: Address already in use)
2018/04/05 14:28:25 [emerg] 9330#9330: bind() to 0.0.0.0:80 failed (98: Address already in use)
2018/04/05 14:28:25 [emerg] 9330#9330: bind() to 0.0.0.0:443 failed (98: Address already in use)
2018/04/05 14:28:25 [emerg] 9330#9330: still could not bind()
2018/04/05 14:28:28 [error] 9392#9392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 83.82.225.41, server: forums.strongervision.co, request: "GET / HTTP/2.0", upstream: "https://91.209.70.5:8443/", host: "forums.strongervision.co", referrer: "https://forums.strongervision.co/index.php?/topic/1-welcome/"

But i really applied everything you said into csf.

**Comment by fevangelou** [comment]
Disable and re-enable Engintron to attempt to resolve the issue. Apache did not have it's ports changed and Nginx cannot bind to ports 80 & 443.

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.
