### ISSUE TITLE
Error : Connection Refused

### ISSUE THREAD

**Issue by josephmiller2000** [engintron/engintron#788]
Nginx Version : 1.8.8
Cpanel Version : v68.0.36

This happened to my two servers. Installed engintron and getting connection refused message while engintron is enabled.

After removing engintron,. it works fine.

**Comment by KarlAustin** [comment]
Could be the same issue I'm having.  It hasn't generated anything in /etc/nginx/conf.d at all - in fact the conf.d directory doesn't exist for me! So all virtual hosts are down if I enable it.

**Comment by Sherbi** [comment]
I have the same issue this directory not exist on my server

> Could be the same issue I'm having. It hasn't generated anything in /etc/nginx/conf.d at all - in fact the conf.d directory doesn't exist for me! So all virtual hosts are down if I enable it.  <

**Comment by fevangelou** [comment]
Are you sure you're using Engintron?

**Comment by Sherbi** [comment]
Sure !!! Is it joke ?? Of force I make install for engintron 1.8.8 when I check config found that Virtual host on /etc/nginx/conf.d but it doesn't exist on server

Regards,

**Comment by KarlAustin** [comment]
> Are you sure you're using Engintron?
Seriously?  You come out with a comment like that when the installer carries on an install instead of checking for what appears to be a known issue, and all sites redirect to nginx holding page if you've got EPEL repo enabled.  Your "workaround" for this, then results in no configuration being generated at all, and sites not responding at all.

**Comment by fevangelou** [comment]
If you add the EPEL repo and don't understand possible consequences AND you don't check the wiki for troubleshooting, what does that make you? Seriously.

**Comment by rallisf1** [comment]
I have the same problem. The EPEL repo was pre-added to my vps' centos 7.4 image and i had no clue. Anyway i followed the [steps](https://github.com/engintron/engintron/wiki/%22Welcome-to-Nginx-on-Fedora%22-showing-on-all-sites-after-upgrading-Engintron-or-cPanel) from the wiki but still have the same problem. btw the /etc/nginx/conf.d folder was completely missing so i created it and copied the default.conf from the [source](https://github.com/engintron/engintron/blob/master/nginx/conf.d/default.conf). Restarted everything and once again i get the default nginx homepage on all domains. I have disabled engintron until resolved.

Please provide a guide to restore the vhosts configuration for nginx when you have the time. Thanks in advance.

**Comment by fevangelou** [comment]
Tried re-installing Engintron?

**Comment by rallisf1** [comment]
of course

**Comment by fevangelou** [comment]
Re-install from WHM and then copy back the installation log please.

**Comment by josephmiller2000** [comment]
Re installed twice using SSH command codes and.. then even re-installed through WHM plugin section"re install stable"

Nothing helping, you guys should look into this,

**Comment by rallisf1** [comment]
here is [mine](https://gist.github.com/rallisf1/9266ef7055886ff6a9465ddf2b1277ed)

**Comment by fevangelou** [comment]
Your Nginx installation seems borked. Did you have another plugin for Nginx
installed before Engintron?

**Comment by fevangelou** [comment]
I've setup dozens of cPanel servers on Contabo. There is no issue with
those. You have custom repositories added. You need to dig around and see
if some other than EPEL causes issues.

If you don't get the conf.d folder in /etc/nginx you might be dealing with
an Nginx installation from another repo.

Alternatively, uninstall Engintron and then manually delete /etc/nginx.
Finally re-install Engintron.

**Comment by rallisf1** [comment]
I did what you said and it worked ^^

I am not sure what exactly caused the problem (probably another repo?)

For everyone with the same problem here are the steps:

1. Uninstall engintron
2. go to /etc/yum.repos.d and rename everything (just add a dot in the end) except centos*.repo, cPAddons.repo, cpanel-plugins.repo, EA4.repo
3. remove /etc/nginx
4. install engintron
-- Optional steps for IPv6 (else you will get connection refused on IPv6 requests)
5. Follow this [guide](https://github.com/engintron/engintron/wiki/Enable-IPv6-support-in-Nginx)

Thank you Fotis for your wonderful work and support even on holidays!

**Comment by fevangelou** [comment]
It would also help others if you could list the repositories you ended
commenting out ;)

**Comment by robwent** [comment]
These are the repos I renamed:

    cd /etc/yum.repos.d
    mv epel.repo epel.repo.
    mv mysql-community.repo mysql-community.repo.
    mv epel-testing.repo epel-testing.repo.
    mv mysql-community-source.repo mysql-community-source.repo.

and back

    mv epel.repo. epel.repo
    mv mysql-community.repo. mysql-community.repo
    mv epel-testing.repo. epel-testing.repo
    mv mysql-community-source.repo. mysql-community-source.repo

This was on a server from hivelocity
