### ISSUE TITLE
proxy server nodejs

### ISSUE THREAD

**Issue by garrablanka** [engintron/engintron#789]
Hello

I have created a node program that it's working on http://mydomain:3000/node/index.js and I want to "hide" the port (3000).

I have been reading that I need the a proxy server so I installed engintron and configured different ways but I can't reach what I want.

For example I have used:

> server {
> listen here.is.my.ip:80;
> server_name www.mydomain.com mydomain.com;
> location /node {
> proxy_pass http://here.is.my.ip:3000;
> }
> }
> 

Please help!
Thanks

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.

**Comment by obxion** [comment]
y que hiciste? cambiaste engintron por otro?
