### ISSUE TITLE
Cannot Allocate Memory

### ISSUE THREAD

**Issue by swartjie** [engintron/engintron#790]
Hey Guys,

Can you please assist?
I setup enginetron a while back but deactivated it at first. When I try to activate it now, I am getting a  lot of error messages in the logs as below. What might be the cause?
On a side note (not sure if it is related), all certificates are showing insecure aswell.

2018/04/10 07:48:31 [emerg] 410029#410029: posix_memalign(16, 16384) failed (12: Cannot allocate memory)
2018/04/10 07:51:16 [emerg] 412580#412580: posix_memalign(16, 16384) failed (12: Cannot allocate memory)
2018/04/10 07:54:15 [emerg] 414498#414498: pread() returned only 0 bytes instead of 4066 in /etc/nginx/conf.d/default_https.conf:10928
2018/04/10 07:54:17 [emerg] 414534#414534: bind() to 0.0.0.0:443 failed (98: Address already in use)
2018/04/10 07:54:19 [error] 414541#414541: *1 access forbidden by rule, client: 66.249.75.26, server: localhost, request: "GET /fire-blog/ HTTP/1.1", host: "domain.tld"
2018/04/10 07:54:21 [error] 414541#414541: *9 access forbidden by rule, client: 207.46.13.204, server: localhost, request: "GET /robots.txt HTTP/1.1", host: "domain.tld"
2018/04/10 07:54:23 [error] 414540#414540: *17 access forbidden by rule, client: 207.46.13.204, server: localhost, request: "GET /robots.txt HTTP/1.1", host: "domain.tld"

Can you please advise on what might be the memory error's cause and if these other error's should be happening, or if it is part of the problem?

**Comment by fevangelou** [comment]
Uninstall and reinstall for starters. I see various errors from your log
and the Engintron installer will attempt to fix them on it's own.

**Comment by swartjie** [comment]
I have done a full uninstall and reinstall. The normal http websites work, but https does not.
When I do a full restart of the services I notice this again in the logs: 
Restarting Nginx...
nginx: [emerg] posix_memalign(16, 16384) failed (12: Cannot allocate memory)
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by fevangelou** [comment]
What does `nginx -t` output?

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.

**Comment by fevangelou** [comment]
(sidenote: if you don't have the RAM for the few MBs that Nginx will use, you clearly have bigger issues to solve)

**Comment by swartjie** [comment]
Hey Guys, Sorry I never got the response emails from the site. Went to spam...
I decided to disable it a while back, because the ssl certificates were becoming a big problem. After a new SSL was added I had to jump through 500 hoops to try and get it to work. It just would not load the SSL while apache would load it.

And the memory is not a problem, I have 32GB of RAM currently not used on the server, it's more a matter of it is not allowed to allocate the ram. Not sure why though...
Would love to get it working though, but I assume the SSL still needs some fine tuning to better operate..

**Comment by fevangelou** [comment]
First off, since this could be related to the Nginx binary installed at the time, simply re-install Engintron to get the latest Nginx build.

If this does not solve the issue, then in /etc/nginx/nginx.conf, try setting "worker_processes" first to value "1" and then to the count of your CPUs (if you have 4 CPUs, add "4"). Restart Nginx and see the issue is resolved. There are very few references for this error. The solution I provide was given by Nginx directly.
