### ISSUE TITLE
Error creating subdomains

### ISSUE THREAD

**Issue by DanielRivera1309** [engintron/engintron#791]
Hello!

When a subdomain is created in cPanel ( v68.0.36 ) we're receiving a 502 Bad gateway error asi you can see for example in: http://ah.cecytlax.edu.mx/

This is happen only with new subdomains. All previous subdomains are working ok.

This is happen in all servers with engintron (v1.8.8)

Thanks in advance!

**Comment by marcelodelta** [comment]
I have the same problem, but with the use of Record A.


endereco.domain..com.br. | A | 00.00.00.00

**Comment by robertmylne** [comment]
I have a similar problem, when creating a website with a subdomain it works initially, then goes down with "503 The server is temporarily unable to service your request due to maintenance downtime or capacity problems" for a few minutes then starts working again.

**Comment by fevangelou** [comment]
@DanielRivera1309 Seems to work on my end.

502 and 503 errors can occurs while Apache is re-building its configuration. If you have servers with tons of sites on them, this can count to minutes until Apache finishes up the new config file.
