### ISSUE TITLE
Not Found Install and config

### ISSUE THREAD

**Issue by veigaeveiga** [engintron/engintron#793]
Hello, I did an installation but when I access the site it stays like this

http://prntscr.com/j3suuz

**Comment by jimcouts** [comment]
Typically this shows up if the site's DNS hasn't propagated. Have you tried from a remote IP or different location?

**Comment by fevangelou** [comment]
Or use this trick: https://github.com/engintron/engintron/wiki/Engintron-&-(under-development)-domains-that-don't-yet-resolve-(point)-to-your-cPanel-server

**Comment by veigaeveiga** [comment]
Tanks ;)
