### ISSUE TITLE
CloudFlare and Engintron

### ISSUE THREAD

**Issue by jimcouts** [engintron/engintron#794]
@fevangelou 

Found something isn't reporting the proper IP when we enable Engintron, something happened just recently where the IP isn't being reported correctly. It's only reporting the server's IP in lieu of the actual IP being passed onto from CloudFlare's Header option. We have all of the following setups accordingly to the documents:

Under custom_rules we have this set appropriately:

`set $PROXY_DOMAIN_OR_IP "216.xxx.xxx.xxx"; # Use your cPanel's shared IP address here`

Which the above is set, before it used to work, where now it's reporting the servers IP to let's say WordPress as the user visiting the site. Now, when we disable Engintron, it works as intended along with CloudFlare -> Apache2 on a cPanel server.

Happy to allow someone access to take a look at the Engintron project and see what we're talking about.

**Comment by fevangelou** [comment]
If the main Apache configuration changed, you need to re-patch it by using "Restore Nginx IP forwarding in Apache". In v1.9.0 I'll use include files in Apache to avoid that.

**Comment by Nirjonadda** [comment]
@fevangelou Do you have any ETA for releasing v1.9.0? Also I am still looking for [nginx-ultimate-bad-bot-blocker](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/29) support, So we are no need re-do Step after every update of Engintron.

Sorry brother for bothering you, Take your time for improvement development.
