### ISSUE TITLE
502 Bad Gateway error

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#797]
Please can you let me know that how to fixing 502 Bad Gateway error? I get solutions for 502 Bad Gateway error with Increase buffer and timeouts inside http block but Does not know where I can add.

````
http {
...
fastcgi_buffers 8 16k;
fastcgi_buffer_size 32k;
fastcgi_connect_timeout 300;
fastcgi_send_timeout 300;
fastcgi_read_timeout 300;
...
}
````

**Comment by ChristianGabs** [comment]
# Buffers
proxy_buffers                 256 16k;
proxy_buffer_size             128k;
proxy_busy_buffers_size       256k;
proxy_temp_file_write_size    256k;

# Timeouts
proxy_connect_timeout         180s;
proxy_read_timeout            240s;
proxy_send_timeout            240s;

You can find in proxy_params_common
