### ISSUE TITLE
APCU

### ISSUE THREAD

**Issue by ChristianGabs** [engintron/engintron#798]
Whoops\Exception\ErrorException: PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php70/root/usr/lib64/php/modules/apcu.so' - /opt/cpanel/ea-php70/root/usr/lib64/php/modules/apcu.so: cannot open shared object file: No such file or directory in Unknown:0

https://github.com/engintron/engintron/wiki/Beyond-Engintron:-Install-APC(u)-in-cPanel

Use this

**Comment by ChristianGabs** [comment]
Try multiple time, same.

Looking this path I don't see apcu.so

**Comment by ChristianGabs** [comment]
Fixed
disable_functions restricted some extension.

Thank you

**Comment by fevangelou** [comment]
Resolved?

**Comment by fevangelou** [comment]
You'll have to send me the APCu installation log from the terminal,
otherwise I can't know what's wrong.

**Comment by fevangelou** [comment]
Forgot to ask: you ARE using EasyApache 4, right?

**Comment by ChristianGabs** [comment]
Yes
CENTOS 7.4 kvm [web]  v68.0.36

**Comment by fevangelou** [comment]
Although it's not complete, I don't see anything wrong with it. Switch to another PHP version to verify.

**Comment by ChristianGabs** [comment]
The rest is same, I try to avoid set massive text. I'm doing few testing but it seems the exec() need to be active as well.

I will come back with news.

Thank you

**Comment by fevangelou** [comment]
Engintron uses cPanel's PHP, not the PHP used for serving websites. Where exactly did you have these functions disabled?

**Comment by ChristianGabs** [comment]
MultiPHP INI Editor. 
By default is coming as empty "disable_functions" I specify to disable few functions just for security propose.

My fault by the point is some people will restrict like me because the security issue you can have as providing hosting.

**Comment by fevangelou** [comment]
In WHM, under Software >> Multi PHP whatever, the PHP chosen as the default in the system is what appears to also be used by the APCu installer. So make sure that the required functions for PECL are open for the installation to proceed. After that, simply add the restrictions back in.
