### ISSUE TITLE
Auto SSL issue with Engintron

### ISSUE THREAD

**Issue by rahmansherif** [engintron/engintron#800]
The domain is resolving fine and it's hosted on the same server. The AutoSSL is working fine on apache but not with Engintron. Also, I have tried to reinstall Engintron from frontend and backend but still facing the same errors. Please help to resolve the issue.

AutoSSL log
This system has AutoSSL set to use “cPanel (powered by Comodo)”.
Checking websites for “mydomain” …

The website “mydomain.com.ph”, owned by “mydomain”, has a valid SSL certificate, but additional SSL coverage may be possible for the domains “webdisk.mydomain.com.ph”, “webmail.mydomain.com.ph”, and “cpanel.mydomain.com.ph”. The system will attempt to replace this certificate with one that includes these additional domains.
WARN The domain “webdisk.mydomain.com.ph” failed domain control validation: The system queried for a temporary file at “http://webdisk.mydomain.com.ph/.well-known/pki-validation/F21490966F80456D99986F5462B4CE08.txt”, but the web server responded with the following error: 401 (Unauthorized). A DNS (Domain Name System) or web server misconfiguration may exist.
WARN The domain “webmail.mydomain.com.ph” failed domain control validation: The system failed to fetch the DCV (Domain Control Validation) file at “http://webmail.mydomain.com.ph/.well-known/pki-validation/8BA710CB0AF0EAF0AFE690E2E5844E28.txt” because of an error: The system failed to send an HTTP (Hypertext Transfer Protocol) “GET” request to “http://webmail.mydomain.com.ph/.well-known/pki-validation/8BA710CB0AF0EAF0AFE690E2E5844E28.txt” because of an error: Size of response body exceeds the maximum allowed of 16384 .
WARN The domain “cpanel.mydomain.com.ph” failed domain control validation: The system failed to fetch the DCV (Domain Control Validation) file at “http://cpanel.mydomain.com.ph/.well-known/pki-validation/8C03DEBED220E58956BC405E3E40950A.txt” because of an error: The system failed to send an HTTP (Hypertext Transfer Protocol) “GET” request to “http://cpanel.mydomain.com.ph/.well-known/pki-validation/8C03DEBED220E58956BC405E3E40950A.txt” because of an error: Size of response body exceeds the maximum allowed of 16384 .
AutoSSL cannot add any new domains to SSL coverage for the website “mydomain.com.ph”.

**Comment by ChristianGabs** [comment]
https://github.com/engintron/engintron/issues/753

Maybe can help you

**Comment by rahmansherif** [comment]
Thanks, @ChristianGabs 

I will try this and update here

**Comment by Friends4U** [comment]
Version 1.8.8 here and AutoSSL also stopped working today :(
Tried everything in #753 but it didn't do anything for me...

**Comment by Friends4U** [comment]
I don't think it's an Engintron issue, renaming the .htaccess on the sites that do not work fixes the problem. Strange because the problem was never there.

**Comment by Friends4U** [comment]
Contacted CPanel support but it is a Engintron (nginx) problem.
When disabling Engintron the SSL is being renewed, and you have to clear cache manually after enabling again.

**Comment by fevangelou** [comment]
@Friends4U Engintron uses direct certificate references from Apache. If you disable Engintron to update certificates (no reason actually to do so) and re-enable, you have to wait a few seconds for Engintron's cron job to kick in and update these SSL certificates into Nginx's configuration.
