### ISSUE TITLE
Is it possible to setup? websocket reverse proxy in engintron?

### ISSUE THREAD

**Issue by josephmiller2000** [engintron/engintron#801]
location / {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade"; 
	    proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;       
        proxy_read_timeout 10800s;
        proxy_connect_timeout 10800s;
        proxy_send_timeout 10800s;        
        limit_conn perip 2;   
}

This works in standalone nginx. But now in engintron.. any help?

**Comment by ChristianGabs** [comment]
Custom Rules

if($SITE_URI ~* "domain.com")
{
    proxy_set_header  Host $host:9001;
	proxy_set_header  Connection "Upgrade";
	proxy_set_header  Upgrade websocket;
}

should work

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.

**Comment by josephmiller2000** [comment]
Nope not working...

tried many methods.. nothing is helping..

location /chat {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade"; 
	    proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;       
        proxy_read_timeout 10800s;
        proxy_connect_timeout 10800s;
        proxy_send_timeout 10800s;              
        limit_conn perip 10;   
}

**Comment by fevangelou** [comment]
Referencing locations directly will probably not work. Engintron's Nginx setup allows web sockets to pass through. I would recommend adding any changes related to websockets in your .htaccess file.

**Comment by imorandinwnp** [comment]
Hi,
I confirm that Websockets does not work out of the box, the upgrade headers are missing.
I've to made these changes to proxy_params_common:

#proxy_hide_header             Upgrade;
proxy_set_header              Upgrade $http_upgrade;
proxy_set_header              Connection "upgrade";      # Enable keepalives

credits: https://stackoverflow.com/questions/55665199/websocket-handshake-returns-error-400-with-engintron

I don't see any drawbacks so far

**Comment by fevangelou** [comment]
Correct @imorandinwnp - any such changes need to be added globally in proxy_params_common which is the "bootstrap" file for proxying in Engintron.
