### ISSUE TITLE
Opencart problems

### ISSUE THREAD

**Issue by RhuanGonzaga** [engintron/engintron#803]
I'm running latest version of engintron and cPanel and getting trouble when enable engintron because nginx is caching client's shopping cart so my customers are getting products that them don't added on cart, someone knows what is this problem ? Thank you!

**Comment by ChristianGabs** [comment]
Ok so what you need to do is use custom rules:

You need to follow your path where or what will trigger your cart if is a javascript or be redirecting doesn't matter.

if ($request_uri ~* "YOU CAN YOU REGEX like /cart(.*)$") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
    set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}

or 

f ($request_uri ~* "/cart(.*)$") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
    set $CACHE_BYPASS_FOR_STATIC 1; # Disables static file caching
}

**Comment by fevangelou** [comment]
@ChristianGabs disabling dynamic caching should be enough.

Keep in mind @RhuanGonzaga that dynamic caching is at 1 sec so it's rare than one client will see the cart of another. Additionally, you could provide me with a way to distinguish when OpenCart opens a session or adds a cookie so I can exclude it from dynamic caching as I've done with other CMSs too.

**Comment by ChristianGabs** [comment]
@fevangelou, thank you  👍

**Comment by ChristianGabs** [comment]
OCSESSID will be the session name

**Comment by dannyzee** [comment]
Hi,

We have the same problem as well but the problem is we are having multiple open cart websites on this server all having the same issue. How can we bypass those ?

**Comment by fevangelou** [comment]
> disabling dynamic caching should be enough.

**Comment by dannyzee** [comment]
Where can I turn that off completely?

**Comment by ChristianGabs** [comment]
if ($SITE_URI ~* "yourdomain.com") {
     set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
}
OR
if ($SITE_URI ~* "yourdomain.com|nextdomain.com|moredomain.com") {
     set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
}

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.
