### ISSUE TITLE
wiki page update for log real visitor IP

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#804]
@fevangelou Please can you add this [steps](https://www.damchey.com/2018/01/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel/) on your wiki page?

**Comment by fevangelou** [comment]
I need to test this first. If it works, I'll make it part of Engintron.

**Comment by Technopope** [comment]
@Nirjonadda @fevangelou 

I saw this on Wiki and tried to use, There is a slight mistake in the tutorial.
In the last part replace - **/scripts/rebuildhttpconfig** with **/scripts/rebuildhttpdconf**

/scripts/rebuildhttpconfig is **not** a valid cPanel script and will throw errors.
