### ISSUE TITLE
htaccess ip restrictions suddenly stop working

### ISSUE THREAD

**Issue by nash122** [engintron/engintron#805]
Up until yesterday, engintron/nginx was passing the remote browser's IP address along so that Apache could use normal IP address like this:

Order Deny,Allow
Deny from all
Allow from 130.191.26
Allow from 146.244.138.163

Today cPanel updated Apache and this no longer works.  It appears that Apache only see's the server's IP address, not the browsers for the reverse proxy in engintron.  What can I check/change to restore the previous behaviour?  I really don't want to edit the various .htaccess files to use SetEnvIf X-Forwarded if I can help it.

Thanks!

**Comment by fevangelou** [comment]
Check at the last option in the "Nginx" menu in Engintron's WHM app.

**Comment by nash122** [comment]
The problem is trivial to fix - re-installing is like using a sledge hammer to fix everything.  Yes it works, but, really?

cPanel did an RPM update of ea-apache24-mod_remoteip.x86_64.  This replaced the remoteip conf file in the /etc/apache2/conf.modules.d directory, breaking the passing of remote IPs.  The fix is to copy the xxx_mod_remoteip.conf.rpmsave contents into the new xxx_mod_remoteip.conf file, and restart Apache.

For the curious, the contents of the working configuration file on my server is (the second IP is your server's IP address):

# mod_remoteip (https://httpd.apache.org/docs/current/mod/mod_remoteip.html)
LoadModule remoteip_module modules/mod_remoteip.so
RemoteIPHeader        X-Forwarded-For
RemoteIPInternalProxy 127.0.0.1 130.191.17.30

**Comment by fevangelou** [comment]
I didn't mean re-installing. There is an option to patch visitor IP passing from Nginx to Apache.
