### ISSUE TITLE
Rate Limit With Engintron

### ISSUE THREAD

**Issue by rafaelmagic** [engintron/engintron#809]
Guys,
I am trying to Rate Limit Wordpress Login requests to help with Brute-Force attacks.

`#Rate Limit WordPress Login
#Wordpress Login zone. Limit login request to 1 request per second

limit_req_zone $limit zone=WPlogin:10m rate=1r/s;

location = /wp-login.php {
            limit_req  zone=WPlogin nodelay;
            include /etc/nginx/fastcgi_params;`

Is the code correct and do I place it in the Customs section or any advice??

Thanks
Rafael

**Comment by rafaelmagic** [comment]
Update:

Add the code below

In Nginx.conf below the line:
## Virtual Host Configs ##
include /etc/nginx/conf.d/*.conf;
    
#Rate Limit WordPress Login
#Wordpress Login zone. Limit login request to 1 request per second
limit_req_zone $binary_remote_addr zone=WPlogin:10m rate=1r/s;


In Custom_Rules:
#Rate Limit Wordoress Login
 location = /wp-login.php {
        limit_req  zone=WPlogin nodelay;
        include proxy_params_common;
        include proxy_params_static;
        }

It seems to be working but I am not sure if I have to include both proxy_params_common & proxy_params_static.

Anyone know??

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.
