### ISSUE TITLE
Hundreds of open connections with hostname ip

### ISSUE THREAD

**Issue by samapraku** [engintron/engintron#810]
I am experiencing an issue where the server IP has opened hundreds of connections to itself when i check the current connections on ports 80 and 443.

My server is completely unresponsive.

I would appreciate any assistance.

Thanks

**Comment by ChristianGabs** [comment]
This is not caused by nginx or apache, could be DDoS.

**Comment by fevangelou** [comment]
Hundreds of connections on your IP also means Nginx is passing traffic to Apache. It's normal to see a large number there. But if your server is unresponsive, consider optimizing it. Check the Wiki for more info or: https://www.fiverr.com/engintron/install-engintron-and-optimize-the-performance-of-your-cpanel-server
