### ISSUE TITLE
Engintron SSL Not Updating in cPanel

### ISSUE THREAD

**Issue by swartjie** [engintron/engintron#811]
Hey Guys,

Quick question. Since using enginetron, whenever someone installs an SSL certificate it does not pickup that the SSL certificate has been added. Sometimes I have to restart Enginetron, or I have to clear the cache, and sometimes neither works...

Any idea what would be causing this?

**Comment by laracroftonline** [comment]
Try adding this in custom_rules

`set $cp_proxy_autossl NO;

if ($host ~* "^(autoconfig|autodiscover|cpanel|cpcalendars|cpcontacts|webdisk|webmail|whm).") {
    set $cp_proxy_autossl CP;
}

# AUTOSSL CPANEL
if ($request_uri ~* "^/[0-9]+..+.cpaneldcv$|^/.well-known/pki-validation/[A-F0-9]{32}.txt(?: Comodo DCV)?$") {
    set $cp_proxy_autossl "${cp_proxy_autossl}AUTOSSL";
}

# AUTOSSL LETSENCRYPT
if ($request_uri ~* "^/.well-known/acme-challenge/(.*)$") {
    set $cp_proxy_autossl "${cp_proxy_autossl}AUTOSSL";
}

if ($cp_proxy_autossl = CPAUTOSSL) {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $CACHE_BYPASS_FOR_STATIC  1;
    set $PROXY_DOMAIN_OR_IP $host;
    set $PROXY_TO_PORT 8080;
}`

**Comment by ChristianGabs** [comment]
Just look on this https://github.com/engintron/engintron/issues/753

No need to open new issue

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.
