### ISSUE TITLE
Issues with RHEL 7 

### ISSUE THREAD

**Issue by flpbarreto75** [engintron/engintron#814]
The installation is giving issues on installing it on RedHat 7. It is looking for the repo : 

http://nginx.org/packages/mainline/rhel/7server/$basearch/

however it trows a 404 error since it does not exist, manually changed it to look for : 

http://nginx.org/packages/mainline/rhel/7/$basearch/
 and it fixed.

**Comment by ChristianGabs** [comment]
There're both in 404

**Comment by ChristianGabs** [comment]
1 ) rpm -q --provides $(rpm -q --whatprovides "system-release(releasever)") | grep "system-release(releasever)" | cut -d ' ' -f 3
2) rpm -q --provides $(rpm -q --whatprovides "system-release(basearch)") | grep "system-release(basearch)" | cut -d ' ' -f 3
OR 
1) rpm -q --qf "%{version}" -f /etc/$distro
2) rpm -q --qf "%{arch}" -f /etc/$distro

The repo is defined by releaserver and basearch 
: http://nginx.org/packages/centos/$releasever/$basearch/

On your output base by releaserver and basearch will define the package. If nginx don't have for the specific releaserver is not a big issue you can use other repo

But by default, the link will construct by the 2 of output 
http://nginx.org/packages/centos/$releasever/$basearch/

1) Output ( 7 )
2) Output (x86_64)

Example : http://nginx.org/packages/centos/7/x86_64/

**Comment by fevangelou** [comment]
Resolved I suppose...

@ChristianGabs Thanks for your help overall ;)
