### ISSUE TITLE
Need to manually restart php-fpm

### ISSUE THREAD

**Issue by robertmylne** [engintron/engintron#815]
## The issue
When I create a new website on a subdomain it works for a few minutes then shows the error:
```
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.
```

If I tail the `apache2/error_log` and refresh the web page I get this:
```
[Wed May 02 15:29:12.931381 2018] [proxy:error] [pid 23528:tid 140003464619776] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /opt/cpanel/ea-php70/root/usr/var/run/php-fpm/01ec0cf803682d3d54723265378c356d92c1d647.sock (*) failed
[Wed May 02 15:29:12.931430 2018] [proxy_fcgi:error] [pid 23528:tid 140003464619776] [client 120.29.52.39:54765] AH01079: failed to make connection to backend: httpd-UDS
```

Now sometime after around 5-10 minutes it will start working again on its own.

## The temporary solution
But if I go into the WHM `PHP-FPM service for Apache` and manually restart the php-fpm service, it will start working straight away. I wasn't having this issue before using Enginetron, but also didn't get the blazing speeds ;). Any help is appreciated.

**Comment by ChristianGabs** [comment]
/opt/cpanel/ea-php70/root/usr/var/run/php-fpm/ 

Missing path, check if this path is completed.

Can be a limited connection by PHP-FPM, try to increase.

Restart PHP-FPM from cpanel after you check or change.

**Comment by robertmylne** [comment]
I think this is a cPanel issue and not a Enginetron issue. Feel free to close. It has happened to all my servers since cPanel updated.

**Comment by saurabhlambe** [comment]
Hi @robertmylne , can you lead me to a URL where cPanel have updated you on this issue?
