### ISSUE TITLE
Mainline doesn't appear to install

### ISSUE THREAD

**Issue by nabeelio** [engintron/engintron#816]
I tried on the WHM panel to install mainline, and did the same on the commandline, it doesn't appear to be installing mainline. The current "stable" version is `1.14.0`, while "mainline" is `1.13.12`. While it's not a big deal, from my understanding, mainline is generally better.

Log is attached. I tried removing the yum package, and it still is only installing stable. Not sure what I'm missing. I haven't updated engintron in a very long time (it's been disabled).

I used:

```sh
[root@master /]# ./engintron.sh install --mainline
```

OS info:

```sh
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)
```

cpanel information:

```sh
[root@master /]# /usr/local/cpanel/cpanel -V
68.0 (build 38)
```

engintron info output

```sh
[root@master /]# ./engintron.sh info
==================
=== OS Version ===
==================

CentOS Linux release 7.4.1708 (Core)

cPanel version: 68.0 (build 38)
```

[log.txt](https://github.com/engintron/engintron/files/1973313/log.txt)

**Comment by ChristianGabs** [comment]
WRONG : ./engintron.sh install --mainline

CORRECT : ./engintron.sh install mainline

**Comment by nabeelio** [comment]
Thanks! That worked. Sorry, I should have checked the source. The instructions say "flag", so `--mainline` seemed correct. However, it was still installing stable instead of mainline when trying it from the WHM panel. That might be some kind of weirdness there.

As an aside, I'm looking at SSL certs, and WHMCS marketplace has an SSL provider ([link](https://marketplace.whmcs.com/help/connect/kb/symantec_ssl_certificates/getting_started/ssl_walkthrough_for_domains_with_hosting_account)), how does engintron handle SSL certs for all of the non-proxied assets?

**Comment by fevangelou** [comment]
@nabeelio It handles them just fine.

**Comment by nabeelio** [comment]
Thanks!
