### ISSUE TITLE
You do not have sufficient permissions to access this page...

### ISSUE THREAD

**Issue by zmenchhofer** [engintron/engintron#817]
I have updated engintron to latest version, whm version 68.0.38

now im not able to access engintron in WHM. 

I have uninstalled and reinstalled engintron and continue to get the same error.

**Comment by ChristianGabs** [comment]
Try 

`/usr/local/cpanel/bin/unregister_appconfig /usr/local/src/engintron/app/engintron.conf`

Then

`/usr/local/cpanel/bin/register_appconfig /usr/local/src/engintron/app/engintron.conf`

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.
