### ISSUE TITLE
APC(u) and php.ini

### ISSUE THREAD

**Issue by zstergios** [engintron/engintron#818]
A common PHP setup is
disable_functions = "show_source, system, shell_exec, passthru, exec, popen, proc_open"

But the installer uses the popen and throws error....
 so each time I have revert back my settings, run the installer and set again the prefered config.

I don't know if it's possible to make the installer script to ingore the current php settings.
Suggestions are to use cpanel's php to run the installer or use custom php.ini for installation only

**Comment by ChristianGabs** [comment]
https://github.com/engintron/engintron/issues/798

To install remove popen, exec

You cannot install without this extension.

`/opt/cpanel/ea-php55/root/usr/bin/pecl install -f channel://pecl.php.net/$APCU_FOR_PHP5`

This will be run for each version of PHP it's about 
```
APCU_FOR_PHP5="APCu-4.0.11"
APCU_FOR_PHP7="APCu-5.1.8"
```

The best way to handle remove them 2 and put back.

**Comment by zstergios** [comment]
This way I'm doing it.
php-cli I think ignores disable_functions.

I'am wondering how important is to include the popen on disable_functions.

**Comment by fevangelou** [comment]
@zstergios It's not the installer I built that uses the functions you block. It's the PECL installer which is called from my script to do the installations.

In WHM, under Software >> Multi PHP whatever, the PHP chosen as the default in the system is what appears to also be used by the APCu installer. So make sure that the required functions for PECL are open for the installation to proceed. After that, simply add the restrictions back in.
