### ISSUE TITLE
cPanel subdomains being cached after last update (session problems)

### ISSUE THREAD

**Issue by imorandinwnp** [engintron/engintron#819]
Changelog:

> Nginx proxy rules for cPanel-specific subdomains (e.g. cpanel., whm., webdisk.* etc.) have been commented out for both HTTP and HTTPS traffic. This allows cPanel or LetsEncrypt certificates to now be issued for these subdomains as well.

The problem is that now Webmail, cpanel and WHM mixes sessions due to micro-caching.

I re-added commented lines and started to work as expected.

**Comment by fevangelou** [comment]
I'll add an exception in the next few minutes. Thanks for reporting back.

**Comment by imorandinwnp** [comment]
Thanks!

**Comment by fevangelou** [comment]
You should be OK now!

**Comment by imorandinwnp** [comment]
Thanks, it works!
