### ISSUE TITLE
New version alert errror

### ISSUE THREAD

**Issue by asturmas** [engintron/engintron#82]
Hello,
Using new version 1.6.1 but received a alert to update to 1.6.0..

![screenshot_2](https://cloud.githubusercontent.com/assets/12483819/13163237/463bd02e-d6a3-11e5-9269-7bff9f9871b6.jpg)

**Comment by fevangelou** [comment]
Just reload Engintron via WHM and the message will disappear.

**Comment by asturmas** [comment]
Silves, thanks
