### ISSUE TITLE
How do I get the .json profile into cPanel?

### ISSUE THREAD

**Issue by GMTtx** [engintron/engintron#820]
When I get to the step in your instructions "Depending on your EasyApache version (EA3 or EA4), grab the latest profile here to install: https://github.com/engintron/engintron/tree/master/cpanel/EasyApache_Profiles" I was unable to find any way to get the file I found there to load into WHM. I tried using the link option and that didn't work, and I got a message that the file had to be a .json file. I tried saving the contents of the file to my pc and uploading it but the upload button never became active. What am I missing?

**Comment by laracroftonline** [comment]
login into your cpanel whm.
go to easyapache 4
when the page loads click on upload a profile
select browse find the json file and click then on upload
after uploading provision the package or add stuff you want and then provision.

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.
