### ISSUE TITLE
Suddenly cannot open Engintron WHM page - error 500

### ISSUE THREAD

**Issue by james-morton-45** [engintron/engintron#821]
System:
Engintron: Latest
WHM 56.0 (build 52)
CentOS 6.9 i686
Using PHP 5 FCGI

I've been using Engintron for almost two years on this particular machine and have had no issues - suddenly in the past 3 weeks, I cannot access the Engintron WHM app - clicking on the menu item causes the menu bar to go blank with an error 500. Opening the menu item into a new tab also brings an error 500. No issues with any other WHM component that I can see. I can perform commands fine via command line, but it's not ideal for me.

I've done the following to troubleshoot:
Uninstalled Engintron
Ran EA3 and did a full reinstall of modules
Reinstalled Engintron
Rebooted Server
Repeated the above steps at least a further 5 times!

Can you please advise which logs to check exactly - Neither Apache or Nginx are showing any errors for specific times when I see the HTTP error 500.

If there's any other info that may be required to aid troubleshooting, let me know. Thank you.

**Comment by laracroftonline** [comment]
It could be that your whm version has become to old to load engintron properly.

**Comment by fevangelou** [comment]
As @laracroftonline mentioned, changes in the WHM API require you to update cPanel to get the new version working. If you don't want to update cPanel, you can always hire me to build a legacy UI for Engintron on your server.
