### ISSUE TITLE
Root page not opening

### ISSUE THREAD

**Issue by mailparikshit** [engintron/engintron#822]
i have installed engintron on cpanel having apache 4,
when ever you try to open a page as https://www.somesite.com/  nginx index page opens up

please provide me solution what should i change so that request gets forwarded to apache to serve page

**Comment by ChristianGabs** [comment]
A solution, hmmm, first we need to understand your issue, do install engintron ? can you copy your status of your Nginx.

Thank you

**Comment by fevangelou** [comment]
Closed as no response was provided from the OP.

**Comment by mailparikshit** [comment]
status of nginx shows started, and other pages are opening fine, except index page as www.website.com/
instead it opens nginx index page

**Comment by fevangelou** [comment]
If you see an index page as you say, there is probably some .htaccess rule forcing that. Nginx will not attempt to serve anything else that Apache passes to it.

**Comment by mailparikshit** [comment]
well, nginx is not passing index page request to apache, it is replying itself,
request is not coming to apache for index page when browsed for website.com/

**Comment by fevangelou** [comment]
Nginx replies with whatever Apache sends back to it. Look at your .htaccess rules. And unless you send me the actual domain, I can't help you with fake domains.

**Comment by mailparikshit** [comment]
i currently disabled engintron as root page is not opening, 
if you can see it rightnow, i can enable engintron for you to see it live
