### ISSUE TITLE
Asking me to reboot my server on the Engintron page

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#823]
I am getting a "You must reboot the server to apply kernel updates and apply software updates" message on the Engintron page but nowhere else.

Rebooting the server does not cause the message to disappear.

<img width="1204" alt="screen shot 2018-05-13 at 9 36 30 am" src="https://user-images.githubusercontent.com/24284360/39967877-6ed4e9c4-5691-11e8-89fe-f65cc3b75351.png">

**Comment by fevangelou** [comment]
That's not Engintron for sure. Perhaps a bug related to the WHM PHP API
(like the sidebar which is always expanded).

**Comment by ChristianGabs** [comment]
You have caching header, this is the reason you should never use PHP API for loading header.

**Comment by WebSavvyGuy** [comment]
@ChristianGabs well thats something whm/cpanel uses.

Any harm to run your script?

**Comment by ChristianGabs** [comment]
You're not running my script, that one is whm, whm/cpanel will generate an HTML file for header footer and navigate. That script will regenerate those 3.

No worry's run that
