### ISSUE TITLE
Nginx not working!

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#825]
Restarting Nginx...
Redirecting to /bin/systemctl restart nginx.service
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

**Comment by ChristianGabs** [comment]
Login to ssh
use : journalctl -xe

Copy  last logs

**Comment by JorgeMarcelino-HS** [comment]
journalctl -xe
--
-- The result is failed.
May 16 11:41:43 server systemd[1]: Unit ea-php72-php-fpm.service entered failed
May 16 11:41:43 server systemd[1]: ea-php72-php-fpm.service failed.
May 16 11:41:43 server systemd[1]: Reloading.
May 16 11:41:43 server systemd[1]: [/usr/lib/systemd/system/vzfifo.service:19] S
May 16 11:41:43 server systemd[1]: Reloading.
May 16 11:41:43 server systemd[1]: [/usr/lib/systemd/system/vzfifo.service:19] S
May 16 11:42:01 server systemd[1]: Started Session 12208733 of user root.
-- Subject: Unit session-12208733.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-12208733.scope has finished starting up.
--
-- The start-up result is done.
May 16 11:42:01 server systemd[1]: Starting Session 12208733 of user root.
-- Subject: Unit session-12208733.scope has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-12208733.scope has begun starting up.
May 16 11:42:01 server CROND[12160]: (root) CMD (/etc/nginx/utilities/https_vhos
lines 2768-2790/2790 (END)

**Comment by ChristianGabs** [comment]
I don't think this is related to Engintron, you must use the command at the same time when you got this: Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

Thank you

**Comment by shahriar-shojib** [comment]
Try going to Tweak Settings and verify if apache http is running in port 8080 and apache https is running in port 8443. 
Then Try these commands:
`nginx -t`
`service nginx restart`

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.
