### ISSUE TITLE
whm mail clients 404 error

### ISSUE THREAD

**Issue by isarantis** [engintron/engintron#828]
Hallo, 

after the last update to 1.8.10 i am having problems with the webmail clients: squirelmail and horde with this error shown everytime i want to switch client:
404 not found : server.host.name:8080/cpsess6629508224/horde/login.php (port 8080)

Also i noticed something similar when trying to change cpanel accounts witch faulty redirects me to:
http://server.host.name:8080/cpsess3014411933/login/?session=aclientuser:aclienttoken
redirections starts here:
http://client.host.domain/cpsess3014411933/xfercpanel/aclientuser
Thanks in advance

**Comment by fevangelou** [comment]
Disable Engintron to verify. If you still get a 404 then they are probably
removed in cPanel.

**Comment by isarantis** [comment]
Disabling the engintron 
fixed the second problem with the account change. but the mail reponds with a difrend problem: 
The webmail.client.host host rejected the connection.

**Comment by isarantis** [comment]
If i access the webmail from server.host.name:2096 everything works as a charm but when someone logins thru webmail.domain and tries to change to somthing else other than roundcube he will get this error:
http://prntscr.com/jjxc04

also same thing when i go to cpanel as root or reseller and try to change from one user to another. 
from server.host.2096 no porblem but from cpanel.domain i get redirected to an address like:
http://cpanel.server.host.name:8080/cpsess3014411933/login/?session=aclientuser:aclienttoken

**Comment by fevangelou** [comment]
This is obviously a proxying issue but it could relate to many factors.

However, in my opinion, the errors you get are an edge-case. Be practical. Roundcube will soon be the only mail client in cPanel. Just disable the others.

As for issues with the mail client when you (the admin) is logged into cPanel accounts, you obviously have the option to access them when you're logged in from WHM's 2087 port.

**Comment by gmariani** [comment]
I get the same issue with Horde, which is NOT going away like Squirrel mail. Both give the same error. I too prefer roundcube, but our clients do use other webmail clients

**Comment by fevangelou** [comment]
This is most likely a configuration issue with how cPanel integrates Horde. The redirect does not work when you go through webmail.domain.tld but it works when you go through the cPanel port URL. Continue this here: https://github.com/engintron/engintron/issues/864

**Comment by cliquei** [comment]
What worked for me was to put the most stuff on default like exim tweak setting and make a full reboot. domain.com/webmail wont work anymore just webmail.domain.com... but it is good. I updated cpanel and so on  before it too.
