### ISSUE TITLE
Magento Cart Issue on Dynamic Caching

### ISSUE THREAD

**Issue by shahriar-shojib** [engintron/engintron#831]
Hello,
I enabled 2 minute caching on nginx dynamic params. 
On Magento site, removing items from cart still shows on cart.
Is there any way to exclude caching for cart and checkout? 
Shahriar

**Comment by ChristianGabs** [comment]
```
if ($request_uri ~* "YOU CAN ADD YOUR REGEX like /cart(.*)$") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
}
```

Result
```
if ($request_uri ~* "/cart(.*)$") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1; # Disables micro-caching
}
```

https://github.com/engintron/engintron/issues/803

Same explanation about how to handle caching base by link

**Comment by shahriar-shojib** [comment]
I understand now that excluding some elements won't be as easy as using an FPC module on magento.
And By design engintron is supposed to either cache a page or not cache a page the whole thing which isn't helpful in my case because, I have a sidebar on my site which acts as a minicart and products gets added to cart by ajax and it even shows number of items in my cart on a small icon on header.
To exclude this from cache, I'd have to exclude the whole page right?

**Comment by ChristianGabs** [comment]
Depends, in most of the case, yes, but it's about how you design to pull the date for the cart as well when you update that. 

In my view how I see is simple, when you add to cart you can refresh that (CART > div) with new stuff you get from a request or you can refresh entirely cart pulling back.

It's about how you will design and how you will refresh the Cart on each new/remove an item.

Caching will be affected but if the request is pulling every time and each Event trigger by javascript will update that Cart you will be fine. The issue anyway will be as well from IE < 10.

**Comment by shahriar-shojib** [comment]
So what you are saying is nginx dynamic cache will not cause any problems with cart if it is refreshed by javascript?
Have a look at the site I am working on, let's say i want to increase the nginx dynamic cache limit to 20 minutes, how should I configure engintron to exclude the cart area from all pages?

**Comment by fevangelou** [comment]
Magento has a tool that exports a Varnish configuration file. See here at the bottom of the document: https://www.fiverr.com/engintron/install-engintron-and-optimize-the-performance-of-your-cpanel-server

Do an export like that and send it over. It will include path and cookie exclusions which I can permenently add to Nginx's dynamic cache configuration. If it's similar to WordPress/WooCommerce, you will then be able to increase the dynamic cache to minutes.

You can send your varnish 4 export file via email to engintron [at] gmail [dot] com.

**Comment by fevangelou** [comment]
Link above updated.

**Comment by fevangelou** [comment]
Try and find exceptions for Varnish caching (they will be the same for Nginx when in proxy caching mode). Send them over so I can adapt them into Nginx.
