### ISSUE TITLE
nginx stopped working ssl engitron 1.8.7

### ISSUE THREAD

**Issue by zmkhan90** [engintron/engintron#832]
Hello,

My Nginx is showing stopped in Engitron 1.8.7 and when i try to restart from SSH or Engitron Backend i get below given error.

Restarting Nginx...
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/cpanel/ssl/installed/keys/ba2f8_57667_787cd88e69913c6ef6d9d8b669ddfadf.key") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cpanel/ssl/installed/keys/ba2f8_57667_787cd88e69913c6ef6d9d8b669ddfadf.key','r') error:20074002:BIO routines:FILE_CTRL:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)
nginx: configuration file /etc/nginx/nginx.conf test failed.

Please help me out on this.

**Comment by laracroftonline** [comment]
tried updating to 1.8.10 yet?

**Comment by zmkhan90** [comment]
Nops not yet. Planned it for tonight.

**Comment by laracroftonline** [comment]
try that first and then comeback here and report if it solved your issue.

**Comment by ChristianGabs** [comment]
I don't know if a new version will help you. 

First looking at your issues on Nginx or apache it's looking for SSL path (/var/cpanel/ssl/installed/keys/ba2f8_57667_787cd88e69913c6ef6d9d8b669ddfadf.key)

This path doesn't exist, so Nginx tries to load that path but will fail because you don't have that file.

The option they are like this :
```

    listen   443;
    server_name     my.domain.com;
    ssl on;
    ssl_certificate      conf.d/cert.pem;
    **ssl_certificate_key  conf.d/cert.key;**
```

But on Engintron you should not specify ssl_cerificate path.

**Comment by zmkhan90** [comment]
Hi Christian, 
I am looking into the directory right away. What if the file is not there?

**Comment by ChristianGabs** [comment]
Looking on close issues here will reproduce the issue

https://github.com/engintron/engintron/issues/561

**Comment by zmkhan90** [comment]
Hi Christian,

The file is not here on the directory.

**Comment by ChristianGabs** [comment]
Ok looking on how it's handle.

Few thinks must be check first

Make sure your cronjob from Engintron it's working, you must have this :

`* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1`

Try to run manualy 

`/etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1`

If this will restart your nginx without any issue then you must make sure the cron it's setup.

**Comment by zmkhan90** [comment]
Hello Christian,

I have updated the Engitron to the latest version and now its showing me HTTP Error 500 when trying to open Engitron Control Panel from my WHM

**Comment by zmkhan90** [comment]
I have WHM 64.X installed on my server.

**Comment by ChristianGabs** [comment]
Try to reinstall again from the command line.

**Comment by zmkhan90** [comment]
I have updated to WHM 68.X and its working fine.
Thankyou both Christian and Laracroft for the help.

Appreciated.

**Comment by ChristianGabs** [comment]
So the cron job was not doing the job. Welcome.

**Comment by zmkhan90** [comment]
Thanks :)
