### ISSUE TITLE
Problem getting Engintron working with Cloudflare

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#833]
I have Engintron installed on a couple other servers so I am not new to this.

But, this one particular server I tried to install it on.    I had previously used Engintron long time ago but uninstalled it.  Now, i want to go back to it.

Everything seemed ok with install, then configured the NGINX Custom Rules.    Because I use cloudflare, as per the instructions, I specified the main shared IP and then the IP's dedicated to a particular domain.   Saved.  Restarted all services.

However, my website would get the "Site is offline Cloudflare message"

I checked the status of Nginx and i get this:

Nginx Status:

Redirecting to /bin/systemctl status nginx.service
● nginx.service - nginx - high performance web server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-05-21 23:58:05 CDT; 2min 18s ago
     Docs: http://nginx.org/en/docs/
 Main PID: 2883 (code=exited, status=0/SUCCESS)

May 21 23:58:05 my.server.hostname systemd[1]: Starting nginx - high performance web server...
May 21 23:58:05 my.server.hostname nginx[7650]: nginx: [emerg] unexpected end of file, expecting "}" in /etc/nginx/custom_rules:94
May 21 23:58:05 my.server.hostname systemd[1]: nginx.service: control process exited, code=exited status=1
May 21 23:58:05 my.server.hostname systemd[1]: Failed to start nginx - high performance web server.
May 21 23:58:05 my.server.hostname systemd[1]: Unit nginx.service entered failed state.
May 21 23:58:05 my.server.hostname systemd[1]: nginx.service failed.

I guess with Nginx failing my server website wouldn't load.    Disabling Engintron returned the website back to normal state.

So, can anybody tell me what has happened?   Again, i did have Engintron installed on this server a  year ago and uninstalled it as per instructions.  Now i was trying to reinstall it and followed everything according to the installation instructions.

I guess perhaps the line here:

**May 21 23:58:05 my.server.hostname nginx[7650]: nginx: [emerg] unexpected end of file, expecting "}" in /etc/nginx/custom_rules:94**

may be the reason but where and how would i fix that?

Please help.

Thanks

**Comment by WebSavvyGuy** [comment]
I went into the /etc/nginx/custom_rules file and copied the "}" again and then started Engintron again.

Now it seems to be working.

Not sure what the issue was as the "}" i used previously was proper.

**Comment by fevangelou** [comment]
Obviously a syntax error when applying the rules. That's why I provide the stock "custom rules" file (which is always updated) for you to copy/paste into your active "custom rules" in order to modify fresh.

As a general rule, always test Nginx's configuration from the Engintron WHM app after you apply changes into custom rules or one of the other Nginx config files.
