### ISSUE TITLE
How to configure ngx_http_memcached_module with nginx?

### ISSUE THREAD

**Issue by shahriar-shojib** [engintron/engintron#835]
Hello,
I am looking into options for utilizing my ram with nginx for better performance.
I am stuck between creating ramdisk and placing nginx cache directory or using the ngx_http_memcached_module.
Which one do you suggest? and I want to know if it helps reducing response time for static as well as dynamic content served by nginx.
And if I want to use ngx_http_memcached_module, is it bundled with nginx by default or i will need to manually install it? and how do i go about configuring it within engintron?
Let me know.
Shahriar

**Comment by fevangelou** [comment]
Ramdisk is fine. Install Memcached that comes with v1.8.11 to lighten up MySQL & PHP load wherever possible. Using ngx_http_memcached_module won't work in a proxy scenario. If you require professional optimization (as a service) you can always hire me through: https://www.fiverr.com/engintron/install-engintron-and-optimize-the-performance-of-your-cpanel-server

**Comment by shahriar-shojib** [comment]
Sure, I will keep you in mind.
