### ISSUE TITLE
How to specify certain pages to be cached only

### ISSUE THREAD

**Issue by rotate4all** [engintron/engintron#836]
The current config seems to be in the direction of 'blacklisting' pages/urls/cookies which contain specific strings. Having lots of pages, and requiring the cache only on a few specific ones, I'd rather use the opposite of:

```
# Disable caching when the "Cache-Control" header is set to "private"
if ($http_cache_control ~* "private") {
    set $CACHE_BYPASS_FOR_DYNAMIC 1;
    set $EXPIRES_FOR_DYNAMIC 0;
}
```

Any way to setup a Cache-Control header which would mark the page to be cached instead?
Was thinking of something along the lines of:
```
if ($http_cache_control ~* "cached") {
    set $CACHE_BYPASS_FOR_DYNAMIC 0;
    set $EXPIRES_FOR_DYNAMIC 5s;
}
```
Then set "cached" as header ONLY for the files I'd like to be cached.
Is something like that possible?

Thanks.

**Comment by fevangelou** [comment]
You can do that in your "custom rules" files. See the notes/comments in that file.

**Comment by rotate4all** [comment]
OK, I've added the following in the custom rules section:
```
 if ($http_cache_control ~* "cached") {
     set $CACHE_BYPASS_FOR_DYNAMIC 0;
     set $EXPIRES_FOR_DYNAMIC 5s;
 }
```
Then purged cache & temp files.
Have setup a php file with the "cached" header as Cache-control directive and accessed it through a Firefox Private Window.
At first access, I get a "X-Nginx-Cache-Status | MISS" in the response header and after each subsequent refreshm, regardless if it's 5s or 50s later, I get a "X-Nginx-Cache-Status | STALE", but never a HIT.
Is this normal? Or am I missing something here?

**Comment by fevangelou** [comment]
Doesn't work this way. You can only set one value in proxy_params_dynamic (proxy_cache_valid 200 1s;). You cannot override that in custom rules. If you could override that, I'd offer a different set of rules e.g. for WordPress sites, Joomla sites etc.

This is an Nginx limitation I'm afraid.

In your case, set the expiration to 5s in proxy_cache_valid and then add your exclusion/inclusions in your custom rules file. I assume you're hosting a single site...
