### ISSUE TITLE
Reseller Dedicated ip

### ISSUE THREAD

**Issue by wh4u** [engintron/engintron#838]
Hello there,
One of my reseller configured with a dedicated ip on whm.
Nginx reports 502 Bad Gateway

i suppose i have to include somehow this ip address in nginx.conf?

**Comment by wh4u** [comment]
Websites using the standard shared ip working perfectly.
Reseller with dedicated ip for sharing his own websites reports a nginx 502 bad gateway.

Where do you suggest to investigate?

**Comment by fevangelou** [comment]
502 means the proxying failed. They should make sure domains actually resolve to your server.
