### ISSUE TITLE
Lots and lots of time_wait connections

### ISSUE THREAD

**Issue by rotate4all** [engintron/engintron#840]
I'm currently experiencing a huge amount of traffic to the server, which happens from time to time.
Previously it was handled directly with Apache with no errors.
Thought Nginx as reverse-proxy would take the load off of Apache but seems it doesn't as there are some side-effects mainly in a HUGE amount of time_wait connections:
```
root@server [~]# netstat -natp | awk '{print $6}' | sort | uniq -c
     10 CLOSING
      1 established)
   1036 ESTABLISHED
     85 FIN_WAIT1
   2766 FIN_WAIT2
      1 Foreign
     50 LAST_ACK
     46 LISTEN
     20 SYN_RECV
  12248 TIME_WAIT
```
These also causes some server errors such as:
`TCP: time wait bucket table overflow (CT0)`
Whereas with Apache, I had none of those ever, no matter how much traffic I thrown against it.
Also, when checking the "Current connections on port 80 (per IP & total)" I can see the bulk of it on the server's IP address:
`8407 xxx.xxx.xxx.xxx (server's main IP)`
But what are they "waiting" for? Apache isn't busy at all, with barely a few busy threads. PHP-FPM is doing great along with Mysql as well.
So what's with the TIME_WAIT? Note that even under normal/light load, the time_waits were around 4-5k whereas under the same scenario with Apache at the front, time_waits were around 1-2k at the most.

**Comment by ChristianGabs** [comment]
Having some connections in TIME_WAIT is a normal part of the TCP connection.

[root@host ~]# cat /proc/sys/net/ipv4/tcp_fin_timeout
60
And change it by modifying that value:

[root@dev admin]# echo 30 > /proc/sys/net/ipv4/tcp_fin_timeout
Or permanently by adding it to /etc/sysctl.conf

net.ipv4.tcp_fin_timeout=30
Also, if you don't use the RPC service or NFS, you can just turn it off:

/etc/init.d/nfsd stop
And turn it off completely
chkconfig nfsd off

**Comment by rotate4all** [comment]
That doesn't explain the issue at hand: why are there so many connections in TIME_WAIT compared to Apache, up to the point that it piles up generating errors?
For example, here's the current status with Apache:
```
root@server [~]# netstat -natp | awk '{print $6}' | sort | uniq -c
      1 CLOSING
      1 established)
    192 ESTABLISHED
      2 FIN_WAIT1
     37 FIN_WAIT2
      1 Foreign
     96 LAST_ACK
     44 LISTEN
    173 SYN_RECV
    228 TIME_WAIT
```
Same timeout values as used in nginx, including keep-alive, as well as TCP values the same in both cases, while under the same circumstances I would have 4-5k TIME_WAIT instances!

**Comment by ChristianGabs** [comment]
Time wait could be only robots, scanners etc. This is not Apache or Nginx and has no relation with this 2.

The connection can be TCP, UDP you must stop blaming apache, nginx because that connection could be UDP or could be on other port which has no relation with nginx.

**Comment by rotate4all** [comment]
No, it wasn't UDP, because the only ports allowed for UDP connections on my server is 20,21,53 while the rest are being actively as per CSF rules.
You can see the count of connections on port 80 reported by Nginx in the main post:
`Current connections on port 80 (per IP & total): 8407 xxx.xxx.xxx.xxx (server's main IP)`

Point is, for some reason the TIME_WAITS were piling up during peak traffic periods leading up to errors being reported (note the "TCP" part, not UDP):
`TCP: time wait bucket table overflow (CT0)`

**Comment by fevangelou** [comment]
Don't forget that when Nginx proxies traffic to Apache, you get additional TCP connections. So when you enable Nginx, it's normal to have more TCP connections opened.

Also add:
```
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1
```
...in your /etc/sysctl.conf file and then merge the changes with `$ sysctl -p`.
