### ISSUE TITLE
Issues with forms

### ISSUE THREAD

**Issue by ajfernandez85** [engintron/engintron#841]
I updated engintron to version 1.8.11. After this, I noticed that I have issues with forms on all my websites. After save the form and page reload, it shows the old values of the form (the values of the form before save it). If I refresh the page, it shows the right values. Yesterday I didn't have these issues.

**Comment by hamersky** [comment]
I have the same problem ??

**Comment by ChristianGabs** [comment]
@hamersky you asking if you have the same problem or you have the same issue?

**Comment by hamersky** [comment]
Sorry,
I have the same problem !
On apache port all working good.
I cleared the cache.
If remove request uri from dynamic cache all working good.

**Comment by ajfernandez85** [comment]
I have cPanel v70.0.43 and the latest update doesn't seem to have any fix related with this issue (https://documentation.cpanel.net/display/CL/70+Change+Log).
I am having this issue on all my Drupal sites. Before I updated engintron I didn't have these problems with forms. If I disable engintron all my sites works well.

Any ideas about this?? I am using PHP 7.1.17 on these sites.

**Comment by fevangelou** [comment]
@hamersky if you remove "$request_uri" from the value of "proxy_cache_key", caching will behave very weirdly for you. If you mean the entire "if" block, then exceptions will be removed so more will be cached.

@all Provide a few URLs so I can check them out remotely with cURL.

**Comment by ajfernandez85** [comment]
Yes, I commented out this line and all is working fine again!
Thanks @fevangelou !!

**Comment by hamersky** [comment]
Ok, working :)
Thanks
