### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Friends4U** [engintron/engintron#842]
"Updated WooCommerce exclusions (cookies and paths) so expect even better performance & behaviour with WordPress/WooCommerce sites. If you host exclusively WordPress sites, you can now safely increase "proxy_cache_valid" in /etc/nginx/proxy_params_dynamic from "1s" (1 second - aka micro-caching) to minutes (e.g. "3m"). If you do this, Nginx can serve dynamic content entirely from its cache for content that CAN be cached, so expect a MAJOR boost in performance. You're welcome :)"

What if you don't host only (but many (mostly)) WP sites, would I leave it on 1s or?

**Comment by fevangelou** [comment]
Can't get any more specific than "If you host exclusively WordPress sites". ;)
