### ISSUE TITLE
Crontab file issue EOF

### ISSUE THREAD

**Issue by imagina** [engintron/engintron#844]
Some of our servers were failing the cron and after a lot of testing we found the problem:

man page says:

`cron requires that each entry in a crontab end in a newline character. If the last entry in a crontab is missing the newline, cron will consider the crontab (at least partially) broken and refuse to install it.`

Adding a simple comment at the end of the file /etc/crontab after the last cron job did the trick

```
* * * * * root /etc/nginx/utilities/https_vhosts.sh >> /dev/null 2>&1
# end of cronfile
```

**Comment by fevangelou** [comment]
This was already in the wiki :)
