### ISSUE TITLE
Cloudflare Error 1000 with SSL

### ISSUE THREAD

**Issue by eran101** [engintron/engintron#845]
Getting error 1000 when using Cloudflare with SSL mode set to Full.
After disabling engintron it works again.
Link for information about the error.
https://support.cloudflare.com/hc/en-us/articles/200171976-Error-1000-DNS-points-to-prohibited-IP
*wasn't tested without SSL

**Comment by laracroftonline** [comment]
for this you need to fill in your users ip into the custom rules like this

set $PROXY_DOMAIN_OR_IP "your server ip";

**Comment by laracroftonline** [comment]
https://github.com/engintron/engintron/wiki/Engintron-&-CloudFlare
