### ISSUE TITLE
Version update checker error

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#85]
I am using v1.6.1 but WHM are still show me A newer version of Engintron (v1.6.0) is now available. Also please can you make a option this Version update checker message can be close? I would like to have a option new version update automatically.

**Comment by fevangelou** [comment]
I'm sorry but I can't confirm this bug. You'll have to provide more info. Auto-updating is not a good idea for such critical components like your webserver. It's the same reason why you need to use EasyApache to get a newer version of PHP on your system.
