### ISSUE TITLE
Fiverr Performance Pack information

### ISSUE THREAD

**Issue by italloduarte** [engintron/engintron#850]
Hello, I would like information on how the STANDARD package that you provide for server optimization works.

I am overloaded on my server in part of Mysql due there are 4 wordpress sites. So I would like to know more details on how this package works.

- Do you do the whole server analysis and then do the optimization?
- Will you change the entire configuration (mysql, apache, WHM) to improve this overhead?
- If your configuration does not work, or it gets worse, do you give support until we get the server running clean?

These are some doubts I have, if possible I await a retreat from you.

Thank you very much in advance.

**Comment by italloduarte** [comment]
?

**Comment by Friends4U** [comment]
For commercial you can mail engintron@gmail.com

It's a proxy, read about it here: https://github.com/engintron/engintron/wiki

**Comment by fevangelou** [comment]
@italloduarte You can use Fiverr to message me directly if you want.
