### ISSUE TITLE
memcached installed but not working

### ISSUE THREAD

**Issue by GMTtx** [engintron/engintron#851]
I installed Memcached per the instructions found in the Engintron Wiki but it did not appear to be working. My application is vBulletin and I was unable to load the vB_Datastore into Memcached. Memcached does appear in the phpinfo page.  I found a couple of test scripts and they both deliver the same error:

`[28-May-2018 17:24:24 UTC] PHP Fatal error:  Uncaught Error: Class 'Memcache' not found in /home/xyz/public_html/home_public_html/vb/memcached-test.php:2
Stack trace:
#0 {main}
  thrown in /home/xyz/public_html/home_public_html/vb/memcached-test.php on line 2`

The test scripts I tried are:

<?php
$memcache = new Memcache;
$memcache->connect("localhost",11211); # You might need to set "localhost" to "127.0.0.1"

echo "Server's version: " . $memcache->getVersion() . "<br />\n";

$tmp_object = new stdClass;
$tmp_object->str_attr = "test";
$tmp_object->int_attr = 123;

$memcache->set("key",$tmp_object,false,10);
echo "Store data in the cache (data will expire in 10 seconds)<br />\n";

echo "Data from the cache:<br />\n";
var_dump($memcache->get("key"));
?>

and...
`<?
$memcache = new Memcache;
$memcache->connect('localhost', 11211) or die ("Could not connect");
echo "Server's version: {$memcache->getVersion()}
";
$tmp = new stdClass;
$tmp->string_attribute = 'testing';
$tmp->string_attribute = 123;
$memcache->set('key', $tmp, false, 10) or die ("Failed to save temporary object at memcache server");
echo "Data from the cache:
\n";
print_r($memcache->get('key'));
?>`

Any suggestions on what I might be doing wrong? What diagnostic methods should I employ?

**Comment by fevangelou** [comment]
The script installed Memcached (the service) and the PHP Memcached modules (not the trailing "d" in both). Memcache (not d at the end) are the old PHP modules which are not supported anymore.
