### ISSUE TITLE
How do I upgrade APCu to current version?

### ISSUE THREAD

**Issue by GMTtx** [engintron/engintron#852]
I installed APCu per the instructions in your wiki and was able to get it working with my application, but when I started monitoring the cache using the apc.php tool found at the [APCu repository](https://github.com/krakjoe/apcu/) it indicates I have an older version installed. How do I move up to the current version? You indicate in your wiki the PECL installer is broken, but it appears in the apc.php tool that it is linking to PECL modules to upgrade.

Also, when I am running APCu it is only caching the specific items my application is putting into it. I find no evidence it is doing any opcode caching at all, which is consistent with the description of APCu in the read.me file at the repository. While I appreciate the caching of specific items loaded by my application, how do we add opcode caching as discussed in your wiki?

Lastly, how do I uninstall APCu if I need to?

**Comment by dnoizeshakerz** [comment]
I have the same question.

**Comment by fevangelou** [comment]
Updated the script to include the latest APCu release at the time of writing. Simply update/re-install Engintron to get the modified script and then re-run it.
