### ISSUE TITLE
Problems issuing Auto-SSL certificates in Cpanel

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#855]
Every new account created is having difficulties issuing an Auto-SSL certificate.

This only started recently and not sure if its because of an Engintron update or Cpanel update.

When i run auto-ssl, it will place the domain in the "Pending queue" but it will remain there forever.

The logs within Auto-SSL show this error:

 Checking websites for “myusername” …
 1:54:02 PM Checking “mywebsite.com” …
 1:54:02 PM ERROR TLS Status: Defective
 Certificate expiry: 5/31/19, 5:52 PM UTC (365 days from now)
 ERROR Defect: OPENSSL_VERIFY: The certificate chain failed OpenSSL’s verification (0:18:DEPTH_ZERO_SELF_SIGNED_CERT).

I tried adding other domains and they all give this same error so its not domain specific  Even just last week I added a domain the exact same way and it was fine to issue an Auto-SSL from Comodo within Cpanel.   This just started happening very recently.

**Update**:  I have found this  1:54:02 PM ERROR TLS Status: Defective error to be normal as its just saying that the domain is using a self-signed certificate.

So ignore the error message but the problem of issuing Auto-SSL certificates still exists since the last update.

I have Cpanel Support looking at the issue now but they cannot find anything as of yet.  The only other scenario is if there is an issue on Comodo's end but I don't see many tickets being opened about issues with them.

**Update2**:  I have disabled Engintron but now none of my SSL enabled domains are working at all.   

It really seems that this application has some serious conflicts with this whole SSL system.     The only way to get the domains working again is turning Engintron back on.   I imagine completely uninstalling Engintron would also bring those SSL enabled https domains up too.

**Comment by WebSavvyGuy** [comment]
Update:  Turns out there was some issue with Comodo issuing certificates.

I will open another ticket for the other issue.

**Comment by fevangelou** [comment]
Prefer LetsEncrypt where possible. ;)

**Comment by faheemsdq** [comment]
If you are administrator for WHM, then please make sure that the cPanel account related to the domain is within Jailed Shell in Manage Shell Access.

**Comment by ryanfc** [comment]
I am having the same issue and it has taken down about 25 of my sites.  Have you found a good solution yet?  What version of WHM are you using?  Trying to find a solution myself.

**Comment by WebSavvyGuy** [comment]
I am using WHM 78 i believe (whatever the most up to date one is)

I cant recall the details of this issue now since it was a while ago but if you have WHM you have cpanel support to help you.   Just open a ticket.

Suggest you update to latest version of everything including Engintron

**Comment by ryanfc** [comment]
Just updated to the latest version and that does seem to have fixed the issue.  Thanks.

**Comment by mdrideout** [comment]
Just reporting that I was having this issue as well, changing to Let's Encrypt solved my problem. (The WHM I am new to managing cannot be upgraded past 72 for yet unknown reasons)

The CPANEL support people kept claiming it was my issue (network settings?) despite that other SSL's were renewing before, during, and after we encountered this ssl renewal issue with 1 of our domains. 

Changing to Let's Encrypt was painless and quick.

**Comment by fevangelou** [comment]
Go L/E! :)
