### ISSUE TITLE
OAM file type BAD GATEWAY

### ISSUE THREAD

**Issue by spopadiin** [engintron/engintron#858]
Hello,
Good work for Engintron team fixing late bugs. However, we face another one with config out of the box.
We use WordPress in this case to render .OAM file type. With Engintron switched on, the render frame returns BAD GATEWAY error.
We tried editing configs, but no success so far.
What would you advise as a fix?
Regards,

**Comment by fevangelou** [comment]
What are .OAM files? It's probably not in Nginx's mime types list, that's why it fails to proxy the request. Should be as simple as adding the file type in /etc/nginx/mime.types.

Send it over as well so it's merged in future updates of Engintron.
