### ISSUE TITLE
run a nodeJs app and on a specific path redirect to other port (of node server app running)

### ISSUE THREAD

**Issue by obxion** [engintron/engintron#861]
i have a vps with cpanel installed, but want run any nodejs app on specific path. i tried do it from diferent ways, but nothing work.. some one can say me how run a different port on an specific path of a domain? nodejs run a server on midomain.com/nodeapp  and i specific the port of the nodejs server. If i have 2 app, i need redirect to both ports, and for each app is the same thing. Help pls

**Comment by fevangelou** [comment]
Read the changelog for "July 24th, 2018 - v1.9.0" here: https://engintron.com/docs/#/pages/Changelog
