### ISSUE TITLE
502 Bad Gateway with Host not found

### ISSUE THREAD

**Issue by CarlosLopezES** [engintron/engintron#862]
Hi,

Since this morning, i have this error:

2018/06/08 12:51:17 [error] *426 www.XXX.es could not be resolved (3: Host not found), client: 85.25.210.41, server: localhost, request: "GET /robots.txt HTTP/1.1", host: "www.XXX.es"

Only ocurrs on some domanins and not every time, but maybe the 80% of the tries.

No software change, until today all was working fine. I'm not using cloudlfare or anything like that.

Thank you!

**Comment by abhishek6262** [comment]
It's happening from the morning itself on our side as well... We're having to restart the NGINX server again and again to fix it.

**Comment by CarlosLopezES** [comment]
On our side, the error was caused by a .ES domains DNS global failure, and now the issue it's gone.

Thank you!
