### ISSUE TITLE
502 bad gateway ngnix error everytime

### ISSUE THREAD

**Issue by damanager** [engintron/engintron#863]
My server is running a combination of Engintron and PHP-FPM, We keep getting intimate issues with it  where NGINX will return a 502 Bad Gateway error, We have install Engintron on our server, cpanel CENTOS 7.5 standard [server] v70.0.48 but we keep getting 502 bad gateway ngnix error every time

Please help

**Comment by Linith** [comment]
Same here, I had to disable it.

**Comment by fevangelou** [comment]
Da Manager's issue was different and it was resolved by optimizing his
server beyond Nginx.
