### ISSUE TITLE
Check configuration for errors

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#865]
Check configuration for errors option not working. Also still are not working Show compiled modules, Show loaded modules and Show parsed settings. Any fix update for both option?

![screenshot00028](https://user-images.githubusercontent.com/6899856/41512203-658527fc-7285-11e8-8bdd-26bbd3e4a7d2.png)

**Comment by fevangelou** [comment]
What CentOS version are you using?

**Comment by Nirjonadda** [comment]
CentOS version 7

**Comment by fevangelou** [comment]
Update Engintron now and let me know if you're good.

**Comment by Nirjonadda** [comment]
How to update because I am already using v1.8.13

**Comment by fevangelou** [comment]
Simply hit the "Update (or re-install) Engintron [Nginx stable]" option.

**Comment by Nirjonadda** [comment]
No, Still are not fixed. Only working Show compiled modules.

Check configuration for errors...

![screenshot00065](https://user-images.githubusercontent.com/6899856/42401353-8f766306-8175-11e8-8978-432303f5d7ff.png)

Show loaded modules...

![screenshot00066](https://user-images.githubusercontent.com/6899856/42401376-aa972076-8175-11e8-9a9b-f0b38bea6236.png)

Show parsed settings...

![screenshot00067](https://user-images.githubusercontent.com/6899856/42401396-bc59b238-8175-11e8-8658-d5a791ec4dec.png)

**Comment by fevangelou** [comment]
Issues fixed. It's now working but you'll have to update again.

**Comment by Nirjonadda** [comment]
Yes, Fixed.
