### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by charliedamon** [engintron/engintron#867]
I install engintron and already set shared and dedicated IP for cloudflare.

All sites works fine, but i have one with error:

1 domain have dedicated IP, use cloudflare and show 404 error

I already set this:

if ($host ~ "domain.com") {
     set $PROXY_DOMAIN_OR_IP "x.x.x.x";
}

and try every ssl option in cloudflare.

noting works

Any idea?

**Comment by fevangelou** [comment]
Does the site actually point to your server's IP address?
