### ISSUE TITLE
Support for Drupal

### ISSUE THREAD

**Issue by kotakomputer** [engintron/engintron#869]
I set micro-caching to 180s, but when logged to Drupal every page was come from cached.
Please support like WP did.

**Comment by fevangelou** [comment]
From what I've seen, these 2 paths should be excluded for logins:
`/admin & /user`

and these 2 cookies which are present when someone is logged in (in regex format):
`SESS[a-zA-Z0-9]+ & SSESS[a-zA-Z0-9]+`

Can you confirm?

**Comment by jollysolutions** [comment]
That looks correct

**Comment by nvlonline** [comment]
Hi,
Just curious if this has been committed. I do not see the changes in the latest code. If it will not be committed, is there a way for me to update the paths without having to hack the proxy_params_dynamic configuration file?
Thanks a lot for your time!

**Comment by fevangelou** [comment]
@nvlonline Can you also confirm the paths and cookie exclusions? I'm not following Drupal development so I don't know if there are changes since then...

**Comment by fevangelou** [comment]
Just to update this thread, Drupal support will be added in v1.11.0.

**Comment by nvlonline** [comment]
Hi, 

Thanks for the update.

I am not an expert but based on my usage:

    Example Session cookie upon login:

    SSESSa3hx1wmnx7kpr3k50p9x8bqwpruyvvy3    

    Maybe: SSESS[a-z0-9]{32}

Common paths for posting content:

    admin
    user
    node/*/add
    node/*/edit
    node/*/delete

**Comment by fevangelou** [comment]
Thank you. Noted.
