### ISSUE TITLE
Getting 502 error after latest update.

### ISSUE THREAD

**Issue by WebSavvyGuy** [engintron/engintron#871]
Website is getting this error all the time now.

Everytime there seems to have something happen when there is an update.  There was both a CPanel and Engintron update.   How can i check what is the culprit this time?

UPDATE:  Got the webserver back up by restarting everything including the entire server.  But scared this might happen again (whatever did happen).   Is there any good way to check for what would cause issues like this in the future? (like a certain log file or test to run)

**Comment by fevangelou** [comment]
Look at the Nginx logs of course.
