### ISSUE TITLE
I've done everything but work? I am not sure

### ISSUE THREAD

**Issue by gkhnpkr** [engintron/engintron#873]
Hello there
First of all, I would like to thank everyone who provided this service.
I did everything necessary for the installation. I did everything carefully during the installation, but I'm not sure if it works.
When I look at the system status, I see that you are not working. When I look at the nginx status, I see that it works, please help.
![screenshot_1](https://user-images.githubusercontent.com/40920636/42413095-f545a10e-8221-11e8-9438-5fa534272578.jpg)
![screenshot_2](https://user-images.githubusercontent.com/40920636/42413096-f56cae48-8221-11e8-8bc1-864ee9c8c527.jpg)

**Comment by gkhnpkr** [comment]
open_basedir is closed.
ConfigServer Security & Firewall settings ;
**csf.allow**
![screenshot_1](https://user-images.githubusercontent.com/40920636/42413132-b100ce64-8222-11e8-9b97-98ec7f0c8637.jpg)
**csf.deny**
![screenshot_2](https://user-images.githubusercontent.com/40920636/42413134-b540a68e-8222-11e8-8f8f-936d7eb74502.jpg)

**Comment by fevangelou** [comment]
Try re-installing just in case in case the "state" file is properly written in /usr/local/src/engintron/.

To check if Nginx is running, simply pass any domain on your server from https://onlinecurl.com/ and inspect the HTTP headers. If you see Nginx referenced, it's running just fine.

**Comment by gkhnpkr** [comment]
Thank u for comment.
I have ssl. It works in http protocol. but it does not work on https
![screenshot_1](https://user-images.githubusercontent.com/40920636/42419019-47ff33b8-82b5-11e8-9c37-462706fcc27b.jpg)
![screenshot_2](https://user-images.githubusercontent.com/40920636/42419020-48250c00-82b5-11e8-8578-3437abc5721e.jpg)

**Comment by gkhnpkr** [comment]
ConfigServer Security & Firewall settings I made the after installing Engintron..
It started to work when I rebuilt Engintron!
![screenshot_3](https://user-images.githubusercontent.com/40920636/42419097-e919a796-82b6-11e8-9ef3-a1a3afe2c0d2.jpg)
![screenshot_4](https://user-images.githubusercontent.com/40920636/42419098-e944e384-82b6-11e8-9bff-9c4902e9b3bb.jpg)
Thank u!
