### ISSUE TITLE
Static cache don't work (images)

### ISSUE THREAD

**Issue by gkhnpkr** [engintron/engintron#889]
I can not see my image files (jpg and png)

no problem with google chrome. but I'm having serious problems with mozilla, safari, mobile site (chrome, mozilla and safari) and mobile apps

I use WordPress infrastructure. PHP version 5.6.x

Any ideas?

Example mozilla firefox pc 
![masaustu](https://user-images.githubusercontent.com/40920636/43355786-5bce5c00-926b-11e8-8b32-ed77d1da9dbc.jpg)

**Comment by fevangelou** [comment]
Paste back the source/URL of one such broken image.

**Comment by gkhnpkr** [comment]
the images are not broken.
images eg nice work on google chrome. but it does not work in mozilla firefox. 

I do not see the images when I download the pictures from the source in mozilla firefox. but i see the images when i download the picturec from the source in google chrome :-1: 

@fevangelou

**Comment by fevangelou** [comment]
If the images are not a national/state secret, do you mind if I take a look at one of the URLs so I can test the HTTP headers? Anything else is pure speculation...

**Comment by gkhnpkr** [comment]
Okay i am sorry.

site url : https://goo.gl/WgEfFd

example post url : https://goo.gl/bcj2rr

**Comment by gkhnpkr** [comment]
but it works when the engintron is disabled or the static cache is cleared. reading firefox jpeg pictures...
@odysseas12

**Comment by odysseas12** [comment]
Windows image viewer does not open them, Photoshop gives error they are not jpeg.
According to 
https://www.get-metadata.com/result/d1bdce84-3439-407a-8e19-d7fbf50e851e
its a webp image which explains why it works in chrome but not firefox.
https://en.wikipedia.org/wiki/WebP

**Comment by gkhnpkr** [comment]
Okay, you're right, I know that.
But when I disabled the engintron or clean the engintron cache, these images are working.

It just does not work in this way? Why? I can not make sense. I have no idea how to solve this problem and it is very annoying.
I have to use Nginx. Please help me.

@odysseas12 @fevangelou

**Comment by odysseas12** [comment]
My guess would be you have some image optimization plugin or setting in wordpress that serves webp images if the browser supports them but once they are cached in nginx they always get served even on unsupported browsers.

**Comment by fevangelou** [comment]
Closing as it's not related to Engintron.

@odysseas12 thanks for the help :)
