### ISSUE TITLE
/tmp is bursted -2

### ISSUE THREAD

**Issue by ailyroot** [engintron/engintron#89]
Hi

I change path to 

# Proxy Settings
	proxy_cache_path /var/cache/nginx/engintron_dynamic levels=1:2 keys_zone=engintron_dynamic:20m inactive=10m max_size=500m;
	proxy_cache_path /var/cache/nginx/engintron_static levels=1:2 keys_zone=engintron_static:20m inactive=10m max_size=1024m;
	proxy_temp_path /var/cache/nginx/engintron_temp;

but on "System Status & Info", I see empty on "Nginx Cache/Temp Disk Usage:", show as below
http://i.imgur.com/MGkRcRA.jpg

anything wrong on this setup?

**Comment by fevangelou** [comment]
Do not cross post please.
