### ISSUE TITLE
Error in Nginx restart

### ISSUE THREAD

**Issue by Shahzadqayyum** [engintron/engintron#895]
Hello!
I'm facing a weird problem today on my new server.
its a freshly installed server with whm/ and Engintron 1.9.0
but issue is with Nginx
when i try to reload nginx via engintron it does shows reloading nginx sign.
but do not show any error successful message even after 10 minutes.
when i try to restart reload apache it works normally.
when i restart both of them apache restarts fine but i can see this message for nginx.

Restarting Nginx...
Redirecting to /bin/systemctl restart nginx.service

help me fix this issue,
my server OS is centos 7.5
thanks in advance.

**Comment by ChristianGabs** [comment]
Restarting Nginx...
Redirecting to /bin/systemctl restart nginx.service

This is your message :D

Redirecting to /bin/systemctl restart nginx.service (This is your confirmation as nginx restarted !

**Comment by fevangelou** [comment]
Closing as there is no response from the OP.
