### ISSUE TITLE
mod_evasive with reverse proxy (engintron)

### ISSUE THREAD

**Issue by codep0et** [engintron/engintron#897]
Hello, I did some research and couldn't come up with anything usefull.

I was wondering if there was a way to configure mod_evasive to use the real ip forwarded by nginx because as of now, it will always blocked on of the server's ip address.

Thanks for any help :)

**Comment by ChristianGabs** [comment]
My understanding:

http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html

You can limit your request etc.

**Comment by codep0et** [comment]
@ChristianGabs Thanks alot for this. Very helpful !
