### ISSUE TITLE
engintron+cachewall cpanel subdomains not working

### ISSUE THREAD

**Issue by urbaman** [engintron/engintron#898]
Hi,

cpanel 72.0.10, Engintron 1.9.0, Cachewall (xVarnish).

Engintron on ports 80,443 to port 8080, Cachewall on port 8080 to port 82, Apache on port 82.

I have a domain (worldsinperil.it) with AutoSSL Domain Validated on subdomains like cpanel or webmail.
If I try whm.worldsinperil.it all browsers see it with a wrong certificate, using the main server's certificate (srvcp01.urbaman.it) and blocking them as un .

If I try cpanel or webmail, it presents a 503 backend error from Cachewall, but the right certificate.

I don't understand the different behaviours, and the certificate problem.

Is there a way to properly proxy them to www.worldsinperil.it:port?

**Comment by fevangelou** [comment]
Use Engintron only and be done with it.

Varnish is not meant to be used with cPanel out of the box. Its use case is
pretty limited and cannot be a one size fits all solution as Engintron is.
If it could have been I'd have developed a plugin myself. And if I ever do
in the future I'll make sure there's a big fat disclaimer on where/how it
can be used.

**Comment by urbaman** [comment]
Ok, disabled Cachewall.

Now, everything is ok when I go to http, trying to get the right certs for the subdomains to get https work properly.

**Comment by urbaman** [comment]
Ok, now having issues with SSL generation for all proxy subdomains (whm, cpcontacts, cpcalendar, autoconfig are missing).

Closing the issue and switching to cpanel forums.

Thank you very much!

**Comment by fevangelou** [comment]
Reinstall Engintron to also restore port settings for Nginx and Apache.
