### ISSUE TITLE
custom proxy subdomain

### ISSUE THREAD

**Issue by urbaman** [engintron/engintron#900]
Hi,

Is it possible to add a "generic" proxy rule, with or without cache, like domain.com/netdata, proxying to port 19999?

Thank you,

**Comment by urbaman** [comment]
here's the formal documentation for netdata: https://github.com/firehol/netdata/wiki/Running-behind-nginx

**Comment by fevangelou** [comment]
See the changelog for the latest version. It describes a similar example
for a node.js app.

**Comment by urbaman** [comment]
And here it is for netdata (netdata.domain.com):

if ($host ~* "(netdata)") {
    #set $PROXY_SCHEME "http";
    #set $PROXY_DOMAIN_OR_IP $host;
    set $PROXY_DOMAIN_OR_IP "127.0.0.1";
    set $PROXY_TO_PORT 19999;
}

I wasn't able to redirect /netdata, that would preserve the SSL cert (I don't know how to get a cert for a custom subdomain not registered with cpanel, as it would get redirected to port 19999 and fail, right?), as the othe way around (if ($SITE_URI ~* "netdata")) throws me a 500 error.

**Comment by fevangelou** [comment]
Don't think a location block will work inside an if statement...
