### ISSUE TITLE
Prestashop Cookie

### ISSUE THREAD

**Issue by rbustos** [engintron/engintron#902]
There are a issues with Prestashop installations when using Engintron caused by Cookie catched in dynamic cache:

/etc/nginx/proxy_params_dynamic:

# CMS (& CMS extension) specific cookies (e.g. Joomla, K2 for Joomla, WordPress, WooCommerce)
if ($http_cookie ~* "(joomla_[a-zA-Z0-9_]+|userID|wordpress_[a-zA-Z0-9_]+|wp-postpass|comment_author_[a-zA-Z0-9_]+|woocommerce_cart_hash|woocommerce_items_in_cart|wp_woocommerce_session_[a-zA-Z0-9]+|sid_customer_|sid_admin_)") {

Please include Prestashop cookie in next release as shown below:

if ($http_cookie ~* "(joomla_[a-zA-Z0-9_]+|userID|wordpress_[a-zA-Z0-9_]+|wp-postpass|comment_author_[a-zA-Z0-9_]+|woocommerce_cart_hash|woocommerce_items_in_cart|wp_woocommerce_session_[a-zA-Z0-9]+|sid_customer_|sid_admin_**|PrestaShop-[a-zA-Z0-9_]+**)") {

**Comment by fevangelou** [comment]
PrestaShop-[a-zA-Z0-9] should be sufficient. Adding this in a while.

**Comment by fevangelou** [comment]
Merged in https://github.com/engintron/engintron/commit/4a6b94e8389df92d5f51cd67b522c63553f9ae7b
