### ISSUE TITLE
mod_bwlimited

### ISSUE THREAD

**Issue by JorgeMarcelino-HS** [engintron/engintron#903]
Every time I restart apache + nginx I get these logs below, should I disable it mod_bwlimited?

[Tue Aug 14 06:23:42.579475 2018] [mpm_prefork:notice] [pid 3119609] AH00163: Apache/2.4.34 (cPanel) OpenSSL/1.0.2o mod_bwlimited/1.4 configured -- resuming normal operations

**Comment by fevangelou** [comment]
This is normal.
