### ISSUE TITLE
Webmail redirect https

### ISSUE THREAD

**Issue by maxisvk** [engintron/engintron#905]
Webmail subdomain not redirect from http to https, with engintron disable works. Test with 1.9 and Cpanel 72 & 74

**Comment by ddrhost** [comment]
Hello, see if the issue has been resolved in the update.
https://github.com/engintron/engintron/wiki/Changelog#august-17th-2018---v191

**Comment by fevangelou** [comment]
@ddrhost It won't.

@maxisvk The solution is simple, using your "custom rules" file in Engintron's WHM app.

Append this:
```
if ($scheme = "http") {
    set $redirToSSL "yes";
}

if ($host ~* "^webmail\.") {
    set $isWebmail "please";
}

set $webmailRedirection $redirToSSL$isWebmail;

if ($webmailRedirection = "yesplease") {
	return 301 https://$host$request_uri;
}
```

Now all requests for webmail.* will be redirected to HTTPS.

**Comment by fevangelou** [comment]
Added in the wiki as well: https://github.com/engintron/engintron/wiki/Redirect-webmail.domain.tld-from-HTTP-to-HTTPS

**Comment by maxisvk** [comment]
i found problem when AutoSSL try to renew webmail subdomain certificate, try to skip redirect when Let’s Encrypt need to verify seem to work... 

if ($scheme = "http") {
    set $redirToSSL "yes";
}

if ($host ~* "^webmail\.") {
    set $isWebmail "please";
}

if ($request_uri ~* "well-known") {
    set $isWebmail "SkipSSLRenew";
}

set $webmailRedirection $redirToSSL$isWebmail;

if ($webmailRedirection = "yesplease") {
	return 301 https://$host$request_uri;
}
