### ISSUE TITLE
IP Address not Forwarding to /var/log/apache/domlogs/<domain>

### ISSUE THREAD

**Issue by devteam9200** [engintron/engintron#909]
I am running Centos 7 and cloud linux / WHM 74.0.4 and Engintron mainline latest build v1.9.1
Build 20180817 (Nginx version: 1.15.2). 

I have tried already tried several "Restore Nginx IP forwarding in Apache" in engintron panel. As well as Engintron re-install mainline. And no luck. 

Tried this : https://www.damchey.com/2018/01/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel/  and no luck replacing the %h with %a 

Then performed the following as per discussions here: https://github.com/engintron/engintron/issues/489

Did the following steps essentially from the above link . 
1 $ cd /var/cpanel/templates/apache2_4
2 $ cp ea4_main.default ea4_main.local
3 Make the following changes to the ea4_main.local file Look for the %h and replace all  with %{X-Real-IP}i
4. /scripts/rebuildhttpdconf    
5. /scripts/restartsrv_apache

Then reinstall Engintron again. No luck??

I am missing some thing here? Or a bug? Any assistance would be much appreciated my friends. Thank you! Overall great product nice work!

**Comment by nandogameiro** [comment]
Hi @devteam9200 ,

I used to do the same when cPanel didn't allow we change it directly on the WHM, but now they do allow.

On WHM go to Apache Configuration -> Global Configuration -> LogFormat (combined) use the line

%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"

After that should be all fine. For me these steps worked and every time that cPanel or Engintron updates these settings will be kept. 

You must have Easy Apache 4.

![image](https://user-images.githubusercontent.com/10284807/44314081-538b6b00-a468-11e8-8710-357e2c2f200f.png)

Hope this works for you.

Cheers

**Comment by devteam9200** [comment]
CHAMPION!!! Too easy nice one! Working! Much appreciated as always. 
Perhaps may i suggest we include this process in our installation documentation guideline? https://github.com/engintron/engintron/wiki/02.-Installation-(and-updates) 

As I have installed Engintron in the past on old centos 6 server and it was same issue but was so long ago and what i had documented did not appear to be working this time. I believe this issue is common but i may be wrong.. But overall nice product and well done. I leave it over to you guys! 

Thanks!
