### ISSUE TITLE
Connection between Nginx and Apache should be http/2 or http/1.1?

### ISSUE THREAD

**Issue by rvencu** [engintron/engintron#910]
I noticed in Apache Status page that all connections to Apache are listed as http/1.1. Is this normal, abnormal or just wrongfully displayed on that page?

**Comment by ChristianGabs** [comment]
Hi Rvencu,

Is normal and the reason is this.

> **Is HTTP/2 proxy support planned for the near future?**
> Short answer:
> **No, there are no plans.**
> Long answer:
> 
> There is almost no sense to implement it, as the main HTTP/2 
> benefit is that it allows multiplexing many requests within a 
> single connection, thus [almost] removing the limit on number of 
> simalteneous requests - and there is no such limit when talking to 
> your own backends.  Moreover, things may even become worse when 
> using HTTP/2 to backends, due to single TCP connection being used 
> instead of multiple ones.
> 
> On the other hand, implementing HTTP/2 protocol and request 
> multiplexing within a single connection in the upstream module 
> will require major changes to the upstream module.
> 
> Due to the above, there are no plans to implement HTTP/2 support 
> in the upstream module, at least in the foreseeable future.  If 
> you still think that talking to backends via HTTP/2 is something 
> needed - feel free to provide patches.

Description will give you the reason : http/2 it's set as nginx you don't have to pass in apache.

**Comment by rvencu** [comment]
Thanks.
