### ISSUE TITLE
How can we Hide Engintron From our Resellers?

### ISSUE THREAD

**Issue by Cavain** [engintron/engintron#911]
Hello,

I don't want my resellers to see Engintron in plugin section. I know that they don't have access to make any actions or use engintron. On the same way I don't want them to see the engintron in plugin section how can we hide it for resellers? I remembers in early releases engintron was not showing in resellers section.

Thank you.

**Comment by fevangelou** [comment]
Are you referring to the menu entry on the side? I don't think it's possible to hide that.

**Comment by Cavain** [comment]
@fevangelou But in your early releases Engintron was not visible in Resellers tab.

**Comment by fevangelou** [comment]
I never controlled that. That being said, Engintron Pro is coming in the next 2-3 months and you will have the option to define which users can access it in WHM (among many other features on top of the regular Engintron release).

**Comment by Cavain** [comment]
Ohh, Great Thanks I'll wait then.

**Comment by fevangelou** [comment]
Closing for now.
