### ISSUE TITLE
Dynamic rate limiting module

### ISSUE THREAD

**Issue by Nexxed** [engintron/engintron#912]
Been looking at most of the issues here and found out that Engintron installs from a repo. I think it would be better if Engintron had its own repo so that we can suggest modules that will make our cPanel servers even more optimized (which is the main focus of Engintron in general). One of which is a rate limiting module (different to the default Nginx module) that can ban rate limited visitors for a specified time in seconds. You can define the ban time for each zone, and it's pretty much the same as the default module. It also has dynamic module support, if anyone is wondering:
https://github.com/limithit/ngx_dynamic_limit_req_module

**Comment by fevangelou** [comment]
Easier said than done.
