### ISSUE TITLE
Disabling engintron several times in a row incorrectly modifies the proxy_port

### ISSUE THREAD

**Issue by hluaces** [engintron/engintron#914]
Hello.

Probably an edge case, but still reporting it.

`engintron.sh` doesn't check the state of the service when you try to enable or disable the plugin. This causes the up/down scripts to modify the variable `$PROXY_TO_PORT` on each execution, appending the number **80** each time.

To reproduce the issue simply do the following.

1- Disable engintron with `/engintron.sh disable`.
2- Check the value of the `PROXY_DEFAULT` variable in `/etc/nginx/conf.d/default.conf` (it should be **80**).
3- Disable engintron again (the value should now be **8080**)
4- Do it one more time.
5- Open the `/etc/nginx/conf.d/default.conf` file and see how the value for `PROXY_DEFAULT` is now **808080**.

If you try to enable engintron again, the proxy port won't be **8080**, as expected. It might be being **80, 808080, 80808080** or something else depending on how many times you enabled/disabled the plugin.

This doesn't happen on HTTPS requests as the sed is unaffected.

I'll probably do a PR later to fix this, just opening the issue to document the behavior.

**Comment by fevangelou** [comment]
Thanks for this. I also updated the enable/disable functions to also cover the SSL port (just in case).
