### ISSUE TITLE
WHM Interface permission code is broken

### ISSUE THREAD

**Issue by frogstarr78** [engintron/engintron#916]
engintron.php line 15

> function checkacl() 
> {
>     $user = $_ENV['REMOTE_USER'];
>     if ($user == "root") {
>         return 1;
>     }
>     $reseller = file_get_contents("/var/cpanel/resellers");
>     foreach (str_split("\n", $reseller) as $line) {
>         if (preg_match("/^$user:/", $line)) {
>             $line = preg_replace("/^$user:/", "", $line);
>             foreach (str_split(",", $line) as $perm) {
>                 if ($perm == "all") {
>                     return 1;
>                 }
>             }
>         }
>     }
>     return 0;
> }

str_split should be explode (ref: http://php.net/str_split vs http://php.net/explode). I've fixed this on my local copy, but then the page errs with code 500, so there is still some other errors in the code somewhere. 

/var/cpanel/resellers:
user:all

Here's the error when run on the cli, substituting the user value:

`Warning: str_split() expects parameter 2 to be long, string given in /root/t.php on line 10`

root@server [~]# php -v
ea-php-cli Copyright 2017 cPanel, Inc.
PHP 5.5.38 (cli) (built: Aug 21 2018 16:56:06) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with the ionCube PHP Loader v4.7.5, Copyright (c) 2002-2014, by ionCube Ltd., and
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

root@server [~]# whmapi1 version
--- 
data: 
  version: 11.74.0.6

Here's the error we get:
You do not have sufficient permissions to access this page...

**Comment by fevangelou** [comment]
The file "/root/t.php" is not part of Engintron.
