### ISSUE TITLE
Adding Additional .conf File to Load for Rocket-Nginx

### ISSUE THREAD

**Issue by MojoCreator** [engintron/engintron#917]
I am trying to add another include to be used with Wordpress installations of WPRocket. I am not sure if this is where I need to add the include or not. I tested with nginx -t and it only brings back the following:

`nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
`
I tried adding to the current server variable with no results, see here, https://www.screencast.com/t/vetY1tRePuA0

Where do I need to add the include so Nginx will also pull in the Rocket-Nginx .conf file?

https://github.com/maximejobin/rocket-nginx/

**Comment by josephsimony** [comment]
I'd be also interested if there's any performance difference with Rocket-Nginx.
WPRocket works fine with Engintron. I thought Nginx is already serving WPRocket generated static pages - thanks to Engintron - instead of Apache (sorry for not going more in-depth with this; I guess I don't even understand the Rocket-Nginx description: why would be static HTML pages would be parsed/executed by PHP and WordPress at all?)

**Comment by hluaces** [comment]
WPRocket generated cache files do not need PHP or WordPress to be executed at all, they are static files which are served via `.htaccess` rules on the Apache side. That configuration you link is needed only if you are using a standalone Nginx installation (a LEMP stack).

Engintron already handles this as it forwards the requests to Apache (caching them afterwards), which correctly serves the rocket-static content without executing php.

`rocket-nginx` is aimed to be used on LEMP stacks —that is, a stack with Nginx and not Apache. Engintron uses a LAMP stack with a caching Nginx, so it is not the same use case.

Engintron also handles caching static files, expiration, and cache-control, so the performance gains that could come from that configuration are minimal, and you would require to adapt the whole structure of config files, as there are several of them which would collide.

My advice: you don't need that config. Maybe there are some bits here and there that can be reused on Engintron, but that's it. If you were to implement it, you'd probably need to rework a lot of config files.

**Comment by MojoCreator** [comment]
@josephsimony - agreed but it seems @hluaces responded in detail (thanks, thats exactly what I needed to know) - no 'major' benefit to using the config file for WPRocket-nginx.  I will let it be, thanks again for the help @hluaces

**Comment by fevangelou** [comment]
@hluaces On the spot!
