### ISSUE TITLE
micro caching

### ISSUE THREAD

**Issue by moamen1** [engintron/engintron#918]
i cant disablr micro caching in engintrom version 1.9.1

because the line that i comment isn't in the default.conf file 

can anybody help

because i have a problem with users, when refresh user page change and users complaining.

**Comment by fevangelou** [comment]
Just add this in your custom rules:

`set $CACHE_BYPASS_FOR_DYNAMIC 1;`

**Comment by fevangelou** [comment]
I also updated the wiki entry: https://github.com/engintron/engintron/wiki/About-Engintron's-micro-caching-features
