### ISSUE TITLE
A few questions about the system.

### ISSUE THREAD

**Issue by yasinyurtalan** [engintron/engintron#919]
Hello;
 
First of all thank you for your engintron system. I will be the 2 of them.
 
1. Compared to Litespeed? How much performance did you get when compared?
2. I have 2 ip addresses on my server for "set $PROXY_DOMAIN_OR_IP "xxx.xxx.xxx.xxx";" in the custom_rules section. How can I adapt this?
 
Thank you in advance, I wish you good work.

**Comment by fevangelou** [comment]
1. Depends. Overall you have finer control. Plus, you can't beat free.
2. You need to assign the main shared IP first and then the 2nd one wrapped in an "if" statement with the domains that it maps to.
