### ISSUE TITLE
cPanel mod_pagespeed

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#921]
Does cPanel mod_pagespeed work with engintron?

https://features.cpanel.net/topic/add-support-for-mod_pagespeed-to-easyapache4

**Comment by windsofchange** [comment]
Engintron is a proxy. So it that works with Apache is the question to be asked. If that works with Apache the proxy will do it's job

**Comment by mustafamsy** [comment]
Yes, it works with engintron. 

> Does cPanel mod_pagespeed work with engintron?
> 
> https://features.cpanel.net/topic/add-support-for-mod_pagespeed-to-easyapache4

**Comment by aliozinan** [comment]
Just asking, I've installed and enabled mod_pagespeed for apache and have Engintron installed and running. Will this config do the job or do we need to install the ngxpagespeed? What would be the difference?

**Comment by fevangelou** [comment]
It will be fine. mod_pagespeed will process Apache's output. Nginx will ensure everything is speedily served.

**Comment by aliozinan** [comment]
thanks for the info
