### ISSUE TITLE
EA4 profile 2018_v3 warning

### ISSUE THREAD

**Issue by gasmas75** [engintron/engintron#922]
Hello. First of all a big thank you for this great plugin. Saved a lot of my server's resources and gave it a great performance boost.
I'm want to activate the EA4 profile but I get a warning:

> This profile includes the following packages that are not supported on this server: 
> mod_fcgid 
> mod_hostinglimits 
> php56-php-memcached 
> php70-php-memcached 
> php71-php-memcached 

Is it safe to proceed? Should I remove them from the profile before provisioning?
info:
OS: CentOS Linux release 7.5.1804 (Core)
Kernel: Linux 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Thank you in advance

**Comment by lamasbr** [comment]
The same here... anyone?

**Comment by radonn24** [comment]
Same here ... advice?

CentOS Linux release 7.5.1804 (Core)
WHM v74.0.9

**Comment by fevangelou** [comment]
These packages come from the EA4 Experimental repo (if you have it installed in your server). If you don't, they will simply not be installed. Which will not break anything either way.

https://documentation.cpanel.net/display/EA4/The+Experimental+Repository
