### ISSUE TITLE
How can i proxy_pass 

### ISSUE THREAD

**Issue by vowave** [engintron/engintron#923]
Hello,
How can i proxy_pass a domain from ip, so when ever i call a file on that domain in my website i can access it with that ip.
I want to do something like this but from my own server.

server {
        listen 80;
        server_name onesignal.com;
        location / {
                resolver 8.8.8.8 ipv6=off;
                proxy_pass https://onesignal.com;
        }
}
server {
        listen 443;
        server_name onesignal.com;
        location / {
                resolver 8.8.8.8 ipv6=off;
                proxy_pass https://onesignal.com;
        }
}

**Comment by fevangelou** [comment]
Use custom rules.

```
if ($host = "onesignal.com") {
    set $PROXY_DOMAIN_OR_IP "onesignal.com";
    set $PROXY_SCHEME "https";
}
```

Although it doesn't really make sense to do all that just to redirect to https.

**Comment by vowave** [comment]
Thank you for your reply, actually i want to do this so my users will access to onesignal javascripts using my server ip. They have banned my country from using it

**Comment by vowave** [comment]
Actually someone I know solved this issue on nginx it self (not engintron) by adding this code 
`$ vim /etc/nginx/site-enables/filter_onesignal
server {
        listen 80;
        server_name onesignal.com;
        location / {
                resolver 8.8.8.8 ipv6=off;
                proxy_pass https://onesignal.com;
        }
}
server {
        listen 443;
        server_name onesignal.com;
        location / {
                resolver 8.8.8.8 ipv6=off;
                proxy_pass https://onesignal.com;
        }
}`
in another VPS nginx website rules and then added the code below to main website's hosts file 
`VPSSERVERIP onesignal.com`

and i was wondering to do this on one server and with engintron

**Comment by fevangelou** [comment]
Yes, but all the above is server-side. It will NOT affect sites that may directly call onesignal.js. Do you understand the difference?

**Comment by vowave** [comment]
yes i do , but then can you suggest me something useful please ?
Im loosing lots of users because of this...
Regards

**Comment by ylluminate** [comment]
Is this effectively the same as Apache's reverse proxy function where you have Apache forward all web (80 + 443) traffic to another server on another IP and port?  For example, if I have web traffic hitting `domain.tld` on cPanel, but I want Nginx/Engintron to pass all of this traffic back and forth to 1.1.1.1:8080, is it done as above?

Is there some more thorough documentation for this and locations of the files to edit, etc?  Or is there an Engintron forum where we can talk about these issues more fully than using Github issues?

**Comment by fevangelou** [comment]
First off, read the docs at https://engintron.com/docs/ - then examine the comments in the "custom rules" file in Engintron. Cause the answer is, yes, you can do what you ask.

**Comment by Revthy** [comment]
Hello,
my custom rule 
if ($SITE_URI ~* "www.example.com/dist/v1/paypal/cp-webhook")
{
    set $PROXY_DOMAIN_OR_IP "billing.example.com";
    set $PROXY_SCHEME "https";
    set $PROXY_TO_PORT 9090;
}
I have remove 'dist' while reverse proxy. For ex: https://billing.example.com:9090/v1/paypal/cp-webhook
How to add proxy path

**Comment by fevangelou** [comment]
@Revthy I don't understand the question. You want to remove "dist" from the path or it's deleted automatically? And no, you can't set a custom proxy path.

**Comment by Revthy** [comment]
Hi @fevangelou 

Let me explain you in more detailed here;

This is my custom rule which I developed -
if ($SITE_URI ~* "www.example.com/dist/v1/paypal/cp-webhook")
{
set $PROXY_DOMAIN_OR_IP "billing.example.com";
set $PROXY_SCHEME "https";
set $PROXY_TO_PORT 9090;
}

In the above rule, if you observed there is "/dist" in the request URL. I wanted to remove that from the URL. Can you please help me on how to remove it.

**Comment by fevangelou** [comment]
Do you mean that the actual URL fetched (via proxy) is `billing.example.com/dist/v1/paypal/cp-webhook`?

**Comment by Revthy** [comment]
Hi @fevangelou ,

Thank you for your support.

Actual fetched URL  is www.example.com/dist/v1/paypal/cp-webhook

Sending URL  (proxy pass) should be like this  billing.example.com/v1/paypal/cp-webhook

is it possible?

**Comment by fevangelou** [comment]
You should map www.example.com/dist/ to billing.example.com/ then.

If you can't do that, you're out of luck.
