### ISSUE TITLE
cPanel login features broken when using domain name to login to WHM

### ISSUE THREAD

**Issue by swartjie** [engintron/engintron#924]
Hey Guys,

Ok so today I noticed that when a reseller uses domain.tld/whm or whm.domain.tld to login to his WHM account, he cannot use the cPanel quick login icons to login to an account, it changes the link to cpanel.servername.....

Is there a way to bridge this issue? Or does it need to have a bug reported and fixed?

**Comment by ddrhost** [comment]
I tested it and the problem also occurs here.

**Comment by swartjie** [comment]
I would love to start using enginetron again if this bug can be fixed...

**Comment by fevangelou** [comment]
That looks like cPanel behaviour...

**Comment by swartjie** [comment]
No it;s the proxy infront of the CP interface causing the issue, when disabling engintron issue resolved immediately...

Very sad, I love the software, but causing too much issues with resellers
