### ISSUE TITLE
facing some issue with codeigniter 

### ISSUE THREAD

**Issue by srikanta159** [engintron/engintron#926]
I have made a project with CodeIgniter and it's having some issues like after user login its come blank space and users are not redirect to the dashboard. I have excluded that domain with micro caching still facing the problem. after disabling engintron its work fine again.

**Comment by fevangelou** [comment]
Disable micro-caching. See "custom rules" comments or the Engintron Docs/Wiki for more info on how to do that.

**Comment by srikanta159** [comment]
did but still same issues

**Comment by srikanta159** [comment]
no solution.. i just changed from engintron to cpnginx and everything is
working fine.

**Comment by fevangelou** [comment]
@srikanta159 Yeah, sure.
