### ISSUE TITLE
Connection Refushed

### ISSUE THREAD

**Issue by Minemarc98** [engintron/engintron#927]
Hello,

I have a problem with engintron, I installed it a few days ago in my Cpanel but I could not have it active for a long time since when I keep it active the web pages do not work, it is strange since only some web pages fail, others do not have that problem . I have an account where I have my websites with a Dedicated IP and some of those pages work and others do not (I have configured the domains in custom rules assigning the Dedicated IP)

After the pages of my clients, some works and others do not.

When I enter the web pages, from the browser, it appears: Connection Refushed. And when I enter nginx error_log, Connection Time out appears.

I can not be active long engintron to be able to show you since I have clients and need uptime.

I hope you can help me with this, thanks!

**Comment by fevangelou** [comment]
Make sure the firewall is not blocking ports 8080 and 8443.
