### ISSUE TITLE
problem in automatic WHM generation of  /etc/nginx/conf.d/default_https.conf

### ISSUE THREAD

**Issue by lpasquali** [engintron/engintron#929]
Hello and gretings from Italy,
 
we are experiencing some problems in ngnix unattended restarts upon variations in WHM virtualhosts:

`set 18 12:19:18 webapp2.netsons.net nginx[916565]: nginx: [emerg] pread() returned only 0 bytes instead of 4069 in /etc/nginx/conf.d/default_https.conf:4495`

from nginx v1.14.0 source I see that this error message should be related to geoip code whish should not be enabled from my understanding of engintron's build:
```
./src/http/modules/ngx_http_geo_module.c:            ngx_read_file_n " \"%s\" returned only %z bytes instead of %z",
./src/stream/ngx_stream_geo_module.c:            ngx_read_file_n " \"%s\" returned only %z bytes instead of %z",
```
If I list the modules built in the nginx binary:
```
[root@webapp2 nginx-1.14.0]# 2>&1 nginx -V | tr -- - '\n' | grep _module
http_addition_module 
http_auth_request_module 
http_dav_module 
http_flv_module 
http_gunzip_module 
http_gzip_static_module 
http_mp4_module 
http_random_index_module 
http_realip_module 
http_secure_link_module 
http_slice_module 
http_ssl_module 
http_stub_status_module 
http_sub_module 
http_v2_module 
mail_ssl_module 
stream_realip_module 
stream_ssl_module 
stream_ssl_preread_module 
[root@webapp2 nginx-1.14.0]# 
```
sorry if my question sounds dumb to you but I never explored this part of the nginx source code before: are the stream_* modules inheriting such methods in ngx_stream_geo I pasted above which may return the configuration error message?

our /etc/nginx/conf.d/default_https.conf is right now 2.1 Mb, each time a definition block from apache configuration is added we see the problem happening

could it be also related to the fact that we may tune up:

 `set 18 12:31:53 webapp2.netsons.net nginx[932618]: nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 1024 or server_names_hash_bucket_size: 1024; ignoring server_names_hash_bucket_size`

server_names_hash_max_size: 1024 (considering the dimension of default_https.conf it might be raised)
server_names_hash_bucket_size: 1024 (our L1 processor cache is 16kb)

this cPanel server has more or less 2400 small virtual hosts.
we were also never been able to see /etc/nginx/conf.d/default_https.conf at 0 bytes, every time I see the webserver down I log in and it comes up nicely.

do you have any ideas about what could cause this problem?

**Comment by fevangelou** [comment]
I believe it's lack of RAM that causes these errors. You should seriously consider optimizing your server's database, Apache, PHP and the system itself to save resources.
