### ISSUE TITLE
Authorization header is stripped

### ISSUE THREAD

**Issue by alegolash** [engintron/engintron#930]
Ηello,
I am trying to allow a POST request to my server using a webhook.
External server gets authorized to run the php script only if sending correct Authorization header (with Bearer token).
Using apache_request_headers() we get all Request headers except "Authorization" header.
Authorization header is not showing up on the PHP side and it seems that Nginx is stripping or disallowing it.
I always get 401 Unauthorized as response.

How could we allow Authorization header to pass to php?

Thank you in advance

**Comment by zstergios** [comment]
@fevangelou I have same issue, may is general miss function of cpanel/apache, but do you have any workground how to solve this?
Probably you can add this to vhost, but this you can make it feature
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

Source https://forums.cpanel.net/threads/add-line-of-code-to-vhost.598267/

**Comment by fevangelou** [comment]
I don't see why Nginx would strip a header like that. I'm guessing the issue is between Apache and Nginx.

You gotta show me a real URL to test so I can see the headers live. Create a test account somewhere and lock it down.

@alegolash Try using a custom header and decrypt it on the app's side as an alternative.

**Comment by zstergios** [comment]
@fevangelou  I have successfully tested the above method.

As your solution adds many features (general purpose) this will help many people too!
Please add this feature, is lifesaver! Just add a button to create this file
/etc/apache2/conf.d/userdata/engitrion_authorizationheader.conf with contents
` SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`




/usr/local/cpanel/scripts/rebuildhttpdconf
/usr/local/cpanel/scripts/restartsrv_httpd

**Comment by fevangelou** [comment]
These are Apache directives, not Nginx directives. This has nothing to do with Engintron.

And since someone installs Engintron on a server, they can also add that too (if they wish to use it).
