### ISSUE TITLE
Apache restart fails in CentOS 7

### ISSUE THREAD

**Issue by hyssop** [engintron/engintron#931]
I discovered that the Apache restart command in the plugin calls /scripts/restartsrv_httpd which appears to work in the Enginetron plug interface, just as it does from the command line. But systemctl status httpd.service shows that it does not actually restart. 

In CentOS 7 it should be systemctl restart httpd.service 

From cPanel Docs (https://documentation.cpanel.net/display/CKB/How+to+Restart+Services): 

> If the /usr/local/cpanel/scripts/restartsrv_* script does not restart the service, you can attempt to restart the service directly.
> 
> For servers that run CentOS, CloudLinux™, Red Hat® Enterprise Linux (RHEL) 6, or Amazon Linux, run the following command, where /etc/rc.d/init.d/service is the path to the service: /etc/rc.d/init.d/service restart
> 
> For servers that run CentOS 7, CloudLinux 7, or RHEL 7, run the following command, where service-name is the service that you wish to restart: systemctl restart service-name.service

Note, the following scripts do work:
/scripts/restartsrv_mysql
/scripts/restartsrv_apache_php_fpm
/scripts/restartsrv_chkservd

My server:
CentOS 7.5
WHM 74.0.8

**Comment by hyssop** [comment]
Did anyone ever look at this....?

**Comment by fevangelou** [comment]
This is the cPanel Apache restart script. It does more checks than just "service httpd restart" or the systemctl equivalent.

**Comment by webgoon** [comment]
I actually though this project was cool only thing I'm having the same exact problem mentioned above has there been any resolution to this?

**Comment by hyssop** [comment]
> 
> 
> This is the cPanel Apache restart script. It does more checks than just "service httpd restart" or the systemctl equivalent.

I realize that, but per the cPanel docs, and my testing, the script you call doesn't restart Apache.

#systemctl restart httpd.service       <---Does restart Apache.

Maybe it's a cPAnel bug (I'm posting a thread on it there next) but the script you call doesn't restart Apache at this time.

-Pete

**Comment by hyssop** [comment]
Update: the default for /scripts/restartsrv_httpd is a *graceful (soft)* restart. The systemctl restart is a hard restart by default, and the same is true for the WHM Apache restart.. This accounts for the difference I was seeing. Sorry I didn't recognize this at the start...

> I actually thought this project was cool only thing is that I'm having the same exact problem mentioned above. Has there been any resolution to this yet?

@webgoon Can you detail what the Engintron restart isn't accomplishing for you? Unfortunately, I can't remember what wasn't working for me when restarting via Engintron, but something was giving me a problem (that WHM's hard restart didn't). It may simply be that certain things require a hard restart, and so maybe the option should be there in Engintron.

-Pete

**Comment by fevangelou** [comment]
@webgoon Oh, it's still cool. And it's about to get 10 times cooler with v2... 😎
