### ISSUE TITLE
Mixed session information

### ISSUE THREAD

**Issue by DanielRivera1309** [engintron/engintron#932]
We started to experience this serious problem from 1.9.1 version.

Using WHMCS for example, our users are seen the account of other clients... We have another 3 systems with PHP sessions and the issue is the same... When one user logged in, his info is displayed, but, when other user logged in and the first user refresh the page, the info of the second user is displayed.

I hope to found a prompt solution, because of this we had to disable engintron in all servers due security and multiple reports of our users.

**Comment by Mul-tiMedia** [comment]
Thank you @DanielRivera1309 for pointing out this problem. We also have a high traffic website with lots of users. As per today we installed engintron on our server. Within 30 minutes the first users started to complain they where loggedin as someone else....  After disabling engintron everything was back to normal.

It's the problem of the php sessions. We use laravel which have run with no problems on a other server with nginx (directadmin)... Very strange issue...

**Comment by fevangelou** [comment]
The 1 sec micro-cache should not be an issue, even for sites with user-generated content. The problem may be a combination of non-null Cache-Control HTTP headers sent when a user is logged in.

At the same time, these clarifications are both in the comments in the "custom rules" file, as well as the Engintron Docs.
