### ISSUE TITLE
Help with critical errors upon hitting deleted cached files

### ISSUE THREAD

**Issue by lpasquali** [engintron/engintron#933]
It looks like that when nignx tries to look after cached files 

2018/09/25 14:28:13 [crit] 600009#600009: unlink() "/var/cache/nginx/engintron_dynamic/b/69/7c54e71590a6ba583a154f56eaebf69b" failed (2: No such file or directory)
2018/09/25 14:28:14 [crit] 600009#600009: unlink() "/var/cache/nginx/engintron_dynamic/5/ce/a986028b2045684b44f7aebd38ae3ce5" failed (2: No such file or directory)
2018/09/26 04:16:19 [crit] 769662#769662: unlink() "/var/cache/nginx/engintron_dynamic/a/87/244157bd804cec8c5e634b13c9b2787a" failed (2: No such file or directory)
2018/09/26 04:16:20 [crit] 769662#769662: unlink() "/var/cache/nginx/engintron_static/0/21/52faa50c9197198691a70a1119982210" failed (2: No such file or directory)
2018/09/26 04:52:16 [crit] 2053133#2053133: unlink() "/var/cache/nginx/engintron_dynamic/1/3f/bde64b0b40ea5a8cb69a6f5fef6b63f1" failed (2: No such file or directory)
2018/09/26 04:52:18 [crit] 2053133#2053133: unlink() "/var/cache/nginx/engintron_dynamic/d/a1/35536f688ac8d381f1f0494c39263a1d" failed (2: No such file or directory)
2018/09/26 04:52:18 [crit] 2053133#2053133: unlink() "/var/cache/nginx/engintron_dynamic/4/ad/def872e1a4584a95cc8a436eb9780ad4" failed (2: No such file or directory)
2018/09/26 04:52:20 [crit] 2053133#2053133: unlink() "/var/cache/nginx/engintron_dynamic/5/5f/682f315f4b8241f600801eeab03505f5" failed (2: No such file or directory)
2018/09/26 04:52:23 [crit] 2053133#2053133: unlink() "/var/cache/nginx/engintron_dynamic/6/b9/f164abdd752c8985e706d43a908a1b96" failed (2: No such file or directory)
2018/09/26 04:52:24 [crit] 2053133#2053133: unlink() "/var/cache/nginx/engintron_dynamic/8/00/155e1f39c3f5974804339aa3ce03e008" failed (2: No such file or directory)

it raises a critical error in the logs because of this nginx piece of code:

        if (ngx_delete_file(name) == NGX_FILE_ERROR) {
            ngx_log_error(NGX_LOG_CRIT, ngx_cycle->log, ngx_errno,
                          ngx_delete_file_n " \"%s\" failed", name);
        }

We do not do any cache deletion by hand, we use:  

/usr/local/src/engintron/engintron.sh purgecache

looking at the code of your script:

    find /var/cache/nginx/engintron_dynamic/ -type f | xargs rm -rvf
    find /var/cache/nginx/engintron_static/ -type f | xargs rm -rvf
    find /var/cache/nginx/engintron_temp/ -type f | xargs rm -rvf
    if [ "$(pstree | grep 'httpd')" ]; then
        echo "Restarting Apache..."
        /scripts/restartsrv apache_php_fpm
        /scripts/restartsrv_httpd
        echo ""
    fi
    if [ "$(pstree | grep 'nginx')" ]; then
        echo "Restarting Nginx..."
        service nginx restart
        echo ""
    fi

I suggest something like:

    if [ "$(pstree | grep 'httpd')" ]; then
        echo "Restarting Apache..."
        /scripts/restartsrv apache_php_fpm
        /scripts/restartsrv_httpd
        echo ""
    fi
    if [ "$(pstree | grep 'nginx')" ]; then
        find /var/cache/nginx/engintron_dynamic/ -type f | xargs rm -rvf
        find /var/cache/nginx/engintron_static/ -type f | xargs rm -rvf
        find /var/cache/nginx/engintron_temp/ -type f | xargs rm -rvf
        echo "Restarting Nginx..."
        service nginx restart
        echo ""
    fi

This would probably avoid 99% of criticals as the apache configuration (I think it has something like 2200+ vhosts) in question keeps a bit to restart, bit which is enough to get dozens of critical error logs, which are awfukl to ignore in production systems so there have not to be false positives like this nginx criticals by design (I also think that nginx.com commercial version has improved code handling this).
I will send you the patch as a pull request

**Comment by fevangelou** [comment]
It takes more time to restart Apache & PHP-FPM than it does to delete the files? How many accounts does that server have on (you have a typo in your message)?

**Comment by lpasquali** [comment]
Hello!
(I updated the typos above, I am sorry), to be precise we use Cloudlinux and so lsapi handles php.
 Whel the answer to your question can be only yes, its the delay addition, which might be totally randomic, of how sometimes apache2 goes down a bit slower, now it is:
- deleting files
- apache restarts, while httpd gets SIGTERM new requests may come in as long as all other apache2 processes get stopped.
- nginx restarts, forgets about purged files which had still memory footprints in the old nginx process
if is done as suggested:
- apache restarts, while httpd gets SIGTERM new requests may come in as long as all other apache2 processes get stopped.
- deleting files
- nginx restarts, forgets about purged files which had still memory footprints in the old nginx process
we are talking about milliseconds probably, but that's enough to get some cached requests being hit. 

So if I delete the files right before I restart nginx there is less chances to get the cache being hit by some request.

As you can see from my previous mail the "glitch" happens mostly in the dynamic cache, I would not call this a bug, as it's because that piece of code in nginx is left as is by will having the enterprise payed version a whole set of functions there to handle in many different ways that critical error message.
Also, it's a shared hosting platform, and as any shared hosting platform has its good share of users with almost any kind of  cms or php site competing for server's resources.
We are going to test the deletion right before nginx and let you know if it is worth to merge my pull request

**Comment by fevangelou** [comment]
I've actually seen large caches of Nginx files, that's why I asked. Also, do share which company it is that's using Engintron. I plan on making a list of hosting companies using Engintron soon.

If you don't want to state the name now, you can always email me on engintron [at] gmail [dot] com.

**Comment by fevangelou** [comment]
Merged in v1.9.3.
