### ISSUE TITLE
limit_conn_zone not working

### ISSUE THREAD

**Issue by mpxbrasil** [engintron/engintron#935]
Hello, i tried to configure limit_conn_zone in default.conf but it seems not working.
Where do i write this settings?

limit_conn_zone $binary_remote_addr zone=conn_limit_per_ip:10m;
limit_req_zone $binary_remote_addr zone=req_limit_per_ip:10m rate=5r/s;

**Comment by mpxbrasil** [comment]
@fevangelou can you help me?

**Comment by fevangelou** [comment]
Sorry, it's out of the scope of the support I provide here.
