### ISSUE TITLE
failed (99: Cannot assign requested address) while connecting to upstream,

### ISSUE THREAD

**Issue by Shreewebs** [engintron/engintron#938]
I am facing this issue quite frequently that the Nginx Services goes down with the following error messages.
2018/09/29 23:34:57 [crit] 4793#4793: *210641 connect() to Xx.XX.XX.XXX:80 failed (99: Cannot assign requested address) while connecting to upstream, client: Xx.XX.XX.XXX, server: localhost, request: "GET /?sitemap84.xml HTTP/1.1", upstream: "http://Xx.XX.XX.XXX:80/?sitemap84.xml", host: "domain.com"

Kindly suggest what needs to be done as there is no Varnish installed on the server

**Comment by mofolo** [comment]
I get the same issue. Previously going into Tweak Settings (on Cpanel) and clicking Save would fix it, but now it's not. 
The issue seems to happen whenever I change something to the httpd.conf.

**Comment by fevangelou** [comment]
Tried this? >> https://ma.ttias.be/nginx-cannot-assign-requested-address-for-upstream/
