### ISSUE TITLE
Engintron WHM page blank

### ISSUE THREAD

**Issue by inertz** [engintron/engintron#939]
Hi,
My server still using old version WHM version 56.
The Engintron page is blank.
Refer to Cpanel error log;
`[03-Oct-2018 11:29:50 Asia/Shanghai] PHP Warning:  require_once(/usr/local/cpanel/php/WHM.php): failed to open stream: No such file or directory in /usr/local/cpanel/whostmgr/docroot/cgi/engintron.php on line 12
[03-Oct-2018 11:29:50 Asia/Shanghai] PHP Fatal error:  require_once(): Failed opening required '/usr/local/cpanel/php/WHM.php' (include_path='/usr/local/cpanel/3rdparty/php/54/lib/php:.') in /usr/local/cpanel/whostmgr/docroot/cgi/engintron.php on line 12
[2018-10-03 11:29:50 +0800] warn [cpsrvd] The subprocess (php) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0xaec1920)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 72
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0xaec1920), "subprocess_name", "php", "subprocess_read_handle", IO::Handle=GLOB(0xb0af4e8), "subprocess_write_handle", GLOB(0xb0af59c)) called at cpsrvd.pl line 6307
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, 0, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 6125
	cpanel::cpsrvd::phpHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, 0, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 5789
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1674
	cpanel::cpsrvd::dodoc(HASH(0x87d76dc)) called at cpsrvd.pl line 1347
	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 841
	cpanel::cpsrvd::script() called at cpsrvd.pl line 334`

`root@svr52 [~]# nano +12 /usr/local/cpanel/whostmgr/docroot/cgi/engintron.php`
`root@svr52 [~]# cat /usr/local/cpanel/php/WHM.php`
`cat: /usr/local/cpanel/php/WHM.php: No such file or directory`
`root@svr52 [~]# cd /usr/local/cpanel/php/`
`root@svr52 [/usr/local/cpanel/php]# ls`
`./  ../  cpanel.php  README.TXT  xml.php`

**Comment by fevangelou** [comment]
I'm afraid it's a very tedious process to keep track of changes and adapt per cPanel version so Engintron simply always supports the latest release. If you can upgrade cPanel, these issues will resolve for you.
