### ISSUE TITLE
Site problems after upgrade today

### ISSUE THREAD

**Issue by marion30304** [engintron/engintron#94]
Hello,
Im recieving this error when accessing my site (thru cloudflare):

Error 1000 Ray ID: 27a814e47b910c4d • 2016-02-26 02:04:51 UTC
DNS points to prohibited IP
What happened?
You've requested a page on a website (hitechmarineequipment.com) that is on the CloudFlare network. Unfortunately, it is resolving to an IP address that is creating a conflict within CloudFlare's system.
What can I do?
If you are the owner of this website:
you should login to CloudFlare and change the DNS A records for hitechmarineequipment.com to resolve to a different IP address.

This happened after I upgraded today.

I have 3 ips. It is now resolving to the server Ip and not my dedicated IP for this website. 

These are the new nginx logs:
2016/02/25 19:52:07 [emerg] 15373#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2016/02/25 19:54:03 [error] 15431#0: *4 localhost could not be resolved (3: Host not found), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.0"
2016/02/25 19:59:05 [error] 15431#0: *6 localhost could not be resolved (3: Host not found), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.0"
2016/02/25 20:04:24 [error] 15431#0: *8 localhost could not be resolved (3: Host not found), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.0"

Ive tried enabling and disabling engintron. So close to moving on to next site. Can you advise or perhaps figure out how to roll back to the previous build?

Thanks

**Comment by ImLuke954** [comment]
Read line 16 to 19 under "Edit Your Custom Rules For Nginx". You will get your solution there.

**Comment by fevangelou** [comment]
Make sure Engintron is enabled and that Apache's port under Tweak Settings in WHM is set to 8080 (reading your logs there seems to be a conflict). Now unless CloudFlare has indeed blocked your actual IP for some reason, edit the "custom rules" file under Plugins > Engintron in WHM and in there add your shared and dedicated IPs as indicated by the instructions in that file.

**Comment by marion30304** [comment]
Thanks for help, I missed that part entirely. Works well, again thanks for such a cool module, my db is quite large and before nginix page loads were around 4s now just over 1s average. Awesome!!
Thanks

**Comment by fevangelou** [comment]
That's good to know! I'd really appreciate it if you wrote a review (which could also help others) in the cPanel Apps directory: https://applications.cpanel.com/listings/view/Engintron-Nginx-on-cPanel
