### ISSUE TITLE
Enabble/Disable Micro-Caching via cPanel

### ISSUE THREAD

**Issue by mdazmir** [engintron/engintron#941]
Is it possible for cPanel owner to enable/disable the micro-caching functions via their own cPanel
dashboard similar to the [features](https://support.serverguy.com/portal/kb/articles/how-to-enable-disable-cachewall-varnish-from-my-cpanel-account) that is currently provided by Cachewall?

The reason I'm asking this question is that will micro-caching function cause problem during the website development process? For example, do I as the server administrator have to flush the Nginx cache on behalf of my customer? Please correct me if I'm wrong.

And if Engintron have the feature to enable/disable the micro-caching functions via their own cPanel, they can enable it by themselves once they are done with the development process.

**Comment by fevangelou** [comment]
It's possible now (via custom rules) but the admin of WHM has to manually add the exceptions.

However, what you mention is coming really soon (hopefully by end of November) as part of the Engintron Pro release (a commercial version of Engintron with lots additional features and ongoing support and software updates).

Keep an eye on engintron.com and/or Engintron's social media accounts as I'll announce the new site and offering there.
