### ISSUE TITLE
Wrong dates in log files

### ISSUE THREAD

**Issue by robertmylne** [engintron/engintron#942]
### Issue

When I open a log file from `/var/log/nginx/` that has been compressed from a previous day `access.log-20181009.gz`. It has access records from dates outside that range and is missing some records from dates inside that range.

**First record**
`- - 127.0.0.1 - - [08/Oct/2018:03:15:01 +0000]  "GET /whm-server-status HTTP/1.0" 499 0 "-" "-"`

**Last record**
`www.mywebsite.net - 165.227.113.94 - - [09/Oct/2018:03:45:14 +0000]  "GET / HTTP/2.0" 200 4979 "-" "Mozilla/5.0 (compatible; NetcraftSurveyAgent/1.0; +info@netcraft.com)"`

**Comment by fevangelou** [comment]
Somewhere in your server setup the time is offset. It could be a delay in log processing as well. Is this really a big issue to mention?

**Comment by robertmylne** [comment]
I rely on the dates in the logs files to be correct for an extension I am creating.

**Comment by fevangelou** [comment]
Try setting your server's time to GMT. See if that changes log dates.

What kind of extension are you referring to by the way?

**Comment by robertmylne** [comment]
`
-rw-r-----  1 nginx adm  1214865 Oct 18 03:15 access.log
-rw-r-----  1 nginx adm    41021 Oct 11 03:23 access.log-20181011.gz
-rw-r-----  1 nginx adm    88632 Oct 12 03:26 access.log-20181012.gz
-rw-r-----  1 nginx adm    50925 Oct 13 03:16 access.log-20181013.gz
-rw-r-----  1 nginx adm    53185 Oct 14 03:15 access.log-20181014.gz
-rw-r-----  1 nginx adm    23665 Oct 15 03:22 access.log-20181015.gz
-rw-r-----  1 nginx adm   115924 Oct 16 03:30 access.log-20181016.gz
-rw-r-----  1 nginx adm  1929300 Oct 17 03:35 access.log-20181017
`

**Comment by fevangelou** [comment]
I have no idea how the whole log rotation thing works. If you can read the files, I'm pretty sure you can set date ranges, in any case...
