### ISSUE TITLE
Set X-XSS-Protection header for one domain

### ISSUE THREAD

**Issue by chrisbasham** [engintron/engintron#943]
How can I set the "X-XSS-Protection" header for a particular domain, overriding what is in nginx.conf?

**Comment by fevangelou** [comment]
Edit your custom rules and add the following at the bottom of the file:

```
set $XSS_Protection "1; mode=block"; # Default Engintron setting
if ($host ~ "example.com") {
    set $XSS_Protection "whatever"; # Replace 'whatever' with your custom value for example.com
}
add_header  X-XSS-Protection $XSS_Protection; # Overrides current global setting
```

I'm not directly adding the "add_header" directive in the if block because it will cause problems when Nginx rebuilds its configuration.

Try it and let me know.
