### ISSUE TITLE
Should PHP-FPM be disabled when using Engintron?

### ISSUE THREAD

**Issue by israelcollazo** [engintron/engintron#946]
I have PHP-FPM enabled still from before installing NGINX+Engintron. Should PHP-FPM be disabled? Is there a negative impact having both PHP-FPM and Engintron enabled?

**Comment by urbaman** [comment]
I have both and no issues.

**Comment by fevangelou** [comment]
Nginx (via Engintron) + Apache + PHP-FPM is currently the best performance combo in cPanel. With the right pool usage in PHP-FPM, you don't even need CloudLinux on servers with hundreds of accounts.

**Comment by JayDubinsky** [comment]
It may be a good addition to the docs to have a "Best setup practices guide" as far as what works best together with nginx. Currently there is not much out there on the web about it.

**Comment by fevangelou** [comment]
@JayDubinsky The EA4 profiles I have a is a good start. For everything else, the upcoming Engintron Pro will greatly assist in optimizing a server for performance.
