### ISSUE TITLE
Removed open_basedir patch from EasyApache 4 systems

### ISSUE THREAD

**Issue by Nirjonadda** [engintron/engintron#947]
@fevangelou cPanel Removed open_basedir patch from EasyApache 4 systems from version 76, So now what is Requirements for engintron?

**Comment by Nirjonadda** [comment]
Read more here: https://documentation.cpanel.net/display/76Docs/76+Release+Notes#id-76ReleaseNotes-Removedopen_basedirpatchfromEasyApache4systems

**Comment by fevangelou** [comment]
Since it's still controlled from php.ini (see here: https://documentation.cpanel.net/display/76Docs/PHP+open_basedir+Tweak) just make sure you don't really use it. Although since Engintron now uses cPanel's PHP copy, I don't think it's an issue anymore. Haven't tested recently though.
