### ISSUE TITLE
Cloudflare with FULL SSL?

### ISSUE THREAD

**Issue by rahulmukati** [engintron/engintron#948]
Hello,

I was testing engintron and found its redirecting site using Cloudflare with FULL SSL to server default page.
In Flexible Mode either it gets ERR_TOO_MANY_REDIRECTS or site gets broken. (In WordPress Case)
Any solution to make site run in FULL SSL Mode also?

In my server some users uses Cloudflare with Flexible or FULL  SSL Mode, so what will be best solution for this?

I have added below code in custom_rules for making sites work with Cloudflare & Dedicated IP too without adding block for each domain that needs Dedicated IP.

```
if ($http_cf_visitor ~ '{"scheme":"http"}') {
    set $PROXY_DOMAIN_OR_IP $server_addr;
}
if ($http_cf_visitor ~ '{"scheme":"https"}') {
    set $PROXY_DOMAIN_OR_IP $server_addr;
}
```

**Comment by Cavain** [comment]
Hi @rahulmukati 

Please check following link:
https://github.com/engintron/engintron/wiki/Engintron-&-CloudFlare

**Comment by rahulmukati** [comment]
Hi @Cavain 

I have checked that! My question is what if we want to use Full SSL Mode only?
Like, if we install Engitron on Shared Hosting server than it will create a lot of issues for them who uses Cloudflare with Full SSL Mode. And may of WordPress users use Full SSL Mode. So whats the solution for that?

Thanks

**Comment by fevangelou** [comment]
No issues at all. Did you actually read the link @Cavain gave you?

> If you use SSL via CloudFlare and your domains also have SSL certificates installed on your cPanel server, make sure you choose "Strict SSL" or "Full SSL" inside "Crypto" settings. This way all HTTPS traffic from CloudFlare will be proxied to your Nginx HTTPS port (443).

**Comment by rahulmukati** [comment]
What if user not have SSL installed on domain and only uses Cloudflare with Full SSL Mode? Then it will make Error 1XXX right? So whats the solution for this?

Is it possible to make any settings in Engitron so that it works with both Full and Flexible Mode?

Some sites uses Full SSL, some Flexible and some are directly connected with nameservers. We don't want issue for anyone, is their any way?

**Comment by ddrhost** [comment]
To use FULL MODE, the client must also have an SSL certificate installed on the server. Or use FLEXIBLE MODE without an SSL certificate installed on the server, but it does not always work well.

Install LETS ENCRYPT for free.

**Comment by dws122** [comment]
Another way is to create an Origin CA with Cloudflare. You can then install that certificate (15 year) in WHM for the account.

https://support.cloudflare.com/hc/en-us/articles/115000479507-Creating-and-managing-certificates-with-Origin-CA

Then you don't have to worry about renewing Let's Encrypt quarterly.

NOTE, though, that Cloudflare Origin CA will not provide SSL support in the browse. You must have Cloudflare set to FULL and have the domain cached, using the Orange Cloud in DNS.
