### ISSUE TITLE
Bypass cache!!

### ISSUE THREAD

**Issue by Mello21century** [engintron/engintron#95]
Hello

I have installed engintron on my cPanel server and I need to understand 2 issues that I'm facing

Is there away to bypass nginx cache for certain domain?
What about on certian website account path starting with for example "manager" folder?

Thanks

**Comment by fevangelou** [comment]
You can do lots of things really. And what you ask is of course possible. But this is a customization beyond the scope of the support we provide freely here, as it requires you to edit a few files, so it's not just a one-liner.

If you need commercial assistance you can always email engintron [at] gmail [dot] com.
