### ISSUE TITLE
Engintron with xVarnish

### ISSUE THREAD

**Issue by Cavain** [engintron/engintron#950]
Hello,

I just installed and tested xVarnish with Engintron it works fine on http websites but the websites which have https enabled nginx stop working on them would this be due to ports?

Any help would be appreciated.

**Comment by Nirjonadda** [comment]
@Cavain Do you get fixed this issue? Cachewall (xVarnish) Compatible with Engintron?

**Comment by Cavain** [comment]
Yes, I got it fixed and worked well with Engintron.

**Comment by Nirjonadda** [comment]
Then Please can be sharing this workaround details? So this will help with all Cachewall user. Thanks
