### ISSUE TITLE
peer closed connection in SSL handshake while SSL handshaking to upstream

### ISSUE THREAD

**Issue by sshcli** [engintron/engintron#952]
**Tested with:**
v1.9.1
Build 20180817
(Nginx version: 1.14.0)

**I have hundreds of errors like this in my logs:**
2018/11/05 09:55:52 [error] 4235#4235: *40966 peer closed connection in SSL handshake while SSL handshaking to upstream, client: 191.95.x.x, server: example.com, request: "GET /templates/protostar/js/template.js?3d04b2c49ae097c8cfe41572ab3129fd HTTP/1.1", upstream: "https://69.x.x.x:8443/templates/protostar/js/template.js?3d04b2c49ae097c8cfe41572ab3129fd", host: "example.com", referrer: "https://example.com/?gclid=EAIaIQobChMI7pPF5bO93gIVTudkCh3wngriEAEYASAAEgL4q_D_BwE"

**Comment by fevangelou** [comment]
You'll have to provide actual URLs (internal and referrer) so I can see what's wrong.

**Comment by sshcli** [comment]
Sorry, I can't do it right now, I did uninstall engintron. Maybe in a few months I will install it again.
Sorry for any inconvenience this can cause to you.
