### ISSUE TITLE
connection refused when I installed engintron

### ISSUE THREAD

**Issue by flavioxx** [engintron/engintron#953]
connection refused when I installed engintron

When I install engintron on my dedicated WHM server it gives a connection problem refused when trying to access any site.

Can someone help me?

I had to remove the engintron to get back to normal.

**Comment by ddrhost** [comment]
Hello. Verify that the 8080 and 8443 ports are released on your firewall and have been changed.

Try removing and reinstalling Engintron

**Comment by fevangelou** [comment]
If the firewall does not cause problems to internal traffic on ports 8080 & 8443, there is no need to uninstall & re-install Engintron.
