### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by Easyschools** [engintron/engintron#954]
I am trying to install nginx to use it in for specific subdomains in cpanel. As i have two projects one is laravel and the other in angular. I want to make the laravel works with apache2 as backend and angular which is hosted by node server i want it to be hosted by nginx. I tried to install it using Engintron yesterday but it changed all my domains to use nginx as webserver. is there option that i can do make some folder work with apache2 and other folder with nginx. I have ordered another ip address so i can make apache2 work with ip different than the ip working with nginx. but when i tried to change domain ip address to the new one it is working but all the subdomains can't retrieve data  and says that ip is not configured. Although I have changed the virtual host ip in /var/cpanel/userdata/domain but still no luck. any help?

**Comment by ChristianGabs** [comment]
Hi,

No, because your apache will be swap to other port 8080 you can force to be public IP. I don't see a good idea to play like some website running on apache and some using nginx.

And I don't know why you should go on this path

**Comment by Easyschools** [comment]
Because i have backend based on laravel and send api calls to android.when I changed the whole server to ngingx the android api has fall down and returning invalid characters as it suppose to be json. so i need to make my backend works with apache2 and frontend with nginx

**Comment by ChristianGabs** [comment]
You can use nginx but you must control the header. The most common issue on API's there is chunked_transfer_encoding.

You can control this species in your custom rules for that domain.

**Comment by Easyschools** [comment]
how to do that? would you please guide me

**Comment by ChristianGabs** [comment]
```
if ($SITE_URI ~* "yourdomain.com") {
     chunked_transfer_encoding off;
}
```

This can be add in your custom nginx config. 
**Edit your custom_rules for Nginx**
