### ISSUE TITLE
Brotli for better compression

### ISSUE THREAD

**Issue by salesigniter** [engintron/engintron#956]
is there a way to add brotli to the engintron nginx or have an install option? I saw this: https://github.com/engintron/engintron/issues/712 which is a good guide but I'd like to be able to update engintron/nginx without any extra step - I'm not sure if I build nginx manually if it will update itself automatically anymore with yum updates?

**Comment by fevangelou** [comment]
It won't update automatically. Engintron grabs Nginx directly from nginx.org.

The benefit you'd get by optimizing other parts of the server will be much greater than using Brotli. E.g. proper MySQL/MariaDB optimization will make you think you switched on a new server with triple specs.
