### ISSUE TITLE
Mobile cPanel

### ISSUE THREAD

**Issue by ddrhost** [engintron/engintron#957]
Hello. When accessing Webmail, cPanel or WHM through the subdomain and in the mobile phone, a session error occurs. You are not logged in. When removing the engintron it works normally.

On the computer it works normally. What can it be?

**Comment by silastammerik** [comment]
same happen here. When access using subdomain I can't login.

**Comment by fevangelou** [comment]
If you use subdomains, you force traffic through Nginx, despite Nginx having clear exclusions for the generic subdomains used for cPanel services. So the error occurring after traffic is simply passed over to the built-in cPanel server probably relates to how that 2nd server handles proxied traffic. I always recommend people use subdomains if they want but make sure to redirect them to cPanel ports, in which case no proxying is performed.

**Comment by ddrhost** [comment]
Yes, the problem is that sometimes the client owns the site in Wix or another server and the emails in my server, forcing the use of the webmail by the subdomain.

Is it possible to disable Nginx from webmail by subdomain?

**Comment by fevangelou** [comment]
It's not possible to switch off Nginx for a select domain or subdomain. Nginx binds to ports 80 and 443 for all incoming traffic. What's possible (and what is done already) is for Nginx to pass the traffic un-altered to the backend server (the built-in cPanel webserver).

**Comment by ddrhost** [comment]
Ok. Thank you.
