### ISSUE TITLE
Cloudlinux/cPanel Update Breaks Engintron Error 502 Bad Gateway without HTTPS

### ISSUE THREAD

**Issue by qlpqlp** [engintron/engintron#959]
Hello,

Since last week CloudLinux (V7.5)/CPanel (V76.0.6) Update, most of the websites witouth HTTPS shows Error 502, even after CACHE clean (Engintron PURGE) it shows again the error.

This happen on all servers since last Friday, I have tried to Update/Reenstal Engintron, and still shows the same problem.

This only happens ramdomly after Refresh Shows OK, then anouther Refresh shows error 502Bad Gatway

We had to disable Engintron on all servers to clients be able to acess the website without errors.

Any workaround on this issue?

Thanks in advance.

**Comment by silastammerik** [comment]
same here, but the issue start happen in only one server since yesterday.

**Comment by AnoopAlias** [comment]
check apache error_log and this may be the apache worker process segfaulting on some request
you will see something like 

`[core:notice] [pid 28669:tid 46962071323712] AH00052: child pid 93183 exit signal Segmentation fault (11)`

This is a CloudLinux issue and I was updated that they will release a fix on 15th Nov 2018

(assuming the 502 you have is caused by segfault)

**Comment by qlpqlp** [comment]
Hello,

Could it be also because of this? https://forums.cpanel.net/threads/ea-7980-rewrite-rules-broken-after-latest-ea4-update.640617/
or is only Cloudlinx?

**Comment by qlpqlp** [comment]
Hello,

More investigating and I think it can be also to do with this:

https://documentation.cpanel.net/display/76Docs/76+Release+Notes#id-76ReleaseNotes-PreventcpsrvdfromservingstandardHTTPports

no?

**Comment by chagwood** [comment]
I can confirm that I'm all of a sudden getting "Bad Gateway" errors on my sites.  Engintron error log entires are now filled with:

2018/11/15 22:44:36 [error] 1082#1082: *49 connect() failed (111: Connection refused) while connecting to upstream, client: XXXXXXX, server: SOMEWEBSITE.com, request: "HEAD / HTTP/1.1", upstream: "https://MYSERVERIP:8443/", host: "www.SOMEWEBSITE.com", referrer: "https://www.SOMEWEBSITE.com/"

**Comment by CryptoSiD** [comment]
I have the same issue on CloudLinux 6.10

Also noticed that the "nginx" service file isn't creating in /etc/init.d/
I can't use "service nginx restart anymore"

From cPanel Engintron show "running" but it's not running.

**Comment by ylluminate** [comment]
Just tried to install this on CENTOS 7.5 kvm v76.0.7 without CloudLinux and getting same 502 on all accounts. Trying to figure out a way to uninstall now.

**Comment by qlpqlp** [comment]
Hello,

We have found the issue and here is the fix :)

Cloud Linux bug on EasyApache mod_isapi

https://forums.cpanel.net/threads/cloudlinux-mod_lsapi-httpd-killed-by-sigsegv.641833/

https://www.cloudlinux.com/cloudlinux-os-blog/entry/beta-mod-lsapi-updated-1-41

For us has fixed after beta test update and server reboot :)

Reagards to all :)

**Comment by fevangelou** [comment]
@ylluminate read the docs, it's a one-liner.

@qlpqlp So it's not an Engintron issue.

**Comment by ylluminate** [comment]
Yes, it was simple to uninstall with the command @fevangelou. 

So in my case, I'm not sure if it is related to this particular issue or not, but a reboot doesn't help. 

I'm seeing the following enumerated in red during the installation:

```
Service Error
	(XID 62ub5w) The “httpd” service failed to restart because the restart script exited with an error:

############## Then I see these:
Startup Log
	Nov 18 13:37:09 server.domain.tld systemd[1]: Starting Apache web server managed by cPanel EasyApache...
	Nov 18 13:37:10 server.domain.tld restartsrv_httpd[11096]: AH00112: Warning: DocumentRoot [/home/username/rails_apps/rails-test/public] does not exist
	Nov 18 13:37:10 server.domain.tld systemd[1]: PID file /run/apache2/httpd.pid not readable (yet?) after start.
	Nov 18 13:37:10 server.domain.tld systemd[1]: Started Apache web server managed by cPanel EasyApache.

Log Messages
	[Sun Nov 18 13:37:10.910087 2018] [mpm_event:notice] [pid 11158:tid 46987371168832] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Sun Nov 18 13:37:10.324847 2018] [mpm_event:notice] [pid 11158:tid 46987371168832] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Sun Nov 18 13:37:10.114350 2018] [:notice] [pid 11130:tid 46987371168832] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.
	[Sun Nov 18 13:36:17.870158 2018] [mpm_event:notice] [pid 10772:tid 47879056266304] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Sun Nov 18 13:36:17.653691 2018] [:notice] [pid 10744:tid 47879056266304] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.
	[Sun Nov 18 05:32:19.076432 2018] [mpm_event:notice] [pid 18893:tid 47024933594176] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Sun Nov 18 00:28:12.749268 2018] [mpm_event:notice] [pid 18893:tid 47024933594176] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Sun Nov 18 00:27:59.812589 2018] [mpm_event:notice] [pid 18893:tid 47024933594176] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Sun Nov 18 00:23:16.740064 2018] [mpm_event:notice] [pid 18893:tid 47024933594176] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Sat Nov 17 23:58:48.990273 2018] [mpm_event:notice] [pid 18893:tid 47024933594176] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Sat Nov 17 23:58:43.768973 2018] [mpm_event:notice] [pid 18893:tid 47024933594176] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Sat Nov 17 23:58:43.550658 2018] [:notice] [pid 18865:tid 47024933594176] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.

################## Finally another red message:
httpd has failed. Contact your system administrator if the service does not automagically recover.
Redirecting to /bin/systemctl start nginx.service

```

So I assume something else is going on here.  There is an orange messages that are in the "Startup Log" regarding a rails app that I'm not running at the moment, but doesn't cause Apache any trouble.

Not really seeing any strong indication of a point of failure...

**Comment by fevangelou** [comment]
Well, do read the error.
`Warning: DocumentRoot [/home/username/rails_apps/rails-test/public] does not exist`

This clearly implies a modified Apache file. That's why the restart fails. It's not even remotely related to Engintron.

**Comment by ylluminate** [comment]
@fevangelou Apache restarts fine with that even in there - normally. So why would is it failing now with Engintron? Truly, I can restart Apache 1,000 times and reboot the system w/o issue, but with Engintron it fails.

**Comment by ylluminate** [comment]
So @fevangelou I did some more troubleshooting and digging, even included cPanel support. I did initially resolve the one warning I noted, but still having problems.  Basically there's nothing wrong with Apache from what we can tell and no warnings or errors from Apache or cPanel.

Any thoughts on further troubleshooting? Here's the log output during installation with the red highlighted failures in "Service Error" and after "Log Messages":
```
=== Restarting Apache & Nginx... ===
Service Status

apache_php_fpm restarted successfully.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Restarts are currently deferred.  Waiting and then trying again.
Apache could not be restarted because the deferral lasted too long.
Cpanel::Exception::Services::RestartError
Service Status
	httpd (PassengerWatchdog (cleaning up...)) is running as root with PID 16795 (systemd+/proc check method).

Service Error
	(XID xe9jwf) The “httpd” service failed to restart because the restart script exited with an error:

Startup Log
	Nov 20 23:12:24 server.domain.tld systemd[1]: Starting Apache web server managed by cPanel EasyApache...
	Nov 20 23:12:24 server.domain.tld systemd[1]: PID file /run/apache2/httpd.pid not readable (yet?) after start.
	Nov 20 23:12:24 server.domain.tld systemd[1]: Started Apache web server managed by cPanel EasyApache.

Log Messages
	[Tue Nov 20 23:12:25.531743 2018] [mpm_event:notice] [pid 16521:tid 47387329037376] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Tue Nov 20 23:12:24.949298 2018] [mpm_event:notice] [pid 16521:tid 47387329037376] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Tue Nov 20 23:12:24.728448 2018] [:notice] [pid 16493:tid 47387329037376] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.
	[Tue Nov 20 23:11:32.451481 2018] [mpm_event:notice] [pid 16070:tid 47298977559616] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Tue Nov 20 23:11:32.224976 2018] [:notice] [pid 16042:tid 47298977559616] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.
	[Tue Nov 20 22:37:04.515112 2018] [mpm_event:notice] [pid 12589:tid 48009239376960] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Tue Nov 20 22:30:23.692188 2018] [mpm_event:notice] [pid 12589:tid 48009239376960] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations
	[Tue Nov 20 22:24:09.099200 2018] [mpm_event:notice] [pid 12589:tid 48009239376960] AH00489: Apache/2.4.37 (cPanel) OpenSSL/1.0.2p mod_bwlimited/1.4 Phusion_Passenger/5.3.5 configured -- resuming normal operations

httpd has failed. Contact your system administrator if the service does not automagically recover.
Redirecting to /bin/systemctl start nginx.service
```

**Comment by RedxLus** [comment]
I have this problem too.
Install but not works in cpanel. 
Have error 502

**Comment by lpasquali** [comment]
We are facing this issue too on around 5 servers with cPanel 74.0.11, Cloudlinux 7.5 with latest patches, Engintron 1.9.1, if for some reason I need to take down engintron with ./engintron disable, or in WHM re-enabling it back causes 502 errors, even if vhosts are rebuild, engintron script to update vhosts is re-run,  everything (nginx, apache) is stopped and then started back. Then Apache when put back in front works just fine.

**Comment by mofolo** [comment]
Also getting the same issue and it randomly happens, each time we have to uninstall and re-install engintron to get it to work. This usually happens after a EasyApache update, but it has happened randomly with no changes at all.

I'm seeing this problem.
`...connect() failed (111: Connection refused) while connecting to upstream, client: ::1, server: localhost, request: "GET / HTTP/1.0", upstream: "http://xxx.xx.xx.xx:80/", host: "localhost"`

Isn't upstream supposed to be 8080 after engintron distils Apache? I'm unsure why this happens, but it looks like Apache magically tries to bind back to port 80.

I also see this:
`2019/01/03 21:59:19 [emerg] 2203371#2203371: bind() to 0.0.0.0:80 failed (98: Address already in use)
2019/01/03 21:59:19 [emerg] 2203371#2203371: bind() to 0.0.0.0:443 failed (98: Address already in use)`
