### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Al3xR0** [engintron/engintron#96]
After installing Engitron, the resources are not loaded (css,js and images) on 2 of my websites (the rest are working ok).

If I access directly the resource link I get:

> Internal Server Error
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at webmaster@website.com to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log.
> 
> Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Do you know how to fix this?

**Comment by fevangelou** [comment]
What was it?

**Comment by Al3xR0** [comment]
I disabled a cache plugin on 3 WordPress websites, and 1 website had some Rewrite Rules in the .htaccess related to js and css files ,that I have commented.

Also I did upgrade from apache 2.2 to 2.4, so maybe this was the main issue.

**Comment by fevangelou** [comment]
I think it's the first one. Some plugins may use php to modify headers for
static files. The .htaccess files do not affect a site's behaviour behind
Nginx.
