### ISSUE TITLE
Add more info to wiki page

### ISSUE THREAD

**Issue by Hostert** [engintron/engintron#960]
Hey Guys!

Thank you for your excelent job here.

Today I found an issue after install engintron on my cPanel with CloudFlare. After make everything work, the real IP address are not logged, even with ip.php showing the real IP.

So, I found and issue here containing [this link](https://www.damchey.com/2018/01/how-to-log-real-visitor-ip-when-using-engintron-on-cpanel/).

Basically, all you have to do is edit LogFormat this way:

```
# from
%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"
# to
%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"
```

If you add this directly to your wiki page, will help people to save a lot of time.

Thanks!

**Comment by fevangelou** [comment]
It is already in the wiki https://engintron.com/docs/#/pages/index (last link as shown here https://jmp.sh/cxWfsrh).

**Comment by Hostert** [comment]
@fevangelou Nice! I didn't see the wiki on your site.

Thanks for your answer.
