### ISSUE TITLE
Http2 not Working after AutoSSL (Not Duplicate)

### ISSUE THREAD

**Issue by AbdulJabbarDumrai** [engintron/engintron#962]
I have been hammering my head against the concrete wall just to enable _Http2 Protocol_ in Nginx (Engintron).  When I installed Engintron for the first time, It just ran smooth with H2 protocol enabled and everything was going great but then the nightmare began when AutoSSL performed its rutine Comodo SSL Certificate installation for expired domains since then I am completely down with H2 protocol.

_My Current Installations are_ 

** Engintron with Nginx info**
nginx version: nginx/1.15.6
built with OpenSSL 1.1.1
TLS SNI support enabled
configured with --with-http_v2_module

**OpenSSL Version info**
OpenSSL 1.1.1

**What I have tried so far?**

1) I completely Uninstalled Engintron then reinstalled. (Not working tried for 3 times Stable / Mainline)
2) Again I uninstalled Engintron and installed Nginx from repo (Not Working)
3) I uninstalled Nginx installed from Repo then compiled/installed latest Nginx itself from source code without Engintron and tuned all possible codes to start H2 Protocol (Not Working)
4) Uninstalled Nginx and installed Engintron back once again (Not Working)
5) Installed Engintron from Codeit repo following github issue #437 & #522 & #368. (Not Working) 
6) Checked all Nginx's *.confs files and made Listening to port 443 to server like this in default_https.conf
            server {
                       listen 443 ssl http2;
                       server_name example.com www.example.com
                       ssl_certificate /var/cpanel/ssl/apache_tls/example.com/combined;
                       ssl_certificate_key /var/cpanel/ssl/apache_tls/example.com/combined;
                       include common_https.conf;
}
7) Confirmed that all SSL Certificates and Keys are present at above stated location.
8) Checked if CSF Firewall is causing any issue and added 8443 and 8080 ports for Apache. 
9) All requests going to 443 and response is coming from Nginx. Apache requests are going to 8080 and 8443
10) Chrome Console shows
            Server: Nginx
            Protocol: Http 1.1
            Https is used
11) Engintron is fetching new SSL certificates from AutoSSL. (Experimented by deleting my SSL certs and running AutoSSL).
12) Engintron is working good, shown in WHM and Nginx is working good as Reverse Proxy.
13) Online Http2 Tests shows that  Server supports HTTP/2.0 and ALPN supported. You can check as https://ebig.pk

The only problem is **Why the Heck H2 Protocol is not getting enabled and not showing Http2 in Console???**.

I have read and gone through almost all of issues related to Http2 on Engintron Github repository.

Please Experts have a look at this. I tried everything I new and I could. May be I am missing something. Thank You.

Out of curiosity! what if I have OpenSSL 1.1.1 and Nginx is compiled against OpenSSL 1.0.2K, will that work? Because both OpenSSL versions support Http2.

**Comment by fevangelou** [comment]
Well, did you try LetsEncrypt certificates?

**Comment by AbdulJabbarDumrai** [comment]
No. I did not tried LetsEncrypt because AutoSSL is working good and SSL Certificates from Comodo are created without any problem. And as a side note that I prefer Comodo over Let's Encrypt so, I didn't tried that. And I think that if there was a problem with Comodo, then Engintron should have problem in fetching new certificates but luckily it fetch new certificates to Nginx easily. So, found no solid reason to try this option.

**Comment by AbdulJabbarDumrai** [comment]
Finally by the grace of GOD, I found the problem behind this reason and astounding, the problem was being caused by my personal Antivirus (ESET). It was filtering SSL/TLS traffic. I thought it would be good to mention here so others can be benefited who hammer their VPS.

**Comment by ChristianGabs** [comment]
Good to know
