### ISSUE TITLE
Engintron firewall configuration for CSF

### ISSUE THREAD

**Issue by devteam9200** [engintron/engintron#963]
Hi Team,

I just wanted to firstly say great work. 

Secondly this documentation here:
https://engintron.com/docs/#/pages/Restrict-access-to-ports-8080-&-8443-used-by-Apache-only-for-Nginx

3. Edit /etc/csf/csf.deny (either via terminal or via CSF's WHM app) and append this line:

**tcp|in|d=8080|s=0.0.0.0/0 # Block all connections to port 8080 except those already allowed in csf.allow
tcp|in|d=8443|s=0.0.0.0/0 # Block all connections to port 8443 except those already allowed in csf.allow**

The problem with the above is when user in WHM GUI clicks "Flush All" these will be lost. May I kindly recommend or add the following update:

# Engintron Recommended Settings 
tcp|in|d=8080|s=0.0.0.0/0 # do not delete
tcp|in|d=8443|s=0.0.0.0/0 # do not delete

This way the rules will be permanent and not flushed or lost. 

Thanks Team.

**Comment by fevangelou** [comment]
You're right. Document updated. Thank you.
