### ISSUE TITLE
Webmail subdomain not working?

### ISSUE THREAD

**Issue by ddrhost** [engintron/engintron#965]
When installing Engintron, access to Webmail by subdomain does not work. There are loading crashes, broken CSS, session problems.

How to solve?

**Comment by ddrhost** [comment]
I added the following in custom_rules to force access to the server hostname with HTTPS, solving the problem temporarily. The problem only occurs with subdomain and HTTP.

Is there anything to solve?

At another point, is there anything to redirect only accesses with HTTP and keep HTTPS in client subdomains?

```
if ($host ~* "^webmail\.") {
    return 301 https://$hostname/webmail;
}
if ($host ~* "^whm\.") {
    return 301 https://$hostname/whm;
}
if ($host ~* "^cpanel\.") {
    return 301 https://$hostname/cpanel;
}
```

**Comment by lpasquali** [comment]
Hello
for both http and https, if I log in with username/password to: 
  http[s]://cpanel.domain.tld 
and then go to Mail Accounts and then click on any user webmail link i get redirected to:
  http[s]://webmail.my-cpanel-server-name.tld
while it should be:
  http[s]://webmail.domain.tld
when I analyzed the cookies (curl -I <cpanel-webmail-link>) I saw:
Set-Cookie: roundcube_sessauth=expired; HttpOnly; domain=my-cpanel-server-name.tld; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; port=8080
Set-Cookie: Horde=expired; HttpOnly; domain=.my-cpanel-server-name.tld; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; port=8080
Set-Cookie: horde_secret_key=expired; HttpOnly; domain=.my-cpanel-server-name.tld; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; port=8080
[..]
commenting out:

# proxy_set_header              X-Forwarded-Host $PROXY_FORWARDED_HOST;

in file /etc/nginx/proxy_params_common made webmail working in all the ways it can be reached for a cpanel user and cookies look like:

Set-Cookie: roundcube_sessauth=expired; HttpOnly; domain=cpanel.domain.tld; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; port=8080
Set-Cookie: Horde=expired; HttpOnly; domain=.cpanel.domain.tld; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; port=8080
Set-Cookie: horde_secret_key=expired; HttpOnly; domain=.cpanel.domain.tld; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; port=8080

**Comment by fevangelou** [comment]
Add a custom rule then to reset $PROXY_FORWARDED_HOST to nothing.
```
if ($host ~* "^(webmail|cpanel|whm|webdisk|cpcalendars|cpcontacts)\.") {
    set $PROXY_FORWARDED_HOST '';
}
```
