### ISSUE TITLE
http not loading and http not redirecting to https

### ISSUE THREAD

**Issue by omerekelly** [engintron/engintron#968]
when i visit my website via
http:// it doesn't load but https:// is working fine.

i have tried redirecting http to https:// still not woking

**Comment by azunitexite** [comment]
Also having this problem on all domains. Websites accessed by either no prefix or http:// do not load. Directly accessing https:// works fine

**Comment by jinbatsu** [comment]
yes mee to, redirect from http to https not work, result is Time Out

**Comment by lpasquali** [comment]
sorry guys, did you disabled and then enabled back engintron from command line or WHM before getting this error? if so this might be related to what I wrote in #973

**Comment by danreb** [comment]
Having this problem too.the issue #973  seems to have the fixes.

**Comment by fevangelou** [comment]
If this issue came up after disabling and then re-enabling Engintron, it's fixed in v1.9.3. Upgrade.
