### ISSUE TITLE
Real IP doesn't show

### ISSUE THREAD

**Issue by marklajer** [engintron/engintron#97]
Hello,

We are using CloudFlare.

Real IP header are doesn't set to the real one when using cloud flare.

The adjust header in proxy_params_common is set - but doesn't take effect.
set $X_REAL_IP $remote_addr;
if ($http_cf_connecting_ip) {
    set $X_REAL_IP $http_cf_connecting_ip;
}

**Comment by marklajer** [comment]
Reinstall through WHM worked.

**Comment by fevangelou** [comment]
If you had a version before 1.6.1 you had to manually update the Apache log
format for this to work properly (it's not an Engintron issue per se).

Was that the case?
