### ISSUE TITLE
How do we increase Micro-Cashing Time?

### ISSUE THREAD

**Issue by Cavain** [engintron/engintron#970]
Hello,

I made some customizations but still unable to increase micro-cashing time from 1s to 10s or 1m if possible. How do we do that?
Also I checked this web-hosting providing website: https://www.inmotionhosting.com/ they have x-nginx-cache which hits all the time how is that? due to static content? is it possible to do that on WordPress website ?

Thanks

**Comment by fevangelou** [comment]
Edit proxy_params_dynamic and simply change 1s here https://github.com/engintron/engintron/blob/master/nginx/proxy_params_dynamic#L82 to the value you want. You'll need to re-adjust if you update Engintron.
