### ISSUE TITLE
Disabled cache all domain

### ISSUE THREAD

**Issue by alexnetwork** [engintron/engintron#971]
Hi,
What should I enter to disable all caches for all domains?
I have another question, if I wanted to forward traffic from IP:80 and IP:443 to IP2:8080 and IP2:8443 would be possible? So a forwarding on a different IP. At the cPanel level I already know how to do it, I just need to know where to change forwarding IP instead of 127.0.0.1.

**Comment by fevangelou** [comment]
It's all in the docs: https://engintron.com/docs/#/pages/About-Engintrons-micro-caching-features
