### ISSUE TITLE
FEATURE REQUEST - disable yum system upgrades  from engintron installer.

### ISSUE THREAD

**Issue by lpasquali** [engintron/engintron#974]
Hello all,

every time ./engintron install is run engintron is upgraded to its latest version and system gets upgraded as well. Is there really some benefit to hardcode something not needed to engintron to function properly? 
I guess it's ok to install what it's needed to the software itself (like nginx, stuff to compile apache modules, dependencies etc.). But why I should see a new kernel being upgraded while installing a webserver or why I should wait a lot of time for cagefs to settle after all easy apache php packages get upgraded?

**Comment by fevangelou** [comment]
Cause that's the proper way to do things. If you have a different preference, simply adapt the code to your needs. It's open source.

**Comment by fevangelou** [comment]
Sort answer is, yes, sorry. Engintron is installed in dozens of thousands of cPanel servers worldwide. You're the first to ask that "yum update" is disabled altogether or as an option. If you have specific needs, you may as well just fork Engintron.
