### ISSUE TITLE
Magento 500 error

### ISSUE THREAD

**Issue by dvakerlis** [engintron/engintron#975]
Hello guys I have a problem with engintron and magento 2.2.2 . I get 500 error in all pages when enable engitron. Can you help me with that?

**Comment by fevangelou** [comment]
500 means backend server error. Call the site URL using port 8080 or 8443 (with HTTPS) and see what response Apache is sending out (if any). It could be a broken .htaccess redirect sending the request into a loop.

**Comment by frilogg** [comment]
I run several magento 1.9 and 2..2 installations on behalf of me and also customers with engintron without any problems. So this is not an engintron bug, but probably a local issue.

**Comment by fevangelou** [comment]
Closed as there was no response from the OP.
