### ISSUE TITLE
resolvers should be a variable outside nginx.conf

### ISSUE THREAD

**Issue by lpasquali** [engintron/engintron#976]
Every time Engintron will be upgraded resolvers will be put back to google ones, implying the use of sed or any kind of ansible/puppet/chef/whatever text substitution in config files. Why don't you make it become a parameter, like another file called global_custom_rules you maintainer do not touch as custom_rules, then included somewhere ad hoc in nginx.conf might do it.

**Comment by fevangelou** [comment]
Noted.

**Comment by fevangelou** [comment]
Closing for now. Will be implemented as a feature in the coming updates.
