### ISSUE TITLE
website broke when enable engintron

### ISSUE THREAD

**Issue by applehappy23** [engintron/engintron#978]
hi,

my website broke when newly installed engintron into my whm, i just activate it. the scripts runs all over the place. any help? thanks

**Comment by danreb** [comment]
This seems to be related to #973 , please check that thread. The latest version introduce a bug.

**Comment by fevangelou** [comment]
@danreb The bug was visible if you disabled/enabled Engintron and is now fixed in v1.9.3.

@applehappy23 Saying "the scripts runs all over the place" doesn't make much sense...

**Comment by fevangelou** [comment]
Closing as there is no response from the OP.
