### ISSUE TITLE
Need help integrating Engintron with Prerender

### ISSUE THREAD

**Issue by ittikorns** [engintron/engintron#979]
I need help integrating engintron with prerender server.

It seems like nginx directs the request to @backend block. By debugging the request with the code below the  X-Prerender-Token with value "TEST TEST" is added to the request but no matter what I've tried the `add_header X-Prerender-Token "YOUR_TOKEN"` never appears in the responded request. That's why I've assumed that it passed the @prerender block and went right to @backend.

What I've tried..

    location / {
        add_header X-Prerender-Token "TEST TEST";
        try_files @prerender $uri $uri/ @backend;
    }

    location @prerender {
        add_header X-Prerender-Token "YOUR_TOKEN";
        
        set $prerender 0;
        if ($query_string ~* "nocache_prerender") {
            set $CACHE_BYPASS_FOR_DYNAMIC 1;
            set $CACHE_BYPASS_FOR_STATIC 1;
            set $prerender 1;
        }
        if ($http_user_agent ~* "googlebot|bingbot|yandex|baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator") {
            set $prerender 1;
        }
        if ($args ~ "_escaped_fragment_") {
            set $prerender 1;
        }
        if ($http_user_agent ~ "Prerender") {
            set $prerender 0;
        }
        if ($uri ~* "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|doc|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|ttf|woff|svg|eot)") {
            set $prerender 0;
        }
        
        #resolve using Google's DNS server to force DNS resolution and prevent caching of IPs
        resolver 8.8.8.8;
        
        set $prerender "service.prerender.io";
            rewrite .* /$scheme://$host$request_uri? break;
            proxy_pass http://$prerender;

        if ($prerender = 1) {
            
            #setting prerender as a variable forces DNS resolution since nginx caches IPs and doesnt play well with load balancing
            set $prerender "service.prerender.io";
            rewrite .* /$scheme://$host$request_uri? break;
            proxy_pass http://$prerender;
        }
    }
    ....

**Comment by fevangelou** [comment]
That won't work cause Nginx works in proxy mode. Integrate Prerender with Apache first. Nginx will then know what to cache and what not to cache, which headers to send and so on...

**Comment by fevangelou** [comment]
Closing as there is no response from the OP.
