### ISSUE TITLE
Suggestion for improvement - varying proxy_cache_valid per host

### ISSUE THREAD

**Issue by traderbighouse** [engintron/engintron#980]
Hi,

[this is a suggestion for future improvements, and I think the feature might benefit a lot of cPanel hosting operators]

I have a use case with a shared hosting server with 100+ clients.
the 1 second micro-cache on proxy_cache_valid works fine for dynamic sites.

However, a large number (40-50%) of the websites on the server, could benefit from longer cached PHP/mysql processed data; and ideally the client could choose if they wish to have their micro-cache kept for 1 second, 1 minute, 5 minutes, 15 minutes. (and perhaps a tool to purge the micro-cache data in cPanel, or temporarily disable it for a particular domain)
For example, a Wordpress business brochure site that is updated once every 2 years could have a micro-cache of 15 minutes (on GET/HEAD requests) without affecting the client; and it would reduce the server load substantially as I suspect many clients (40%+) would fit under this configuration well.

I saw this posted: https://groups.google.com/forum/#!topic/openresty-en/qiJcoLW-qAY
More specifically this solution: https://groups.google.com/d/msg/openresty-en/qiJcoLW-qAY/1HLBL0TaFAAJ
could this be a solution to implement multiple values of proxy_cache_valid across different hosts? If so, would it be possible for the client to be able to control this inside cPanel in the future?

As a use-case, I have noticed that a client with cloudlinux and without engintron previously loaded in about 13 seconds. After adding engintron, the site loads in 4.5 seconds. However I am noticing it loads in about 2.5 seconds under varnish. Even though it is a Wordpress site with a contact form, the site itself is pretty static.

Thank you for your time

**Comment by serveroptimizer** [comment]
Agreed! If the micro cache length could be altered per domain in the plugin menu or elsewhere in cpanel accounts for individual sites this would make a very useful addition.
