### ISSUE TITLE
All home pages down

### ISSUE THREAD

**Issue by fogunkoya** [engintron/engintron#983]
All my home pages are down. The rest of the websites work ok but all the home pages are down. I have uninstalled and reinstalled nginx. 

What I mean is index.php always leads to the Test Page. OS is Amazon AMI
All internal pages are served correctly. 

I can put in a temporary fix by manually adding root /path/to/home/ for each virtual host. This is overwritten regularly. Only fix for now is to either remove engintron or to remove permissions for changes to default_https.conf so the manual fix is permanent, then add the configs manually for any new domains added.

**Comment by fevangelou** [comment]
Amazon uses NAT, so Nginx cannot use external DNS to resolve the internal IPs. Either map the internal IPs  per domain(s) using "custom rules" or change the DNS resolvers in /etc/nginx.conf to point to Amazon's internal DNS.

**Comment by fevangelou** [comment]
Closing as there is no response from the OP.

**Comment by fogunkoya** [comment]
This is something that worked previously and suddenly all home pages went down. Only solution I have now is to remove engintron
