### ISSUE TITLE
micro-caching [user2 gets ip from user1]

### ISSUE THREAD

**Issue by Telematica1** [engintron/engintron#985]
Hello everybody,

If you call the variable $ _SERVER ['REMOTE_ADDR'] in a browser, USER2 (locally separated),
who calls the same URL as USER1, gets the IP address of USER1.
We were able to do the same with "cookie-variables ", which can lead to customer data being exchanged at webshops.

Steps to reproduce:
Video description: https://anx.io/VI6a3

Ok, we know now, that the reason ist the micro-caching function. We already set it off temporarily with the "set $CACHE_BYPASS_FOR_DYNAMIC 1;" command, but we're searching for a better solution. 

Has anyone already had similar experiences? Is it possible to optimize the rules (proxy_params_dynamic) so that this can not happen? Thank you in advance!

**Comment by fevangelou** [comment]
Caching is a complex issue. But it's entirely up to the app to properly implement it.

You can use cookies or HTTP headers to instruct Nginx NOT to cache GET requests (when a logged in user browses a site). See how the rules are for common CMSs and either add yours there or simply use the names of these rules in your app.
