### ISSUE TITLE
Custom rules or default_http.conf for each sub domain / domain

### ISSUE THREAD

**Issue by noochthemooch** [engintron/engintron#986]
Is there any way to accomplish this? I need to add a few rules for a sub domain however I for the life of me cannot find a seperate config that will allow me to. 

The problem I have is 2 custom rules.

1. This is code for my subdomain

    location /videos/ {
        root /home2/v1.example.com/public_html;
        internal;

        location ~* .*\.mp4 {
            mp4;
        }
    }

2. This is code for main domain.

    location /content/videos/ {
        root /home/example.com/public_html;
        internal;

        location ~* .*\.mp4 {
            mp4;
        }
    }

If both are added to the custom rules or the default config then the sites 404 how can I get around this?

**Comment by fevangelou** [comment]
Don't do that. It won't work.
