### ISSUE TITLE
cloudflare redirect

### ISSUE THREAD

**Issue by chilledguru** [engintron/engintron#988]
i have single IP on my vps and have included my IP in the following block:

set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX"; # Use your cPanel's shared IP address here

now ...i am not sure which should i comment in the following block so traffic can redirect to cloudflare ssl

 set $redirToSSL "";
 if ($http_cf_visitor ~ '{"scheme":"http"}') {
     set $redirToSSL "on";
 }

 if ($host ~ 'domain-to-exclude-from-redirect.com') {
     set $redirToSSL "off";
 }
 if ($redirToSSL = "on") {
     return 301 https://$host$request_uri;
}

**Comment by fevangelou** [comment]
Setting `set $PROXY_DOMAIN_OR_IP "XXX.XXX.XXX.XXX"; ` is just fine.

**Comment by chilledguru** [comment]
thank you for the reply. i am also facing nginx waiting issue. see the image.

http://prntscr.com/magvaj

**Comment by fevangelou** [comment]
This probably means Apache takes too long to respond to Nginx's requests. Check my optimization guides in the Engintron Docs.

**Comment by chilledguru** [comment]
yes, i applied that but still issue. can you advise if i can load all traffic on nginx and bypass apache totally.

also my site is behind cloudflare.

**Comment by fevangelou** [comment]
You can't do that with Engintron. Try this instead: https://applications.cpanel.net/listings/view/XtendWeb-Nginx-Cluster-Control/showAsListingCategory:Web-Server-Alternatives

**Comment by chilledguru** [comment]
> 
> 
> You can't do that with Engintron. Try this instead: https://applications.cpanel.net/listings/view/XtendWeb-Nginx-Cluster-Control/showAsListingCategory:Web-Server-Alternatives

Thank you for your valued time and continuous prompt support.

**Comment by fevangelou** [comment]
You're welcome.
