### ISSUE TITLE
cPanel now says "nginx FAILED"

### ISSUE THREAD

**Issue by BackyardVoyager** [engintron/engintron#989]
Hello,

I am installing Engintron on CentOS 7 with the latest cPanel version. So far everything works fine, but I get this email from cPanel telling me nginx has FAILED.

![load](https://user-images.githubusercontent.com/45982355/50566071-690c7d80-0d03-11e9-94ca-1a2b24ff7f66.PNG)

**Comment by BackyardVoyager** [comment]
![80](https://user-images.githubusercontent.com/45982355/50566188-b9d0a600-0d04-11e9-92b2-fc18d70d331b.PNG)
Is this correct?

**Comment by pmjcreations** [comment]
The Apache SSL port should be **0.0.0.0:443**, not 0.0.0.0:8443.

**Comment by mofolo** [comment]
> The Apache SSL port should be **0.0.0.0:443**, not 0.0.0.0:8443.

Are you sure? Isn't NGINX supposed to bind to 443 and then pass on to Apache at 8443?

**Comment by mofolo** [comment]
I found that line 20 in **default.conf** was setting to this:

`set $PROXY_TO_PORT 80;`

I change it to 
`set $PROXY_TO_PORT 8080;`

And everything worked as expected.

For some reason after doing anything on WHM that would do a httpd.conf update, something would happen where both Apache and Nginx would want to bind to 80 or 443 and break.

**Comment by BackyardVoyager** [comment]
So in WHM with Apache, should that be 80/443 or 8080/8443? 
    	
    	

    	Get Outlook for iOS
    
  




On Tue, Jan 8, 2019 at 3:47 PM -0500, "Moe" <notifications@github.com> wrote:












I found that line 20 in default.conf was setting to this:


set $PROXY_TO_PORT 80;


I change it to

set $PROXY_TO_PORT 8080;


And everything worked as expected.


For some reason after doing anything on WHM that would do a httpd.conf update, something would happen where both Apache and Nginx would want to bind to 80 or 443 and break.

**Comment by mofolo** [comment]
Without NGINX, Apache should 80/443

With NGINX enabled, Apache should be 8080 and 8443

Make sure you also change `set $PROXY_TO_PORT 8080;` in your nginx default.conf
This Port number should match up to the Apache port number.

**Comment by pmjcreations** [comment]
> > The Apache SSL port should be **0.0.0.0:443**, not 0.0.0.0:8443.
> 
> Are you sure? Isn't NGINX supposed to bind to 443 and then pass on to Apache at 8443?

Oops, my bad. I am not sure now as I have uninstalled Engintron long time back.

**Comment by fevangelou** [comment]
@mofolo The disable/enable option in v1.9.2 had issues which are fixed in 1.9.3. This is what probably left the wrong port number in "default.conf".

**Comment by mofolo** [comment]
Hey @fevangelou 
I upgraded to 1.9.3 and changed one of our sites on the MultiPHP Manager and the same issue appeared.

I had to change the Apache Port and the Default.conf and restart Apache + Nginx to get it working again.

**Comment by fevangelou** [comment]
Probably a leftover state. Please open a new issue if this persists.
