### ISSUE TITLE
Upgraded to WHM 76.0.15

### ISSUE THREAD

**Issue by webaholicsteam** [engintron/engintron#992]
New version of WHM is only change i can think of, but enigntron no longer works, gives "ERR_EMPTY_RESPONSE" when enabled. sometimes it gives 502 nginx error, but ultimately does not work like it did pre 76.0.14

**Comment by webaholicsteam** [comment]
fixed it, not sure how, just cleared out custom ngnix rules and restarted firewall and about every other services

**Comment by lpasquali** [comment]
Did you disable Engintron bbefore upgrading?

**Comment by teenhype902102** [comment]
I'm having the same problem after WHM updated. Engintron is disabled for now until I can find a fix. =/

**Comment by fevangelou** [comment]
The issue in @webaholicsteam case seems to be their custom rules (unless Apache took more time to restart after the upgrade). In any case, check the logs folks.

I've had no issues on the servers I manage for the record...
