### ISSUE TITLE
Cloudflare SSL off - Just SSL Installed on Server

### ISSUE THREAD

**Issue by Cavain** [engintron/engintron#994]
Hello,

I've disabled Cloudflare SSL and just wanted to use my server SSL with Cloudflare. I didn't found any documentation related to this [Engintron-&-CloudFlare](https://engintron.com/docs/#/pages/Engintron-&-CloudFlare). How should I do that?

Thank you!

**Comment by fevangelou** [comment]
You don't need to do anything really. It just works.

**Comment by Cavain** [comment]
@fevangelou It won't work for me. I made some experiments on my own but that didn't workout for me.
