### ISSUE TITLE
wp-login.php

### ISSUE THREAD

**Issue by ddrhost** [engintron/engintron#997]
Is there something to limit access to wp-login.php and block attacks and bruteforce?

**Comment by ddrhost** [comment]
The best way would be to configure ratelimit in Nginx. It's possible? Does Engintron support?

**Comment by fevangelou** [comment]
It's possible if you implement it on your own within Engintron.

**Comment by fevangelou** [comment]
See this as well: https://github.com/engintron/engintron/pull/925
