### ISSUE TITLE
Moving to Engintron and LITESPEED

### ISSUE THREAD

**Issue by sitedart-studio** [engintron/engintron#999]
Have been quite impressed with Engintron, so I am looking to make a major move on a large in production server.

What caveats or issues will I find when I install Engintron and then remove Litespeed? Any gotchas? Remove Litespeed before installing?

thank you (ps: great product!)

**Comment by fevangelou** [comment]
You'll need to switch to Apache first and then install Engintron. Test it and if you like it you can then remove LiteSpeed. You may only need to configure Engintron for CloudFlare. In any case, it's all in the Engintron Docs: https://engintron.com/docs
